### ISSUE TITLE
ARM64

### ISSUE THREAD

**Issue by be5invis** [d2phap/ImageGlass#1000]
### Is your feature request related to a problem? Please describe.
The current ImageGlass only targets X86 and X64, lacking ARM64 support. As .NET6 adding ARM64 support for WinForm, it is possible to support ARM64 platform as well.

### Describe the solution you'd like
* Migrate to .NET 6
* Target ARM64

### Describe alternatives you've considered
Current ARM64 Windows support running x86 application through emulation, but the performance will be greatly reduced due to emulating a JIT language.

**Comment by d2phap** [comment]
Thanks @be5invis 
Migration to .NET 6 is planned for v9.0 which will be released in 2022

**Comment by be5invis** [comment]
@d2phap Not sure whether WinForms have plans to backport A64 support to .NET 5. WPF will do that: https://github.com/dotnet/wpf/issues/1817.

**Comment by namoen0301** [comment]
I build ImageGlass v9 on windows arm64 successfully, how about provide arm64 version of ImageGlass? @d2phap

**Comment by d2phap** [comment]
You can try the ARM64 release of [ImageGlass 9.0 RC](https://github.com/d2phap/ImageGlass/releases/tag/9.0.6.1008) now, it's built against .NET8.

Note that, I don't have ARM device to test.

**Comment by SituChengxiang** [comment]
![image](https://github.com/d2phap/ImageGlass/assets/52872757/66a03b8c-06e8-433c-8907-cda86b116158)
An Error On ARM Platform. I'm using Windows11 on Snapdragon (TM) 8cx Gen 2 ,OS version 22635.3139  
- Error details:  
ImageGlass.Base: Method 'get_Interlace' in type 'ImageMagick.MagickSettings' from assembly 'Magick.NET-Q16-HDRI-OpenMP-arm64, Version=13.4.0.0, Culture=neutral, PublicKeyToken=2004825badfa91ec' does not have an implementation.  
at ImageGlass.Base.Photoing.Codecs.PhotoCodec.LoadAsync(String filePath, CodecReadOptions options, ImgTransform transform, Nullable'1 token)
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)

**Comment by d2phap** [comment]
@SituChengxiang 

Can you help to verify if these 2 builds work for you?

[ImageGlass_9.0.10.201_arm64_1.zip](https://drive.google.com/file/d/1fpmH95vQBQNAnX-sKAQTBteNekEqkGhl/view?usp=sharing)

[ImageGlass_9.0.10.201_arm64_2.zip](https://drive.google.com/file/d/1XwMiJr_CdPbu1n6d3e0PPJ7hy8IBn1Sx/view?usp=sharing)

**Comment by SituChengxiang** [comment]
Thanks for replying, however…… neither  build arm64_1 nor arm64_2 work well.  
I remember that the 9.0 RC version is able to run.  
![image](https://github.com/d2phap/ImageGlass/assets/52872757/b09208e3-fa66-4cb7-a9ce-cc4053202ef1)

ImageGlass Kobe v9.0.10.201 (64-bit, .NET 8.0.1)  
Magick.NET Q16-HDRI-OpenMP arm64 netstandard21 13.4.0  

- Error details:

ImageGlass.Base: Method 'get_Interlace' in type ImageMagick.MagickSettings' from assembly 'Magick.NET-Q16-HDRI-OpenMP-arm64, Version=13.4.0.0,
Culture=neutral, PublicKey Token=2004825badfa91ec' does not have an implementation.

at ImageGlass.Base.Photoing.Codecs.PhotoCodec.LoadAsync(String filePath, CodecReadOptions options, ImgTransform transform, Nullable'1 token)
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)

（Both reported that, please ignore any defensive or improper expression, English is not my native language).
