### ISSUE TITLE
.fax files (tiff files with just a different extension)

### ISSUE THREAD

**Issue by wildpa** [d2phap/ImageGlass#1007]
### Is your feature request related to a problem? Please describe.

I have a lot of .fax files, created by a scanning software,

### Describe the solution you'd like
It would be nice if ImageGlass could just open .fax files like a .tiff file.

### Describe alternatives you've considered
 i could rename them all to .tiff, then ImageGlass could open them, but this would entail changing all the paths in a database too.
Or i could use another Software for .fax files
I tried reactivating the old windows photo viewer, but this will only display the first page of a tiff.

### Additional context
Sadly MS seems to have removed all onboard capabilities to open .fax files.

**Comment by d2phap** [comment]
Hi @wildpa 

If IG opens it after you rename to .tiff, you can add `.fax` extension to IG by:
- Open Settings > File Type Associations
- Click on Add... button
- Type `.fax`, and click OK
- Enjoy

**Comment by wildpa** [comment]
Oh wow, thank you, i somehow didn't see that option...
