### ISSUE TITLE
Webp Image preview

### ISSUE THREAD

**Issue by Happyclem** [d2phap/ImageGlass#1008]
I would really appreciate to be able to have **preview of my webp images without opening them** :)

![2021-04-09_153005](https://user-images.githubusercontent.com/65565485/114187581-aecf3c00-9937-11eb-9818-1b9689e786df.png)

**Comment by fire-eggs** [comment]
ImageGlass is not responsible for Windows Explorer preview.

You will have to investigate other options. For instance, [Icaros](https://shark007.net/forum/Thread-New-Release-3-2-0-Final) apparently can provide webp preview.

**Comment by d2phap** [comment]
You can try https://sourceforge.net/projects/sagethumbs/ as well

**Comment by huangwb8** [comment]
Obviously, "ImageGlass + Icaros" is the best choice for most users (ฅ´ω`ฅ)

**Comment by Hunanbean** [comment]
> Obviously, "ImageGlass + Icaros" is the best choice for most users (ฅ´ω`ฅ)

Why do you consider this obvious?
