### ISSUE TITLE
Installation doesn't ask for admin password, error message

### ISSUE THREAD

**Issue by saucefrog** [d2phap/ImageGlass#101]
I have two accounts on my Windows 7 system, admin and user. When I'm logged in as user and want to install new software, I'm usually asked to type in the admin password through UAC.

Imageglass doesn't ask that. It assumes we are logged in as admin and the installation then quits with an error message not having write permission to the program files folder.

Please fix this.

**Comment by d2phap** [comment]
This is fixed in the upcoming version
