### ISSUE TITLE
Upgrade to 8.1.4.18 is broken

### ISSUE THREAD

**Issue by iDm1** [d2phap/ImageGlass#1014]
### System information:
 - Windows OS version:  Windows 10 x64
 - ImageGlass version: 8.0.12.8

### To Reproduce
1. Download ImageGlass_8.1.4.18_x64.msi
2. Start ImageGlass_8.1.4.18_x64.msi

### Actual behavior:
Upgrade fails with the message: "Another version of this product is already installed. Installation of this version cannot continue. To configure or remove the existing version of this product, use Programs and Features in the Control Panel."

### Expected behavior:
Upgrade should work.

**Comment by d2phap** [comment]
Please download again, I fixed the upgrading issue with MSI installer for x64.
Thanks!
