### ISSUE TITLE
Switching fullscreen and back moves window to primary monitor

### ISSUE THREAD

**Issue by gunters63** [d2phap/ImageGlass#1015]
### System information:
 - Windows OS version: 10
 - ImageGlass version:  8.1.4.18

### To Reproduce
1. Move Imageglass window to secondary monitor
2. Press F11 for fullscreen
3. Press F11 for switch back to windowed mode

### Actual behavior:

4. Imageglass window gets moved to primary monitor 

### Expected behavior:

4. Imageglass window restores position, size AND monitor

**Comment by d2phap** [comment]
This issue is fixed in [v9.0 beta 2](https://github.com/d2phap/ImageGlass/releases/tag/9.0.2.904).
