### ISSUE TITLE
Show checkerboard background for transparent gifs

### ISSUE THREAD

**Issue by rubenguip** [d2phap/ImageGlass#1017]
### Is your feature request related to a problem? Please describe.
For gif images that have alpha, would it be possible to add an option to display the transparency as a checkerboard background by default? As it is today, when I open a gif image and select to scale to fit or another such option there is no way to know where is the border of the image.

### Describe the solution you'd like
Option to display the transparency as a checkerboard background 

### Describe alternatives you've considered
I guess only showing the image border would also work.

### Additional context
Gifs like this:
https://i.stack.imgur.com/gN4HK.gif

Link to the original image: 
https://stackoverflow.com/questions/43219681/glitchiness-when-i-add-transparency-to-a-gif-and-convert-it-to-webm

![gN4HK](https://user-images.githubusercontent.com/82772484/115154135-b84f5700-a04f-11eb-9db3-a61545935383.gif)
![001 (2)](https://user-images.githubusercontent.com/82772484/115154142-bf766500-a04f-11eb-8eca-d4d26ee92eb6.gif)

**Comment by fire-eggs** [comment]
Did you try the 'B' command (draw checkerboard background)?  If enabled, it will stay enabled across ImageGlass invocations.

If you want to be certain of the image edge, you can use the option 'Display checkerboard only in the image region" setting - under Settings / General.

**Comment by fire-eggs** [comment]
Works as designed.
