### ISSUE TITLE
Opening an image pops up the message "Reached the first image" and only shows a blank screen until you go prev/next.

### ISSUE THREAD

**Issue by SelfDestructor** [d2phap/ImageGlass#1019]
### System information:
 - Windows OS version: Windows 10 Pro 20H2 19042.685
 - ImageGlass version: 8.1.4.18

### To Reproduce
1.  Double click on any image with ImageGlass set as default.
2.  See the message "Reached the first image" and just a blank screen.
3. Go to the next or previous image and then back again and the image shows up correctly.

### Actual behavior:
Every time I open an image, no matter what file format (jpg, png, gif, heic) it just shows up blank.

### Expected behavior:
When opening an image it should appear in ImageGlass. This worked before updating to 8.1.4.18

### Screenshots:
Launching ImageGlass directly with the welcome image: https://i.imgur.com/KGzj4JL.png

![image](https://user-images.githubusercontent.com/3154213/115170345-01a4b280-a0f3-11eb-8b44-3f7ca9d37aa9.png)

**Comment by fire-eggs** [comment]
Occurs only when "loop back to beginning" setting is OFF.

If there is only one image in the folder, next / prev will not "recover".

**Comment by SelfDestructor** [comment]
I used the 64-bit installer.

I had loop back option enabled from the previous version. Toggling it off and on again makes images show up as expected on launch.

**Comment by d2phap** [comment]
> Toggling it off and on again makes images show up as expected on launch.

It seems that there was a problem in `igconfig.xml` file while updating new version. 🤔

**Comment by SelfDestructor** [comment]
A problem in my existing config, or in general? I run daily backups so here is my config from 2 days ago, before I updated just in case:
[igconfig.xml.txt](https://github.com/d2phap/ImageGlass/files/6334133/igconfig.xml.txt)

**Comment by CrBoysen** [comment]
same problem here

**Comment by fire-eggs** [comment]
Pretty sure this is a bug. I ran IG8.1 from scratch (not an upgrade) and saw the described behavior.

**Comment by fire-eggs** [comment]
Additional behavior:
1. Run imageglass (i.e. do not double-click an image to run ImageGlass)
2. Make sure "Loop back" option is OFF
3. Use File/Open to open a file.

Note at this point that the toast message which appears is "Last image has been reached" [not "first image"]!

**Comment by SecondBunny** [comment]
> 
> 
> I used the 64-bit installer.
> 
> I had loop back option enabled from the previous version. Toggling it off and on again makes images show up as expected on launch.

This doesn't work for me. Only by keeping it on does it work.

**Comment by SelfDestructor** [comment]
I didn't test it with the option turned off as I prefer to have it on. Turning it off causes the bug to happen on my end too.

**Comment by d2phap** [comment]
Shipped the fix to IG Moon, https://imageglass.org/moon
