### ISSUE TITLE
"Reached first image" state stops animated GIF from playing

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#1020]
### System information:
 - Windows OS version: 7
 - ImageGlass version: 8.1

### To Reproduce
1. Load a folder of images. The first/only image should be an animated GIF
2. Note: "Loop back viewer" setting should be OFF
3. Note first image in list is animated and playing.
4. Try to go "previous": the "first image reached" toast message appears

### Actual behavior:
The animated image stops playing, and does not resume even after the toast message disappears.

### Expected behavior:
The animated image should continue playing.

### Additional context:
See issue #1019

**Comment by d2phap** [comment]
Shipped the fix to IG Moon, https://imageglass.org/moon

**Comment by fire-eggs** [comment]
Hey, @d2phap - the latest Moon release (4/20) looks too early to have this fix - did you update the Moon page?

**Comment by d2phap** [comment]
Hmm, there should be v8.1.4.25, I will upload again later

**Comment by d2phap** [comment]
I re-uploaded

**Comment by fire-eggs** [comment]
Thanks, I see it, maybe it was my browser cache???

**Comment by d2phap** [comment]
I think because the Hosting service provider was upgrading IG's host, and they used the old backup to restore it.
