### ISSUE TITLE
Cannot convert from WEBP to PNG after upgrading to 8.1.4.18

### ISSUE THREAD

**Issue by joekrie** [d2phap/ImageGlass#1021]
### System information:
 - Windows OS version: Windows 10 Pro 19042.928
 - ImageGlass version: 8.1.4.18 x64

### To Reproduce
1. Download https://upload.wikimedia.org/wikipedia/commons/a/a1/Johnrogershousemay2020.webp
2. Open WEBP file in ImageGlass
3. Save as PNG (File > Save image as...)
4. Open PNG in ImageGlass

### Actual behavior:
Invalid PNG file is generated, and when you open in ImageGlass you get this error:
ImageGlass cannot open this picture because the file appears to be damaged, corrputed or not supported. Magizk.NET-Q16-OpenMP-x64: improper image header `{path to img}' @ error/ipl.c/ReadIPLImage/232

### Expected behavior:
Saves a valid PNG file

### Screenshots:
Error:
![image](https://user-images.githubusercontent.com/6656882/115328038-94763900-a155-11eb-809e-4910877c662e.png)
Invalid image:
![Johnrogershousemay2020](https://user-images.githubusercontent.com/6656882/115328175-c5ef0480-a155-11eb-82de-7f2895466486.png)

### Additional context:
Saving WEBP to JPG or BMP also generates invalid file, as does saving PNG to JPG.

**Comment by d2phap** [comment]
I think this issue is ~due to Magick.NET~, I will investigate the problem.
For temporary solution,
- you can press <bkd>Ctrl+C</kbd> to copy the image data to clipboard,
- then press <bkd>Ctrl+D</kbd> to paste this data to ImageGlass, 
- after that, you can press <bkd>Ctrl+S</kbd> to save the webp to png

**Comment by d2phap** [comment]
Fixed this issue in the latest build of IG Moon, not due to Magick.NET lib:
https://imageglass.org/moon
