### ISSUE TITLE
Japanese language archive is broken

### ISSUE THREAD

**Issue by ghost** [d2phap/ImageGlass#1023]
### System information:
 - Windows OS version: Windows 10 x64
 - ImageGlass version: N/A

### To Reproduce
1. Download japanese language archive from <https://imageglass.org/language/download/ja>
2. Unzip `ja.zip`

### Actual behavior:
I can not unzip `ja.zip`.

### Expected behavior:
I will get language files.

### Screenshots:
None

### Additional context:
None

**Comment by fire-eggs** [comment]
Yup, it's empty!

Japanese.iglang can be found in the 8.0.12.8 branch but not the 8.1.  You can try the [8.0 version](https://github.com/d2phap/ImageGlass/blob/8.0.12.8/Setup/Assets/Languages/Japanese.iglang) but off-hand I don't know what new strings were added.

**Comment by ghost** [comment]
Okay, I will try the 8.0 version.
Thank you very much.

**Comment by fire-eggs** [comment]
I'm reopening because I think the website should provide the 8.0 version at least, not an empty zip.

**Comment by fire-eggs** [comment]
I see 10 new strings added in 8.1, mostly related to Zoom Optimization. So the 8.0 language pack is "pretty good".

**Comment by d2phap** [comment]
There is an issue with CrownIn the service that I'm using for localization.
I'm contacting them for the fix.

**Comment by d2phap** [comment]
The issue is fixed, you can download now!
Thanks
