### ISSUE TITLE
Picture switching problem

### ISSUE THREAD

**Issue by xiaoxiang01a** [d2phap/ImageGlass#1025]
### System information:
 - Windows OS version: Windows 10 Pro 19041.928
 - ImageGlass version: 8.1.4.18 x64
### To Reproduce
- About 3MB picture files
1. Put multiple 3MB of image file into the same folder
2. open one of the pictures
3. buttons<'←'> or <'→'> to switch, the obvious pausing (more obvious than Win10 picture viewer )
- About 10KB picture files
1. Same as above just Replace with small files  and ‘载入中’ in black appears
### Expected behavior:
1. Big files switching reduces snap
2. In the old version, the switching of small files is not stuck
![Snipaste_2021-04-22_20-18-53](https://user-images.githubusercontent.com/73389963/115715557-d5b35680-a3aa-11eb-84c1-12d9cb18fd35.png)

**Comment by d2phap** [comment]
This issue is fixed. ImageGlass Moon v9.0 beta 1 has big improvement for fast switching images. You can press and hold Left/Right arrow button to feel:
https://github.com/d2phap/ImageGlass/releases/tag/9.0.1.514.

If the file is still being loaded after 1.5 second, the loading message will appear.
