### ISSUE TITLE
Rotating files and saving them causes corruption

### ISSUE THREAD

**Issue by Ares9323** [d2phap/ImageGlass#1033]
### System information:
 - Windows OS version: 10 21H1
 - ImageGlass version: 8.1.4.18_x64 PORTABLE

### To Reproduce
1. Open an image
2. Rotate it (with the "save after rotate" option enabled)
3. Image is corrupted and no longer readable

### Actual behavior:
Sometimes I get the error "Unable to save image... Path/of/file.png"
![image](https://user-images.githubusercontent.com/46932745/116491968-6900f600-a89b-11eb-88e4-2ab80f261d49.png)

Other times the image gets corrupted without the error and shows this 
<img width="651" alt="Error after rotation" src="https://user-images.githubusercontent.com/46932745/116491891-348d3a00-a89b-11eb-8705-0adc386adbc5.png">

Problem encountered with .jpg and .png files, not tried other formats, with version 8.0 works fine 
(I rolled back to it but I felt the need to report because I would have lost many files if they weren't in onedrive)
After some time could happen that the corrupted image can become the same picture of the previous one in the folder (really strange bug)

### Expected behavior:
Rotate and save the file

### Additional context:
I attach here two files that I used to reproduce the error, as you can see here the image "TheFirstTree_ending.png" first gets corrupted by rotation, then become like the other one after some seconds.
![image](https://user-images.githubusercontent.com/46932745/116492090-aebdbe80-a89b-11eb-9352-aa7e6bdf41ae.png)

Original pictures I backupped before rotating
[Pictures.zip](https://github.com/d2phap/ImageGlass/files/6395785/Pictures.zip)

Corrupted picture
[Corrupted.zip](https://github.com/d2phap/ImageGlass/files/6395794/Corrupted.zip)

**Comment by d2phap** [comment]
Can you try the latest IG Moon (https://imageglass.org/moon)?
This bug  is similar to #1021.

The official release will be shipped in a few weeks.

**Comment by Ares9323** [comment]
![image](https://user-images.githubusercontent.com/46932745/116519804-34f4f780-a8d2-11eb-85c2-865f6db810e0.png)

Just tried with the latest Moon, still corrupted but with different error

**Comment by d2phap** [comment]
Fixed this bug in IG Moon: https://imageglass.org/moon
