### ISSUE TITLE
BUG: Settings not saved when using AutoUpdate 0

### ISSUE THREAD

**Issue by Loakii** [d2phap/ImageGlass#1034]
### System information:
 - Windows OS version: Windows Server 2016 10.0.14393 Build 14393
 - ImageGlass version: 8.1.4.18

### To Reproduce
1. Make programdir nonwriteable for users
2. Create igconfig.admin.xml in programdir with AutoUpdate 0
3. Start ImageGlass as user
4. Settings wont be saved (should be saved in %appdata% but it doesn't save anything)

### Actual behavior:

When defining AutoUpdate 0 in igconfig.admin.xml no settings are being saved

### Expected behavior:

Settings being saved when disabling AutoUpdate in igconfig.admin.xml

### Screenshots:

N/A

### Additional context:

igconfig.admin.xml content
```
<ImageGlass>
  <Configuration>
    <Info description="ImageGlass Configuration file" version="7.5" />
    <Content>
      <Item key="AutoUpdate" value="0" />
    </Content>
  </Configuration>
</ImageGlass>
```

When creating %AppData%\ImageGlass beforehand it works as intended.

**Comment by Loakii** [comment]
For now using a script when launching that creates the folder %AppData%\ImageGlass

**Comment by d2phap** [comment]
Thanks @Loakii 
Probably duplication of #689
