### ISSUE TITLE
Fully fullscreen mode?

### ISSUE THREAD

**Issue by R-a-p-o-l-a-s** [d2phap/ImageGlass#1035]
Unless I have missed something, seems like there's no way to display an image in full screen without the top bar? Excluding slideshow, but that's not the most usable solution, anyway. It's a very needed thing and I'm surprised to see it missing, and hope to see it added.

**Comment by d2phap** [comment]
You can press <kbd>T</kbd> to hide the tool bar. Full screen mode is to remove the window frame, and expand app's size to fit the screen, including Taskbar.

**Comment by d2phap** [comment]
You can find the options in Settings > Image > Full screen in the latest build of IG Moon now: https://imageglass.org/moon

![image](https://user-images.githubusercontent.com/3154213/140269074-80e708ee-9ddf-42cd-95c5-e48a58dac0bd.png)
