### ISSUE TITLE
It shows no image when double clicking on image file.

### ISSUE THREAD

**Issue by arthursun** [d2phap/ImageGlass#1038]
### System information:
 - Windows OS version:  10
 - ImageGlass version:  8.1.4.18

### To Reproduce
1.  Double click an image file to open with ImageGlass
2.  It says "reaching the 1st image" (I translated this, not sure what's the notice in English version) . Then nothing is shown but a grey background.
3.  Use left/right or scroll mouse changing images will bring up the image. But when the folder has only one image, you can't bring up the image.

### Actual behavior:

Image doesn't show.

### Additional context:

Not sure if this is related that I upgraded from an older version(can't remember version number), and didn't restart my computer. (For some reasons I don't want to restart my computer yet)

**Comment by d2phap** [comment]
Hi @arthursun 

This bug is duplicated (https://github.com/d2phap/ImageGlass/issues/1019) and fixed in the latest build of IG Moon (https://imageglass.org/moon)
The official release will be shipped in next few weeks.

**Comment by arthursun** [comment]
@d2phap  Thank you! I wondered if it's that obvious, there should be a report about it. I did checked many posts, but missed that  one.
