### ISSUE TITLE
After updating imageglass to the last version, image are not drawed anymore in imageglass

### ISSUE THREAD

**Issue by Zeus64** [d2phap/ImageGlass#1039]
### System information:
 - Windows OS version: 10
 - ImageGlass version: 8.1.4.18

When I double click on an image in the Windows Explorer, it's work I can see the image in imageglass. However when I do the same from total commander (https://www.ghisler.com/) It's not work ! Please not that it's was working very well in previous version of ImageGlass, it's after the update that it's not work anymore

**Comment by d2phap** [comment]
Thanks @Zeus64 
This is probably duplicated of #1019, and fixed in the latest build of ImageGlass Moon https://imageglass.org/moon
The official release will be shipped in few weeks

**Comment by Zeus64** [comment]
@d2phap yes thanks it's look exactly the same issue !
