### ISSUE TITLE
Doesn't support high-resolution screens

### ISSUE THREAD

**Issue by nZeus** [d2phap/ImageGlass#104]
Doesn't support high-resolution screens (UltraHD).
This makes the app absolutely useless. :(
Just look at this screen:
![image](https://cloud.githubusercontent.com/assets/2727326/17648464/aa892f96-6216-11e6-969f-9878b4195d4e.png)

**Comment by nZeus** [comment]
Settings screen: 
![image](https://cloud.githubusercontent.com/assets/2727326/17648466/e84d4808-6216-11e6-9034-9d2149bffaf9.png)

**Comment by d2phap** [comment]
Thanks @nZeus 

This issue has been reported at #32 
Still investigating in fixing.

**Comment by d2phap** [comment]
Hi @nZeus 

Please help me test this issue by downloading and running the ImageGlass.exe in the below link: 
http://www.imageglass.org/upload/moon/ImageGlass_3.x_20022017.zip

Thanks
