### ISSUE TITLE
i get imageglass cannot open this picture becaut this file appears to be damaged but the file is valid but is very large

### ISSUE THREAD

**Issue by aphideater** [d2phap/ImageGlass#1040]
### System information:
 - Windows OS version: 
 - ImageGlass version: 

### To Reproduce
1. open normal file 
2.  go back and forth till you find a large file in the folder 
3. the file will not open

### Actual behavior:
files says is courpted but is not

### Expected behavior:
open the file normaly 

### Screenshots:
![image](https://user-images.githubusercontent.com/83680753/117086613-bf67ac00-ad55-11eb-8c6d-0df499a0b05a.png)

### Additional context:
the file will open if clicked on but not in the arrow navigation mode 

im sorry but im not native english and not programer so my report may be bad but im sure the point is described will for people to understad salutation and thank you for great porgram

**Comment by aphideater** [comment]
just to clearfy i have 64 gigs of ram so thats not a issue

**Comment by aphideater** [comment]
my mode is random order

**Comment by d2phap** [comment]
What version of ImageGlass are you using?

**Comment by aphideater** [comment]
8.1.4.18

also here is a pic of the picture open on one window by arrow another by click showing the difference
![image](https://user-images.githubusercontent.com/83680753/117089285-a95de980-ad5d-11eb-82bf-9913506176e3.png)

**Comment by aphideater** [comment]
in general only happens with big files not small ones under maybe 5mb

**Comment by d2phap** [comment]
Can you try the latest build of IG Moon: https://imageglass.org/moon
This might be fixed

**Comment by aphideater** [comment]
i was unable to reproduce the error on the new version of imgeglass 8.2.6.6
