### ISSUE TITLE
File tree with folders

### ISSUE THREAD

**Issue by Denis96** [d2phap/ImageGlass#1041]
![Sin título](https://user-images.githubusercontent.com/11568576/117109179-8f83cd00-ad84-11eb-9413-f6498a8e0a31.png)

I don't know if there is such a thing, but it could be a very cool feature to show more than one folder and to be able to organize everything more easily.

**Comment by d2phap** [comment]
Thanks @Denis96 
However, ImageGlass is designed to work with File Explorer, so there is no gallery, or file/directory tree. This is to simplify the app and avoid being bloated.
