### ISSUE TITLE
the first photo cannot be displayed if disable "Loop back viewer to the first image when reaching the end of the list"

### ISSUE THREAD

**Issue by lyaaz** [d2phap/ImageGlass#1042]
### System information:
 - Windows OS version: Win10 19042.964
 - ImageGlass version: 8.1.4.18

### To Reproduce
1. uncheck "Loop back viewer to the first image when reaching the end of the list"
2. open a photo with IG.

### Actual behavior:

IG starts but the image is not displayed. If there are more than one photos in the folder, switch the image and all the images in the folder will be displayed correctly, else never.

### Expected behavior:

All photos are displayed correctly.

### Screenshots:

![20210505_chrome_326](https://user-images.githubusercontent.com/45838887/117123109-312d0d80-adc9-11eb-904b-e191b9f17a80.png)

**Comment by d2phap** [comment]
Thanks @QingKongBaiYu 
This is probably duplicated of #1019, and fixed in the latest build of ImageGlass Moon https://imageglass.org/moon
The official release will be shipped in few weeks
