### ISSUE TITLE
Window fit (F9) sets wrong window size with small images

### ISSUE THREAD

**Issue by SylwesterZarebski** [d2phap/ImageGlass#1045]
### System information:
 - Windows OS version: Windows 10 20H2 (build 19042.928)
 - ImageGlass version: 8.1.4.18
 - Theme: Windows 10 Dark (HiDPI) 3.4

### To Reproduce
1. Open small image with Window fit (F9) option enabled.
2. See very small window with no image, almost only window title bar.

### Actual behavior:
ImageGlass do not set proper window size and opened image is not visible at all.

### Expected behavior:
Image should be visible.

### Screenshots:
ImageGlass window after opening image:
![obraz](https://user-images.githubusercontent.com/1755531/117574916-d274d600-b0df-11eb-8394-188ff5511af5.png)
Sometimes it opens as:
![obraz](https://user-images.githubusercontent.com/1755531/117575027-4c0cc400-b0e0-11eb-8246-df66569f1148.png)

### Additional context:
Opened image (png) to test:
![icon-zoom](https://user-images.githubusercontent.com/1755531/117574907-bffa9c80-b0df-11eb-9a3c-53503cdda442.png)

Probably ImageGlass should set minimum width and height of window to properly display icons/buttons bar and at least menu button.

**Comment by d2phap** [comment]
Thanks @SylwesterZarebski 
This is duplicated of #814

**Comment by SylwesterZarebski** [comment]
Sorry, Github search did not find #814 using *Window fit* or *F9* phrases.

PS. And now it finds... Github quirks?
