### ISSUE TITLE
Consider shipping hotfixes for crucial bugs for the latest stable release

### ISSUE THREAD

**Issue by akdevservices** [d2phap/ImageGlass#1046]
Bugs happen, it's part of the software development process. But it would be nice to have hotfixes for annoying bugs (like #1020) for the latest stable release.

**Comment by d2phap** [comment]
Thanks @akdevservices 
It will be shipped by this weekend.

**Comment by akdevservices** [comment]
@d2phap
Nice piece of software. Thank you for your work.
