### ISSUE TITLE
Center thumbnails horizontally in Thumbnail panel

### ISSUE THREAD

**Issue by akdevservices** [d2phap/ImageGlass#1049]
If there is a small number of images in Thumbnail panel, all images are left aligned. It would be great if thumbnails are center aligned.
![ImageGlass1](https://user-images.githubusercontent.com/29972256/117663589-adbb4580-b155-11eb-8903-6058147cb7d0.png)

**Comment by d2phap** [comment]
The thumbnails are aligned center by default in [ImageGlass Moon 9.0 beta 3](https://github.com/d2phap/ImageGlass/releases/tag/9.0.3.1225)

![image](https://user-images.githubusercontent.com/3154213/209425448-0758763f-9eb8-40c7-b0d1-f3a40bc9623d.png)
