### ISSUE TITLE
"Loading..." graphical glitch annoyance

### ISSUE THREAD

**Issue by 4294967296** [d2phap/ImageGlass#105]
There is a "Loading..." white text in a black background rectangle being briefly shown during image transition.

This is not actually a bug, but it is certainly an annoyance, and it occurs both during manual navigation and during slideshow.

It could be configured to become visible only if the waiting time is too long, so it would not distract image browsing under normal circumstances.

P.S.

This project seems to have a great potential.

I am going to submit a lot of requests, recommendations, and bug reports.

I have already navigated to the open and closed issues, to exclude duplicate reports.

I hope that, by submitting my suggestions, I will be able to help you improve your project and sort out some malfunctions.

**Comment by d2phap** [comment]
Hi @4294967296 

Thanks for your many feedbacks.
I appreciate all of them.

Phap

**Comment by d2phap** [comment]
Removed the "Loading..." text
