### ISSUE TITLE
When using Windows fit, if the picture size is too small, the display will be abnormal

### ISSUE THREAD

**Issue by haoey** [d2phap/ImageGlass#1052]
### System information:
 - Windows OS version: 
 - ImageGlass version: 

### To Reproduce
1. 
2. 
3. 
4. 

### Actual behavior:

When using Windows fit, if the picture size is too small, the display will be abnormal.

### Expected behavior:

Small size pictures can be displayed normally in Windows fit mode
### Screenshots:

This is a normal picture.
![image](https://user-images.githubusercontent.com/70797176/118144926-9626da00-b43f-11eb-9a8e-311fcefdd3ee.png)
This is the picture after windows fit is turned on. Obviously, there is an error.
![image](https://user-images.githubusercontent.com/70797176/118144975-a343c900-b43f-11eb-8e29-8bee4dc9fc98.png)

**Comment by d2phap** [comment]
This is duplicated of #814
