### ISSUE TITLE
show toolbar when starting up.

### ISSUE THREAD

**Issue by haoey** [d2phap/ImageGlass#1053]
### Is your feature request related to a problem? Please describe.

1. close “show toolbar when starting up“.
2. Open image glass, and then open toolbar, "show toolbar when starting up" will open automatically.

### Describe the solution you'd like

  I hope that "show toolbar when starting up" and manual opening do not interfere with each other, that is, That is, "show toolbar at startup" is still closed after manually opening the toolbar

**Comment by d2phap** [comment]
Both are working same. I don't think it's not necessary to create another behavior.
