### ISSUE TITLE
Image glass seems to have two in my computer

### ISSUE THREAD

**Issue by haoey** [d2phap/ImageGlass#1054]
### System information:
 - Windows OS version: windows 10
 - ImageGlass version: 8.1.4.18

### To Reproduce
If I use imageglass to open pictures through windows explorer and "everything" file search software, the interface is different, that is to say, their configuration files are different.

Open through Windows Explorer
![image](https://user-images.githubusercontent.com/70797176/118148845-8ad5ad80-b443-11eb-8b27-c683ac2b190e.png)
Open the file search software in "everything"
![image](https://user-images.githubusercontent.com/70797176/118148868-8f9a6180-b443-11eb-81de-3c611cd10d0b.png)

### Expected behavior:

I hope we can unify them.

**Comment by d2phap** [comment]
ImageGlass uses `%AppData\ImageGlass%` as "Configuration directory" if the Startup directory is not writable. You can read more about it at: https://imageglass.org/docs/app-configs

In your case, you might install it into 2 place?! Can you open both cases, and check the location of the ImageGlass process?

**Comment by haoey** [comment]
> ImageGlass uses `%AppData\ImageGlass%` as "Configuration directory" if the Startup directory is not writable. You can read more about it at: https://imageglass.org/docs/app-configs
> 
> In your case, you might install it into 2 place?! Can you open both cases, and check the location of the ImageGlass process?

I think I understand that this software can only be installed once, but it uses different configuration files through different software calls, so it looks like two of software。
![image](https://user-images.githubusercontent.com/70797176/118155866-45b57980-b44b-11eb-8f06-69722e3627a8.png)

**Comment by haoey** [comment]
> ImageGlass uses `%AppData\ImageGlass%` as "Configuration directory" if the Startup directory is not writable. You can read more about it at: https://imageglass.org/docs/app-configs
> 
> In your case, you might install it into 2 place?! Can you open both cases, and check the location of the ImageGlass process?

After "open file location", they are the same file, but their icon colors are different.

![image](https://user-images.githubusercontent.com/70797176/118157158-cb85f480-b44c-11eb-92f6-8b575b7f907b.png)

**Comment by d2phap** [comment]
The issue here is Everything might open ImageGlass as admin, that's why IG had write permission in `C:\Program Files\ImageGlass` folder.

This is how ImageGlass is designed. The solution is to install ImageGlass in `%LocapAppData%\Programs\` folder. IG 9 already set this location as default when user choose to install for Current user only.
