### ISSUE TITLE
Crop and Saving .png File Error 

### ISSUE THREAD

**Issue by RoroRoze** [d2phap/ImageGlass#1056]
### System information:
 - Windows OS version: 
 - ImageGlass version: 

### To Reproduce
1. Open .png photo
2. Crop the .png photo
3. save as .png
4. Try open the saved photo
5. Error

### Actual behavior:

Can't read file header ! 
Unknown file format, empty/damaged file or file not found !

### Expected behavior:

Open as normal 

### Screenshots:

.png Photo Before Cropping:
![image](https://user-images.githubusercontent.com/65495906/118373105-af559500-b5bd-11eb-9b7a-d88f221c371d.png)

Error Message:
![image](https://user-images.githubusercontent.com/65495906/118373097-951bb700-b5bd-11eb-849f-c8a3393f2fda.png)

.png Photo After Cropping:
![image](https://user-images.githubusercontent.com/65495906/118373115-c0060b00-b5bd-11eb-9cdc-3da838170790.png)

**Comment by fire-eggs** [comment]
This is a known issue, and a fix is available in [ImageGlass Moon](https://ImageGlass.org/moon). An updated "official" release is anticipated soon.
