### ISSUE TITLE
Crop using aspect ratio

### ISSUE THREAD

**Issue by RoroRoze** [d2phap/ImageGlass#1057]
### Is your feature request related to a problem? Please describe.

Crop using Specific aspect ratio instead of using Width & Hight 
Similar to Photoshop 
### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/65495906/118373233-6b16c480-b5be-11eb-9720-a98faeaafffa.png)

**Comment by d2phap** [comment]
Duplicated #755
