### ISSUE TITLE
Save of animated GIF loses animation

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#1058]
### System information:
 - Windows OS version: N/A
 - ImageGlass version:   8.1

### To Reproduce
1. Load an animated GIF file
2. Use save to save it [no changes!]
3. GIF is no longer animated

### Actual behavior:
GIF file loses animation.

### Expected behavior:
File should be saved with its original characteristics : animation, color depth, etc.

### Screenshots:
N/A

### Additional context:
N/A

**Comment by d2phap** [comment]
Fixed this in [v9.0 beta 4](https://github.com/d2phap/ImageGlass/releases/tag/9.0.4.416)
