### ISSUE TITLE
Full screen related requests/recommendations

### ISSUE THREAD

**Issue by 4294967296** [d2phap/ImageGlass#106]
## Request 1

You may include in the settings a "Start in full screen mode" option.

Being able to press enter or double click on an image filename and view the image in a clean environment is a nice option.

You can alternatively include a "Start-up mode" option in the settings with a drop down list giving the following options:

Windowed
Full screen
Restore previous session selection
## Request 2

You may include in the settings an "Allow to double click to enter and exit full screen mode" option.

Double clicking to enter and exit full screen mode seems to be quite a common feature in many image viewers.

Since there is already a request to implement "Allow to double click to view actual image size", there must be some option about double clicking available in the settings.
## Request 3

There is already an "Allow to press ESC to quit application" option in the settings.

If you are in full screen mode, this setting is not active, since ESC exits full screen mode.

This can be frustrating if you mainly want to use the application as a viewer in full screen mode, since you have to press ESC twice to exit the application, and you also have to see the windowed interface.

You can keep the existing option working as it is, while also introducing a relative option for full screen mode.

You have to rename the existing option to "Allow to press ESC to quit application while in windowed mode".

You can then introduce an "Allow to press ESC to quit application while in full screen mode" option, to be able to exit the application directly from the full screen mode.

You can always press "Alt + Enter" to exit full screen mode and return to windowed mode, so this setting does not create any functional problems.

**Comment by d2phap** [comment]
Double-click action is set as toggling 
- View actual size of image, and
- Auto fit the image

This feature is implemented in ``develop`` branch

**Comment by d2phap** [comment]
merged to #407

**Comment by d2phap** [comment]
Implemented full-screen mode on startup
