### ISSUE TITLE
Make the Enter key a fullscreen toggle

### ISSUE THREAD

**Issue by timmay7** [d2phap/ImageGlass#1062]
Currently, it seems like F11 is the fullscreen toggle. Since the Enter key isn't used for anything, I would suggest making that a fullscreen toggle as well.

There are also ergonomic reasons for doing this:
- The Enter key is larger and easier to press.
- The Enter key is in a more convenient location, instead of F11's upper-right corner placement.

**Comment by rosswald** [comment]
Especially those who come from Irfanview. Also some video players also have enter as their fullscreen key. Since it's unused it's the logical option (also, if you can make it configurable - even better).

**Comment by d2phap** [comment]
I will merge this to #608 - keyboard customization
