### ISSUE TITLE
Settings > Unexpected scrolling behavior when hovering over dropdown menus

### ISSUE THREAD

**Issue by timmay7** [d2phap/ImageGlass#1063]
Regardless of where my mouse cursor happens to be, I expect the scrolling behavior to scroll the entire page of options.

If my cursor happens to be hovering over a dropdown menu, it instead scrolls the list of items within that menu. That is NOT the expected behavior. See my attached video for the issue.

https://user-images.githubusercontent.com/4268981/118419111-f603c780-b66f-11eb-93ea-b48f60eb3759.mp4

Also, keep in mind that the default behavior of web dropdown elements does not behave like your Settings menu. Take a look at the example I created in the Codepen below. Notice how you're scrolling the entire page regardless if your mouse is hovering over the dropdown.

https://codepen.io/timmay7/pen/dyvXwvm

**Comment by d2phap** [comment]
Hi, this is not web dropdown. This is the correct behavior of Win32 app combobox
