### ISSUE TITLE
Add "Browser" items to the folders context menu

### ISSUE THREAD

**Issue by xmha97** [d2phap/ImageGlass#1067]
Hi, please add "Browser" items to the folders context menu.
![Explorer](https://user-images.githubusercontent.com/23485114/118541318-c97ea700-b766-11eb-84bf-82652d41bd66.png)

**Comment by fire-eggs** [comment]
Some technical details:
https://stackoverflow.com/questions/20449316/how-add-context-menu-item-to-windows-explorer-for-folders

**Comment by xmha97** [comment]
Yes, I know, but I want to add this option by default.
```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\Directory\shell\ImageGlass.Browser]
@="Browser with ImageGlass"
"Icon"="\"C:\\Program Files\\ImageGlass\\ImageGlass.exe\",0"

[HKEY_CLASSES_ROOT\Directory\shell\ImageGlass.Browser\command]
@="\"C:\\Program Files\\ImageGlass\\ImageGlass.exe\" \"%1\""
```
Download [Registry.zip](https://github.com/d2phap/ImageGlass/files/6497681/Registry.zip)

**Comment by fire-eggs** [comment]
And I'm entering the link for my future reference as an ImageGlass developer.

**Comment by d2phap** [comment]
I won't implement this because it leaves the registry behind after users uninstall the app (similar to Make default photo viewer)
