### ISSUE TITLE
Add simple drawing tool

### ISSUE THREAD

**Issue by progonkpa** [d2phap/ImageGlass#1069]
I missed the ability to draw a line or draw a rectangular box (without fill) around content I wished to highlight.
P.S. The mask on your profile picture is bloatware ;)

**Comment by d2phap** [comment]
Thanks @progonkpa 
IG focuses on viewing functions, so I don't want to develop lots of editing features.
Instead, you can right-click > Edit  image..., it will open the third-party app for editing. You just need to save, IG will update the changes.
