### ISSUE TITLE
Zooming related requests/recommendations

### ISSUE THREAD

**Issue by 4294967296** [d2phap/ImageGlass#107]
## Request 1

You can also set the "+", "-" and "0" keys in the numerical keypad for zooming in and out and actual size.

I see that using the numerical keypad "0" key has been already requested, but how about the numerical keypad "+" and "-" keys?
## Request 2

The current zoom button descriptions, are "Zoom in (Ctrl + =)", "Zoom out (Ctrl + -)" and "Actual size (Ctrl + 0)".

So these controls are behaving as the ones used in browsers, but as it seems, they can also be used in a simpler way.

For zooming in and out, you don't actually have to press the "Ctrl" key, simply pressing "=" and "-" works fine.

You can also set the "0" key to zoom to actual size, without needing the "Ctrl" key, just like the "+" and "-" ones.

That should obviously be set for both "0" keys, since I already suggested enabling the numerical keypad "+", "-" and "0" keys.

You should probably ignore the next comment, since it seems to be an overkill to change the button descriptions to "Zoom in ([Ctrl + =] or [=] or [+]", "Zoom out ([Ctrl + -] or [-])" and "Actual size ([Ctrl + 0] or [0])".

While the details provided above could inform a random user about simpler ways to change the zoom level using the keyboard, the descriptions look ugly.

**Comment by d2phap** [comment]
Added new shortcuts: 0 and Num0
