### ISSUE TITLE
PSD layers merged after press Ctrl+s

### ISSUE THREAD

**Issue by panins** [d2phap/ImageGlass#1074]
### System information:
 - Windows OS version: Windows 10 20H2
 - ImageGlass version: 8.2.6.6

### To Reproduce
1. Open any .psd file with multi layers.
2. Ctrl+s
3. All layers merge to 1 layer. 

### Actual behavior:

Using hot key Ctrl+s , all layers  in .psd file have merged. All my work with the psd file have lost.

### Expected behavior:

Crtl+s" save file to another image format and the layers stay untouched.

### Additional context:

This hot key is too easy to ruin a psd file.

**Comment by d2phap** [comment]
Added a warning message when you override the image file in [v9.0 beta 2](https://github.com/d2phap/ImageGlass/releases/tag/9.0.2.904).
In this version, the PSD layers are kept but the structure is not (text layer is rasterized to image).

As ImageGlass does not focus on editing features, so this warning will be useful enough.

![image](https://user-images.githubusercontent.com/3154213/188650599-71d02626-babd-4a59-8dd5-ed8508832e1c.png)
