### ISSUE TITLE
Save and Save As of a pasted image from clipboard results in dialog error

### ISSUE THREAD

**Issue by DoomRater** [d2phap/ImageGlass#1075]
### System information:
 - Windows OS version: Windows 10 Home 20H2 (OS Build 19042.985)
 - ImageGlass version: 8.2.6.6

### To Reproduce
1. Copy image to clipboard
2. Open ImageGlass
3. Paste image
4. Attempt to save

### Actual behavior:
![image](https://user-images.githubusercontent.com/4010432/118707171-35552400-b7e8-11eb-89c1-b8a55cceb382.png)

### Expected behavior:
A Save Dialog Box to open up allowing me to specify where the image should be saved.

### Additional context:
I was originally on a previous version of ImageGlass when I tried to do this, and received the same error message found in issue #1055.

**Comment by fire-eggs** [comment]
Hooray, a new bug! Couldn't see this one because of the error shown in #1055 ...

**Comment by d2phap** [comment]
Fixed in the latest build of ImageGlass Moon: https://imageglass.org/moon
