### ISSUE TITLE
No .HEIC file icon

### ISSUE THREAD

**Issue by Davexx** [d2phap/ImageGlass#1076]
### System information:
 - Windows OS version:  Windows 10.0.19042
 - ImageGlass version: 8.2.6.6

### To Reproduce
1. Install ImageGlass
2. Associate HEIC image files with ImageGlass
3. In a windows file browser, observe the file icon for a known  HEIC file
4. File Icon uses a default ImageGlass icon and not an icon from the "Ext-Icons" folder

### Actual behavior:

There is no HIEC.ico file in the "Ext-Icons" folder as a source for a HEIC icon.
ImageGlass uses a default ImageGlass icon.

### Expected behavior:

ImageGlass should have a matching icon for HEIC files and not use a default ImageGlass icon.
There should be a HEIC.ico file in the "Ext-Icons" folder, and/or the software should recognize one if there is a proper HEIC.ico file in the folder.

### Screenshots:

![image](https://user-images.githubusercontent.com/3362914/118708690-421e4b80-b7d9-11eb-95fb-5aec23dd391d.png)

**Comment by d2phap** [comment]
@Davexx 
I don't have original design for those icons, so need somebody to contribute :)

**Comment by d2phap** [comment]
Maybe @AnotherDimension-Ex (#492) and @KyoGrou (#217) can help to update the icons pack?

**Comment by Davexx** [comment]
I would be more than happy to add icons to any icons set needing the HEIC icon.  If you have source files for the sets in need, that would allow me to create them quickly and accurately.  If you don't, I could create them from scratch.  Let me know which ones need the update.

I noticed that the "**Resolute Bay Icon Set**" and "**AnotherDimension-Ex Icon Set**" already contains a HEIC.ico file, so those ones are ready to go!

**Comment by KyoGrou** [comment]
@d2phap this is my updated icons pack with the new .HEIC extension
[ImageGlass Icons.zip](https://github.com/d2phap/ImageGlass/files/6526481/ImageGlass.Icons.zip)

**Comment by KyoGrou** [comment]
@d2phap Also the icons colors has been changed since the last time I made the pack so maybe we can update the preview image on the website, yes ?

**Comment by d2phap** [comment]
As you wish! 
Pls note that IG icon is theme-aware, which means, the icon is changable through theme pack.

The main IG icon is still blue

**Comment by d2phap** [comment]
Added this to the latest build of ImageGlass Moon: https://imageglass.org/moon
