### ISSUE TITLE
Multi-page TIFF file, orientation of pages not respected

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#1077]
From Google groups.

### System information:
 - Windows OS version: 
 - ImageGlass version: 8.2.6.6

### To Reproduce
1. Load attached TIF
2. Using page navigation, goto page 2.

### Actual behavior:
The 2d page is shown only as wide as the first page. The first page is rotated, so it is narrow; the second page is not, so it is wide. So the 2d page is truncated, width-wise.

### Expected behavior:
The 2d page should be shown wide, as contained in the file.

### Additional context:
See attached sample file.
[hoch_quer_hoch.tif.zip](https://github.com/d2phap/ImageGlass/files/6503783/hoch_quer_hoch.tif.zip)

**Comment by d2phap** [comment]
Fixed this in [v9.0 beta 4](https://github.com/d2phap/ImageGlass/releases/tag/9.0.4.416)
