### ISSUE TITLE
Unhandled Exception (Save/Save as...)

### ISSUE THREAD

**Issue by Komprogue** [d2phap/ImageGlass#1079]
### System information:
 - Windows OS version: Windows 7 x86
 - ImageGlass version: 8.2.6.6 & 8.1.4.18

### To Reproduce
1. Take screenshot 
2. Open ImageGlass and paste your image 
3. Click "Save" / "Save as..." or press Ctrl+S
4. Get error message 

### Actual behavior:

![bug](https://user-images.githubusercontent.com/84424346/118749602-83a90800-b866-11eb-96cf-24c91543137e.jpg)

### Expected behavior:
Saving an image without any troubles. 

### Additional context:
That bug appears during three last releases.

**Comment by d2phap** [comment]
Duplicated of #1079
