### ISSUE TITLE
Use "Up" and "Down" keys to zoom in and out request/recommendation

### ISSUE THREAD

**Issue by 4294967296** [d2phap/ImageGlass#108]
As it is already configured:

"Left" and "Right" keys are used to navigate through the images.
"Up" and "Down" keys are used to pan vertically at a very slow rate.

"Ctrl (or Alt or Shift)" + "Left and Right" keys are used to pan horizontally a screen at a time.
"Ctrl (or Alt or Shift)" + "Up and Down" keys are used to pan vertically a screen at a time.

Maybe it makes sense to change the "Up" and "Down" keys function to zoom in and out, since you can also pan in combination with the "Ctrl" key.

You could also differentiate the "Alt" + "Arrow keys" combination to pan horizontally and vertically at a very slow rate, to get back the existing "Up and Down" functionality.

Alternatively, although it might be an overkill to do so, you can make an "Arrow keys" setting section under settings, and provide all possible available options.

An optional configuration could be to also provide an option to use all arrow keys for panning, since navigating through the images can be done using PageUp and PageDown.

**Comment by fire-eggs** [comment]
Available in current ImageGlass Moon (https://imageglass.org/moon)
