### ISSUE TITLE
Bug with cropping images in albums

### ISSUE THREAD

**Issue by gingerkid427** [d2phap/ImageGlass#1081]
### System information:
 - Windows OS version: Win10 x64 20H2
 - ImageGlass version: 8.2.6.6

### To Reproduce
1. Open an image in an album
2. Open the cropping tool
3. Select an area, dragging the mouse to either side of the window until the previous/next image arrow appears
4. Release the mouse

### Actual behavior:

ImageGlass moves to the previous/next image

### Expected behavior:

The crop area should be selected properly

**Comment by leo-smi** [comment]
For me the crop doesn't save even if I clice manually in save.

**Comment by fire-eggs** [comment]
> For me the crop doesn't save even if I clice manually in save.

Your comment is not related to the issue raised here. Please open a new issue instead.

**Comment by d2phap** [comment]
This issue should be fixed in v9.0 beta 3
