### ISSUE TITLE
Ability to add title-bar "applet" buttons

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#1084]
From Discord, re: F11 as full-screen mode shortcut:

ijahangard — Today at 2:08 AM
Yeah ! Good idea
I also like to see its button on title bar as an applet button

Request is to be able to add action buttons to the title bar [not toolbar].

**Comment by d2phap** [comment]
Adding buttons on title bar adds more complexity into the app as it's hard and complex to customize the WinForms UI. The new ImageGlass uses WinUI 3 and Webview2 will have more customization.
