### ISSUE TITLE
Set as default photo viewer... setting get error alert

### ISSUE THREAD

**Issue by thang-nhatrangart** [d2phap/ImageGlass#1085]
### System information:
 - Windows OS version: 10
 - ImageGlass version: lastest

### To Reproduce
1. 
2. 
3. 
4. 

### Screenshots:

![image](https://user-images.githubusercontent.com/64763913/119120769-df39e800-ba56-11eb-88da-a516ebf156e9.png)

**Comment by d2phap** [comment]
Similar to #1360, it's fixed in [v9.0 beta 2](https://github.com/d2phap/ImageGlass/releases/tag/9.0.2.904).
