### ISSUE TITLE
Maybe usefull setting/feature

### ISSUE THREAD

**Issue by dhana-exe** [d2phap/ImageGlass#1086]
Umm you know... i searching and found your amazing "imageglass" while i have problem with windows photo viewer...
one feature that i love most from that is when someone send me the picture/image and that picture is "not right" i mean... they send to me on rotated version... so i had to rotate 90° to left or right to see the image as i should...

and the good things when i do rotate the image, any image with that old "windows photo viewer" from windows 7 is after i rotate, they saved my picture on last rotated setting, and they not change any size, or quality of the image....
that's what i love most about it..
can you make any setting for this? i know, not all people love this... but i think for people who didn't use rotate setting much except they really need to rotate some image to the right positition and want to make that always like that i think this a great feature....

and on windows photo viewer that i talking about... they "change" the rotation of the image and when i open it on different devices or upload the image that i already rotated on Windows photo viewer... the rotation still present (maybe they edited to make the image rotate)

well sorry for my bad english but my point is to request this software to have some feature like that... or atlest have setting to make this happen
this is may very usefull for me since i run "university club" and i need to check people ID's with that and then upload the data to university to reporting....
sometime, image not shown on Windows image viewer, (this is bug)
and now i found your software and really hope you can create such feature present on this software... maybe if you already do this... on future i ask the club leader to atleast give some donate to respect this amazing software

thanks :)

**Comment by d2phap** [comment]
You can find these settings in Settings > Edit:
Save image after modification
Image quality

**Comment by dhana-exe** [comment]
ah amazing
:D thanks alot
i will tell everyone to use this now

even gif can be played faster on here
amazing software man :D

**Comment by dhana-exe** [comment]
eh wait... after i rotate and they autosaved
the image damaged
![image](https://user-images.githubusercontent.com/29838157/119141515-8dea2280-ba6f-11eb-9b11-3ae9f444bd0e.png)

**Comment by d2phap** [comment]
The update to fix the image corruption issue. It does not auto save the image, but:
- v8.8 shows a confirm dialog to save the image changes
- v9.0 beta 4 shows "Save" button on the toolbar
