### ISSUE TITLE
Current ImageGlass resource leaks

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#1087]
I ran [Coverity Scan](https://scan.coverity.com/) against a fork of ImageGlass as of early May. Setting aside some false positives, the scan correctly identified a number of resource leaks.

Unfortunately, the reporting capabilities for the free version are limited, I've attempted to distill them down here:

| File | Method | Issue |
| --- | --- | --- |
| ImageInfo.cs | GetWxHSize | var ico=new Icon() : needs disposal |
| ImageInfo.cs | GetImageResolution | two calls to ico.Bitmap need disposal |
| DownloadFile.cs | DownloadFile | var WC = new WebClient() : needs disposal |
| DesktopWallpaper.cs | Set | img is not disposed |
| DesktopWallpaper.cs | Set | WebClient is not disposed |
| Update.cs | GetUpdateConfig | WebClient is not disposed |
| frmCheckForUpdate.cs | LoadTheme | this.Icon = Icon.FromHandle() : created bitmap is not disposed |

Most of these can be fixed with `using`.

**Comment by d2phap** [comment]
fixed
