### ISSUE TITLE
Zoom optimisation: Auto (High quality/Nearest-neighbour)

### ISSUE THREAD

**Issue by Mine-Modder** [d2phap/ImageGlass#1088]
### Is your feature request related to a problem? Please describe.
I like using Auto mode as it makes pixel art look pixelated while zoomed in, without losing detail when zoomed out. However, the _Low quality_ part of the current auto mode _Auto (Loq quality/Nearest-neighbour)_

_Low quality_ at 60% zoom looks better than _Nearest-neighbour_, but it doesn't look that great, which would be expected for a mode named _Low quality_. _High quality_ does look a lot better at 60% zoom; just take a look at the comparison image below.

### Describe the solution you'd like
I would like _Zoom optimisation_ to have an _Auto (High quality/Nearest-neighbour)_ option.

### Describe alternatives you've considered
None

### Additional context
![image](https://user-images.githubusercontent.com/83986705/119375445-1c061900-bcbb-11eb-88d1-7d4ab1effe83.png)

**Comment by d2phap** [comment]
You can manually define it in [ImageGlass Moon 9.0 beta 3](https://github.com/d2phap/ImageGlass/releases/tag/9.0.3.1225) with 
`ImageInterpolationScaleDown` and `ImageInterpolationScaleUp` settings. The supported interpolation values are:
- NearestNeighbor
- Linear
- Cubic
- SampleLinear
- Antisotropic
- HighQualityBicubic
