### ISSUE TITLE
Loop back viewer setting request/recommendation

### ISSUE THREAD

**Issue by 4294967296** [d2phap/ImageGlass#109]
There was a request about an image loop back setting for the slideshow, which has been addressed a long time ago.

The original poster also asked about an image loop back setting for the viewer, but he posted it in the already closed issue.

As it is configured, image loop back is always enabled in the viewer.

The relative setting about the slideshow does not work on the viewer.

You may adjust that setting to work both for the viewer and the slideshow, and rename it to:

"Loop back to the first image when reaching the end of the list".

You may alternatively include two separate options, named as:

"Loop back viewer to the first image when reaching the end of the list".
"Loop back slideshow to the first image when reaching the end of the list".

**Comment by rastographics** [comment]
Glad I just found ImageGlass it is fantastic. The first thing I noticed is the same thing that @4294967296 says above: need to add a setting to disable looping on photo viewing. 

As a user, sometimes I want confirmation that I have reached the last photo in a folder. With looping always enabled, it is difficult to tell when I have gone through all the photos.

**Comment by d2phap** [comment]
Added this feature!
