### ISSUE TITLE
JXL files do not show up in thumbnails in file explorer

### ISSUE THREAD

**Issue by Shidouuu** [d2phap/ImageGlass#1090]
![image](https://user-images.githubusercontent.com/36283656/119583174-00bb0c80-bd94-11eb-8456-1f4909c2b547.png)

ImageGlass 8.2.6.6

**Comment by fire-eggs** [comment]
ImageGlass is not responsible for Windows Explorer preview.

[This](https://github.com/saschanaz/jxl-winthumb) seems to be the best option right now.
