### ISSUE TITLE
configre upscale and downscale algorithm separately

### ISSUE THREAD

**Issue by soldivelot** [d2phap/ImageGlass#1092]
I want to zoom out image using bicubic algorithm and zoom in using nearest neighbor algorithm, but there is no such option
Is it possible to set the sampling algorithm separately instead of choosing some presets like “Auto (Low Q / NN)”?
This can provide more flexibility:smile:

**Comment by d2phap** [comment]
You can do it in [ImageGlass Moon 9.0 beta 3](https://github.com/d2phap/ImageGlass/releases/tag/9.0.3.1225) with 
`ImageInterpolationScaleDown` and `ImageInterpolationScaleUp` settings. The supported interpolation values are:
- NearestNeighbor
- Linear
- Cubic
- SampleLinear
- Antisotropic
- HighQualityBicubic

**Comment by soldivelot** [comment]
thanks:smile:

**Comment by Comitant** [comment]
> You can do it in [ImageGlass Moon 9.0 beta 3](https://github.com/d2phap/ImageGlass/releases/tag/9.0.3.1225) with `ImageInterpolationScaleDown` and `ImageInterpolationScaleUp` settings. The supported interpolation values are:
> 
>     * NearestNeighbor
> 
>     * Linear
> 
>     * Cubic
> 
>     * SampleLinear
> 
>     * Antisotropic
> 
>     * HighQualityBicubic

Can you also add something like lanczos for downsampling?

**Comment by d2phap** [comment]
Unfortunately, ImageGlass only uses the interpolation algorithm from Direct2D and honestly I don't know how to add a new one.

**Comment by Comitant** [comment]
> Unfortunately, ImageGlass only uses the interpolation algorithm from Direct2D and honestly I don't know how to add a new one.

Apparently MagicScaler has tools to easily implement more advanced algorithms. Though, I'm not too knowledgeable on it.
https://github.com/saucecontrol/PhotoSauce
