### ISSUE TITLE
After rotating a multipage TIF file, all page navigation features stop working

### ISSUE THREAD

**Issue by trickshooter** [d2phap/ImageGlass#1094]
### System information:
 - Windows OS version: Windows 10, 64 bit, 21H1
 - ImageGlass version: 8.2.6.6

### To Reproduce
1. Open any multipage TIF file
2. Rotate left or right (once or multiple times) or even rotate back into its original position
3. All menu options and the tool window for page navigation are there, are enabled, are active, are clickable, but without the desired effect (not switching to next/prev page anymore)
4. Though, it seems to do "something" since the page counter "1/n" is somehow "flashing" on clicks.

### Actual behavior:
After rotating a multipage TIF file, it is no longer possible to go to prev/next page.

### Expected behavior:
To have a working page navigation after previously having rotated a TIF file (in whatsoever direction and no matter how often).  

### Screenshots:
-none-

### Additional context:
-none-

**Comment by d2phap** [comment]
ImageGlass does not support advanced editing features, it's mostly for viewing purpose only.
In the latest build of ImageGlass Moon 8.7: https://imageglass.org/moon, a warning message will be shown when user overrides the image.

![image](https://user-images.githubusercontent.com/3154213/225963268-33deedb8-c2fb-464b-8dce-68a258bff66d.png)
