### ISSUE TITLE
Support animated SVG

### ISSUE THREAD

**Issue by xmha97** [d2phap/ImageGlass#1098]
Hi, Please support animated SVG.
Like this: [loader.zip](https://github.com/d2phap/ImageGlass/files/6649552/loader.zip)

**Comment by iJahangard** [comment]
> Hi, Please support animated SVG.
> Like this: [loader.zip](https://github.com/d2phap/ImageGlass/files/6649552/loader.zip)

Also ,TGS and Lottie files

**Comment by d2phap** [comment]
This feature is implemented in [ImageGlass 9.0 beta 5](https://github.com/d2phap/ImageGlass/releases/tag/9.0.5.726)

**Comment by iJahangard** [comment]
Wow that's awesome
Thank you so much

**Comment by xmha97** [comment]
Thanks 🙏
