### ISSUE TITLE
Fix selected toolbar buttons on Windows 11

### ISSUE THREAD

**Issue by xmha97** [d2phap/ImageGlass#1099]
Hi, I use Windows 11.
Selected toolbar buttons is bad look:
![image](https://user-images.githubusercontent.com/23485114/122386149-d4557300-cf82-11eb-84ec-9c373401f60c.png)
Please fix it.

**Comment by fire-eggs** [comment]
Technical details for future reference.

I've confirmed this. ImageGlass currently does not have control over the toolbar button highlight colors. Attempts to change Registry settings [which worked in the past] had no effect. Appears to be controlled by the theme, which is effectively impossible to edit.

**Comment by xmha97** [comment]
I know this is difficult but I recommend switching to WPF.

**Comment by d2phap** [comment]
You can try the new build of IG Moon for Windows 11 UI updates.
https://imageglass.org/moon

**Comment by xmha97** [comment]
Thanks.
![image](https://user-images.githubusercontent.com/23485114/128606244-c3664a3d-2aba-4254-b6d8-d917f5167fa0.png)
