### ISSUE TITLE
Configurable mousewheel settings request/recommendation

### ISSUE THREAD

**Issue by 4294967296** [d2phap/ImageGlass#110]
I see that you already plan to implement some extra mousewheel functions.

For me, it makes sense to set as default:

"Mousewheel" = "Go to previous/next image"
"Mousewheel + Ctrl" = "Zoom image"

"Mousewheel + Alt" = "Horizontal pan"
"Mousewheel + Shift" = "Vertical pan"

If you observe the position of the Ctrl, Alt and Shift keys on the keyboard, it makes sense to map these keys as recommended above.

You could also offer an option under settings to enable mousewheel function changes over specific window areas, but make sure that it would be optional, because not everyone likes this behavior.

You can alternatively make these actions fully customizable under settings, to suit all tastes.

The code required for the following changes is not complicated, you just have to redirect action assignments.

Make a "Mousewheel" setting section under settings and include these mousewheel actions:

Mousewheel
Mousewheel + Alt
Mousewheel + Ctrl
Mousewheel + Shift

For each of the above actions, make a drop down list to choose one of the following assignments:

Do nothing
Zoom image
Vertical pan
Horizontal pan
Go to previous/next image

You can also include an "invert mousewheel direction" check box for each action to cover all tastes, but that may be an overkill.

**Comment by d2phap** [comment]
This feature is implemented, you can try it here http://www.imageglass.org/moon
