### ISSUE TITLE
Some invisible icons with the Icon8 Office16 (Dark) theme.

### ISSUE THREAD

**Issue by SilverKnight-Z** [d2phap/ImageGlass#1100]
### System information:
 - Windows OS version: Windows 7 Starter SP1 32-bit
 - ImageGlass version:  8.0.12.8_x86 (portable)

### To Reproduce
1. Open ImageGlass
2. Right Click and go to Settings
3. Go to Theme
4. Install Icon8 Office16 (Dark)
5. Customize the toolbar to your liking

### Actual behavior:
Some icons in the toolbar are invisible while the Icon8 Office16 (Dark) theme is installed. Specifically I'm referring to the "crop" and "scale to fill" icons.

### Expected behavior:
All icons appear correctly.

### Screenshots:
![crop](https://user-images.githubusercontent.com/82909608/122444227-54bda900-cf6e-11eb-9205-162831a7d235.jpg)
![scale](https://user-images.githubusercontent.com/82909608/122444261-5be4b700-cf6e-11eb-8ed4-159e3626211b.jpg)

**Comment by d2phap** [comment]
The Icon8 Office16 theme is removed from the website due to license issue
