### ISSUE TITLE
Ascending and descending loading options in the right-click menu

### ISSUE THREAD

**Issue by SilverKnight-Z** [d2phap/ImageGlass#1101]
### Is your feature request related to a problem? Please describe.
It's annoying to have to go to the settings every time I want to change the loading order of the images between ascending and descending.

### Describe the solution you'd like
I would love it if the ascending and descending loading options were also in the menu that appears when you right click on an image. And that they appear just below the other loading options, just like in Windows Explorer.

### Additional context
If implemented, this would further improve the user experience of this viewer, which has already surprised me a lot.

**Comment by d2phap** [comment]
Implemented in the latest build of ImageGlass Moon: https://imageglass.org/moon

Main menu and context menu
![image](https://user-images.githubusercontent.com/3154213/139864129-ca16b926-43ee-4f3c-9c29-b8e19a1ff229.png)

**Comment by SilverKnight-Z** [comment]
That's awesome! Thank you so much!
