### ISSUE TITLE
delete removes images without asking

### ISSUE THREAD

**Issue by attikov** [d2phap/ImageGlass#1103]
It became rather a review.

This sf removes images on pressing DEL without any confirmation, if recycle bin is off possible unwanted data loss.
Very-very bad design pattern.

Touch gesture support is pathetic.

Uninstalled.

**Comment by d2phap** [comment]
> This sf removes images on pressing DEL without any confirmation

You can change the setting in Settings > General > Others

> Touch gesture support is pathetic.

You can use MS Photos for better touch support.
Thanks!
