### ISSUE TITLE
HEIC display wrong

### ISSUE THREAD

**Issue by xkonglong** [d2phap/ImageGlass#1106]
### System information:
 - Windows OS version:  win10 1809
 - ImageGlass version:    8.2.6.6

### To Reproduce
1. 
2. 
3. 
4. 
![image](https://user-images.githubusercontent.com/9131496/124238623-65b01200-db4b-11eb-99bb-eb89720694ec.png)

**Comment by fire-eggs** [comment]
Could you provide one of the images that displays incorrectly?

**Comment by xkonglong** [comment]
> Could you provide one of the images that displays incorrectly?

https://1drv.ms/u/s!AthRRU4MyrUagowQMmq-C8qVDAlpHw?e=kgwoGX

**Comment by fire-eggs** [comment]
I've attempted to test this image with:
1. MS Windows 10 Photos
2. Google Photos
3. [HEIC to JPG online converter](https://heic.imobie.com/heic-to-jpg/)
4. [HEICtoJPEG](https://heictojpg.com/)

All these have failed to load or display the image.

Testing with [this](https://speedtesting.herokuapp.com/heicviewer/), the result looks like:

![image](https://user-images.githubusercontent.com/9809727/124364249-3e6e4900-dc0e-11eb-8853-7360c6bce519.png)

We'll probably have to ask the ImageMagick folks before we make any progress.

**Comment by xkonglong** [comment]
Install  CopyTrans HEIC for Window ,  This image can display. 


https://www.copytrans.net/copytransheic/

**Comment by fire-eggs** [comment]
Good to know, thanks!

**Comment by xkonglong** [comment]
> We'll probably have to ask the ImageMagick folks before we make any progress.


ImageMagick is can display need not "CopyTrans HEIC".

![屏幕截图 2021-07-08 100718](https://user-images.githubusercontent.com/9131496/124851394-0df32a00-dfd5-11eb-96e2-476ad852d143.png)

**Comment by d2phap** [comment]
Just close this, cannot reproduce
