### ISSUE TITLE
Rapid Next / Delete actions freeze/kill IG

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#1107]
From Google Groups:
>Basically I open a folder and either Delete or Right Arrow to prune the images I no longer need.
After a while Imageglass pauses and then stops - Not Responding. Clicking the mouse makes the screen go white cloudy and the program crashes. 

I have reproduced the problem.

### System information:
 - Windows OS version: Windows 10 Pro x64
 - ImageGlass version: 8.2.6.6

### To Reproduce
1. Open a folder in Imageglass containing images
2. Proceed to click the right arrow and delete key (deleting every other image).

NOTE: the problem reproduces if step 2 is done _quickly_. Moving through and deleting the images _slowly_ (e.g.) once per second does NOT cause a problem.

Merely moving through the images with the arrow key, even quickly, does not cause the problem. It is the combination of arrow plus delete.

### Actual behavior:
When I exercise the scenario, IG gets to a state where it is no longer showing images. Clicking the arrow key to move to the next image does nothing. Reloading the file list _might_ clear the problem, although the first image IG tried to display showed an error.

The reporting user suggests that IG freezes and crashes. I've not had that happen.

### Expected behavior:
IG acts as normal.

**Comment by fire-eggs** [comment]
Running the scenario inside the debugger, I've narrowed down the problem slightly. When IG gets into the "won't show more images" state, it turns out that `Local.IsBusy` flag is true.

Reloading the image list "fixes" the problem because `Local.IsBusy` gets reset to false.

So the delete process appears to be messing up the `Local.IsBusy` state.

**Comment by d2phap** [comment]
This issue is fixed in [v9.0 beta 2](https://github.com/d2phap/ImageGlass/releases/tag/9.0.2.904)
