### ISSUE TITLE
Support for Android vector drawable

### ISSUE THREAD

**Issue by iJahangard** [d2phap/ImageGlass#1108]
I have some android vector drawable xml files
It is hard to see them , Everytime i want to see them , I have to go online and upload and see or convert to svg

It can help me develope android apps and substratum themes or mod app's design

If it is possible, please add support for these xml files

**Comment by d2phap** [comment]
Hi, ImageGlass uses Magick.NET library to load image, you can to submit a request to the folks at https://github.com/dlemstra/Magick.NET
