### ISSUE TITLE
CMYK PSD files not generating thumbnails

### ISSUE THREAD

**Issue by MilkManEX** [d2phap/ImageGlass#1109]
Windows 11 (and previously on Windows 10)

1. Save a PSD file with image>mode set to CMYK

Results in the generic IG thumbnail.

Example:
The RGB images are the ones with thumbnails. Otis-copy is a duplicate of otis saved as RGB instead of CMYK.
![image](https://user-images.githubusercontent.com/16171167/124333496-5ee0c980-db62-11eb-8bfc-f9cb450f79c5.png)

**Comment by fire-eggs** [comment]
ImageGlass does not provide the thumbnails in Windows Explorer. If thumbnails for PSD files in CMYK don't work, contact Microsoft.

**Comment by d2phap** [comment]
You may wanna try this https://sourceforge.net/projects/sagethumbs/ for shell extension
