### ISSUE TITLE
"Window adapt to image" description and icon inconsistency recommendations

### ISSUE THREAD

**Issue by 4294967296** [d2phap/ImageGlass#111]
## Recommendation 1

The "Window adapt to image" description could be changed to something more proper.

"Adjust window to image dimensions" or "Adjust window to actual image dimensions" seems to be a better description.
## Recommendation 2

The icon used for the "Window adapt to image" function, is not consistent with the other icons, and leads to confusion.

This icon indicates a "Scale to Window" function, which is an automatic best choice between "Scale to Width" and "Scale to Height", without window resizing.

Such a "Scale to Window" button is not actually needed, because an automatic "Scale to Window" behavior is being always enforced by default.

The "Window adapt to image" icon is therefore confusing because it indicates that the displayed image size is being adapted to the window size, not that the window size is adapted to the actual image size, which is a totally different function.

Maybe you should change this icon with something else that you find more appropriate.

**Comment by d2phap** [comment]
Thanks for the correction.
I updated it.
