### ISSUE TITLE
 remember  setted locked  zoom position(not only centered or lef top)   and   modification date of photo all time  in title bar

### ISSUE THREAD

**Issue by BunyaminBozdagli** [d2phap/ImageGlass#1110]
It will be more useful if the following features are added to this application:

1)remember zoom, rotation, flip, position  for  each photo (while app is open only)    (for comparing two images easily)

2)sometimes the creation date of the pictures, sometimes the modification date appears in the title. Only the modification date should appear.

**Comment by what-aboot** [comment]
I second the request for the zoom setting to remain constant when moving between images. I have set my ig.admin.xml to open at actual size (Autozoom0) for the first image. To have it then revert to Autozoom 1 for the next image is very annoying.

**Comment by d2phap** [comment]
1) Implemented in [ImageGlass Moon 9.0 beta 3](https://github.com/d2phap/ImageGlass/releases/tag/9.0.3.1225): Lock zoom ratio also keeps the position for the next image.


2) You can choose what to display on the title bar in ImageGlass Moon 9.0 beta 1: https://github.com/d2phap/ImageGlass/issues/971#issuecomment-1133560019
