### ISSUE TITLE
ImageGlass / Greenshot (in)compatability

### ISSUE THREAD

**Issue by Wynadorn** [d2phap/ImageGlass#1111]
### System information:
 - Windows OS version: 20H2 (19042.985)
 - ImageGlass version: 8.2.6.6 (64 bit)
 - Greenshot version: 1.2.10 Build 6 (64 bit)

### To Reproduce
1. In Greenshot head to Configure External Commands in de tray icon's context menu.
2. Create a new entry for ImageGlass
         `Name: ImageGlass`
         `Command: C:\Program Files\ImageGlass\ImageGlass.exe`
         `Argument: "{0}"`
3. Take a screenshot, Open it with ImageGlass

### Actual behavior:
1. Greenshot will create a temporary copy of the screenshot as .png under `%temp%/` for example:
`%temp%/2021_07_08_16_57_41_Notepad.png`

2. The process for ImageGlass.exe will be launched however no GUI will be shown.

3. When inspected though the task manager the startup command seems to be fine and I've confirmed this manually.
![image](https://user-images.githubusercontent.com/4095127/124945228-3f3c1c00-e00e-11eb-9358-31f7cf2f4bfa.png)

* Forcefully terminating ImageGlass causes the following message to be displayed by Greenshot:
![image](https://user-images.githubusercontent.com/4095127/124945614-9a6e0e80-e00e-11eb-9abe-05f35dc29d18.png)
These messages can be read back in the `Greenshot.log` file
`2021-07-08 16:50:31,175 [Running ImageGlass] WARN  - [ExternalCommand.ExternalCommandDestination] Error:`
       `(process:16080): WARNING **: 16:50:28.480: unknown line join style undefined`
       `(process:16080): WARNING **: 16:50:28.480: unknown line cap style undefined`
Full `Greenshot.log` file: https://pastebin.com/raw/TQ9Pwvsq

* Forcefully terminating Greenshot instead of ImageGlass will cause the image will open.

### Expected behavior:

For the screenshot to be displayed in ImageGlass.

### Additional context:

* This functionality works for applications such a paint and photoshop.
* Updating to Greenshot version 1.3.205 UNSTABLE did not resolve the issue.
* I've created an issue in the Greenshot repository linking here: https://github.com/greenshot/greenshot/issues/323

**Comment by fire-eggs** [comment]
The way that GreenShot activates external programs appears to be incompatible with ImageGlass. If executed normally, ImageGlass runs fine accepting an image on the command line.

I found that after sending a screenshot to ImageGlass, then exiting Greenshot, ImageGlass would then appear (but without the screen cap).


I have two possible solutions.
1. If ImageGlass is configured as the "default image viewer", then using "cmd" as the "external program" will work.
2. If you edit Greenshot.ini after setting up your ImageGlass "external command", IG works.

**Solution 1:**
Run greenshot's plugin. Name your external command as you wish. For the "Command" entry, browse to "C:\Windows\System32" and select "cmd.exe". For the "Argument" entry, it should read "/c "{0}"". Here's what mine looks like:

![image](https://user-images.githubusercontent.com/9809727/124968711-d5af1400-dff3-11eb-960a-490dbbd0c015.png)

When you send the capture to this command via greenshot, a command prompt window will appear just before IG appears. The command prompt window closes when IG is closed.

**Solution 2:**
a. Set up your ImageGlass command configuration as you showed in your post above.
b. Edit the Greenshot.ini file. I found mine in `C:\users\<myname>\AppData\Roaming\Greenshot`.
c. Search for the string "RunInbackground.". It will have the name of the external command. E.g. for the command configuration in your post above, it will read: "RunInbackground.ImageGlass=True"
d. Change "True" to "False", save your changes, and exit/restart Greenshot.

Here's mine:
![image](https://user-images.githubusercontent.com/9809727/124969502-c8465980-dff4-11eb-9428-3ce40d301744.png)
where "RunInbackground.IG2" has ImageGlass as the "Command".


These messages:
```
(process:16080): WARNING **: 16:50:28.480: unknown line join style undefined
(process:16080): WARNING **: 16:50:28.480: unknown line cap style undefined
```
Are produced by ImageGlass to "standard error", and normally are invisible to the user. If you don't want to see them, you can change Greenshot.ini: find the line `RedirectStandardError=True` and change it to `False`.

**Comment by Wynadorn** [comment]
Thanks, both very useful workarounds.

I'll close the issue as I'm sure others who'd run into this can live with these solutions.

_edit:_
> I've done some more testing and it seems to be the actual `RedirectStandardError=False` variable that makes or breaks this issue.
> `RunInbackground` does not seem to make any difference.
