### ISSUE TITLE
Default Theme Replacement

### ISSUE THREAD

**Issue by SaskiFX** [d2phap/ImageGlass#1112]
### Is your feature request related to a problem? Please describe.
I'm deploying ImageGlass from SCCM, and I'd like to be able to override the default theme from within the .xml default file. It doesn't seem to work that way now. 

### Describe the solution you'd like
I'm copying the theme over to the Program Files\ImageGlass\Themes directory as part of the install, so it should be waiting there.

### Describe alternatives you've considered
Maybe an igtasks.exe to do it?

**Comment by d2phap** [comment]
The other option is to override `Themes\Kobe` folder.
I will check why it does not work.

Thanks

**Comment by gbs-kgs** [comment]
same here,  doesn't work to overwrite with config.default.xml

**Comment by JonathanPitre** [comment]
Is there any progress on that one?

**Comment by d2phap** [comment]
Should be working in v9.0:
- Copy theme to the `Themes` folder
- Create `igconfig.default.json` with this content:
```json
{
  "_Metadata": {
    "Description": "ImageGlass configuration file",
    "Version": "9.0"
  },
  "DarkTheme": "your theme name",
  "LightTheme": "your theme name"
}
```
