### ISSUE TITLE
No zero connection at first start

### ISSUE THREAD

**Issue by sculpordwarfsuntea** [d2phap/ImageGlass#1115]
### System information:
 - Windows OS version: Windows 11
 - ImageGlass version: 8.2.6.6

### To Reproduce
1. Install ImageGlass_8.2.6.6_x64.msi
2. Start ImageGlass for the first time
3. Check the network activity for ImageGlass only
4. ImageGlass connects to online server on first startup without asking the user
5. For privacy reasons software should be designed to always give zero connection on first startup

### Actual behavior:
No zero connection

### Expected behavior:
There should be a small setup wizard at the first start of the software, where the user can decide if automatic update should be searched or not. So the user can decide if he wants zero connection at first start or not. I'm not sure but it seems that this problem here is because of automatic update function, maybe there are other background functions that generally do not allow zero connection at the first start of the software.

### Screenshots:
N/A

### Additional context:
N/A

**Comment by d2phap** [comment]
Hi @sculpordwarfsuntea 

ImageGlass only uses network connection to check for update.
You can disable by default using a config file: https://imageglass.org/docs/app-configs.

I understand that you care about the privacy, but this is a basic feature of a software and it does not harm any thing.
So I don't want to add many options which can make ImageGlass bloated.

Thanks!
