### ISSUE TITLE
Save dialog should have current photo's directory

### ISSUE THREAD

**Issue by keeganrowe** [d2phap/ImageGlass#1116]
### System information:
 - Windows OS version: Windows 8.1
 - ImageGlass version:  7.6.4.30 Portable

### To Reproduce
1. Open a photo from a directory e.g. C:\A\
2. Press Ctrl + S to save it
3. Note the directory in which the application will save the photo e..g C:\B\

### Actual behavior:
The folder in which the photo will be saved is generally the last one used to save any photo e.g. C:\B\

### Expected behavior:
The folder in which the photo will be saved should by default be where the photo originated from e.g. C:\A\ so that I can save my rotated photo.

Note this is debatably a bug or a feature, as some people might want to possibly save altered copies of photos in a particular directory? Not sure. 

Thanks otherwise for a great app.

**Comment by d2phap** [comment]
The save / open dialog currently remembers  the last open directory.
