### ISSUE TITLE
Zoom dropdown in toolbar

### ISSUE THREAD

**Issue by worldsdream** [d2phap/ImageGlass#1119]
Thank you for creating such a modern app to view our photos.

I always used another photo app, till I discovered ImageGlass.

There is a feature that I do miss. It’s a zoom dropdown in the toolbar which let me adjust the zoom.

For example:
100%
90%
80%
70%

Thanks.

**Comment by d2phap** [comment]
v8.3 introduced Custom zoom which you can manually set zoom factor to any value.

![image](https://user-images.githubusercontent.com/3154213/148396505-9345a938-2547-41be-aa4b-0cc698a4433b.png)

**Comment by worldsdream** [comment]
It works great. I will close this then.
