### ISSUE TITLE
Automatic scaling bug reports and possible solution

### ISSUE THREAD

**Issue by 4294967296** [d2phap/ImageGlass#112]
## Bug report 1

After starting up the application, if you manually resize the window, the image being displayed inside the window is automatically scaled to best fit the new window size without being cropped.

If you use the "Scale to Width (Ctrl + W)" and/or "Scale to Height (Ctrl + H)" option, then the image does not continue to automatically scale to any new window size.

If the image is manually refreshed, by pressing (F5), automatic scaling is resumed.
## Bug report 2

The "Window adapt to image (Ctrl + M)" function seems to misbehave when the previously displayed image was zoomed in or out.

The window is resized to the actual image size, but the image displayed inside the window is not automatically adjusted to the new window size, but it stays in the previous zoom level.

You need to manually refresh the image, by pressing (F5), so it will adjust to the new window size, and continue to do so in subsequent manual window size changes.
### Solution

Maybe all you have to do to correct this behavior is to also include a refresh command near the end of the respective code of all these image sizing options, "(Ctrl + W)", "(Ctrl + H)" and "(Ctrl + M)".

**Comment by d2phap** [comment]
**About bug 1: When using Scaling W/H then resize window, Image isn't resized accordingly.** 
- Won't fix
- When you use "Scale to Width (Ctrl + W)" and/or "Scale to Height (Ctrl + H)", ImageGlass will consider it as Zoom function. While you are zooming, resizing window cannot change the image size.

**About bug 2: When using Scaling W/H on a zoomed image, the size of image is not changed.** 
- Fixed
