### ISSUE TITLE
Add: Gif Play mode add play/pause shortcut key

### ISSUE THREAD

**Issue by lingchuanbo** [d2phap/ImageGlass#1122]
Add: Gif Play mode add play/pause shortcut key
Thank you

**Comment by d2phap** [comment]
You can play/pause by pressing Ctrl+Space:
![image](https://user-images.githubusercontent.com/3154213/129053100-b2b00ee6-c2ca-422e-b18c-28f055d539d1.png)

Or view separated frame of GIF file by using Page navigation tool:
![image](https://user-images.githubusercontent.com/3154213/129053190-3a6e36c5-6fe7-4ede-82cf-e7526ac437d7.png)

**Comment by LLVIG** [comment]
Could the page navigation buttons be made available to the toolbar customization, so you could add them to the toolbar directly? Among with the play button. Some other app has this function, allowing easily to choose the specific gif frame, for example.
![nomacs  2022-01-18 @ 23-12-00](https://user-images.githubusercontent.com/73268401/150012453-bc0201cb-3928-4b64-9c9a-227bd9cbe3af.png)
