### ISSUE TITLE
Pin "Leftover" on Taskbar

### ISSUE THREAD

**Issue by Dhiparizky** [d2phap/ImageGlass#1123]
### System information:
 - Windows OS version: Windows 10 HSL 20H2 Build 19042.1151
 - ImageGlass version: 8.2.6.6

### To Reproduce
1. Drag and Drop the Image to the Taskbar, which will "Pin" it there.
2. Unpin it from taskbar

### Actual behavior:
When an image is pinned to the taskbar, unpinning it seems to leave an invisible taskbar shortcut.

### Expected behavior:
Any form of pin-to-taskbar shortcut should be gone when unpinned.

### Screenshots:
![image](https://user-images.githubusercontent.com/73228272/129117767-0261a4f3-773e-413d-bb42-08fcf1837b3f.png)
![image](https://user-images.githubusercontent.com/73228272/129118654-17d88ace-0e0a-41ff-87ee-217b0c4ca656.png)
![image](https://user-images.githubusercontent.com/73228272/129118699-e299c6bf-ec09-4c93-b01e-eb9a49d082b9.png)

### Additional context:
This issue can be resolved by restarting the Explorer.exe

**Comment by d2phap** [comment]
Should not be an issue in v9
