### ISSUE TITLE
Why is ImageGlass displaying some SVG images wrong?

### ISSUE THREAD

**Issue by xmha97** [d2phap/ImageGlass#1124]
Why is ImageGlass displaying SVG images wrong?
![Windows 11](https://user-images.githubusercontent.com/23485114/129459491-027193d4-99b7-484f-be7c-ebef24bba5fa.png)
[Office.zip](https://github.com/d2phap/ImageGlass/files/6987171/Office.zip)

**Comment by xmha97** [comment]
These images also do not open in Photoshop and Illustrator.
But they open well in Firefox and Inkscape.
![WIndows 11](https://user-images.githubusercontent.com/23485114/129460339-01a10d38-fa6d-4556-b16a-37e949515fdb.png)

**Comment by fire-eggs** [comment]
ImageMagick 7.1.0-4 gives me these error for "+logo_Exchange.svg":
```
non-conforming drawing primitive definition `L35' @ error/draw.c/TracePath/6611.
non-conforming drawing primitive definition `L12.022' @ error/draw.c/TracePath/6611.
```

So ImageMagick might be the problem.

**Comment by fire-eggs** [comment]
Here is a modified version of "+logo_Exchange.svg" which ImageGlass, ImageMagick, and other programs handle OK:

[logo_Excange_V2.svg.zip](https://github.com/d2phap/ImageGlass/files/6987263/logo_Excange_V2.svg.zip)

I'd be interested to know if Photoshop and Illustrator handle it OK as well.

**Comment by fire-eggs** [comment]
From [this issue](https://github.com/w3c/svgwg/issues/827) in the SVG Working group, the SVG is valid as per the spec. But "many parsers" can't handle it; Adobe Illustrator is mentioned.

**Comment by xmha97** [comment]
> 
> 
> Here is a modified version of "+logo_Exchange.svg" which ImageGlass, ImageMagick, and other programs handle OK:
> 
> [logo_Excange_V2.svg.zip](https://github.com/d2phap/ImageGlass/files/6987263/logo_Excange_V2.svg.zip)
> 
> I'd be interested to know if Photoshop and Illustrator handle it OK as well.

![image](https://user-images.githubusercontent.com/23485114/129692683-30dc61a2-a7a4-45a4-bf26-22e59e80957b.png)

I opened the SVG file you sent with several apps:
| # | App Name                            | Test Result                             |
|---|-------------------------------------|-----------------------------------------|
| 1 | Microsoft Edge / Google Chrome      | The SVG file loaded with some errors. ✔️ |
| 2 | Adobe Photoshop / Adobe Illustrator | The SVG file not load. ❌                |
| 3 | Inkscape                            | The SVG file loaded well. ✔️             |
| 4 | Mozilla Firefox                     | The SVG file not load. ❌                |

**Comment by fire-eggs** [comment]
Thanks for the update! Looks like I left some garbage at the end of the file [editing manually]. I'll see if I can clean it up.

**Comment by xmha97** [comment]
> Thanks for the update! Looks like I left some garbage at the end of the file [editing manually]. I'll see if I can clean it up.

Thank you for your follow up. 🙏

**Comment by fire-eggs** [comment]
I think this will take care of some of the errors.

[logo_Excange_V3.svg.zip](https://github.com/d2phap/ImageGlass/files/7010632/logo_Excange_V3.svg.zip)

I must be missing something - both FireFox and Edge load the "V2" file without errors - do you have some sort of diagnostics enabled?

Thanks,
Kevin

**Comment by fire-eggs** [comment]
Apparently, ImageMagick cannot be completely relied on for SVG parsing. To quote from [ImageMagic issue #898](https://github.com/ImageMagick/ImageMagick/issues/898):

>ImageMagick has an internal SVG renderer but its far from being compliant with the SVG specification and can fail to read
>anything but the most basic SVG image files. Instead, we recommend installations rely on alternative SVG renderers, either 
>the RSVG delegate library or Inkscape.

I've seen similar limitations in other SVG libraries. It looks like this issue will be a limitation, unless Phap wishes to integrate another SVG rendering library ...

**Comment by d2phap** [comment]
We won't use other library, this is just a limitation
