### ISSUE TITLE
Request for ImageGlass to use the order of images as displayed on Windows desktop

### ISSUE THREAD

**Issue by ivalith** [d2phap/ImageGlass#1127]
### Is your feature request related to a problem? Please describe.
So while I know ImageGlass allows you to change the order images load in and can follow the Windows File Explorer order when possible, something I can't seem to get it to do is load images the way they're shown when they're on the windows desktop, something that I've only seen Windows Photo Viewer do, with even the Windows 10 Photos app failing to. Normally what would happen when using Windows Photo Viewer is that images would load top to bottom left to right as they're ordered on your desktop, but this seems unrelated to the Windows File Explorer option and so ImageGlass seems to follow the order you specify without any way to choose something like this. 

### Describe the solution you'd like
The solution I'd like is some option or checkable box to load the images in the order they're displayed on the desktop specifically (mirroring the way Windows Photo Viewer loads them) instead of following the rules it uses for folders.

### Additional context
If it helps, I've included an example of what I mean. In this image these 6 image thumbnails don't follow an order but ImageGlass will load them by name because that's what's set in the image loading order settings while Windows Photo Viewer will load them from top to bottom in the way I expect when looking at them. 

![2021-08-22_18-57-00](https://user-images.githubusercontent.com/57418557/130372893-e12155af-1575-4c46-af6c-71b1b4f58b32.png)

**Comment by JFMugen** [comment]
I would love that as well.

**Comment by d2phap** [comment]
Currently, ImageGlass can only know the order of files if that folder is open.

**Comment by d2phap** [comment]
I dont see any apps can do this, I will close then.
