### ISSUE TITLE
Ability to make it a "viewer" only...

### ISSUE THREAD

**Issue by AzzaAzza69** [d2phap/ImageGlass#1132]
Ie. disable file operations like renaming, delete, moving, etc.

**Comment by slashedstar** [comment]
I wanted it at least to have an option to enable a user prompt confirming the deletion of the file, if you press delete it just deletes the file blowI wanted it at least to have an option to enable a user prompt confirming the deletion of the file, if you missclick the delete button it just deletes the file 🤯

**Comment by fire-eggs** [comment]
>I wanted it at least to have an option to enable a user prompt confirming the deletion of the file, if you press delete it just deletes the file

ImageGlass behaves just like Windows Explorer: when you delete a file, it is sent to the Recycle Bin, where you can recover it.

**Comment by slashedstar** [comment]
> 

I'm aware of that, but unlike WE it doesn't have an option to ask if you really want to delete the file, which would prevent the hassle of searching the trash bin or going to the folder where the image was and pressing ctrl+z

**Comment by d2phap** [comment]
The option is here:

![image](https://user-images.githubusercontent.com/3154213/166460362-c8dee6f1-2d6b-41d7-95ae-306fc77026f2.png)

**Comment by d2phap** [comment]
You can disable the features of ImageGlass by using the setting `DisabledMenus`, see https://github.com/d2phap/ImageGlass/issues/1498#issuecomment-1482911514

For v9, open its `igconfig.json` file, the menu names are (begins with `Mnu` prefix):
https://github.com/d2phap/ImageGlass/blob/1bdc50dc2884571803da59545ebc4be0c0d96e23/v9/ImageGlass/FrmMain.Designer.cs#L1105-L1224

Example: Disable rotate left/right feature
```ts
// in igconfig.json
{
  "DisabledMenus": "MnuRotateLeft;MnuRotateRight"
}
```
