### ISSUE TITLE
Scaling an image.

### ISSUE THREAD

**Issue by jtagcat** [d2phap/ImageGlass#1133]
Didn't find an option, nor an issue mentioning scaling an image, and saving it.

Using different algorithms and keeping aspect ratio would be neat. [paint.net](getpaint.net) seems to have a functional scaling (resize) menu. Extra points for showing a preview for the algorithm/size.

**Comment by d2phap** [comment]
Hi, ImageGlass focuses on viewing features, you can edit the viewing image through Edit menu (using 3rd party app)

**Comment by jtagcat** [comment]
Why is cropping implemented then? [/nbr](https://tonetags.carrd.co/#masterlist)

Most image viewers I've come across have cropping and scaling. When the user reached to me¹, I was about to reach gThumb. Windows Photos also allows scaling. I can only name feh as the one that can't.

Opening a full-blown image editor for this seems overkill. Even then, the resize/scale options are hidden behind menus, and saving-closing is complicated.

¹ Image must be smaller/larger than x requirements.

**Comment by d2phap** [comment]
I understand that you want some features, but
- An image viewer to me, as its name - viewer, should not include any editing features.
- Cropping was added lately, uses "selection" function of ImageBox component, I don't have to write a lot to enable it.
- When talking about editing, I must care about quality loss, metadata, layers, EXIF data, color profile, gamma, and a ton more... I really don't have these kinds of knowledge to handle them. You can see some bugs about these issue. Data losing is always dangerous!
