### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by SteveThackery** [d2phap/ImageGlass#1140]
### System information:
 - Windows OS version: 21H1, 19043.1202
 - ImageGlass version: 8.2.6.6

### To Reproduce
1. Make sure the clipboard has an image stored
2. Start ImageGlass from the Start menu
3. Ctrl+V to paste the image into ImageGlass
4. Click the 'Save' icon

### Actual behavior:
ImageGlass reports an unhandled exception: "System.ArgumentException: The path is not of a legal form."

### Expected behavior:
ImageGlass should open the "File > Save As..." dialog.

### Screenshots:
![image](https://user-images.githubusercontent.com/79258223/133415512-a3ebfa3c-821f-41a8-92f3-14a12f9b7bda.png)

**Comment by d2phap** [comment]
duplicated of #1075

**Comment by SteveThackery** [comment]
Sorry!  Didn't realise it was a duplicate.
