### ISSUE TITLE
Color Picker (K): A hexadecimal color is created, but 2 characters too many

### ISSUE THREAD

**Issue by DarkTownStudios** [d2phap/ImageGlass#1142]
### System information:
 - Windows OS version: 10
 - ImageGlass version: 8.2.6.6

### To Reproduce
1. Just use the Color Picker (K)
2. Krita, Gimp, Illustrator, Photoshop will not accept copied value
3. 
4. 

### Actual behavior:
A hexadecimal color is created, but 2 characters too many
Appears to simply have added "FF" to each hexadecimal
.
(_Optional request issue_): 

### Expected behavior:

Simply  produces a resultant hexadecimal color code from sample in correct 6-character format.

### Screenshots:
![IG Color Picker Bug Hexadecimal 091521-FF](https://user-images.githubusercontent.com/35611078/133455521-75f6e917-eb8c-4d47-9f21-85c2594ff78f.jpg)

**Comment by d2phap** [comment]
You can change it in Settings > Tools
![image](https://user-images.githubusercontent.com/3154213/133458735-ce0eba62-5797-4811-b6cd-f2684b20e385.png)
