### ISSUE TITLE
Add option to save to same folder as original image

### ISSUE THREAD

**Issue by sken130** [d2phap/ImageGlass#1144]
Most of the times, I want to change the format of an opened image, and save it to the same folder as the original image.

So, I would hope that the File menu --> Save image as...  has an option to save to the same folder as the original image.

**Comment by sken130** [comment]
There is one more place I want to have such option.

Summary:

Menu --> File --> Save image as...
Menu --> Image --> Extract image pages...

**Comment by d2phap** [comment]
In v9.0.11, you can open `igconfig.json` file and change `OpenSaveAsDialogInTheCurrentImageDir` to `true`.

V9.1 will add UI for this setting:

![image](https://github.com/d2phap/ImageGlass/assets/3154213/4813cb73-9d7c-44f2-bb31-7463d9c230e7)

**Comment by d2phap** [comment]
Added the UI for this setting in [ImageGlass 9.1 Beta](https://github.com/d2phap/ImageGlass/releases/tag/9.0.11.529)
