### ISSUE TITLE
frmMain Designer error is not edit

### ISSUE THREAD

**Issue by byteschain** [d2phap/ImageGlass#1146]
### System information:
 - Windows OS version: 
 - ImageGlass version: 

### To Reproduce
1. 
2. 
3. 
4. 
![image](https://user-images.githubusercontent.com/19890858/136655458-0d542cdb-186d-4054-89c5-05fb5d9e5dc2.png)

**Comment by fire-eggs** [comment]
Please provide more information.

![image](https://user-images.githubusercontent.com/9809727/136662590-d6364fe1-7066-4ccb-a2bc-00ecbb1b8aa6.png)

**Comment by d2phap** [comment]
Closed, unable to replicate
