### ISSUE TITLE
Change UI to adapt Windows11

### ISSUE THREAD

**Issue by bai12-9em** [d2phap/ImageGlass#1147]
Will the author be willing to change the UI for windows11? @d2phap

**Comment by d2phap** [comment]
You can try ImageGlass Moon. It has the latest UI for Win11

**Comment by bai12-9em** [comment]
Thanks,l will try.Will this change be applied to the official version?

**Comment by d2phap** [comment]
> Will this change be applied to the official version?

This is shipped to IG Moon for testing first, then stable build
