### ISSUE TITLE
failing to open 42k image

### ISSUE THREAD

**Issue by FluffyDiscord** [d2phap/ImageGlass#1149]
### System information:
 - Windows OS version: 20h2 19042.1052
 - ImageGlass version: 8.2.6.6

### To Reproduce
1. download [this image (.png)](https://drive.google.com/u/0/uc?export=download&confirm=nOf9&id=10h1lCzVEFoAgBOP-mF0-7q43ZCaLHIzh)
2. open
3. wait a bit
4. see System.Drawing: Parameter incorrect error (translated)

### Actual behavior:
viewer hangs and fails to open the file

### Expected behavior:
open and view it normally

### Screenshots:
![image](https://user-images.githubusercontent.com/10332247/136854685-078129a3-c474-4755-9fb8-f4093c4b817e.png)

![image](https://user-images.githubusercontent.com/10332247/136854662-2e4c3733-40a0-4bed-baa4-0787325f3e16.png)

**Comment by fire-eggs** [comment]
This image vastly exceeds ImageGlass' maximum limits. The largest image IG can handle is about 17Kx17K, if I remember correctly ...

**Comment by d2phap** [comment]
thanks @FluffyDiscord, it's known issue and also a limitation: #272
