### ISSUE TITLE
Display the file name on task bar

### ISSUE THREAD

**Issue by bai12-9em** [d2phap/ImageGlass#1150]
When I set to open this setting   “Item key="IsUseEmptyTitleBar" value="True" “，logo and text are hidden. #915   （black frame）,this is what i hope.

But the title bar on the taskbar, the text is hidden  (red frame)，I hope it can be shown  （red  frame）
 @d2phap 

![屏幕截图 2021-10-14 222529](https://user-images.githubusercontent.com/92163936/137340433-c13e7ee8-63d0-4881-93a6-9142bcc6ed80.jpg)

**Comment by d2phap** [comment]
@bai12-9em 
It's not feasible bcuz the taskbar uses window title
