### ISSUE TITLE
ImageGlass crashes .NET framework when opening multi-selected images in zipped folder

### ISSUE THREAD

**Issue by LukeL19** [d2phap/ImageGlass#1152]
ImageGlass version 8.2.6.6 crashes the .NET framework when multiple .jpg images (12 in my case) **in a zipped folder** are selected at once, and attempted to be opened by right-clicking and selecting Open in the Windows context menu with ImageGlass set as default. It tries to open them all, but then the following error happens, among many .NET errors:

.NET-BroadcastEventWindow.4.0.0.2bf8098.0: ImageGlass.exe
The exception unknown software exception (0xe0434352) occurred in the application at location 0x00007FF850754F99.

Then the graphics display goes into square resolution with oversized icons, and only a restart fixes it.

This occurred on Windows 10 Home 64-Bit with last installed Windows update KB4023057 and last update I could find that mentioned .NET framework in the name being KB4601050.

Also, multi-select open works perfectly fine with the same files once unzipped.
And I have no trouble opening one image in the zipped folder.

**Comment by d2phap** [comment]
Thanks @LukeL19 
Can you check and follow the steps in this link: https://answers.microsoft.com/en-us/windows/forum/all/net-broadcasteventwindow-40000298bee0ccc-exe/f99b23a9-02a6-46ac-b83c-9e51174f098c
