### ISSUE TITLE
Sub-second slideshow interval

### ISSUE THREAD

**Issue by DannyBen** [d2phap/ImageGlass#1155]
It would be nice to be able to set slideshow interval as sub seconds: 0.3 for instance.

**Comment by d2phap** [comment]
Implemented in v8.7, you can set the interval as `4.3` but it must be >= 1 second.

**Comment by DannyBen** [comment]
> but it must be >= 1 second.

Why this arbitrary limitation? I needed sub-second, not fraction second...

**Comment by d2phap** [comment]
@DannyBen 
If the interval is smaller than 1, it may not be enough time for the app to load the image and render it on the viewer. If the image is large, it's sure that 1s is not enough.

I can reopen and implement this if you just use it for small images.

**Comment by DannyBen** [comment]
Thank you for your consideration.

Of course, you know your app better, so if you feel this is going to create a bad experience for some users, I understand - it is no big deal, I can manage either way.

My use case was this: I had thousands of files that I wanted to do a "flash review" on - for quality control. One second was too slow, so I ended up creating a script that presses space (or right arrow, done remember) every 0.3 seconds. The increased speed was important for me.

If this limitation can be removed without too much hassle and without harming other users, I would love it.

**Comment by d2phap** [comment]
Published v8.7.11.6 to remove this restriction!

**Comment by DannyBen** [comment]
Thank you!
