### ISSUE TITLE
Interlaced image

### ISSUE THREAD

**Issue by nisjeyenthiran** [d2phap/ImageGlass#1158]
### System information:
 - Windows OS version: 21H1
 - ImageGlass version: 8.2.6.6

### To Reproduce
1. open a .bmp file
2. 
3. 
4.

**Comment by fire-eggs** [comment]
Kindly provide a sample image which illustrates the problem. A ".bmp file" includes lots of possible format options (a DIB, a mono image, a pallete image, an OS/2 image, etc, etc). I have just successfully viewed several ".bmp" files of different formats successfully.

What exactly _is_ the problem? Image displays wrong? Wrong colors? etc

**Comment by d2phap** [comment]
Close due to lack of information
