### ISSUE TITLE
Add Alt-F shortcut for opening menu in the top-right

### ISSUE THREAD

**Issue by zhouyc98** [d2phap/ImageGlass#1159]
I think adding "Alt-F" shortcut to open the menu in the top-right is a good idea. Many apps use this shortcut like chrome and edge browser :)  
Currently, opening the menu is linked with a hotkey "`", but it is not intuitive and not easy to be pressed compared to Alt-F.

**Comment by d2phap** [comment]
Yea, it's changed to `Alt+F` in the latest build of IG Moon: https://imageglass.org/moon, also mentioned here:
https://github.com/d2phap/ImageGlass/issues/970#issuecomment-960497453
