### ISSUE TITLE
Some images are darker than normal

### ISSUE THREAD

**Issue by vamartid** [d2phap/ImageGlass#116]
Well I Tested it on many images I've made with Photoshop
and it appears that some images are a lot darker...
I tested it both in .png  and .jpg the same preview
I took a printscreen of the image itself from when I opened 
on the browser where the preview is normal and I saved it.
I opened it with ImageGlass again and it was ok.
So in conclusion
-ok means that the first image file could not be previewed right with
Imageglass which seem like a real issue to me who I use it as my primary Image viewer in windows 10.

**Comment by d2phap** [comment]
Thanks @vamartid 
Can you send me the photos that are not displayed correctly?
It will help help to test the issue.

**Comment by vamartid** [comment]
sure! here
http://image.prntscr.com/image/04a7c2cb04314f99bcded775c202d4c7.png

**Comment by kkots** [comment]
It displays fine for me. Could be that you configured Photoshop to alter
the view in some way and forgot about it. For example, there's a Display
Filters setting in GIMP under View menu which can adjust brightness, color
and color mode of the view (not the image).

**Comment by vamartid** [comment]
Forgive me if I am missing your point or your instructions but
the problem is not about Photoshop's options (I just installed it anyway and
the same hapens for images I had from before this photoshop installation)
as you can see the preview of the image is fine in the Firefox
but in the Imageglass preview it's not (and there is no option to fix it on Imageglass)
If you ensist there is a problem about my configurations at photoshop (~in photoshop the image looks
like the preview in firefox~ anyway if you do), please do sent me some more specific instructions about what to do, to fix this.
But I do not think a problem of Imageglass can be fixed from an option of Photoshop
I could just download an image rather than making it whith an image editor.
and i just followed [this :link:](https://forums.adobe.com/thread/963474) about reseting photoshop preferencies preview is still the same [:link: ](http://image.prntscr.com/image/c3c41c3d81884e0681972b9ab0ca6cf4.png) after rerunning both 3 programs also [here :link: ](https://www.sendspace.com/file/tq7yu0)are the old photoshop configurations

**Comment by d2phap** [comment]
Hi @vamartid 

I downloaded and try opening by ImageGlass, MS Photo, Chrome and Edge.
It displays fine.

![untitled](https://cloud.githubusercontent.com/assets/3154213/18010482/4461698c-6be3-11e6-903f-85c36de29d5b.png)

**Comment by vamartid** [comment]
Well this is strange.
I can not tell you if this is happening for more users or if it is happening only on me.
It is just happening.
After I saw your answer @d2phap  I tried to do a clean installation so I uninstalled the program and reinstalled it.
Same thing happening :cry: .
<img src="http://image.prntscr.com/image/f5c2c0dc6fdf4148bdd5b48fbb38cc96.png" alt="window">
Anyway if you somehow find a solution for me please do post it here.
Also if you need any info of my pc please do ask for them.
Thank you both for the answers.

**Comment by d2phap** [comment]
Hi @vamartid ,

Can you try downloading this build if it helps
http://www.imageglass.org/upload/moon/ImageGlass_3.x_24022017.zip

Phap



![image](https://cloud.githubusercontent.com/assets/3154213/23327142/ef79088c-fb41-11e6-9ee9-0c1dadf3f623.png)

**Comment by unkilling** [comment]
Hi
I have exactly the same issue with ImageGlass v4.5.11.27.
I don't understand neither why imaglass doesn't keep the black stroke around the picture. Just vansihed ...
![psvsig](https://user-images.githubusercontent.com/9696193/37553004-abb5329e-29bf-11e8-9534-cb3b6dd59011.jpg)

There is a weird transparency as well when i use "Show Checked Background".
This is a shame ImageGlass is a such good tool except this issues
![weirdtransparency](https://user-images.githubusercontent.com/9696193/37553072-d110c4ee-29c0-11e8-85a0-d720168ee96f.jpg)

**Comment by d2phap** [comment]
@unkilling 
How about other viewer, can you try on Photos, Chrome, Firefox?

**Comment by unkilling** [comment]
This is a PSD file. Other extensions are good, only PSD's got an issue.
So I can't open it whit Edge, Firefox, Chrome either Photo.This only thing is opening it with Irfanview. No problem with IRFV as you can see.
I tried on a second PC with the same version of Windows 10 Pro 1709 ans the same version of ImageGlass : same result
![irfanview](https://user-images.githubusercontent.com/9696193/37553374-2edda5c8-29c7-11e8-8cc8-ca6f53b391e8.jpg)

**Comment by fire-eggs** [comment]
Some Googling for "photoshop files appear dark" suggests a problem with the color profile of the monitor.

Users suggest Photoshop works around this, but other image viewers do not.

A quote from [some_forum](https://forums.envato.com/t/photoshop-colors-are-lighter-washed-out/77553/11)

> Guys, I’ve fixed this! Just realised that the problems started when I got my new monitor. So I checked the Color Management settings of Windows and found out that it was using the Samsung Monitor ICC Color Profile instead of the sRGB IC61blablabla one. So I’ve changed it and installed that sRGB profile as the main color profile of my screen.

**Comment by d2phap** [comment]
Hi @vamartid 
Can you try the ImageGlass Moon 5.5.12.8 which has a better Color Management in Settings dialog?

**Comment by d2phap** [comment]
No further info provided, closed this issue

**Comment by vamartid** [comment]
sorry for late response, the problem seems not to occur now
