### ISSUE TITLE
By default, the edit button can't work on Windows 11

### ISSUE THREAD

**Issue by xmha97** [d2phap/ImageGlass#1160]
Hi @d2phap 
By default, the edit button can't work on Windows 11!
![image](https://user-images.githubusercontent.com/23485114/141594791-565ba99c-3d8c-4009-b19c-d0d22c34c7de.png)
![image](https://user-images.githubusercontent.com/23485114/141594887-901e9ced-ca6e-4705-9a1e-e1c58cd9edf6.png)
Because there is no longer the mspaint.exe file in System32.
Solution:
The following file should be used:
"%LocalAppData%\Microsoft\WindowsApps\mspaint.exe"
![image](https://user-images.githubusercontent.com/23485114/141594976-8b918019-8a26-4d18-a4ea-fff0077128a7.png)
![image](https://user-images.githubusercontent.com/23485114/141595204-dabe4439-cb61-47c0-a599-c1a834c07e59.png)

**Comment by d2phap** [comment]
Windows 11 removes the verb of associated programs (ImageGlass uses verb `edit` to for the default editing). So in the latest build of IG Moon: https://imageglass.org/moon, in Windows 11, I try to use `mspaint.exe` for the default editing app.

@xmha97 please help to test.

**Comment by xmha97** [comment]
Thanks, everything worked fine.

**Comment by xmha97** [comment]
![image](https://user-images.githubusercontent.com/23485114/148671568-4bf8fe73-b006-48fe-8211-76ac8b5e9d98.png)
Apparently the problem still exists.

Please remove Paint from the optional feature and install it from Microsoft Store.
https://www.microsoft.com/en-us/p/paint/9pcfs5b6t72h
![image](https://user-images.githubusercontent.com/23485114/148671602-3174bfa1-2243-49ec-8cf5-4b77d02801e4.png)

**Comment by d2phap** [comment]
Thanks I will try

**Comment by d2phap** [comment]
Hmm, I cannot install MS Paint from Store
![image](https://user-images.githubusercontent.com/3154213/148679436-8d016d2a-ec71-4541-b33b-c3c8cf112cfd.png)

**Comment by xmha97** [comment]
What windows are you using?

Yes, you can not install the Paint package in Windows 10.

![image](https://user-images.githubusercontent.com/23485114/148683226-43196a52-cf67-49b8-9fd9-1911ce8aa709.png)

But in Windows 11 you can and the package is installed by default.
![image](https://user-images.githubusercontent.com/23485114/148683240-c734652c-2d60-4524-b506-301138322222.png)

To download Microsoft store packages:
1. Go to https://store.rg-adguard.net/
2. Enter this link: https://www.microsoft.com/en-us/p/paint/9pcfs5b6t72h
3. Download package:
![image](https://user-images.githubusercontent.com/23485114/148682813-d0bb480c-42ab-474b-b80c-f7327be319db.png)

**Comment by xmha97** [comment]
@d2phap I understood the problem.

I installed the MS Paint package on Windows 10 (not Windows 11), Please remove this condition:
![image](https://user-images.githubusercontent.com/23485114/148684972-d7ae0571-495c-4318-adbe-73522fcf6382.png)

Also, I can't edit if there is a space in the folder name,
For example: "D:\Pictures\My Wallpapers\Blue.png"
![image](https://user-images.githubusercontent.com/23485114/148685185-9c8263d1-000a-4ffd-866c-469f7535358c.png)
You should add two `"` in the filename:
![image](https://user-images.githubusercontent.com/23485114/148685122-17a22855-3999-4769-9f33-20ce2a0902bd.png)

**Comment by d2phap** [comment]
Can you try again, still v8.3.12.9:
https://imageglass.org/moon

The implementation is a bit different:

```cs
private void EditByDefaultApp(string filename) {
    var win32ErrorMsg = string.Empty;

    using var p = new Process();
    p.StartInfo.FileName = filename;
    p.StartInfo.Verb = "edit";

    // first try: launch the associated app for editing
    try {
        p.Start();

        RunActionAfterEditing();
    }
    catch (Win32Exception ex) {
        // file does not have associated app
        win32ErrorMsg = ex.Message;
    }
    catch { }


    // second try: use MS Paint to edit the file
    if (string.IsNullOrEmpty(win32ErrorMsg)) return;
    p.StartInfo.FileName = Environment.ExpandEnvironmentVariables("mspaint.exe");
    p.StartInfo.Arguments = $"\"{filename}\"";

    try {
        p.Start();

        RunActionAfterEditing();
    }
    catch (Win32Exception) {
        // show error: file does not have associated app
        MessageBox.Show(win32ErrorMsg, filename, MessageBoxButtons.OK, MessageBoxIcon.Error);
    }
    catch { }
}
```

**Comment by xmha97** [comment]
OK, thank you. <3
![image](https://user-images.githubusercontent.com/23485114/148690982-42a1990b-30c1-4b0d-9f41-609084892258.png)

But why is MSPaint not set by default?
![image](https://user-images.githubusercontent.com/23485114/148692271-54540634-d0d7-44d0-b03b-baaa34c3de2a.png)

**Comment by d2phap** [comment]
So ImageGlass tries to use the "associated app" for editing by using verb `edit`:
```cs
p.StartInfo.Verb = "edit";
```

For example: When install Photoshop, it registers verb "edit" to Windows registry the extensions for editing. If user hasn't specified the editing app, ImageGlass will open Photoshop instead of MS Paint.

**Comment by xmha97** [comment]
Ok, thank you for your explanation.
