### ISSUE TITLE
Keep the window always on top and hotkey

### ISSUE THREAD

**Issue by qaz075115961** [d2phap/ImageGlass#1161]
### The function that keep the window always on top is inconvenience
I usually will open a photo and will keep it on the top on my screen. But in this software, I have to click right mouse button and select the option. I feel there are too many steps to implement that.

### Add a button or a hotkey for the function
I think that maybe adding a button in the toolbar or a hotkey in the settings will be appreciated. And it is more wonderful to add both of them to the software.

### Hotkey
I just realize that there is no hotkey function in the software, that is doleful. Maybe you can consider allowing users to customize their own hotkey?

**Comment by d2phap** [comment]
Implemented in the latest build of IG Moon: https://imageglass.org/moon
Also requested in #970
