### ISSUE TITLE
Config files are missing (ImageGlass - June)

### ISSUE THREAD

**Issue by capkwantum** [d2phap/ImageGlass#1162]
### System information:
 - Windows OS version: Windows 10
 - ImageGlass version: June

### Actual behavior:

After the Installation of the current ImageGlass version, not all config files are created

### Expected behavior:
As described [here ](https://imageglass.org/docs/app-configs)there must be al least 2 config files.

### Screenshots:
![image](https://user-images.githubusercontent.com/66368797/141804995-17512c1a-1425-44b1-86d6-38a173075b25.png)

**Comment by capkwantum** [comment]
ImageGlass folder under %AppData% doesn't exist at all. If I update any settings the **igconfig.xml** will be updated. 
This is **not** a portable version.  Any  help would be appreciated!

**Comment by d2phap** [comment]
It's designed like that, you need to manually create the files in Start up folder.

After installed, and launched, IG creates igconfig.xml file in Config folder.

**Comment by capkwantum** [comment]
> It's designed like that, you need to manually create the files in Start up folder.
> 
> After installed, and launched, IG creates igconfig.xml file in Config folder.

Thank you for a such quick response!

As you can see in my screenshot the only file that is created after ImageGlass is installed is **igconfig.xml**
No files are created in %AppData% folder. So everything is stored in **igconfig** (C:\Programm files\ImageGlass)

**Comment by d2phap** [comment]
If IG has the write permission to create or write file in the installed folder, it will use the installed folder as configuration folder.

You can open Settings > General > Configuration directory to see where the configuration file is saved
