### ISSUE TITLE
Allow printing photos/contact sheets on black background?

### ISSUE THREAD

**Issue by victorhooi** [d2phap/ImageGlass#1163]
Is there any way in ImageGlass, when printing, to print photos/contact sheets on a black background?

(I know this would be more wasteful of ink, but it's something our users really want, and existing apps they use like PicCollage do it, hence there's some user inertia at play).

Also, it is often better when reviewing contact sheets/photos on a black background.

**Comment by d2phap** [comment]
@victorhooi ImageGlass just use the basic Print Pictures dialog of Windows for printing. So it does not support this.
