### ISSUE TITLE
Change order of EXIF data

### ISSUE THREAD

**Issue by shockergit** [d2phap/ImageGlass#1166]
Add an option to move file information from top to botton in Exif tab.

**Comment by shockergit** [comment]
It would have been nice if we can change the order of the list and the EXIF tab follows the main theme of the app

**Comment by d2phap** [comment]
@shockergit You can do it by changing the command line of Exiftool in Settings > Tools.
See https://github.com/d2phap/ImageGlass/issues/1187#issuecomment-989739105 for details
