### ISSUE TITLE
Imageglass only opens in second monitor.

### ISSUE THREAD

**Issue by InJustIs** [d2phap/ImageGlass#117]
I'm on W10 Anniversary edition, and imageglass refuses to open on my main monitor. I've tried opening it moving it over and closing it. Still opens on monitor 2, I've tried moving it with win+arrow keys then closing it. I've tried everything and it refuses to open on monitor 1.

It used to work fine with W10, I could move it to a monitor, close it and it would open in the monitor I last closed it in. Now it just opens on monitor 2 only.

**Comment by d2phap** [comment]
Hi @InJustIs 

Is monitor 2 your primary monitor? You can check it in the Settings of Windows

**Comment by InJustIs** [comment]
My monitor 1 is set to my primary monitor. The issue has since fixed itself, not sure what the problem was initially.

**Comment by zach-is-my-name** [comment]
Having the same problem.

**Comment by d2phap** [comment]
This issue is fixed.

ImageGlass Moon for testing: 
http://imageglass.org/upload/moon/ImageGlass_3.x_07032017.zip
