### ISSUE TITLE
CTRL + W to close Window

### ISSUE THREAD

**Issue by tngyeu** [d2phap/ImageGlass#1172]
Mình hay phải mở nhiều cửa sổ IG để làm việc.
Thói quen sử dụng CTRL + W ở các trình duyệt nên việc dùng ATRL + F4 để đóng cửa sổ nhanh rất bất tiện.

Mong là bác hỗ trợ thêm trường hợp này.

**Comment by tngyeu** [comment]
Mình vừa kiểm tra lại phần hot key 1 lần nữa thì thấy là IG sử dụng ESC để quit, mình có thể thêm thói quen này. Nên việc có sửa hay không thì cũng không quá quan trọng.
Tuy nhiên mình nghĩ CTRL W là 1 phím nóng khá thông dụng nên bác có thể xem xét.
Xin cảm ơn!

**Comment by d2phap** [comment]
Implemented in the latest build of ImageGlass Moon: https://imageglass.org/moon.

Lưu ý, kể từ phiên bản này IG sẽ mặc định khởi động cùng Windows và thu nhỏ xuống khay hệ thống khi đóng. Bạn có thể thay đổi hành vi này trong Settings > General > Others.
