### ISSUE TITLE
Shift drag in ImageGlass is tied to one of windows 10 keybinding

### ISSUE THREAD

**Issue by TKperson** [d2phap/ImageGlass#1173]
### System information:
 - Windows OS version: windows 10 home version 10.0.19042 build 19042
 - ImageGlass version: 8.3.11.21 [Portable]

### To Reproduce
1. open imagelgass
2. press f10 to switch to a "headless" mode
3. shift drag to move the image around

### Actual behavior:
ImageGlass window snaps to a certain position (see screenshot below)

### Expected behavior:

ImageGlass window moves freely when performing shift+drag

### Screenshots:

![Screenshot_2021-11-24_113601](https://user-images.githubusercontent.com/50115012/143495842-f7bcbe96-06b8-448f-9f75-646a32b7608f.png)

### Additional context:

shift drag in imageglass is tied to windows auto snaps key binding

i have been having this problem quite a while ago after i update my windows to a newer version ( i dont remember which one) it introduced this auto snapping function

**Comment by fire-eggs** [comment]
Maybe I'm missing something, I can't reproduce the issue as described.

Running Windows 10- 19042. IG is in headless mode (F10).

Click on IG and drag [_no_ shift] works. Using shift-drag doesn't "snap". 

Unless you're using it, you could turn off snap in Windows (settings, multitasking).

**Comment by TKperson** [comment]
It doesn't auto snap the sizing, it auto snaps positioning of the IG window.
I'll upload a video

https://user-images.githubusercontent.com/50115012/143507323-5b692050-c53a-4e10-90da-c736114b5ec1.mp4

After some digging, it turns out that one of my windows plugin (powertoys) was causing the problem

sorry for the inconvenience

**Comment by fire-eggs** [comment]
No problem, thank you for the update!
