### ISSUE TITLE
Trying to view a specific channel of an image results in a "Cannot access a disposed object." error.

### ISSUE THREAD

**Issue by Unordinal** [d2phap/ImageGlass#1175]
### System information:
 - Windows OS version: Windows 10 version 20H2
 - ImageGlass version: 8.3.11.21

### To Reproduce
1. Open any image file. (Tested with '.tif' and '.png' images).
2. Use "Shift+C" or go to "Menu -> Image -> View channels"
3. Select a channel other than 'All'.

### Actual behavior:
An error pops up in place of the image with the following text:

> ImageGlass cannot open this picture because the file appears to be damaged, corrupted or not supported.
> Magick.NET-Q16-OpenMP-x64: Cannot access a disposed object.
> Object name: 'MagickImage'.

### Expected behavior:
The image with the selected channel should appear normally.

### Additional context:
The image appears correctly until a specific channel is selected. Selecting the 'All' channel results in the image coming back and is able to be viewed properly once more.

**Comment by fire-eggs** [comment]
Confirmed with jpg as well.

Thank you for the report!

**Comment by fire-eggs** [comment]
Inappropriate use of `using` added to `ApplyColorChannel` on line 262 of Photo.cs:
```
                using var channelImgM = (MagickImage)imgM.Separate(magickChannel).First();
```
`channelImgM` is returned in "channel other than All" case but is disposed by the `using` resulting in the exception.

**Comment by d2phap** [comment]
Fixed this in the latest build of IG Moon:
https://imageglass.org/moon
