### ISSUE TITLE
Thumbnails for vector graphics files

### ISSUE THREAD

**Issue by m1karii** [d2phap/ImageGlass#1176]
Title.

**Comment by fire-eggs** [comment]
Are you referring to thumbnails in Windows Explorer?

**Comment by m1karii** [comment]
> Are you referring to thumbnails in Windows Explorer?

yes

**Comment by fire-eggs** [comment]
ImageGlass does not provide the thumbnails in Windows Explorer. You need to investigate using Explorer extensions such as [SageThumbs](https://www.cherubicsoft.com/en/projects/sagethumbs/).

**Comment by m1karii** [comment]
> ImageGlass does not provide the thumbnails in Windows Explorer. You need to investigate using Explorer extensions such as [SageThumbs](https://www.cherubicsoft.com/en/projects/sagethumbs/).

from what i know the default app (for any given fileformat) provides thumbnails. is this incorrect?

**Comment by fire-eggs** [comment]
>from what i know the default app (for any given fileformat) provides thumbnails. is this incorrect?

That is incorrect. Windows Explorer itself provides the thumbnails for basic formats, such as JPEG, BMP, etc; not via Windows Photos. Other thumbnails are provided via Explorer extensions. It is possible that various apps include an Explorer extension as part of their package. ImageGlass does not.

[E.g. I've been working on an [Explorer extension to provide thumbnails for ebooks](https://github.com/fire-eggs/DarkThumbs) (epub, mobi, etc). No epub reader I've ever used as the "default app" provided Explorer thumbnails for the ebooks.]

**Comment by m1karii** [comment]
In case anybody reads this in the future: https://github.com/tibold/svg-explorer-extension works well
