### ISSUE TITLE
Exiftool command preview doesn't update when changing exe

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#1177]
### System information:
 - Windows OS version: Win10
 - ImageGlass version: latest

### To Reproduce
1. Run imageglass
2. Open Settings, tools. Note the exiftool exe should already be selected.
3. Click on "select exif tool file" link, select a different exe than one already selected.

### Actual behavior:
The "command preview" does not update to show the new exe name.

### Expected behavior:
Command preview updates to show new exe name.

### Screenshots:

![image](https://user-images.githubusercontent.com/9809727/143778955-31160ad4-85a5-43ee-9592-d8e4a8675348.png)

**Comment by d2phap** [comment]
Should be no longer an issue with the standalone Exif viewer - [ExifGlass](https://github.com/d2phap/ExifGlass)
