### ISSUE TITLE
Exif tool dialog won't accept anything but "exiftool.exe"

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#1178]
### System information:
 - Windows OS version: Win 10
 - ImageGlass version: latest

### To Reproduce
1. Make sure there is no exiftool path in igconfig.xml
2. Run imageglass, load an image.
3. 'X' to invoke the Exif tool dialog.
4. Click on the link to find the exif tool.
5. Select a valid exe (e.g. the exiftool download from sourceforge is actually named "exiftool(-k).exe").

### Actual behavior:
The dialog reports "exif tool is not found or invalid". The dialog won't function unless an exe called "exiftool.exe" is used.

### Expected behavior:
A legit filename of the exiftool should be accepted. The Settings \ Tool window _will_ accept "exiftool(-k).exe". 

### Additional context:

The actual name of the exiftool exe when downloaded from sourceforge is "exiftool(-k).exe" [see attached zip]. As this is the actual name of the tool, it should be accepted.

[exiftool-12.36.zip](https://github.com/d2phap/ImageGlass/files/7614019/exiftool-12.36.zip)

**Comment by sjain882** [comment]
Same issue, however I never get a dialog, it just completely freezes imageglass. No dialogs visible in alt tab menu or taskbar. Also for some reason all imageglass windows open with "always on top" on by default, not sure why this is the case

also, it spawns two exif tool process when it happens. these never close themselves even if you quit imageglass from task manager

**Comment by d2phap** [comment]
This issue is fixed in the latest build of ImageGlass Moon 8.7: https://imageglass.org/moon.

**Comment by ScienceZone** [comment]
> This issue is fixed in the latest build of ImageGlass Moon 8.7: https://imageglass.org/moon.

After verification, the problem that ImageGlass cannot use Exiftool normally was indeed solved on V8.7, but there was a problem in later versions, only part of the content can be displayed in the Exiftool window, which should be the rightmost part, which seems to be enlarged and the window "dead". Is ImageGlass going downhill?
/
