### ISSUE TITLE
Image move distance too short

### ISSUE THREAD

**Issue by tokukawa01** [d2phap/ImageGlass#1179]
When I press arrow keys to move my view through the image (the action is discribed as pan leftright and pan updown in the software), it just moves a very short distance a single time, so I have to wait for a while every time, and it's quite annoying.

 I guess the problem is the move distance is set to a certain percentage of the **screen size**, and the problem will get more serious when zooming in.

As a solution, I think the move distance should be set to some percentage of the **image size**, which can avoid the zoom in problem mentioned above. And It's better to add an option in config for users to adjust the move percentage like the picture below (it's an option panel from NeeView). Thanks!

![未标题-1 拷贝](https://user-images.githubusercontent.com/95200968/143815038-70abbb57-e808-4935-a354-b9188002597e.jpg)

**Comment by d2phap** [comment]
Add panning speed options in Settings > Image (#1286).
Deployed to the latest build of IG Moon: https://imageglass.org/moon

![image](https://user-images.githubusercontent.com/3154213/154062970-f04f6635-c067-40be-821f-f1d47ccaaff5.png)

**Comment by tokukawa01** [comment]
Thank you very much!😊 I wait for this option a long time.



---Original---
From: "Phap Dieu ***@***.***&gt;
Date: Tue, Feb 15, 2022 20:39 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [d2phap/ImageGlass] Image move distance too short (Issue #1179)




 
Add panning speed options in Settings &gt; Image (#1286)
 

 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
