### ISSUE TITLE
Add 'Exit' button for toolbar

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#1182]
From Discord:

Senex Barbatus: FEATURE REQUEST:  In Settings/Toolbar/Available Buttons, add a button to close ImageGlass.  This way I only need one click to close the app.

**Comment by xmha97** [comment]
Similar: #611

**Comment by fire-eggs** [comment]
Right, thanks!

**Comment by d2phap** [comment]
Merge this to #611
