### ISSUE TITLE
Some more icons

### ISSUE THREAD

**Issue by herb52** [d2phap/ImageGlass#1183]
### Is your feature request related to a problem? Please describe.

Image Glass released a set on more than 71 icons for various image-types that can be opened.
### Describe the solution you'd like

It would be wonderful to add some more icons for filetypes that are missing: e.g. *.heif, *.heic, *.avif, *.cr3 and maybe others

**Comment by fire-eggs** [comment]
HEIC icon is part of 8.3 release.

Feel free to contribute some icons!

**Comment by d2phap** [comment]
Added icons for JXL, HEIF, CR3, AVIF, B64 for the next release
