### ISSUE TITLE
Option to hide file details in Exif tools

### ISSUE THREAD

**Issue by shockergit** [d2phap/ImageGlass#1187]
Please add an option to hide the file details in exiftool tab and bring exif data to top. And add an option to show only selected exif date (i dont want to see all the exif data i only want to see the lens details). I think this will reduce the exif data loading speed.

**Comment by d2phap** [comment]
You can exclude it by adding this command: `--File:All --ExifTool:All`

![image](https://user-images.githubusercontent.com/3154213/145171481-c29c7796-097a-4602-8f61-cb2888062e7e.png)

**Comment by shockergit** [comment]
> You can exclude it by adding this command: `--File:All --ExifTool:All`
> 
> ![image](https://user-images.githubusercontent.com/3154213/145171481-c29c7796-097a-4602-8f61-cb2888062e7e.png)

Thank you soo much. are their any commands to change order.

**Comment by d2phap** [comment]
You need to manually enter the tag groups in the order you want.
For example: `--File:All --ExifTool:All -Composite:All -PNG:All`. This excludes `File` and `ExifTool` group, and put `Composite` before `PNG`.

For details, you can check on their website: https://exiftool.org/#groups

![image](https://user-images.githubusercontent.com/3154213/145381890-57b4f52f-d54b-4a24-9859-0de9ce81453e.png)

**Comment by shockergit** [comment]
> You need to manually enter the tag groups in the order you want. For example: `--File:All --ExifTool:All -Composite:All -PNG:All`. This excludes `File` and `ExifTool` group, and put `Composite` before `PNG`.
> 
> For details, you can check on their website: https://exiftool.org/#groups
> 
> ![image](https://user-images.githubusercontent.com/3154213/145381890-57b4f52f-d54b-4a24-9859-0de9ce81453e.png)

Thank you soo much thats all i need.
