### ISSUE TITLE
Windows store version open image from explorer bug

### ISSUE THREAD

**Issue by ghost** [d2phap/ImageGlass#1189]
### System information:
 - Windows OS version: 11
 - ImageGlass version: 8.3.11.21

### To Reproduce
1. Install it
2. Open it and go to the settings to add image glass as the default.
3. Add image glass as the default in windows 11 panel
4. Try to launch a photo from the explorer

### Actual behavior:
Error message : "Windows can't acces to the peripheric..."

### Expected behavior:
Picture open

### Additional context:
If i copy the file in the presspaper and past it in the image glass it work so it must be a settings in the webstore app who is missing (to have access to photo)

**Comment by ghost** [comment]
i think the problem comme from the way to assign them to the picture, to assign them we must do launch it in admin.
maybe it can explain the access error he think the app must be administrator

**Comment by d2phap** [comment]
Yea, I'm fixing this

**Comment by d2phap** [comment]
I've just submitted a fix to the Store.
It will take hours to get approved from Microsoft testers, then you can update it throw MS Store.

Phap

**Comment by d2phap** [comment]
Just to update here, the MS tester requested more information for the submission of the fix because it uses `broadFileSystemAccess`. I already submitted again so just wait for their approval.

![image](https://user-images.githubusercontent.com/3154213/146208175-0170f71e-c2af-453d-a303-269f64e3cf33.png)

**Comment by ghost** [comment]
> Just to update here, the MS tester requested more information for the submission of the fix because it uses `broadFileSystemAccess`. I already submitted again so just wait for their approval.
> 
> ![image](https://user-images.githubusercontent.com/3154213/146208175-0170f71e-c2af-453d-a303-269f64e3cf33.png)

ok thanks to the update :)

**Comment by d2phap** [comment]
The fix is pushed to MS Store!

**Comment by ghost** [comment]
confirm it's fixed thanks
