### ISSUE TITLE
Memory leak: ImageGlass has an issue loading images from a specific folder, consuming 78% CPU and 8.3 GB of RAM causing my PC to hang

### ISSUE THREAD

**Issue by mauricecaaaaaben** [d2phap/ImageGlass#119]
The hang lasts for about a minute and a half before recourse usage goes back to normal and everything is fine. [Here's a picture of task manager during the hang](https://i.imgur.com/iD1z7Hv.jpg) (excuse the camera photo, hard to take a screenshot while hanging...).

**Comment by fire-eggs** [comment]
Using the sample images from #120 and #121, I've narrowed down the problem a little.

If I disable the `metadataCache` functionality of  `ImageListView`, the issue disappears. 

JPEG file analysis online suggests that at least one of the error images has some erroneous JPEG data, including some possible length discrepancies. If the metadata extractor isn't smart about checking lengths, it could be trying to allocate a negative amount of memory.

Unless I'm mistaken, we don't use the metadata nor the shellinfo data which the thumbnail bar collects.

**Comment by d2phap** [comment]
The original version of **ImageListView** has no issue with those files
https://github.com/oozcitak/imagelistview

I plan to upgrade it, too. https://github.com/d2phap/ImageGlass/projects/3

**Comment by d2phap** [comment]
@fire-eggs 
New discover:
Tried changing this line:
```csharp
e.Result = request.Adaptor.GetDetails (request.VirtualItemKey, request.UseWIC);
```
to
```csharp
e.Result = request.Adaptor.GetDetails (request.VirtualItemKey, false);
```
the issue is fixed!

Source:
https://github.com/d2phap/ImageGlass/blob/master/Source/Components/ImageGlass.ImageListView/ImageListViewCacheMetadata.cs#L237

**Comment by fire-eggs** [comment]
Fantastic! Simplest solution is best!
