### ISSUE TITLE
SVG files are blurred out

### ISSUE THREAD

**Issue by shockergit** [d2phap/ImageGlass#1191]
### System information:
 - Windows OS version: 10
 - ImageGlass version: 8.3.11.21 portable

When I open SVG files it's all blurred out in ImageGlass but it's opening high quality in other image viewers and Inkscape.
This is when the file opened in Inkscape.
![inkview_02oREMS7oP](https://user-images.githubusercontent.com/63154802/145721716-53eed754-6d2f-4c2b-b073-9ee66b3dee8f.png)

And this when opened in ImageGlass.
![ImageGlass_xmkNuiZR60](https://user-images.githubusercontent.com/63154802/145721624-29b0a56d-559a-46a7-9d00-c068e77af4ea.png)

**Comment by shockergit** [comment]
This is the original SVG file.GitHub doesn't support SVG uploading, so I renamed the format to PNG. Just rename the file format from png to svg.
![flatfoot](https://user-images.githubusercontent.com/63154802/145721844-e0ec5426-1b9b-40dd-83b9-41bf57ad874b.png)

**Comment by d2phap** [comment]
IG does not support for scaling SVG yet, see #421
