### ISSUE TITLE
[Enhancement] Support WASD instead of arrow keys

### ISSUE THREAD

**Issue by CasAdair** [d2phap/ImageGlass#1192]
### Is your feature request related to a problem? Please describe.
N/A

### Describe the solution you'd like
I'd like to see an option to replace the arrow keys with WASD

### Describe alternatives you've considered
I used to have a cheap keyboard that could swap wasd and arrow keys, but I bought an expensive keyboard and this one doesn't have that feature.

### Additional context
N/A

**Comment by d2phap** [comment]
You may wanna check AutoHotkey: https://www.autohotkey.com if it can help.
You can follow #608 for future updates about keyboard shortcut customization

**Comment by CasAdair** [comment]
I decided to buckle down and write a good script for this purpose. I hope anyone who needs it finds this well.
```
#IfWinActive ahk_exe ImageGlass.exe
$w::
    Send {Up}
    Return
$s::
    Send {Down}
    Return
$a::
    Send {Left}
    Return
$d::
    Send {Right}
    Return
$Up::
    Send {w}
    Return
$Down::
    Send {s}
    Return
$Left::
    Send {a}
    Return
$Right::
    Send {d}
    Return
