### ISSUE TITLE
Possibility to set to stay app in background

### ISSUE THREAD

**Issue by DanRotaru** [d2phap/ImageGlass#1196]
So I have 16 GB of RAM and I think this this option will be very necessary and helpful.
If one app process will be in background it will open images files much faster than if I just open and close app with all this components and features.
Just add checkbox in settings "Save in background" and if is enable and close app, this will save a background process.
Hope you will think about it.

**Comment by fire-eggs** [comment]
Doing this might help address the concerns about IG startup time as well.

**Comment by d2phap** [comment]
Implemented this in the latest build of IG Moon:
https://imageglass.org/moon

![image](https://user-images.githubusercontent.com/3154213/148556605-863cad58-a28e-4d0c-840e-e0b4c2ebb6f4.png)

**Comment by DanRotaru** [comment]
Unfortunately it is not fast enough, windows 10/11 default image viewer (with latest updates) opens more faster than ImageGlass

**Comment by d2phap** [comment]
> Unfortunately it is not fast enough, windows 10/11 default image viewer (with latest updates) opens more faster than ImageGlass

It's #794
