### ISSUE TITLE
Adding Option to Enable Image change alert

### ISSUE THREAD

**Issue by AutomationBoi** [d2phap/ImageGlass#1199]
The user  Can select the option to enable alerts after a set number of Images have been switched. Helpful in Slideshows mainly.

**Comment by AutomationBoi** [comment]
Working on It

**Comment by d2phap** [comment]
Ready in the latest build of IG Moon:
https://imageglass.org/moon

**Comment by AutomationBoi** [comment]
Hey excited to hear that, looking forward to see this in final build.
