### ISSUE TITLE
Support PSD and XCF formats

### ISSUE THREAD

**Issue by Baegus** [d2phap/ImageGlass#12]
As far as I know, there are some open source libraries that can parse PSD files very well (such as [this PSD plugin for Paint.NET](https://psdplugin.codeplex.com) or the one GIMP uses).

Would it be possible to add support for this format (or maybe even GIMP's XCF)?

**Comment by d2phap** [comment]
Thank you for your suggestion!

**Comment by d2phap** [comment]
Supported PSD format

**Comment by Baegus** [comment]
Really cool, thanks!
