### ISSUE TITLE
Memory leak (?) with certain files

### ISSUE THREAD

**Issue by Isiolith** [d2phap/ImageGlass#120]
Hello !

I encountered something similar too issue #119 , but I do not think that this is correlated with the containing folder.
For instance, these pictures are triggering the leak for me (3.2.0.16 with or without Image Booster option). They may have something in common, as the one from #119 : 

Pic 1 (initial image)
![Pic 1 (initial image)](https://cloud.githubusercontent.com/assets/3522346/18256424/7e1f4c50-73b5-11e6-94ab-e1e021600a6a.JPG)

Pic 2 (initial converted to png)
![Pic 2 (initial converted to png)](https://cloud.githubusercontent.com/assets/3522346/18256431/97d92256-73b5-11e6-9526-84b17ebb6428.png)

Pic 3 (initial converted to jpg 70% grey levels
![Pic 3 (initial converted to jpg 70% grey levels)](https://cloud.githubusercontent.com/assets/3522346/18256432/99cde6dc-73b5-11e6-8379-35076afa160a.jpg)

Feel free to merge both issues, but I felt it right to create a new one with a more appropriated title.

**Comment by d2phap** [comment]
Closed as duplicated issue of #119
