### ISSUE TITLE
ImageGlass registry keyes.

### ISSUE THREAD

**Issue by ghost** [d2phap/ImageGlass#1201]
### System information:
 - Windows OS version:  10 21H2
 - ImageGlass version: 8.3.11.21 and others

### To Reproduce
1.  Install ImageGlass
2.  Uninstall ImageGlass
3. ImageGlass does not remove registry keyes.
4. Explorer still shows ImageGlass as the default even after uninstallation.

### Actual behavior:
Since ImageGlass does not remove registry keys, Windows still takes it as the default application for opening files such as .png, .jpg, .ico

### Expected behavior:
 ImageGlass should remove these keys when uninstalling so that I don't have to remove them manually afterwards.

**Comment by d2phap** [comment]
For now you need to open Settings > File Type Associations, click on "Unregister extensions" to remove them. Duplicated of #546
