### ISSUE TITLE
Unable to press next image / prev images buttons unless window is focused

### ISSUE THREAD

**Issue by Sxderp** [d2phap/ImageGlass#1202]
### System information:
- Windows OS version:
-- Windows 10 Education [Basically same as Enterprise] 
-- 20H2 / 19042.1415
- ImageGlass version: 
-- 8.3.11.21

### To Reproduce
1. Open an image.
2. Unfocus the window (click on some other window)
3. Press the "next image" button
4. Press the "next image" button again

### Actual behavior:
First click focuses ImageGlass. Second click performs the action.

### Expected behavior:
Not having to double click.

**Comment by d2phap** [comment]
It's basic and normal behavior of all Windows software that you need to focus on the window to interact with it.

**Comment by Sxderp** [comment]
I'm not sure about that. It's pretty inconvenient to force a focusing click. The "Windows Photo Viewer" does not do this. I was hoping to make ImageGlass a close drop-in replacement as "Windows Photo Viewer" has trouble with newer files (weird coloring in .webp) and sometimes has issues opening files with certain ICC profiles.

There are two issues that I noticed. The problem I reported here is the first. Which is made worse by Windows lacking a proper sloppy-focus. The other being similar to #361 but only on a network share. However, deleting a file will refresh the list. I didn't bother making a report for that one, it's pretty edge-case.

---

As a small update. I tried with a few other programs on my Windows computer. Many of them do not require a focusing click before interaction with the elements.
Things I tested (may not be indicative, a number of them are cross-platform):
- Windows Settings
- Firefox
- Steam
- Audacity
- Notepad++

The one program that required focusing was Paint.NET. Maybe this is a .NET thing?

Edit again. Turns out the Paint.NET thing is only partially. You can't instantly click on the "menu bar" items (File / Edit / Image), but using the tools, changing tools, or even pressing "print" does not require a focusing click.

**Comment by fire-eggs** [comment]
Yeah, there are some technical challenges involved. Windows tells the app that it has been "activated" but not _how_ it has been activated. I.e. was the app restored from minimized; executed; alt+tab; or clicked on ? 

Without trying it out, I can't tell off-hand if / when the "mouse click" event is provided to the app (before the "activated"? after?).

**Comment by Sxderp** [comment]
Maybe I'm not understanding the issue, but does it matter if the window receives the activation event before or after? If an element receives a click even then it should be handled regardless if the window was recently activated. The only time the order may matter is if you wanted to enable / disable certain elements based on window activation. I don't think that inconsistency would be good UX.

**Comment by Sxderp** [comment]
Can this be reopened for review? As I've pointed out the statement in the second comment:

> It's basic and normal behavior of all Windows software that you need to focus on the window to interact with it.

Is not accurate.

**Comment by d2phap** [comment]
Thanks @Sxderp! 
Shipped this to the latest build of IG Moon: https://imageglass.org/moon

**Comment by d2phap** [comment]
In v8.6.7.13, this setting is off by default because it causes issue: Left/Right keyboard control keeps losing focus
https://groups.google.com/g/imageglass/c/u1tAUsF2RN8/m/y6rOyEqOAAAJ

You can enable it in `igconfig.xml` file by changing `AutoFocusToolbarOnHover` value to `true`.

**Comment by Sxderp** [comment]
It would seem that this is caused by an unconditional focus to the toolbar on hover. The issue can likely be solved by only focusing the toolbar (or another part of the program) if the window is not already active. Examples on how to check if the window is already active are linked below. Some of them seem like they would be expensive checks. Unfortunately I don't have the development environment setup at this time to do any testing. If I get around to it I'll post a PR or new issue with further discussion.

https://stackoverflow.com/questions/7162834/determine-if-current-application-is-activated-has-focus
https://stackoverflow.com/questions/7049989/how-to-determine-whether-my-application-is-active-has-focus
