### ISSUE TITLE
E-Mail Button

### ISSUE THREAD

**Issue by Pendora2017** [d2phap/ImageGlass#1203]
Hi there,

it would be very nice if the ImageGlass Bar (where all Icons are located e.g. File Open, Zoom could get an E-Mail Button.

on click behavoir: opens the Windows standard E-Mail Programm with a new Mail and automatically attach the Image

Maybe you would prior this feature request if i spend more beer? 😂

**Comment by AuerBau** [comment]
Hi there,

is will be great when we have this button. Is there a plan to implement this?

**Comment by d2phap** [comment]
You can do it in ImageGlass 8 with Share dialog

![image](https://user-images.githubusercontent.com/3154213/209429841-9cfa34f5-f970-4e9d-9cfb-853e37802da2.png)
