### ISSUE TITLE
Scroll Image Speed Setting

### ISSUE THREAD

**Issue by siblount** [d2phap/ImageGlass#1204]
### Is your feature request related to a problem? Please describe.

Currently, scrolling through a large portrait is painfully slow when using Up and down arrow keys.
### Describe the solution you'd like

A setting that improves the scrolling of images through Up down . Max - up to 4x the current speed.

**Comment by d2phap** [comment]
Deployed to the latest build of IG Moon: https://imageglass.org/moon
