### ISSUE TITLE
Startup

### ISSUE THREAD

**Issue by xmha97** [d2phap/ImageGlass#1205]
IG created a startup shortcut in path below:
"%AppData%\Microsoft\Windows\Start Menu\Programs\Startup"
![image](https://user-images.githubusercontent.com/23485114/148671864-764974c1-652a-494e-86e3-e76c12214ffd.png)

Please use registry for add startup item not startup shortcut.
![image](https://user-images.githubusercontent.com/23485114/148671901-8cdf4085-28f4-4e45-b1aa-721479c94b62.png)

Thanks.

**Comment by d2phap** [comment]
@xmha97 any reasons or explain why? I am not aware of the difference

**Comment by xmha97** [comment]
1. The folder tends to be favorited by users, easy for them to create a shortcut there.
1. The registry key tends to be favorited by installers.
1. Most apps use the registry key to startup.
1. Apps run earlier in the registry key when the computer is started.

**Comment by d2phap** [comment]
Done this in IG Moon: https://imageglass.org/moon

**Comment by xmha97** [comment]
Thanks.
