### ISSUE TITLE
Support relative path for ExifTool

### ISSUE THREAD

**Issue by xmha97** [d2phap/ImageGlass#1208]
Hi, I installed ExifTool using Chocolatey.
```powershell
choco install exiftool
```
"C:\ProgramData\chocolatey\bin" added to %Path% and I can use it on Terminal:

![image](https://user-images.githubusercontent.com/23485114/148698564-7ac26673-7752-427a-abf1-446a8d457409.png)

ImageGlass can't detect installed ExifTool.

![image](https://user-images.githubusercontent.com/23485114/148698619-0cb06938-f5d4-46cc-89ea-2d7497179b18.png)

**Comment by d2phap** [comment]
ImageGlass currently only support absolute path for `exiftool.exe`

**Comment by d2phap** [comment]
This issue is fixed in the latest build of ImageGlass Moon 8.7: https://imageglass.org/moon. You will need to directly edit the `igconfig.xml` file to use the relative path of exiftool

**Comment by xmha97** [comment]
Thanks 🙏
But I'm using the ImageGlass v9.0 Beta 3.

**Comment by d2phap** [comment]
ImageGlass 9.0 beta 4 will have a new exif viewer tool as a standalone app.

**Comment by xmha97** [comment]
> ImageGlass 9.0 beta 4 will have a new exif viewer tool as a standalone app.

Thanks 🙏
