### ISSUE TITLE
[bug] System freeze

### ISSUE THREAD

**Issue by SomeRed** [d2phap/ImageGlass#121]
I am on Windows 10 Professional, some pictures freeze my whole system when I open them with ImageGlass, (the default image viewer of Windows 10 works fine), here is an example 
![20120524020052](https://cloud.githubusercontent.com/assets/8383836/18368785/254c3574-7622-11e6-9585-2c8800776cfe.jpg)

If you need more images like that one, I have many of them, I took them using the camera of an old chinese device that looks like a PSP.

**Comment by d2phap** [comment]
Closed as duplicated issue of #119
