### ISSUE TITLE
Ctrl+Shift++/- keys to rotate images

### ISSUE THREAD

**Issue by xmha97** [d2phap/ImageGlass#1210]
In many apps (like Adobe Acrobat Pro), the rotation is with the following buttons:

`Ctrl`+`Shift`+`+` -> Rotate to Left
`Ctrl`+`Shift`+`-` -> Rotate to Right

I need this feature for ImageGlass
Thanks.

**Comment by d2phap** [comment]
It's about shortcut customization, so follow #608
