### ISSUE TITLE
Rotating an image may corrupt it.

### ISSUE THREAD

**Issue by masterofobzene** [d2phap/ImageGlass#1215]
### System information:
 - Windows OS version: 10
 - ImageGlass version: 8.3.11.21

### To Reproduce
1. open image
2. try rotating it

### Actual behavior:
Sometimes the image will not save the changes, and sometimes it corrupts the archive leaving the file unusable.

### Expected behavior:
Rotate the image and save the changes.

**Comment by fire-eggs** [comment]
Phap shipped an update via [ImageGlass Moon](https://imageglass.org/moon) which hopefully addresses this issue. See issue #1134 for example.
