### ISSUE TITLE
Light lines in context menus

### ISSUE THREAD

**Issue by DEHNCKA** [d2phap/ImageGlass#1218]
### System information:
 - Windows OS version: 7 SP1 x64
 - ImageGlass version: 8.3.12.12_x64 (8.3.11.21 x64)

Please remove the light lines in the context menus:

- context menu of the main menu;
- context menu in the viewing area;
- context menu for system tray icon.

![2022-01-16_22-18-21](https://user-images.githubusercontent.com/59572905/149672832-7ccc1014-d23b-49ae-925b-0709dc42c137.png)![2022-01-16_22-21-35 (2)](https://user-images.githubusercontent.com/59572905/149672909-e60834a4-25e8-4bc4-a135-f4566921ed4d.png)![2022-01-16_22-23-23](https://user-images.githubusercontent.com/59572905/149672845-6b54ebf9-747b-44b0-b039-8ce603711fa1.png)

P.S. Noticeable only with a dark design.

**Comment by d2phap** [comment]
Fixed this in the latest build of ImageGlass Moon 8: https://imageglass.org/moon and [ImageGlass Moon 9.0 Beta 1](https://github.com/d2phap/ImageGlass/releases/tag/9.0.1.514).

![image](https://user-images.githubusercontent.com/3154213/169306992-c62a157c-cf8e-4ca2-bbba-1776528ca573.png)
