### ISSUE TITLE
Accent colors and substrates (backlight)

### ISSUE THREAD

**Issue by DEHNCKA** [d2phap/ImageGlass#1219]
### System information:
 - Windows OS version: 7 SP1 x64
 - ImageGlass version:  8.3.12.12_x64 (8.3.11.21 x64)
### My notes:
1. Currently the color "accentcolor" (in the theme file) is used for highlighting in the toolbar. At the same time, according to my findings, this color (parameter) is also used for text links. It is not right. Text links should have a separate color that is not used elsewhere.I suggest renaming "accentcolor" to "accentlinkcolor" and only use it for text links.

This wish is due to the fact that the text should have a more contrasting color in relation to the background, and in the current configuration, the text is lost and I can’t do anything when creating a theme, because there are no alternatives - either I make the text not contrasting, or I make it too bright substrate (backlight) in the panels.Here's how text gets lost in different places on the interface:

![2022-01-11_02-56-22 (2)](https://user-images.githubusercontent.com/59572905/149675674-963e69fc-63a9-442a-8cfc-d333bd0e7d88.png)
![2022-01-16_23-52-02](https://user-images.githubusercontent.com/59572905/149675688-8ef5d418-975d-4f7f-b744-d2a35a8753c0.png)

2. What to do with the rest of the "substrates" (highlights)? Right now the **toolbar** uses this sequence:

accentcolor ― accentlightcolor ― accentdarkcolor
( indicator   ―         hover          ―          click         )

― it needs to be changed to this:

accentdarkcolor ― accentlightcolor ― accentdarkcolor   <--- (the sequence must be the same everywhere)
(     indicator       ―        hover          ―          click         )

The same goes for the **"Pages"** tool. At the moment, the highlight in the tool works like this:

accentlightcolor ― accentdarkcolor ― accentlightcolor
(       hover         ―          click           ―          hover       )

― should be changed to this:

accentdarkcolor ― accentlightcolor ― accentdarkcolor   <--- (the sequence must be the same everywhere)
(       hover          ―         click           ―          hover       )

I'm talking about this:

![2022-01-16_02-56-01](https://user-images.githubusercontent.com/59572905/149676208-3bc91032-ce41-475e-9ec0-46fd5cf2d716.png)
![2022-01-16_02-56-11](https://user-images.githubusercontent.com/59572905/149676210-3c0fbb3b-0bd3-4ec4-9c70-afbc5ce9c9cf.png)
![2022-01-16_02-56-22](https://user-images.githubusercontent.com/59572905/149676214-cde69323-19c6-4252-958c-7f8443f41c28.png)

![2022-01-16_02-58-24](https://user-images.githubusercontent.com/59572905/149675999-5ef8fe93-3ec1-4eb6-9fbd-4e026ccebd7a.png)
![2022-01-16_02-58-34](https://user-images.githubusercontent.com/59572905/149676001-25924909-e596-4fe9-be99-f036e43c1fb8.png)

**Comment by d2phap** [comment]
ImageGlass 9 will have a revamp UI, and all of UI-related issues are resolved in [branch v9](https://github.com/d2phap/ImageGlass/tree/v9). It's still in-progress, and does not have a beta version. You can check the source code in the branch, or follow the progress at https://github.com/d2phap/ImageGlass/projects/11

**Comment by DenisVelicanov** [comment]
And how can I understand this? It's just that it's hard for me to figure it out here, the devil will break his leg ... I'm writing in vain, since this is no longer relevant or what?

**Comment by DenisVelicanov** [comment]
Or did you send it to fixes for version 9?
