### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by lovebdsobuj** [d2phap/ImageGlass#122]
Some of thing you can take for implement. 
- Add Next & Prev icon beside image on Image Viewing Screen. Like your website 

![](https://i.imgur.com/DaCjCAH.png)
- Add three color on `Show checked background` `Ctrl+B`. 1. Black, 2. White, 3. Transparent (user can change `white` color to others, white color is user defined)
- Add Upload to Imgur feature.
- User can set different app for photo edit by settings.
- Implement self image properties viewer.

**Comment by d2phap** [comment]
Hi @lovebdsobuj 

Thanks for your suggestion!
I will consider and investigate my time for future version

Phap

**Comment by d2phap** [comment]
Implemented "User can set different app for photo edit by settings." @ https://github.com/d2phap/ImageGlass/pull/175

**Comment by d2phap** [comment]
The feature:
> Add Next & Prev icon beside image on Image Viewing Screen.

is WIP #448
