### ISSUE TITLE
Unreadable characters in the topic title / missing the right font

### ISSUE THREAD

**Issue by DEHNCKA** [d2phap/ImageGlass#1220]
### System information:
 - Windows OS version: 7 SP1 x64
 - ImageGlass version: 8.3.12.12_x64 (8.3.11.21 x64)
### My notes:
I understand that the author wanted to depict kaomoji near the name of the design theme (more precisely, near the first item in the list of design themes), but this may not work for someone (these characters are not deciphered for me). This is probably due to the lack of the desired font in the system.

This needs to be fixed, for example, by replacing unreadable characters with readable ones, or by including the desired font in the program package, or by completely removing this creativity from the first line (I personally support the latter option).

Here's what I'm talking about:

![2022-01-17_00-13-55](https://user-images.githubusercontent.com/59572905/149676854-9091c752-137e-4e1e-818a-75da3d32c124.png)

**Comment by d2phap** [comment]
This issue is fixed in [ImageGlass 9.0 beta 5](https://github.com/d2phap/ImageGlass/releases/tag/9.0.5.726)
