### ISSUE TITLE
Buttons for closing and docking tool windows.

### ISSUE THREAD

**Issue by DEHNCKA** [d2phap/ImageGlass#1222]
You can [use](https://aka.ms/SegoeFonts) the "[Segoe MDL2 Assets](https://docs.microsoft.com/en-us/windows/apps/design/style/segoe-ui-symbol-font)" font from Microsoft for symbols in buttons in tool windows (upper right corner). So these buttons will be better perceived functionally and look more aesthetically pleasing.

In addition, the proportions of these buttons must be brought to those adopted in Windows 10-11. Currently the buttons are oblong like in Windows 8... .

![2022-01-17_01-55-35 (2)](https://user-images.githubusercontent.com/59572905/149680237-1ccae475-ab2b-4fec-a544-0d3e0e7780ff.png)

These symbols should be used in these buttons (these are only samples for viewing, you do not need to insert these images into the interface in the literal sense):

![e894](https://user-images.githubusercontent.com/59572905/149680353-c99697ff-f159-4639-ab49-18629be5520a.png)
![e840](https://user-images.githubusercontent.com/59572905/149680354-0f2cd6fd-4243-4490-a3bd-9fd1fc3b6984.png)

And to tell you the truth, I don't quite understand why you hid the titles from the explorer in the tool windows and made your own custom...

**Comment by d2phap** [comment]
[ImageGlass Moon 9.0 beta 3](https://github.com/d2phap/ImageGlass/releases/tag/9.0.3.1225) uses the native window title bar:

![image](https://user-images.githubusercontent.com/3154213/209429784-33584cf5-7e13-4337-bc2a-d9a8ee5ede8a.png)
