### ISSUE TITLE
The item "Send to ..." in the context menu of the program instead of the item "Edit image (editor name) ..."

### ISSUE THREAD

**Issue by DEHNCKA** [d2phap/ImageGlass#1223]
Replace the "Edit image (editor name) ..." item with the "Send to ..." item with a drop-down context submenu that will contain several editors. Make the list of editors and paths to them (to activate them) and so on customizable (in the program settings, in the "Edit" item).

This will help avoid the tedious process of customizing editor pinning for each format and give users more choice of editors. Not all editors open all formats, some are generally very selective. Previously, there was a link in the context menu of ImageGlass to "Open with ..." in Windows, but then it stopped working,which is very bad, it became uncomfortable.

It would also be nice to link the "Send to ..." item to the selection of "flags" on the thumbnails ([here](https://github.com/d2phap/ImageGlass/issues/1211#issue-1098483421)), so it will be possible to send several selected files at a time to the desired editor directly from ImageGlass.

The process, in general, is similar to the action of the "Send to ..." item in Windows Explorer, only everything will be done through ImageGlass. I think this will be useful for those who work without running Explorer to save RAM resources.

Thus, we do not restrict the user, but provide him with an independent choice of editor from the context submenu. When clicking in the image area - we send only this image to the editor of our choice from the context submenu. When clicking in the thumbnail area (after selecting several thumbnails beforehand) - we send several files in a batch to the editor of our choice from the context submenu.

**Comment by DEHNCKA** [comment]
I hope I chewed everything thoroughly.

**Comment by d2phap** [comment]
In v9.0, you can add external apps and assign hotkey to open it in Settings > Tools.
