### ISSUE TITLE
Substrate (backlight) under the navigation arrows

### ISSUE THREAD

**Issue by DEHNCKA** [d2phap/ImageGlass#1224]
I mean this:
![2022-01-16_03-51-53](https://user-images.githubusercontent.com/59572905/149683111-16c90138-3d2c-498b-9867-a7adc36f9df8.png)
![2021-11-22_16-00-05](https://user-images.githubusercontent.com/59572905/149683113-181d2373-85fa-43ca-b31e-2a6aaf3e5d72.png)

The size and shape of the background (highlight) under these arrows needs to be corrected. The grid for these arrow icons looks like this:

![12-2-1160x470](https://user-images.githubusercontent.com/59572905/149683681-4789387d-c9eb-482b-9f18-765d85d4044e.png)

This needs to be corrected, because. icons with arrows do not visually fit on the current background (highlight). They need some "air", free space. In addition, the background (highlight) should adapt to the theme, just as it happens, for example, on the toolbar. To do this, it is better to add a separate parameter in the theme file (for example,"navigationarrowshighlightcolor") with transparent(!) color support.

P.S. The background (highlight) should not be a circle, but a square with rounded corners.

**Comment by DEHNCKA** [comment]
Should look like this:
48x48px
![next](https://user-images.githubusercontent.com/59572905/149688147-c7561509-38d3-434b-be8f-55fd2f4d7db5.jpg)

**Comment by DEHNCKA** [comment]
Here is the grid:
[ios7-grid.zip](https://github.com/d2phap/ImageGlass/files/7878481/ios7-grid.zip)

**Comment by DEHNCKA** [comment]
Here is my source:
[next.ZIP](https://github.com/d2phap/ImageGlass/files/7878491/next.ZIP)

**Comment by d2phap** [comment]
Updated the navigation buttons in ImageGlass Moon 9.0 beta 1:
https://github.com/d2phap/ImageGlass/releases/tag/9.0.1.514

![image](https://user-images.githubusercontent.com/3154213/169642251-cb5dfb29-412f-4826-8709-34b94aad4d7a.png)
