### ISSUE TITLE
Dots in the counter

### ISSUE THREAD

**Issue by DEHNCKA** [d2phap/ImageGlass#1226]
In the counter (in slideshow mode), replace the symbol ":" with this symbol: "∶". This one will be centered (relative to line height).

I'm talking about this:
![2021-11-22_16-27-57](https://user-images.githubusercontent.com/59572905/150017451-8a5f0a56-e728-47d4-9a0c-3a1f8c865246.png)

**Comment by DEHNCKA** [comment]
It will look like this picture (this is in another application):
![2022-01-19_01-00-18](https://user-images.githubusercontent.com/59572905/150018055-ca0d6031-1a43-4d0b-8cd7-2b9ac988af08.png)

**Comment by DEHNCKA** [comment]
My final version:
![2022-01-19_01-03-38](https://user-images.githubusercontent.com/59572905/150021358-294baa34-83df-4c24-ae4e-847718b9112f.png)
[2022-01-19_01-03-38.zip](https://github.com/d2phap/ImageGlass/files/7892475/2022-01-19_01-03-38.zip)

#1227

**Comment by DEHNCKA** [comment]
Note: The dark gray border is just a background, like a viewport in a program or an image.

**Comment by d2phap** [comment]
Fixed the colon in v8.7
