### ISSUE TITLE
Substrate (backlight) under the time counter

### ISSUE THREAD

**Issue by DEHNCKA** [d2phap/ImageGlass#1227]
The background (highlight) under the time counter should adapt to the theme of the program (have its own transparent color from the theme file). I represent it like this:

![2022-01-19_01-03-38](https://user-images.githubusercontent.com/59572905/150021497-d5b2a9ba-38e2-40f5-b483-85c1784d8707.png)
(Segoe UI - 48 pt; substrate (backlight) - based on iOS7 Icon Grid)
[2022-01-19_01-03-38.zip](https://github.com/d2phap/ImageGlass/files/7892484/2022-01-19_01-03-38.zip)

**Comment by DEHNCKA** [comment]
Note: The dark gray border is just a background, like a viewport in a program or an image.

**Comment by d2phap** [comment]
I will keep the simple dark/light for the slideshow timer
