### ISSUE TITLE
Icons for "ExifTool" and "Page navigation" in the toolbar

### ISSUE THREAD

**Issue by DEHNCKA** [d2phap/ImageGlass#1228]
Other tools have icons in the toolbar, but "ExifTool" and "Page navigation" don't, why? It would be logical to allow the user to add these tools to the toolbar.

**Comment by d2phap** [comment]
You can add a custom toolbar button with any SVG icon in Settings > Toolbar > Toolbar buttons... > Add a custom buttons...
