### ISSUE TITLE
Second row in the toolbar

### ISSUE THREAD

**Issue by DEHNCKA** [d2phap/ImageGlass#1229]
Sometimes not all icons fit on the toolbar (for example, when the program window is pinned to half the screen) and they begin to hide in the context menu of the toolbar. This is not very convenient. Instead, I suggest that the icons move to the second row (third, fourth, etc...) when the panel is "squeezed" into a narrow state.

**Comment by d2phap** [comment]
I decide not to implement this. It requires complex toolbar layout change.
