### ISSUE TITLE
Crop tool: adjust the background (highlight) to the theme of the program

### ISSUE THREAD

**Issue by DEHNCKA** [d2phap/ImageGlass#1230]
Set the "highlight" color when cropping the image to the "accentdarkcolor" setting, and also set the color of the lines (grid borders) to the "accentcolor" setting (this is also the color of the text links for now).

It would also be nice to work on grid anchors: they should be round and follow the theme of the program (in the color sense), but not stand out too much (not burn) and at the same time not be lost against the background of the "backlight". Perhaps their color should be tied to the "accentcolor" parameter (the same parameter as for the grid borders),and when you hover over them with the mouse pointer, they will slightly increase their brightness ("accentlightcolor").

**Comment by d2phap** [comment]
This is done in [ImageGlass Moon 9.0 beta 3](https://github.com/d2phap/ImageGlass/releases/tag/9.0.3.1225)

![image](https://user-images.githubusercontent.com/3154213/209428453-fab81990-c437-4124-b619-21d857f71a4f.png)
