### ISSUE TITLE
Translations for dialogues

### ISSUE THREAD

**Issue by DEHNCKA** [d2phap/ImageGlass#1232]
Add translation strings to language packs. We need to translate these dialogues:

![2022-01-19_02-19-09 (2)](https://user-images.githubusercontent.com/59572905/150029150-72ccefc2-c356-4bec-b11a-c5af2673d7d7.png)
![2022-01-19_02-19-32 (2)](https://user-images.githubusercontent.com/59572905/150029155-55911da4-3cd0-4afa-b2e1-435a917d65c4.png)
![2022-01-19_02-19-57 (2)](https://user-images.githubusercontent.com/59572905/150029158-2bee9c7a-a17a-461f-ad6b-82e6ece735f7.png)

**Comment by d2phap** [comment]
Done in v9
