### ISSUE TITLE
Notification sound: the ability to choose your sound file

### ISSUE THREAD

**Issue by DEHNCKA** [d2phap/ImageGlass#1233]
The title speaks for itself. Add the ability to select an individual file from a directory specified by the user (folder selection). Not all sound schemes in the system are suitable for the sound of the image switching notification in the slideshow. Changing the sound scheme every time is a strange undertaking, it is easier to designate the desired audio file.

**Comment by d2phap** [comment]
To keep IG simple, I will close this as not planned.
