### ISSUE TITLE
Mouse wheel scrolling not working in thumbnails panel

### ISSUE THREAD

**Issue by DEHNCKA** [d2phap/ImageGlass#1235]
### System information:
 - Windows OS version: 7 SP1 x64
 - ImageGlass version: 8.3.12.12_x64 (8.3.11.21 x64)
 
### My notes:
Hovering the mouse pointer over the thumbnail area and attempting to scroll through the thumbnails by scrolling the mouse wheel does NOT scroll the thumbnails. Moreover, if the "zoom" action is assigned to scrolling the mouse wheel in the settings, then this leads to a change in the image scale - this is normal, but this should not happen, when the mouse pointer is over the thumbnail area.

**Comment by d2phap** [comment]
Just found there is a similar ticket here #1235
