### ISSUE TITLE
GIF playback

### ISSUE THREAD

**Issue by DEHNCKA** [d2phap/ImageGlass#1236]
This has already been said, but I will add. It was proposed to add a play / pause button in the middle to the "Page navigation" tool so that you can continue playing the gif-file from the frame where you left off. I support it, I also really need this opportunity.

I propose to correct the Ctrl + Space command as well,so that when you press this combination again, playback does not start from the first frame, but from the current one.

**Comment by d2phap** [comment]
This feature is implemented in v9.0 beta 4.
- Play/Pause buttons are added to Page navigation tool
- Also playback resumes from the paused frame, not restart from the first one
