### ISSUE TITLE
The white rectangle on the start

### ISSUE THREAD

**Issue by yura-f** [d2phap/ImageGlass#1239]
### System information:
 - Windows OS version: win 10 pro (x64) (16Gb RAM)
 - ImageGlass version: 8.3.11.21 (x64)

### To Reproduce
1. Just open any image from ImageGlass

### Actual behavior:
You will see a white rectangle and after ~500ms showing the image

### Expected behavior:
I don't want to see the white rectangle on the start :)

### Screenshots:
![This is an image](http://joxi.net/0KAgJ8fEvPy32l.jpg)

**Comment by d2phap** [comment]
Should be fixed in v9.0 beta
