### ISSUE TITLE
Shortcut name

### ISSUE THREAD

**Issue by xmha97** [d2phap/ImageGlass#1245]
Please remove the version from the shortcut file name.
![image](https://user-images.githubusercontent.com/23485114/150466105-1baf6847-0b2d-42d9-a2b5-42c9849726f1.png)
Only apps mentioned their version in their names that can be installed into some versions at the same time. For example Visual Studio and Photoshop.

**Comment by xmha97** [comment]
It seems that this issue was fixed on "ImageGlass Kobe 8.4.2.22 - Hotfix".

**Comment by d2phap** [comment]
yeah
