### ISSUE TITLE
Registry error when `Start with OS` is unchecked

### ISSUE THREAD

**Issue by Chris1320** [d2phap/ImageGlass#1247]
### System information:

 - Windows OS version: 21H2
 - ImageGlass version: 8.4.1.22

### To Reproduce
1. Open settings.
2. Uncheck `General > Others > Start with OS`.
3. Click "Apply" or "Save". (You might need to click it two or more times for the error to show)

### Actual behavior:

An error saying "No value exists with that name.". The title of the window says "Deleting SubKey SOFTWARE/Microsoft/Windows/CurrentVersion/Run"

### Expected behavior:

Everytime I click "Apply" or "Save" while "Start with OS" is unchecked, I don't expect an error to occur.

### Screenshots:

![image](https://user-images.githubusercontent.com/74256376/150470102-75a92e1a-600a-4706-ac9c-90a3b849e78f.png)

### Additional context:

I think, everytime I click "Apply" or "Save", the program tries to remove the registry entry that will autorun the program on OS start.

**Comment by d2phap** [comment]
Thanks @Chris1320 
Already paused the update notification. I will push a fix soon.

**Comment by d2phap** [comment]
This should be fixed in v8.4.2.22 now

**Comment by Chris1320** [comment]
Cool, thanks!
