### ISSUE TITLE
Error message when closing ImageGlass (Store Version)

### ISSUE THREAD

**Issue by drandarov-io** [d2phap/ImageGlass#1249]
### System information:
 - Windows OS version: Windows 11
 - ImageGlass version: 8.4 (Store)

### To Reproduce
1. Uninstall ImageGlass 8.3 from GitHub
2. Install ImageGlass 8.4 from Store
3. Disable "Start on login" and "Keep in background"
4. Save settings and close ImageGlass

### Actual behavior + Screenshot:
![image](https://user-images.githubusercontent.com/13102251/150499058-e69df75b-1774-49cf-82b1-bca13010a33a.png)

### Expected behavior:
No error message.

### Additional context:
Bought the store version to not get the spider.com integration. Now it's buggy :/

**Comment by d2phap** [comment]
Hi @drandarov-io 
The fix (v8.4.2.22) is submitted to the Store, but the review process of Microsoft takes few days.
I will update here again once it's published.

**Comment by drandarov-io** [comment]
Thanks for the fast info! :)

**Comment by d2phap** [comment]
The fix arrived to the Store!

**Comment by drandarov-io** [comment]
Can confirm it's fixed. Thanks :)
