### ISSUE TITLE
Can't show file type icon

### ISSUE THREAD

**Issue by xmha97** [d2phap/ImageGlass#1251]
On registry, for all file types set "PhapSoftware.ImageGlass"
`.JPG`=PhapSoftware.ImageGlass
`.BMP`=PhapSoftware.ImageGlass
`.PNG`=PhapSoftware.ImageGlass

![image](https://user-images.githubusercontent.com/23485114/150515433-1f53e510-771f-40e6-90d0-5dda9567f4d1.png)
(See desktop icons)

This was not the case before and a key was set for each type of file. For example:
`.JPG`=ImageGlass.AssocFile.JPG
`.BMP`=ImageGlass.AssocFile.BMP
`.PNG`=ImageGlass.AssocFile.PNG

**Comment by d2phap** [comment]
This should be fixed in the MSI x64 of v8.5. It took me 2 hours to key in all extensions into AdvancedInstaller

**Comment by xmha97** [comment]
> This should be fixed in the MSI x64 of v8.5. It took me 2 hours to key in all extensions into AdvancedInstaller

Thanks.
