### ISSUE TITLE
spider.com integration is user hostile and should be removed

### ISSUE THREAD

**Issue by martinlindhe** [d2phap/ImageGlass#1252]
In the new version spider.com has been integrated. This allows internet users to abuse your IP doing any kinds of network requests proxied thru you.

This is user hostile, can lead to criminal charges of users of this software and is highly immoral.
Please reconsider dropping this or expect FORKS.

**Comment by a1xon** [comment]
Why not switch to a paid version? Uninstalled the app as soon as I noticed the bloatware.

**Comment by martinlindhe** [comment]
@a1xon This is not about the choices I am able to make, but about the spider.com malware being injected in normal user installs without their understanding of what that means.

**Comment by a1xon** [comment]
@martinlindhe sorry. missunderstanding. you are completly right. I meant instead of stuffing maleware into a free version you could completly switch the payment model to a paid version and don't offer a free version at all anymore.

**Comment by d2phap** [comment]
Alright, I guess people do not like this, so I will remove version 8.4!
The Store release is not affected.

**Comment by MightyKnight** [comment]
I believe, in contrast to *static* things like ads, promotions or similar, the main problem with the Spider integration is that it's not predictable what exactly they (a third party) does with your device (e.g. here any traffic could be routed over your IP).

Very positively surprised by you listening to feedback and changing it, I was about to drop ImageGlass.
I'm sure you'll figure out a better way to financially support the project.

One thing you should definitely do is promote the Microsoft Store version more directly, I previously didn't know you could even buy ImageGlass. Now I'll do just that. It's hard to notice on the website, and you could also display something when launching the program the first time. 

Thanks.

**Comment by martinlindhe** [comment]
@d2phap Thank you for reconsidering this!
I would like to continue to support you so I will purchase a Microsoft Store version for now.

**Comment by Yakabuff** [comment]
@d2phap I love how you added literal malware to a supposed "lightweight image viewer".  How can anyone trust you after this lmao maybe you add a crypto miner next time?

**Comment by d2phap** [comment]
@Yakabuff what should I do now? I became international criminal after 1 night, and all people from nowhere can come and judge me. Before this integration, I made an announcement to poll people's reaction  on ImageGlass discord server for the first release of IG Moon. There were very little comments, I guessed people were fine with the changes, it's been there for 2 weeks. When it came to the official release, I expected there would be more comments, but in fact, people have been insulting me more. When @martinlindhe came and commented, I realized the Spider service may lead to a bigger issue so I deleted the release.

Until now, I have been not living by the people donation. ImageGlass does not make enough money to maintain a better web server. It's just got a code signing certificate after I published to MS Store for 2 months. I created and maintained the app for myself, and feel happy when it helps people. You can see lots of FOSS already discontinued, or abandoned.

> How can anyone trust you after this lmao maybe you add a crypto miner next time?

I've never met the "anyone", so they should trust themselves, not a stranger. Instead, see the commits history, verify it themselves, involve in the discussion, contribute to the project, raise **polite** questions, that's the point of OSS. People come, people leave, I am not paying money to keep them for my fame.

**Comment by Yakabuff** [comment]
@d2phap  It should go without saying that adding malware that connects you to a literal botnet goes against the essence of FOSS.  You shouldn't have to ask or raise a poll for something like this.  

>ImageGlass does not make enough money to maintain a better web server [..] I am not paying money to keep them for my fame.

It's funny how you're somehow painting yourself as the victim and twisting it so it's somehow our fault that you had to do this because you don't get enough donations.  Nobody's holding you at gunpoint to continue this project. Find a better monetization technique or find more affordable hosting solutions (Github pages?).  

>Instead, see the commits history, verify it themselves,

https://github.com/d2phap/ImageGlass/pull/1217/commits/97c716cf1ad23535b7b6840ba189270e440e742e

Are we supposed to verify the binary blobs you slip into your project under the ambiguous commit message `restructuring external dlls`? This was weeks ago before any sort of official announcement (No, your Discord server does not count).  Speaking of which, why didn't you poll this on a more public space like Twitter or on Github issues?

**Comment by d2phap** [comment]
> Instead, see the commits history, verify it themselves,
> 97c716c
> Are we supposed to verify the binary blobs you slip into your project under the ambiguous commit message restructuring external dlls?

Ridiculous, why didn't you count these? Or I MUST write in details every single commit? I'm not working for a company here.

![image](https://user-images.githubusercontent.com/3154213/150624649-efd075a4-94f3-4aa9-93ea-1de403ccb70d.png)


> This was weeks ago before any sort of official announcement (No, your Discord server does not count). Speaking of which, why didn't you poll this on a more public space like Twitter or on Github issues?

If you really followed the project, you would always see all of my announcements for IG Moon were made in Discord. And why "your Discord server does not count"? It's listed on the website as 1 of the 3 official support channels: https://imageglass.org/support.

> idk, you've already shown your true colours. Feel free to keep whatever malware you've added in the MS store version though. I doubt anyone will notice or care.

Haters always hate, I will just let them go. Also, I am not welcome your comments here anymore, you come with full of sarcasm and criticism. Let the polite people continue.

**Comment by eebssk1** [comment]
> @d2phap It should go without saying that adding malware that connects you to a literal botnet goes against the essence of FOSS. You shouldn't have to ask or raise a poll for something like this.
> 
> > ImageGlass does not make enough money to maintain a better web server [..] I am not paying money to keep them for my fame.
> 
> It's funny how you're somehow painting yourself as the victim and twisting it so it's somehow our fault that you had to do this because you don't get enough donations. Nobody's holding you at gunpoint to continue this project. Find a better monetization technique or find more affordable hosting solutions (Github pages?).
> 
> > Instead, see the commits history, verify it themselves,
> 
> [97c716c](https://github.com/d2phap/ImageGlass/commit/97c716cf1ad23535b7b6840ba189270e440e742e)
> 
> Are we supposed to verify the proprietary binaries you slip into your project under the ambiguous commit message `restructuring external dlls`? This was weeks ago before any sort of official announcement (No, your Discord server does not count). Speaking of which, why didn't you poll this on a more public space like Twitter or on Github issues? Are ordinary people supposed to dig through your git commits to check if the image viewer they just downloaded connects them to a botnet?
> 
> > what should I do now?
> 
> idk, you've already shown your true colours. Feel free to keep whatever malware you've added in the MS store version though. I doubt anyone will notice or care.

Fork, remove, compile, don't talk shit. If you really want, be polite.

**Comment by Yakabuff** [comment]
@d2phap  Last time I checked (a month or two ago), your ImageGlass server had ~100 people. Sure, it is an official support channel but compared to the number of stars this project has, you might as well be talking to a wall at this point. 

>Haters always hate, I will just let them go. Also, I am not welcome your comments here anymore, you come with full of sarcasm and criticism. Let the polite people continue.

Should we not be critical about your decision?  Are people just "haters" if they don't want malware in their image viewer?

**Comment by silverwings15** [comment]
being constructively critical is one thing, but i don't see the point of your inflammatory posts made _after_ the dev has quickly rectified his mistake

**Comment by Yakabuff** [comment]
> being constructively critical is one thing, but i don't see the point of your inflammatory posts made _after_ the dev has quickly rectified his mistake

I don't see how any of my posts are inflammatory but yeah, I agree.  If the dev refuses to apologize or shoulder any responsibility other than "I already removed the botnet why are you hating" then you're absolutely right, this discussion is pointless

**Comment by silverwings15** [comment]
sorry he didn't mail you a personal apology along with some roses to meet your personal standard of what fixing a screw-up should entail. i hope you will find a software more suitable for your needs going forward, where lip service is more important than actions. shouldn't be too hard 👍‍

**Comment by martinlindhe** [comment]
@Yakabuff you are not adding to the discussion.

**Comment by andranoxi** [comment]
>fixing a screw-up should entail

This "screw-up" shouldn't've happened in the first place. For something calling itself "a lightweight, versatile image viewer" to also make you essentially an exit node makes zero sense.

Kinda goes against that whole tagline. I'd understand it a *little* more if it were an opt-in "help the developer pay the bills" kind of deal but to be enabled by default and adding unknowing users to what is essentially a botnet is uncalled for.

**Comment by silverwings15** [comment]
all fair points, but he realized his mistake soon enough and did the right thing by pulling the new 'feature' entirely, instead of leaving it in and making it opt-in, or worse, persisting with his initial decision like other projects i've seen in the past would've done.

**Comment by d2phap** [comment]
Hi, the version 8.5 is already released:
- No more Spiderman no way home
- Options: Start with OS and Continue running background is unset by default
- Others features and bugfixes are same as v8.4 (which was already withdrawn)

I will close this, if you want to continue the discussion here, feel free to create another one in Discussion.
Thank you!

**Comment by digitalblossom** [comment]
@d2phap One last thing, check out OpenCollective and Librepay if you want ro receive donations. DarkReader makes 100 thousand USD per year via the former.

Github sponsors would be an option as well of course.

**Comment by d2phap** [comment]
Thanks @digitalblossom 
I think I put quite a lot of options already :)

**Comment by worldsdream** [comment]
When I saw the release with spider, I had my concerns too.

Thanks for listening to the users/customers @d2phap. You're always friendly and bring ImageGlass to the next level. I will buy ImageGlass in the Microsoft store.

I would have loved to buy it from your website with a key. I am not so in favor of Microsoft store apps. Just to let you know.

**Comment by Hexawolf** [comment]
Why is this happening? I remember the controversy around MuseScore and Audacity, then some open-source author (who also happened to be making explosives at home), now a photo viewer!.. Who's next? Krita? Blender? What kind of dystopia this is, instead of building tighter communities to survive the advent of neo-feudalism, we are trying to f*ck with each other. People were fine with doing open-source software for decades now. But why it is now that unsuspecting users are obligated to suffer? What if some users simply can not afford making a donation, isn't free software about _sharing and caring_ in the first place?

What happened here - and was happening in other projects lately - is inherently political, so with all respect, I do advise reading about Marx's theory of alienation. It is tightly related to what is _really_ happening all around. Because regardless of all the political stuff and memes that divide us, we all are doing _something_, and there is an inherently scary path in getting alienated from what you do, from the process of doing it, from your own nature that initiated what you were doing in the first place - and from the people around you who work with you and use the product of your work. **Things will only get worse if we become disconnected from each other.** I just can't get into deep depths here, nobody will understand and it is probably not worth the effort anyway, given author's attitude.

> I've never met the "anyone", so they should trust themselves, not a stranger.

This is where it all went downhill. I give little hopes that you guys will see what is wrong with this, because it takes a good grounding in philosophy - or some good psychedelics - but it is inherently wrong indeed. Really, having grounding in economics also gives a clue at why this is wrong - because what you do is called [Public Good](https://en.wikipedia.org/wiki/Public_good_(economics)) and you all use these daily. Heck, you use the Internet, tap water, electricity, even if you work remotely!

It's not the time and place, but if anyone will stumble upon this (and if this won't get deleted) I really suggest thinking about this, instead of blindly taking sides and assuming knowledge you don't have. The damage is done and sealed in history, but what lessons can we take from the entire situation? What do we achieve by alienating from each other? _Why_ are we harming each other, _who_ told us not to trust strangers?

**Comment by spiderwest** [comment]
I am the CEO at Spider.com. We vet all of our users, you likely know who our customers are, they are large fortune 500 companies. Businesses that need pricing on Amazon products or positions in Search Engine results. The large enterprises with all this data don't make it easy to gather at scale. So by using a few queries from thousands of different IPs we can use the collective wisdom of the crowd. Secret shoppers have exist for about 500 hundred years and pre-date the Internet. You use this service every time you shop at a grocery store. The price of a bag of rice or can of beans will be reasonable to competing grocery stores. 

The great news is we are not processor or memory heavy. In fact we don't compute anything local on machines and the bandwidth we use is the equivalent to downloading a few images. We sponsor projects to help developers and keep software free. We all know that software takes hundreds of hours to develop and maintain, so symbiotic relationships are good for the community. 

We always require disclosure and being upfront with users. We require an informed decision on the part of the software's user. I am happy to answer questions about how Spider works. I can assure you we are GDPR compliant, we don't care about collecting user data we only gather data that is publicly available online about products and companies from public facing websites.

**Comment by geraldsnm** [comment]
@d2phap Can you also consider adding another paid option that doesn't require installing and running UWP executables?

I'm against TPM 2.0 / Windows 11 / UWP and any/all movement towards turning powerful unrestricted desktop computers into the mobile app license model that started with the iPhone and is now starting to infect desktop's with the "we sell you a subscription to license the software for a period of time, you never own the software" model where you don't own your own system that you paid for agenda.

Please create a x32/64 binary and the option to buy a lifetime license for the product, you could accept payment on Paypal and still leave the MS Store App version available for other users who are not offended by the MS Store licensing model as I am.

**Comment by d2phap** [comment]
@geraldsnm people buy Store version because they want the smooth update process of Store app. 
I will think about it after I implement the autoupdater.

**Comment by CardealRusso** [comment]
> Hi, I decided to remove the Spider service from ImageGlass since all people don't like it. Instead, I will find the suitable model for the app.
> 
> Currently, version 8.4 is already removed from download. ImageGlass Store version is not affected.
> 
> I will work on an update this weekend. Thank you! Phap

you're cringe
