### ISSUE TITLE
Custom Install location broken with 8.5

### ISSUE THREAD

**Issue by SaiBork** [d2phap/ImageGlass#1260]
### System information:
 - Windows OS version: 11, 21H2, 22000.434
 - ImageGlass version:  8.5.1.22

### To Reproduce
1. Start x64 msi installer
2. Select Custom
3. Select MainFeature
4. Click Browse to change location
5. Installation Type either (both cause an issue)
6. Continue installation

### Actual behavior:
During the install screen above it shows the correct location, but installs into default location based on "Installation Type"   
"Only for me" - This installs it in the user's C:\Users\USERNAME\AppData\Local\Programs\ImageGlass
"Everybody" - This installs it in "C:\Program Files\ImageGlass"

### Expected behavior:
1. As it's an update it should know where it is already without me having to pick an installation location
2. It should install in the given location, not ignoring the Custom location chosen

### Additional context:
- I ran an Uninstall and tried again, but same results each time.  
- It seems that the choice of Installation Type should be a step before being able to Customise the setup.  
- If you click "Next" after "Installation Type" and then "Back" twice to "Custom Setup" you can see the path has changed

**Comment by d2phap** [comment]
Confirm the bug

**Comment by SaiBork** [comment]
I've updated the report with more details as I've now seen what part causes the issue. It's the "Installation Type" that breaks it. So better off to install an old version and then overwrite with the portable new release at this point.

**Comment by d2phap** [comment]
@SaiBork fixed this, you can download the MSI x64 again

**Comment by SaiBork** [comment]
@d2phap Done and confirmed working with the order changed. Thanks for the quick update.

**Comment by worldsdream** [comment]
When I saw the release with spider, I had my concerns too.

Thanks for listening to the users/customers @d2phap. You're always friendly and bring ImageGlass to the next level. I will buy ImageGlass in the Microsoft store.
