### ISSUE TITLE
Changing Settings with Mouse Scrolling

### ISSUE THREAD

**Issue by vuslatx** [d2phap/ImageGlass#1268]
Excuse me for my bad English. 

### System information:
 - Windows 11 Pro
 - ImageGlass version: Imageglass 8.5 portable without spiderman

1.  On settings panel, options change with mouse scrolling. I think it is unnecessary and causes confusion. I want to scroll down option page, but option changes. On blank space, no problem but i shouldn't have to do for this. 

### Expected behavior:
If i want to change options, i must click on this option. I mean for option, "list options."

### Screenshots:
![image](https://user-images.githubusercontent.com/3154213/232967370-cf1848e5-240d-4757-b554-8932eab29792.png)

**Comment by fire-eggs** [comment]
Yes, I see the issue.

Part of this is "standard windows control behavior". Once input focus is on a combobox for example, clicking the up/down arrows moves between the options in the list. Defined by Microsoft, not IG.

A work-around is to use the Tab key to move focus between the controls. As focus moves further down the controls, the panel will scroll.

[For some reason, in the Images section, the initial focus is on the "number of images" spinner. By Windows standard, initial focus should be on "Find images in child folder".]

**Comment by d2phap** [comment]
Should not an issue in IG 9 because it uses web control for the select box.
