### ISSUE TITLE
Right-click menu's frame

### ISSUE THREAD

**Issue by ghost** [d2phap/ImageGlass#1271]
### System information:
 - Windows OS version: Windows 10 21H2
 - ImageGlass version: 8.5.1.22 x64

### To reproduce
1. Open any right-click menu.

### Actual behavior:
Top and left frame line has higher width from bottom and right. Not sure if this is intentional or not.

### Expected behavior:
All lines having same width.

### Screenshots:
![image](https://user-images.githubusercontent.com/60701198/150842331-f14cea66-ac90-4358-aaa7-5e9b43b5c12a.png)

**Comment by fire-eggs** [comment]
Duplicated by issue #1218
