### ISSUE TITLE
Windows Store/native apps icons lost at windows search ONLY

### ISSUE THREAD

**Issue by DimMan88** [d2phap/ImageGlass#1274]
I have a problem since last summer. 

Windows Store/native apps icons lost at windows search ONLY. 
Tried sfc /scannow (no problem found) , 
Tried Dism /Online /Cleanup-Image /CheckHealth (no problems found)
Tried Dism /Online /Cleanup-Image /ScanHealth (no problem found)
Tried rebuild icon cache, delete Google drive (many people says that is gdrive problem)...no solution yet.
Maybe this is not a Microsoft's fault and its an Imageglass bug?

![unknown](https://user-images.githubusercontent.com/71668463/151131182-1f5a30ae-31da-4ee8-a834-a5dcc101bae9.png)

### System information:
 - Windows OS version:  Windows 10 Pro x64 21H2 19044.1469
 - ImageGlass version: 8.5.1.22

**Comment by d2phap** [comment]
There is a solution here: https://github.com/d2phap/ImageGlass/issues/664#issuecomment-1018246003
