### ISSUE TITLE
Associate PDF files

### ISSUE THREAD

**Issue by xmha97** [d2phap/ImageGlass#1275]
ImageGlass can open the first page of the PDF files.

This is great for me because I can extract PDF books covers in JPG format.

[![ImageGlass](https://cdn.discordapp.com/attachments/818852544859209751/935098302519705640/unknown.png)](https://discord.com/channels/818852544859209748/818852544859209751/935098303106932756)

Please associate PDF files with ImageGlass.

![image](https://user-images.githubusercontent.com/23485114/151253474-dd5b2b98-c5c6-400d-addd-cd877edd0f20.png)

You might think that PDF format is only used for documents and is not a good format for images.
In response, I have to say that most graphics programs support PDF format.

# Inkscape
## Open
![image](https://user-images.githubusercontent.com/23485114/151250922-ddc7c7a5-3324-4fce-8f3a-bf4bcf2087af.png)
## Save
![image](https://user-images.githubusercontent.com/23485114/151251158-47501fad-3b87-4cb0-9ed8-54da45d72c8b.png)

# Photoshop
## Open
![image](https://user-images.githubusercontent.com/23485114/151249551-b5f90cfa-6a9d-4c51-a5ed-49d5a8d792df.png)
## Save
![image](https://user-images.githubusercontent.com/23485114/151249722-bdd89732-b467-497a-80ba-79edc5c15fdc.png)

---

Same as #280

**Comment by d2phap** [comment]
@xmha97 ImageGlass uses Magick.NET to read the files. The reason I don't add PDF into default extensions is it requires Ghostscript to read.

You can check all of supported formats of it here:
http://imagemagick.net/script/formats.php#supported

**Comment by xmha97** [comment]
OK, I'll close this issue.
