### ISSUE TITLE
Is it possible to adjust the size of thumbnail manually?

### ISSUE THREAD

**Issue by TheCGDF** [d2phap/ImageGlass#1278]
### Is your feature request related to a problem? Please describe.
Thumbnails look too small on my HDR screen.
![ImageGlass_EJwiQDEAOa](https://user-images.githubusercontent.com/17256673/151652910-b14de3da-c38b-4b9f-b074-2d4e53a87581.jpg)

### Describe the solution you'd like

I tried to adjust the width of the thumbnails, but it just becomes two columns.
![image](https://user-images.githubusercontent.com/17256673/151652906-10e28227-9b47-49e6-b463-c45a8fb74c5c.png)

### Describe alternatives you've considered

If it is impossible to make the size fit the width automatically, it's ok to have an option in settings menu.

### Additional context

With some DPIs, the thumbnails will be blocked by the scrollbar.
![image](https://user-images.githubusercontent.com/17256673/151653033-99838869-f82b-4009-9286-3d3305ba8b78.png)
The display area of thumbnails and scrollbar should not coincide.

**Comment by d2phap** [comment]
Merged this to #678
