### ISSUE TITLE
Image Properties display integrated in a sidebar

### ISSUE THREAD

**Issue by olippuner** [d2phap/ImageGlass#1279]
### Making it the best tool to delete images in large shooting sets, based on fully informed decisions 
 A great software with potential to become the favorite tool for photographers that need to scan hundreds or even thousands of photographs of one shooting. These are frequent numbers, eg. for animal photographers as I am. In Postprocessing of the first tasks is to trim down those fast numbers of photos as quickly and seamless as possible. Just recently I had to halving 2000 Images with more than 0.5 TB from Canon R5 in a first rough selection, then halving it again to 500 images and so on.

Any interruption on this workflow, even for a few seconds weight heavily. Currentl the user in such a workflow has to 

```
FOR K = 1 to thousands of time:
_______show the popup:
_______select details tab:
_______scroll down the the sections of relevance:
_______read those values, memorize them or note them by hand if you can't memorize them all:
_______the close the popup.
Check the next image
```

When shooting under the pressure of the action shutter speeds, ISO and aperture are often varied. While deleting, these criteria are of great importance. Eg. often I have to find the optimum between ISO/Noise and Shuter-speed/Motion-stop. 

Reading the image properties each time in a popup greatly ruins this workflow. Also I want to switch back and forth between different images while reading the image properties before deciding which images can  be deleted.

### Image Properties displayed directly in a sidebar of the actial window plane
1. Showing the image property details record as an option in the same windows pane as the main image. Any popup as offered currently breaks the workflow.
2. A Keyboard Shortcut to quickly turn on/off this display option, or just recycle Ctrl-I used currently for the Popup.
3. Optional comfort feature: Customizing with checkbox option for each of the image detail properties. Keep the Grouping as given by windows popup, but camera information (aperture, shutter speed, camera model) preferably in top position

### Describe alternatives you've considered
 Continue to search for the best and fastest image manager software, ;-)

### Additional context
Eletronic shutter and modern hi-res digital cameras produce masses of images. Support for a quick and seamless pruning/deletion process is of outmost important for a good image manager software.

**Comment by d2phap** [comment]
Hi @olippuner 

I wonder if the Exif tool of ImageGlass fits your need?
With Exif tool, when you change the viewing image, it also loads the corresponding information without toggling the window tool. You also can filter, change the order of the EXIF tags.

This tool is in a separate window. But I guess you can just put it side by side with ImageGlass window so it can help your work.
