### ISSUE TITLE
File open process instance remains active even after the file is closed

### ISSUE THREAD

**Issue by malondkarchetan04** [d2phap/ImageGlass#1282]
### System information:
 - Windows OS version: 21H2 (OS Build 19044.1503)
 - ImageGlass version: 8.5.1.22 x64

### To Reproduce
1. Create a new folder on desktop
2. Add few images (maybe PNG or JPG files)
3. Double click to open and use arrow keys to scroll through multiple images in the folder
4. Close ImageGlass
5. Move all the images to another folder in the drive
6. Now try deleting the now empty new folder created on desktop where all images were added initally

### Actual behavior:
1. When trying to delete the empty folder, it does not allow you to delete it but instead shows you a message "action cannot be completed as file is open in another program"
2. If check the associated handles in resource monitor, you can see that it is the ImageGlass process responsible for this (Press Ctrl+Alt+Delete > Task Manager > Go to Performance tab > Click on Open Resource Monitor at the bottom > Go to CPU tab > Associated Handles > In search bar, type the name of the folder you were not able to delete)

### Expected behavior:
Once an user clicks the cross button to close image glass all associated process should close. In fact, ImageGlass processes should not be running in the background in the first place and should only trigger when application launches (e.g. when opening a file) and it should end when application closes. I believe this is how older versions of ImageGlass behaved. In the newer versions, this application has taken a wrong turn and it won't go down very well with Windows users. As it is Windows users are skeptical about any new processes running in the background. A simple image visualizer software keeping itself running in the background is not something that we would like.

### Screenshots:
N/A

### Additional context:
N/A

**Comment by Sxderp** [comment]
1. This was a request https://github.com/d2phap/ImageGlass/issues/1196 ; to deal with the fairly slow start time of the software.
2. You should be able to disable it in Settings -> General -> Others by unseleting "continue running in background".
3. Newest (unreleased? but probably available as an "unstable" download) should disable this by default. Unfortunately I think you may need to uncheck it yourself since you already have the software.

**Comment by fire-eggs** [comment]
The "real" issue here would be ImageGlass holding on to existing handles. The background process shouldn't need to do that.

Otherwise the behavior is intentional, beneficial, and as @Sxderp reminds us, can be disabled.

**Comment by d2phap** [comment]
Close this for now, feel free to ask me reopen if it happens on v9
