### ISSUE TITLE
Scale to fill doesn't take into account the toolbar

### ISSUE THREAD

**Issue by mirh** [d2phap/ImageGlass#1287]
### System information:
 - Windows OS version: 10 20H2
 - ImageGlass version: 8.5.1.22

### To Reproduce
1. Open an image
2. Resize the window to be wider than the image aspect ratio
3. Make sure the toolbar is enabled
4. Click scale to fill

### Actual behavior:
The image is stretched to fill the entire window, as if the toolbar was drawn on top of it

### Expected behavior:
Image fills in the effective viewport

### Additional context:
Something like this also happen in scale to width, even though I guess it could even be intentional (nobody is telling you that height should fit there)

**Comment by d2phap** [comment]
@mirh can you attach a screenshot or draw your expectation?

**Comment by mirh** [comment]
The toolbar covers the top of the image, that's what I'm saying. 
You have to manually pan to see the rest of it.

**Comment by mirh** [comment]
Ok.. right. 
The thing is supposed not to tamper with aspect ratio. 
So fill doesn't mean "fill the window with the image" but "have the image somehow fill the window" (which is in turn equal to "*scale to height* OR *scale to width*, whichever is the closest"). 
I'm a bit torn on how it would be best to move from here.

**Comment by d2phap** [comment]
@mirh can you attach a screenshot or draw your expectation?
