### ISSUE TITLE
ImageGlass too slow especially for raw file. maybe use  embedded jpeg ?

### ISSUE THREAD

**Issue by Zeus64** [d2phap/ImageGlass#1290]
ImageGlass is very slow to open, especially for raw file, but often raw files contain embedded jpeg with high resolution (exemple my raw contain a preview jpg of 1616x1080 that is often bigger than the screen resolution) so is could be good for imageGlass to use this embedded jpeg instead.

**Comment by d2phap** [comment]
You can select this option in Settings > Image:

![image](https://user-images.githubusercontent.com/3154213/154826952-03e67ade-7e74-4ce0-9bc2-3570e51b584d.png)

**Comment by Zeus64** [comment]
Oh my god didn't catch it ! it's sooo good!
 
Is it possible to enable it also (the embedded thumbnail) for jpeg ? I explain, my camera is doing 7952x5304 images, that are quite big and it's little slow to open it with imageglass (2-3 seconds each images), but they have a thumbnail of 1616x1080 that is quite big and enough for my screen resolution. If we use the embded thumbnail then we can accelerate drastically by a factor from 5 to 10 the opening speed (if I compare with the arw who use it)

the option I imagine: 
* Use embedded thumbnail for all images : yes/no

and because sometime jpeg images can have very small thumbnail that we can't use :
* to use embedded thumbnaill, thumbnail must be :
    * with a min width of: xxx  
   * with a min height of: xxx

**Comment by Zeus64** [comment]
I just opened a new feature request :
https://github.com/d2phap/ImageGlass/issues/1293

**Comment by d2phap** [comment]
Thanks I will take a look
