### ISSUE TITLE
ImageGlass too slow with big jpeg file. Maybe use embedded jpeg ?

### ISSUE THREAD

**Issue by Zeus64** [d2phap/ImageGlass#1293]
ImageGlass is very slow to open with big jpeg file (2-3 seconds for 7952x5304 images), but often those files contain embedded jpeg with high resolution (example my 7952x5304 jpeg contain a preview jpg of 1616x1080 that is often bigger than the screen resolution) so it's could be good for imageGlass to use this embedded jpeg instead. If we use the embedded thumbnail then we can accelerate drastically by a factor of 10 the opening speed (if I compare with the raw of similar size who use embedded images)

This is similar to what ImageGlass do with Raw file

the options I imagine:

Use embedded thumbnail for raw images : yes/no
Use embedded thumbnail for other images : yes/no
 ___ if a thumbnail have a min width of: xxx
 ___ if a thumbnail have a min height of: xxx

**Comment by Zeus64** [comment]
@d2phap I don't know the status of imageGlass 9.0 but as it's seem you redraw it from scratch if you could add this feature in it it's would be very great !

**Comment by d2phap** [comment]
Thanks @Zeus64 I have plan to implement this in the next beta release

**Comment by d2phap** [comment]
This feature is implemented in [ImageGlass Moon 9.0 beta 3](https://github.com/d2phap/ImageGlass/releases/tag/9.0.3.1225)!

- You can use 2 settings: `EmbeddedThumbnailMinWidth`, `EmbeddedThumbnailMinHeight` to set the min size of the embedded thumbnails.
- To use embedded thumbnail for RAW file: `UseEmbeddedThumbnailOtherFormats`
- And other formats: `UseEmbeddedThumbnailOtherFormats`
