### ISSUE TITLE
Icons not scalling correctly to be pixel perfect

### ISSUE THREAD

**Issue by ghost** [d2phap/ImageGlass#1296]
### System information:
 - Windows OS version: 10
 - ImageGlass version: Kobe 8.5.1.22 / Moon 8.5.2.15

### To Reproduce
1. Open the software
2. Look at the icons

### Actual behavior:
Starting from 8.0.12 looks very weird.
The icons are not aligned to be pixel perfect.
And not centered correctly on box.

Container box not looking good too.

### Screenshots:
![image](https://user-images.githubusercontent.com/48178307/155844368-7c8e8e03-9015-4566-ba94-41e7ae38c625.png)
![image](https://user-images.githubusercontent.com/48178307/155852148-ae5a466a-4396-49e3-817b-cbf02f8e6e2b.png)

### Additional context:
Icons size should be changed back to 20 as default.

**Comment by d2phap** [comment]
This should be already fixed in v8.7:
![image](https://user-images.githubusercontent.com/3154213/209429575-9188cb4a-ac17-479f-851a-e281ee8607e1.png)



as well as v9.0 beta 3:
![image](https://user-images.githubusercontent.com/3154213/209429549-ed82ad86-f228-4d2a-9f4a-ecf23d50d545.png)
