### ISSUE TITLE
Next / previous image is not loaded

### ISSUE THREAD

**Issue by Jarzka** [d2phap/ImageGlass#1300]
### System information:
 - Windows OS version: 11
 - ImageGlass version: 8.5.1.22

### To Reproduce
1. Open any image, it loads ok
2. Click next / previous image buttons (or press arrow button right / left)
3. The current image disappears but no new image is ever loaded

### Actual behavior:
Does not load the next / previous image

### Expected behavior:
Should load the next / previous image from the disk

**Comment by fire-eggs** [comment]
We'll need more information to be able to diagnose this. I can think of a couple of scenarios where there won't be images to navigate to - e.g. opening an image from Explorer search results, where the image is by itself in a folder.

First of all, what does the titlebar show for available images? E.g. here is a sample:

![image](https://user-images.githubusercontent.com/9809727/156930659-ab9f64d5-b5ba-4895-993f-38fc0b75d448.png)

The image is in a folder containing 8 images (the "4/8 file(s)" section). What are the numbers when you are having this issue?

If you're expecting images in sub-folders to be included, remember to activate the appropriate setting:

![image](https://user-images.githubusercontent.com/9809727/156930791-d4290a66-f4bf-4a2f-bc4a-de02e79bd3cf.png)

**Comment by Jarzka** [comment]
The titlebar shows just "ImageGlass".

I'm not expecting to be able to browse images from sub-folders, I'm just browsing files on the same folder.

Here is a little video demostration of the bug. I first open an image with ImageGlass and the navigation does not work in any direction. Then I open the image with Microsoft Photos (the default photo viewing app in Windows 11), and the navigation works.

https://www.dropbox.com/s/zzm6y5guvcdkv8h/imageglass_fail.mp4?dl=0

**Comment by fire-eggs** [comment]
Ooooh thanks for the video! Yup, that's really scrod. Sorry for the inconvenience!

**Comment by fire-eggs** [comment]
After Windows 11 did its update thing (grrr!) I installed IG 8.5.1.22 and had no problems. I'm guessing there might be an issue with your machine/installation.

What I'd like to suggest next is for you to find your igconfig.xml file. The location is shown in the Settings... dialog as the "Configuration Directory". If you don't mind, zip and attach it.

The first thing to do would be to edit it with Notepad or something, looking for the setting `IsUseEmptyTitleBar`.  It "should" look like this:

`<Item key="IsUseEmptyTitleBar" value="False" />`

If the value is "True", please set it to "False" as shown. Save it and run IG and then maybe we'll get some real info in the title bar.

[If you have problems finding the igconfig.xml file, or the above setting change has no effect, that'll tell us something as well.]

**Comment by Jarzka** [comment]
The `IsUseEmptyTitleBar` was already set to false in my igconfig.xml:
```<Item key="IsUseEmptyTitleBar" value="False" />```

Here is my configuration zip: https://www.dropbox.com/s/8e8secjq736lidj/ImageGlass.zip?dl=1

**Comment by fire-eggs** [comment]
I'm seeing some issues in my tests with the "Language" settings. This could also cause these IG problems (e.g. the empty title bar).

We'll try forcing IG to use the English language.
1. Rename the folder `Languages` in `C:\Program Files\ImageGlass` [or wherever it is installed] to `_Languages`. [This will require admin.]
2. Edit the `igconfig.xml` file and change this line:
```
      <Item key="Language" value="Languages" />
```
to this:
```
      <Item key="Language" value="" />
```

Thanks for the upload. I'm sorry for the run-around, your patience and assistance is appreciated!

**Comment by Jarzka** [comment]
I renamed the folder `Languages` in `C:\Program Files\ImageGlass` to `_Languages` and changed the line in igconfig.xml. Did not help, the problem still persists the same way (the windows title bar is "ImageGlass" and previous/next  image does not load).

Also, the application was already using English language even before this change.

**Comment by Jarzka** [comment]
I tried running ImageGlass as admin for testing purposes. It asked my to select language (I selected English) and theme. Now the image navigation works! However, if I start ImageGlass without adming rights, the problem persists.

**Comment by Jarzka** [comment]
I uninstalled ImageGlass and cleared all its configuration files in `C:\Program Files\ImageGlass` and `C:\Users\<username>\AppData\Roaming`. After that, I reinstalled it (with typical settings) and now the navigation works!

**Comment by fire-eggs** [comment]
Hooray! Glad you got it solved! Apologies for the run-around.

**Comment by d2phap** [comment]
Maybe, the file type associations settings was empty.

**Comment by Jarzka** [comment]
Not sure if that was the reason, but IMO the next / previous image buttons should work no matter if the program is set to be the default application for opening the images or not.

**Comment by d2phap** [comment]
ImageGlass uses user-defined file extensions list (Settings > File type associations) to filter image files from the disk. I just suspected your igconfig.xml file was corrupted, or somehow the extensions list setting was empty. That's why it could not load any images.

Using the user-defined file extensions list allows user to add new extensions that support by Magick.NET.

**Comment by Jarzka** [comment]
Unfortunately this started happening again, even if I have set ImageGlass as the default viewer for all of my image files. :(
