### ISSUE TITLE
Settings panel dark theme

### ISSUE THREAD

**Issue by ghost** [d2phap/ImageGlass#1301]
### Is your feature request related to a problem? Please describe.

I use a custom Windows 10 dark theme and the settings panel of this app is completely white. White text on a white BG.

### Describe the solution you'd like

The settings panel to have a dark theme option.

### Describe alternatives you've considered

The settings panel to respect the OS theme, regardless of any custom themes, and have the option to switch from Light to Dark mode.

**Comment by fire-eggs** [comment]
Which ImageGlass theme are you using? [I'll guess Kobe, but need to confirm.]

Can you be more specific about which aspects of the Windows 10 theme you changed?

**Comment by ghost** [comment]
Thanks for your response. Yeah, I'm using Kobe, but I tried them all with the same result. I've attached screenshots of some of the settings panels, along with the custom Windows 10 theme I'm using. I downloaded the theme from DeviantArt, but I don't recall who created it.

Edit: I should probably mention that I'm using the portable version.

![01](https://user-images.githubusercontent.com/51302763/157343499-1cc930f1-3afd-4b95-a248-9957ef86225e.PNG)
![02](https://user-images.githubusercontent.com/51302763/157343502-6213f03f-8bb0-473a-b44f-af1c2e500a22.PNG)
![03](https://user-images.githubusercontent.com/51302763/157343494-15dbf8a4-4c2e-4e0f-8e68-9f228ca4764c.PNG)
![04](https://user-images.githubusercontent.com/51302763/157343498-48f5bcd2-9ef8-4a2d-99e2-5aff10e277b5.PNG)
[DarkRCBlue.zip](https://github.com/d2phap/ImageGlass/files/8210399/DarkRCBlue.zip)

**Comment by ghost** [comment]
Closing this issue as I've moved to Linux.
