### ISSUE TITLE
Settings Panel text illegible : Windows 11 Light Theme

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#1304]
### System information:
 - Windows OS version: 11
 - ImageGlass version: 8.5.1.22

### Actual behavior:

Windows 11, "Sunrise" theme, or "Windows (light)" theme. 

Using the "2017 (Light Gray)" IG theme, the settings panel has light grey text against mid-grey background. Illegible.

### Screenshots:

![image](https://user-images.githubusercontent.com/9809727/157271958-dbdbcbf3-c9ed-4999-8010-89fc235a0e40.png)

**Comment by d2phap** [comment]
This was fixed in v8.6. The link color is now always blue
