### ISSUE TITLE
ImageGlass Edit Toolbar Action - Windows Error Association

### ISSUE THREAD

**Issue by giwrgosmant** [d2phap/ImageGlass#1307]
### System information:
 - Windows OS version: Windows 11 Version 21H2 (Build 220000.556)
 - ImageGlass version: 8.5.1.22 x64

### To Reproduce
1. Open an image in ImageGlass
2. Go to edit button in toolbar and press it.
3. Windows error appears: "**There is no association of an application with the specified file for this function**"

### Actual behavior:

It doesn't open an editor.

### Expected behavior:

It should open an editor.

### Screenshots:

![2022-03-10 14_57_21-](https://user-images.githubusercontent.com/51835189/157666597-0430bfdd-3999-402a-96dc-1187c3f112fc.png)

### Additional context:

I don't know if ImageGlass have build-in editor but if not I would like to open an editor of Windows Photos or Paint when I press to edit via ImageGlass and I don't really know which association file should I choose in Win11 for that.

**Comment by giwrgosmant** [comment]
@d2phap or any other can you help me with this?
Thanks

**Comment by d2phap** [comment]
Because Windows 11 removed the verb "edit" of the file, I tried to fix in v8.3 here #1160
You need to manually open Settings > Edit, and select the application for editing.

**Comment by d2phap** [comment]
You can try the new build of IG Moon https://imageglass.org/moon
It will try to find MS Paint and use it on Windows 11

**Comment by giwrgosmant** [comment]
> You can try the new build of IG Moon https://imageglass.org/moon
> It will try to find MS Paint and use it on Windows 11

Thx a lot. I will give it a try tommorow. 🙂

**Comment by giwrgosmant** [comment]
> You can try the new build of IG Moon https://imageglass.org/moon
> It will try to find MS Paint and use it on Windows 11

I tried the latest Moon version. Now opens the MS paint, nice 👍
It would be better if it could open the editor of stock windows photos app tho.
Thanks good job 😎

**Comment by d2phap** [comment]
Thanks @giwrgosmant for confirming.
This is for the default editor, the customization can be done in Settings > Edit.
