### ISSUE TITLE
Warning: " ImageGlass无法打开该图片，因为该文件貌似已经损坏或不支持。System.Drawing:参数无效。"

### ISSUE THREAD

**Issue by Heaven7528** [d2phap/ImageGlass#1309]
### System information:
 - Windows OS version:  win10
 - ImageGlass version: 8.5.1.22 x86

### To Reproduce
Open the image and switch to the next one in succession.

### Actual behavior:

Warning: " ImageGlass无法打开该图片，因为该文件貌似已经损坏或不支持。System.Drawing:参数无效。"
![Z4PLQL7GPW6CA70S9Z%77EP](https://user-images.githubusercontent.com/64640240/157813895-16d66992-da1a-4d8f-aa0b-427bf14dd24b.png)
![Z4PLQL7GPW6CA70S9Z%77EP](https://user-images.githubusercontent.com/64640240/157813997-bd9c9d47-d22a-42bb-af73-02b5de25a1d6.jpg)

### Additional context:

![image](https://user-images.githubusercontent.com/64640240/157813188-8983a6cb-0282-4f49-9921-e704fcb8a119.png)

**Comment by fire-eggs** [comment]
This exception usually occurs when ImageGlass is asked to view an image larger than a specific size. If you provide the details about the image which fails with this error, we can confirm whether this is the case.

**Comment by Heaven7528** [comment]
Yes, I have this problem when I view raw images and big tiff images (They're usually bigger than 20 megabytes）. I love imageglass, which is small but very accurate in color rendering, According to my needs, I can customize different  color space. So is there any way to solve this problem?












何旭升
***@***.***


---原始邮件---
发件人: "Kevin ***@***.***&gt;
发送时间: 2022年3月12日(周六) 凌晨5:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [d2phap/ImageGlass] Warning: " ImageGlass无法打开该图片，因为该文件貌似已经损坏或不支持。System.Drawing:参数无效。" (Issue #1309)




 
This exception usually occurs when ImageGlass is asked to view an image larger than a specific size. If you provide the details about the image which fails with this error, we can confirm whether this is the case.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by d2phap** [comment]
Your image dimension (not the file size) must be very big (> 10k x 10k). ImageGlass has this limit

**Comment by Heaven7528** [comment]
My picture size is not that big, the largest is about 4.5k * 7k, view a single picture is no problem, continuous view multiple will be a problem.I'll send you some pictures later.












何旭升
***@***.***


---原始邮件---
发件人: "Phap Dieu ***@***.***&gt;
发送时间: 2022年3月12日(周六) 中午11:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [d2phap/ImageGlass] Warning: " ImageGlass无法打开该图片，因为该文件貌似已经损坏或不支持。System.Drawing:参数无效。" (Issue #1309)




 
Your image dimension (not the file size) must be very big (&gt; 10k x 10k). ImageGlass has this limit
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by d2phap** [comment]
That would be great!

**Comment by Heaven7528** [comment]
What kind of network disk do you use?
It is slow to download large files by email, I share them with you through the internet disk










何旭升
***@***.***


---原始邮件---
发件人: "Phap Dieu ***@***.***&gt;
发送时间: 2022年3月12日(周六) 中午12:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [d2phap/ImageGlass] Warning: " ImageGlass无法打开该图片，因为该文件貌似已经损坏或不支持。System.Drawing:参数无效。" (Issue #1309)




 
That would be great!
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Heaven7528** [comment]
何旭升
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "d2phap/ImageGlass"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月12日(星期六) 中午12:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [d2phap/ImageGlass] Warning: " ImageGlass无法打开该图片，因为该文件貌似已经损坏或不支持。System.Drawing:参数无效。" (Issue #1309)





 
That would be great!
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

example3.zip (639.88M, 2022年04月11日 13:52 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=233061626cc662e1dbc1e32f43315116530503060002515f4f070707061c575a53524c5a01030714005203045403575a5b540304653d635c1a510c12095450171859116213&t=exs_ftn_download&code=b0abe1c9




example1.zip (526.46M, 2022年04月11日 13:53 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=79343834f3902fbd81c5ba791e31054d5a075c070e06070015510f06011c03515b04150c0d54544f0f060f0c0e0701570a010f04383d3707405555445454064c425d48344e&t=exs_ftn_download&code=8484817b




example2.zip (653.13M, 2022年04月11日 14:07 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=743463389cbe4ee28cc5e1754563511a5002560f5b00550618570208564e575107564e59545607180005070d075a050050035b0d636f63504d550e480f06511b4f5d133815&t=exs_ftn_download&code=54c8ccc5

**Comment by fire-eggs** [comment]
Thank you very much for the sample images!

I had trouble seeing any problems. However, I did start getting the following error message:

![image](https://user-images.githubusercontent.com/9809727/158230118-939718ac-e739-465b-add0-72959b2dc4ab.png)

For me, it seems to be a memory issue.

For starters, I see you're using the 32-bit ImageGlass. Do you have a 64-bit machine, and can you use the 64-bit ImageGlass? I only see errors with 32-bit ImageGlass. I should also say my test machine has only 4G of RAM.

Another thing to try is to reduce the amount of memory being used. Within ImageGlass, not using thumbnails is a big memory win. Also, make sure that the ImageBooster (Settings, Image) is set to zero:

![image](https://user-images.githubusercontent.com/9809727/158231619-e1a447f8-c1f2-4560-9b90-08bccf9ff9ff.png)

Not having a lot of programs running is the solution "outside" ImageGlass.

Let us know if this helps at all ...

**Comment by Heaven7528** [comment]
Yes, I have a 64-bit machine and it's memory is&nbsp; 16GB , but I downloaded the software from your website and installed it by default to 32-bit, I thought your software was only 32-bit.
I'll install the 64-bit application and set it up as you provided.
Thanks for your reply .&nbsp; &nbsp; &nbsp;(●'◡'●)ﾉ♥
