### ISSUE TITLE
Arrow Keys to Scroll down and up. NOT Pan up and down.

### ISSUE THREAD

**Issue by srishak34** [d2phap/ImageGlass#1310]
### Is your feature request related to a problem? Please describe.

Id like to have my arrow keys as an option to scroll please. i had f****ng enough scrolling with my mouse. my mouse is quite cheap see, its scroll wheel had its short life span too, no freaking way im gonna go break it like this. the pan up and down is such a di**. its soooooo sloooowww especially doing the hq/hd images. its suck. that i sometimes would almost lose patience and hit my keyboard instead.

### Describe the solution you'd like

make it an option to scroll with your arrow keys.

### Describe alternatives you've considered

NO. MAKE IT AN OPTION TO SCROLL WITH THE ARROW KEYS.

### Additional context

this app is great ngl. its so fast. and well its not perfect but that just normal for any app. rather im grateful and happy to know that its easy to suggest a feature like this. Good work man.

**Comment by fire-eggs** [comment]
SETTINGS. KEYBOARD. UP / DOWN ARROWS.

![image](https://user-images.githubusercontent.com/9809727/158201622-d52342e6-5200-4c5b-abd0-578e6333fb9c.png)
