### ISSUE TITLE
Cropping is kind of a pain. Custom cut area is nice but there Images where custom cut area doesnt work, and thats a pain.

### ISSUE THREAD

**Issue by srishak34** [d2phap/ImageGlass#1311]
### Is your feature request related to a problem? Please describe.

like the title said, cropping is kind of a pain. 
you see, i love Illustrations i download from internet. HQ/HD images especially. but among those there would be text of some kind, or even something that gets quite in the way of the view. obviously i crop those. buuuuuttttt remember. its hd images. its thousands of pixels and you are saying i had to do all this crap manually? you mean there is no feature to just let fill the whole cut area from the get go? oh hell no.
my mouse is cheap, holding my left click button to do all that is just going to wreck it. doing it custom is nice, but that doesnt mean its always a good idea when you had to do so many images. and yes my right hand index fingers hurt from doing all those s***ty cropping. 
### Describe the solution you'd like

just make another button at the cropping panel that will instantly make the cut area to fill the whole image. you can just leave it to user on what to do with it.
### Describe alternatives you've considered

idonthaveone. just make the cropping easier pleaseeee my fingers hurt.
### Additional context

i make this separate from the previous issue so that it wont confuse anyone.

**Comment by d2phap** [comment]
Done in [ImageGlass Moon 9.0 beta 3](https://github.com/d2phap/ImageGlass/releases/tag/9.0.3.1225)
