### ISSUE TITLE
gif image saved with .jpg extension can't play at all

### ISSUE THREAD

**Issue by hellojianqun** [d2phap/ImageGlass#1313]
### System information:
 - Windows OS version: Windows10
 - ImageGlass version: 8.5

### To Reproduce
1. Save an gif image with an extension of ".jpg"
2. Open the saved jpg file in ImageGlass
3. The image will not automatically start playing like an gif file
4. Press Ctrl+Space, nothing happens

### Actual behavior:

Such a file will not automatically start playing, and still not play even after pressing Ctrl+Space.

### Expected behavior:

The image automatically starts playing when opened, at least, starts playing after pressing Ctrl+Space.

### Additional context:

When I save some images from web pages, they may not be given a correct extension by the browser. So I hope ImageGlass can determine the images' real format by the file header etc, not be affected by their file extension.

**Comment by d2phap** [comment]
ImageGlass uses the file extension to determine image format. This is to avoid the unnecessary calculation while reading the file.
