### ISSUE TITLE
无法打开图片以及菜单栏透明

### ISSUE THREAD

**Issue by Monarsoft** [d2phap/ImageGlass#1319]
![image](https://user-images.githubusercontent.com/49823635/160797127-a40b6038-f57d-4d75-b532-5421a99c2f13.png)

**Comment by fire-eggs** [comment]
Have you installed the [.NET Framework 4.8](https://dotnet.microsoft.com/download/dotnet-framework/net48) ?

**Comment by d2phap** [comment]
You need to install .NET 4.8
