### ISSUE TITLE
event subscribing leakage

### ISSUE THREAD

**Issue by ironromeo** [d2phap/ImageGlass#132]
Every call to NextPic method subscribe one more handler to same target
 //Track image loading progress
GlobalSetting.ImageList.OnFinishLoadingImage += ImageList_OnFinishLoadingImage;
...
so after several image showing program calls ImageList_OnFinishLoadingImage many times.
At this moment only one line of code in this handler
DisplayTextMessage("", 0);
 so bug is not critical yet

**Comment by d2phap** [comment]
Thanks @ironromeo for the bug report.
Fixed.
