### ISSUE TITLE
CTRL+SHIFT+S does not SAVE AS

### ISSUE THREAD

**Issue by kevinfrteels** [d2phap/ImageGlass#1321]
### System information:
 - Windows OS version: 21%2 19044.1620
 - ImageGlass version: 8.5.1.22   x64

### To Reproduce
1. Any open image file
2. CTRL+SHIFT+S
3. 
4. 

### Actual behavior:

The shortcut for FILE >SAVE AS which is CTRL+SHIFT+S creates a red line following a 90 degree angle about 5 cursors long on each side

### Expected behavior:

This should open a FILE>SAVE AS dialog box

### Additional context:

I have uninstalled and reinstalled this multiple times. The behavior has not changed. I use this on a two monitor setup and it does so on both.

**Comment by d2phap** [comment]
It's probably duplicated of #1273

**Comment by d2phap** [comment]
Confirm duplication of #1273
