### ISSUE TITLE
Add Exit option to the context menu

### ISSUE THREAD

**Issue by SumatraPeter** [d2phap/ImageGlass#1322]
There seems to be no way to close the viewer if one is in fullscreen mode with the toolbar turned off.

An easy solution would be to add an **Exit** option to the right-click context menu (especially in fullscreen mode, but might be useful for mouse users otherwise too).

(Note that this is _not_ the same as the prior feature request made to add a Close button to the toolbar itself.)

**Comment by d2phap** [comment]
Exit option is added in v8.7
