### ISSUE TITLE
Enable ESC to close/cancel dialogs

### ISSUE THREAD

**Issue by SumatraPeter** [d2phap/ImageGlass#1324]
In Windows itself for example, the delete dialog can be closed/canceled simply by pressing ESC. In IG's delete confirmation dialog however ESC does nothing.

So it would be nice if IG's dialogs also responded to ESC to close/cancel them.

(Speaking of delete confirmation dialogs, while I like that IG's displays the full path to the file, it would be better if it also displayed the image dimensions and size like Windows' delete confirmation dialog does, which would be useful when one is in fullscreen mode with the titlebar and toolbar hidden.)

**Comment by d2phap** [comment]
Those are dialogs opened by `MessageBox.Show()` function do not support closing by ESC key.
Most of them are for showing error message.

The rest can be closed by ESC, e.g. Rename dialog, Go to dialog, Custom zoom dialog,...
I will need to replace the `MessageBox` by the custom dialog component.

**Comment by d2phap** [comment]
All dialogs in [v9.0 beta 2](https://github.com/d2phap/ImageGlass/releases/tag/9.0.2.904) support closing / cancelling by ESC.
