### ISSUE TITLE
Continue running in the background

### ISSUE THREAD

**Issue by SumatraPeter** [d2phap/ImageGlass#1325]
Instead of "Continue running background when the app is closed", it would make more sense if the setting read "Continue running _in the_ background when the app is closed".

Also, what exactly does "Start with OS" and this option do? _What_ component keeps running in the background and why? Does it index stuff, or make app startup faster?

**Comment by fire-eggs** [comment]
>What component keeps running in the background and why?

ImageGlass itself is running in the background. Start with OS means IG is running at Windows startup, in the background. By doing so, ImageGlass opens up much faster when the user double-clicks on an image.

**Comment by SumatraPeter** [comment]
Thanks @fire-eggs for that explanation. BTW the first sentence above _is_ a feature request of sorts, since it's about requesting a minor edit to make the setting read better. :)

**Comment by d2phap** [comment]
Thanks @SumatraPeter for the correction.

**Comment by d2phap** [comment]
Updated the text in the latest build of ImageGlass Moon 8: https://imageglass.org/moon

![image](https://user-images.githubusercontent.com/3154213/169302750-1d5bb25e-836d-4015-96fc-2006533b3f7f.png)
