### ISSUE TITLE
IG doesn't come and open image in foreground even when it should?

### ISSUE THREAD

**Issue by mistergom** [d2phap/ImageGlass#1329]
### Discussed in https://github.com/d2phap/ImageGlass/discussions/1328

<div type='discussions-op-text'>

<sup>Originally posted by **mistergom** April 16, 2022</sup>
Hello!
This question is following the last posts of this discussion:
https://github.com/d2phap/ImageGlass/issues/620

I read that:
_With "allow multiple instances" OFF then yes, IG doesn't currently force the single window instance to the front. The exception to this is when the IG instance is minimized: the window pops front when IG restores from minimized._

Why?
I'm graphic designer, juggling between a lot of windows when I work, and I would need that IG come in foreground when I double-click on an image, wherever it is... Because I need to see it immediately...
When several windows are one above the other, IG stays in background and/or in place...

Any thoughts?
Thanks!</div>

**Comment by d2phap** [comment]
You can just continue on the #620 instead of creating new ones.
Btw, I just replied.

**Comment by mistergom** [comment]
Oh I'm sorry, I thought that the issue was quite different... ^^
