### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tthiery** [d2phap/ImageGlass#133]
I was looking around for a c# based, extension powered image viewer for Windows. Found this. Awesome. Want to contribute, however GPL is a no-go for me. I am right now coding a Archiving solution in .NET (MIT licensed).

Is there any rational behind the License? Is Apache v2 or MIT an alternative?

**Comment by s8321414** [comment]
I think it is because of freeimage's GPL license?

**Comment by tthiery** [comment]
Well make sense, a pity. Exactly the viral aspect I try to avoid. There are many aspects in license choice but some are enforced.

**Comment by d2phap** [comment]
Yes, ImageGlass is using some GPL license libraries :)

**Comment by tthiery** [comment]
I guess no hope then :)

**Comment by ALIENQuake** [comment]
@tthiery @d2phap The freeimage and some other libs were removed, it's possible to revisit this request?
