### ISSUE TITLE
"Pinch to Zoom" actually scrolls up and down

### ISSUE THREAD

**Issue by WinkelCode** [d2phap/ImageGlass#1331]
### System information:
 - Windows OS version: Windows 11 21H2
 - ImageGlass version: 8.5.1.22 x64
 - Apple Magic Trackpad 2 with official Windows Precision drivers

### Problem description:

The "pinching to zoom" gesture actually scrolls up and down when zoomed into an image and does nothing when zoomed out.
The scrolling/"two finger up and down" gesture zooms the image, but is really weird and unresponsive, if the fingers aren't moved above a certain speed threshold nothing happens (it's effectively unusable for that purpose).
Two finger swipe left and right does nothing. (Usually two finger up/down & left/right would scroll around the image when zoomed in)

All of this works as expected in other applications like Affinity Designer.

### Attempted troubleshooting steps:

Rebooting, turning touch gesture support on and off (no change).

These are my zoom settings (should be the default options): 
![image](https://user-images.githubusercontent.com/29005772/165225938-66d84b6d-c63d-4517-8173-fd746d769096.png)

**Comment by WinkelCode** [comment]
# UPDATE:

I managed to get it to sort of work:
![image](https://user-images.githubusercontent.com/29005772/165226374-68049fac-a6c0-4f65-a276-6f00d533195d.png)

"Mouse wheel" = Two finger up/down

"Mouse wheel + Ctrl" = Pinch

"+ Shift"/"+ Alt" = IDK, doesn't seem to do anything.

With these settings the only thing missing is two finger swipe left and right.

Edit: These settings actually work acceptably with a mouse as well, you just have to hold Ctrl to Zoom which is actually not that uncommon in other applications.

Also, my mouse has left/right buttons in the scroll wheel (which are detected by most applications), these don't work in ImageGlass so mice as well as touchpads might benefit from added functionality.

**Comment by d2phap** [comment]
ImageGlass does not support "Pinch to zoom", Swipe left/right. Duplicated of #305

I'm not sure but you may wanna try unchecking this option:
![image](https://user-images.githubusercontent.com/3154213/165538735-ef89abfe-334c-4c33-b61c-01dee4f8b4cb.png)
