### ISSUE TITLE
.webp do not animate like .gif file

### ISSUE THREAD

**Issue by Salman1993october** [d2phap/ImageGlass#1332]
### System information:
 - Windows OS version: windows 10 pro 64 latest version
 - ImageGlass version: latest 

### To Reproduce
1. it happened after the update
2. 
3. 
4. 

### Actual behavior:
 i am a noob dont ask

### Expected behavior:
 i am a noob dont ask

### Screenshots:
 bruh

### Additional context:
 only the .webp are not animating like the  .gif file

**Comment by d2phap** [comment]
Duplicated #508
