### ISSUE TITLE
Show a close button in full-screen mode

### ISSUE THREAD

**Issue by xinoulei** [d2phap/ImageGlass#1335]
Hi there.

I have seen this has been asked before, however, in the previous request the poster asked for a context menu entry to close the app. What I would like to propose is adding a (semi-transparent) close button that would appear on the top-right corner of the window when entering a full-screen mode. 

For example, this is how the close button looks in Picasa Photo Viewer:

![2](https://user-images.githubusercontent.com/1996029/167398170-38b263ed-82bf-4d57-a324-562895bf0177.PNG)
![1](https://user-images.githubusercontent.com/1996029/167398150-17100444-5a8c-4fa9-adce-2146651b8a92.PNG)

**Comment by d2phap** [comment]
Thanks. It's kinda similar to #1182 and #611. Let's follow this there
