### ISSUE TITLE
Hide all panels on slideshow mode

### ISSUE THREAD

**Issue by xmha97** [d2phap/ImageGlass#1336]
Please hide all panels on slideshow mode:
![image](https://user-images.githubusercontent.com/23485114/168167310-55721800-ae44-4855-b43e-91555dc24f13.png)

**Comment by d2phap** [comment]
This is done in the new Slideshow mode of [ImageGlass Moon 9.0 beta 3](https://github.com/d2phap/ImageGlass/releases/tag/9.0.3.1225)
