### ISSUE TITLE
Full screen on mouse wheel

### ISSUE THREAD

**Issue by JonDous** [d2phap/ImageGlass#1337]
I'm surprised but I didn't file to set mouse wheel press to enter/exit full screen mode.

**Comment by d2phap** [comment]
You can do this in [v9.0 beta 2](https://github.com/d2phap/ImageGlass/releases/tag/9.0.2.904) with this setting:

```js
// in igconfig.json

"MouseClickActions": {
  "WheelClick": {
    "ToggleOn": {
      "Executable": "MnuFullScreen",
      "Argument": ""
    },
    "ToggleOff": {
      "Executable": "MnuFullScreen",
      "Argument": ""
    }
  }
},
```

The list of events for `MouseClickActions`:
https://github.com/d2phap/ImageGlass/blob/40c22af09e81ac6ffc8b8e0f3114615677ee4c45/v9/Components/ImageGlass.Base/Types/MouseEvent.cs#L26-L42
