### ISSUE TITLE
Simplified right-click menu，mouse drag window

### ISSUE THREAD

**Issue by bai12123** [d2phap/ImageGlass#1342]
Hello author, I encountered 2 problems in the process of using, here is my suggestion
1.There are too many options in the right-click menu, some functions I can't use, and sometimes I even click accidentally。I hope you can provide a way to simplify the right-click menu options (such as providing changes in the configuration file?)

2.In borderless mode (image fit window)，I hope to be able to drag the picture with the mouse operation, without holding down shift+mouse to drag。Hope it can be changed by myself in version 9.0 @d2phap

**Comment by d2phap** [comment]
Duplicated issue:
1 -> #102
2 -> #1005
