### ISSUE TITLE
When printing FAX files, the folder %AppData%\ImageGlass\Temp is not created and IG crashes

### ISSUE THREAD

**Issue by andre-sicking** [d2phap/ImageGlass#1343]
### System information:
 - Windows OS version: Windows Server 2016 Datacenter, German
 - ImageGlass version: 8.5.1.22 x64

### To Reproduce
1. Open Multipage .fax file
2. CTRL-P (Print)

### Actual behavior:
ImageGlass crashes. Text below is from german OS, but the problem should be clear. Literally: A part of the path "C:\Users\..." could not be found.

************** Ausnahmetext **************
System.IO.DirectoryNotFoundException: Ein Teil des Pfades "C:\Users\XXXXXXX\AppData\Roaming\ImageGlass\Temp\XXXXXXXXXXXXXXXXXX.tiff" konnte nicht gefunden werden.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   bei ImageGlass.frmMain.mnuMainPrint_Click(Object sender, EventArgs e)
   bei System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   bei System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.PerformClick()
   bei ImageGlass.frmMain.<frmMain_KeyDown>g__checkMenuShortcut|37_0(ToolStripMenuItem mnu, <>c__DisplayClass37_0& )
   bei ImageGlass.frmMain.<frmMain_KeyDown>g__checkMenuShortcut|37_0(ToolStripMenuItem mnu, <>c__DisplayClass37_0& )
   bei ImageGlass.frmMain.frmMain_KeyDown(Object sender, KeyEventArgs e)
   bei System.Windows.Forms.Control.OnKeyDown(KeyEventArgs e)
   bei System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
   bei System.Windows.Forms.Form.ProcessKeyPreview(Message& m)
   bei System.Windows.Forms.Control.ProcessKeyMessage(Message& m)
   bei System.Windows.Forms.Control.WmKeyChar(Message& m)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

### Expected behavior:
ImageGlass should show the print dialog.

### Additional context:
A workaround exists:
- Open ImageGlass and open the file to be printed
- Create %AppData%\ImageGlass\Temp folder upfront printing
- Print file

After printing the Temp folder is deleted correctly, but further printings now lead to a crash if the folder is not manually created before each and every print. Maybe the creation of the Temp folder is not implemented correctly or did I miss something for myself?

Thanks for looking at it.

For now I have a workaround in place that redirects the Temp-Folder to another (existing) location using Microsoft FSLogix, so this is of low priority for me but I think it's better to report the bug.

**Comment by d2phap** [comment]
Thanks @andre-sicking 
Confirm the bug

**Comment by d2phap** [comment]
Fixed this issue in the latest build of IG Moon: https://imageglass.org/moon
The official release will come in a few weeks.

**Comment by andre-sicking** [comment]
Thank you for fixing this. Can confirm that it works in IG Moon.
