### ISSUE TITLE
Can not open avif image that bigger than 32768*32768

### ISSUE THREAD

**Issue by LyntNy4n** [d2phap/ImageGlass#1344]
### System information:
 - Windows OS version: win11
 - ImageGlass version: 8.5.1.22 and 9 beta1

### Screenshots:

![Snipaste_2022-05-25_20-30-51](https://user-images.githubusercontent.com/49772385/170262666-0ec9a7b4-8721-490a-a432-42575fcc57b7.jpg)

But png and jpg don't have this issue.

**Comment by Sxderp** [comment]
Images can be vectors for malicious actors. One way to attack a system is via resource exhaustion from decompression bombs. As a result the ImageMagick library has some defaults in regards to how many resources it allocates to decode images. This has an unfortunate side-effect of blocking some legitimate images. This policy can be [overwritten](https://imagemagick.org/script/security-policy.php) but I don't know enough about the .NET bindings to say whether ImageGlass needs new code to load an alternative policy.

**Comment by d2phap** [comment]
Probably I will just close this. IG just uses the default policy of MagickNET
