### ISSUE TITLE
The display of long images is not friendly

### ISSUE THREAD

**Issue by bai12123** [d2phap/ImageGlass#1346]
## Solution: Use fit-width mode , the display area is automatically moved to the top of the picture.   
@d2phap 
![a95cbdfc98c01c3a8fa98a03d8dffa2f2d1b9d94](https://user-images.githubusercontent.com/99849852/170547810-12d3e30a-089c-4899-9186-b146d6ced596.jpg)

**Comment by d2phap** [comment]
- Do not write in big font size unless you want to get bad impression from the reader.
- Following the issue template is respecting the project author.
- And for your issue:
![image](https://user-images.githubusercontent.com/3154213/170615168-ed1fbdb0-1050-444a-8a4d-4113463655a4.png)

**Comment by bai12123** [comment]
1.The uppercase font is used because the original font is too small, I will pay attention
2.Sorry, because there is no template requirement in other communities, I didn't pay much attention to it myself, I will pay attention to the template next time, and I also like this software
3.Finally thank you for your answer
