### ISSUE TITLE
'About' modal dialog displaying not on top during "Keep window always on top"

### ISSUE THREAD

**Issue by kkots** [d2phap/ImageGlass#135]
Hate to report again, but encountered an issue with "Help (F1)" toolbar button which brings up an "About" window that displays below the rest of ImageGlass windows for which "Keep window always on top" setting is checked. The "About" window is mandatory which means other ImageGlass windows can't be clicked until it is closed. Since other windows cannot be resized or moved during this, it becomes the only solution to close ImageGlass in case if 'keep-on-top' windows were full-screen or obstructed "About" window fully.

Not a big issue, though.

![unt](https://cloud.githubusercontent.com/assets/8692796/19614589/668316f8-97ff-11e6-8408-a6d20b85f2fb.png)

**Comment by d2phap** [comment]
Thanks for the issue, it can be fixed in next version

**Comment by d2phap** [comment]
Fixed
