### ISSUE TITLE
Please keep only ImageGlass Remove Kobe Word from Title Bar

### ISSUE THREAD

**Issue by ghost** [d2phap/ImageGlass#1352]
Please keep only ImageGlass **Remove Kobe Word** from Title Bar

![Screenshot (286)](https://user-images.githubusercontent.com/98110551/171880144-60efbacd-12a6-4896-bc36-7905432c8176.jpg)

**Comment by Sxderp** [comment]
Can you elaborate on why you think this is necessary? I don't know why it was added (maybe a version name like Debian uses? buster/bullseye/bookworm), but it's not really a breaking change is it? I'm pretty sure (I don't have a Windows system in front of me) that Windows truncates the end of a title string if it cannot fit in the taskbar, so you don't even see it there.

**Comment by ghost** [comment]
Only one thing, because I don't like version name title bar

**Comment by d2phap** [comment]
I want to make the app's code name clear, and not to confuse people with another release at https://github.com/ImageGlass/Spider.
In the future, user can switch to different update channel: Kobe, Moon, Spider,... like Windows Insider, and improve the auto-update process.

**Comment by niresh1234** [comment]
But, you must add **Show Version Name in Title Bar** in the Setting Page

Can you add this option in next version?

**Comment by d2phap** [comment]
Okay I will create a setting for it in the next release.

**Comment by Dypsis** [comment]
> I want to make the app's code name clear, and not to confuse people with another release at https://github.com/ImageGlass/Spider. In the future, user can switch to different update channel: Kobe, Moon, Spider,... like Windows Insider, and improve the auto-update process.

But you've already renamed the Program Files folder name to ImageGlass Kobe.
How is that going to work smoothly if you switch channels?

**Comment by Sxderp** [comment]
> But you've already renamed the Program Files folder name to ImageGlass Kobe.
> How is that going to work smoothly if you switch channels?

Same as Firefox? Your profile and settings data are stored in the user folder and can be found regardless if you're running Firefox Nightly, Firefox Developer, Firefox Stable, Firefox ESR, all of which can be installed at the same time.

As for this issue, I still can't wrap my head around it and am going to drop out of it.

**Comment by d2phap** [comment]
Published v8.6.7.13, reverted the folder name to ImageGlass, and removed "Kobe" from the title bar.
The release code is only shown in the About dialog.
