### ISSUE TITLE
Latest update broke it (8 6 6 6)

### ISSUE THREAD

**Issue by Shituation** [d2phap/ImageGlass#1353]
### System information:
 - Windows OS version: Win10 x64
 - ImageGlass version: 8 6 6 6 

### To Reproduce
After installing the new "kobe" version:
1. Installation path changed, adding the word "kobe" for some reason. This killed profiles for my keyboard (app detection). Fixed manually. Why changing default paths now?
2. File types got messed up for some reason and windows still asked me which program to use for every image (jpg). Got this fixed somehow playing with filetypes inside the program and on windows.
3. My settings got erased. (path change??) manually fixed by losing time; configuring everything again.
4. Zoom is broken. There is no way to make the app use the whole window to show the images while keeping "height" ratio. Height ratio is not honored next program launch or next image. Also happens when deleting an image from inside the app, zoom gets reset to "scale to width" (which in my opinion is stupid since 90% images (except panoramics maybe) will be partially visible when this option is set on most monitors/tvs ).

**Comment by d2phap** [comment]
Hi @Shituation 

> 1. Installation path changed, adding the word "kobe" for some reason. This killed profiles for my keyboard (app detection). Fixed manually. Why changing default paths now?
> 2. File types got messed up for some reason and windows still asked me which program to use for every image (jpg). Got this fixed somehow playing with filetypes inside the program and on windows.

Sorry for these troubles, but I want to make the app's code name clear, and not to confuse people with another release at https://github.com/ImageGlass/Spider. Also, I didn't think changing the name could break anything.


> 3. My settings got erased. (path change??) manually fixed by losing time; configuring everything again.

The settings for installation are usually saved in `%AppData%\ImageGlass`, and this folder is not changed so it should not happen. Unless you run IG as administrator, it will use the installed folder to save the settings file.


> 4. Zoom is broken. There is no way to make the app use the whole window to show the images while keeping "height" ratio. Height ratio is not honored next program launch or next image. Also happens when deleting an image from inside the app, zoom gets reset to "scale to width" (which in my opinion is stupid since 90% images (except panoramic maybe) will be partially visible when this option is set on most monitors/tvs).

I'm not sure what happened because I cannot reproduce it. Can you attach a video or any screenshots.

**Comment by Shituation** [comment]
> I'm not sure what happened because I cannot reproduce it. Can you attach a video or any screenshots.

No, I can't. Too much work and I've already uninstalled the latest version and went back to 8 5 1 22 and it works as intended.
I will simply block updates until this is fixed. Maybe someone else will report it. Its an image viewer so its not critical and the old versions simply work so for me, time is more valuable than "showing proof" of the problem in this case.

**Comment by d2phap** [comment]
Published release v8.6.7.13 https://github.com/d2phap/ImageGlass/releases/tag/8.6.7.13
