### ISSUE TITLE
8.6.6.6 is broken for me

### ISSUE THREAD

**Issue by 1mad1** [d2phap/ImageGlass#1354]
### System information:
 - Windows OS version: Windows 10 21H2 
 - ImageGlass version: 8.6.6.6 64-bit

### To Reproduce
1. Install the new update (8.6.6.6) over ImageGlass (old version: 8.5.1.22)
2. Open ImageGlass or any image

### Actual behavior:

Image isn't showing, Toolbar icons aren't shown, see the screenshot

### Screenshots:

![Screenshot (6)](https://user-images.githubusercontent.com/52380483/171994959-6a3a54bf-b50c-4b58-ab37-622d8acca081.png)

### Additional context:

Uninstalled 8.6.6.6, reinstalled it, still same issue.
Uninstalled 8.6.6.6, installed 8.5.1.22, no issue, i can see the image.

off-context: Wrong release date
![image](https://user-images.githubusercontent.com/52380483/171995067-5786e0c9-6502-4312-8efd-2501514219aa.png)

**Comment by graphixillusion** [comment]
For me it crashes on start. Windows 10 21H2. This is what i have in the eventviewer:

```
Application: ImageGlass.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception
Exception information: System.IO.FileNotFoundException
   in System.IO.__Error.WinIOError(Int32, System.String)
   in System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean)
   in System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, Int32)
   in System.Xml.XmlDownloadManager.GetStream(System.Uri, System.Net.ICredentials, System.Net.IWebProxy, System.Net.Cache.RequestCachePolicy)
   in System.Xml.XmlUrlResolver.GetEntity(System.Uri, System.String, System.Type)
   in System.Xml.XmlTextReaderImpl.OpenUrlDelegate(System.Object)
   in System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode, CleanupCode, System.Object)
   in System.Threading.CompressedStack.Run(System.Threading.CompressedStack, System.Threading.ContextCallback, System.Object)
   in System.Xml.XmlTextReaderImpl.OpenUrl()
   in System.Xml.XmlTextReaderImpl.Read()
   in System.Xml.XmlLoader.Load(System.Xml.XmlDocument, System.Xml.XmlReader, Boolean)
   in System.Xml.XmlDocument.Load(System.Xml.XmlReader)
   in System.Xml.XmlDocument.Load(System.String)
   in ImageGlass.UI.Theme.LoadTheme(Int32, System.String)
   in ImageGlass.UI.Theme..ctor(Int32, System.String)
   in ImageGlass.Settings.Configs.Load()
   in ImageGlass.Program.Main()
```

Last NET Framework 4.8 is installed on the system.

**Comment by d2phap** [comment]
@1mad1 It seems the Magick.NET has multiple version conflicts, need to delete the old version of Magick.NET in your machine. I don't know how yet, I will check.

@graphixillusion 
What theme are you using? It seems that IG cannot load the igtheme.xml file.

**Comment by graphixillusion** [comment]
@d2phap yes you are right. i installed it with scoop and something went wrong. Now i've reinstalled from scratch and the error is gone. Maybe it would be better a notification popup instead of a crash?

**Comment by d2phap** [comment]
@graphixillusion IG should come with the Kobe theme by default, I'm not sure why it's missing, but I will check and add more error message for the missing files

**Comment by robsiera** [comment]
I have exactly the same error, and cannot get rid of it. Repaired it, uninstalled/reinstalled it. Nothing helps. Indeed some file of the previous install were still floating around. Removed them. Cleaned registry. But still the same error.
I do not have more details. No event log error in my case.
Any suggestions? 
--edit--
I uninstalled 8.6.6.6 and reinstalled 5.1.22. That works without any issue.

**Comment by d2phap** [comment]
The amazing @fire-eggs has found the solution for this: https://groups.google.com/g/imageglass/c/TC77lLRiLr4/m/uEtHVOO-AQAJ

> I installed IG 8.6.6.6 on Win10 and it asked me to install .NET 4.8 - so yes, you already had 4.8 installed.
>
> It ran for me, but I've been running IG 8.5.1.22 for some time with no problems.
>
> As a test, I renamed vcomp140.dll in c:\windows\system32, then ran ImageGlass. Up came the "NativeMagickSettings" error!
>
> So I believe a copy of vcomp140.dll is required. I know that a copy of that file is available in the ImageGlass 8.5.1.22 portable download; alas it cannot be found in the 8.6.6.6 downloads.
>
> I can't upload a file here, so I've placed a copy in my Google Drive: [vcomp140.dll](https://drive.google.com/file/d/1noAl5KHap4ZyjvJGNOHxkcT7-dduAj_i/view?usp=sharing)
>
> If you've already got a copy of vcomp140.dll on your system, then I ain't got a clue! You should be able to put that file either in the ImageGlass install folder or in C:\windows\system32.

You can download `vcomp140.dll` here, and put it in the installed folder of ImageGlass:
[vcomp140.dll.zip](https://github.com/d2phap/ImageGlass/files/8854707/vcomp140.dll.zip)
I have also paused the update of v8.6 until I pack a new one.

**Comment by asheroto** [comment]
Same issue here... Brand new VM install with Windows 10 - issue present. Brand new install on a laptop with Windows 10 - issue present.

![asdf](https://user-images.githubusercontent.com/49938263/173176685-39bcb558-b745-4ff0-aea0-2f0532db33b8.png)

**Comment by asheroto** [comment]
> The amazing @fire-eggs has found the solution for this: https://groups.google.com/g/imageglass/c/TC77lLRiLr4/m/uEtHVOO-AQAJ
> 
> > I installed IG 8.6.6.6 on Win10 and it asked me to install .NET 4.8 - so yes, you already had 4.8 installed.
> > It ran for me, but I've been running IG 8.5.1.22 for some time with no problems.
> > As a test, I renamed vcomp140.dll in c:\windows\system32, then ran ImageGlass. Up came the "NativeMagickSettings" error!
> > So I believe a copy of vcomp140.dll is required. I know that a copy of that file is available in the ImageGlass 8.5.1.22 portable download; alas it cannot be found in the 8.6.6.6 downloads.
> > I can't upload a file here, so I've placed a copy in my Google Drive: [vcomp140.dll](https://drive.google.com/file/d/1noAl5KHap4ZyjvJGNOHxkcT7-dduAj_i/view?usp=sharing)
> > If you've already got a copy of vcomp140.dll on your system, then I ain't got a clue! You should be able to put that file either in the ImageGlass install folder or in C:\windows\system32.
> 
> You can download `vcomp140.dll` here, and put it in the installed folder of ImageGlass: [vcomp140.dll.zip](https://github.com/d2phap/ImageGlass/files/8854707/vcomp140.dll.zip) I have also paused the update of v8.6 until I pack a new one.

Yep, this fixes it! Thanks.

**Comment by d2phap** [comment]
Fixed this issue in the release v8.6.7.13 https://github.com/d2phap/ImageGlass/releases/tag/8.6.7.13

**Comment by asheroto** [comment]
Do any of you manage the Chocolatey package for ImageGlass?

**Comment by d2phap** [comment]
@asheroto No I don't maintain any other download sources, only from GitHub and the website https://imageglass.org. You can contact the package maintainer, or just wait for a few days, I guess.
