### ISSUE TITLE
When trying to install ImageGlass for (Only Current User)

### ISSUE THREAD

**Issue by ghost** [d2phap/ImageGlass#1355]
When trying to install ImageGlass for (Only Current User)

**Main Problem:
ImageGlass not Get any Administrator Rights During install for "Only Current User"**
- Because Writing a Registry Keys, Need Administrator Rights.........................

![1](https://user-images.githubusercontent.com/98110551/172033575-c6504528-6ed2-4dc4-bf3e-175f7cb35305.jpg)
![2](https://user-images.githubusercontent.com/98110551/172033583-1d8bfa55-6bed-4cd9-a00b-a4f6fc662370.jpg)

**Comment by d2phap** [comment]
I also posted this issue here: https://github.com/d2phap/ImageGlass/discussions/1351#discussioncomment-2881696
I'm still waiting for the Advanced Installer support team to reply me: https://www.advancedinstaller.com/forums/viewtopic.php?f=2&t=50421&p=127545#p127545

**Comment by d2phap** [comment]
Fixed this issue in the release v8.6.7.13 https://github.com/d2phap/ImageGlass/releases/tag/8.6.7.13
