### ISSUE TITLE
No thumbnails generated for EPS files, navigation not working

### ISSUE THREAD

**Issue by Baegus** [d2phap/ImageGlass#1357]
### System information:
 - Windows OS version: 10
 - ImageGlass version: 8.6.6.6 Kobe

### To Reproduce
1. Have a folder with multiple EPS files.
2. Open one.
3. Try to navigate left/right.

### Actual behavior:
No thumbnails get generated for the EPS files and pressing left/right does nothing. The single EPS image does get opened though.

### Expected behavior:
Thumbnails should get generated (or at least show the ImageGlass icon) and navigation should work.

**Comment by d2phap** [comment]
@Baegus Can you share some screenshots?

To read EPS file, you need to install GhostScript, then open IG Settings > File type associations, add `.eps` extension to the list

![image](https://user-images.githubusercontent.com/3154213/172821596-6c593c7d-9d69-4bbc-8fbf-6605df316a0a.png)
