### ISSUE TITLE
Please use a similar "set as desktop wallpaper" as window's photo viewer uses

### ISSUE THREAD

**Issue by Opzon** [d2phap/ImageGlass#136]
Sorry I don't know how to tag posts but PLEASE make it so that it fits the image to your resolution like window's photo viewer does as I hate unfilled edges when I try to apply some ridiculous sized wallpaper PLUS my second monitor isn't 1080p so even if I resize every single image to 1920x1080 it'll be messed up on my other monitor.

**Comment by d2phap** [comment]
implemented in v4.5
