### ISSUE TITLE
Icon for "Thumbnail panel" could be more intuitive

### ISSUE THREAD

**Issue by juliankadar** [d2phap/ImageGlass#1364]
I've just clicked on the icons on the toolbar and discovered the thumbnail panel feature. I was a litte bit surprised which feature was behind that icon because I didn't expect a thumbnail panel at all.

May I suggest a more intuitive version?

It should better imitate the resulting screen like a large picture on top-center and small thumbnails below. Some kind of a combination of the slide show icon an the checkerboard backgroud icon. Please consider my attached propsal.

<img width="41" alt="ImageGlass Thumbnail panel" src="https://user-images.githubusercontent.com/107535656/173760831-14ee60ab-1cd7-4c4d-9842-74d7e036dcc5.PNG">

**Comment by d2phap** [comment]
Updated the icon in v8.7 Kobe / Light Grey theme

**Comment by juliankadar** [comment]
Great! Thank you :-)
