### ISSUE TITLE
Fast zoom, window flickers badly

### ISSUE THREAD

**Issue by bai12123** [d2phap/ImageGlass#1371]
### System information:
 - Windows OS version: windows11  21h2
 - ImageGlass version: ImageGlass Kobe 8.6.7.13

### To Reproduce
1. Enable "window fit" behaviour
2. Use the scroll wheel to zoom quickly
3. Quick next picture

### Actual behavior:

Enable "window fit" behaviour，when I use the scroll wheel for fast zooming (or fast next picture), the window has severe flickering and the zooming is not smooth. Give it a try, and you'll see what I'm talking about

### Expected behavior:

Fix window flickering

**Comment by d2phap** [comment]
Fixed this in v8.7
