### ISSUE TITLE
Window remains on top on update 8.6.7.13 x64 on Windows 11 21H2 (also not resizing when changing to a different monitor with different scaling)

### ISSUE THREAD

**Issue by ghost** [d2phap/ImageGlass#1374]
### System information:
 - Windows OS version: Windows 11 21H2
 - ImageGlass version: 8.6.7.13 x64

### To Reproduce
1. Open any image with ImageGlass, and open a few other windows like explorer or microsoft word or chrome browser.
2. Try to make other windows in focus
3. ImageGlass will remain on top, covering everything else, including taskbar if you put it over that.
4. 

### Actual behavior:

For some reason ImageGlass only wants to stay on top. It doesn't go behind over windows when changing the focus.
An additional issue is that when you have two monitors, and the two monitors have different Windows scaling (mine is 150% and other is 100%) and you try to move ImageGlass between the two, it doesn't "resize". When moving from the high DPI monitor to the low DPI monitor, the title bar appears large, as if ImageGlass is still using the 150% scaling setting from the high DPI monitor. When moving ImageGlass to the other monitor, the scaling should automatically change to 100%. Note that these percentages depend on what you have set your scaling to in Windows settings.

### Expected behavior:

The ImageGlass program is supposed to not show in front of taskbar or other windows.

### Screenshots:

![image](https://user-images.githubusercontent.com/76711360/175161959-42bdb738-df2e-4630-b6ff-6b43386655be.png)
Alternatively:
https://www.dropbox.com/s/k4uk15p2jo8fzyw/Screenshot%202022-06-22%20181012.png?dl=0

**Comment by d2phap** [comment]
Can you check if the menu Layout > Keep window always on top is checked?

**Comment by ghost** [comment]
Awesome that fixed it! I assume the new update made that default?

**Comment by d2phap** [comment]
It's not never set as default.
It has a hotkey (`), and appears in the context menu, too. I think people may miss-press the key some time
