### ISSUE TITLE
Can't display some (.ico) Files

### ISSUE THREAD

**Issue by yousuftamer** [d2phap/ImageGlass#1378]
### System information:
 - Windows 11
 - ImageGlass version: 8.6.7.13 x64

### The Issue:
1. Can't display some (.ico) Files

### Screenshots:
![image](https://user-images.githubusercontent.com/81828638/176991329-108ceb37-9945-4ad6-ae93-6606bdfbe0f6.png)

**Comment by d2phap** [comment]
You should have attached the file.
