### ISSUE TITLE
ImageGlass crashes when trying to open a Jpeg XL file

### ISSUE THREAD

**Issue by Funkmiser** [d2phap/ImageGlass#1381]
### System information:
 - Windows OS version: Windows 11 x64 Version 21H2 (Build 22000.739)
 - ImageGlass version: Kobe 8.6.7.13 x64

### To Reproduce
1. Attempt to open the jxl image from [Test image and conversion.zip](https://github.com/d2phap/ImageGlass/files/9048412/Test.image.and.conversion.zip)
2. Watch as ImageGlass immediately closes a couple of second later

### Actual behavior:
I can't tell if this is an error with ImageGlass or with Magick.NET, usually Magick.NET throws an error that ImageGlass will then display. But this time I had converted the png in the zip file above using default parameters with cjxl.exe v0.6.1 from the libjxl github releases, and then when I try to open the jxl file ImageGlass pulls up for a second or two and then immediately closes out without an error.

### Expected behavior:
ImageGlass opens the jxl file and then after waiting a bit shows the image.

**Comment by cp2732** [comment]
Hello, I am also seeing a similar issue with ImageGlass. I am converting a TIFF file to JXL and after trying to open it with ImageGlass, ImageGlass immediately quits. I am using Windows 10 22H2 and ImageGlass 8.7.11.6 x64. I am using the following ImageMagick command for the conversion:
`magick -verbose -define jxl:effort=9 -define jxl:quality=100 "input.tif" "output.jxl"`

Here are the input and output files:
[input.zip](https://github.com/d2phap/ImageGlass/files/10051209/input.zip)
[output.zip](https://github.com/d2phap/ImageGlass/files/10051214/output.zip)

**Comment by d2phap** [comment]
@cp2732 This is upstream issue (https://github.com/libjxl/libjxl/issues/1579)

**Comment by AlifianK** [comment]
@d2phap 
The same problem, ImageGlass crashed, but strangely it only happens with grayscale pictures only. I tried viewing the image with Tachiyomi reader and it opened normally, so I don't think it's related to the libjxl issue, should I open a new issue here or on libjxl? I use v0.7 of libjxl. [Image sample](https://drive.google.com/file/d/1V1PtMFOLiAHfRkEsVC4gnsp2mQC84KNG/view?usp=sharing)

**Comment by d2phap** [comment]
Thanks @AlifianK for the sample files. It's also the same issue. ImageGlass uses Magick.NET, Magick.NET uses libjxl to handle JXL file. In the test, [Magick.NET throws `AccessViolationException`](https://github.com/dlemstra/Magick.NET/issues/1280) error when opening this file, and mostly because the issue I mentioned above.

**Comment by AlifianK** [comment]
Thanks, I'll comment on the upstream issue too.

**Comment by d2phap** [comment]
I close this because it' upstream issue.
