### ISSUE TITLE
System hanging for a while when installing ImageGlass

### ISSUE THREAD

**Issue by aotuitx** [d2phap/ImageGlass#1383]
### System information:
 - Windows OS version: 10.0.17763.1637
 - ImageGlass version: 8.0.12.8、8.6.7.13

### To Reproduce
1. Do some ImageGlass settings
2. 
3. 
4. 

### Actual behavior:

I am setting up ImageGlass. During the setting process, after a while, I felt that the system was obviously stuck, and the right mouse button did not respond.

This problem happened to me when I used this software for the first time: 8.0.12.8, so I didn't use it later. I didn't remember why I didn't use it last time until I used it again today and the same problem happened.

### Screenshots:

video: https://github.com/aotuitx/-ImageGlassBugreport/blob/main/c5e691c2121f02ee5dd7ddcae8808fbd.mp4

**Comment by d2phap** [comment]
Do you still experience this issue? I can't access the video url.

It's probably not because of ImageGlass, it might cause by your antivirus software.
