### ISSUE TITLE
Expand exiftool by enabling editing and removing exif data

### ISSUE THREAD

**Issue by ghost** [d2phap/ImageGlass#1384]
### Is your feature request related to a problem? Please describe.

I've been searching for a clean and modern looking open source image viewer that's also capable of reading, editing and removing exif data. Imageglass at the moment only reads exifdata.

### Describe the solution you'd like

Imageglass will be able to view, rewrite and remove exifdata
### Describe alternatives you've considered

I've tried multiple alternatives like using exiftool in the terminal, or gui applications that use exiftool as their base, but most if not all of these are abandoned and have security issues.

**Comment by d2phap** [comment]
Since Exif tool is moved to https://github.com/d2phap/ExifGlass, please follow this issue https://github.com/d2phap/ExifGlass/issues/1
