### ISSUE TITLE
imageglass hijacks microsoft apps icons with imageglass png icon

### ISSUE THREAD

**Issue by cakiya** [d2phap/ImageGlass#1386]
### System information:
 - Windows OS version: Microsoft Windows 10 Home 10.0.19043 Build 19043
 - ImageGlass version: ImageGlass Kobe 8.6.7.13 x64

### To Reproduce
1. Install Imageglass (i used the .msi)
2. restart computer
3. open windows menu and type a name of a microsoft app (store, settings, photos, etc)
4. look at the hijacked icon of imageglass png file type instead of the microsoft app icon

### Actual behavior:
Imageglass's PNG icon is used as icons for microsoft apps in the windows start menu

### Expected behavior:
Microsoft apps should have their own unique app icons that are not imageglass icons

### Screenshots:
here's a screenshot: https://imgur.com/a/1n9qAkG

### Additional context:
ive used imageglass since v7 and i updated to v8 via downloading the new installer and installing again
image previews in file explorer work as intended though

**Comment by d2phap** [comment]
see this https://github.com/d2phap/ImageGlass/issues/664#issuecomment-1022305280
