### ISSUE TITLE
Does not consider Folder's current sorting

### ISSUE THREAD

**Issue by waqas** [d2phap/ImageGlass#139]
For example, if I sort pictures by Date in current folder and then open ImageGlass, it would keep going through as if sorted by names.

**Comment by tekord** [comment]
+1

**Comment by 7Soul** [comment]
+1

**Comment by user234683** [comment]
@d2phap A corollary to this would be adding an option to sort by "Date" the way explorer does. When explorer sorts by date, if the image has an EXIF "Date taken", it uses that. Otherwise it uses the earlier of date modified or date created. Also, it doesn't seem to consider milleseconds when sorting by any of the different date options.

**Comment by d2phap** [comment]
This will need to have a shell extension but I'm still not sure if it is feasible.

**Comment by Kosyne** [comment]
+1, this is the only thing keeping me from using this as my main photo viewer.

**Comment by TheGormley** [comment]
+1

**Comment by d2phap** [comment]
This feature is ready in the latest version of ImageGlass Moon: https://imageglass.org/moon

To enable Windows File Explorer sort order support, 
- go to Settings > Image
- select the option `Use Windows File Explorer sort order if possible`
  ![image](https://user-images.githubusercontent.com/3154213/59548510-13f7b780-8f83-11e9-9ef8-0443ab7983a3.png)

#### How it works
- This feature works `ONLY IF` the viewing folder is being opened in File Explorer. 
- ImageGlass ignores other application-defined sort order options and uses the order from File Explorer
- You can update the sort order without changing order options in Settings by menu `Reload image list`

**Comment by biva** [comment]
> 
> 
> @d2phap A corollary to this would be adding an option to sort by "Date" the way explorer does. When explorer sorts by date, if the image has an EXIF "Date taken", it uses that. Otherwise it uses the earlier of date modified or date created. 

I just created a dedicated issue for this feature request: https://github.com/d2phap/ImageGlass/issues/544

**Comment by d2phap** [comment]
Thanks @biva for the feedback

**Comment by Unknow0059** [comment]
This was a great addition.

**Comment by sadmansajid** [comment]
> For example, if I sort pictures by Date in current folder and then open ImageGlass, it would keep going through as if sorted by names.

+1
