### ISSUE TITLE
Small feat request: Close btn on context menu

### ISSUE THREAD

**Issue by uzerucer** [d2phap/ImageGlass#1390]
### Is your feature request related to a problem? Please describe.
I have configured ImageGlass such that it opens in full screen mode and I prefer it this way however, I can't close it from mouse itself...

### Describe the solution you'd like
So I would like a close btn in context menu when I right click, 

![image](https://user-images.githubusercontent.com/101860653/179133886-0bb69f4a-12ce-4cac-8491-4623436bdad1.png)

### Describe alternatives you've considered
Not using fullscreen mode.. I don't like using keyboard everytime to close...

**Comment by d2phap** [comment]
Added Exit option for context menu in v8.7
