### ISSUE TITLE
These bmps looks weird on 8.6.7.13

### ISSUE THREAD

**Issue by floppyD** [d2phap/ImageGlass#1391]
### System information:
 - Windows OS version: 10
 - ImageGlass version: 8.6.7.13

### To Reproduce
1. open image

### Actual behavior:
Image looks washed.

ImageGlass
![image](https://user-images.githubusercontent.com/29208110/179372764-0455693c-9e51-4dac-8860-d805ff714b49.png)

Edge browser
![image](https://user-images.githubusercontent.com/29208110/179372775-99befee6-2df9-40bf-b729-cc4958939ec3.png)

Paint.NET
![image](https://user-images.githubusercontent.com/29208110/179372795-cb320510-4707-4d3f-9c01-4a0404c37d24.png)

Images
[walker d.zip](https://github.com/d2phap/ImageGlass/files/9126639/walker.d.zip)

**Comment by d2phap** [comment]
Thanks @floppyD for the report, but it's similar to #386.

ImageGlass uses Magick.NET to read the image formats. And this image is a 32 bit BMP3 image. This means that 4 channels can be stored per pixel. When the 4th channel are not all zero ImageMagick will treat the 4th channel as an alpha channel.
https://github.com/dlemstra/Magick.NET/issues/271#issuecomment-410369165.

![image](https://user-images.githubusercontent.com/3154213/179383510-7a838cd8-a164-471f-848d-f1f4cfb770bf.png)
