### ISSUE TITLE
ImageGlass Not Showing Last Double-Clicked Image

### ISSUE THREAD

**Issue by NRHGDW** [d2phap/ImageGlass#1392]
### System information:
 - Windows OS version: 10 21H1 19043.1826
 - ImageGlass version: 8.6.7.13 x84

### To Reproduce
1. Double click an image in explorer
2. Wait for ImageGlass to open, showing that image
3. Double click a different image in explorer

### Actual behavior:
ImageGlass is focused, but is still showing the first image

### Expected behavior:
ImageGlass is focused, and showing the image I just double-clicked

### Additional context:
I just upgraded from 7.x, which had the expected behavior - double clicking an image in explorer always replaces the current image in ImageGlass with the image I have double-clicked. I checked the settings a few times and didn't see anything obvious. If I close ImageGlass entirely and double click the second image, ImageGlass now shows it (but again, doesn't change to a new one if I double-click that).

**Comment by d2phap** [comment]
Make sure you check this option:

![image](https://user-images.githubusercontent.com/3154213/179383151-900ac618-971f-499e-b177-41f0111d3e38.png)

**Comment by NRHGDW** [comment]
Made no difference. Also, to clarify, this is not on startup. ImageGlass is open, then I double click another image. ImageGlass comes to focus and top, but is still on the previous image. Video available if needed.

**Comment by d2phap** [comment]
It seems that you're enabling multiple instances of IG.
Can you try disabling this option and see if it works?

If not, a video would be helpful.

![image](https://user-images.githubusercontent.com/3154213/179383716-db663b96-5856-4957-88aa-29f2a2a44bcb.png)

**Comment by NRHGDW** [comment]
I am not trying to use multiple instances; everything is one instance. Here is a video.
https://user-images.githubusercontent.com/99230615/179383992-69cdba69-b152-4bd8-b0a8-e733f851682d.mp4

**Comment by d2phap** [comment]
Thanks for the video, I still can't reproduce with my laptop.

One more try, can you download this config, rename it to `igconfig.xml`, then paste it to the configuration directory (see the Settings > General to know where the Config dir is)

[igconfig.xml.log](https://github.com/d2phap/ImageGlass/files/9127052/igconfig.xml.log)

**Comment by NRHGDW** [comment]
Replacing settings did not work. Uninstall/reinstall did not work. Changing install from current user to all users did not work.
I have set up _beta 9.0.1.518 x64_ and can confirm that it _does work_ as expected. So for me the solution will be to move to beta until release. Thanks.
