### ISSUE TITLE
.ico File's Icon

### ISSUE THREAD

**Issue by sovalyeler** [d2phap/ImageGlass#1396]
### System information:
 - Windows OS version: 10.0.19043 Build 19043
 - ImageGlass version: 8.6.7.13

I can't change icon files'(.ico) icons. Explorer always shows default ImageGlass icon.
![image](https://user-images.githubusercontent.com/108634252/179975253-6d18b09e-1c8b-42db-82c1-b109aff2ea8a.png)
![image](https://user-images.githubusercontent.com/108634252/179975291-e52b3a5d-a0fa-4f52-80cd-70bf1103a9e7.png)
![image](https://user-images.githubusercontent.com/108634252/179975320-803d1f51-4d1e-4ef7-8565-4c520b0bae76.png)

**Comment by d2phap** [comment]
Because of this issue https://github.com/d2phap/ImageGlass/issues/664, so I removed ICO extension from the list. I will add it back in the next release

**Comment by sovalyeler** [comment]
It's fixed now, thank you.
