### ISSUE TITLE
"Imageglass cannot open this pic bc the file appears to be damaged"

### ISSUE THREAD

**Issue by vermomths** [d2phap/ImageGlass#1398]
### System information:
 - Windows OS version: win10
 - ImageGlass version: 8.3.11.21

### To Reproduce
1. rotate the pic
2. click on the next one 
3. click back to the rotated pic
4. the pic cannot be seen anymore and it shows "Imageglass cannot open this pic bc the file appears to be damaged"

### Actual behavior:

^

### Expected behavior:

the pic not be damaged

**Comment by d2phap** [comment]
@vermomths please update to the latest version and check if the error still persists for you.

**Comment by vermomths** [comment]
> 
Hello, thank you for your reply. I updated to the latest version and the problem still exists.

**Comment by d2phap** [comment]
Can you attach the file? I will need to do more investigation

**Comment by vermomths** [comment]
Sure. Here's what it shows.

**Comment by d2phap** [comment]
@vermomths You forgot to attach the file

**Comment by vermomths** [comment]
I did attached a png to the previous email but not sure what happened.
Here it is again

**Comment by d2phap** [comment]
No file again, it's better to go to https://github.com/d2phap/ImageGlass/issues/1398, then attach your file here

**Comment by vermomths** [comment]
![20220726141819](https://user-images.githubusercontent.com/109801662/181688055-cba74d8e-69b0-49a4-b893-4376998e2634.png)

**Comment by d2phap** [comment]
I mean if you can attach the image file (not the screenshot).
But according to the message in the screenshot, your image file has "**insufficient image data**" for Magick.NET library to decode and display in ImageGlass, which means you file might be corrupted

**Comment by vermomths** [comment]
Hello,
It seems that every time after I rotate an image, it becomes damaged, which
is very annoying since I cannot retrieve the original file. Could you
please help me with this? Thank you!

**Comment by d2phap** [comment]
So your issue is related to #1273 which is a bug
