### ISSUE TITLE
DNG Raw support (Suggestion)

### ISSUE THREAD

**Issue by EduAwaSeka** [d2phap/ImageGlass#140]
I like ImageGlass. If supports files of type dng it would be wonderful.

Adobe has available an SDK for dng that may be useful

[https://www.adobe.com/support/downloads/dng/dng_sdk.html](https://www.adobe.com/support/downloads/dng/dng_sdk.html)

**Comment by d2phap** [comment]
`RAW` formats are supported in v4.5

**Comment by eaardal** [comment]
I have v5.0.5.7 and `.dng` format does not seem to be supported yet - would be really awesome if it was 🙏

**Comment by d2phap** [comment]
​Hi!

ImageGlass uses WIC to read RAW formats, I can open DNG files in ImageGlass
My test DNG files:
https://kenrockwell.com/leica/m9/sample-photos-3.htm
​
Phap



‌
