### ISSUE TITLE
Keybindings not working when pressed on Numpad [v9.0]

### ISSUE THREAD

**Issue by sydeslyde** [d2phap/ImageGlass#1400]
### System information:

 - Windows OS version: Windows 10 21H2 (19044.1826 x64)
 - Keyboard Layout: German
 - ImageGlass version: 9.0.1.518 (64-bit)

### To Reproduce

1. Open an Image
2. Zoom in by scrolling the mousewheel
3. Press key `0` on the numpad (to reset to actual size)

### Actual behavior:

Nothing happens.

### Expected behavior:

Zoom should be reset to actual size (because `0` is keybinding for actual size)

### Additional context:

- Regular `0` in the number row of the main-keys works as expected.
- **IMPORTANT**: other numpad-keybindings (I think basically all zoom/scale related) have the same behavior and DO NOT work as expected.

**Comment by d2phap** [comment]
The first beta version only supports assigning 1 hotkey to the action.
If you want to set it to Numpad, you can change the hotkey for `MnuActualSize` to `NumPad0` in `igconfig.json`

```js
MenuHotkeys: {
  "MnuActualSize": "NumPad0"
},

```

**Comment by d2phap** [comment]
[ImageGlass Moon 9.0 beta 3](https://github.com/d2phap/ImageGlass/releases/tag/9.0.3.1225) supports this by default.

It also supports setting multiple hotkey in `igconfig.json` file.

```
MenuHotkeys: {
  "MnuActualSize": ["A", "B"]
},
```
