### ISSUE TITLE
Windows sorting order ignored

### ISSUE THREAD

**Issue by MSi57** [d2phap/ImageGlass#1401]
### System information:
 - Windows OS version: 10.0.19044 Build 19044
 - ImageGlass version: 8.6.7.13

### To Reproduce
1. In Settings / Image / Image loading order, tick the box "Use Windows Explorer sorting order if possible"
2. Press Save
3. In Windows Explorer, set sort order to e.g. photo taken.
4. Open a picture file in Windows Explorer with Image Glass
5. In Image Glass, browse pictures using the keyboard arrow buttons

### Actual behavior:

Image Glass is not following the Windows Explorer sorting order. You'll notice this best if there are photos taken around the same time but with different naming schemes.

### Expected behavior:

Should follow the Windows Explorer sorting order. What does it actually mean, "Use Windows Explorer sorting order _if possible_"? When is it not possible to follow that order?

**Comment by d2phap** [comment]
Mentioned here #544.

IG currently can mimic the sort order for Name, Size, Extension. For Date, Windows uses data from EXIF tag, IG uses ModifiedDate/CreationDate/LastWriteTime from file attributes which do not match.
