### ISSUE TITLE
Full screen improvements

### ISSUE THREAD

**Issue by regs01** [d2phap/ImageGlass#1403]
May i suggest couple of things related to full screen?

- When closing the app from full screen (using ESC), the app will remember dimensions and size of maximized window. So next time it will open into full screen. That saving should be ignored, if it is in full screen mode.
- It will also remember toolbar visibility state. So next launch, when you switch from full screen back to windowed toolbar will not be visible, if you are using auto hide toolbar in full screen option.
- Press F11 message is a little annoying. Showing just couple of times would be enough.
- An option to open app into full screen when opening an image.
- ESC to get back to windowed mode if full screen was open from windowed mode. And then second ESC to close the app. If opened directly into full screen, then ESC to immediately close the app.
- Customizable background color separately for full screen.
- Double click to full screen was already mentioned in other feature requests, but would really greatly improve usability.

**Comment by d2phap** [comment]
Most of the suggestions here are already implemented in v9.0 beta 2: https://github.com/d2phap/ImageGlass/projects/12#card-83527059

You can customize the hotkeys, mouse clicks, chain the actions and a lot more...
