### ISSUE TITLE
Works VERY slow with large images

### ISSUE THREAD

**Issue by thekrotek** [d2phap/ImageGlass#1404]
### System information:
 - Windows OS version: 10
 - ImageGlass version: 8.6.7.13 x64

### To Reproduce
 Try to open this image:

https://en.wikipedia.org/wiki/The_Tower_of_Babel_(Bruegel)#/media/File:Pieter_Bruegel_the_Elder_-_The_Tower_of_Babel_(Vienna)_-_Google_Art_Project_-_edited.jpg

### Actual behavior:
When large image is opened, ImageGlass works VERY slow. If you zoom such picture and try to scroll it to check the details, picture moves extremely slowly.

### Expected behavior:
Fast loading, smooth scrolling.

**Comment by d2phap** [comment]
This is a long and big improvement topic, also mentioned at #272, #522.
The file is just too big (30,000 × 21,952) for the current ImageGlass.
- ImageGlass v8 does not use GPU to render the image, so it's laggy when handling the large image.
- ImageGlass v9.0 beta 1 supports GPU rendering for non-transparent, non-animated images with maximum dimension up to 16,384 pixels.

**Comment by thekrotek** [comment]
OK, good to know, thank you. Will try v9.0, because right now even default Photos app works much better that v8. The latter is slow in general, not only with large images. It improved lately, but still slow comparing to some other image viewers. I am looking for fast image viewer myself, this is a core feature to me.

Keep up the good work anyway!
