### ISSUE TITLE
WARNING- rotating pictures may corrupt them (already reported time ago)

### ISSUE THREAD

**Issue by masterofobzene** [d2phap/ImageGlass#1406]
### System information:
 - Windows OS version: x64  its not a windows issue, its the app.
 - ImageGlass version:  8 6 7 13

### To Reproduce
1. rotate a picture
2. go "next"

### Actual behavior:
picture is corrupted when being saved.

### Screenshots:
![imagen](https://user-images.githubusercontent.com/94469116/183698554-ac87eaa0-614c-4bcd-bc15-8f28d67eb896.png)

**Comment by d2phap** [comment]
it's a known bug #1273
