### ISSUE TITLE
Stereoscopic 3D formats: PNS and JPS (PNG and JPG, but different extension)

### ISSUE THREAD

**Issue by ThreeDeeJay** [d2phap/ImageGlass#1408]
### Is your feature request related to a problem? Please describe.
A Stereocopic 3D image is basically 2 views in the same frame, one for each eye.
When attempting to open a PNS or JPS file, ImageGlass isn't able to display it.
![image](https://user-images.githubusercontent.com/71472458/184796149-a0813629-22a6-4fb2-adf2-5397e517d5f1.png)

### Describe the solution you'd like
ImageGlass just needs to treat PNS and JPS like PNG and JPG, respectively, and it should be able to load since as far as I know, the formats are identical (although some PNS/JPS files have extra metadata specifying the left-right view order)

### Describe alternatives you've considered
If I rename a PNS to PNG, then ImageGlass can load it, but it's not practical to do it every single time.
![ImageGlass_WowPdDN0cJ](https://user-images.githubusercontent.com/71472458/184796591-5e0d3bba-e61d-40ea-8f28-ecad84ef306f.png)

**Comment by d2phap** [comment]
You can add these extensions in Settings > File type associations, click Add button and type the extensions

![image](https://user-images.githubusercontent.com/3154213/184814544-f6fbe999-f6c6-4cc5-8705-61052e414abb.png)

**Comment by ThreeDeeJay** [comment]
Neat, that works for me.
This is such a niche request that I'll just go ahead and close the issue. Tho it would probably be a good idea to pre-add them. 👌
