### ISSUE TITLE
Thumbnails don't update after editing image

### ISSUE THREAD

**Issue by ghost** [d2phap/ImageGlass#1409]
### System information:
 - Windows OS version: 10 20H2 Enterprise 
 - ImageGlass version: 8.6.7.13

### To Reproduce
1. Crop an image & save it; thumbnail in windows explorer will not update
2. Rotate an image & save it; thumbnail will not update BUT preview pane in windows explorer shows correct image or maybe not
3. 
4. 

### Actual behavior:

Thumbnails & previews don't get updated, sometimes the preview in windows explorer will show the correct image after editing while thumnail sticks to the original

### Expected behavior:

Thumbnails & previews should reflect edits

### Additional context:

Problem was present with older version as well (8.5.1.22)

**Comment by d2phap** [comment]
Thanks @FrankGHB 
This issue was already posted here: #754
