### ISSUE TITLE
Make crop behave more like other apps

### ISSUE THREAD

**Issue by hessch** [d2phap/ImageGlass#1410]
Crop uses a visualization that is opposite to any other app that I use, i.e. instead of coloring the selection,
the non selected parts are colored. 
The idea is actually nice, as it makes the resulting image stand out. It has a side effect though. When using
ImageGlass as a browser to quickly crop many images, this becomes painful, the opaque overlay makes that
one doesn't know what part of the  Image to crop out yet.

A possible solution would be to start with an 100% crop instead of a 0% crop as is the default now, this is 
similar to what is requested in issue #1311. With the current crop visualization this means that minor tweaks 
would require less mousing around and images aren't obscured before cropping.

An alternative solution would be to change the visualization. A single dashed selection outline isn't as clear as the
current visualization but it could even work before cropping, I think this would be more inline with other image
editors. This way of visualizing the selecting has the benefit that no part of the image is ever obscured. Having this
as a configurable option would certainly suit some users.

Personally I think in either case starting every image with 100% instead of 0% of the image selected when crop is 
active is the most intuitive and practical way to deal with an image that isn't cropped yet.

**Comment by d2phap** [comment]
[ImageGlass Moon 9.0 beta 3](https://github.com/d2phap/ImageGlass/releases/tag/9.0.3.1225) added support for
- cropping with aspect ratios,
- setting the default selection,
- an option to close the Crop tool after it's done

![image](https://user-images.githubusercontent.com/3154213/209428453-fab81990-c437-4124-b619-21d857f71a4f.png)
