### ISSUE TITLE
Toolbar flickers on image change

### ISSUE THREAD

**Issue by Setsu-BHMT** [d2phap/ImageGlass#1418]
### System information:
 - Windows OS version: 10.0.19044 Build 19044
 - ImageGlass version: 8.6.7.13 x64
(BTW it would be helpful if the version string in the Help dialog is copy-able)

### To Reproduce
1. Open an image to view
2. Press arrow keys to switch to next image

### Actual behavior:
The top toolbar will flicker due to re-painting.

### Expected behavior:
The top toolbar should be cached and not re-painted, since none of the options should change when switching images.

### Screenshots:
N/A due to the flicker lasting only a few milliseconds.

### Additional context:
Very minor issue I admit, but since images are shown on a black background any sort of flickering becomes very noticeable.

**Comment by d2phap** [comment]
This is because the app state is set to busy while it's loading / saving / processing image. This will be fixed in version 9.0

**Comment by d2phap** [comment]
This issue was fixed in [ImageGlass 9.0 beta](https://github.com/d2phap/ImageGlass/releases/tag/9.0.3.1225)
