### ISSUE TITLE
Hi, Single key press hotkey to copy current photo to a preset folder. Would be life changing for culling photos. [:

### ISSUE THREAD

**Issue by nonogamester** [d2phap/ImageGlass#1419]

**Comment by d2phap** [comment]
Hi @nonogamester, you can do it in ImageGlass 9 by creating a custom tool to run [`xcopy` command](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/xcopy):
- Open app settings > Tools
- Click on "Add..." button
- Fill in the "Add an external tool" dialog:
![image](https://github.com/d2phap/ImageGlass/assets/3154213/a9e669b5-b46c-4906-8067-46ebf5c9870e)
- Click "Add hotkey" to assign a hotkey for your tool
- Click "OK" to close the dialog, then click "Apply" to save the settings

When opening Tools menu of ImageGlass 9, you will see your new tool there:
![image](https://github.com/d2phap/ImageGlass/assets/3154213/b294c7d8-9d24-460f-850b-3c7a5a576d05)

So now you can just press the hotkey, ImageGlass will execute the tool command to copy the current viewing image to the folder you specified.
