### ISSUE TITLE
open archives and browse the images inside

### ISSUE THREAD

**Issue by SekiBetu** [d2phap/ImageGlass#1420]
### Is your feature request related to a problem? Please describe.

The images are stored in a archive(.zip .7z .rar) file, and extracting them will make a mess of the folder

### Describe the solution you'd like

use ImageGlass to open the archive file and browse the images inside without extracting them

### Describe alternatives you've considered

just like what [NeeView](https://bitbucket.org/neelabo/neeview/wiki/Home) did

### Additional context

none.

**Comment by d2phap** [comment]
Duplicated to #254
