### ISSUE TITLE
Support light theme

### ISSUE THREAD

**Issue by xmha97** [d2phap/ImageGlass#1421]
I'm using [ImageGlass Moon 9.0 beta 2](https://github.com/d2phap/ImageGlass/releases/tag/9.0.2.904)

I need the light theme.

![image](https://user-images.githubusercontent.com/23485114/189673645-8bbfc876-09b0-47d5-ad8b-aa53541082eb.png)

**Comment by d2phap** [comment]
- The `IsDark` property is just to indicate the type of the theme pack, to prepare for #434
- IG v9 changes and introduces new theme properties, you can add these settings into the `Settings` section in `igtheme.json` file:

https://github.com/d2phap/ImageGlass/blob/40c22af09e81ac6ffc8b8e0f3114615677ee4c45/v9/Components/ImageGlass.UI/Themes/IgThemeModels.cs#L62-L89

**Comment by d2phap** [comment]
It has been supported since v9.0 beta 3
