### ISSUE TITLE
Move to folder

### ISSUE THREAD

**Issue by d2phap** [d2phap/ImageGlass#1422]
From https://groups.google.com/g/imageglass/c/VDOwZo3L6uo/m/4PAFxT2UAQAJ

### Describe the solution you'd like
It would be nice to have "Quick Move shortcut"
- in Settings - there would be "Move to specific folder" path
- pressing eg. CTRL + F6 will move specific file to that folder 

as a bonus
-  there can be, lets say, 5 options for different Move folders
- and also 5 shortcuts - CTRL +F6 ... CTRL+F10

**Comment by cr1za** [comment]
I support this idea.

**Comment by d2phap** [comment]
Can be done in IG 9. For moving file, replace `xcopy` with [`move` command](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/move) instead: https://github.com/d2phap/ImageGlass/issues/1419#issuecomment-1840508259
