### ISSUE TITLE
Image corrupted after rotated

### ISSUE THREAD

**Issue by masterofobzene** [d2phap/ImageGlass#1426]
### System information:
 - Windows OS version: win 10 x64
 - ImageGlass version:  8.6.7.13 

I'm done with your software. It ruined lots of images from my collection. Recently it completely hung my pc (and I know this because it was the only program running besides windows file explorer). After the restart it started "forgeting" the zoom setting to "scale to fit" continually. After that, the 3 images I rotated where CORRUPTED BY YOUR SOFTWARE.

You should take this thing out of the internet until you fix it before it makes any more damage.

**Comment by d2phap** [comment]
Duplicated #1273

This is a known bug. IG is not the photo editor, the option to save image is unchecked by default. Instead, you should read this thing on the internet before you create any more duplicated issues.
