### ISSUE TITLE
Set GPS location to photos

### ISSUE THREAD

**Issue by xmha97** [d2phap/ImageGlass#1432]
Please add the feature to add GPS location to photos using ImageGlass.
```
exiftool -GPSAltitude="0" -UserData:GPSCoordinates="34.6363, 50.874900000000004, 0" -Rotation="0" -XMP:GPSLatitude="34.6363" -XMP:GPSLongitude="50.874900000000004" -GPSLongitudeRef="West" -GPSLatitudeRef="North" VID_20221006_094430.jpg
```
https://www.google.com/maps/@34.6363,50.874900000000004,21z

**Comment by d2phap** [comment]
In v9, you can create a new tool to pass the above command.

![image](https://github.com/d2phap/ImageGlass/assets/3154213/2df54ac6-5778-462a-9f3b-8b5cfb821c28)
