### ISSUE TITLE
Imageglass NOT respecting color profile management settings

### ISSUE THREAD

**Issue by robredrob** [d2phap/ImageGlass#1433]
### System information:
 - Windows OS version: 10 Pro
 - ImageGlass version: v8.6.7.12 x64

### To Reproduce
1. Going to ImageGlass setting and choosing color profile in color management
2. NOT also enabling "apply to non embedded images"
3. Apply/Save
4. View images with and without color embedded profiles

### Actual behavior:

Whether images have or not embedded profiles, ImageGlass shows all images the same, not respecting the settings color management options

### Expected behavior:

As in other color managed image viewers, images with different color profiles should view differently with respect to their clor profile

### Additional context:

Used color profiles from sRGB to Display P3 (Apple)

**Comment by d2phap** [comment]
After changing the color management setting, you will need to reload the image (Ctrl+R).
It's better if you have some screenshots and attach the image file here.
