### ISSUE TITLE
Can't open ppm file.

### ISSUE THREAD

**Issue by Hyderman** [d2phap/ImageGlass#1435]
### System information:
 - Windows OS version: 11
 - ImageGlass version: 8.6.7.13 x64

### To Reproduce
1. Open the image.ppm file

### Actual behavior:

Can't open file.

### Expected behavior:

Open the file.

### Screenshots:

![image](https://user-images.githubusercontent.com/81628944/196983151-50b76abf-69fb-42fa-af78-a0dbe4936dc7.png)

### Additional context:

[image.zip](https://github.com/d2phap/ImageGlass/files/9831272/image.zip)

**Comment by d2phap** [comment]
According to the error message: `Improper image header`, so this image file is invalid (invalid header).

When I try opening it with GIMP, it also shows `Invalid file`!
![image](https://user-images.githubusercontent.com/3154213/196989658-0f0c142e-2610-48d9-a563-95a4428d0782.png)

**Comment by Hyderman** [comment]
The problem seems to come from Powershell when i create the file, CMD solves the problem.
