### ISSUE TITLE
Can open jp2 images but ignores them when switching to next/previous

### ISSUE THREAD

**Issue by Shadlock0133** [d2phap/ImageGlass#1439]
### System information:
 - Windows OS version: Windows 10 x64
 - ImageGlass version: 8.7.10.26

### To Reproduce
1. Have folder of images in ".jp2" format
2. Open any image
3. Change to next/previous image

### Actual behavior:

Image closes, leaving program with empty window

### Expected behavior:

Switch to next/previous image in the folder.

### Screenshots:

Opened first image in the folder, with thumbnail panel open
![image](https://user-images.githubusercontent.com/3766527/198111375-f84bd3db-a3dd-471a-bbb1-7d4943ec3025.png)

After switching to next image
![image](https://user-images.githubusercontent.com/3766527/198111471-b83fa82a-d378-42b5-b785-feca28d26438.png)

**Comment by d2phap** [comment]
Can you check if `.jp2` is listed in the Settings > File type associations?
![image](https://user-images.githubusercontent.com/3154213/200466420-bf5aafea-b268-4655-a10f-4bce0769a6cc.png)

If not, you can add it.

**Comment by Shadlock0133** [comment]
Adding it to the list fixed it, thanks. Might be worth to add it to the list by default.
