### ISSUE TITLE
"there was a problem sending the command to the program"

### ISSUE THREAD

**Issue by Zikoooo** [d2phap/ImageGlass#144]
**everytime i try play gif , this msg pop up , it so annoying** :( 
![untitled](https://cloud.githubusercontent.com/assets/23313653/20059220/ea505cda-a4ec-11e6-9ffc-06a796b0ac3f.png)

hope there is fix .

**# Thanks.**

**Comment by ephilippona** [comment]
I could not reproduce the issue.

**Comment by d2phap** [comment]
hi @ephilippona,

Can you attach your gif file? (if possible)

**Comment by d2phap** [comment]
Closed because being unable to reproduce
