### ISSUE TITLE
Slideshow mode persists across application sessions

### ISSUE THREAD

**Issue by Setsu-BHMT** [d2phap/ImageGlass#1442]
### System information:
 - Windows OS version: 10.0.19044 Build 19044
 - ImageGlass version: 8.7.10.26 x64

### To Reproduce
1. Open an image using explorer double click
2. Once ImageGlass loads, enter slideshow mode
3. Alt+F4 to quit the program
4. Open any image using explorer double click
5. Observe ImageGlass starts in slideshow mode, paused

### Actual behavior:
Exiting ImageGlass while in slideshow mode will cause the next execution of ImageGlass to remain in slideshow mode

### Expected behavior:
Slideshow mode should be reset upon program exit

### Screenshots:
N/A

### Additional context:
If this is intended behavior, suggest adding a config option to disable it.

**Comment by d2phap** [comment]
Fixed in v9.0
