### ISSUE TITLE
TIFF: negative image positions unsupported

### ISSUE THREAD

**Issue by PeinNMB** [d2phap/ImageGlass#1446]
I use Adobe Photoshop's picture format is .tif, but it cannot be opened and the file is bad, but it is not a real damaged file.

ImageGlassThe picture cannot be opened because the file appears to be damaged or unsupported.
Magick.NET-Q16-HDRI-OpenMP-x64:TIFF:negative image positions unsupported@error/tiff.c/WriteTIFFlmage/3829

**Comment by PeinNMB** [comment]
![4AE45D17-582A-4a3c-BA95-89E612CFBCB9](https://user-images.githubusercontent.com/115677720/200098644-4acb903d-0d4d-4315-a5da-3c9e4626909f.png)

**Comment by Setsu-BHMT** [comment]
Well if you have complaints you should log it with Magick.NET...it's a different project. ImageGlass just uses the library.

**Comment by d2phap** [comment]
@PeinNMB 
You can either report this to https://github.com/dlemstra/Magick.NET, or attach your TIF file here so that I can test it.
