### ISSUE TITLE
Cannot minimize an image under certain circumstances.

### ISSUE THREAD

**Issue by RVillaT** [d2phap/ImageGlass#1448]
### System information:
 - Windows OS version: Windows 11 64 bit 22H2 (build 22621.819)
 - ImageGlass version: Kobe v8.7.11.6 x64

### To Reproduce
Automatic zoom activated (1)
Fit to window activated (F9)
Toolbar hidden (T)
1. Open any image with a vertical resolution higher than the screen's max resolution : the image fits to the screen.
2. Show the toolbar (T).
3. Hide the toolbar (T).
4. Minimize image -> IMPOSSIBLE

### Actual behavior:
Cannot minimize image. The image maximizes in a loop.

### Expected behavior:
Image can be minimized.

**Comment by d2phap** [comment]
Thanks @RVillaT 
Confirm the bug!

**Comment by d2phap** [comment]
This issue is fixed in the latest build of ImageGlass Moon 8.7: https://imageglass.org/moon
