### ISSUE TITLE
An option in the settings to show/hide file names for images in the Thumbnail panel

### ISSUE THREAD

**Issue by Eugenii10** [d2phap/ImageGlass#1449]
### Is your feature request related to a problem? Please describe.
Let's imagine a situation. You have a folder with lots of images some of which are very close similar. You have opened one of images in external software (e.g. Paint), your ImageGlass window is focused on another image from that folder. Then you need to find some data from `exiftool` for the image opened in the external software (in this case Paint). You switched to ImageGlass and started scrolling through the Thumbnail panel (because ImageGlass doesn't have an embedded File Explorer) looking for the image. You know the file name for the image image you want (you see it in the external software), but since ImageGlass doesn't show file names in the Thumbnail panel you have to click on each similar image and check for its name in the Title bar.

### Describe the solution you'd like
An option in the settings to show/hide file names for images in the Thumbnail panel.

### Describe alternatives you've considered
There are no alternatives. You have to click on each similar image and check for its name in the Title bar.

### Additional context
I have found that ImageGlass had file names in the Thumbnail panel before. https://github.com/d2phap/ImageGlass/issues/315

**Comment by d2phap** [comment]
Hi @Eugenii10 

[ImageGlass v9.0 beta 2](https://github.com/d2phap/ImageGlass/releases/tag/9.0.2.904) added support for this feature via the setting `ShowThumbnailFilename` in `igconfig.json`. It also supports showing tooltip of image information when you hover on the thumbnail.

![image](https://user-images.githubusercontent.com/3154213/201915269-ad024e96-ce49-4693-8dd1-13f40e0fb99f.png)

**Comment by Eugenii10** [comment]
Hello👋 
As I understand there are no **Settings** window and **Tools** now in the 9.x beta. And I can't move Thumbnail panel to the right side. So I will be waiting for future beta releases 👀!
And I have another suggestion. If you want I can create a separate issue for this:
+ Embed an 'exiftool' window somewhere in the main window. Single monitor users will thank you 😉! With an option to open it in a separate window for multi-monitor users.

Nice software btw 👍!

**Comment by d2phap** [comment]
I will close this as it's implemented in v9.0 beta
