### ISSUE TITLE
This image doesn't load in ImageGlass Moon

### ISSUE THREAD

**Issue by floppyD** [d2phap/ImageGlass#1453]
### System information:
 - Windows OS version: 10
 - ImageGlass version:  9.0.2.904_Beta-2

### To Reproduce
1. Open https://upload.wikimedia.org/wikipedia/commons/6/6d/The_Garden_of_Earthly_Delights_by_Bosch_High_Resolution.jpg?download

### Actual behavior:
It doesn't load.

### Expected behavior:
It loads.

### Additional context:
Other than being really slow, Kobe 8.7.11.6 opens it just fine.

**Comment by floppyD** [comment]
Neither can open this one by the way, Moon returns this error:
![image](https://user-images.githubusercontent.com/29208110/204161205-cba5c9d0-c2e1-45f7-a998-fc587c7b4caf.png)

https://upload.wikimedia.org/wikipedia/commons/9/96/The_Garden_of_earthly_delights.jpg?download

**Comment by d2phap** [comment]
IG Moon v9.0 beta 2 does not support opening image file that is bigger than 16384px because this is the maximum supported dimension for Direct2D texture.

In the beta 3 release, ImageGlass will be able to open it by scaling to 16384px.

**Comment by d2phap** [comment]
Released [ImageGlass Moon 9.0 beta 3](https://github.com/d2phap/ImageGlass/releases/tag/9.0.3.1225)!
