### ISSUE TITLE
certain TIF pictures doesnt load

### ISSUE THREAD

**Issue by JoGrob** [d2phap/ImageGlass#1454]
### System information:
 - Windows OS version:  10
 - ImageGlass version:  8.7.11.6

### To Reproduce
1. try loadin TIF picture
2. errormessage appears

### Actual behavior:
instead of displaying the picture a errormessage appears

### Expected behavior:
TIF picture should be displayed

### Screenshots:
see attached

### Additional context:
Problem is also reported to [Magick.NET] (https://github.com/dlemstra/Magick.NET)
https://github.com/dlemstra/Magick.NET/issues/1310#issue-1467557297
with possible workaround 
https://github.com/dlemstra/Magick.NET/issues/1310#issuecomment-1330458735

![errormsg](https://user-images.githubusercontent.com/59739587/204544689-453dc832-34a9-4c6d-8f10-4a245735846f.jpg)
[picture.zip](https://github.com/d2phap/ImageGlass/files/10113513/picture.zip)

**Comment by d2phap** [comment]
I managed to make it work by ignoring 3 tags:
```
"34022", // ColorTable
"34025", // ImageColorValue
"34026", // BackgroundColorValue
```

Will include this in the future release

**Comment by d2phap** [comment]
[ImageGlass Moon 9.0 beta 3](https://github.com/d2phap/ImageGlass/releases/tag/9.0.3.1225) fixes this issue
