### ISSUE TITLE
Slow image transition "wait loading" warning

### ISSUE THREAD

**Issue by DrVektor** [d2phap/ImageGlass#1455]
### System information:
 - Windows OS version: Ms windows 10 x64
 - ImageGlass version: 8.7.11.6
 - cpu : ryzen 5 5600x gigabyte b450m s2h 16 3200 t-force vulcan 16gb memory.

### To Reproduce
1. It always happens whenever I open one image and switch to another. However, when I do the same with jpegview, this wait never happens.
2. I dont know is this a bug but annoying and reason to switch jpegview but image-glass more accurate colors and pixel rendering than jpegview. 
3. 
4.

**Comment by d2phap** [comment]
ImageGlass 8.x does not support hardware acceleration so it's much slower.
You can try [ImageGlass 9.0 beta 3](https://github.com/d2phap/ImageGlass/releases/tag/9.0.3.1225) instead.

The other solution is increasing the `ImageBoosterCacheCount` number, this will use more RAM to cache the image into memory.

**Comment by DrVektor** [comment]
Thank you my friend. I downloaded but toolbar is at top. How can i move it bottom. I looked up to config.json but i coulnd find the line. Maybe need to add extraline for to do this. But how and which? Thank you again. 🙂

**Comment by d2phap** [comment]
It does not support yet. I will add in v9.0 beta 4
