### ISSUE TITLE
[small feature] a toolbar button to toggle "Display new image in folder automatically" 

### ISSUE THREAD

**Issue by Extraltodeus** [d2phap/ImageGlass#1456]
First I want to say thanks for this great software!

Then my request :

I would like it to be possible to have a toolbar button to toggle the "Display new image in folder automatically" .
I use ImageGlass for viewing StableDiffusion output. That functionnality is excellent to let me see directly the output as soon as it's there, with the zoom level locked. But now when I want to check out older images, I have to manually disable that feature from the options or wait for my batch to finish. It would be really nice if it was possible to have such shortcut!

Best regards

**Comment by d2phap** [comment]
To keep IG simple, I will not implement this.
