### ISSUE TITLE
Exif support bug

### ISSUE THREAD

**Issue by ZhiZe-ZG** [d2phap/ImageGlass#1459]
### System information:
 - Windows OS version: Windows 10
 - ImageGlass version: ImageGlass 8.7

### To Reproduce

1. Down load exif from official site (windows executable file).
2. Unzip the `exiftool-12.52.zip` to get the exe file. The default exe file name is `exiftool(-k).exe`.
3. Select `exiftool(-k).exe` in ImageGlass, then the program no respond.

### Additional context:

Rename the `exiftool(-k).exe` as `exiftool.exe` can avoid this.

**Comment by d2phap** [comment]
Thanks @ZhiZe-ZG 
It's duplication of #1178. Exif tool currently only accepts filename that contains alphabet (a to z).
