### ISSUE TITLE
Some suggestions/wishes

### ISSUE THREAD

**Issue by DGardell** [d2phap/ImageGlass#146]
Hello!

I like your application, just what I was looking for. I've also made a translation to Swedish. Anyhow, I have some suggestions or maybe you can call it wishes. But first of all, thank you for your work! :) 👍 

* Support for *.cr2 (Canon RAW-format)
* Customizable layout, i.e. select which buttons to show at the toolbar, the size of the buttons and ability to move the toolbar (I would like it centered at the bottom like in Windows Photo Viewer)
* Ability to show image properties/info somewhere on the screen, like photo/creation date and EXIF. Now there is some info at the top bar, but the date is set to last changed, not the real creation date for example.
* More settings for the zoom. For instance zooming with the mouse wheel, I would like to have the ability not to use it for zooming out (very rarely do that), i.e. if I had zoomed in it should stop at the image original size (if it's smaller than the window, otherwise full view inside the window) when I zoom out using the mouse wheel.

That's about it. If this was possible it would be the ideal image viewer for me.

**Comment by d2phap** [comment]
Thanks for the feedbacks

**Comment by feidaman** [comment]
Regarding the zooming out request, if implemented it would have to be optional. There are times when zooming out smaller than original size is actually handy. For example, when I take a screen capture on a hi-res display, the resulting image is too big, some times I deliberately zoom way out, then take the screen capture. Useful for pasting a quick photo into a chat window and that sort of thing.

**Comment by d2phap** [comment]
- `RAW` formats are supported in v4.5
- _More settings for the zoom_: I won't implement this

**Comment by d2phap** [comment]
Implemented `Customizable layout: select which buttons to show at the toolbar`

**Comment by d2phap** [comment]
Merge this to #336 (EXIF) and close issue

**Comment by d2phap** [comment]
Implemented Exif tool in ImageGlass Moon: https://imageglass.org/moon
For more details, check at #871
