### ISSUE TITLE
Unable to open avif

### ISSUE THREAD

**Issue by superbonaci** [d2phap/ImageGlass#1465]
Can't open this AVIF:

[animation-woods.avif.zip](https://github.com/d2phap/ImageGlass/files/10240636/animation-woods.avif.zip)

**Comment by d2phap** [comment]
ImageGlass does not support animated format of AVIF because MagickNET does not.

**Comment by dlemstra** [comment]
Magick.NET has support for reading animated AVIF files but this file appears to be Duck_IVF (https://wiki.multimedia.cx/index.php/Duck_IVF) instead of AVIF.
