### ISSUE TITLE
Animated webp takes a lot of time to load

### ISSUE THREAD

**Issue by superbonaci** [d2phap/ImageGlass#1466]
### System information:
 - Windows OS version: Windows 11
 - ImageGlass version: 8.7.11.6 x64

### To Reproduce
1. Opening this animated webp works but takes about 17 seconds to start reproducing it, meanwhile displays "Loading...". I think it's too much for a lightweight vysor.

[animation-woods.webp.zip](https://github.com/d2phap/ImageGlass/files/10240659/animation-woods.webp.zip)

**Comment by d2phap** [comment]
This issue is fixed in the latest build of ImageGlass Moon 8.7: https://imageglass.org/moon

**Comment by superbonaci** [comment]
Confirmed it works thank you very much!
