### ISSUE TITLE
New images ignore Windows Files Explorer sort order.

### ISSUE THREAD

**Issue by drandarov-io** [d2phap/ImageGlass#1467]
### System information:
 - Windows OS version: `Windows 11 22H2 (22623.1037)`
 - ImageGlass version: `8.7.11.6 x64`

### To Reproduce
1. Sort image folder by date (newest to oldest / descending)
2. Open newest image
3. Create newer image in folder

### Actual behavior:
The newest image is put at the very end of the list instead of the very start. 
If `Display new image in folder automatically` is enabled the view switches to the new image and you are at the very end of the thumbnail panel.

### Expected behavior:
The newest image is put at the very start of the list instead of the very end. 
If `Display new image in folder automatically` is enabled the view switches to the new image and you are at the very start of the thumbnail panel.

### Screenshots:
/

### Additional context:
Using `File > Reload image list` /  `Ctrl+Shift+R` fixes the problem, but needs to be pressed after every new image.

**Comment by d2phap** [comment]
Thanks @drandarov-io!
It was put at very last to avoid the app overworked on sorting the file list.
I will add an option to do it

**Comment by drandarov-io** [comment]
Thanks, that would be great!

**Comment by guest999v22** [comment]
> Thanks @drandarov-io! It was put at very last to avoid the app overworked on sorting the file list. I will add an option to do it

To add to this issue, if the option "loop back viewer to the first image when reaching the end of the list" is unchecked then if the viewer is at the currently newest image & after that some newer image is created in the folder then the newer image is added at the end of the list so only way to reach from former newest image to the current newest image is by scrolling from the beginning to the end of the list in this case which can be quite time consuming & annoying if folder has hundreds of images. Also please change the behaviour of "Refresh" button in toolbar to that of "ctrl+shift+R" as before reading this thread I wasn't aware that "refresh" button in toolbar behave differently from the "ctrl+shift+R" or at least give an option to display a button executing "ctrl+shift+R" in toolbar.

**Comment by d2phap** [comment]
Implemented in [ImageGlass 9.2 Beta](https://github.com/d2phap/ImageGlass/releases/tag/9.1.8.1104), new created images will be auto-rearranged as the current sort order.
