### ISSUE TITLE
May you add moving to next image by mouse Scroll Wheel

### ISSUE THREAD

**Issue by train777** [d2phap/ImageGlass#1469]
Image Glass image browser is one of the best these days .

many people has shoulder pain and browsing images nee to click 
the mouse . May you add one new feature option to move to next image 
by using  mouse scroll wheel which is faster and less pain for shoulder muscles

i got that option in Irfan photo browser  and hope you add it to your browser 

bless you  

Tariq

**Comment by d2phap** [comment]
In v8, you can change it in Settings > Image > Mouse wheel actions
![image](https://user-images.githubusercontent.com/3154213/209430690-e548a554-00a7-442d-a94b-2c30c497dba4.png)

In v9.0 beta, in `igconfig.json` file, set this setting:
```json
"MouseWheelActions": {
  "Scroll": "BrowseImages"
},
```

**Comment by train777** [comment]
thank you dear
