### ISSUE TITLE
Suggestion: double-click zoom

### ISSUE THREAD

**Issue by btxtiger** [d2phap/ImageGlass#147]
Hi, 
it would be so nice to have a double click zoom / zoom out.
E.g. The image is completely shown on startup. Let's say the scaling is 70%. When I doubleclick the image, the scaling changes to a preset zoom factor (e.g. 2x), so the scaling changes to 140%. Another doubleclick leads back to 70% default scaling.
This way is a fast option to quickly look at details in the image.

**Comment by d2phap** [comment]
Thanks @btxtiger 
That's great

**Comment by d2phap** [comment]
I decided to use double-click action for toggling
- View actual size of image, and
- Auto fit the image

This feature is implemented in ``develop`` branch
