### ISSUE TITLE
Version 9.0 Does not support newer .Net version

### ISSUE THREAD

**Issue by Tarek-Hasan** [d2phap/ImageGlass#1471]
### System information:
 - Windows OS version: 10 22H2
 - ImageGlass version: 9.0 beta3

### To Reproduce
1. Uninstall older .net versions (except versions ships with windows)
2. install .net 7.0
3. open the program

### Actual behavior:
Version 9.0 of ImageGlass doesn't open with newer .net version. It says .net framework is missing.

### Expected behavior:
program should automatically support newer .net version

**Comment by d2phap** [comment]
I have added [.net7 release](https://github.com/d2phap/ImageGlass/releases/tag/9.0.3.1225). But it's weird that apps built with .net6 cannot run on .net7
