### ISSUE TITLE
[9.0] make the "navigation arrow buttons" clikable on whole left and right areas like in v8.7

### ISSUE THREAD

**Issue by diieg707** [d2phap/ImageGlass#1472]
i just realized when "navigation arrow buttons" is checked on v8.7 the whole left and right area is clikable, on version 9 only the arrow circle area is clikable,

please make the version 9 just like the 8.7, it's so much more confortable not need to aim at the very middle to be able to toggle next/previous image

**Comment by d2phap** [comment]
Done in [v9.0 beta 4](https://github.com/d2phap/ImageGlass/releases/tag/9.0.4.416)
