### ISSUE TITLE
extend the "navigation arrow buttons" click area to bottom 

### ISSUE THREAD

**Issue by diieg707** [d2phap/ImageGlass#1474]
when we check "navigation arrow buttons" on v8.7 only the left and right bars are clickable, please make it possible to click on the bottom area as well like in the picture
![2022-12-30 00_07_04-Sandboxie_BorderWindow](https://user-images.githubusercontent.com/54504707/210030574-128fc392-3241-4f08-9f20-b36ce33b85cb.png)
**green = previous click area
red = next click area**

**Comment by d2phap** [comment]
I will not implement this because it will become messy when the app layout is changed
