### ISSUE TITLE
Please redesign buttom layout.

### ISSUE THREAD

**Issue by lessload** [d2phap/ImageGlass#1475]
When down size windows buttom will show like `|  =  | ... |` 
Make it not common sense for user experience beacuse in many apps keep `|  =  |` buttom to left or right.
If buttom layout look like `| ... |  =  |` it will make more common sense and better user experience.

**Comment by daved163g** [comment]
you can configure the toolbar to suit yourself

**Comment by d2phap** [comment]
@lessload this overflow button position comes from ToolStrip component of WinForms framework which is not customizable. I will close this as a limitation.
