### ISSUE TITLE
fuzzy svg

### ISSUE THREAD

**Issue by hpytree** [d2phap/ImageGlass#1476]
### System information:
 - Windows OS version: win10
 - ImageGlass version: 
[ImageGlass Kobe 8.7.11.6 - Hotfix](https://github.com/d2phap/ImageGlass/releases/tag/8.7.11.6)

I have opened a svg image from [material-design-icons](https://github.com/google/material-design-icons). At first,the image was small but clear. But when I zoom in,the image became fuzzy.(you know, svg is vectorial) I think it's a bug. Thank you very much.

**Comment by d2phap** [comment]
Hi @hpytree 
ImageGlass does not support for scaling SVG (yet). See #421
