### ISSUE TITLE
Webp image write support.

### ISSUE THREAD

**Issue by onolox** [d2phap/ImageGlass#1477]
Webp image write support.

Webp is becoming dominant image format, it's way better and smaller than png, gif or jpg.
Support to save/convert a file to Webp is a must in 2023.

Thanks for this amazing piece of software!

**Comment by MoemenShahawy** [comment]
webp can chortle on it

**Comment by 3xploiton3** [comment]
AVIF way better when achieve small size image

https://web.dev/compress-images-avif/

**Comment by d2phap** [comment]
Implemented in [v9.0 beta 4](https://github.com/d2phap/ImageGlass/releases/tag/9.0.4.416)

**Comment by onolox** [comment]
> AVIF way better when achieve small size image
> 
> https://web.dev/compress-images-avif/

Then open your feature request.

**Comment by donatopace** [comment]
Offline method to convert:
https://avif.io/
Can you add it under IMAGEGLASS?
