### ISSUE TITLE
Upright Nikon (NEF) Raw images are displayed landscape instead portrait (wrong orientation)

### ISSUE THREAD

**Issue by robbx335** [d2phap/ImageGlass#1478]
### System information:
 - Windows 10 21H2
 - ImageGlass version: 8.7.11.6

### To Reproduce
1.  open an upright NEF raw file 

### Actual behavior:
ImageGlass displays Nikon NEF Raw format upright images in landscape (90° clockwise turned)
Other image display programs (Windows built in, Irfanview, Honeyview etc.) do show the 
NEF image correctly oriented

### Expected behavior:
image should be displayd upright as other image display programs do

### Screenshots:
![image](https://user-images.githubusercontent.com/122089366/210997981-55989369-cb66-4291-91d8-fad3c91e6829.png)

**Comment by d2phap** [comment]
Can you share the file? Thank you!

**Comment by daved163g** [comment]
This also occurs for my ORF and RAF raw files, too. ImageGlass seems to be misinterpreting/ignoring the EXIF orientation flag for raw files. Should be a simple fix.

**Comment by robbx335** [comment]
Hello,

Sorry for the late response.

Here finally is a link to two upright files (NEF and DNG). Both are not displayed with the proper orientation.

 <https://drive.google.com/drive/folders/1URc8sag_IxuECfmLomT5PWUBTr1_sNTv?usp=share_link> https://drive.google.com/drive/folders/1URc8sag_IxuECfmLomT5PWUBTr1_sNTv?usp=share_link

Thank you for ImagGlass. I like this program very much.

Thomas

 

Von: Phap Dieu Duong ***@***.***> 
Gesendet: Samstag, 4. Februar 2023 11:12
An: d2phap/ImageGlass ***@***.***>
Cc: Thomas ***@***.***>; Author ***@***.***>
Betreff: Re: [d2phap/ImageGlass] Upright Nikon (NEF) Raw images are displayed landscape instead portrait (wrong orientation) (Issue #1478)

 

Can you share the file? Thank you!

**Comment by d2phap** [comment]
Sorry @robbx335 I haven't downloaded it. Can you share again 😥

**Comment by robbx335** [comment]
Hello,

No problem. Here are two upright images.

https://drive.google.com/drive/folders/1a1t44_sRQZSuxR1Ga1cjivIlPrLhl7DR?usp=share_link

Thanks.

Thomas

 

Von: Phap Dieu Duong ***@***.***> 
Gesendet: Dienstag, 4. April 2023 15:56
An: d2phap/ImageGlass ***@***.***>
Cc: Thomas ***@***.***>; Mention ***@***.***>
Betreff: Re: [d2phap/ImageGlass] Upright Nikon (NEF) Raw images are displayed landscape instead portrait (wrong orientation) (Issue #1478)

 

Sorry @robbx335 <https://github.com/robbx335>  I haven't downloaded it. Can you share again 😥

**Comment by d2phap** [comment]
Thank you!
