### ISSUE TITLE
Fullscreen / Frameless via F10/F11 behaves strange

### ISSUE THREAD

**Issue by robbx335** [d2phap/ImageGlass#1479]
### System information:
 - Windows version: 10 21H2 
 - ImageGlass version: 8.7.11.6

### To Reproduce
I have a two monitor setup:
- left: 3840x2160 Text & App Scaling 175%
- right: 1920x1080 Text & App Scaling 100%

### Actual behavior:
IG behaves strange, when F10 and F11 are pressed multiple times in a random order.
Both Window frame and position appearence is randomly mixed, not predictable and 
doesn't match with the checkmarks shown in the hamburger menu.

another issue is, that 
when zoom is set to "scale to width" and Frameless and Fullscreen are on
and then F11 is pressed, a part of the picture appears on the right screen

### Screenshots:
wrong indicator for "Frameless":
![image](https://user-images.githubusercontent.com/122089366/211004060-fca81103-58d0-4287-8049-6c44f4a94fb7.png)

part of image on right screen:
![20230106_120228](https://user-images.githubusercontent.com/122089366/211004180-e1dfc075-c47c-4ec5-aa90-cfaca3548253.jpg)

**Comment by d2phap** [comment]
@robbx335 could you please check if this issue still persists with IG v9?
