### ISSUE TITLE
Could not open this image

### ISSUE THREAD

**Issue by cmhdream** [d2phap/ImageGlass#1484]
### System information:
 - Windows OS version: win10 pro x64 22h2 19045.2486
 - ImageGlass version: ImageGlass_Moon_9.0.3.1225_Beta-3_x64 net6

### To Reproduce
1. open app
2. open picture from folder
3. 
4. 

### Expected behavior:

Could not open this image
imageGlass moon v9.0.3.1225 (64-bit,. Net 6.0.13)
Error Details:
System.Private.CorelibL An item with the same key had already been added.
key:a26c3c36-234c-4950-ae16-e34aace71d0d

### Screenshots:

![Snipaste01-18_073853](https://user-images.githubusercontent.com/24859526/213036001-866a55b9-47fa-4d4f-8d66-72742d75d4f9.jpg)

### Additional context:

net 6.0 & net7.0 the same question.

**Comment by d2phap** [comment]
Can you check v9.0 beta 4 if the issue still persists?
