### ISSUE TITLE
Zooming in/out rescales entire window everytime and causes ugly flickering

### ISSUE THREAD

**Issue by zachHixson** [d2phap/ImageGlass#1486]
### System information:
 - Windows OS version: Windows 10
 - ImageGlass version: 8.7

### To Reproduce
1. Open image
2. scroll in and out
3. observe the entire window redrawing and changing size

### Actual behavior:
Whenever I zoom in and out the entire window changes size and there is no setting to disable it. It doesn't do this smoothly and instead the entire window flashes at it scales up and redraws. It's especially bad for SVGs and ends up pixilating them badly in most cases. 

### Expected behavior:
Window stays same size, but image inside it changes size

### Additional context:
It wasn't always this way and used to work as expected. Not sure which update broke it, but it was definitely in the last 6-8 months.

**Comment by d2phap** [comment]
It seems you enabled the Window Fit feature. You can disable it in main menu > Window Fit

**Comment by zachHixson** [comment]
Huh, could have sworn I clicked that, but I guess I clicked every other option but that. Worked, thanks!
