### ISSUE TITLE
HDR images are not displayed as HDR when HDR desktop is enabled

### ISSUE THREAD

**Issue by PaulCoddington** [d2phap/ImageGlass#1488]
### System information:
 - Windows OS version: 11
 - ImageGlass version: 8.7.11.6

### To Reproduce
1. Open EXR file in ImageGlass on SDR Windows Desktop (10-bit sRGB).
2. Open EXR file in ImageGlass on HDR Windows Desktop (12-bit BT.2100 PQ).

### Actual behavior:
EXR file is displayed in SDR when SDR desktop is active.
EXR file is displayed in SDR when HDR desktop is active.

### Expected behavior:
EXR file should be displayed in SDR when SDR desktop is active.
EXR file should be displayed in HDR when HDR desktop is active.

### Additional context:
HDR is becoming more mainstream and there appears to be no 
HDR-capable photo viewers for Windows apart from opening images 
in an editing application, such as Affinity Photo.

As HDR is more lifelike than SDR and can potentially capture the 
full range of photographic slides and negatives, it seems best 
to scan historical/family photos in HDR.

Easily displaying large collections of HDR photos (including slideshows) 
will likely become more commonplace in the near future.

**Comment by d2phap** [comment]
Probably duplication of #1430

**Comment by d2phap** [comment]
@PaulCoddington can you try [ImageGlass Moon 9.0 RC](https://github.com/d2phap/ImageGlass/releases/tag/9.0.6.1008) if it works for you when HDR is on?

**Comment by PaulCoddington** [comment]
> @PaulCoddington can you try [ImageGlass Moon 9.0 RC](https://github.com/d2phap/ImageGlass/releases/tag/9.0.6.1008) if it works for you when HDR is on?

I'm a bit pressed at the moment and will try to get to it soon. In the meantime, I hope others will also help with testing. Thank you for efforts.

**Comment by gwy15** [comment]
I can confirm that with ImageGlass 9.0 RC 45 (9.0.6.1008), ImageGlass cannot display HDR images properly.
I tested avif, jxl (generated by Adobe Camera Raw) and heic (generated by iOS) files.
avif and jxl look gray, while heic can fallback to SDR properly but lose all HDR effect.

**Comment by BenjaProg** [comment]
First time using ImageGlass primarily because I want to display the HDR photos of my Pixel 8 properly.
ImageGlass is displaying the images like Windows Photos, Irfanview, Firefox and [HDRImageViewer](https://github.com/13thsymphony/HDRImageViewer).
Only Iron browser (chromium, didn't test chrome) shows the images like on the Pixel 8 itself, with correct brightness in the highlights. All others look like the additional HDR brightness information is not applied and only the fallback base image of the *.jpg is used. To be honest I am not sure that it works like this, but it seemed like it to me.

Edit: Ah just realized the ticket is closed because it will not be implemented

**Comment by PaulCoddington** [comment]
> @PaulCoddington can you try [ImageGlass Moon 9.0 RC](https://github.com/d2phap/ImageGlass/releases/tag/9.0.6.1008) if it works for you when HDR is on?

Sorry it took so long to get back.

Have downloaded 9.0.11.502 for a quick play.

EXR 16-bit and EXR 32-bit display as sRGB SDR on Windows 11 HDR desktop.
PNG 32-bit HDR displays without the BT.2100 PQ curve applied (washed out).

Potential problem: Windows misreports my monitor as 1500 nits, which could potentially crush levels, but the loss of wide color gamut is obvious and ImageGlass only matches Affinity Photo in colour and dynamic range after Affinity Photo has been used to convert EXR to sRGB.
