### ISSUE TITLE
Problem with   .svg  images

### ISSUE THREAD

**Issue by Csumidex** [d2phap/ImageGlass#1489]
.SVG image  (1024 x 768 px) not showing correctly

Same image is OK in Irfan Wiev . Here is a flag of Pitcarin Island (Oceania) + Andorra (Europe) .... in your wiever and in Irfan View

### Screenshot
![image](https://user-images.githubusercontent.com/3154213/216371557-a5ea0132-9462-408a-8251-ebf0e988db7f.png)

![image](https://user-images.githubusercontent.com/3154213/216371585-c72a9d24-8a11-4467-8c07-480207bd211b.png)

Image Glass 8.7.116 portable X86
Win 7 Ultimate X86

**Comment by d2phap** [comment]
Hi @Csumidex,
ImageGlass uses [Magick.NET](https://github.com/dlemstra/Magick.NET) to decode the image file. I suggest you to report this issue to Magick fork with a sample file.
