### ISSUE TITLE
Ask before delete picture

### ISSUE THREAD

**Issue by tekord** [d2phap/ImageGlass#149]
I accidentally pressed DELETE button, picture changed and I had no idea my picture has been deleted. We definetelly need confirmation before delete. Just make flag in app settings. Somebody do not need confirmation, but for me it is vital.

Thanks.

**Comment by d2phap** [comment]
Hi @tekord 

Since Issue #33, Delete confirmation dialog was been removed from ImageGlass.
I think, better to have an option that user can enable it

Phap

**Comment by d2phap** [comment]
Added this option
