### ISSUE TITLE
Can you add a feature to turn on/off transparency when displaying images?

### ISSUE THREAD

**Issue by l19ht** [d2phap/ImageGlass#1491]

**Comment by l19ht** [comment]
![Snipaste_2023-02-08_14-47-50](https://user-images.githubusercontent.com/11738989/217455153-3290f354-b202-4b9a-8aed-0460fdf2ae03.png)
Transparent images do not show RGB information.

**Comment by d2phap** [comment]
I don't get what you mean here. If the image has alpha pixel, you can toggle the checkerboard background and see.
