### ISSUE TITLE
Stack Multiple Images Into One Window (Tabs support)

### ISSUE THREAD

**Issue by DankestFke** [d2phap/ImageGlass#1494]
### Opening multiple photos becoming a hassle when you try to alt + tab on windows
In that case, why don't add a feature which have tabs that are able to store multiple images in ImageGlass than having multiple instances as an option. In my opinion, this may increase the load time too.

![cool suggestion](https://user-images.githubusercontent.com/62785913/219843352-80fc151a-768c-4e26-a199-4127968f4f5b.png)

**Comment by d2phap** [comment]
Sorry I have no plan for this feature
