### ISSUE TITLE
当程序窗口关闭并且保持后台运行时，希望可以解除文件夹的占用

### ISSUE THREAD

**Issue by liJie-wk** [d2phap/ImageGlass#1495]
![image](https://user-images.githubusercontent.com/57932868/219899746-dbd22d91-368b-42bc-b4be-1ca6ec2ef38b.png)

有时候浏览完图片后，想进行文件归类整理，系统就会提示文件被占用，无法修改

**Comment by liJie-wk** [comment]
![image](https://user-images.githubusercontent.com/57932868/219898990-26abe335-7258-40fa-82bd-3e234f93b41b.png)

**Comment by liJie-wk** [comment]
有时候浏览完图片后，想进行文件归类整理，系统就会提示文件被占用，无法修改

**Comment by d2phap** [comment]
Please edit your post in English
