### ISSUE TITLE
Switch themes when Windows switches from Light to Dark mode

### ISSUE THREAD

**Issue by Euan-Wall** [d2phap/ImageGlass#1496]
### Is your feature request related to a problem? Please describe.
My Windows 11 changes automatically from light to dark mode at sunset. ImageGlass stays in Light Gray theme.

### Describe the solution you'd like
I would like to change automatically between Kobe and Light gray themes when Windows theme changes from light to dark.

**Comment by d2phap** [comment]
Please follow #434 for future update.
Thank you!
