### ISSUE TITLE
Add "Save" icon to toolbar, currently only "Save As" exists

### ISSUE THREAD

**Issue by heraldodinero** [d2phap/ImageGlass#1497]
### Is your feature request related to a problem? Please describe.
I make extensive use of toolbars. When rotating images or making other quick edits, there's no toolbar icon to save the existing file without requiring a filename dialog box (ie what "Save As" produces). A quick icon to save/update the existing file would be preferable for such an otherwise awesome program in every other way.

### Describe the solution you'd like
Add a "Save" button similar in presentation to the Save As but with a clear differentiation. 

### Describe alternatives you've considered
I'm currently using the 3-dots -> File -> Save menu. It's fine, it works, but a simple Save icon in the toolbar would work even better!

### Additional context
n/a

**Comment by d2phap** [comment]
Hi @geraldsnm,

You can always press the hotkey <kbd>Ctrl+S</kbd> to save the viewing image.

If you use v9.0 beta, you can add new button to the toolbar by editing the `igconfig.json` file.
```json
"ToolbarItems": [
  {
    "Type": "Button",
    "Id": "Btn_Save",
    "Text": "Save image",
    "DisplayStyle": "Image",
    "Image": "C:\\path\\to\\save.svg",
    "OnClick": {
      "Executable": "IG_Save"
    }
  }
]
```

I close this ticket because it's implemented in v9.0 beta.
