### ISSUE TITLE
Option to disable "Set as desktop background." context menu.

### ISSUE THREAD

**Issue by JonathanPitre** [d2phap/ImageGlass#1498]
### Is your feature request related to a problem? Please describe.
No

### Describe the solution you'd like
It would be great to have a new feature to disable "Set as desktop background". It makes sense in an enterprise where we wish to block wallpaper change. At the moment, even if we have a Windows GPO to disable background change, ImageGlass can bypass it.

You could add a new feature into igconfig.admin.xml to block background changes and remove the context menu option. Something like:

`<Item key="IsBackgroundChangeAvailable" value="False" />`

### Describe alternatives you've considered
Windows GPO to block background change is not preventing ImageGlass from doing it. However, Windows Photos seems to respect the setting.

![image](https://user-images.githubusercontent.com/15003329/220453543-f691ca1f-d9e4-4a36-b39b-cfcb414c6346.png)

**Comment by d2phap** [comment]
### 🔴 For v9.0, pls refer to https://github.com/d2phap/ImageGlass/discussions/1947#discussioncomment-9807788

### 🔵 For v8.8
IG 8.8 adds support for this feature via the setting `DisabledMenus` in config file. You can disable multiple menus by using the menu names, separated by semicolon:
```xml
<!-- disable menu mnuMainSetAsLockImage and mnuMainSetAsLockImage -->
<Item key="DisabledMenus" value="mnuMainSetAsDesktop;mnuMainSetAsLockImage" />
```

To know the menu names which start with `mnu` prefix, you can refer to:
https://github.com/d2phap/ImageGlass/blob/eeaeb86d73e9c6ac339b1c98652ed11c53d78c94/Source/ImageGlass/frmMain.Designer.cs#L2115-L2230

**Comment by JonathanPitre** [comment]
that's awesome! Thank you
