### ISSUE TITLE
Toolbar button twinkle one time when switch to another picture

### ISSUE THREAD

**Issue by qing2023** [d2phap/ImageGlass#1499]
### System information:
 - Windows OS version: win11 (22H2)
 - ImageGlass version:  8.7.11.6 x64

### To Reproduce
1. 
2. 
3. 
4. 

### Screenshots:

![picture88](https://user-images.githubusercontent.com/126084818/220651863-be62f4fa-7f5a-461a-95d1-b10d1c2d6ac5.png)

**Comment by d2phap** [comment]
This should be fixed in v9.0 beta.
