### ISSUE TITLE
Cannot launch igtasks.exe

### ISSUE THREAD

**Issue by Baegus** [d2phap/ImageGlass#15]
When I try to create a language pack or do anything else that launches igtasks.exe, nothing happens. No errors or freezes, no new processes running.
Changing UAC or compatiblity settings doesn't change anything.

Running Windows 8.1

**Comment by d2phap** [comment]
Thank  your for your report.
I confirm this issue, and will fix in the next release.

**Comment by d2phap** [comment]
Fixed
