### ISSUE TITLE
Suggestion: Hardware acceleration thing, or just lack of performance.

### ISSUE THREAD

**Issue by Rezzered** [d2phap/ImageGlass#150]
Hi ! Thank you for such wonderful app, really comes in handy for replacing the current horrible windows 10 Photo viewer.

I had a question regarding the performance of photo viewer, since i have noticed, when viewing and moving around images while zoomed, or just viewing images that are bigger than my monitor, the thing doesn't feel so smooth as to comparision like Windows 7 picture viewer, or Windows 10 photo viewer.
Any plans on making picture overview experience a bit smoother ? =]

P.S My PC -
Clean Win 10 Pro 1607 installation
i5-4670 3.8GHz
8GB DDR3 RAM
GTX 770
All drivers up to date.

Thank you.

**Comment by d2phap** [comment]
Hi @Rezzered 
Due to some limitation of Winform .NET, the performance is not as much as expectation.

I'm developing a completely new ImageGlass application recently. This may take time.

**Comment by Rezzered** [comment]
Thank you, and good luck !
