### ISSUE TITLE
Issues with rendering SVG wrapped text (draw.io)

### ISSUE THREAD

**Issue by drandarov-io** [d2phap/ImageGlass#1500]
### System information:
 - Windows OS version: Windows 11 Pro 22H2 (22623.1325)
 - ImageGlass version: 8.7.11.6

### To Reproduce
1. Create draw.io diagram with wrapped text (see attached svg at the bottom)
2. Open it in ImageGlass and compare to browser and Windows Explorer rendering

### Actual behavior:

The bug causes the Text to not be wrapped and therefore unreadable.

### Expected behavior:

The SVG should be rendered with wrapped text as in the browser or Draw.io

### Screenshots:

Comparison of draw.io, ImageGlass and the Edge Browser:
![image](https://user-images.githubusercontent.com/13102251/221526075-10f36a20-819c-4d7b-ad46-5da14047eb1d.png)

### Additional context:

The SVG file:
![Bug Demo drawio](https://user-images.githubusercontent.com/13102251/221525818-dfff7e4d-e1fa-4fc8-a602-a152dbab3b4a.svg)

**Comment by d2phap** [comment]
MagickNET has limit to render SVG format: https://github.com/dlemstra/Magick.NET/issues/1343#issuecomment-1417198804
> Magick.NET uses librsvg for svg rendering but this library is not as good as inkscape. My advice would be to install inkscape on your system. This will then be used when reading a svg file with Image Glass.

**Comment by drandarov-io** [comment]
Thanks for the info. That's unfortunate since I'd like to avoid installing additional tools. I assume it's unlikely for this situation to change in the near future. If that's the case and you can't do anything about it feel free to close the issue.
