### ISSUE TITLE
Couple of feature suggestions

### ISSUE THREAD

**Issue by ghost** [d2phap/ImageGlass#1501]
### Is your feature request related to a problem? Please describe.
No, it's not a bug or problem. Just a few feature suggestions.

### Describe the solution you'd like

1. Customizing more key controls would be a nice feature. For instance, F for full screen not F11. The F key is closer than F11 and more convenient to press.

2. When toggling full screen (F11) the toolbar should auto-hide for true full screen experience: no borders, no toolbars, no icons, just the image. Right now it looks like I have to press T to hide the toolbar and then press T again when going back to normal window. 

3. I'd like the ability to set Window Fit (F9) as permanent behavior so the window always resizes along with the image when I double-click the opened image or use keys to zoom the image in or out. Right now it seems to forget his.

I downloaded the latest beta to see if any of these are implemented but there are no settings in the GUI I can't figure out the settings file:( 

### Describe alternatives you've considered
N/A

### Additional context
None. Thank you! Cheers!

**Comment by tenauge** [comment]
+1

**Comment by Creaper1** [comment]
Add the ability to select multiple channels to view. I.E. R+B, R+G+B, R+A. Instead of a single channel only or all at once. Would like to be able to see R+G+B without Alpha or black.

**Comment by d2phap** [comment]
1) You can do it in v9.0 beta, open `igconfig.json`, under the `MenuHotkeys`, add:
```json
"MenuHotkeys": {
  "MnuFullScreen": ["F"],
}
```
You need to know the name of the menu to assign hotkeys, it starts with `Mnu`, see: https://github.com/d2phap/ImageGlass/blob/d71e92c18790454dd24aa3eca96942c824dcb461/v9/ImageGlass/FrmMain.Designer.cs#L1110-L1230

2) In v9.0 beta, in `igconfig.json`, set this to `true`:
```json
"HideToolbarInFullscreen": true,
```

In v8.7:
![image](https://user-images.githubusercontent.com/3154213/225208225-e3fd52fe-7772-4f04-88ce-903fc0c669d5.png)

3) In v8.7, the Window Fit mode is togglable, it's restored in the next launch.
V9.0 beta does not support Window Fit mode, but in the upcoming beta 4, just set:
`EnableWindowFit: "true"`
in `igconfig.json`


> Add the ability to select multiple channels to view. I.E. R+B, R+G+B, R+A. Instead of a single channel only or all at once. Would like to be able to see R+G+B without Alpha or black.

Already requested here #593
