### ISSUE TITLE
The program doesn't remember the thumbnail bar size when it's on the right side.

### ISSUE THREAD

**Issue by thericle** [d2phap/ImageGlass#1502]
### System information:
 - Windows OS version: Windows 11 Pro 22H2
 - ImageGlass version: 8.7.11.6

### To Reproduce
1. From Settings > Image > Thumbnail bar, check the "Show thumbnails on right side" option.
2. Open a picture.
3. Open the thumbnail bar (it appears very thin).
4. Resize the thumbnail bar.
5. Close the thumbnail bar (important)
6. Close the picture.
7. Open ImageGlass again.
8. Open the thumbnail bar, again.

### Actual behavior:
The thumbnail bar appears again with almost 0 width.

### Expected behavior:
I'd expect it to remember the size it had the last time.

I'm not really sure if this is considered a bug but I don't believe it's wanted behavior.

**Comment by thericle** [comment]
One correction/update. I noticed that if you open the EXE file of the program and then drag an image into it, it remembers the latest thumbnail bar size. The problem appears when you right-click on an image file and select "open with > ImageGlass".

**Comment by d2phap** [comment]
This issue is fixed in [ImageGlass 9.0 beta 5](https://github.com/d2phap/ImageGlass/releases/tag/9.0.5.726)
