### ISSUE TITLE
User-defined hotkeys mapping and file-copy behaviour

### ISSUE THREAD

**Issue by theMK2k** [d2phap/ImageGlass#1511]
### Is your feature request related to a problem? Please describe.

It would be great if:
- besides Cursor Left/Right the user can also use letters A/D (as in WASD, left handed) to browse the previous/next file
- copying files is done by Ctrl+C and image content by Shift+Ctrl+C (currently it is vice-versa)
- "open with" by pressing Enter (instead of "D")
- copying files does not stack the clipboard but rather clear the clipboard before the current file is copied

### Describe the solution you'd like

I think it would be great if the following can be user-defined in the settings:
- hotkey mapping
- file-copy behaviour (stacking the clipboard vs. single file)

### Describe alternatives you've considered

My current alternative is having forked ImageGlass and implement the hard-coded stuff in the way I personally like: https://github.com/theMK2k/ImageGlass/commits/mk2k

**Comment by d2phap** [comment]
Hi @theMK2k, FYI:

### Hotkey customization
It is implemented in v9.0 beta, you can open `igconfig.json`, use the `MenuHotkeys` setting:

```js
"MenuHotkeys": {
  <menu_name>: [<hotkey_list>],
}
```

Example:
```json
"MenuHotkeys": {
  "MnuViewNext": ["D", "RightArrow"],
  "MnuOpenWith": ["Enter"],
}
```

You need to know the name of the menu to assign hotkeys, it starts with `Mnu`, see: https://github.com/d2phap/ImageGlass/blob/d71e92c18790454dd24aa3eca96942c824dcb461/v9/ImageGlass/FrmMain.Designer.cs#L1110-L1230

### Copy/cut behaviour
It's also implemented in v9.0 beta. To change the default behaviour, open the `igconfig.json`:

```ts
"EnableCopyMultipleFiles": false,
"EnableCutMultipleFiles": false,
```
