### ISSUE TITLE
Can I display the image name at the bottom of the image

### ISSUE THREAD

**Issue by q762020457** [d2phap/ImageGlass#1512]
抱歉，英文不好，不知道翻译的对不对，中英文都写上了

可以在设置选项里面勾选：是否在图片底部显示图片名称；
1.名称在上面，图片在下面，不在同一视线内，看一眼上面，再看一眼下面，看时间长了就会累；
2.如果在图片底部显示图片名称，图文结合看，在同一视线内，批量浏览图速度会更快，更方便，更节省时间。

You can check whether to display the image name at the bottom of the image in the setting options;

"The name is above, the picture is below, and not in the same line of sight. Take a look at the top, and then take a look at the bottom. Looking at it for a long time can make you tired;";

"If the image name is displayed at the bottom of the image and viewed in combination with text, batch browsing of the image within the same line of sight will be faster, more convenient, and more time saving.".

**Comment by d2phap** [comment]
Showing file name in thumbnail bar is supported in v9.0 beta, see https://github.com/d2phap/ImageGlass/issues/539#issuecomment-1133560415
