### ISSUE TITLE
Zooming by hotkey in Window Fit mode does not work in 8.8

### ISSUE THREAD

**Issue by RVillaT** [d2phap/ImageGlass#1516]
### System information:
 - Windows OS version: 11
 - ImageGlass version: 8.8

### To Reproduce
1. Open image
2. Select "Scale to fit" in toolbar
3. Change zoom level (+ or -)

### Actual behavior:
Hello,

I'm not sure if it's a bug or if the change was intended (I hope not), but in version 8.8 the toolbar option "Scale to fit (5)" doesn't behave as it did in previous versions. The window no longer adapts automatically to the image when changing the zoom level. As far as I'm concerned, this was the feature that interested me the most in Imageglass. I manipulate a significant amount of images every day, and I don't see myself having fun adapting the window by hand each time I change the zoom. Is it the new intended behavior ? If it's intended then it's probably a deal breaker for me. 

Thank you.

### Expected behavior:
Window must adapt to the image when "Scale to fit" is selected and the zoom level is changed.

**Comment by d2phap** [comment]
Probably due to the fix of #1448. To clarify, that is "Window Fit" mode where the window adapts to the image size.
Just tested, it's still working when zooming with mouse wheel.

**Comment by RVillaT** [comment]
Indeed, it works correctly when zooming with the wheel. Is there a way to make it work also when using + or - ?

**Comment by d2phap** [comment]
I will update the release soon

**Comment by d2phap** [comment]
Updated, you can download again!

**Comment by RVillaT** [comment]
Thank you so much, it works !
