### ISSUE TITLE
[Issue] Prevented starting, installing, modifying or even uninstalling due to database error

### ISSUE THREAD

**Issue by LinguaOccultus** [d2phap/ImageGlass#1517]
Hello!

I am using ImageGlass for some time now on my desktop and installed it in my notebook now also. While working fine here aswell all the time, it suddenly stopped working. But I also cannot uninstall, (re-)install or modify it. The error always is:

![image](https://user-images.githubusercontent.com/90448229/227621566-0987c6b8-9b1b-401a-a778-01aa80a61d0c.png)

I tried to install the new version today on top of the old one to see if this is a known error solved with it maybe, but still the same.

How can this be solved?

Greetings,

Tim

**Comment by d2phap** [comment]
It seems that your Windows installer service has problem.
Can you try these solutions:
- https://qa.appnee.com/93/database-c-windows-installer-inprogressinstallinfo-ipi
- https://answers.microsoft.com/en-us/windows/forum/all/error-2203-database/78599a00-6887-4407-98e1-6a4655568b48
- https://www.ntfaq.ch/post/inprogressinstallinfoipi-Cannot-open-database-file-System-error-2147287037

If ImageGlass does not work correctly, you may delete the `igconfig.xml` file (usually located in `C:\Users\<user>\AppData\Roaming\ImageGlass`

**Comment by LinguaOccultus** [comment]
You are right; I became aware later that this is affecting all installations and such and is a Windows Installer problem. Since I already tried the usual stuff, I guess I will have to reinstall Windows. Since not related to ImageGlass, I am closing this thread.
