### ISSUE TITLE
Use the drag&drop of images from image viewer to another application

### ISSUE THREAD

**Issue by d2phap** [d2phap/ImageGlass#152]
From MontyX

Hello,

I like to use the application, because this is lightweight and fast.
I would like to request a new feature, if possible:
In many cases like as chat apps, gmail in browser, I can use the drag&drop of images from image viewer to the chat.
E.g. when I create a screen capture, open it with the image viewer, I can drag the image and drop in the chat window.

If this is possible, please look after it, because this is the only tool, that I'm missing from your app.

Thanks a lot in advance,
MontyX

**Comment by d2phap** [comment]
Added!

**Comment by gerroon** [comment]
> Added!

Is this supported in the current version? I cant seem to be able to dd into anything.

**Comment by d2phap** [comment]
You can hold Ctrl and drag
