### ISSUE TITLE
Lag and error before showing exif data

### ISSUE THREAD

**Issue by luci9t** [d2phap/ImageGlass#1520]
### System information:
 - Windows OS version: Windows 11, version 22H2
 - ImageGlass version: ImageGlass_Kobe_8.8.3.28_x64 (the latest version as of March 27, 2023)

### To Reproduce
1. Configure exiftool (put exiftool.exe path in Imageglass settings)
2. Open a PNG file
3. Open exiftool for image (press x)
4. The error message is shown before showing the exif data

### Actual behavior:

You press X and it first throws this error of "the exif file does not exist (even when it is configured properly), for a second, before showing the exif data. The error looks like:
![image](https://user-images.githubusercontent.com/84169312/227857959-c02502f6-cbe3-4494-afe0-45b9651114d1.png)

### Expected behavior:

Before this version, it worked properly, you press "X" and it showed the exif data straight away, with no lag whatsoever, no error message either. 

### Additional context:

I'd just use the last version, but the title bar color apparently doesn't turn dark when the app is pending an update.

**Comment by d2phap** [comment]
It should be fixed in [v8.8.4.4](https://github.com/d2phap/ImageGlass/releases/tag/8.8.4.4).

**Comment by luci9t** [comment]
yes it works fine now, thanks for you work!
