### ISSUE TITLE
Save dialog box?

### ISSUE THREAD

**Issue by Andy76swe** [d2phap/ImageGlass#1524]
### System information:
 - Windows OS version: 
 - ImageGlass version: 8.8.3.28 x64

### To Reproduce
1. edit image
2. press Save
3. dialog box shows up asking for location and name when it should just save to original image
4.

**Comment by d2phap** [comment]
Hi @Andy76swe 

In v8.8, the saving behaviour is changed as described here: https://github.com/d2phap/ImageGlass/releases/tag/8.8.3.28, so it only auto-saves the supported formats. This is to avoid the unsupported image not being corrupted.

> Image saving has been updated to only work with supported formats listed in the "Write" column of [the supported formats](https://imageglass.org/docs/supported-formats) page (https://github.com/d2phap/ImageGlass/issues/1504):
> - If the user attempts to save an unsupported format, the "Save as..." dialog will be opened instead.
> - This change also affects other image saving-related features such as rotation, flipping, and cropping.

Saving feature in ImageGlass has never been enough tested. So it's better to disable it.
In the future, I will add support for more formats for saving.
