### ISSUE TITLE
Unhandled Exception error

### ISSUE THREAD

**Issue by hujan86** [d2phap/ImageGlass#1525]
### System information:
 - Windows OS version: Windows 10 Version 22H2 (Build 1904.2604)
 - ImageGlass version: 8.8.3.28

### To Reproduce
1. Upgrade to the latest version via x64 MSI installer from v8.7
2. After installation is done, start the app and the exception error will appear.

### Actual behavior:
Exception error will persistently occur when reopening the app. 

### Expected behavior:
Display home screen at start up or display image when opening an image.

### Screenshots:
![Untitled](https://user-images.githubusercontent.com/30305320/228696354-1a336218-d9dc-4603-8e2f-947e50cf2548.png)

### Additional context:
Details of the error message:
[error.log](https://github.com/d2phap/ImageGlass/files/11106567/error.log)

**Comment by d2phap** [comment]
This which can occur when there is an old version of a DLL still lingering somewhere around. Not sure why it happens, probably the installer does not do its work correctly.

You can fix this by using "Prepare" button of the MSI in the "Programs and Features"

![image](https://user-images.githubusercontent.com/3154213/228707781-6d1d16b8-2c33-470c-97cc-ffede040d5a3.png)

**Comment by hujan86** [comment]
> This which can occur when there is an old version of a DLL still lingering somewhere around. Not sure why it happens, probably the installer does not do its work correctly.
> 
> You can fix this by using "Prepare" button of the MSI in the "Programs and Features"
> 
> ![image](https://user-images.githubusercontent.com/3154213/228707781-6d1d16b8-2c33-470c-97cc-ffede040d5a3.png)

Repair option in the installer confirmed fixed the bug. Thanks.
