### ISSUE TITLE
Sceenshots on download screen for 8.8.3.28 are loaded twise. (on Firefox)

### ISSUE THREAD

**Issue by Lucksinia** [d2phap/ImageGlass#1528]
### System information:
 - OS version: Windows 11 Pro, Ubuntu 20.04
 - ImageGlass version: not relevant, but 8.8.3.28

### To Reproduce
1. Go to https://imageglass.org/release/imageglass-8-8-3-28-40#downloads
2. Scroll to the Screenshots tab on page.
3. click on it

### Actual behavior:
When opening image it loads, stutters, unloads and then loads again

### Expected behavior:
When opening image it loads, and that's all.

### Additional context:
I think that's some weird firefox behavior, but i don't know enough about web engines to help. or maybe it's not only firefox specific. Needs further testing.

**Comment by d2phap** [comment]
Thanks @Lucksinia 
I will close because it's not related to the software itself though.
