### ISSUE TITLE
The exiftool window layout is broken

### ISSUE THREAD

**Issue by TheWAVs** [d2phap/ImageGlass#1532]
### System information:
 - Windows OS version:  Windows 10 21H1 (19043)
 - ImageGlass version: ImageGlass_Kobe_8.8.4.4_x64

### To Reproduce
1.  Open any image
2.  Open exiftool for image exif data (press x)
3.  The exiftool window will look screw** up

### Actual behavior:
If you press X  once an image is opened, the exiftool window won't display correctly.

### Expected behavior:
Before the last two versions, the exiftool window worked well, showing the correct exif data immediately.

### Screenshots:
![ImageGlass_PpWzMXVhHy](https://user-images.githubusercontent.com/10777531/229790394-32c18c81-a764-4ae3-8e12-987f74bfd19f.png)

### Additional context:
This only version works fine for me: ImageGlass Kobe 8.7.11.6 - Hotfix

**Comment by d2phap** [comment]
Hmm I cannot reproduce. Can you attach a video?

THe Exiftool should look like this:
![image](https://user-images.githubusercontent.com/3154213/229806070-12e61a9b-8ef8-4f71-a6b3-351bf835f57b.png)

**Comment by TheWAVs** [comment]
> Hmm I cannot reproduce. Can you attach a video?
> 
> THe Exiftool should look like this: ![image](https://user-images.githubusercontent.com/3154213/229806070-12e61a9b-8ef8-4f71-a6b3-351bf835f57b.png)

Of course,  this is what happens...

https://i.imgur.com/yyU57Xz.mp4

**Comment by d2phap** [comment]
Thanks @TheWAVs 
- Can I check with you your screen DPI scaling? You can see how to check here: https://www.top-password.com/blog/change-dpi-scaling-settings-in-windows-10/
- Can you try using Repair button from the MSI installer?
![image](https://user-images.githubusercontent.com/3154213/229812683-429dff0e-c3e6-4f54-97ae-8dda22601ec2.png)
or in Program and features:
![image](https://user-images.githubusercontent.com/3154213/229813272-00fcf312-144e-4abe-8a36-2c4596bfe161.png)

**Comment by TheWAVs** [comment]
> Thanks @TheWAVs
> 
> * Can I check with you your screen DPI scaling? You can see how to check here: https://www.top-password.com/blog/change-dpi-scaling-settings-in-windows-10/
> * Can you try using Repair button from the MSI installer?
>   ![image](https://user-images.githubusercontent.com/3154213/229812683-429dff0e-c3e6-4f54-97ae-8dda22601ec2.png)
>   or in Program and features:
>   ![image](https://user-images.githubusercontent.com/3154213/229813272-00fcf312-144e-4abe-8a36-2c4596bfe161.png)

> * Can I check with you your screen DPI scaling? 
![ApplicationFrameHost_rv5NDZOU0s](https://user-images.githubusercontent.com/10777531/229815671-72cc50de-5b89-4437-87ba-23d075854730.png)


> * Can you try using Repair button from the MSI installer?
I already tried.

**Comment by h-347** [comment]
Still same bug. (My screen resolution is 1366x768 too.)

**Comment by ScienceZone** [comment]
I had the same problem about a year ago, this error is unbearable, so I have been using ImgeGlass only as a spare tire for other picture viewing software, but I have been paying attention to its development, recently downloaded V8.10, still have the same problem, looking through the "Issues" found the same problem, it was verified that this problem was briefly solved in V8.7, but it appeared again in later versions, is it ImgeGlass later Going downhill, the problem arises again! The developer's head is puzzling! Sometimes I really want to beat them up when I'm cranky, haha...

**Comment by d2phap** [comment]
User should switch to [ExifGlass](https://imageglass.org/tools) to work with ImageGlass 9
