### ISSUE TITLE
Reopen recently closed images

### ISSUE THREAD

**Issue by ghost** [d2phap/ImageGlass#1534]
### Is your feature request related to a problem? Please describe.
No way of reopening recently closed images after Windows crashes or I manually restart

### Describe the solution you'd like
Reopen recently closed images

### Describe alternatives you've considered
Bookmark and history list

**Comment by d2phap** [comment]
You can enable this setting to re-open the last seen image.
![image](https://user-images.githubusercontent.com/3154213/232207190-663fb2b9-3934-48f2-80bf-55d3a5cbce9f.png)

But if when your system is crashed, ImageGlass will still be unable to save the setting.

For bookmark, it's been requested here: #141

**Comment by ghost** [comment]
It only opens the last seen image
