### ISSUE TITLE
Zooming past 100% and double clicking to fit breaks image scaling

### ISSUE THREAD

**Issue by Comitant** [d2phap/ImageGlass#1535]
### System information:
 - Windows OS version: Windows 10 22H2
 - ImageGlass version: 8.8.4.4

### To Reproduce
1. Zoom past 100% on any image that is larger than monitor resolution
2. Double click to fit window
3. Image will now be using nearest filter to downscale

### Actual behavior:

When zooming further than full-size resolution of an image and then double clicking to fit window, ImageGlass will use nearest scaling to downscale. Zooming back by scrolling does not cause this to happen, nor does pressing the scale to fit hotkey.

It does not have any affect on images smaller than monitor resolution, since it only affects downscaling.

This problem appeared during 8.8.3.28 and remains in the latest update.

### Expected behavior:

Imageglass should use normal downscale filter

**Comment by Comitant** [comment]
Any update on this?

**Comment by d2phap** [comment]
Duplicated of #1549. I suggest you to use v8.7 or 9.0 beta 4 while waiting for next update
