### ISSUE TITLE
Suggestion: Improve the image navigation more

### ISSUE THREAD

**Issue by binhnguyenvo** [d2phap/ImageGlass#154]
It's easy to realize the significant delay during the navigation of images (backward and forward). Although I've used a PC equipped with good CPU and RAM, but it still has a lag/delay between image switching. You can try the ACDSee Quick View to see its surprising speed in this case. 
Please improve this point as it is daily and frequently used feature/operation.
Thank you so much.

**Comment by d2phap** [comment]
Changed to use new lib to speed up loading speed
