### ISSUE TITLE
Add support for automatically adjusting window size when opening image from clipboard

### ISSUE THREAD

**Issue by VM8gkAs** [d2phap/ImageGlass#1540]
### Is your feature request related to a problem? Please describe.
Just a feature request.

### Describe the solution you'd like
When "Auto zoom" and "Window fit" are enabled, each time an image is opened from the clipboard, it automatically zooms to 100% and adjusts the window size to match the image size.
Currently, this function requires manually pressing F9 twice to achieve. (Version 8.8.4.4)

### Describe alternatives you've considered
None.

### Additional context
1. Original
![ImageGlass_eQxFHe7Yv9](https://user-images.githubusercontent.com/61822684/231926451-cf4df20b-8c17-4067-9c5c-0a6cbdbce15c.png)
2. Paste screenshot (image size smaller than window size)
![ImageGlass_eClBy4dNNp](https://user-images.githubusercontent.com/61822684/231926473-949aeaca-e46e-48ee-803d-c4bc5fec74dc.png)
3. Paste screenshot (image size larger than window size)
![ImageGlass_xhec6iKlZK](https://user-images.githubusercontent.com/61822684/231926481-7bf06281-b3c6-4265-9b78-18e75efd11ec.png)

**Comment by d2phap** [comment]
This issue is fixed with the new Window Fit mode in v9.0 beta 4
