### ISSUE TITLE
Window title bar

### ISSUE THREAD

**Issue by xmha97** [d2phap/ImageGlass#1544]
Please allow editing of the title bar text (like Telegram)

![image](https://user-images.githubusercontent.com/23485114/232206283-39f82f3b-4c01-4537-a931-556db5aa3985.png)

I need a string in the option, like this:

```json
{
"windowTitlebar": "ImageGlass - $imageWidth x $imageHeight"
}
```

**Comment by d2phap** [comment]
It has been supported since v9.0 beta 1, see the setting: https://github.com/d2phap/ImageGlass/issues/971#issuecomment-1133560019

**Comment by xmha97** [comment]
> It has been supported since v9.0 beta 1, see the setting: [#971 (comment)](https://github.com/d2phap/ImageGlass/issues/971#issuecomment-1133560019)

Thanks, you can close this issue.
