### ISSUE TITLE
[Frameless mode] Can't resize the window

### ISSUE THREAD

**Issue by xmha97** [d2phap/ImageGlass#1545]
Hi, I can't resize the window on frameless mode.

# Frame Mode
![image](https://user-images.githubusercontent.com/23485114/232208468-8d1c2e36-91e9-4c93-a650-1e4a71e0fbf1.png)

# Frameless Mode
![image](https://user-images.githubusercontent.com/23485114/232208474-18085d6f-9717-41c0-8b78-18ad85885d86.png)

### System information:
 - Windows OS version: 11
 - ImageGlass version: 9.0.4

**Comment by d2phap** [comment]
Duplicated of #1330. Borderless form of WinForms does not support resizing.
