### ISSUE TITLE
Support Minimize and Maximize items on toolbar

### ISSUE THREAD

**Issue by xmha97** [d2phap/ImageGlass#1546]
Please support the toolbar's `minimize` and `maximize` items on ImageGlass v9.0.5:

![image](https://user-images.githubusercontent.com/23485114/232209039-753baa12-c3ed-4618-b610-e0f0dab6cdd8.png)

![image](https://user-images.githubusercontent.com/23485114/232209044-c36be08b-7f61-4516-beca-f4c3193a4666.png)

**Comment by d2phap** [comment]
You can use this:
- Executable: `IG_SetFrmMainState`
- Argument: `Maximized`, or `Minimized`, or `Normal`

Note that the `IG_SetFrmMainState` will be changed to `IG_SetWindowState` in the next release.

**Comment by xmha97** [comment]
Thanks, it working.
Please also add an Executable for Maximize/Restore.

**Comment by d2phap** [comment]
You can use that method to change 3 states of the window, just replace the argument accordingly.
- Argument for "Restore" is `Normal`
