### ISSUE TITLE
Image Transition fade reappearing

### ISSUE THREAD

**Issue by MaresSen** [d2phap/ImageGlass#1548]
### System information:
 - Windows OS version: Windows10 22H2 (19045)
 - ImageGlass version: Moon_9.0.4.416_Beta-4_x64_net7

### To Reproduce
1. Set "EnableImageTransition" to false
2. Open any image from a gallery, size doesn't matter
3. Switch to another image
4. Then switch again to another image

### Actual behavior:
**First image**
_- no transition fade -_
**Second image**
_- transition fade -_
**Every subsequent image**
_- transition fade -_

Deactivating Image Transition fade only works for the first image transition - no matter the size.

### Expected behavior:
**First image**
_- no transition fade -_
**Second image**
_- no transition fade -_
**Every subsequent image**
_- no transition fade -_

Transition fade shouldn't reappear.

### Additional context:
Image size doesn't matter, ImageBooster settings also don't matter. Beta 3 doesn't share that behaviour. Annoying when trying to compare multiple similar images.

**Comment by d2phap** [comment]
@MaresSen could you attach a video? I have `EnableImageTransition=false` and there is not fading transition appears.
