### ISSUE TITLE
ImageGlass always opens using nearest-neighbor zoom

### ISSUE THREAD

**Issue by CodeMarc11** [d2phap/ImageGlass#1549]
When ImageGlass is set to "Scale to fit", launching it to open an image will always start with zoom using nearest-neighbor. Small images will be pixelated. Zoom method used will correct itself when zoom factor is manually changed.

System info:
Windows 10 Home 64-bit
ImageGlass 8.8.4.4, but saw this earlier in 8.8.3.x

To reproduce:
1. In ImageGlass, go to Settings: Image, Zoom optimization and choose "High quality".
2. Set ImageGlass to "Scale to fit" and make its window large. Close ImageGlass.
3. Go to a small image in File Explorer, e.g. 1/4 the size of IG window. (I attached a simple example.)
4. Double-click image. Note that image is noticeably pixelated in ImageGlass - it is using nearest-neighbor zoom, despite being set to high quality.
5. Left/right arrow to open other small images in same folder. They will also appear pixelated.
6. Manually (+) to zoom in, then (-) to zoom back out. Note that image is now smoother.

Actual behavior:
ImageGlass always starts with nearest-neighbor zoom. If an image is zoomed when IG opens, like with Scale to fit for a small image, it will be pixelated. Navigating to previous/next image continues to use nearest-neighbor until zoom is manually changed, then it corrects to proper zoom method.

Expected behavior:
ImageGlass should open images using current Zoom optimization setting.
![Low res](https://user-images.githubusercontent.com/38742926/232277551-76efeb1f-8d9b-4c85-836e-1ff234e9840b.png)

**Comment by d2phap** [comment]
Confirmed the bug. V9.0 beta works correctly.

**Comment by ly-pa** [comment]
I had the same issue, for those who do not want to use the beta yet going back to 8.7.11.6 for now is an option as it does not have this issue.

**Comment by d2phap** [comment]
This issue is fixed in v8.9
