### ISSUE TITLE
Cannot open the Settings menu with 9.0 beta 4

### ISSUE THREAD

**Issue by PoloniumRain** [d2phap/ImageGlass#1550]
### System information:
 - Windows OS version: Windows 10 64-bit
 - ImageGlass version: 9.0 beta 4 (.NET 7)

### To Reproduce
1. Open IG
2. Go to Main Menu
2. Click on Settings

### Actual behavior:

This appears instead of the Settings menu: 
![error](https://user-images.githubusercontent.com/50634894/232337657-6475ffb2-6838-4ca3-96f5-de7299c00882.jpg)

I'm not sure if this is even a bug, because this has always happened with every Beta release of ImageGlass, including releases from years ago. The `igconfig.json` file is inside the ImageGlass folder as well. Final releases never have this problem, only beta.

So i'm assuming that there's something i'm meant to do to make the Settings menu work? I already have both .NET Desktop Runtime 7.0.5 and WebView2 version 110 installed. The same thing happens on both Windows 10 and 11.

BTW excellent work @d2phap :)

**Comment by d2phap** [comment]
V9 is being developed from scratch, it just does not support GUI for settings.
Next release will come with Settings GUI!

**Comment by PoloniumRain** [comment]
Oh right lol, well i'll close this issue then!
