### ISSUE TITLE
ImageGlass 9.0 ignores HEIC orientation

### ISSUE THREAD

**Issue by alexantr** [d2phap/ImageGlass#1551]
### System information:
 - Windows OS version: 10 22H2
 - ImageGlass version: 9.0.4.416 Beta-4 x64 net7

### Actual behavior:
All images display in landscape orientation

### Expected behavior:
Image should be oriented to correct orientation

<details>
<summary>Screenshots</summary>
  
ImageGlass 8.8.4.4 with correct orientation:

![ImageGlass_2023-04-17_22-03-14](https://user-images.githubusercontent.com/4941848/232586415-2156a30c-776c-4a53-aa8a-05ac57630cd4.jpg)
![ImageGlass_2023-04-17_22-01-34](https://user-images.githubusercontent.com/4941848/232586429-e1198922-a65f-4d5e-81f9-8bc1e8ae0533.jpg)

ImageGlass 9.0.4.416 with no orientation:

![ImageGlass_2023-04-17_22-02-37](https://user-images.githubusercontent.com/4941848/232586591-b8bdcaca-3547-4f5a-8992-49e025602ece.jpg)
![ImageGlass_2023-04-17_22-02-14](https://user-images.githubusercontent.com/4941848/232586617-d2763968-0252-4bc7-ba32-2fe1df302639.jpg)

</details>

[imageglass_test_heic.zip](https://github.com/d2phap/ImageGlass/files/11254855/imageglass_test_heic.zip) contains 4 example photos with rotation 0°, -90°, -180° and -270°

**Comment by d2phap** [comment]
This issue is fixed in [ImageGlass 9.0 beta 5](https://github.com/d2phap/ImageGlass/releases/tag/9.0.5.726)
