### ISSUE TITLE
Menu as a toolbar item

### ISSUE THREAD

**Issue by xmha97** [d2phap/ImageGlass#1555]
Hi, I want to move the menu button on the toolbar to the center. (like Windows 11 Photos app)

![image](https://user-images.githubusercontent.com/23485114/233621219-747c9e10-e1a6-4689-8fc5-2e2f5c6e1919.png)

But I can't find the menu item on the igconfig.json
I need this:
```
  "ToolbarItems": [
    {
      "Type": "Button",
      "Id": "Btn_Menu",
      "Text": "",
      "DisplayStyle": "Image",
      "CheckableConfigBinding": "",
      "Alignment": "Right",
      "Image": "Menu",
      "OnClick": {
        "Executable": "MnuShowMenu",
        "Argument": ""
      }
    },
```

**Comment by d2phap** [comment]
You can use `IG_OpenMainMenu` for the `Executable` to open the main menu.

**Comment by xmha97** [comment]
I want to move the hide menu button
Or change the position of the menu button.
Now I can't do it.

**Comment by xmha97** [comment]
I want to move the hide menu button
Or change the position of the menu button.
Now I can't do it. @d2phap

**Comment by d2phap** [comment]
Main menu button is fixed to the right side. Changing its position requires updating all buttons alignment as well. So I will not implement it.
