### ISSUE TITLE
Thumbnails in explorer not showing?

### ISSUE THREAD

**Issue by individuell** [d2phap/ImageGlass#156]
I would like to see a preview / thumbnail of the picture itself instead of the imagesGlass logo. Couldn't find a single result searching for this - is it just me or what can I do to enable this?

![thumbnailsexporernotshwoiung](https://cloud.githubusercontent.com/assets/5064362/23048673/b94f0846-f4b7-11e6-933b-e875d96f0f27.png)

**Comment by individuell** [comment]
SOLUTION:

ahh - as I submitted this issue I found out about this - it's not ImageGlass related! Windows option:

![thumbnailsexporernotshwoiung2](https://cloud.githubusercontent.com/assets/5064362/23048766/56f930f8-f4b8-11e6-8df8-9d55d4d717af.png)

**Comment by d2phap** [comment]
:)
