### ISSUE TITLE
Save option while cropping images open "save as" box

### ISSUE THREAD

**Issue by maniac5670** [d2phap/ImageGlass#1560]
### System information:
 - Windows OS version: Windows 10 22H2
 - ImageGlass version: 8.8

### Actual behavior:
when choosing option "save" while cropping images, it opens "save as" box

### Expected behavior:
when choosing option "save" while cropping images, it should directly save the cropped image to the original folder replacing the original one.

**Comment by d2phap** [comment]
Please see https://github.com/d2phap/ImageGlass/issues/1524#issuecomment-1488674088
