### ISSUE TITLE
Similar to Windows Photo

### ISSUE THREAD

**Issue by nobef** [d2phap/ImageGlass#1561]
I would like to suggest the logic of programs like Windows Photo. To set library folders (eg E:Images) and have everything shown in a grid. Why don't desktop apps follow this model, at least as an option? Isn't it more convenient than opening the last photo or opening the location manually? Well here's an example:
 
![изображение](https://user-images.githubusercontent.com/77186394/234104203-8775e9f1-0208-4a1a-ba57-370f58f12a69.png)

**Comment by d2phap** [comment]
Please refer to https://github.com/d2phap/ImageGlass/issues/1629#issuecomment-1666695156
