### ISSUE TITLE
[9.0] Make possible to configure custom zoom levels

### ISSUE THREAD

**Issue by slavoyar8601** [d2phap/ImageGlass#1563]
### Describe the solution you'd like

Make possible to configure custom zoom levels like in previos versions of IG

### Additional context

I's like to have an option to set custom zoom levels like 10%, 20%, 50%, 75%, etc. in IG 9.0

**Comment by d2phap** [comment]
Implemented in [ImageGlass 9.0 beta 5](https://github.com/d2phap/ImageGlass/releases/tag/9.0.5.726).
You can define the zoom levels in Settings > Viewer > Zooming. The numbers must be separated by `;`

![image](https://github.com/d2phap/ImageGlass/assets/3154213/cfa63dfb-83cc-46ec-9673-40d57bbc3318)
