### ISSUE TITLE
Thumbnails are not  refreshed.

### ISSUE THREAD

**Issue by JBanneck** [d2phap/ImageGlass#1564]
Thumbnails are not refreshed. They are for newly cropped photos but older ones are not. I checked, the older ones have been updated in Windows.

Not a big deal. Please fix it when convenient. 

Thank you. Great Application!

**Comment by d2phap** [comment]
Should be fixed in [ImageGlass 9.1 Beta](https://github.com/d2phap/ImageGlass/releases/tag/9.0.11.529)
