### ISSUE TITLE
Newly opened images do not have zoom optimization applied

### ISSUE THREAD

**Issue by Gabyalufix** [d2phap/ImageGlass#1565]
### System information:
 - Windows OS version: Windows 10, 64 bit
 - ImageGlass version: 8.8.3.28 x64

### To Reproduce
1. Set zoom optimization to "high-quality bicubic". Set zoom level to "scale-to-fit".
2. Maximize the imageglass window.
3. Close imageglass
5. Open a new LOW-RESOLUTION image. It must have lower resolution than your monitor. Note that the image is displayed with aliasing and pixelization artifacts
6. Change the zoom settings (zoom in, and back out, or switch between scale-to-fit and scale-to-fill and back, etc). The image will no longer have aliasing and pixelization artifacts.

### Actual behavior:
When opening a new image, it appears that the zoom optimization is not being applied until you change the zoom, despite the fact that the newly opened image is automatically zoomed to fit.

### Expected behavior:
When opening a new image the zoom optimization should be applied

### Screenshots:

Images before and after I zoom in and out:
![zoom example 1A](https://user-images.githubusercontent.com/22138139/235676211-8e6aa3fd-6220-47f8-afe9-89c58718bc49.PNG)
![zoom example 1B](https://user-images.githubusercontent.com/22138139/235676212-e274730b-b0e8-49cf-a45a-fcf3e0e45bca.PNG)

**Comment by d2phap** [comment]
Duplicated of #1549
