### ISSUE TITLE
[9.0 beta 4] Animated png won't open

### ISSUE THREAD

**Issue by RAZUMNO** [d2phap/ImageGlass#1567]
- ImageGlass version:  9.0 beta 4 .net 7.0

So, firstly the need for the right format is already painful, because most of the times programs and browsers saves that as .png extension. And manually changing it every time is painful and exhausting. XnViewMp doesn't have such a problem, it's just open it and everything works fine. And your program have specific requirement that extension must be .apng.

And now the bug itself. Program can't open that .apng format. I have that error message
![image](https://user-images.githubusercontent.com/10924780/236192455-2253eaef-b7fc-4a33-95fe-0fc3c22c338b.png)
All I did is manually changing .png to .apng. XnViewMp still can open that .apng file

**Comment by d2phap** [comment]
IG uses MagickNET (ImageMagick) to read and decode APNG format:
- You need to download [`ffmpeg`](https://ffmpeg.org/download.html) and put the `ffmpeg.exe` in the installed folder of ImageGlass, or add it into `PATH` variable.
- MagickNET requires the extension to be `.APNG`
