### ISSUE TITLE
Photo viewing on network locations slow

### ISSUE THREAD

**Issue by ghost** [d2phap/ImageGlass#1568]
### System information:
 - Windows OS version: 10 22h2
 - ImageGlass version: 
![image](https://user-images.githubusercontent.com/122007087/236595227-d468250b-2274-4bad-ba4e-0df92c35059a.png)

I have network folders with photos in them.
I open any photo inside that folder.
Program opens up and I can switch between all the photos in that folder within the program without issues.
The problem is the delay when switching photos (assuming because of delay due to network location).

My question is how can I avoid this?
Is there a way to force ImageGlass so that when I open a single photo, ALL photos in that folder are "cached" in a way to allow for quick transitions?

Moving these photos on my desktop works 100% right - 0 delay when switching photos. Problem is network locations, and I cannot find a way around this. Please help me out.

Thank you

**Comment by d2phap** [comment]
Hi @Rezy942 
Usually, accessing files from the network is much slower than the hard disk.
Can you try v9.0 beta 4 if it's improved?

**Comment by ghost** [comment]
Thank you for responding about this issue!
I tried the beta and it works wonderfully! Now the behavior is to load the next imagine in line INSTANTLY, but it might be at lower resolution, so it will take 1-2 sec to load fully. Which i believe is microsoft photos behavior. This is what I wanted. (much easier to scroll through multiple photos quickly to find the one u need)

I believe the issue was with imageglass forcing each image to be at max resolution right away, causing the delay.
Again, thank you. When can we expect 9.0 beta release? :)

**Comment by d2phap** [comment]
v9.0 beta 5 will probably be released in 2 months. It's also the last beta release. It's going to take another 3 months for the official v9.0 release.

**Comment by ghost** [comment]
I see. I will just use the beta version from now on then, and keep an eye out for official release :)

**Comment by d2phap** [comment]
Okay, So I will close this issue
