### ISSUE TITLE
Uninstaller leaves a lot of junk behind 

### ISSUE THREAD

**Issue by soumyasatpathy** [d2phap/ImageGlass#1569]
### System information:
 - Windows OS version: 10.0.22621.1702
 - ImageGlass version:  ImageGlass_Kobe_8.8.4.4_x64

### To Reproduce
1. Install imageglass, setting it as default image viewer, associated to all extensions
2. Using Windows 'Default Apps' set IG as the default viewer
3. Use IG
4. Uninstall imageglass, reboot

### Actual behavior:
The ImageGlass uninstall has left a number of Registry entries still in place. This manifests to the user by selecting an image file in explorer, right-click, select "open with", then "choose another app". Image Glass is listed as a choice. Another thing is it renames all images files types as "ImageGlass.AssocFile.JPG". This is so annoying. 

### Expected behavior:
ImageGlass needs to remove all registry entries and clean its traces in the system.

### Screenshots:
![3fr](https://github.com/d2phap/ImageGlass/assets/85225715/106189df-2468-424f-be22-42c256a3d8a8)

![ari](https://github.com/d2phap/ImageGlass/assets/85225715/97aa916e-9cff-4bea-acfc-4c76deaafd16)

**Comment by d2phap** [comment]
The installer is independent and separate from the app, created by Advanced Installer Express version (free). There are some limits that you need to manually undo the below settings if you enable it:
- Set as default photo viewer (click Unregister extensions button in Settings > File type associations)
- Start with Windows to improve startup time (uncheck the checkbox, and save)

Alternatively, you can purchase IG Store version which has seamless update/install process.

**Comment by dahamsta** [comment]
FYI I switched to the store version and it also left all the file associations in place.

**Comment by bananalemonmelon** [comment]
> The installer is independent and separate from the app, created by Advanced Installer Express version (free). There are some limits that you need to manually undo the below settings if you enable it:
> 
> * Set as default photo viewer (click Unregister extensions button in Settings > File type associations)
> * Start with Windows to improve startup time (uncheck the checkbox, and save)
> 
> Alternatively, you can purchase IG Store version which has seamless update/install process.

I tried both, but ImageGlass is still displayed on the top of "open with" menu.

It seems like there is something else that need to be removed from the registry.

<img width="576" height="718" alt="Image" src="https://github.com/user-attachments/assets/dead7c81-89b5-4fd5-bc96-dd9df039ec92" />

**Comment by Luxuslaerm** [comment]
> > The installer is independent and separate from the app, created by Advanced Installer Express version (free). There are some limits that you need to manually undo the below settings if you enable it:
> > 
> > * Set as default photo viewer (click Unregister extensions button in Settings > File type associations)
> > * Start with Windows to improve startup time (uncheck the checkbox, and save)
> > 
> > Alternatively, you can purchase IG Store version which has seamless update/install process.
> 
> I tried both, but ImageGlass is still displayed on the top of "open with" menu.
> 
> It seems like there is something else that need to be removed from the registry.
> 
> <img alt="Image" width="576" height="718" src="https://private-user-images.githubusercontent.com/576529/500370141-dead7c81-89b5-4fd5-bc96-dd9df039ec92.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Njc1MTE2NDksIm5iZiI6MTc2NzUxMTM0OSwicGF0aCI6Ii81NzY1MjkvNTAwMzcwMTQxLWRlYWQ3YzgxLTg5YjUtNGZkNS1iYzk2LWRkOWRmMDM5ZWM5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDEwNFQwNzIyMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MzY1YTU2NDNkMGNhMDEyMzQzNjI1N2Q0MTNjZDI0NmI1MDdlMTJjOWIyZDFiOWI1YjZlYmZkOGQ3Nzg4YzA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tW5HlXGQbg84E8tDGsFAshcUa9wjHuzQOAj8HOWiXvI">

Open regedit and delete `HKEY_CURRENT_USER\Software\ImageGlass`
