### ISSUE TITLE
Paper shows blank when printing image.

### ISSUE THREAD

**Issue by aldeniangman** [d2phap/ImageGlass#1570]
Hello! I've been having a bit of trouble when trying to print an image with ImageGlass. Unfortunately, the paper comes out completely blank. It would be so helpful if this issue could be addressed in the future. Thank you kindly.

**Comment by d2phap** [comment]
Hi @aldeniangman 

ImageGlass uses the built-in "Print Pictures" dialog of Windows for printing.

Could you provide more information:
- the image file extension (e.g. PNG file)
- the image dimension (e.g. 4000x4000 pixels)
- ImageGlass version
- Your Windows version
- What happened when you click on Print menu in ImageGlass?

**Comment by donniebnyc** [comment]
Same problem.

PNG
921 x 89
IG Version: 9.1.8.723 (64-bit)
Win 11 Pro, 23H2

I get the print dialog box but the preview image is incomplete or missing some parts.  Prints incorrectly. 

Thanks.
