### ISSUE TITLE
Drag & drop image from IG to anywhere

### ISSUE THREAD

**Issue by LLKoder** [d2phap/ImageGlass#1574]
It would be nice if the app have this feature.

I mean to drag & drop as main picture...
![2023-05-22_19-16](https://github.com/d2phap/ImageGlass/assets/50442676/13f0aae7-baf9-4a9c-9ff6-25defce61911)

...as small shots.
![2023-05-22_19-17](https://github.com/d2phap/ImageGlass/assets/50442676/9be973ce-a740-4a80-9343-53a7b7549cc9)

**Comment by d2phap** [comment]
Hi @LLKoder,
In v8, you can hold SHIFT button and drag the viewing image to anywhere.
In v9.0 beta 4, you can just drag the thumbnail.
