### ISSUE TITLE
DNG Grayscale file not supported. (only single color channel?) [error/dng.c/ReadDNGImage/572]

### ISSUE THREAD

**Issue by ClenonWolf** [d2phap/ImageGlass#1575]
### System information:
 - Windows OS version: 10 22H2 19045.2865
 - ImageGlass version: 8.8.4.4 x64

### To Reproduce
1. (Scan file in vuescan using: Make Gray from: Auto)
2. Open DNG file (In my case scanned image from vuescan. Please read "Additional context")

### Actual behavior:
I've scanned images in auto grayscale in the raw DNG format (seemingly only giving one color channel) and when I try to open it in ImageGlass it gives this Error:
Magick.NET-Q16-HDRI-OpenMP-x64: No error '...' @ error/dng.c/ReadDNGImage/572
![image](https://github.com/d2phap/ImageGlass/assets/79905337/ace5e8ca-a299-44fd-8949-9ad11b9c118b)

At first I suspected the scanning software generating broken files, but they seem to open perfectly fine in Photoshop or Lightroom.
Color images in the same format from the same scanning software open fine. (Including grayscale from the r/g/b/infrared channels)

### Expected behavior:
File should open normally.

### Screenshots:
Color Scan: 
[RAW File](https://drive.google.com/file/d/1ElM_dwekxqETK3JvNO6rtcdgrzalDiC5/view?usp=share_link)
![Screenshot_59](https://github.com/d2phap/ImageGlass/assets/79905337/a84dc11a-7ded-4256-80e0-43051ec4093a)

Grayscale Scan:
[RAW File](https://drive.google.com/file/d/1JTywpxXGB4MshidzpYww7A3fx-V6Uvmb/view?usp=share_link)
![Screenshot_60](https://github.com/d2phap/ImageGlass/assets/79905337/55f1d772-5331-4e96-a44f-6579efb941c5)

The issue seems to only appear with the Grayscale setting set to Auto:
![image](https://github.com/d2phap/ImageGlass/assets/79905337/094b5c6c-18ae-4463-bc94-878663211a61)

[Folder with more example DNG files](https://drive.google.com/drive/folders/1FWiDJA0qFoB6cHTyIlB70WoxDCc5e5dH?usp=share_link) including separate color, auto grayscale and grayscale from a single color channel.
[Auto Grayscale DNG ImageGlass Issue.zip](https://github.com/d2phap/ImageGlass/files/11565227/Auto.Grayscale.DNG.ImageGlass.Issue.zip)

### Additional context:
Halfway into writing this issue, I found out the cause for this error was the Auto setting. Grayscale from manually selected color channels works fine. So it's probably a rather niche problem and low priority.
 
I've investigated this to some extend beforehand and there seem to be some differences in the Metadata. Namely the Auto settings one seemingly only having one color channel:
Auto Grayscale:
![Screenshot_62](https://github.com/d2phap/ImageGlass/assets/79905337/db984d2f-f332-48e5-a664-03fd3fb71a6f)
![image](https://github.com/d2phap/ImageGlass/assets/79905337/4e0fdb99-6213-4e63-8290-afd71deb85c8)

Grayscale from blue:
![Screenshot_63](https://github.com/d2phap/ImageGlass/assets/79905337/41c3a55d-15fc-4002-a569-4c12630506b8)
![image](https://github.com/d2phap/ImageGlass/assets/79905337/93452f88-2f31-4575-9d69-346de9e5b3e4)

Sorry if this is slightly unstructured. I was trying to investigate myself before posting, adding information as I was writing.

**Comment by d2phap** [comment]
Thanks @ClenonWolf for the details!
I will report this to MagickNET fork because the error comes from MagickNET library.

**Comment by d2phap** [comment]
This issue is fixed in v8.9
