### ISSUE TITLE
Very slow to open an animated webp

### ISSUE THREAD

**Issue by xiaweichuliang** [d2phap/ImageGlass#1576]
### System information:
 - Windows OS version: 10
 - ImageGlass version: 8.8.4.4

### To Reproduce
1. opening an animated .webp image is very slow, maybe get stuck and broken. But use another software called Honeyview can open it quickly, but it behaves worse in opening a .gif file. 
2. 
3. 
4.

**Comment by d2phap** [comment]
@xiaweichuliang 
- Can you try using Repair feature from the IG installer to clear the old cache, see https://github.com/d2phap/ImageGlass/issues/1525#issuecomment-1489572306
- Can you attach your webp file?
- Can you try IG v9.0 beta 4?

**Comment by xiaweichuliang** [comment]
> @xiaweichuliang
> 
> * Can you try using Repair feature from the IG installer to clear the old cache, see [Unhandled Exception error #1525 (comment)](https://github.com/d2phap/ImageGlass/issues/1525#issuecomment-1489572306)
> * Can you attach your webp file?
> * Can you try IG v9.0 beta 4?

Sorry, Github does not allow me to upload .webp file, and I tried several times but still cannot download beta4 because it will turn to Microsoft shop and is not for free (I am a greenhand on this stuff)

**Comment by d2phap** [comment]
> Github does not allow me to upload .webp file

You can zip it, or change the extension to jpg before uploading.

> I tried several times but still cannot download beta4 because it will turn to Microsoft shop and is not for free (I am a greenhand on this stuff)

v9.0 beta 4 is not on MS Store yet, you can download from the Assets section of the release:
<img width="986" alt="image" src="https://github.com/d2phap/ImageGlass/assets/3154213/eb0d53c7-b023-43b9-a01c-0e9639e72217">

**Comment by xiaweichuliang** [comment]
can you send me your email address? I'll send you the file and the comparison with Honeyview. But it has adult content, sorry for that

**Comment by d2phap** [comment]
Don't you have another file to test? Does it happen to only that file?
