### ISSUE TITLE
Fix "open with" menu on Windows 7

### ISSUE THREAD

**Issue by xmha97** [d2phap/ImageGlass#1579]
It's a fix fox https://github.com/d2phap/ImageGlass/issues/869
Please use:
```
C:\Windows\System32\rundll32.exe shell32.dll,OpenAs_RunDLL C:\Windows\IdentityCRL\WLive48x48.png
```
Instead of:
```
"C:\Windows\System32\OpenWith.exe" C:\Windows\IdentityCRL\WLive48x48.png
```
It works on Windows XP - 11

**Comment by d2phap** [comment]
Since v9 requires Win 10 version 2004 or later, it should not be an issue
