### ISSUE TITLE
Per user file association (not per machine)

### ISSUE THREAD

**Issue by xmha97** [d2phap/ImageGlass#1581]
As you know, the installer is not optimized for standard users https://github.com/d2phap/ImageGlass/issues/1216, and finally, I found out that I can use the [Scoop](https://scoop.sh/) manager package. This package manager installs all apps without administrator access. (Unlike the [Chocolatey](https://chocolatey.org/))
```PowerShell
scoop bucket add extras
```
```PowerShell
scoop install extras/imageglass
```
Now the ImageGlass app is installed and works without problems, but the File Type Associations section still requires admin access!

![IMG_20230526_155608](https://github.com/d2phap/ImageGlass/assets/23485114/b9691543-edf5-408a-9289-8ed1acda093e)

File association in the app should work without admin access because my choice should not affect the choice of other users.
Also, file association per machine can give a bad performance to other users if ImageGlass is installed only for the current user because other users do not have access to this user's files and the app does not run.

File association can only be done for one user, see the 7-zip as an example app:

![image](https://github.com/d2phap/ImageGlass/assets/23485114/51743f2a-0152-445d-9fc6-ebc7a4fe7a85)

My English is poor and this text is translated, if you don't understand something, ask.

**Comment by xmha97** [comment]
@d2phap Can you make this a high priority?

**Comment by d2phap** [comment]
Not for v8, this will introduce a breaking change

**Comment by d2phap** [comment]
Implemented in [ImageGlass 9.0 beta 5](https://github.com/d2phap/ImageGlass/releases/tag/9.0.5.726)
