### ISSUE TITLE
Unable to compile V9

### ISSUE THREAD

**Issue by boromyr** [d2phap/ImageGlass#1582]
I tried to compile ImageGlass 9 but the ImageGlass.Tool project seems to be missing. The project is either missing or not uploaded to git by mistake.

### To Reproduce
1. Download ImageGlass V9 from git
2. Start compiling

### Actual behavior:

Error NU1104 The project 'D:\Users\PC\Documents\@imageglass\ImageGlass.Tools\Source\ImageGlass.Tools\ImageGlass.Tools.csproj' was not found. Verify that the project reference is valid and that the project file exists.

### Screenshots:
![image](https://github.com/d2phap/ImageGlass/assets/52782032/07c31bf2-ba74-44bc-857e-223c1ac38b23)

### Additional context:
Visual Studio 2022

**Comment by d2phap** [comment]
You will need to add project reference to https://github.com/ImageGlass/ImageGlass.Tools. Note that the branch `1.9040` is for v9.0 beta 4, branch `develop` is for the upcoming beta 5.
