### ISSUE TITLE
Multipage TIF files

### ISSUE THREAD

**Issue by Kakmael** [d2phap/ImageGlass#1583]
### System information:
 - Windows OS version: Windows 10 Entreprise LTSC 1809
 - ImageGlass version: 8.7.11.6 x64

### To Reproduce
1. Opening a multipage TIF file with Imageglass.

### Actual behavior:

TIF files are associated with ImageGlass. When opening a 1 page TIF file: everything works. When opening multipage TIF file, error occurs. The error is "ImageGlass cannot open this picture because the file appears to be damaged, corrupted or not supported". When opening this TIF file with the Windows Photo Viewer, it workd (old version, don't know for the new version). You can navigate between the TIF pictures. It's like a bundle.

### Expected behavior:

Opening and showing all the TIF files bundled into one TIF file. 

### Screenshots:

![image](https://github.com/d2phap/ImageGlass/assets/135025821/c76aa106-cca5-4d90-b1df-dee4ccf1f2ea)
![image](https://github.com/d2phap/ImageGlass/assets/135025821/0e337de6-5220-4184-bd5e-1595106edb5a)

### Additional context:

A TIF test file is appended to the ticket. I had to ZIP it so i can upload it. 
Test File : [Multipage.zip](https://github.com/d2phap/ImageGlass/files/11599816/Multipage.zip)

Sorry this is my first ticket ever on GitHub, be kind :)

**Comment by d2phap** [comment]
Thanks @Kakmael. I managed to fix it by ignoring the tag 32932.

**Comment by d2phap** [comment]
This issue is fixed in v8.9

**Comment by Kakmael** [comment]
Hello @d2phap 
Thank you a lot for the bugfix. It worked, I tested it with several files.
To naviguate between the pages, is there a "GUI" way? I could do it with ctrl+arrow, but it is hard to see that there are multiple pages. Should I create a change request?
Thanks !

**Comment by d2phap** [comment]
You can open the "Page navigation tool" in menu Tools.
![image](https://github.com/d2phap/ImageGlass/assets/3154213/863dbb25-6847-46b5-9f62-e4991b057a21)
