### ISSUE TITLE
Exit button on Toolbar

### ISSUE THREAD

**Issue by tboy-123** [d2phap/ImageGlass#1588]
Exit button at the end of the Toolbar will be good for people who work mostly with mouse. 

Bug - Program can not open big Photoshop (PSD)  files - 180 MB for example . Tested in last official release and new beta version. Same files are  OK in other viewers.  (I'm on Wndows 10 LTSB)

Thank you for this fantastic program!

**Comment by d2phap** [comment]
You can add new button on toolbar in v9.0 beta by editing `igconfig.json` file. See [the changelog of v9.0 beta 1](https://github.com/d2phap/ImageGlass/releases/tag/9.0.1.514).
Some thing like this:
```json
"ToolbarItems": [
  {
    "Type": "Button",
    "Id": "Btn_Exit",
    "DisplayStyle": "Image",
    "Alignment": "Right",
    "Image": "XXXXXX",
    "OnClick": {
      "Executable": "MnuExit"
    }
  },
]
```

> Bug - Program can not open big Photoshop (PSD) files - 180 MB for example . Tested in last official release and new beta version. Same files are OK in other viewers. (I'm on Wndows 10 LTSB)

What is the error message?
Can you send a screenshot, or a download link of the file?

**Comment by tboy-123** [comment]
Few days ago I installed latest drivers for my video card and now I can NOT reproduce this error. Everything is OK with opening very large PSD files - even above 500 MB.
I'm sorry for this false report. Please delete it if necessary but keep EXIT button request.
