### ISSUE TITLE
Title bar supports white

### ISSUE THREAD

**Issue by bai12123** [d2phap/ImageGlass#1589]
### Is your feature request related to a problem? Please describe.

This is my current title bar color and I'm using the light theme. As far as I know, the title bar color of the dark theme can be changed to dark, but the title bar of the light theme cannot be changed to white.

### Describe the solution you'd like

I want to change the title bar color to white.

### Additional context

I'm using:
![06  ：21  ：56](https://github.com/d2phap/ImageGlass/assets/99849852/b9f1b222-75a9-42b1-97f3-06079a4ad3ed)
what I expected:
![06  ：21  ：56 (1)](https://github.com/d2phap/ImageGlass/assets/99849852/9cbba031-1921-4e81-9cf3-e12e5391ddc2)

**Comment by d2phap** [comment]
ImageGlass uses the native Windows title bar so it follows the Windows setting, it does not support title bar customization.

You can disable transparency in Windows settings but this will affect other apps and windows as well.

**Comment by bai12123** [comment]
I've tried turning off transparency, changing the theme color. Due to windows restrictions, the theme color can only be changed to gray, not white. These practices do not make the title bar white. I am using Windows11 22h2.
Before asking the question, I searched for similar issues in **issues** and found that the title bar of the previous version was white, and the solution was to change the theme color, but it didn't work, so I proposed a new feature.
![19  ：18  ：59](https://github.com/d2phap/ImageGlass/assets/99849852/36665c2f-79e8-4f5b-bc1b-83a78bc9105d)

**Comment by bai12123** [comment]
Before asking the question, I searched for related issues in **issues** and found that the title bar of the previous version was white, and I also tried to change the theme color, but this would cause my series of software to look discordant, so I proposed a new function

**Comment by d2phap** [comment]
I have no plan to implement a custom title bar
