### ISSUE TITLE
Thumbnails do not display when scaling != 100%

### ISSUE THREAD

**Issue by extrobe** [d2phap/ImageGlass#159]
On higher res displays, you might increase scaling

However, when this is done, and your scaling is not 100%, the thumbnail strip does not render correct - instead it shows the first letter(s) of the filename.

![image](https://cloud.githubusercontent.com/assets/25456852/23190727/8bbfcf40-f891-11e6-8dd3-126e00ce626a.png)

![image](https://cloud.githubusercontent.com/assets/25456852/23190809/0d302ec6-f892-11e6-870d-afc27ffbe14c.png)

(Using Windows 10.0.14393, Imageglass 3.5.9.17 - replicated on several devices)

**Comment by d2phap** [comment]
Thanks extrobe for the issue.
However, this is duplicated issue which reported at #32. Please refer to #32 instead.

Anyway there is an testing version for this, you can find and help me test by the download link in #32

Thanks,
Phap
