### ISSUE TITLE
Windows installer breaks file associations

### ISSUE THREAD

**Issue by CodeMarc11** [d2phap/ImageGlass#1592]
### System information:
Windows 10 Home x64 22H2, non-Admin user (UAC required Admin password to run installer), ImageGlass Kobe_8.9.6.9_x64. Though I've seen this with previous installers.

### To Reproduce:
I had ImageGlass Kobe_8.7.11.6_x64 installed, with ImageGlass as the default image viewer.
1) I installed the new version 8.9.6.9 selecting "Typical" install.
2) After install, I double-clicked a PNG file and got the Windows error for no file association:
![File association error](https://github.com/d2phap/ImageGlass/assets/38742926/72ccf224-1a72-4e75-9c1c-27a3d5304acd)

### Actual behavior:
The "Typical" install _removed_ the file associations from ImageGlass, leaving them set to nothing.

### Expected behavior:
Installer (default/Typical) leaves file type associations unchanged.

### Additional context:
I re-ran the new installer and chose "Modify". Features showed "File Type Associations" with a red X, labelled "optional, excluded by default". Guessing this is meant to leave existing file type associations unchanged by default, but instead (for the occasional installer) removes them? Could running as a non-Admin user be related? It's "good security practice," but most Windows home users just run as an Admin.

Changing File Type Associations to "Will be installed" and finishing the installer fixed the associations; the PNG opened in ImageGlass. However, Windows was still confused about ImageGlass as the default image viewer. Settings: Default apps shows ImageGlass, but still has a "+" as if nothing is set 🤔:
![Broken default image viewer](https://github.com/d2phap/ImageGlass/assets/38742926/04bd08ce-46f2-41a7-a0b2-df84ed85a84a)

**Comment by d2phap** [comment]
You can open Settings > File type associations, click on "Unregister extensions" button to remove all ImageGlass associated file type keys in registry. This will delete the broken "ImageGlass" menu in Default apps as well.

After that, you can either click on "Set as default photo viewer" button or use Prepair from the MSI.

**Comment by CodeMarc11** [comment]
"Unregister extensions" in ImageGlass results in an error dialog "Unable to delete registered file extensions of ImageGlass app". The file associations were still set after.

I think that got rid of the broken "ImageGlass" entry in the Default apps menu with "+" for an icon, in spite of the error.

**Comment by d2phap** [comment]
The error message is expected and reported some times here as well. But it should still work.
