### ISSUE TITLE
Rotating Multi-Page .tif files stops navigaion

### ISSUE THREAD

**Issue by Nodle** [d2phap/ImageGlass#1599]
### System information:
 - Windows OS version:  Windows 11
 - ImageGlass version: 8.9.6.9 x64

### To Reproduce
Steps to reproduce the behavior
1. Open multi-page .tif
2. Navigate to any page within .tiff
3. Rotate page any number of times
4. Can no longer change page.

### Actual behavior:
After opening a multi-page .tif document and you navigate to then rotate any of the pages you will be unable to navigate to a different page.
This behavior also applies to flipping horizontally and vertically.
Another observation is that the window title `| x/n pages |` section will reset to `| 1/n pages |` when you try and change page after rotation.

![image](https://github.com/d2phap/ImageGlass/assets/1491567/9e95f0a6-37e1-4bbe-ae72-75dea7f0fa2a)

### Expected behavior:
You should still be able to navigate to other pages within the .tif regardless of the orientation of an individual page.

### Additional context:
I have attached the .tif file example. 
Extension changed to .txt due to supported uploadable files.
[multipage_tiff_example.tif.txt](https://github.com/d2phap/ImageGlass/files/11795111/multipage_tiff_example.tif.txt)

**Comment by d2phap** [comment]
ImageGlass v8 does not support saving multi-page formats (GIF, TIF, ...). [ImageGlass 9.0 beta 4](https://github.com/d2phap/ImageGlass/releases/tag/9.0.4.416) basically supports it without any warranty.

You should see a warning message in both version when saving image.
