### ISSUE TITLE
Failed to associate with certain file types (e.g., .png) as default application

### ISSUE THREAD

**Issue by herrlich10** [d2phap/ImageGlass#16]
After installation, I launched ImageGlass as administrator and Settings > File Associations > Add default > Set associations. 

Some image types (e.g., .gif) was successfully associated (when double clicked, ImageGlass would launch), but others were not (including .jpg and .png). When I double click the image file, or right click > Open with > ImageGlass 2, Windows Photo Viewer is launched instead.

I checked the Windows register, under HKEY_CLASSES_ROOT, ".png" seemed to point to another entry called "pngfile", and pngfile > shell > open > command was set to ["C:\Program Files (x86)\ImageGlass\ImageGlass.exe" "%1"] without the bracket, which seemed to be normal.

I'm running 64-bit Windows 7 Home Premium SP1, ImageGlass 2.0.1.5.

**Comment by d2phap** [comment]
There were some issues with the installer.
Temporarily, please use File Associations of Windows to set as default application.

Thank you!

**Comment by herrlich10** [comment]
Strangely, even if I Right click a .png file > Open with > Choose default program... > Image Glass 2 > Check "Always use ..." > OK (I think this is what you mean by "use File Associations of Windows to set as default application"), the file is still opened with Windows Photo Viewer... And this is exactly what I don't understand. 

When I set default program to Paint, it works as expected. It seems that Windows is treating Image Glass and Windows Photo Viewer as the same. How to achieve this effect (with windows registry settings)?

**Comment by d2phap** [comment]
It is so strange!

Please try "Set Associations" in control panel.
http://www.7tutorials.com/how-associate-file-type-or-protocol-program

**Comment by herrlich10** [comment]
I tried the approach using control panel, without luck.

Then I uninstalled Image Glass, and reinstalled again. This time, manually set file association from either context menu or control panel both worked! Although batch setting for multiple file types from within Image Glass Settings dialog still has no effect, I can start working:)

I guess the uninstall procedure somehow fixed my registry (potentially corrupted because I've tried a lot of other image viewers for locked zoom level and pan position across images during browsing, or even slideshow, before I finally find Image Glass. Great job!)

**Comment by d2phap** [comment]
Thank God!
Anyway, this may the big issue. Thank you for explaining clearly.

**Comment by saaa-hsjgrobler** [comment]
I'm having the same issue. JPG files open in ImageGlass, but PNGs and pretty much everything else opens in windows photo viewer. I've tried setting as default through windows "right click > open with > set default" and it still opens in photo viewer. I went to settings for ImageGlass and set the associations to default and it still did nothing. I added the context menu entries and "Open with ImageGlass" does work. Even from within Photo Viewer if I go "Open > ImageGlass" it just re-opens in photo viewer. In the windows list of file associations it shows that ImageGlass is set to open all image formats. Going to try uninstalling and re-installing now. Using version 2.0.1.5.

**Comment by saaa-hsjgrobler** [comment]
Uninstalling and re-installing fixed the issue for me as well.
My exact process was: Uninstall ImageGlass > Run CCleaner on registry > Download and install latest version of ImageGlass (still 2.0.1.5) > Launch ImageGlass > Settings > File Associations > Set Associations.

**Comment by d2phap** [comment]
Thank you *saaa-hsjgrobler*!
This issue was reported so long time. Unfortunately, I have been kinda busy for recent months, so I couldn't publish a new release to fix all reported bugs.

**Comment by ilpssun** [comment]
I was experiencing the same issue for PNG files (Windows kept opening the Windows image viewer).  Uninstalling and reinstalling ImageGlass fixed the problem for PNG files, but now the Adobe Acrobat link in my start menu also has an ImageGlass file icon :-(  Pretty annoying – but of course better than not being able to open PNG files via double clicking.

**Comment by Dol-phin** [comment]
@saaa-hsjgrobler Cleaning the registry isn't recommended: http://www.edbott.com/weblog/2005/04/why-i-dont-use-registry-cleaners/

**Comment by reddit-is-fun** [comment]
I can't set a default photo viewer in Windows 10 system settings. Imageglass isn't in the list and I only have the option to open the store. Only PNG files don't open with the program, from what I've tested.

**Comment by lovebdsobuj** [comment]
@d2phap,
> ### Can't set **ImageGlass** as a default photo viewer on Windows 10. Imageglass not present in the list > `Control Panel\Programs\Default Programs\Set Default Programs`

**Comment by blindhead** [comment]
I solved correcting the program path in the regedit

![pantalla-001455](https://cloud.githubusercontent.com/assets/23023062/19634221/a87ea6e6-997e-11e6-80a6-b74b2d2aef37.png)

**Comment by d2phap** [comment]
The issue is fixed (same as #129).
This is a tesing version: http://www.imageglass.org/upload/moon/ImageGlass_3.x_17032017.zip
