### ISSUE TITLE
ImageGalss was faster to open images?

### ISSUE THREAD

**Issue by arnofly** [d2phap/ImageGlass#1600]
### System information:
 - Windows OS version: Windows 10 x64 22H2
 - ImageGlass version: 8.9.6.9 x64

### To Reproduce
1. Just double click on an image file and wait... ;)
2. Go to the next/preview image in the folder from ImageGlass, and wait... ;)

### Actual behavior:
I use the same computer and I seem to remember that ImageGlass was faster. Maybe I'am not alone.

**Comment by arnofly** [comment]
I imported my old AppData directory in new Windows profile, so I will start by create a new ImageGlass profile.

**Comment by laniakeadev** [comment]
Same, on 8.8.4.4

**Comment by eebssk1** [comment]
While the current version is not really slow for me, it seems the older version do slightly faster.

**Comment by arthurjosse** [comment]
Just tested the supposedly faster new version (moon rc 9) and damn, choking performance. Opening an image take at least a couple of seconds!

**Comment by d2phap** [comment]
See https://github.com/d2phap/ImageGlass/issues/794#issuecomment-1752286529
