### ISSUE TITLE
Keep focus in Window Fit mode when mouse outside image, to prevent interrupted file-scrolling

### ISSUE THREAD

**Issue by hced** [d2phap/ImageGlass#1601]
### Issue

I'm using Mouse Scrollwheel for Next/Prev image.

When mouse wheeling in Window Fit mode, you'll end up with an image whose windo smaller than your current mouse position. At that point the scrolling is handed over to the OS, which breaks the flow!

### Proposed solution
Would love having ImageGlass retain focus if mouse isn't over image window in Window fit mode.

If not by default, then maybe an optional setting: "Keep application focus in Window fit mode" or something along those words?

I'm using the latest Moon ImageGlass on Windows 11. (Side question: I noticed image scrolling is almost twice as fat scrolling images in Window fit mode! Which is a real bonus!)

**Comment by d2phap** [comment]
I don't think (or don't know) it's possible to do wheel scroll out side of the window area.
Technically, you need to hover on it when scrolling so that the scroll event is triggered and ImageGlass will process it.

A workaround is to use hotkeys (Left/right arrow)

**Comment by d2phap** [comment]
Closed as not planned.
