### ISSUE TITLE
Flicker in toolbar when scrolling through images

### ISSUE THREAD

**Issue by QueenUlyana** [d2phap/ImageGlass#1602]
### System information:
Windows 10 LTSC
ImageGlass version: 8.9.6.9

### To Reproduce
Flipping .png .jpeg .gif images

### Actual behavior:
Flickers

### Expected behavior:
No flicker

https://github.com/d2phap/ImageGlass/assets/83131824/31731dc2-dfe9-4c26-9663-d634f20d00e6

**Comment by QueenUlyana** [comment]
**I also noticed that ImageGlass opens slower than the standard Windows viewer.**

**Comment by d2phap** [comment]
The flickering issue is fixed in v9.0 beta

**Comment by QueenUlyana** [comment]
> The flickering issue is fixed in v9.0 beta

**Which one should I download?**
![2023-06-27_171625](https://github.com/d2phap/ImageGlass/assets/83131824/d5800b1e-463d-476b-81ea-f68543edec61)

**Comment by QueenUlyana** [comment]
> The flickering issue is fixed in v9.0 beta

I ended up downloading "ImageGlass_Moon_9.0.4.416_Beta-4_x64_net7.zip" and unzipped the folder into Program Files. As a result, now there is no my language and no normal settings as before. Now the settings are in a text file, I tried to switch the language to my native language, but no results. Everything is still in English, now how to configure the program for myself, I do not know.

![2023-06-27_172930](https://github.com/d2phap/ImageGlass/assets/83131824/4759823f-2f36-4028-9b26-7f517c49e708)

**Could you release a release version with normal settings?**

**Comment by QueenUlyana** [comment]
**Yeah, so also to this, the settings in text format are not saved, no matter how much I did not save them, they are reset to the base. Bullshit!**

**Comment by QueenUlyana** [comment]
@d2phap Could you just make a fix for version 8.9.6.9 (remove flickers) and that's it? I would like that very much, do it please. That's all I ask. I don't need these betas at all, they are total crap.

**Comment by d2phap** [comment]
@QueenUlyana 
- You English is definitely better than mine, but your talking manner is not. You should learn how to ask nicely, that will help you to have better image in other people.
- All the things you complained are why it's called beta, not official release. See https://www.pcmag.com/encyclopedia/term/beta-version
- As I mentioned, this issue is fixed in the beta release. You can either use the v8 or the beta, or wait for the official release.
