### ISSUE TITLE
issue rendering svg

### ISSUE THREAD

**Issue by 3xploiton3** [d2phap/ImageGlass#1605]
### System information:
 - Windows OS version: windows 11
 - ImageGlass version: 8.9.6.9 x64

reference:
https://www.ups.com/assets/resources/webcontent/images/ups-logo.svg

### Screenshots:

![image](https://github.com/d2phap/ImageGlass/assets/19517680/062e305d-e3cb-45c7-98e7-aaa0ee9dd2b6)

chrome stable
![image](https://github.com/d2phap/ImageGlass/assets/19517680/a7603665-74ff-4d73-b8d5-ba24539e47b3)

**Comment by d2phap** [comment]
Hi @3xploiton3 

ImageGlass uses MagickNET, MagickNET uses `librsvg` to read and render SVG file.
The library has limitations.
