### ISSUE TITLE
double click on photo and instant full screen, press esc to close viewer.

### ISSUE THREAD

**Issue by dreamstates** [d2phap/ImageGlass#1606]
Hello, I would simply like to be able to double click on an image file, have it open in full screen zoomed in so it touches the edges of the screen then press escape to end the photo viewer app. I downloaded the latest version for win11. 

Thank you.

**Comment by d2phap** [comment]
Please refer to this https://github.com/d2phap/ImageGlass/issues/1753#issuecomment-1840794799
