### ISSUE TITLE
Lock position

### ISSUE THREAD

**Issue by markovandooren** [d2phap/ImageGlass#1608]
### Is your feature request related to a problem? Please describe.

I very often need to inspect a series images when zoomed in to clearly see individual pixels. Therefore I lock the zoom level in the UI. This allows me to quickly go from image to image when I am looking at the center of the image. But this does not work when the area I want to inspect is not in the center of the image because the position always resets to the center when I go to another image. 

### Describe the solution you'd like
Similar to the button to lock the zoom level, I would like to have a button that locks the position. In case that would is an invalid position for the next image, then it could either go back to the center or to the nearest corner.

**Comment by d2phap** [comment]
This was requested at #795 and implemented in [ImageGlass Moon 9.0 beta 3](https://github.com/d2phap/ImageGlass/releases/tag/9.0.3.1225). The "Lock zoom ratio" also keeps the position for the next image.
