### ISSUE TITLE
Smooth touch gesture

### ISSUE THREAD

**Issue by TheCGDF** [d2phap/ImageGlass#1611]
When swipe to view the previous/next picture, it will help a lot if there is a animation to preview the previous/next picture.

Just like:
![image](https://github.com/d2phap/ImageGlass/assets/17256673/115b3e57-8889-4d1e-aeab-f4e70b0e2684)

Or use a fade animation.

Also, the zoom gesture is not smooth too...

**Comment by d2phap** [comment]
Touch gestures are supported in [ImageGlass 9.0 beta 5](https://github.com/d2phap/ImageGlass/releases/tag/9.0.5.726) including
- Pinch to zoom
- Swipe to pan
- Long tap to open context menu
I will not support swipe left/right to navigate to other image
