### ISSUE TITLE
When triggering custom hotkeys such as `Alt` and `[Key]` causes windows error sound to play

### ISSUE THREAD

**Issue by gaberiel44** [d2phap/ImageGlass#1613]
### System information:
 - Windows 11
 - Version 9.0.4.416 (64bit) 

### To Reproduce
1. Using `Alt` and `Z` as a hotkey in the `igconfig.json`
2. Trigger `Alt` + `Z` 
3. Hotkey triggers command
4. Then, Windows Error sound plays

Using `Alt` and `[Key]` as a hotkey in the `igconfig.json` file works but after triggering the hotkey, windows error sound is player.
I think its because in IG, the alt modfier is set to trigger "Menu Bar" panel, in this case, the toolbar panels. 

It would be cool if we can repurpose these keys to our own use instead.

**Comment by d2phap** [comment]
Thanks, I also noticed it and fixed in the upcoming beta 5

**Comment by d2phap** [comment]
This issue is fixed in [ImageGlass 9.0 beta 5](https://github.com/d2phap/ImageGlass/releases/tag/9.0.5.726)
