### ISSUE TITLE
Cropping Picture goes to previous/next picture if mouse is released on the sides of the window

### ISSUE THREAD

**Issue by Ares9323** [d2phap/ImageGlass#1616]
### System information:
 - Windows OS version: 11
 - ImageGlass version: ImageGlass_Kobe_8.9.6.9_x64

### To Reproduce
1. Click "Cropping"
2. Resize the picture and stay close to the window borders
3. Release the mouse

### Actual behavior:
It goes to next/previous picture instead of cropping it

### Expected behavior:
The picture is cropped and you can save it.
It's fine to be able to go to the next picture, but if I'm drawing a rectangle to crop the picture it's pretty obvious that I don't want to go to the next picture. Probably the event is fired on mouse button release and this is causing the issue.

### Screenshots:
https://github.com/d2phap/ImageGlass/assets/46932745/1b12146c-9c79-41ad-a6fe-ff1a6a4af90b

**Comment by d2phap** [comment]
This is fixed in v9.0
