### ISSUE TITLE
certain TIF pictures doesn't load

### ISSUE THREAD

**Issue by JoGrob** [d2phap/ImageGlass#1617]
### System information:
 - Windows OS version: Win 11 x64
 - ImageGlass version: 8.9.6.9

### To Reproduce
1. try loadin TIF picture
2. errormessage appears

### Actual behavior:
instead of displaying the picture a errormessage appears

### Expected behavior:
TIF picture should be displayed

### Screenshots:
![Screenshot 2023-07-24 141801](https://github.com/d2phap/ImageGlass/assets/59739587/708371eb-8912-46f5-80f4-600c4cdc1937)

### Additional context:
Similar to issue 1454 may be fixed by ignoring tag 34031 // TrapIndicator

(https://github.com/d2phap/ImageGlass/issues/1454)

**Comment by d2phap** [comment]
This issue is fixed in [ImageGlass 9.0 beta 5](https://github.com/d2phap/ImageGlass/releases/tag/9.0.5.726)

**Comment by d2phap** [comment]
Also fixed in v8.10
