### ISSUE TITLE
RW2 (panasonic RAW) wrong orientation

### ISSUE THREAD

**Issue by kendoka15** [d2phap/ImageGlass#1619]
### System information:
 - Windows OS version: Windows 10 Pro x64 22H2
 - ImageGlass version: 8.9.6.9 x64

1. Untick "Use embedded thumbnail for RAW formats" in "Image" tab in settings
2. Open .RW2 file

The portrait image (included below) opens in landscape. This happens for all my RW2s. The EXIF contains "Rotate 270 CW".

The included file is in a .zip because github would not let me upload .RW2
[P1160304.zip](https://github.com/d2phap/ImageGlass/files/12166529/P1160304.zip)

**Comment by d2phap** [comment]
fixed in v8.10
