### ISSUE TITLE
Fails to open from File Explorer

### ISSUE THREAD

**Issue by Yogmesh** [d2phap/ImageGlass#1621]
### System information:
 - Windows OS version: 11
 - ImageGlass version: 8.9.6.9 x64

### To Reproduce
1. Have ImageGlass set as the default image viewer
2. Open Window's File Browser
3. Double click on an image
4. Receive file system error message

### Actual behavior:
For a couple weeks after installing Image Glass worked just fine. Then one day, ImageGlass stopped opening images by double clicking them in the File Browser window. ImageGlass will still open images if you open ImageGlass and go to File->Open option. All other features of ImageGlass still seem to work, other than the WIndows "Open with" function.

**Comment by d2phap** [comment]
Hi @Yogmesh 
What is the system error? Can you attach a screenshot?

**Comment by Yogmesh** [comment]
![Screenshot 2023-07-26 103734](https://github.com/d2phap/ImageGlass/assets/140600140/7f51af7f-9849-436b-97c9-df050992af8c)

**Comment by d2phap** [comment]
Looks like Windows reset the file type associations.

You can go to ImageGlass Settings, open tab File Type Associations, click on “Set as default photo viewer” button.

An error dialog may appear, just ignore it.

**Comment by Yogmesh** [comment]
No luck on resetting the file associations. I tried resetting the default app for images in both the File Browser and Settings->Apps->Default, with a full reboot in between, but the error persists. Opening images direct from File Browser with the in-built Photos app still works fine, so the problem seems to be software specific rather than general usage.

**Comment by d2phap** [comment]
This is not ImageGlass' error, but Windows file type associations error.
If you google the error, you will see a ton of them.

You can follow steps here to see if it works:
https://answers.microsoft.com/en-us/windows/forum/all/explain-system-error-2143322102-all-my-photos-wont/724e608b-dcf7-44df-8794-0767a964721e
