### ISSUE TITLE
Cannot open this JPG file with v9.0 beta 5

### ISSUE THREAD

**Issue by suyangzuo** [d2phap/ImageGlass#1622]
### System information:
 - Windows OS version: 11 22H2
 - ImageGlass version: Beta 5

用 ImageGlass 打开就会出现如图错误：
<img width="247" alt="2nElc83Qww" src="https://github.com/d2phap/ImageGlass/assets/50766353/e7c88746-4869-42f6-915e-42f34dbc9515">

我已将此图片上传
![playstation](https://github.com/d2phap/ImageGlass/assets/50766353/31008961-f200-4f85-b250-3e54e8d747ed)

**Comment by d2phap** [comment]
It's upstream issue, I already reported to MagickNET fork!

**Comment by d2phap** [comment]
Fixed in [ImageGlass 9.0 RC](https://github.com/d2phap/ImageGlass/releases/tag/9.0.6.1008)
