### ISSUE TITLE
SVG render bug

### ISSUE THREAD

**Issue by ghost** [d2phap/ImageGlass#1625]
### System information:
 - Windows OS version: 11
 - ImageGlass version: 8.9.6.9 (latest)

### To Reproduce
1. Open SVG

### Actual behavior:
Not rendered correctly. The SVG looks like a glitch. This happens to the most of SVG files. I tried a lot different ones.

<img src="https://github.com/d2phap/ImageGlass/assets/53160891/1b4c57e8-3a84-44a4-aa2a-e01f7d0e5da5" width="300" />

<sup>Viewed in ImageGlass.</sup>

### Expected behavior:
Correct rendered.

<img src="https://github.com/d2phap/ImageGlass/assets/53160891/5b8317e8-57a5-47d7-aa8a-426a4c8eaa08" width="300" />

<sup>Viewed in Chrome.</sup>

### Source File

[albums.zip](https://github.com/d2phap/ImageGlass/files/12222826/albums.zip) (svg inside)

**Comment by d2phap** [comment]
ImageGlass v8 has limits in rendering SVG format. You can try [ImageGlass Moon 9.0 beta 5](https://github.com/d2phap/ImageGlass/releases/tag/9.0.5.726) for full featured SVG support.

**Comment by ghost** [comment]
The main view looks good but the thumbnails below not (same as in v8).
![screenshot](https://github.com/d2phap/ImageGlass/assets/53160891/d139ffd5-d7d1-4681-b380-e4575a1ab411)

Also if you zoom with mouse wheel there is a bug that the image becomes tiny and in window title swtiches between 200% and a big percentage number.

![demo](https://github.com/d2phap/ImageGlass/assets/53160891/89715b73-4d87-4697-894f-58be2c09e715)

**Comment by d2phap** [comment]
The thumbnails are rendered by MagickNET (not Webview2). You can report this issue to https://github.com/dlemstra/Magick.NET.
