### ISSUE TITLE
Not working touchpad zoom for svg images

### ISSUE THREAD

**Issue by DanRotaru** [d2phap/ImageGlass#1626]
### System information:
 - Windows OS version: 11 PRO 22H2
 - ImageGlass version: [ImageGlass Moon 9.0 beta 5](https://github.com/d2phap/ImageGlass/releases/tag/9.0.5.726)

### To Reproduce
1. Open svg format image
2. Zoom in/out using laptop touchpad

### Actual behavior:
Not working zoom out (using touchpad) on svg format images, look at video and will be more clearly :)

### Expected behavior:
Shoud work :))

### Video:
https://github.com/d2phap/ImageGlass/assets/7759507/0e7d500d-06d3-4c00-bd19-bfb4b32548b7

Thanks a lot for Webview2 svg support!

**Comment by boromyr** [comment]
same problem in RC1 version

**Comment by d2phap** [comment]
Merge this to #1766 for now, I haven't been able to reproduce it yet.
