### ISSUE TITLE
with "Viewer / Display viewer scrollbars" enabled "Scale to fit (5)" doesn't work properly

### ISSUE THREAD

**Issue by JoGrob** [d2phap/ImageGlass#1628]
### System information:
 - Windows OS version: Windows 11
 - ImageGlass version: 8.9.6.9

### To Reproduce
1. open ImageGlass
2. got to "Settings", "General" and enable  "Viewer / Display viewer scrollbars"
3. open a picture in a directory with more pictures within
4. use "View next image" and "View previous image" to switch trough images
5. sometime you will see an non properly scaled image with a white frame

### Actual behavior:

with "Viewer / Display viewer scrollbars" enabled "Scale to fit (5)" doesn't work properly
Image sometimes is scaled to small with a white frame

### Expected behavior:

Image should be properly scaled to Windows size

### Screenshots:

![screenshot](https://github.com/d2phap/ImageGlass/assets/59739587/3eaea72c-ada2-46b5-a0fc-8aee5b749db5)

**Comment by d2phap** [comment]
Should not be an issue with v9
