### ISSUE TITLE
Thumbnail view

### ISSUE THREAD

**Issue by YepPlz** [d2phap/ImageGlass#1629]
We have thumbnail panel in the bottom. Can you add thumbnail view on whole window? Like in other apps: double click opens preview.

![image](https://github.com/d2phap/ImageGlass/assets/3154213/0e65124b-e7b4-4124-96e7-62cd1a1f51c0)

**Comment by d2phap** [comment]
ImageGlass aims not to be a photo organizer. If you want to view more thumbnails, you move it to the side.
- In v8.x, open Settings > Image > Thumbnail bar, select the option: `Show thumbnails on right side`
- In v9.0 beta 5, open Settings > Layout, drag the "Gallery" to the left/right side
![image](https://github.com/d2phap/ImageGlass/assets/3154213/1d0c2aa4-babd-4157-bd29-ed06d7bc3a81)
