### ISSUE TITLE
Crop: Save opens Save As-dialog instead of overwriting the current image

### ISSUE THREAD

**Issue by SvendK** [d2phap/ImageGlass#1631]
### System information:
 - Windows OS version: Windows 10 Version 22H2 (OS Build 19045.3324)
 - ImageGlass version: Version: 8.9.6.9 x64 [Portable]

### To Reproduce
1. Open image
2. Click Crop
3. Select cropping image
4. Click Save (not Save as...)

### Actual behavior:
The Save As... dialog opens - and not in the directory where the current image is and not with the current image name preentered and seleted, so OK can overwrite the current window.

### Expected behavior:
The current crop-selection is saved with the current images name and path, overwriting said image. You know, saving without asking for a name :-)
A warning/confirmation box could appear to make sure the user really want to overwrite the current image.

### Screenshots:
![image](https://github.com/d2phap/ImageGlass/assets/3720082/a8083116-4214-44df-9822-0e0f2627ae82)

**Comment by d2phap** [comment]
Hi @SvendK, please refer to https://github.com/d2phap/ImageGlass/issues/1614#issuecomment-1658320811

**Comment by SvendK** [comment]
Uh, perfect, thanks! I believe I searched for open issues with the same
problem, but I can see you fixed this 2 weeks ago in the beta.

It's no fuss, I just wait for the official release, just wanted to report
it.

Thanks for the quick reply.

Best regards,
Svend K
