### ISSUE TITLE
Main image display is "damped" / has a grey overlay

### ISSUE THREAD

**Issue by theMK2k** [d2phap/ImageGlass#1632]
### System information:
 - Windows OS version: Win 10 22H2 Build 19045.2728
 - ImageGlass version: ImageGlass_Moon_9.0.4.416_Beta-4_x64_net6 and ImageGlass_Moon_9.0.5.726_Beta-5_x64_net6

### To Reproduce

1. Open ImageGlass (with or without the image file as parameter)

### Actual behavior:

The main image display is "damped" / has a grey overlay, see screenshot below.

You can clearly see in the thumbnail gallery that the image should contain black and white, however, the main image display doesn't show these colors. Tested with Kobe and Kobe Light Themes.

### Expected behavior:

The main image display should show the same colors as the gallery. It should show the actual colors defined by the image file.

### Screenshots:

![image](https://github.com/d2phap/ImageGlass/assets/16878526/adcf0bf0-0b5a-4777-9a3f-eefcc7339b02)

![image](https://github.com/d2phap/ImageGlass/assets/16878526/81a40ab8-0a7a-414d-ae24-38d8df6e123c)

### Additional context:

none

**Comment by d2phap** [comment]
@theMK2k can you attach the file?

**Comment by theMK2k** [comment]
@d2phap sure. [SpaceInvader.zip](https://github.com/d2phap/ImageGlass/files/12357721/SpaceInvader.zip)

Please note that these are only examples. The issue happens 99% with any image I want to view in ImageGlass.

I also now tested ImageGlass on the same machine but in an RDP session. With this, the issue doesn't come up.

It looks like you implemented some sort of transition animation which is possibly broken when the issue with "damped" image display is in effect.

**Comment by d2phap** [comment]
No issue with the files, and IG 9.0 beta 5 displays correctly, too.
If it could cause by the transition, you can try disabling it in the app setting:

![image](https://github.com/d2phap/ImageGlass/assets/3154213/54492e48-e004-405b-8823-0287ea6951f0)

**Comment by theMK2k** [comment]
@d2phap disabling the transition effect definitely solved the problem for me. Even reverting back to enabled transition effects now let IG behave correctly. It's still mysterious what actually led to the issue. Currently I'm unable to provoke it.

**Comment by d2phap** [comment]
That's good to know! Thanks @theMK2k
