### ISSUE TITLE
IG does not appear on "Default Asscociation XML File"

### ISSUE THREAD

**Issue by Ogg3l** [d2phap/ImageGlass#1633]
### System information:
 - Windows OS version: Server 2012
 - ImageGlass version: 8.9.6.9

### To Reproduce
1.  Set Image Glass as Default Application for a jpg-file
2. Export with command: Dism.exe /online /export-defaultappassociations:C:\temp\CustomFileAssoc.xml

### Actual behavior:
Image Glass is not there under Association .jpg

### Expected behavior:
There should be an entry like:
![image](https://github.com/d2phap/ImageGlass/assets/37155857/9819a657-2841-4ed1-ac54-b7cfa6826c5b)

<Association Identifier=".jpg" ProgId="ImageGlass.AssocFile.JPG" ApplicationName="ImageGlass" />

Is it already a known issue?

Thank you for your support :)

**Comment by d2phap** [comment]
Hi @Ogg3l 

Can you check this thread:
https://groups.google.com/g/imageglass/c/-bkIUt_oJZo/m/D1b8ZGd3AAAJ

Some people could do it successfully
