### ISSUE TITLE
"Not a JPEG file: starts with 0xef 0xbb"

### ISSUE THREAD

**Issue by jocasrb** [d2phap/ImageGlass#1635]
### System information:
 - Windows OS version: 10
 - ImageGlass version: Image Glass Moon v9.0.5.726; did not work on previously version 

### To Reproduce
1. Error on opening a image (Type of file: ImageGlass JPEG File (.jpeg))

### Actual behavior:
I can not open particular image(s). But Photoshop is opening them without issues.

### Expected behavior:
I expect ImageGlass to show it

### Screenshots:
![qvvzvzvz](https://github.com/d2phap/ImageGlass/assets/58470362/a3aae5b6-c8d2-49e1-9299-95168a25cd0c)

### Additional context:

![qvvzvzvz](https://github.com/d2phap/ImageGlass/assets/58470362/e1acf0b6-b819-4912-b1a3-a5c53a76a8c7)

**Comment by d2phap** [comment]
It seems your file is not a JPEG file.
Could you attach the it here?

**Comment by jocasrb** [comment]
Ok here is one of the examples:
![49A1F1F2-7876-477E-A826-3786EE812936](https://github.com/d2phap/ImageGlass/assets/58470362/852bb0a9-db30-4c37-a561-89db9b295b3c)

Could be the reason be a image sent from other OS, so various Windows photo viewers cant open it?

EDIT: seems it doesnt show the image...here is the link: we. tl /t-tmTFyXmuwy

**Comment by d2phap** [comment]
Your file is invalid. None of the apps I tried can open it including GIMP, MS Photos and Chrome here, except for Photoshop. That's why it does not show the image on the browser here.

So I will just close this issue as the file is not valid.

**Comment by i-am-dies** [comment]
The same goes for JPG files with the "png" extension (you could rename any file yourself to check it). IrfanView and other viewers are able to guess real format and open these files without issues, where's ImageGlass just reports error. 

<img width="443" height="200" alt="Image" src="https://github.com/user-attachments/assets/78fd5bb9-ce47-436a-b5f1-e6ffef285692" />

<img width="1330" height="605" alt="Image" src="https://github.com/user-attachments/assets/437b0647-9a2c-4fe7-a7e3-26c0c2e048e2" />

<img width="335" height="496" alt="Image" src="https://github.com/user-attachments/assets/fd73106e-2ddf-44b4-8df6-3402c9db51e5" />

Also, the image of OP is indeed a JPEG. Could be with some issues tho.

<img width="875" height="532" alt="Image" src="https://github.com/user-attachments/assets/715780b5-7ea5-4cb0-b1b6-8b064910154e" />
