### ISSUE TITLE
Image order is ignored

### ISSUE THREAD

**Issue by Enferlain** [d2phap/ImageGlass#1638]
I press left, and right, and images appear in a random order, regardless of what I set the image loading order to. The options do change the order, but just to another random one, not to what I'm looking for. I just want it to go in the same way as my file explorer sort by date descending.

I'm on 9.0.5.726 after a clean windows install. This didn't happen on the previous version I was on, so I'm going to try installing that again.

**Comment by d2phap** [comment]
ImageGlass (both v8 and v9) has limits in supporting File Explorer sort order. Some of the requirements are:
- The Explorer window of the viewing folder must be remained open
- Only sorting by Name, File size, Extension are fully supported
- Sorting by date has different implementation
  + Explorer uses date value from EXIF data: DateTimeOriginal, CreateDate,...
  + ImageGlass uses date value from file attributes: Date created, Last access, Last write

**Comment by Enferlain** [comment]
Wasn't sure how to fix it. The stable installer version works fine without any tinkering in the same order as I have downloaded files in a folder, so that's good.
