### ISSUE TITLE
[Feature request] 1.There's no support for touch control  2.Deleting the old version of imageglass, still some remaining registry data never been cleaned.

### ISSUE THREAD

**Issue by 0-0alephant** [d2phap/ImageGlass#1640]
1.
No touch support on windows. pan, scale , will get some unexpected behavior.

2.
Right click using open with, old version of imageglass still present in the "Open With" option.

![Screenshot 2023-09-03 164759](https://github.com/d2phap/ImageGlass/assets/128656803/ec01d980-ef71-4a5a-9155-2bd4744c0ae6)

**Comment by addonaddict** [comment]
Please take care of this, when a program is removed, there should be absolutely no trace of it left on the system.
That should be a standard to strive for.

**Comment by d2phap** [comment]
> No touch support on windows. pan, scale , will get some unexpected behavior.

You can try ImageGlass 9.0 beta 5

> Right click using open with, old version of imageglass still present in the "Open With" option.

The installer is independent to the ImageGlass app. If you set ImageGlass as default photo viewer through the app, you will need to manually remove it
- in v8: Open Settings > File type associations, click on button: Unregister extensions
- in v9: Main menu > Help > Unset default photo viewer
