### ISSUE TITLE
加载一张超大的图像，操作卡顿

### ISSUE THREAD

**Issue by Linjinyia** [d2phap/ImageGlass#1641]
![image](https://github.com/d2phap/ImageGlass/assets/126772685/93e4c07f-e83b-4ddb-a8e7-a20a36d0e866)
你好。我在githup上找到您的项目，整体操作使用都非常优秀。但是不知道您有没有测试过加载超大图像缩放平移图像的时候，非常卡断。图像分辨率约17000*15000。

**Comment by d2phap** [comment]
Please write in English or Vietnamese
