### ISSUE TITLE
Support for 360° images

### ISSUE THREAD

**Issue by Happyclem** [d2phap/ImageGlass#1643]
Viewer for 360° images.
Currently, those images can be opened but there is not any option fo visualise them on every angles.

Thanks for your work already !

**Comment by oheimala** [comment]
Hi I would also love to see ImageGlass viewing 360 panorama .jpg images. I have not found any app supporting them easily, except Google Photos, but that is cloud based.

Maybe this component would be useful in the development? 
https://pchen66.github.io/Panolens/#Home

.. or this?
https://pannellum.org/

**Comment by d2phap** [comment]
Merge this to #1483
