### ISSUE TITLE
[Feature Request] Go to first image / Go to last image buttons on toolbar

### ISSUE THREAD

**Issue by BraianWhite** [d2phap/ImageGlass#1645]
As simple as the title says, it would be nice to have the option to add to the toolbar a button "go to first image" and another  "go to last image" of the current folder being browsed.

**Comment by d2phap** [comment]
Currently, ImageGlass 9.0 beta 5 does not have UI for customizing toolbar buttons yet. You can add new buttons by editing `igconfig.json` file.

To add View the first/last image buttons:

```json
  "ToolbarButtons": [
    {
      "Type": "Button",
      "Id": "Btn_ViewFirstImage",
      "Text": "",
      "DisplayStyle": "Image",
      "CheckableConfigBinding": "",
      "Alignment": "Left",
      "Image": "ViewFirstImage",
      "OnClick": {
        "Executable": "MnuGoToFirst",
        "Arguments": ""
      }
    },
    {
      "Type": "Button",
      "Id": "Btn_ViewLastImage",
      "Text": "",
      "DisplayStyle": "Image",
      "CheckableConfigBinding": "",
      "Alignment": "Left",
      "Image": "ViewLastImage",
      "OnClick": {
        "Executable": "MnuGoToLast",
        "Arguments": ""
      }
    }
  ]

```


![image](https://github.com/d2phap/ImageGlass/assets/3154213/b4261479-2e49-4bf2-9ee5-2d30c9bf2ba1)
