### ISSUE TITLE
Program doesn't remember its window's position when anchored

### ISSUE THREAD

**Issue by thericle** [d2phap/ImageGlass#1646]
### System information:
 - Windows OS version: 11 Pro 22621.2215
 - ImageGlass version: 9.0.5.726

Normally, when I close the program, the next time I open it, it remembers its last position. But when I anchor the program (let's say to the right half of the screen) and then close it, it doesn't save that particular position. Version 8.9.6.9 that I used until now didn't have this issue.

**Comment by BlepBlep** [comment]
Can confirm this happens with me as well, with 9.0 RC as well.

**Comment by d2phap** [comment]
Fixed in [ImageGlass 9.0.7.1125](https://github.com/d2phap/ImageGlass/releases/tag/9.0.7.1125)
