### ISSUE TITLE
Rotate functionality very difficult to use, please add shortcut button to rotate

### ISSUE THREAD

**Issue by addonaddict** [d2phap/ImageGlass#1648]
If im missing something, please guide me, as I could not figure it out myself:

ImageGlass version:
![image](https://github.com/d2phap/ImageGlass/assets/73442541/82407b6f-81ad-4e74-80b2-aabe244448b5)

### Is your feature request related to a problem? Please describe.
After looking through the settings and menus for an hour, I could not find a way to EASILY rotate my images on the fly.
I only found 2 ways:
1. navigate via menu (extremely slow for many photos)
2. Use shortcuts (unintuitive, and I will always forget them)

### Describe the solution you'd like
Add a button on the top menu that will rotate an image 90 degrees, similar to Microsoft Photos.
This button will apply only to selected photo.
After using Ctrl + S to save the photo, this photo should be saved in its rotated form for when I re-open it in future.

### Describe alternatives you've considered
None. An easy to use button is a must. All other methods are extremely user unfriendly.

### Additional context
![image](https://github.com/d2phap/ImageGlass/assets/73442541/388df9be-f7f9-4503-a74f-af27188e3df0)

**Comment by d2phap** [comment]
Currently, ImageGlass 9.0 beta 5 does not have UI for customizing toolbar buttons yet. You can add new buttons by editing `igconfig.json` file.

To add Rotate left/right buttons:
```json
  "ToolbarItems": [
    {
      "Type": "Button",
      "Id": "Btn_RotateLeft",
      "Text": "",
      "DisplayStyle": "Image",
      "CheckableConfigBinding": "",
      "Alignment": "Left",
      "Image": "RotateLeft",
      "OnClick": {
        "Executable": "MnuRotateLeft",
        "Arguments": ""
      }
    },
    {
      "Type": "Button",
      "Id": "Btn_RotateRight",
      "Text": "",
      "DisplayStyle": "Image",
      "CheckableConfigBinding": "",
      "Alignment": "Left",
      "Image": "RotateRight",
      "OnClick": {
        "Executable": "MnuRotateRight",
        "Arguments": ""
      }
    }
  ]
```


![image](https://github.com/d2phap/ImageGlass/assets/3154213/1d5bcdd3-f2a2-4945-91a7-eb2b5720f9e7)

**Comment by addonaddict** [comment]
Thank you I appreciate this.
When this comes out of beta, can we expect a rotate button added by default?
In my opinion, this is in the top 5 most useful features to have. Fiddling with toolbar customizations is good, but feels like multiple steps for an important basic feature.
Thanks again!

**Comment by kDylanHayes** [comment]
@d2phap This is a basic feature that we would like restored as functionality regressed since v8. Defaults should be user-friendly as only power users will change the UI
