### ISSUE TITLE
Multiple Pages in one TIF file

### ISSUE THREAD

**Issue by Chavenay** [d2phap/ImageGlass#1649]
### System information:
 - Windows OS version:  Windows Server 2022 Datacenter
 - ImageGlass version:  8.8.4.4 

### To Reproduce
1. Open TIF file with multiple pages
2. 
3. 
4. 

### Actual behavior:
The software only allows you to see the 1st page.

### Expected behavior:
how to see the following pages of the TIF file ?

**Comment by d2phap** [comment]
You can use shortcuts or the Page navigation tool:

![image](https://github.com/d2phap/ImageGlass/assets/3154213/baccf6c9-d258-4ed9-ac91-e00234642900)


![image](https://github.com/d2phap/ImageGlass/assets/3154213/531928f1-44cc-42da-b314-0b7694edab9f)
