### ISSUE TITLE
Wrong Filename Requested Against Case-Sensitive UNC/Mapped Network Share

### ISSUE THREAD

**Issue by wuffleton** [d2phap/ImageGlass#165]
I've recently discovered ImageGlass as a very viable alternative to Windows 10's built-in one, but I've discovered some weird behavior when using ImageGlass to view files on my network shares. All is well until I try to access any image whose name contains a capital letter. 

It appears some kind of normalizing is going on somewhere (like an extra `.ToLower()` where it shouldn't be) which will obviously not impact anything against a Windows host or Linux/Unix host with `case sensitive = no` on the server/share, but will completely break loading the image if the server is expecting the same case as the name on the filesystem and the underlying filesystem is also case-sensitive.

I found that the same set of files when copied to a folder on a local drive, would load without problem. After cranking up samba's logging, I noticed that I was getting a lot of blocks similar to the following when navigating through one of my problem folders using ImageGlass:
```unix_convert called on file "tumblr_nj7uzskncq1rritjco1_1280.png"
unix_convert begin: name = tumblr_nj7uzskncq1rritjco1_1280.png, dirpath = , start = tumblr_nj7uzskncq1rritjco1_1280.png
check_reduced_name: tumblr_nj7uzskncq1rritjco1_1280.png reduced to /home/wuffleton/tumblr_nj7uzskncq1rritjco1_1280.png
unix_mode: unix_mode(tumblr_nj7uzskncq1rritjco1_1280.png) returning 0600
open_file_ntcreate: FILE_OPEN requested for file tumblr_nj7uzskncq1rritjco1_1280.png and file doesn't exist.
```

In this case, I noticed that it is in fact `tumblr_nj7uzsKncQ1rritjco1_1280.png` when considering the casing on the source filesystem. This is the same name that ImageGlass displayed in the title bar, meaning that Windows and ImageGlass are clearly seeing the right name over the share.

As I regrettably lack the skill in C# to submit a patch myself, I'd be really appreciative if this could get fixed at some point!

**Comment by d2phap** [comment]
Hi @wuffleton ,

I will look into next few days.
I may need your help to check if it works correctly

Thanks

**Comment by d2phap** [comment]
Hi @wuffleton 

Here is a testing version with fixes, please help me confirm:
http://imageglass.org/upload/moon/ImageGlass_3.x_19032017.zip

**Comment by wuffleton** [comment]
I can confirm that the new build is now requesting the correct names against a case-sensitive share and properly handles capital letters in the path, filename, and/or extension. No more "Imageglass cannot open this picture" messages, and no name conversion errors in the server logs.

**Comment by d2phap** [comment]
Thanks @wuffleton
