### ISSUE TITLE
Expand/Contract Thumbnail panel

### ISSUE THREAD

**Issue by AnonymouZEE** [d2phap/ImageGlass#1650]
### Is your feature request related to a problem? Please describe.
Thumbnail bar are somewhat limited for folders with lots of files

### Describe the solution you'd like
A expand button "^" (contract button when expanded "v")
would expand the thumbnails to fill the client area
when the user double-click one it becomes the active image...
(single-click action only when is contracted 
to permit future functionality like multiple selection...
and a future a right-click context menu would be desirable also...)

**Comment by d2phap** [comment]
Hi @AnonymouZEE, please refer to my previous comment here https://github.com/d2phap/ImageGlass/issues/1629#issuecomment-1666695156
