### ISSUE TITLE
ImageGlass Kobe does not install for all users (or at least give option to)

### ISSUE THREAD

**Issue by GHM3434** [d2phap/ImageGlass#1651]
### System information:
 - Windows OS version: Windows 11 22h2
 - ImageGlass version: ImageGlass 8.9.6.9 msi installer

### To Reproduce
1. install the ImageGlass 8.9.6.9 msi installer
2. No option to install for all users on the computer
3. ImageGlass is only installed on the one user

### Actual behavior:

Only installs imageglass on the one specific user account that installed the app.

### Expected behavior:

Install for all users on the pc or at least give the option to install for all users.

**Comment by d2phap** [comment]
Probably close this https://github.com/d2phap/ImageGlass/issues/1708#issuecomment-1833864550
