### ISSUE TITLE
Hitting save when cropping triggers a "save as" operation instead, 

### ISSUE THREAD

**Issue by pmcstjean** [d2phap/ImageGlass#1654]
### System information:
 - Windows OS version: Windows 10
 - ImageGlass version: bug is happening in 8.9.6.9 and 8.8.4.4

### To Reproduce
1. Open any image (PNG)
2. Hit 'C' to start cropping
3. Hit the save button

### Actual behavior:
It opens a 'save as' window

### Expected behavior:
It should save in the current file (it is not readonly)

### Additional context:
I uninstalled and rolled back to 8.6.7.13 and it works in that version and previous. Didn't try 8.7.11.6 but I tried in the latest 2 versions and the bug is present.

**Comment by d2phap** [comment]
Hi @pmcstjean, please refer to https://github.com/d2phap/ImageGlass/issues/1614#issuecomment-1658320811
