### ISSUE TITLE
Suggestion: Invert Scroll Wheel Navigation Directon

### ISSUE THREAD

**Issue by wuffleton** [d2phap/ImageGlass#166]
As it stands - ImageGlass uses scroll-up to navigate to the next image, and scroll-down to navigate to the previous image. However, most other image viewers implement the opposite behavior - Up-Previous, Down-Next (like scrolling through a web page). 

It would be great if we could get a tickbox in settings to invert the scroll wheel direction for navigation (or even ship this as the default) to make it easier for users of other image browsing software to seamlessly make the switch to ImageGlass.

**Comment by d2phap** [comment]
Hi @wuffleton 

Thanks for the feedback. 
This is exact duplicated to #151 and is implemented in the next release.
