### ISSUE TITLE
Recursive rendering/reading of images

### ISSUE THREAD

**Issue by AutomationBoi** [d2phap/ImageGlass#1660]
I just thought about the below feature... If this does not make sense please do let me know

Currently we can view all the images inside one folder, it will be a good feature if we can just give the root directory and it will pick all the image files in all sub directories.

This can result in very slow execution in some cases yes but in most cases it will be good feature. Like users can see slideshow of their kids/vacations etc. together rather than selecting the folder manually every time.

This can help us to enhance our scope and become image editor+ image viewer tool.

**Comment by d2phap** [comment]
You can enable it in the Settings > Image:

### for v8.x
![image](https://github.com/d2phap/ImageGlass/assets/3154213/e6b8c290-4dec-4561-9232-b2b1ef4dc132)

### for v9.0 beta 5
![image](https://github.com/d2phap/ImageGlass/assets/3154213/3b90bc8e-441f-4fed-8b0c-f98ff9286dd6)

**Comment by AutomationBoi** [comment]
Thanks a lot for letting me know... I was not sure it was already available... Thanks again
