### ISSUE TITLE
On Magick.NET SVG rendering errors: Magick.NET developer says the library they use does not support all SVG syntaxes

### ISSUE THREAD

**Issue by Yukai-Qian** [d2phap/ImageGlass#1662]
This issue is reported before: #1625 
And I submitted an issue to Magick.NET: https://github.com/dlemstra/Magick.NET/issues/1450
However, based on their reply:
> It seems that this SVG file is using a compact version of paths and this doesn't seem to be supported by the library that ImageMagick is using to read svg files. Maybe ImageGlass should change expands the paths before handing it to Magick.NET?

It does not seem like they are able to solve this issue due to an upstream library.

Could ImageGlass maybe fully migrate to WebView2 for 9.0?

### System information:
 - Windows OS version: Windows 11
 - ImageGlass version: 8.10.9.27 & 9.0 beta 5

### To Reproduce
1. Open the following SVG file with ImageGlass:
```svg
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 512 512">
  <defs/>
  <circle cx="256" cy="256" r="256" fill="#2D323B"/>
  <circle cx="256" cy="256" r="24" fill="#CB81DA"/>
  <path fill="#CB81DA" fill-rule="evenodd" d="M165 170c4 32 16 72 38 113 21 42 46 76 70 97 12 11 24 18 34 22s18 3 24 0c5-3 10-9 13-18 3-10 3-23 2-38-3-31-14-69-34-109a6 6 0 0111-5c20 41 32 81 35 113 1 16 1 30-3 42-3 11-9 21-19 26s-22 4-34 0c-11-4-24-13-37-24-25-23-51-58-73-100s-35-84-39-118c-2-17-1-32 2-44s9-22 20-27c9-6 21-5 33-1 11 5 24 13 36 24a6 6 0 01-8 9c-11-11-23-18-32-21-10-4-18-4-24-1s-11 10-13 20c-3 10-4 24-2 40z" clip-rule="evenodd"/>
  <path fill="#CB81DA" fill-rule="evenodd" d="M100 268c6 7 16 14 29 20a6 6 0 01-5 11c-14-7-25-14-33-23-8-8-12-18-12-29 1-11 7-21 17-29s23-14 39-20c33-10 76-15 124-13 47 2 90 12 121 26 16 7 29 15 38 23 8 9 14 20 13 31 0 10-6 20-14 27-9 8-20 14-34 19a6 6 0 11-5-11c14-5 24-10 31-17 7-6 10-12 10-19 1-6-2-14-10-21-7-8-19-15-34-21-29-13-70-23-117-25-46-2-88 3-119 13-15 5-27 11-35 18-9 6-12 13-13 20 0 6 3 13 9 20z" clip-rule="evenodd"/>
  <path fill="#CB81DA" fill-rule="evenodd" d="M189 396c10-3 22-9 35-18a6 6 0 116 10c-13 10-26 16-38 19s-24 2-33-4-14-16-16-29c-2-12-1-28 2-44 8-33 26-73 52-113s56-72 84-92c13-9 27-16 39-19 12-4 24-3 34 3 9 6 14 17 16 29 2 13 1 28-3 44a6 6 0 01-12-2c4-16 5-29 3-40-2-10-5-17-11-21s-14-4-24-2c-10 3-22 9-35 18-26 19-56 50-81 89-26 38-43 77-50 109-3 15-4 29-3 39 2 11 6 18 12 21 5 4 13 5 23 3z" clip-rule="evenodd"/>
</svg>
```
https://user-images.githubusercontent.com/100383998/272665900-1dff3fb1-c1ad-4057-bb3b-2ccd3351d78b.svg

### Actual behavior:

On 8.10.9.27, it is rendered as
![272664143-e94f4e06-1ea3-4975-914f-ee402dee8077](https://github.com/d2phap/ImageGlass/assets/100383998/87328d1c-12a9-4948-8899-c50b2702d6a9)
On 9.0 Beta 5, the image is correctly rendered thanks to WebView 2, but its thumbnail, still rendered with Magick.NET, is the same as above.
![image](https://github.com/d2phap/ImageGlass/assets/100383998/d5207aad-e0ce-4445-96a1-e97fd82fca31)

### Expected behavior:

It should be rendered as
![272663572-7f2d19d8-dcfb-4f07-b9cc-222a5633ca9b](https://github.com/d2phap/ImageGlass/assets/100383998/0af1ac1e-3c07-4f81-822e-cdb18cb0dfc6)

### Screenshots:

See above.

**Comment by d2phap** [comment]
Hi @Yukai-Qian 

The thumbnails are just quick preview of the images, it is not always correct. The current SVG viewer in v9.0 has limited functions and is an opt-out feature, it means the app will still work if Webview2 is not installed on their machine.

I have no plan to support Webview2 engine in the Gallery component.
