### ISSUE TITLE
Select dialog buttons with arrow keys

### ISSUE THREAD

**Issue by xmha97** [d2phap/ImageGlass#1663]
Hi, on Windows Explorer, I can select dialog buttons with arrow keys

https://github.com/d2phap/ImageGlass/assets/23485114/5cba24f4-476b-4f25-a152-e282a87a16ce

I need this feature for ImageGlass.

![image](https://github.com/d2phap/ImageGlass/assets/23485114/e23a43cb-bb83-4095-8c57-b5c759b97577)

You should set the tab stop for the **Yes** button to **0**
and for the **No** button to **1**

**Comment by d2phap** [comment]
Fixed this in v9.0.11
