### ISSUE TITLE
Make it possible to disable thumbnail caching completely

### ISSUE THREAD

**Issue by thericle** [d2phap/ImageGlass#1666]
I'm the same person who created this issue: https://github.com/d2phap/ImageGlass/issues/1647. 2/3 issues I mentioned there are now solved, and thank you for that. The 3rd issue is semi-solved. I feel there should be a better way to disable thumbnail caching completely, instead of just deleting any thumbnails created after the app is closed.

Maybe there is a way for whatever function creates the thumbnails, to do it only if the cache is set to > 0.
Kind of like:
```
if thumbnailsCache > 0:
    create thumbnails
```

It's probably not that simple. Anyway, this issue is less important than the issues in the original post, so feel free to ignore it if you think it's unnecessary but I still wanted to mention it.

**Comment by d2phap** [comment]
Thanks @thericle, as mentioned in https://github.com/d2phap/ImageGlass/issues/1647#issuecomment-1751723491, the cache is necessary to maintain its smooth operation. That's just it at least for now, I may check again in the future if I can do further more.

**Comment by miaLDN** [comment]
This is a no-go for me; that and also logging last file viewed.
I removed permission from `%LOCALAPPDATA%\ImageGlass\ThumbnailsCache` but ImageGlass behaves weird.  I don't need or want a thumbnail viewer - just a simple viewer.

Application needs privacy settings, and consideration.
