### ISSUE TITLE
Add a smooth zoom animation

### ISSUE THREAD

**Issue by PoloniumRain** [d2phap/ImageGlass#1668]
Now that 9.0 supports GPU rendering it should be possible to have very smooth zooming. For example, in the Windows Photos app there's a very smooth animation when zooming in/out, where as IG just does it instantly in steps with no animation. 

But there's a problem with the way the Photos app does it - The animation is too slow, so it feels a little unresponsive and not precise. It would be good if IG implemented a similar smooth zooming animation but sped it up by at least 50%. This way it will remain very useable and snappy while also looking good. Obviously there would also be a way to disable/enable this feature in the Settings, and maybe even have a setting to adjust the animation speed.

**Comment by d2phap** [comment]
I'm not a fan of zoom animation for mouse wheel / touchpad because it does not feel natural.
Currently with v9, if you use touchpad, the zoom is very smooth because the zoom step (delta value) is small.

Also, if you zoom in/out using the menu or hotkey, I already implemented the smooth zoom animation because this is non-continuous action.

**Comment by PoloniumRain** [comment]
Ah yeah, i see the toolbar buttons have this animation. 

Well i hope you consider adding an option to enable a similar animation behaviour when using the mouse wheel. I think it doesn't feel natural because most photo apps, and even photo editing software like Photoshop, do it too slowly like the Windows Photos app. Like i said before, if it was sped up it would feel way better. But i think it would require quite a bit of tweaking to get it feeling just right, so i understand if this isn't a priority.

**Comment by d2phap** [comment]
I will just close this because I think it's really not necessary.
