### ISSUE TITLE
Color profile setting is not saved with 9.0 RC

### ISSUE THREAD

**Issue by PoloniumRain** [d2phap/ImageGlass#1669]
### System information:
 - Windows OS version: 10 Pro
 - ImageGlass version: 9.0 RC with .NET 8

### To Reproduce
1. Go to Settings > Image.
2. Set the 'Color profile' to any option.
3. Click Apply and close IG.
4. Re-open IG and this setting will not be saved.

I know this is possibly happening because it simply hasn't been implemented yet, but just letting you know.

**Comment by d2phap** [comment]
Fixed in [ImageGlass 9.0.7.1125](https://github.com/d2phap/ImageGlass/releases/tag/9.0.7.1125)
