### ISSUE TITLE
Icon set for file association not showing

### ISSUE THREAD

**Issue by CPS2Evolved** [d2phap/ImageGlass#1672]
### System information:
 - Windows OS version: 10.0.19045 Build 19045 (Clean install)
 - ImageGlass version: ImageGlass_Kobe_8.10.9.27_x64

### To Reproduce

1. Copy contents of "Ext-Icons" to "C:\Users\{name}\AppData\Local\Programs\ImageGlass\Ext-Icons\" (according to README.MD).

Added note: Programs\ImageGlass was non-existent after installing and running ImageGlass, so I had to manually add it.

2. Set ImageGlass as default photo viewer.

![Capture3](https://github.com/d2phap/ImageGlass/assets/78268472/bd4d5467-91f0-4544-83c6-05fd15303563)

### Actual behavior:
Icon set not showing on common image files (jpg, png, webp), the default icon set is persistent. it does show on the .ico file type, so far.

![Capture5](https://github.com/d2phap/ImageGlass/assets/78268472/2b517a9e-01ed-4dae-9da9-3fa3452e96ce)

### Expected behavior:
Enforce the icon set to be applied to associated file types, preferably through the options menu of ImageGlass (import icon pack?).
Cleanup of wrongly registered icons, see below.

### Additional context:

Some start menu icons are confused.
 
![Capture4](https://github.com/d2phap/ImageGlass/assets/78268472/ecf2c749-b32e-4b60-b177-e9c3f08fbb99)

**Comment by d2phap** [comment]
After changing the icon files, you will need to open ImageGlass settings > File type associations, click on "Set as default photo viewer" button
