### ISSUE TITLE
[9.0 RC] Custom theme doesn't load

### ISSUE THREAD

**Issue by maphapthieunu** [d2phap/ImageGlass#1673]
### System information:
 - Windows OS version: Windows 11 Version 23H2 (22635.2483)
 - ImageGlass version: 9.0.6.1008 (64-bit)

### To Reproduce
1. Open ImageGlass
2. Open Settings dialog
3. Switch to the Appearance tab
4. Download and install a custom theme

### Actual behavior:

When I install a custom theme into ImageGlass, it does not show up in the 'Theme' list (although the theme files are in the folder). Tried changing the `configversion` in the igtheme.xml file to '9' and  `DarkTheme` in the configuration file to "Fluent".

### Expected behavior:

The theme shows up correctly in the 'Theme' list.

### Screenshots:

![](https://i.imgur.com/AfF6yRx.png)

### Additional context:

Or maybe the theme isn't even compatible.

**Comment by d2phap** [comment]
FYI, the current theme packs on the website are not compatible with v9.0. I will update docs for v9.0 at https://github.com/imageGlass/theme

**Comment by d2phap** [comment]
I have updated some theme packs for v9.0 support: https://imageglass.org/themes
For official guideline, see this announcement: https://github.com/ImageGlass/Theme/issues/12
