### ISSUE TITLE
Setting ImageGlass as image viewer by default

### ISSUE THREAD

**Issue by rocobruno** [d2phap/ImageGlass#1674]
### Additional context

Feature or modification requested

Can it be possible to let any standard users set ImageGlass as the default image viewer ? Right now anytime a standard user want to set ImageGlass as it's default image viewer it requires administrative credentials. Thank you !

**Comment by d2phap** [comment]
Hi @rocobruno, this is already implemented in v9.0 RC

**Comment by rocobruno** [comment]
Oh I see, thanks. Can't wait for that major release. Keep up the good work!
