### ISSUE TITLE
Zoomed images getting reset to actual size while saving files to the same location as the image being loaded

### ISSUE THREAD

**Issue by otmeek** [d2phap/ImageGlass#168]
Ok so I'm not exactly sure what's causing this. I have ImageGlass displaying an image, zoomed in, on a second monitor while using Photoshop. Everytime I perform a save operation in Photoshop by pressing CTRL+S, ImageGlass resets the image view to actual size.

After a bit of testing, I determined that this only happens when saving to the same location as the image being loaded in ImageGlass. I saved some text files to the same location using notepad, and these cause the image to reload as well but don't cause it to reset to its actual size. It seems only Photoshop is triggering this behaviour.

Can easily be worked around by saving my reference images to a different directory than the one I store my .psd's in, but I thought I'd report it,

**Comment by d2phap** [comment]
Hi @otmeek 

This behaviour is because ImageGlass triggers and reloads the image whenever user makes change on it.
I will tag it as a suggestion.

Thanks,
Phap

**Comment by d2phap** [comment]
This suggestion is implemented.

Please be noted that ImageGlass will refresh the viewing image with the the same zooming state only if:
- The viewing image file is **_modified_** (by third-party app). 

Some third-party apps **_delete_** the file from hard disk before saving image. This will be treated as **_Delete_** and  **_Create_** which are not supported to remain the zooming state.
