### ISSUE TITLE
Skip First Launch-Configuration on Windows 10 22H Multisession for Default ALL Users

### ISSUE THREAD

**Issue by MarioZVGL** [d2phap/ImageGlass#1680]
### System information:
 - Windows OS version: Windows 10 22H Multisession for Azure Virtual Desktop
 - ImageGlass version: 8.10.9.27

### To Reproduce
1. Would likt to skip the Start Window because we want ImageGlass as default Photoviewer für all Users in our environment (90 Users)
2. Every User is working on AVD Multisession
3. Found old article with sets it via Regedit for Local User (HKEY_Current_User)
4. But need it for all Users (HKEY_Local_Machine) because it is multiuser-system

Is this possible?

Thanks!

**Comment by MarioZVGL** [comment]
https://github.com/d2phap/ImageGlass/issues/365#issuecomment-400250985

- This was the article i found

**Comment by d2phap** [comment]
ImageGlass supports overriding user configs, please see details at: https://imageglass.org/docs/app-configs.

## For v8.x
You can create `igconfig.default.xml` (or `igconfig.admin.xml`) file and deploy it to the installed folder of ImageGlass, with this content:

```xml
<ImageGlass>
  <Configuration>
    <Info description="ImageGlass Configuration file" version="7.5" />
    <Content>
      <Item key="FirstLaunchVersion" value="6" />
    </Content>
  </Configuration>
</ImageGlass>
```

Setting `FirstLaunchVersion` to a value that is greater than `5` will suppress the First-launch Configuration dialog.


## For v9.0 RC or later
ImageGlass 9.0 uses JSON format to store user setting, so it will be `igconfig.json`, `igconfig.default.json` and `igconfig.admin.json`.

```json
{
  "_Metadata": {
    "Description": "ImageGlass configuration file",
    "Version": "9.0"
  },
  "QuickSetupVersion": 9
}
```

Setting `QuickSetupVersion` to a value that is greater than `9` will suppress the Quick Setup dialog.

**Comment by MarioZVGL** [comment]
This worked for me and helped me a lot thank you!
