### ISSUE TITLE
Please add support to Panasonic DC-S5M2 RAW file RW2

### ISSUE THREAD

**Issue by green-forg** [d2phap/ImageGlass#1684]
Really wish that S5M2 can be supported, currently it is just a pink mess -_-
<img width="1280" alt="image" src="https://github.com/d2phap/ImageGlass/assets/65800174/41403cc7-16a4-4d5a-9e1c-64d19732d805">

**Comment by d2phap** [comment]
@green-forg  Can you send the file?
