### ISSUE TITLE
Settings Panel Does Not Work (Version 9 Beta 5 and now RC)

### ISSUE THREAD

**Issue by mojoZHU** [d2phap/ImageGlass#1685]
### System information:
 - Windows OS version: Windows 11 Pro 22H2 (computer joined to Active Directory domain with group policy etc.)
 - ImageGlass version: 9 Release Candidate (.NET 7 and 8 versions tried)

### To Reproduce
1. Extract Zip
2. Finish first setup
3. Open settings panel

### Actual behavior:
The Settings panel does not seem to function at all. The settings are blank, the dropdown boxes contain nothing, settings don't save and the links don't do anything when clicked. There is a igconfig.json file in the root folder

### Expected behavior:
Settings panel with working links, dropdowns, ability to save

### Screenshots:
![Screenshot 2023-11-02 121522](https://github.com/d2phap/ImageGlass/assets/83429154/2c0d20b2-2b22-4bcd-b7bb-b9f1b5114c49)

### Additional context:
I raised this issue for the last Beta as well, and I was asked to confirm that the About window and Update windows are both working and they both still are. The links on these windows definitely work.

**Comment by d2phap** [comment]
Hi @mojoZHU 

Please open the `igconfig.json` of v9.0 RC, set `EnableDebug` to `true`, and then run ImageGlass 9.0 RC, go to Settings, press Ctrl+Shift+I to open the DevTool, click on the "Console" tab. There should be some errors. Please help me expand the errors, copy and paste it here!

![image](https://github.com/d2phap/ImageGlass/assets/3154213/afd0d959-77df-44cb-a5ba-e787a03bde83)

Also, can you tell me what folder did you extract ImageGlass to? Does it have the write permission?

Thanks

**Comment by mojoZHU** [comment]
Hi @d2phap

I have done what you said, but there were no errors on the console. I think I have found the problem though and it is the directory it is installed in.

So I have tried the following directories. I am logged in as an administrator and I did try "Run as Administrator" for all folders:

- "D:\ImageGlass 9 RC" - This folder works
- "E:\ImageGlass 9 RC" - This folder works
- "E:\OneDrive\ImageGlass 9 RC" - This folder works
- "E:\OneDrive\Tigers Toolbox\ImageGlass 9 RC" - This folder works
- "E:\OneDrive\Tiger's Toolbox\ImageGlass 9 RC" - This folder does NOT WORK
- "E:\OneDrive\Test This ' Apostrophe\ImageGlass 9 RC" - This folder does NOT WORK

I think the problem is the "'" (apostrophe) in the folder name. This character could be causing an issue.

I have checked the write permissions for these folders and that should be fine, they are all new folders made by my user today.

Let me know if I can provide any more information.

**Comment by d2phap** [comment]
Thanks @mojoZHU 
I managed to reproduce it. It cause by the `'` in the path.

**Comment by mojoZHU** [comment]
Okay cool :)

**Comment by d2phap** [comment]
Fixed in [ImageGlass 9.0.7.1125](https://github.com/d2phap/ImageGlass/releases/tag/9.0.7.1125)
