### ISSUE TITLE
Labels of checkboxes are not clickable in the installer

### ISSUE THREAD

**Issue by Anton-V-K** [d2phap/ImageGlass#1686]
### System information:
 - Windows OS version: Windows 10 64-bit
 - ImageGlass version: 8.10.9.27

### To Reproduce
1. Start the installation.
2. At the last page try to click on the labels next to checkboxes.

### Actual behavior:
Labels of the checkbox ignore mouse clicks, and the user have to precisely click inside the checkbox square

### Expected behavior:
Left-mouse click on the checkbox label should toggle the corresponding checkbox.

### Screenshots:
![image](https://github.com/d2phap/ImageGlass/assets/20116984/c4ac8da2-64c7-4b46-be3e-3d42a04671cf)

**Comment by d2phap** [comment]
It's the Express version of AdvancedInstaller, I cannot fix that
