### ISSUE TITLE
High Resolution Image File not working on i5-650 PC - Graphics Driver Issue with [ImageGlass v9 RC]

### ISSUE THREAD

**Issue by ghost** [d2phap/ImageGlass#1687]
Refrance to this https://github.com/d2phap/ImageGlass/discussions/1665#discussioncomment-7309553

High Resolution Image not working on My PC's Graphics Driver (Integrated Graphics)

What I notice?
1. Yesterday I try This in VMware on Same PC & the Same Image File Working..

2. Today I Re-install Windows 10 on My PC, and Try without any Driver & Software installed (only .net7 & webview2).. and the Image File working correctly..

3. But after install Display Driver, The Image File didn't work.... Try to uninstall Display Driver, Image File works..

(Note: Display Driver is Latest & Installed from Windows Update)

Note2: with ImageGlass8, it's always Working....

PC Specs:
Processor: i5-650 (1st Generation)
RAM: 4GB
OS: Windows 10 22H2 (64 bit)

For your Investigation: I put the Driver ZIP file Here. [Graphics Driver.zip](https://github.com/d2phap/ImageGlass/files/13325506/Graphics.Driver.zip)

![Problem](https://github.com/d2phap/ImageGlass/assets/120308983/1361a62e-88f1-4361-8d5f-f678efb85b1b)

**Comment by d2phap** [comment]
I tried to reproduce with Win10 22h2 64bit in VirtualBox but also could not reproduce. I could not install your driver, too.
![image](https://github.com/d2phap/ImageGlass/assets/3154213/6e4a0de9-2989-40ba-80bc-2a234cd82c83)

**Comment by ghost** [comment]
@d2phap i says above

My same pc > VMware > not have issues (also VMware tools)

**Problem Only happened in my actual (real) pc** & when driver are installed.. without driver not issue... I mean some conflict/problem of driver..

-  This is only display driver available for my pc (didn't find older version)

 - But same driver, imageglass8 work fine...

.
.
.
One more thing, In **[ImageGlass 9 beta 1](https://github.com/d2phap/ImageGlass/releases/tag/9.0.1.514)**

When try to opened image, image open in this version but automatically hide..

See this screen-recording **(v9 beta1)**


https://github.com/d2phap/ImageGlass/assets/120308983/81a5659f-fab4-4c78-be60-31a0282c9906

**Comment by d2phap** [comment]
It seems that the only way to reproduce the issue is having a laptop as same as yours. I am unable to do it with my devices so I cannot fix this.

ImageGlass 9 beta 1 is the first beta so it's very unstable. Moreover, the rendering engine was replaced in v9.0 beta 2.

**Comment by 1234G-G4321** [comment]
Only Beta1 able to open, but automatically hide

& From v beta2, screen blank with text "Loading..."

Also, I send driver file not for installing, I know it's not possible to install other PC's drivers..
I send for investigation purpose...

.
.
.
.
.
One more:
1. I'm disable Display driver (from Device Manager)
2. Open imageglass RC & it's working
3. I stay imageglass open
4. Now I'm enable driver & imageglass crash (not happened in v8)

![IMG-20231113-WA0000](https://github.com/d2phap/ImageGlass/assets/120308983/4bf0b696-3296-4fb5-a3ce-3123d6b3955e)

```
Version: ImageGlass v9.0.6.1008
Release code: moon
OS: Microsoft Windows NT 10.0.19045.0 64-bit

----------------------------------------------------
Error:

A valid display state could not be determined.
----------------------------------------------------

System.ComponentModel.Win32Exception (0x88990006): A valid display state could not be determined.
   at DirectN.ID2D1RenderTargetExtensions.Resize(ID2D1HwndRenderTarget renderTarget, D2D_SIZE_U size)
   at D2Phap.DXControl.OnResize(EventArgs e) in D:\_GITHUB\@d2phap\DXControl\Source\DXControl\DXControl.cs:line 325
   at ImageGlass.Viewer.DXCanvas.OnResize(EventArgs e) in D:\_GITHUB\@d2phap\ImageGlass\v9\Components\ImageGlass.Views\DXCanvas.cs:line 1424
   at System.Windows.Forms.Control.OnSizeChanged(EventArgs e)
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
   at System.Windows.Forms.Control.UpdateBounds()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at D2Phap.DXControl.WndProc(Message& m) in D:\_GITHUB\@d2phap\DXControl\Source\DXControl\DXControl.cs:line 313
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

**Comment by 1234G-G4321** [comment]
@d2phap

Only Beta1 able to open, but automatically hide

& From v beta2, screen blank with text "Loading..."

Also, I send driver file not for installing, I know it's not possible to install other PC's drivers..
I send for investigation purpose...

.
.
.
.
.
One more:
1. I'm disable Display driver (from Device Manager)
2. Open imageglass RC & it's working
3. I stay imageglass open
4. Now I'm enable driver & imageglass crash (v8 not crash, only v9 crash)

![IMG-20231113-WA0000](https://github.com/d2phap/ImageGlass/assets/120308983/4bf0b696-3296-4fb5-a3ce-3123d6b3955e)

```
Version: ImageGlass v9.0.6.1008
Release code: moon
OS: Microsoft Windows NT 10.0.19045.0 64-bit

----------------------------------------------------
Error:

A valid display state could not be determined.
----------------------------------------------------

System.ComponentModel.Win32Exception (0x88990006): A valid display state could not be determined.
   at DirectN.ID2D1RenderTargetExtensions.Resize(ID2D1HwndRenderTarget renderTarget, D2D_SIZE_U size)
   at D2Phap.DXControl.OnResize(EventArgs e) in D:\_GITHUB\@d2phap\DXControl\Source\DXControl\DXControl.cs:line 325
   at ImageGlass.Viewer.DXCanvas.OnResize(EventArgs e) in D:\_GITHUB\@d2phap\ImageGlass\v9\Components\ImageGlass.Views\DXCanvas.cs:line 1424
   at System.Windows.Forms.Control.OnSizeChanged(EventArgs e)
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
   at System.Windows.Forms.Control.UpdateBounds()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at D2Phap.DXControl.WndProc(Message& m) in D:\_GITHUB\@d2phap\DXControl\Source\DXControl\DXControl.cs:line 313
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

**Comment by ghost** [comment]
@d2phap

Only Beta1 able to open, but automatically hide

& From v beta2, screen blank with text "Loading..."

Also, I send driver file not for installing, I know it's not possible to install other PC's drivers..
I send for investigation purpose...

.
.
.
.
.
One more:
1. I'm disable Display driver (from Device Manager)
2. Open imageglass RC & it's working
3. I stay imageglass open
4. Now I'm enable driver & imageglass crash (v8 not crash, only v9 crash)

![IMG-20231113-WA0000](https://github.com/d2phap/ImageGlass/assets/120308983/4bf0b696-3296-4fb5-a3ce-3123d6b3955e)

```
Version: ImageGlass v9.0.6.1008
Release code: moon
OS: Microsoft Windows NT 10.0.19045.0 64-bit

----------------------------------------------------
Error:

A valid display state could not be determined.
----------------------------------------------------

System.ComponentModel.Win32Exception (0x88990006): A valid display state could not be determined.
   at DirectN.ID2D1RenderTargetExtensions.Resize(ID2D1HwndRenderTarget renderTarget, D2D_SIZE_U size)
   at D2Phap.DXControl.OnResize(EventArgs e) in D:\_GITHUB\@d2phap\DXControl\Source\DXControl\DXControl.cs:line 325
   at ImageGlass.Viewer.DXCanvas.OnResize(EventArgs e) in D:\_GITHUB\@d2phap\ImageGlass\v9\Components\ImageGlass.Views\DXCanvas.cs:line 1424
   at System.Windows.Forms.Control.OnSizeChanged(EventArgs e)
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
   at System.Windows.Forms.Control.UpdateBounds()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at D2Phap.DXControl.WndProc(Message& m) in D:\_GITHUB\@d2phap\DXControl\Source\DXControl\DXControl.cs:line 313
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

**Comment by ghost** [comment]
> It seems that the only way to reproduce the issue is having a laptop as same as yours. I am unable to do it with my devices so I cannot fix this.

Hey @d2phap 

If you need to check/test/finding issues/investigate

I will give you access to my PC **via AnyDesk** (if you want)

From:
7:15pm to 8:45pm (Indian Time)
1:45pm to 3:15pm (GMT)
& Sometime when my PC is ON

**Comment by mirh** [comment]
When you have just the basic display driver, windows relies WARP to run UI applications. 
Once you set up the gpu instead, that's what you use. And Ironlake just had direct3d 10_0 support. 

Now (putting aside that you are 93 minor build numbers below the [latest](https://retrosystemsrevival.blogspot.com/2019/11/quantic-driver-10-r2-intel-hd-1000.html) one) I would suppose that may not play nice with whatever newer library that is used here. 
Imageglass uses [`D2D1_FEATURE_LEVEL_DEFAULT`](https://learn.microsoft.com/en-us/windows/win32/api/d2d1/ne-d2d1-d2d1_feature_level) which should still be fine there, but I wonder if [directwrite](https://github.com/smourier/WicNet/issues/3) or something else in [DirectN](https://github.com/smourier/DirectN) couldn't be the culprit (even though I reckon this is supposed to still be fine with d3d9 too). 

We might bang our head on our walls here then, but if you have a legit regression range between beta 1 and RC (v8 vs v9 would surely be too much) then it seems relatively easy for you to blindly bisect. 

EDIT: presumably other people could try to reproduce the issue with arbitrary feature levels in [WARP](https://www.gamedev.net/forums/topic/697324-how-to-use-directx-control-panel/)

**Comment by ghost** [comment]
@mirh as you mention [this](https://retrosystemsrevival.blogspot.com/2019/11/quantic-driver-10-r2-intel-hd-1000.html), is not work for Windows10
for windows 10, the is working driver directly from Windows Update: [Link](http://download.windowsupdate.com/msdownload/update/driver/drvs/2013/04/200000263_dcb0607954adad6f676a8ee3f8e57a10b239e9dd.cab)

also, @d2phap , see abow @mirh replay, hope this will help to something idea to reproduce.

**Comment by mirh** [comment]
This is just a hypothesis really (and as I said, there's also some blind "check and try" job that you could do yourself)

p.s. try [this](http://www.mediafire.com/file/70qg07qtlyn14oc/Quantic+x64+-+%5BR2%5D-+Rebranded.7z) or [this](https://www.mediafire.com/file/ycta4vzrxvitia3/PHDGD+Quantc+C3+%2864Bit%29.7z) then

**Comment by ghost** [comment]
@mirh manage to installed successfully, but imageglassRCv9 still didnt work for HR Images
![Screenshot (262)](https://github.com/d2phap/ImageGlass/assets/120308983/c50c1b68-fefa-45b8-a622-b8268adfc5ba)

**Comment by mirh** [comment]
Ok so, here's what I get when I set the feature level below 11_0 in dxcpl (btw [this](https://download.visualstudio.microsoft.com/download/pr/b280d97f-25a9-4ab7-8a12-8291aa3af117/a37ed0e68f51fcd973e9f6cb4f40b1a7/windowsdesktop-runtime-8.0.0-win-x64.exe) is the last version of the net8 runtime I have installed)
```
Version: ImageGlass v9.0.6.1008
Release code: moon
OS: Microsoft Windows NT 10.0.19045.0 64-bit

----------------------------------------------------
Error:

The specified device interface or feature level is not supported on this system.
----------------------------------------------------

System.ComponentModel.Win32Exception (0x887A0004): The specified device interface or feature level is not supported on this system.
   at DirectN.HRESULT.ThrowOnError(Boolean throwOnError)
   at DirectN.ID2D1RenderTargetExtensions.EndDraw(ID2D1RenderTarget renderTarget)
   at D2Phap.DXControl.WndProc(Message& m) in D:\_GITHUB\@d2phap\DXControl\Source\DXControl\DXControl.cs:line 293
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```
It's not exactly the same to be fair, though at the same time it's not even monumentally different. 

What does your dxdiag display info says?

**Comment by ghost** [comment]
@mirh @d2phap 

DXDIAG - Intel HD Graphics **Driver: Enable** (Imageglass HR* Image Not Working)
![Screenshot (276)](https://github.com/d2phap/ImageGlass/assets/120308983/fcd07295-3f33-4f76-ac42-cc9ee5aa0cf9)
.
.
.
DXDIAG - Intel HD Graphics **Driver: Disable** (Imageglass HR* Image Working)
![Screenshot (275)](https://github.com/d2phap/ImageGlass/assets/120308983/406f3064-df9f-42fb-a931-7f8357e0d7e8)
.
.
.

_Footnote: HR=High Resolution_

**Comment by mirh** [comment]
Does imageglass improve if you use [dxcpl](https://learn.microsoft.com/en-us/windows/uwp/gaming/use-the-directx-runtime-and-visual-studio-graphics-diagnostic-features) to disable feature level upgrade or force WARP?
And what does the `dotnet --list-runtimes` command says?

**Comment by 1234G-G4321** [comment]
@d2phap @mirh ,
**Imageglass HR Image Working, when Force WARP ON**

![ImageGlassHRImageWORKING](https://github.com/d2phap/ImageGlass/assets/120308983/874b2f16-e190-41a4-ad51-9543a4761edd)


```
C:\Users\Windows10>dotnet --list-runtimes
Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by 1234G-G4321** [comment]
@d2phap @mirh ,
**Imageglass HR Image Working, when Force WARP ON**

![ImageGlassHRImageWORKING](https://github.com/d2phap/ImageGlass/assets/120308983/874b2f16-e190-41a4-ad51-9543a4761edd)


```
C:\Users\Windows10>dotnet --list-runtimes
Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by ghost** [comment]
@d2phap @mirh ,
**Imageglass HR Image Working, when Force WARP ON**

![ImageGlassHRImageWORKING](https://github.com/d2phap/ImageGlass/assets/120308983/874b2f16-e190-41a4-ad51-9543a4761edd)


```
C:\Users\Windows10>dotnet --list-runtimes
Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by d2phap** [comment]
Thanks for the investigation. I'm currently taking a break and won't be able to check further.
This seems to me your issue causes by the specific driver, I'm not sure. There is nothing I can do for now.

**Comment by mirh** [comment]
Is there d2d-d3d [surface sharing](https://learn.microsoft.com/en-us/windows/win32/direct2d/direct2d-and-direct3d-interoperation-overview) or something going on? After some extra scavenging, it seems that could create some sketchy-yet-not-immediate problem. 

Also, was it meant for a [variable](https://github.com/d2phap/DXControl/blob/3.0.1/Source/DXControl/DXControl.cs#L128) to be named *_useHardwar****d****Acceleration*? How can you toggle it at runtime?

**Comment by ghost** [comment]
@mirh I don't have technical/programing knowledge, so not understand your previous reply... @d2phap this above quote should help you!

also, currently I switch back to Imageglass8 as Main application & Imageglass9 as only for Testing...

**Comment by mirh** [comment]
Even without dev knowledge, as I hinted you may still help by identifying which of the first other 4 betas is the first that is broken for good.

**Comment by siblount** [comment]
Do you think it would be advantageous to use a CPU fallback option? If the GPU fails to render the image, it will fallback to the CPU until the app session is closed. Alternatively, similar to all the Chrome browser options to have an option to render images with GPU (checked) or not (unchecked). I know this doesn't directly solve the problem, but there are some other use cases for this.

For example, on my desktop, I only have a dedicated GPU, the RTX 3090, and it uses WAYYYY too much power just to render some images. For this scenario, I would rather use my CPU than GPU to handle graphics...for me at least.

**Comment by mirh** [comment]
It's called *acceleration* for a reason. 
There's no way a gpu is less efficient than a cpu in what it's tasked to do. And if you are worried about your 350W card waking up (putting aside that every modern card has at least half a dozen of P-states) then you should think a bit more holistically about using some kind of laptop-like hybrid graphics even on your desktop. 

With this said, I literally already mentioned a toggle for that (it's just that I'm not sure if it's a .NET/dx thing with some system-wide knob, or just a program-specific preference). But beyond that, the very weird thing is that whereas d3d 10_1 WARP fails immediately with a pretty straightforward error, real life 10_0 hardware somehow does not.

**Comment by siblount** [comment]
@mirh 
> There's no way a gpu is less efficient than a cpu in what it's tasked to do. And if you are worried about your 350W card waking up (putting aside that every modern card has at least half a dozen of P-states) then you should think a bit more holistically about using some kind of laptop-like hybrid graphics even on your desktop.

You are absolutely correct...if I had an integrated GPU. Pulling 120W minimum for the GPU alone compared to rendering at ~55-75W with the CPU is so much better. With browsers, I disable the "Use hardware acceleration when available" option, because if I don't...that thing will pull 200W and I know because my room will turn into an oven real quick (although, it's a great time for the Winter :3). ATP I'd have to replace every part to upgrade or downgrade the CPU to one that has integrated graphics. 

I just thought it might be cool to have this feature given this issue, along with some other potential use cases.

**Comment by mirh** [comment]
I think you have some big problem with your card if that's happening
https://www.techpowerup.com/review/msi-geforce-rtx-3090-ti-suprim-x/38.html

**Comment by siblount** [comment]
@mirh 
> I think you have some big problem with your card if that's happening https://www.techpowerup.com/review/msi-geforce-rtx-3090-ti-suprim-x/38.html

Lol! I think those are with 1080p monitors. At 4K, dual monitor, idle is 80W.

**Comment by mirh** [comment]
Resolution of an empty desktop has nothing to do with anything. 
If any, it might be that your monitors to achieve 4K (at whatever frequency and on whatever cable they have) requires/use some super tight timings with a vblank too short for the card to idle. 
Try to see if lowering anything of that with a custom resolution improves anything, and check if you didn't set "maximum performance" in the settings (because if that's your idle you have already lost really).

**Comment by d2phap** [comment]
I will just close this for now
