### ISSUE TITLE
Install new language packs not create Language folder

### ISSUE THREAD

**Issue by anemology** [d2phap/ImageGlass#1688]
### System information:
 - Windows OS version: 11
 - ImageGlass version: 9.0.6.1008_RC_x64_net8

### To Reproduce
1. Download zip from GitHub Release.
2. Download language pack from https://imageglass.org/language/download/zh-TW
3. Settings -> Language -> Install new language packs -> select `Chinese Traditional.iglang.json`

### Actual behavior:

The Error message shows `Could not find a part of the path 'C:\ImageGlass\Language\Chinese Traditional.iglang.json'`

### Expected behavior:

Nothing happened, but the Display language will add a new language.

### Screenshots:

![Settings](https://github.com/d2phap/ImageGlass/assets/12845882/ecafb465-2143-4252-a578-f564168ddf0c)

### Additional context:

The `Language` folder not auto create when fresh install. After I created the folder, issue was resolved.

**Comment by d2phap** [comment]
Fixed in [ImageGlass 9.0.7.1125](https://github.com/d2phap/ImageGlass/releases/tag/9.0.7.1125)
