### ISSUE TITLE
Improved Thumbnail Panel (Grid, Stacked Layout similar to Pinterest, Animated GIF tag)

### ISSUE THREAD

**Issue by d2phap** [d2phap/ImageGlass#169]
From **Lucian Boroslache**:

I've found ImageGlass today searching and I could not wait to make a mockup for future development suggestions.
I got tired of viewing images in windows 7 folders where I have only a few options to view the images (Extra Large Icons, Large Icons, Medium Icons, Small Icons, List, etc.), I can't not even view large vertical images in the folder.

So I've made those mockups, maybe the idea is implemented in the software in a day:

## **This is how the folder layout looks in ImageGlass right now:**
What I don't like is that I can't see large images and there is too much space unused, just like in the actual folder view from Windows. Quite boring.

![](https://lh3.googleusercontent.com/-z1LvM-ZZCZE/WMmAPofyudI/AAAAAAAAHcY/xqlQ4q56_bszNe9rHllEyOzuUHuhKrfMQCLcB/s1600/_normal.jpg)

### **1. GRID VIEW**

**Now, this is the improved view:**

In the left corner we have the view option (Grid/Stacked/Details) and the sorting. In the right corner is the zoom options (for the thumbnail panel).
The picture thumbnails don't have any margin and all of them are cropped & centered to fit a rectangle forming a perfect grid.

![](https://lh3.googleusercontent.com/-c-e92Cv9KFA/WMmAl4VcZCI/AAAAAAAAHcc/kB62wg2zHVEM54ZfFElJksBDPYTqLio3gCLcB/s1600/new_zoom_x7_grid.jpg)

**A better zoom functionality:**
The right corner zoom functions are step based (you'll drag or press the zoom magnifier for one step)
For example in the image below, the zoom factor is 4x (4 images per line).

![](https://lh3.googleusercontent.com/-zVd7HTb5QCY/WMmCBr9ILgI/AAAAAAAAHco/ZxDiy-3bGs0cfPIQwbmE7xaV4mzNVccpwCLcB/s1600/new_zoom_x4_grid.jpg)

**You can still drag the thumbnail panel from the side to make it smaller:**

But it will not break the grid, the zoom factor is still set on 4 images per line. It's different than the current ImageGlass thumbnail viewer (if you drag the thumbnail panel, the thumbnails have same size but the number of how many are on a line is changed).

![](https://lh3.googleusercontent.com/-kiSII0L8BYM/WMmDFdFbBzI/AAAAAAAAHc4/Wn-yM2AL3usyATX5UBGCc1k3vx88jMzOgCLcB/s1600/new_zoom_x4_grid_drag.jpg)

**You can use the zoom feature to see details in the images before opening them:** 
Now it's zoomed to 2 images per line.

![](https://lh3.googleusercontent.com/-djNSPD4rtl4/WMmD3te70rI/AAAAAAAAHdA/6rMDcplVrOgwLc5KrvUn35-6d3cIBOauwCLcB/s1600/new_zoom_x2_grid.jpg)

**Use the 1x image per line and drag the panel side to see small thumbnails:**
First, zoom in to one image per line and...

![](https://lh3.googleusercontent.com/-X_KknpN3wAo/WMmEkgXI3GI/AAAAAAAAHdI/icNbwf0KbcEzNypDEHyv4uFM0UTXvgL8gCLcB/s1600/new_zoom_x1_grid.jpg)

Drag the side of the panel to see small thumbnails. 

![](https://lh3.googleusercontent.com/-ng-4IuE3F5w/WMmE4sHtkFI/AAAAAAAAHdM/KWCZuD-BEQIkCbN-fqueNKPqMlMJUyDPwCLcB/s1600/new_zoom_x1_grid_drag.jpg)

### **2. STACKED VIEW** 

**Similar to pinterest, see the whole image in the thumbnails using the Stacked View layout option:**
([website example using stacked view](http://labs.benholland.me/pinterest/))

![](https://lh3.googleusercontent.com/-sfKeceKiZcw/WMmFvZcAlfI/AAAAAAAAHdU/t1-4iYz6eIw0O0G34KRVOYFnTdvT-7qyACLcB/s1600/new_zoom_x4_stacked.jpg)

Enable margins and animation (GIF) tag:

![](https://lh3.googleusercontent.com/-dRbRBhjftQM/WMmGKGXNUmI/AAAAAAAAHdY/clC2hn0opRgsDTVp_XFtoRGA6nVTz-ZmwCLcB/s1600/new_zoom_x4_stacked_margin_with_menu.jpg)

Keep stacked layout even when viewing larger/smaller thumbnails:

![](https://lh3.googleusercontent.com/-jzRlVwBWi7Q/WMmH4Pe5_vI/AAAAAAAAHd0/gbAq3QREGF8tsJLUUSeFu7qCzvoHjT5TACLcB/s1600/new_zoom_x2_stacked.jpg)

![](https://lh3.googleusercontent.com/-5t6FmfpMm4k/WMmH8aCgfsI/AAAAAAAAHd4/kJdcrGk8ZOALCdUqAwIwVwNMqraEs29kgCLcB/s1600/new_zoom_x2_stacked_margin_with_menu.jpg)

![](https://lh3.googleusercontent.com/--rg91zw9WDQ/WMmICTaJHrI/AAAAAAAAHd8/SrJhEgQgvd82sWCrHinSfwJ3lS294kJkwCLcB/s1600/new_zoom_x1_stacked.jpg)

![](https://lh3.googleusercontent.com/-HY6yI2Hf-hU/WMmIL7SwIcI/AAAAAAAAHeA/POna-cvML7UEXmzOzdWuuofsiA4ek6cMQCLcB/s1600/new_zoom_x1_stacked_drag.jpg)

That's all!

**Comment by vital-net** [comment]
Please We need this ! I'm even ready to donate for this feature to be implemented.
More dense, and a pinterest display like, and animated GIF thumbnail option.

Thank you

**Comment by fire-eggs** [comment]
The original mockup images have vanished off the interwebs. I'm attaching a PDF snapshot I made of the topic back in July 2018; the mockup images provide a lot of important detail.

[Issue #169 · d2phap_ImageGlass.pdf](https://github.com/d2phap/ImageGlass/files/3179423/Issue.169.d2phap_ImageGlass.pdf)

**Comment by d2phap** [comment]
Deleted this issue as requested by the author!
