### ISSUE TITLE
Switch Available Buttons with Current Buttons

### ISSUE THREAD

**Issue by inson1** [d2phap/ImageGlass#1690]
I think its the default tbh. Or at least that is experience :)
I mean in most apps the current buttons are on left side and available buttons on right side :)
 
PS
If you dont like the idea, move it to discussions, please :)

![ImageGlass_0yHqROFkaT](https://github.com/d2phap/ImageGlass/assets/75314629/d62ef5bd-735c-4739-a8b5-e7fc26413b4c)

**Comment by d2phap** [comment]
It has been this arrangement for years, and I don't want to change it :)
