### ISSUE TITLE
Add Title section in Settings (like toolbar section)

### ISSUE THREAD

**Issue by inson1** [d2phap/ImageGlass#1693]
Have option to select/unselect things from title like size, zoom level, name, icon 
Have option to change order of things in title
Show/Unshow the whole title
Option to select text size
(like in toolbar)
![ImageGlass_em6bbDIYs4](https://github.com/d2phap/ImageGlass/assets/75314629/29e0ad59-fa7e-4a97-8e44-f408ac849f3e)

Related to #915

**Comment by d2phap** [comment]
In v9, you can customize the image information tag on title bar in app settings > General > Others
