### ISSUE TITLE
Option to Reset all settings/preferences

### ISSUE THREAD

**Issue by inson1** [d2phap/ImageGlass#1694]
You can reset some groups of settings, but I didnt find found how to reset all settings / preferences

**Comment by d2phap** [comment]
You can just delete the `igconfig.xml` or `igconfig.json` file to reset the settings

**Comment by inson1** [comment]
@d2phap But that isnt user friendly way to be honest

**Comment by vivadavid** [comment]
Hi, I also think a reset button for the settings would be really helpful. Just now, I have been trying different zooming parameters and I can't remember what the default settings were.

Thanks in advance!

**Comment by d2phap** [comment]
Okay just reopen it!

**Comment by vivadavid** [comment]
> Okay just reopen it!

Thanks!

**Comment by d2phap** [comment]
In v9.0.11, you can use "Quick Setup" dialog to reset all settings.
In v9.1, there will be a text link "Reset settings" in Settings dialog to do this.

**Comment by vivadavid** [comment]
Thanks!

**Comment by d2phap** [comment]
Added to [ImageGlass 9.1 Beta](https://github.com/d2phap/ImageGlass/releases/tag/9.0.11.529)

![image](https://github.com/d2phap/ImageGlass/assets/3154213/d27d0553-755a-46e0-b241-6d05f92468e5)

**Comment by vivadavid** [comment]
Thanks, @d2phap !!

**Comment by vivadavid** [comment]
Unfortunately, ImageGlass 9.1 Beta (v9.0.11.529) won't run on my PC, so I was unable to test it.

**Comment by d2phap** [comment]
@vivadavid what is the error?

**Comment by vivadavid** [comment]
> @vivadavid what is the error?

I double click on the EXE file but nothing happens.

. NET 8 is installed on my PC.

**Comment by d2phap** [comment]
@vivadavid Can you check if it's same as this issue?
https://github.com/d2phap/ImageGlass/issues/1915#issuecomment-2117345978

**Comment by vivadavid** [comment]
I have repaired .NET 8 (x64), but the programme still won't run. Should I install .NET 8 (x86)?

**Comment by d2phap** [comment]
@vivadavid you need to check the log in "Event Viewer". Let's move this to #1935
