### ISSUE TITLE
I would move close on escape to keybord section from general section

### ISSUE THREAD

**Issue by inson1** [d2phap/ImageGlass#1695]
I think it would make more sense to have all keyboard settings in one place. Idk if you are going to do it in v9 or not. In v8 it wasnt in keyboard settings

**Comment by d2phap** [comment]
This setting is removed in v9 because IG supports hotkey customization in `igconfig.json`

**Comment by inson1** [comment]
@d2phap customization in some file isnt user friendly

**Comment by d2phap** [comment]
Hotkey customization is still under experiment in v9. It will have UI eventually.
