### ISSUE TITLE
[BUG] Menu doesnt close ater I click on app's frame

### ISSUE THREAD

**Issue by inson1** [d2phap/ImageGlass#1697]
### System information:
 - Windows OS version: 10
 - ImageGlass version: 9.0.6.1008

### To Reproduce
1. Click on select box
2. Move settings window by frame
3. Menu stays

When I click somewhere else menu closes

###How to Fix it
When somebody clicks on frame, menu should close

### Screenshots:
![ImageGlass_WN0AYksuax](https://github.com/d2phap/ImageGlass/assets/75314629/7b0ac81d-d253-4a5b-8cbc-ee37e586cea4)

**Comment by d2phap** [comment]
this is the native control of browser, so there is no fix for it
