### ISSUE TITLE
[BUG] App doesnt save empty toolbar

### ISSUE THREAD

**Issue by inson1** [d2phap/ImageGlass#1698]
### System information:
 - Windows OS version: 10
 - ImageGlass version: 9.0.6.1008

It worked before, idk what changed :/

### To Reproduce
1. Open the app
![ImageGlass_J2o18SLzAJ](https://github.com/d2phap/ImageGlass/assets/75314629/1d2610ac-b1b0-48fe-8023-e37ae74d70d8)
2. Clean the toolbar
![ImageGlass_BcCSgKm96k](https://github.com/d2phap/ImageGlass/assets/75314629/b419d3ea-e58a-44a2-9f14-2fa3934041f5)
3. Close the app
4. Open the app again
![ImageGlass_J2o18SLzAJ](https://github.com/d2phap/ImageGlass/assets/75314629/1d2610ac-b1b0-48fe-8023-e37ae74d70d8)

If I leave something there, then toolbar is saved

**Comment by d2phap** [comment]
It's as expected. User can hide the toolbar instead

**Comment by inson1** [comment]
@d2phap but if you hide it then you also hide the settings button
