### ISSUE TITLE
Dull colors

### ISSUE THREAD

**Issue by ampp33** [d2phap/ImageGlass#17]
JPEG images (saved out of PS) in ImageGlass appear to have duller colors than if the picture were displayed in Windows Photo Viewer.  See the attached screenshots; the first image is a screencap from ImageGlass, while the second is from Windows Photo Viewer.

![bad](https://cloud.githubusercontent.com/assets/1832274/7152623/4b898f6a-e30d-11e4-88e7-46d4f3420f4c.PNG)
![good](https://cloud.githubusercontent.com/assets/1832274/7152624/4b94d582-e30d-11e4-89fb-ddbb76a68f36.PNG)

**Comment by d2phap** [comment]
Hi!

Could you please send me your original photo. It is little hard to identity issue with screencap.
Moreover, What OS are you running?

Thank you.

**Comment by ampp33** [comment]
Image attached below (assuming that's the correct way to send it to you).  I'm using Windows 7.

![clip](https://cloud.githubusercontent.com/assets/1832274/7221674/70e72f52-e6c2-11e4-9082-4175b6fc9845.jpg)

**Comment by d2phap** [comment]
OK. I understood the issue. ImageGlass skipped embedded color profile.
I can fix it in the next release.

**Comment by d2phap** [comment]
fixed this issue in https://github.com/d2phap/ImageGlass/commit/fa00c042c74731eedb21a173b01c4edf1aebce86
