### ISSUE TITLE
Possibility to opt out the 'upload to facebook' button?

### ISSUE THREAD

**Issue by zsdonny** [d2phap/ImageGlass#170]
Not a fan of social media, is it possible to have an option to remove the facebook button? Many thanks

**Comment by d2phap** [comment]
Hi @zsdonny ,
Currently, this facebook sharing button is showing on tool bar and you cannot remove it as well.
In the future, thi button will become "Sharing" which allows user can share the viewing image to many services / email / bluetooth...

I will tag this as a suggestion.

**Comment by d2phap** [comment]
The Facebook button was removed https://github.com/d2phap/ImageGlass/commit/965ac507d8125237f7b3c191423a790987d29117
