### ISSUE TITLE
PNG quality when image is loaded to 100% zoom

### ISSUE THREAD

**Issue by Opicka879** [d2phap/ImageGlass#1701]
### System information:
 - Windows OS version: Windows 10 Home 22H2
 - ImageGlass version: 9.0.7.1125 (64-bit)

### To Reproduce
1. Set zoom to autozoom
2. Set Image interpolaton with zoom ≤ 100 % at Nearest neighbor
3. Open PNG image with some bold text on
4. You can see the problem
5. Zoom-out and zoom back to 100% to fix

### Actual behavior:
When i open some PNG file with Nearest neighbor setting at 100% zoom level, there is bad quality of image. When i zoom-out and zoom back to 100% problem is fixed. In other settings of Image interpolation text on images is very blury, so i need to use Nearest neighbor. I did not try another file types, maybe the problem is in others too.

At version 8 these images did looks fine at Nearest neighbor setting everytime when loaded.

### Expected behavior:
Images should look good right after loading, not after re-zooming again. 

And maybe consider to add setting of Image interpolation for 100% zoom level separately.

**Comment by d2phap** [comment]
Hi @Opicka879 
Can you send some screenshots for better understanding the issue?

**Comment by Opicka879** [comment]
Version 8 loaded
![v8-loaded](https://github.com/d2phap/ImageGlass/assets/37151776/de135314-b7b8-4f20-b94e-3a476fe4a2e0)

Version 9 loaded
![v9-loaded](https://github.com/d2phap/ImageGlass/assets/37151776/5799ee93-4d7e-463e-8387-631b524d91c5)

Version 9 rezoomed (zoom out one step and zoom back to 100%)
![v9-rezoomed](https://github.com/d2phap/ImageGlass/assets/37151776/3270abac-28f6-4b1e-af20-fa82fa288ab6)

**Comment by yoshinatsu** [comment]
Yeah, the interpolation for ≤ 100% also applies to 100%.
I think 100% should always be at nearest neighbor, or else the image has scaling artifacts, or is blurry.
For now we are forced to used nearest neighbor if we want to have a clear image at 100%.
This wasn't the case for version 8.

**Comment by siblount** [comment]
@yoshinatsu See https://github.com/d2phap/ImageGlass/issues/1716#issuecomment-1826409558

**Comment by Opicka879** [comment]
@d2phap Just for be sure you did not miss it. The problem is not only default setting of interpolation but even the bad image quality after open the PNG file with nearest neighbor setting. That screenshots are all with nearest neighbor setting for all options. 

Still when you load PNG it looks wierd at 100% (screenshot 2). Zooming-in and go back to 100% does not fix the problem. Only zooming-out and go back to 100% fixing the problem (screenshot 3).

**Comment by d2phap** [comment]
Fixed in [ImageGlass 9.0.8.1208](https://github.com/d2phap/ImageGlass/releases/tag/9.0.8.1208)
