### ISSUE TITLE
Zoom toolbar buttons' functionality is swapped

### ISSUE THREAD

**Issue by clothedsnake** [d2phap/ImageGlass#1704]
### System information:
 - Windows OS version: Windows 11 23H2
 - ImageGlass version: 9.0.7.1125

### To Reproduce
1. Click on Zoom Out in the toolbar
2. Click on Zoom In in the toolbar

### Actual behavior:

The functions for ZoomIn and ZoomOut are swapped. When I click on ZoomIn, the image zooms out, and vice-versa.

### Expected behavior:

When a user clicks on ZoomIn, the image should zoom in. When a user clicks on ZoomOut, the image should zoom out.

### Screenshots:

n/a

### Additional context:

This is a regression from 8.1.x.

**Comment by d2phap** [comment]
@clothedsnake thanks for the bug.
The function of the buttons is correct (according to its tooltip), it's just the icons are swapped.
You can temporarily fix it by open the Kobe and Kobe-Light theme folder of ImageGlass, rename the `ZoomIn.svg` and `ZoomOut.svg` accordingly.

**Comment by d2phap** [comment]
Fixed in [ImageGlass 9.0.8.1208](https://github.com/d2phap/ImageGlass/releases/tag/9.0.8.1208)
