### ISSUE TITLE
"Toolbar" and "Gallery Panel" re-enabled after quitting from full screen mode

### ISSUE THREAD

**Issue by Balzhur** [d2phap/ImageGlass#1705]
### System information:
 - Windows OS version: Windows 11 Pro 23H2 22631.2715
 - ImageGlass version: 9.0.7.1125 (64 bit) Windows Store version. .NET 8

### To Reproduce
1. Delete igconfig.json to have a clean state
2. Start IG
3. Press "T", "G"
4. Exit IG
5. Start IG - IG starts in windowed mode with no toolbar and gallery panel --> ${\color{green}OK}$
6. Press "F11" for full screen then "Esc" to exit
7. Start IG - IG starts in Full Screen, but toolbar and gallery panel are back --> ${\color{red}not\ OK}$

### Actual behavior:
See steps to reproduce.
"Toolbar" and "Gallery Panel" re-enabled automatically after quitting IG from full screen mode with toolbar and gallery turned off.

### Expected behavior:
Toolbar and gallery panel states are saved during exit.

**Comment by siblount** [comment]
Related to #1715

**Comment by d2phap** [comment]
Should be fixed in [ImageGlass 9.0.9.1230](https://github.com/d2phap/ImageGlass/releases/tag/9.0.9.1230)
