### ISSUE TITLE
real portable version with .net desktop runtime dlls integrated.... 

### ISSUE THREAD

**Issue by svenbolte** [d2phap/ImageGlass#1707]
The current 9 version needs to install .net desktop runtime 8 and edge webview2 runtime.
There is a portable version of imageglass viewer that IS NOT portable as it needs things to run as administrator in machine.

It would be great to have a REAL portable version like paint.net does have one.

If you download paint.net portable x64 ALL the uses components (and framework things) are integrated in the portable folder and do not need to be installed.

I do not want to have things like the .net desktop framework installed and a queeky edge browser and runtime and run services in background that i do not need for other programms at all. :(

**Comment by d2phap** [comment]
Refer to https://github.com/d2phap/ImageGlass/issues/1895#issuecomment-2083069419

**Comment by svenbolte** [comment]
R.I.P - best free image viewer on windows. 
Sad to hear about your plans. As most companies do not allow users to install software and in most cases .net Desktop runtime is not needed for other software in companies or other projects integrate the runtime in their product i am very sad to discard Image Glass viewer 9 and revoke usage recommendation for our customers.

Need to find alternatives that are slim and functional like V8.
Too bad i cannot code in c#, else i would make a fork ov v8
