### ISSUE TITLE
Moving ImageGlass window to another monitor with color profile does not update the image

### ISSUE THREAD

**Issue by janweigel** [d2phap/ImageGlass#1709]
### System information:
 - Windows OS version: 11 pro 23H2 Build 22631.2715
 - ImageGlass version: 9.0.7.1125 64-bit

### To Reproduce
1. In Settings set Color Management -> Color Profile to "Current Monitor Profile"
2. Use a Monitor with a calibrated Color Profile
3. Open an Image with embedded Color Profile
4. Compare the Colors to other color managed apps

### Actual behavior:
ImageGlass 9 seems to be not color managed app at all and shows the Image like e.g. the Windows Explorer Preview but not like any other color managed app like Chrome or Figma or Photoshop. 

### Expected behavior:
The colors should be displayed color managed. This was working in Version 8 and I could even move ImageGlass from one Screen to the other and it would adjust to the correct color profile. Now the color management of ImageGlass 9 seems to be completely broken.

### Screenshots:
ImageGlass 9 on the left vs. Chrome on the right

![ImageGlass9 vs Chrome - Color Management Bug](https://github.com/d2phap/ImageGlass/assets/4882318/650ce984-1908-4d95-8801-7b7d957bdaae)

**Comment by d2phap** [comment]
Can you send me the sample file?

I'm using Dell laptop with color profile monitor. IG 9 displays correctly for me. The below is a CMYK image:
![image](https://github.com/d2phap/ImageGlass/assets/3154213/e86efb98-3a7a-4411-ab00-4225f8319026)

Also make sure you select "Professional user" profile in the "ImageGlass Quick Setup" dialog. If not, you need to manually apply the settings highlighted below:

<img src="https://github.com/d2phap/ImageGlass/assets/3154213/974770c1-5f1f-4fdf-b749-07a2cb29f17f" height="400" align="left" />
<img src="https://github.com/d2phap/ImageGlass/assets/3154213/c4a5534c-579a-4c79-b827-9f8e883aac35" height="500" align="left" />

**Comment by janweigel** [comment]
Hi @d2phap 

I did some further investigation both with IG 8 and IG 9 and the problem in both versions is actually that ImageGlass does not adapt to the monitor's color profile it is currently shown on.
I also have a Dell Laptop with color profile and an external LG display with another color profile.

If I open Chrome or Figma and move the window between monitors the apps adapt to the color profile of the current monitor.
ImageGlass fails to do that and always loads the profile of the monitor it was open on. 

Here are two screenshots to illustrate the problem.

1. Chrome on the left and ImageGlass 9 on the right, both opened on the external LG monitor: Color profile applied correctly:
![ig9-vs-chrome-display-lg](https://github.com/d2phap/ImageGlass/assets/4882318/1f7c6b5a-6f63-4585-bc90-37b7c2059994)

2. Chrome on the left and ImageGlass 9 on the right, both moved to the Dell monitor: 
=> Chrome (and other apps like Figma, Photoshop, Edge, ...) correctly adapt to the profile of the monitor, while ImageGlass fails to adapt to the new monitor:
![ig9-vs-chrome-display-dell](https://github.com/d2phap/ImageGlass/assets/4882318/9ecabdc6-3c78-48ac-98e0-36738f97b758)

**Comment by d2phap** [comment]
> If I open Chrome or Figma and move the window between monitors the apps adapt to the color profile of the current monitor.
> ImageGlass fails to do that and always loads the profile of the monitor it was open on.

Currently, ImageGlass does not auto-reload the image when you move the window to another monitor with a color profile. You will need to press <kbd>Ctrl+R</kbd> to manually reload it

**Comment by janweigel** [comment]
Ah ok, thanks.
Yes, reloading with  Ctrl+R manually indeed works.
That should be mentioned somewhere in the monitor profile settings.
Thank you!

**Comment by d2phap** [comment]
Added a note in app settings in [ImageGlass 9.0.8.1208](https://github.com/d2phap/ImageGlass/releases/tag/9.0.8.1208)
