### ISSUE TITLE
ADD ZOOM by pressing "+" and "-"

### ISSUE THREAD

**Issue by user6669** [d2phap/ImageGlass#171]
In the previous version there was a zoom function by pressing the "plus" and "minus" buttons. Now she stopped working. Please FIX it.

**Comment by d2phap** [comment]
Hi @user6669 ,

"+" and "-"  keys are added in the next version.
You can check the shortcuts reference here:
http://imageglass.org/documentation/ui-shortcuts-reference

This will be released in middle of April.
Stay tuned :)

Phap
