### ISSUE TITLE
can't open tif file

### ISSUE THREAD

**Issue by gisgyf** [d2phap/ImageGlass#1710]
![image](https://github.com/d2phap/ImageGlass/assets/130264348/56f16c49-9889-4868-bcf6-681c2bf683b2)

**Comment by d2phap** [comment]
@Simplify-2023 Can you share your TIF file because I cannot reproduce it

![image](https://github.com/d2phap/ImageGlass/assets/3154213/64c67da9-1e12-4773-9ec6-2c370852c8ca)

**Comment by gisgyf** [comment]
> @Simplify-2023 Can you share your TIF file because I cannot reproduce it
> 
> ![image](https://private-user-images.githubusercontent.com/3154213/285593749-64c67da9-1e12-4773-9ec6-2c370852c8ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MTkyMjMsIm5iZiI6MTcwMDkxODkyMywicGF0aCI6Ii8zMTU0MjEzLzI4NTU5Mzc0OS02NGM2N2RhOS0xZTEyLTQ3NzMtOWVjNi0yYzM3MDg1MmM4Y2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjVUMTMyODQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWNjYjQzZWExYzQ5ZjAxMDA2YzM0OTlhNWQxNzgxYTQxMTBjNWRlNzE2ZGM0MmJlMjA3MDgwMmZmZmZlNmE4YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vodclqK5cjw20eencoUdj10OMDo_2ioZqnF397I_obE)

It's a landsat image and approximately 1GB. Upload such a large file is time consuming so I am not ready to upload it, but you can simply download any tif file that's large than 500MB and test if it works on imageGlass.

**Comment by d2phap** [comment]
Unfortunately, I'm unable to check your issue without a sample file

**Comment by gisgyf** [comment]
> Unfortunately, I'm unable to check your issue without a sample file

Alright, please check out and download tif file from this link 'https://opendata.digitalglobe.com/events/california-fire-2020/pre-event/2018-02-16/pine-gulch-fire20/1030010076004E00.tif'

**Comment by d2phap** [comment]
Apparently, your file size and dimension is too big to open with ImageGlass, see the [limitations](https://imageglass.org/docs/features#limitations). I wonder if any app can open it.

![image](https://github.com/d2phap/ImageGlass/assets/3154213/5b9c0e8a-593a-44e2-80ca-b0f6eb63a225)
