### ISSUE TITLE
ImageGlass update prompt fails to recognize 64-bit Windows

### ISSUE THREAD

**Issue by siblount** [d2phap/ImageGlass#1712]
### System information:
 - Windows OS version: 22621.2715
 - ImageGlass version: 8.10.9.27

### To Reproduce
1. Wait for prompt for an ImageGlass update.

### Actual behavior:
It is saying that Windows is not a 64-bit version.

### Expected behavior:
It should say that Windows **is** a 64-bit version.

### Screenshots:
![image](https://github.com/d2phap/ImageGlass/assets/74916907/26edea51-1153-410c-95ba-fc587935001f)

### Additional context:
Putting this here in case it was not fixed in update.

**Comment by siblount** [comment]
Just realized this could also be because I set it to install in C:/Program Files/ImageGlass instead of local.

**Comment by worldsdream** [comment]
Confirmed.

**Comment by chiragwad** [comment]
I can reproduce this error as well

**Comment by mirh** [comment]
Of course it happens when there is literally not even a check. 
https://github.com/d2phap/ImageGlass/blob/c0800aba0a9e935b955a35b52c3afc0d3ecb084a/v8/Components/ImageGlass.Base/Update/UpdateService.cs#L98

**Comment by Cragt** [comment]
Additional confirmation of the issue upon clean installation of ImageGlass 8.10.9.27 via chocolatey

**Comment by d2phap** [comment]
Haha, I forgot to remove the hardcoded code while debugging. But I'm not sure whether I should publish a new version of v8.

**Comment by mirh** [comment]
You could sneakily just replace the old installer perhaps. It's kinda.. disconcerting to read that your 64-bit windows somehow isn't 64-bit.

**Comment by siblount** [comment]
@d2phap I would say publish a new version of v8. This is because your roadmap says it will release critical updates for v8 still until some time in 2024.

**Comment by d2phap** [comment]
Published [v8.11](https://imageglass.org/news/announcing-imageglass-8-11-89)
