### ISSUE TITLE
ImageGlass ignoring & overwriting user config file

### ISSUE THREAD

**Issue by siblount** [d2phap/ImageGlass#1715]
### System information:
 - Windows OS version: 11
 - ImageGlass version: 9.0.7.1125

### To Reproduce
1. open IG
2. close IG
3. edit user file config, specifically "showGallery" property to false
4. open IG.
5. close IG
6. open IG to notice the gallery and toolbar is back up and showing again

### Actual behavior:
Currently, everytime I open ImageGlass its show the toolbar and the gallery bar and I don't want it to show. I skimmed around the settings and couldn't find anything related. When I manually, edited the "showGallery" property to false, when ImageGlass was closed, and opened IG back up, it worked, but then when I closed it again and open it back up, it reverted back.

### Expected behavior:
Changing the settings in the file is not overwritten.

**Comment by siblount** [comment]
For a temp solution, setting the file attributes of _igconfig.json_ to read-only solves this problem.

**Comment by d2phap** [comment]
It's as expected. ImageGlass does not support this and I don't have plan to implement this, too.
