### ISSUE TITLE
Images do not load (ARM64 only)

### ISSUE THREAD

**Issue by ArminiusTux** [d2phap/ImageGlass#1717]
### System information:
 - Windows OS version:  Win11 v23H2 (Build 22631.2715)
 - ImageGlass version: 9.0.7.1125 (arm64 build)

### To Reproduce
1. Download ImageGlass_9.0.7.1125_arm64.zip
2. Make sure that WebView2 & .NET v8 runtimes are installed
3. Extract ImageGlass
4. Run ImageGlass.exe and finish the QuickSetup

### Actual behavior:
After finishing the quick setup no images are loaded. The menu bar is also missing the icons.
The preview bar on the bottom however is loading the images correctly.

### Expected behavior:
The menu bar icons should be visible and the main view section should load and display the image.

### Screenshots:

<img width="548" alt="ImageGlass" src="https://github.com/d2phap/ImageGlass/assets/44533868/f23a2856-5516-4a7f-bc39-3ac7b611027a">

### Additional context:
The release candidate (ImageGlass_Moon_9.0.6.1008_RC_arm64_net8.zip) is behaving just fine.
The error is not restricted to any picture format, UAC mode nor the window size (happens also in fullscreen).

**Comment by d2phap** [comment]
@ArminiusTux 
I've just downgraded MagickNET lib to v13.3.0, can you try this build?
https://drive.google.com/file/d/1qPrMGE8yMPv0HF2KYSPcS-mYwTzY3vTD/view?usp=sharing

**Comment by hellvy-github** [comment]
> @ArminiusTux I've just downgraded MagickNET lib to v13.3.0, can you try this build? https://drive.google.com/file/d/1qPrMGE8yMPv0HF2KYSPcS-mYwTzY3vTD/view?usp=sharing

Hello, I've tried this build and still got same error. I've noticed MagickNET lib version is already v.13.3.0 (released build and test build use same MagickNET lib version)

**Comment by ArminiusTux** [comment]
Confirmed, no visible change.

<img width="512" alt="ImageGlass_error" src="https://github.com/d2phap/ImageGlass/assets/44533868/a45d1091-a02c-40d3-bf46-0fa2863798d7">

**Comment by d2phap** [comment]
My last try: https://drive.google.com/file/d/10vZVp9o20RPpqNt-o_4T0THllGU5z7w8/view?usp=sharing, can you help to check please?

**Comment by hellvy-github** [comment]
> My last try: https://drive.google.com/file/d/10vZVp9o20RPpqNt-o_4T0THllGU5z7w8/view?usp=sharing, can you help to check please?

This build is working fine! Thank you very much :)

**Comment by ArminiusTux** [comment]
Indeed the new ARM64 build is fine. Thanks @d2phap for the quick fixup!
<img width="641" alt="ImageGlass_fine" src="https://github.com/d2phap/ImageGlass/assets/44533868/209373f0-c74d-49bd-8a57-03d2972c5028">

**Comment by d2phap** [comment]
Published [ImageGlass 9.0.8.1208](https://github.com/d2phap/ImageGlass/releases/tag/9.0.8.1208)
