### ISSUE TITLE
Opening file on 2nd monitor makes IG open on that monitor. (IG 9)

### ISSUE THREAD

**Issue by BlepBlep** [d2phap/ImageGlass#1718]
Using ImageGlass 9.0.7.1125, when opening a file that happens to be on a second monitor, it opens ImageGlass on that monitor, instead of its saved position. This did not happen with IG 8.

**Comment by d2phap** [comment]
This is as expected, IG uses the new WinApi [`SetWindowPlacement()`](https://github.com/d2phap/ImageGlass/blob/c0800aba0a9e935b955a35b52c3afc0d3ecb084a/Source/Components/ImageGlass.Settings/WindowPlacement/WindowSettings.cs#L30) for saving/restoring window size and location.

**Comment by BlepBlep** [comment]
> This is as expected, IG uses the new WinApi [`SetWindowPlacement()`](https://github.com/d2phap/ImageGlass/blob/c0800aba0a9e935b955a35b52c3afc0d3ecb084a/Source/Components/ImageGlass.Settings/WindowPlacement/WindowSettings.cs#L30) for saving/restoring window size and location.

That's extremely disappointing and very annoying to use. I'll be going back to IG8 or looking for something new then. I have my Windows Explorer open on my other monitor so I can view and search at the same time. Having the window open over my windows explorer every time is very very annoying.
