### ISSUE TITLE
Window Fit Problem

### ISSUE THREAD

**Issue by hoyachoe** [d2phap/ImageGlass#1719]
### System information:
 - Windows OS version:  Windows 11
 - ImageGlass version:   ImageGlass_9.0.7.1125_x64.msi

### To Reproduce
1. Window Fit on,  AutoZoom On, 
2. (Auto-center the window in Window Fit mode-- Uncheck)
3. Move the window position and close Image Glass.
4. Double-click the image in the folder to launch Image Glass.
5. Image Glass is executed in a position different from the window position at the time of termination.
----
1. Window Fit on,  AutoZoom On, 
2.  (Auto-center the window in Window Fit mode-- Uncheck)
3. Attempt to reduce the size of the window by dragging the mouse on the window frame.
4. The window frame and image size are not modified and take damage.

### Actual behavior:

If Window Fit is activated, the position of the window is not saved when the program is terminated  (Auto-center the window in Window Fit mode-- Uncheck)

If enable Window Fit and drag the window with the mouse to reduce the window size, image size correction will not work and the image will be damaged.

### Expected behavior:

In ImageGlass_Kobe_8, even if Window Fit is enabled, the position of the window when closed is saved.
In ImageGlass_Kobe_8, even if Window Fit is activated, the window size can be adjusted by dragging the mouse.
However, both do not work in version 9.

**Comment by siblount** [comment]
There was also an instance where Window Fit caused the application to crash...something among the lines of the MinWidth being  out of bounds. I didn't save it, stupid me. I'll post it here if I can reproduce it again.

**Comment by d2phap** [comment]
This has been fixed since v9.0.8
