### ISSUE TITLE
Flickering bug when dragging window borders

### ISSUE THREAD

**Issue by RVillaT** [d2phap/ImageGlass#1720]
### System information:
 - Windows OS version: Windows 11
 - ImageGlass version: ImageGlass_9.0.7.1125_x64.msi

### To Reproduce
1. Open any image. Window Fit On (F9), AutoZoom On.
2. Reduce the size of the window by dragging the borders.
3. Around the borders, an area the size of the initial window flickers.

### Actual behavior:

Flickering around the image when the size of the window is reduced by dragging the borders upon opening the image.
Sometimes the flickering area remains visible once the resizing is done.
If the image is zoomed once, everything works fine and there is no flickering at all.

### Expected behavior:

There should be no flickering when the size of the window is reduced by dragging the borders upon opening the image.

### Additional context:

Seems related to issue [https://github.com/d2phap/ImageGlass/issues/1719](https://github.com/d2phap/ImageGlass/issues/1719)

**Comment by d2phap** [comment]
Fixed in [ImageGlass 9.0.8.1208](https://github.com/d2phap/ImageGlass/releases/tag/9.0.8.1208)
