### ISSUE TITLE
Ability to zoom using the + and - buttons

### ISSUE THREAD

**Issue by RVillaT** [d2phap/ImageGlass#1721]
### Is your feature request related to a problem? Please describe.

Since version 8 of Imageglass I zoom using the keyboard keys (+ and -), which I find more efficient for my workflow than the mouse wheel. In version 9, the mouse wheel seems to be the only solution for zooming (unless I am mistaken). If you use a mouse without a wheel, you cannot zoom.

### Describe the solution you'd like

I would like to be able to zoom using the keyboard keys (+ and -) in addition to the mouse wheel. as in version 8.

**Comment by d2phap** [comment]
Hi @RVillaT 
If you talk about the + and - key on the numeric keypad, you can change the hotkeys for the menu by editing `igconfig.json` file as below:

```json
// in igconfig.json
"MenuHotkeys": {
  "MnuZoomIn": ["=", "Add"],
  "MnuZoomOut": [ "-", "Subtract"]
},
```

For more details, pls refer to https://github.com/d2phap/ImageGlass/discussions/1702#discussioncomment-7660806

**Comment by RVillaT** [comment]
Thanks, it works perfectly. Problem solved.

**Comment by d2phap** [comment]
Added this as default hotkeys for zooming in [ImageGlass 9.0.8.1208](https://github.com/d2phap/ImageGlass/releases/tag/9.0.8.1208)
