### ISSUE TITLE
Scroll wheel doesn't work if "Scroll inactive windows when I hover over them" is disabled in Windows settings.

### ISSUE THREAD

**Issue by BrianCrowe3** [d2phap/ImageGlass#1723]
### System information:
 - Windows OS version: 
Windows 10 Home Build 19045

 - ImageGlass version: 
9.0.7.1125_x64 portable

### To Reproduce
1. Disable "Scroll inactive windows when I hover over them" in the Windows settings app under Devices->Mouse
2. Open image in image glass, try to use the scroll wheel.

### Actual behavior:
Scroll wheel doesn't work whether imageglass is active or not

### Expected behavior:
Scroll wheel to function as normally when imageglass is the active window regardless of "Scroll inactive windows when I hover over them" being disabled or not

### Additional context:
I don't actually know if this is an imageglass problem or a Windows problem. I'm assuming it's an imageglass problem because the "Scroll inactive windows when I hover over them" setting works as expected in all of my other programs (including imageglass 8.10.9.27 x64).

**Comment by d2phap** [comment]
Fixed in [ImageGlass 9.0.8.1208](https://github.com/d2phap/ImageGlass/releases/tag/9.0.8.1208)
