### ISSUE TITLE
Cannot increase slideshow interval

### ISSUE THREAD

**Issue by bommit91** [d2phap/ImageGlass#1728]
### System information:
 - Windows OS version: 11
 - ImageGlass version: 9

### To Reproduce
In setting under slideshow, whenever I try to increase the interval to be greater than 5, the box remains red and the effect cannot be applied.

### Actual behavior:
Cannot apply changes to slideshow interval

### Expected behavior:
To be able to save changes to the slideshow interval

### Screenshots:
![Screenshot 2023-11-27 113122](https://github.com/d2phap/ImageGlass/assets/152201858/5001dd48-14ab-4ab7-ba3a-f345d1c86a00)

**Comment by d2phap** [comment]
Confirm this bug.
You can directly edit the `igconfig.json` file for temporary solution:

![image](https://github.com/d2phap/ImageGlass/assets/3154213/e797e23c-7380-4ea2-a297-1be3905cfa5d)

**Comment by d2phap** [comment]
Fixed in [ImageGlass 9.0.8.1208](https://github.com/d2phap/ImageGlass/releases/tag/9.0.8.1208)
