### ISSUE TITLE
Full screen toggle button style doesnt update when toggled off

### ISSUE THREAD

**Issue by sguergachi** [d2phap/ImageGlass#1729]
### System information:
 - Windows OS version: 
Edition	Windows 11 Pro
Version	23H2
OS build	22635.2700

 - ImageGlass version: 9.0.7.1125

### To Reproduce
1. Click full screen button
2. Click full screen button again
3. 
4. 

### Actual behavior:

![image](https://github.com/d2phap/ImageGlass/assets/615386/fa6e2052-659e-433e-ab69-95097b255fde)
the toggle button style looks as if its selected, when it should not be

### Expected behavior:

![image](https://github.com/d2phap/ImageGlass/assets/615386/0621c108-3d8a-4f02-a9bb-5c4f0c38c2e0)
button should not look selected

**Comment by d2phap** [comment]
Fixed in [ImageGlass 9.0.8.1208](https://github.com/d2phap/ImageGlass/releases/tag/9.0.8.1208)
