### ISSUE TITLE
Using left and right arrow keys when zoomed in

### ISSUE THREAD

**Issue by dtruebin** [d2phap/ImageGlass#173]
I'm using ImageGlass 3.5.9.17. Per [UI Shortcuts Reference](http://www.imageglass.org/documentation/ui-shortcuts-reference), left and right arrows are used to switch between images. In fact, when an image is zoomed in, all four arrows perform scrolling on key down. At the same time, left and right arrows still perform switching on key up. This is annoying, especially when zoom is locked.

Demo:
![demo](https://cloud.githubusercontent.com/assets/1437843/24493507/520cb334-152f-11e7-8a81-6f49537c4128.gif)

**Comment by d2phap** [comment]
Thanks @dtruebin 
There may be some conflictions of the hotkeys

**Comment by fire-eggs** [comment]
Available in latest ImageGlass Moon (https://imageglass.org/moon).
