### ISSUE TITLE
Ability to copy version number in About screen

### ISSUE THREAD

**Issue by sguergachi** [d2phap/ImageGlass#1730]
To submit a bug we must provide the ImageGlass version number. It would be helpful if we can select the version number in the about screen to easily paste it.

![image](https://github.com/d2phap/ImageGlass/assets/615386/58b90f89-5024-43e6-88d7-2ad0843e23bc)

**Comment by d2phap** [comment]
Implemented in [ImageGlass 9.0.8.1208](https://github.com/d2phap/ImageGlass/releases/tag/9.0.8.1208)
