### ISSUE TITLE
ImageGlass cannot be open properly

### ISSUE THREAD

**Issue by cherub0507** [d2phap/ImageGlass#1732]
### System information:
 - Windows OS version: win 11 x64 (23H2)
 - ImageGlass version: 9.0.7.1125

### Description
1. installed the .NET Desktop Runtime 8 (64-bit) and WebView2 Runtime 64-bit with the latest version, got the System Requirements ready
2. installed the ImageGlass 9.0.7.1125
3. open the photo with ImageGlass, cannot work properly, always shows 'loading'

### Screenshots:
![image](https://github.com/d2phap/ImageGlass/assets/58015207/95333597-3771-4da7-898d-17dbdf3eeade)

**Comment by cherub0507** [comment]
ImageGlass 8.10.9.27 works properly.

**Comment by bwisely** [comment]
same bug at my PC

**Comment by d2phap** [comment]
Probably duplicated of #1687. You can try enable WARP for IG 9:
- Press Windows + R, type `dxcpl`, press Enter
- Then force WARP on as described here https://github.com/d2phap/ImageGlass/issues/1687#issuecomment-1826305326

**Comment by mirh** [comment]
Unless hacked otherwise, I really don't think a W11 computer wouldn't even support dx12.
