### ISSUE TITLE
webview error - how to fix?

### ISSUE THREAD

**Issue by kolunio82** [d2phap/ImageGlass#1733]
### System information:
 - Windows OS version: 11 x64
 - ImageGlass version: latest

### To Reproduce
1. install
2. run

### Actual behavior:

error message
![2023-11-28 12_25_22-NVIDIA GeForce Overlay DT](https://github.com/d2phap/ImageGlass/assets/17217747/7a773c49-14d4-475f-83d5-f4a3bbc29795)

**Comment by d2phap** [comment]
Your WebView2 runtime is older than the one IG is using (version `119.0.2151.72`). Please update it https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download.

**Comment by kolunio82** [comment]
which file shoud i download?

**Comment by bwisely** [comment]
my issue is the same. and I already installed webview

**Comment by d2phap** [comment]
@kolunio82 https://go.microsoft.com/fwlink/p/?LinkId=2124703
