### ISSUE TITLE
AVIF images with a gain map

### ISSUE THREAD

**Issue by vaisest** [d2phap/ImageGlass#1735]
### System information:
 - Windows OS version: 11 23H2 22631.2715
 - ImageGlass version: 9.0.7.1125

### To Reproduce
1. Load AVIF gain map image

### Actual behavior:
![image](https://github.com/d2phap/ImageGlass/assets/4550061/81af58f1-9feb-4d4b-bbfe-8a3cc9def7e6)

### Expected behavior:
I would expect the image to be displayed.

### Additional context:
I believe Google's Ultra HDR format refers to the same HDR format of embedding a gain map. JPEG images however were displayed, although only in SDR.

[Here's Adobe's documentation on gain maps](https://helpx.adobe.com/camera-raw/using/gain-map.html), which contains [sample images](https://www.adobe.com/go/gainmap_sample_photos).

**Comment by d2phap** [comment]
Your AVIF file contains 2 frames, by default, ImageGlass will read all frames with MagickNET, convert to WicBitmapDecoder, and render on the viewer. Currently, getting frame with WicBitmapDecoder throws that error. It seems Windows WIC does not support it somehow.

You can make it works by adding `.avif` to the `SingleFrameFormats` setting to force ImageGlass reading only the first frame:
```json
// in igconfig.json file
"SingleFrameFormats": ".avif;.heic;.heif;.psd;.jxl;",
```

**Comment by vaisest** [comment]
Is actual support planned? These Gain Map images will probably start to get much more popular as e.g. the Google Pixel 8 added support for them.

**Comment by d2phap** [comment]
I will need to spend more time to check further. So no fixed plan.

**Comment by d2phap** [comment]
v9.0.8.1208 already fixes this by adding `.avif` to the `SingleFrameFormats` by default. That's all I can fix for now
