### ISSUE TITLE
Bad quality png img in V9

### ISSUE THREAD

**Issue by yfjuu6** [d2phap/ImageGlass#1737]
### System information:
 - Windows OS version: Version 23H2 (Windows 11)

 - ImageGlass version: All v9 But not V8

### To Reproduce
1. Install 9.0.7.1125
2. Open a PNG file
3. It's blurry
4. Remove 9.0.7.1125
5. Install 8.10.9.27 (stable)
6. Open a PNG file
7. Everything looks sharp

### Actual behavior:

I've just found ImageGlass and I was about to start using it Because it seemed to me the appropriate app,
But I've compared several Images in terms of quality on the default windows Photo and ImageGlass_9.0.7.1125_x64(the latest version) and I've found that the image quality
in windows Photo is better than the image quality in ImageGlass_9.0.7.1125_x64 although the "image quality" option in the setting is set to "100", then I downloaded the previous version (ImageGlass_Kobe_8.10.9.27_x64) and Re-compared it with windows Photo and I've found that the image quality is good and it's the same in both apps (ImageGlass_Kobe_8.10.9.27_x64 and windows Photo).
Finding :
- The image quality in the 8th versions is better than the image quality in 9th versions (stable or beta).
- The image quality in the 8th versions = the image quality in windows Photo(both are good).

has anyone discovered this?
why the image quality in 9th versions is bad But not in 8th versions?
I hope my meaning is clear.
Any help Please! Thanks advanced!

**Comment by worldsdream** [comment]
Duplicate:
https://github.com/d2phap/ImageGlass/issues/1716

**Comment by dabljues** [comment]
@siblount It doesn't work.

For 100% zoom (OG size), the `High quality bicubic` makes it bad. However, switching to `Nearest neighbor` for `<=100%` makes it sharp again

**Comment by siblount** [comment]
@dabljues This is a matter of personal preference. The best option in terms of image quality in both scenarios is `High quality Bicubic`. Nevertheless, changing the `When zoom > 100%` and `When zoom <= 100%` is how you address the blurriness.
