### ISSUE TITLE
ImageGlass becomes unusable when browsing a folder with 1000's of images

### ISSUE THREAD

**Issue by TomGrubbe** [d2phap/ImageGlass#1738]
### System information:
 - Windows OS version: Windows 11 Pro 22H2
 - ImageGlass version:  9.0.7.1125 (64-bit)

This performance bug also existed in version 8.

### To Reproduce
1. Associate image files (.jpg, .png, etc.) with ImageGlass.
2. In Windows explorer, brows to a folder containing 1000s of images, say 2000-5000 images.
3. Double click one of them so it opens in IG.
4. Try to navigate from image to image using the keyboard or mouse
5. It is unacceptably slow switching from one image to the next.  Making it pretty much unusable.

This happens whether or not the gallery panel is turned on.

### Actual behavior:

Switching between images when browsing a folder containing 1000s of images make ImageGlass unusable.

### Expected behavior:

Browsing a folder containing 1000s of images should switch between images as quickly as it does in a folder containing 10 images.

### Screenshots:
N/A

### Additional context:
N/A

**Comment by siblount** [comment]
I'm curious with this issue, so I tried reproducing it. I made a folder with 11,189 distinct images and fiddled around with some settings. Then, I added 10 subdirectories, each with about 1000 images into the mix.

Some potentially impacting settings: Active file watchdog was enabled, Image Booster caching set to 0, Gallery disabled. Recursive directory option was disabled.

I also had enough RAM and limited the CPU to cap at 2.4 GHz.

My findings:
 - Image Boost cache had no noticeable negative performance impact.
 - File watchdog had no noticeable performance impact.
 - At default, I have the "Gallery" disabled by default. But enabling it, caused a huge spike in CPU usage, and a noticeable delay of rendering the thumbnails for the Gallery while IG was generating the thumbnails.
 - Enabled the recursive directory option still had no noticeable performance impact.
 - Loading an image in a separate directory with a bunch of PSDs, though only 8 distinct PSDs, had little to no noticeable impact.

Though, for it to be "unacceptably slow switching from one image to the next. Making it pretty much unusable.", my findings could _not_ conclude this. There was a slowdown, yes, but not "unacceptably slow" or "unusable". 

@TomGrubbe Are the images you are viewing on the cloud? On OneDrive? Google Drive? etc.
Are you critically low on storage space on your C drive? 

My next guess is that multiple exceptions are being thrown each time Tom navigates to the next image. .NET Exceptions are very slow. That would explain IG being "unacceptably slow". The next question would be what?

Also, my next guess could be that the file types he's using causes a high amount of RAM, like with PSD files (#286). I do remember loading a PSD in v8 with multiple layers, UHD would take a century to load. But it seems in v9 that's no longer the case.

**Comment by TomGrubbe** [comment]
Thanks for looking into this @siblount.

1. The folder containing the images is a shared drive mounted on a Linux machine.
2. The physical disc is a WD MyBook external USB drive.

The problem was 1.

* If I copy the files to my PC's drive D (internal SSD) then ImageGlass flies through each image.
* If I attach the WD USB disc to my PC instead of using a shared drive ImageGlass flies through the image list.

So the problem was browsing a shared folder mounted on a Linux machine.  Funny thing is the Windows Photos app didn't have this problem.  But it may be using a different Windows API to access file info.

Anyway, there's nothing you need to fix.  You can close this issue.
