### ISSUE TITLE
annoying popups "Full Screen mode is enable Press F11 to exit Full Screen mode."

### ISSUE THREAD

**Issue by yfjuu6** [d2phap/ImageGlass#1739]
### Is your feature request related to a problem? Please describe.

Every time I enter to full screen mode by pressing F11 or by pressing the button in the toolbar "full screen (F11)", the popup notification (Tooltip) :
"Full Screen mode is enable
Press F11 to exit Full Screen mode."
appears for 3 seconds In the middle of the window. 
and When I exit fullscreen, I will also get a notification telling me :
"Full Screen mode is disabled".

This is something that I can recreate 100 out of 100 times and makes me wait for 3 seconds each time I enter or exit full screen to see the entire image or the spot covered by the popup for 3 seconds.
### Describe the solution you'd like

Is there a way to disable this popup?
If no, It would be better to create an option to control its display (show or hide).
Jsut like the option in Firefox when watching videos :
[How to remove press esc to exit full screen in firefox and chrome?](https://stackoverflow.com/questions/27989886/how-to-remove-press-esc-to-exit-full-screen-in-firefox-and-chrome)
[How do I remove annoying "Press Esc to exit full screen mode" message in Flash Video?](https://support.mozilla.org/en-US/questions/693559)
[Press ESC to exit Fullscreen Won't Go Away !!](https://answers.microsoft.com/en-us/microsoftedge/forum/all/press-esc-to-exit-fullscreen-wont-go-away/2870cd91-97bd-4e5c-bc7a-cc12caf203ac)
### Describe alternatives you've considered

Changing its location in a corner of the window, not in the middle.
### Additional context

We hope that this feature will be added!
Thanks advanced

**Comment by d2phap** [comment]
In-app message for window modes are removed in [ImageGlass 9.0.8.1208](https://github.com/d2phap/ImageGlass/releases/tag/9.0.8.1208)
