### ISSUE TITLE
502 Bad Gateway downloading

### ISSUE THREAD

**Issue by ToFran** [d2phap/ImageGlass#174]
Hello,
This issue is not directly related with the software, but all download links @ imageglass.org are down.

**Comment by d2phap** [comment]
Hi @ToFran 
Can you try again?
I can download now

**Comment by d2phap** [comment]
Update again:
There is sometimes a 502 Bad Gateway error.
I'm checking

**Comment by ToFran** [comment]
It is finally working on my end.

**Comment by d2phap** [comment]
Thanks @ToFran
