### ISSUE TITLE
Bug when minimizing a window with Window Fit On.

### ISSUE THREAD

**Issue by RVillaT** [d2phap/ImageGlass#1741]
### System information:
 - Windows OS version: Windows 11
 - ImageGlass version: ImageGlass_9.0.7.1125_x64.msi

### To Reproduce
1. Open any image. Window Fit On (F9).
2. Minimize the window by clicking on the minimize button.
3. The window minimizes and then maximizes itself as a completely empty window.

### Actual behavior:

The window cannot be minimized normally when the image has just been opened with Window Fit On. It maximizes itself as a completely empty window.

### Expected behavior:

The window should be able to be minimized at any time.

**Comment by d2phap** [comment]
Fixed in [ImageGlass 9.0.8.1208](https://github.com/d2phap/ImageGlass/releases/tag/9.0.8.1208)
