### ISSUE TITLE
Half-transparent images

### ISSUE THREAD

**Issue by inosik** [d2phap/ImageGlass#1744]
### System information:

 - Windows OS version: 10 (22H2)
 - ImageGlass version: 9.0.7.1125 (installed via Scoop)

### To Reproduce

1. Open a JPEG containing a plain white image

### Actual behavior:

Any image I view with ImageGlass has a transparency, even JPEGs.

### Expected behavior:

The image should be displayed properly.

### Screenshots:

The version installed via Scoop:

![ImageGlass_2023-12-01_09-28-05](https://github.com/d2phap/ImageGlass/assets/11393003/84aed541-b501-45b1-a326-187f05afeabf)

The Windows Store version:

![ImageGlass_2023-12-01_09-33-31](https://github.com/d2phap/ImageGlass/assets/11393003/7c9c8d01-383f-4f55-831d-340e72cf8ca1)

### Additional context:

Same with the Windows Store version. Let me know if I can provide more details.

**Comment by d2phap** [comment]
You can try disabling this setting
![image](https://github.com/d2phap/ImageGlass/assets/3154213/384e88d5-8864-43ca-88cd-bf7ada9855e5)

**Comment by inosik** [comment]
Yes, disabling this setting fixes this problem.
