### ISSUE TITLE
always open the main library

### ISSUE THREAD

**Issue by nobef** [d2phap/ImageGlass#1749]
If I have images (most of them) are in c:/users/images or d:/pictures it doesn't matter, then I want it to open by default, and not randomly open the last folder with 2 pictures. Is it possible to do this at least as an option? Why is such a simple idea of cataloging ignored by most developers in Windows?

**Comment by d2phap** [comment]
ImageGlass is not aim to be a photo organizer so I will not implement this feature.
But there is a hack that you can always load photos from a folder by creating `igconfig.admin.json` (similar to `igconfig.json`) with this content:

```
{
  "_Metadata": {
    "Description": "ImageGlass configuration file",
    "Version": "9.0"
  },
  "ShouldOpenLastSeenImage": true,
  "LastSeenImagePath": "path\\to\\the\\image.jpg"
}
```

Put this file in the startup folder of ImageGlass. Refer to https://imageglass.org/docs/app-configs to learn about ImageGlass' app config files.

**Comment by nobef** [comment]
@d2phap Thanks for the method with the config. But there is a strange argument for refusal. I don't understand what is the use case for the application. Open pictures through Explorer? Or always, contrary to logic, keep images everywhere except the image folder and open them differently through this application?
 Strange but typical logic inherent in old developers.
