### ISSUE TITLE
When the toolbar is disabled, the image takes part of the info bar on top

### ISSUE THREAD

**Issue by vivadavid** [d2phap/ImageGlass#1752]
### System information:
 - Windows 11 (23H2). 
 - ImageGlass 9.0.8.1208.

When the toolbar is disabled, the image takes part of the info bar on top. The bar is bigger than necessary (there's a lot of empty space below the text), so I'd suggest making the bar smaller.

### Screenshots:

![screenshot](https://github.com/d2phap/ImageGlass/assets/9334287/79bc132d-45ff-477b-9d92-dfabf321eec9)

**Comment by d2phap** [comment]
ImageGlass uses the native title bar of Windows, there is no customization. Unfortunately, there is no fix for this.

**Comment by vivadavid** [comment]
OK, thanks anyway!

**Comment by Barafu** [comment]
OK, you can not resize the title bar. But can you shrink image a little so it does not cover the title bar in this mode?

**Comment by worldsdream** [comment]
@d2phap shouldn’t it automatically know that there is a title bar and not overlap the image?

I don’t mind it. I really don’t. But it looks better if you can do some magic and ensure that the image doesn’t overlap the title bar.
