### ISSUE TITLE
Not showing the first/last image while holding the arrow key (many images, without the loop)

### ISSUE THREAD

**Issue by petonemec** [d2phap/ImageGlass#1754]
### System information:
 - Windows OS version: 11 Home 22H2
 - ImageGlass version: 9.0.8.1208 (64-bit)

### To Reproduce
1. Disable the option 'Loop back to the first image when reaching the end of the image list' in Settings -> Image.
2. Open a folder with MULTIPLE images, not just a couple.
3. Fast move to the first/last image using the left/right arrow keys (press and HOLD until the end of the list).
4. When reaching the beginning/end, the last loaded image remains displayed instead of loading the actual first/last image. Also, the bubble 'Reached the first/last image' just blinks in the view.

### Actual behavior:
The folder has plenty of images. When the 'Loop back to the first image...' option is disabled, the app doesn't load/show the first/last image in that folder when reaching the end of the list by holding the arrow keys. Instead, it shows the last loaded image (from somewhere in the middle of the list). The bubble 'Reached the first/last image' shows and disappears immediately, not allowing one to catch the info text.

### Expected behavior:
After reaching the end of the list by holding the arrow keys, the first/last image loads to the view, and the bubble 'Reached the first/last image' shows for a short time (as when reaching the end of the list by repeatedly pressing the arrow keys to select the images one-by-one).

### Screenshots:
![image](https://github.com/d2phap/ImageGlass/assets/17578104/d4c73e20-d1ee-48a7-b225-cb5c18e61c2e)

### Additional context:
The problem does not occur if there are just a few images in a folder.

**Comment by d2phap** [comment]
Should be fixed in [ImageGlass 9.0.9.1230](https://github.com/d2phap/ImageGlass/releases/tag/9.0.9.1230)

**Comment by petonemec** [comment]
Thank you very much.

Dňa št 28. 12. 2023, 12:18 Phap Dieu Duong ***@***.***>
napísal(a):

**Comment by petonemec** [comment]
https://github.com/d2phap/ImageGlass/assets/17578104/ab820dce-fee1-4bdb-9d8e-8b47bc6e8876

Hello,
I have checked this behavior in 9.0.9.1230. Have a look at the attached screen record, please. Sometimes it works, sometimes not. When I started screen recording, it worked more often... :-O Anyway, I wish you a Happy New Year.
