### ISSUE TITLE
Zoom custom values are not respected when using + and - keybord shortcuts.

### ISSUE THREAD

**Issue by RVillaT** [d2phap/ImageGlass#1756]
### System information:
 - Windows OS version: Windows 11
 - ImageGlass version: 9.0.8.1208

### To Reproduce
1. Enter Zoom custom values (for example : 5; 10; 15; 20; 25; 30; 35; 40; 45; 50; 55; 60; 65; 70; 75; 80; 85; 90; 95; 100; 110; 120; 130; 140; 150; 160; 180; 200; 220; 240; 260; 300; 340; 380; 420; 460; 500; 550; 600; 750).
2. Use + or - keyboard shortcuts to zoom.
3. Custom values are not respected. The zoom goes from 10 to 10 or 20 to 20 without taking into account values ending in 5.

### Actual behavior:

Zoom custom values are not respected when using + and - keybord shortcuts. Zoom goes from 10 to 10 or 20 to 20 and skips other values. Zooming with the mouse wheel works normally and respects custom values. Using MenuHotkeys in igconfig.json to configure new shortcuts works normally too.

### Expected behavior:

Zooming when using + and - keybord shortcuts should respect custom values.

**Comment by d2phap** [comment]
Should be fixed in [ImageGlass 9.0.9.1230](https://github.com/d2phap/ImageGlass/releases/tag/9.0.9.1230)
