### ISSUE TITLE
Window position shift down on open when taskbar is on top of screen

### ISSUE THREAD

**Issue by wx00** [d2phap/ImageGlass#1759]
### System information:
 - Windows OS version: Windows 10
 - ImageGlass version: 9.0.8.1208 (64-bit)
 - Display scaling: 100% (so we know this problem is not related to scaling)

### To Reproduce
1. Windows taskbar position set to top of screen.
2. Open ImageGlass 9,do not maximize window, maybe move window to align its top edge to taskbar's bottom edge to better see it moving.
3. Close ImageGlass 9.
4. Open ImageGlass 9 again.

### Actual behavior:

ImageGlass 9 move down some pixels from last close position every time it opens.

### Expected behavior:

ImageGlass 9 stay at the same position every time.

### Additional context:

ImageGlass 8 correctly remember last position...

**Comment by d2phap** [comment]
@wx00 
This is as expected, IG 9 uses the new WinApi [`SetWindowPlacement()`](https://github.com/d2phap/ImageGlass/blob/c0800aba0a9e935b955a35b52c3afc0d3ecb084a/Source/Components/ImageGlass.Settings/WindowPlacement/WindowSettings.cs#L30) for saving/restoring window size and location.
Other modern Windows apps also have the same behavior.
