### ISSUE TITLE
Main window GUI doesn't display UI controls in correct sizes if Windows display settings is scaled

### ISSUE THREAD

**Issue by cihlen** [d2phap/ImageGlass#176]
Main window GUI doesn't display UI controls in correct sizes if Windows display settings is scaled.
I have a 4K 65" TV in my livingroom so the resolution is 3840x2160 and the scale setting is set to 300%.

Main window:
![imageglass_scaling problems](https://cloud.githubusercontent.com/assets/1988708/24552756/00fa2392-1628-11e7-8d1d-2bca496ad3b5.png)

My Display settings:
![mydisplaysettings](https://cloud.githubusercontent.com/assets/1988708/24552791/297ce430-1628-11e7-8b37-4b56e06f562b.png)

**Comment by d2phap** [comment]
Hi,

This issue will be absolutely fixed in the upcoming release next few weeks. As it is a duplicated issue of #32

Thanks
