### ISSUE TITLE
Cannot open APNG files

### ISSUE THREAD

**Issue by Bishop0702** [d2phap/ImageGlass#1761]
### System information:
Windows 10 21H2
ImageGlass 9.0.8.1208
.Net 8.0.0
WebView2 119.0.2151.97

### To Reproduce
Open any .apng file.

### Actual behavior:
Cannot open the image. See screenshot for error message.

### Expected behavior:
Open the image normally.

### Screenshots:
![Untitled](https://github.com/d2phap/ImageGlass/assets/43810531/a6583bb4-c326-4b85-a594-4e84ffee5164)

Magick.NET-Q16-HDRI-OpenMP-x64: FailedToExecuteCommand '"ffmpeg.exe" -nostdin -loglevel error -i "C:/Users/M/AppData/Local/Temp/magick-qCOPHBBRh1_y3eWA7dJHoOkjVUJSMObG" -an -f rawvideo -y -pix_fmt rgba -vcodec webp -lossless 1 "C:/Users/M/AppData/Local/Temp/magick-fm77yQQDEcJmwsx9b_VlueOXC87l8iaC'“ (The system cannot find the file specified. ) @ error/delegate.c/ExternalDelegateCommand/519

at lmageMagick.MagicklmageCollection.NativeMagicklmageCollection.ReadFile(IMagickSettings'1 settings) in /_/src/Magick.NET/Native/MagicklmageCollection.cs:line 796

at lmageMagick.MagicklmageCollection.Addlmages(String fileName. IMagickReadSettings'1 readSettings, Boolean ping) in/_/src/Magick.NET/MagicklmageCollection.cs:line 2006

### Additional context:
If rename the .apng file to .png, then only the first frame will be loaded (which is expected).

Tried installing ffmpeg and adding it to %PATH%, but still get the same error.

**Comment by Bishop0702** [comment]
Reinstalling ImageGlass then putting ffmpeg.exe into the installation folder solved the issue. But now encounters the same slow render issue as described in #1731.

**Comment by Bishop0702** [comment]
Closed.

**Comment by d2phap** [comment]
With [ImageGlass 10.0.4.819](https://github.com/d2phap/ImageGlass/releases/tag/10.0.4.819), you can just install [APNG codec plugin](https://imageglass.org/plugins).
