### ISSUE TITLE
Image is displayed squashed depending on the window size (version 9.0.8 only)

### ISSUE THREAD

**Issue by skycommand** [d2phap/ImageGlass#1762]
### System information:
 - Windows OS version: 10.0.19045.3693
 - ImageGlass version: 9.0.8.1208

### To Reproduce
1. Download the sample image I provided below.
2. Open it in ImageGlass
3. Resize the viewing window. Try different sizes. (Edited 2023-12-24)

### Actual behavior:

The image could appear horizontally or vertically squashed depending on the size of the window. Not every size squashes the image. But some sizes do. (Edited 2023-12-24)

### Expected behavior:
The image must appear as is.

### Screenshots:

Screenshot:
![Sample image inside ImageGlass](https://github.com/d2phap/ImageGlass/assets/17097175/1270c744-b907-40b9-a62f-f2e80f097099)

Sample image:
![Test](https://github.com/d2phap/ImageGlass/assets/17097175/8025188c-d689-4647-b575-5b3ac0907918)

Sample image in ZIP format (to prevent accidental delivery error):
[Sample image.zip](https://github.com/d2phap/ImageGlass/files/13599043/Sample.image.zip)

### Additional context:

- In the screenshot I provided, please notice the garbled text. Please compare with the sample for a better understanding.
- This problem doesn't appear in version 9.0.7.

Thanks in advance.

**Comment by d2phap** [comment]
I'm unable to reproduce this (Windows 11). I will try to check it on Windows 10

**Comment by d2phap** [comment]
I tried my best to reproduce the issue on VirtualBox but no luck.

https://github.com/d2phap/ImageGlass/assets/3154213/8f9de9fb-6c2b-4c64-9564-76ce6b4e375c

**Comment by skycommand** [comment]
Please try testing it in 1920×1080 resolution. (That's my screen's size.) Also, please try frameless mode, and full screen mode too. And finally, this issue appeared on version 9.0.8 only.

I'll try to record a video for you later today.

**Comment by skycommand** [comment]
I reproduced it in a virtual machine. Here is a link to the video. (For some reason, GitHub doesn't allow me to attach big videos.)

[Video](https://1drv.ms/v/s!Am9yc_jG9eAOkGKpqERq9_P2eoOc?e=i50BXJ)

This issue manifests even without maximizing. The image starts horizontally squashed. When I test different size, it becomes vertically squashed.

**Comment by skycommand** [comment]
I've reproduced the problem in a virtual machine. [Here is a video of it](https://1drv.ms/v/s!Am9yc_jG9eAOkGKpqERq9_P2eoOc).

Furthermore, I've discovered that just resizing the window alone triggers the problem. Here are a few examples:

<details>
<summary>Sample 1</summary>

This image is okay:

![1 Okay](https://github.com/d2phap/ImageGlass/assets/17097175/0cfa82bd-4d6f-49fa-b143-1bfc223018c0)

This image is horizontally squashed:

![3 Horizontally squashed](https://github.com/d2phap/ImageGlass/assets/17097175/3a8e6328-c460-44c0-9e5a-48ec553734d4)

This image is vertically squashed:

![5 Vertically squashed](https://github.com/d2phap/ImageGlass/assets/17097175/9c4acb9f-f5c7-43eb-8680-0de7bbdf5645)
</details>
<details>
<summary>Sample 2</summary>

This image is okay:

![2 Okay](https://github.com/d2phap/ImageGlass/assets/17097175/964cf659-6257-4624-813c-dc0bf7c8333c)

This image is horizontally squashed:

![4 Horizontally squashed](https://github.com/d2phap/ImageGlass/assets/17097175/c38bef4c-6e7a-404f-b421-31f6097c0394)

This image is vertically squashed:

![6 Vertically squashed](https://github.com/d2phap/ImageGlass/assets/17097175/512d380d-0d47-49cd-a180-545be2cada38)
</details>

**Comment by d2phap** [comment]
Thanks for the details. I followed your guide with different images but still could not reproduce it.

![image](https://github.com/d2phap/ImageGlass/assets/3154213/c1e53558-0f5a-434c-a473-5e79c7302d3f)


Have you tried changing the image interpolation settings if it help?
![image](https://github.com/d2phap/ImageGlass/assets/3154213/e3c50593-cbfa-4e5a-bdbc-ccd796259465)

**Comment by skycommand** [comment]
No. I have not changed that settings. And in the virtual machine, I have changed no setting at all.

If it helps, my display is a 1080p (1920x1080) at 166 PPI.

**Comment by LazyBoot** [comment]
I'm seeing the same issues
Notably it only happens at 100% zoom, any more or less and the issue goes away
win10 19045.3803
And it only seems to happen on some window sizes
I did also test multiple interpolation settings, with no change.

**Comment by skycommand** [comment]
@LazyBoot Hello. I'm trying to find out why we can reproduce it but d2phap can't. Would you mind telling us what is your screen resolution and PPI?

**Comment by LazyBoot** [comment]
I'm not sure how to find my PPI, but resolution is 3440z1440 (100Hz) running at 100% scaling in windows.

**Comment by skycommand** [comment]
Thanks a lot. I used this web utility to obtain my PPI: <https://dpi.lv/>

**Comment by LazyBoot** [comment]
> Thanks a lot. I used this web utility to obtain my PPI: https://dpi.lv/

ok, I have 110 PPI according to that (34" ultrawide screen)

Also, in case it matters for the bug reproduction, I *am* running a multi-monitor setup. (2nd is just a 1080p one though.)

**Comment by Tomoko1** [comment]
I have the same issue and I also have a 1080p screen with 166PPI, if that helps. 👍 I'm also on the latest version of Windows 10.

**Comment by d2phap** [comment]
My PPI is 341, 250%.

I tried changing to image interpolation for 100% scale to `HighQualityBicubic`. Can you help to test this build?
https://drive.google.com/file/d/1SQiv6sF_5cslfYokEiKTr3NcZjBZ4PFU/view?usp=sharing

**Comment by Opicka879** [comment]
> My PPI is 341, 250%.
> 
> I tried changing to image interpolation for 100% scale to `HighQualityBicubic`. Can you help to test this build? https://drive.google.com/file/d/1SQiv6sF_5cslfYokEiKTr3NcZjBZ4PFU/view?usp=sharing

I am little bit drunk right now, but it seems to be ok now for me :)

**Comment by floppyD** [comment]
> My PPI is 341, 250%.
> 
> I tried changing to image interpolation for 100% scale to `HighQualityBicubic`. Can you help to test this build? https://drive.google.com/file/d/1SQiv6sF_5cslfYokEiKTr3NcZjBZ4PFU/view?usp=sharing

It looks better, but still scaling images needlessly. This 640x480 test image is still being resized to 640x481.

Test image
![img1](https://github.com/d2phap/ImageGlass/assets/29208110/c7c719d4-3381-4314-b60b-2d6531dfdc21)

Test image on IG
![img2](https://github.com/d2phap/ImageGlass/assets/29208110/7bfc7fab-ffdc-4d0d-87c3-440efc8a6a80)

Screenshot
![new](https://github.com/d2phap/ImageGlass/assets/29208110/f52a13b4-015d-4a41-b577-89771729eb5b)

**Comment by LoliMilkQ** [comment]
> My PPI is 341, 250%.
> 
> I tried changing to image interpolation for 100% scale to `HighQualityBicubic`. Can you help to test this build? https://drive.google.com/file/d/1SQiv6sF_5cslfYokEiKTr3NcZjBZ4PFU/view?usp=sharing

It looks good. 
But the short sides are expanded by 1 pixel, seems like a waste of performance.

**Comment by d2phap** [comment]
I probably found the root issue. It happened when the drawing location (X, Y) is float number, Direct2D somehow scaled it incorrectly with 1 extra pixel (as reported https://github.com/d2phap/ImageGlass/issues/1762#issuecomment-1868206717). For example with image 400x400 px:
- (x, y) = (100, 100): ok no issue
- (x, y) = (100.5, 100): wider 1px
- (x, y) = (100, 100.5): longer 1px

So I reverted back to use `NearestNeighbor` for 100% scaling. Can you help to test this build if it's fixed:
https://drive.google.com/file/d/1WEqziBZCasnowFYBMon-y3mRib50QUET/view?usp=sharing

**Comment by LoliMilkQ** [comment]
> I probably found the root issue. It happened when the drawing location (X, Y) is float number, Direct2D somehow scaled it incorrectly with 1 extra pixel (as reported [#1762 (comment)](https://github.com/d2phap/ImageGlass/issues/1762#issuecomment-1868206717)). For example with image 400x400 px:
> 
>     * (x, y) = (100, 100): ok no issue
> 
>     * (x, y) = (100.5, 100): wider 1px
> 
>     * (x, y) = (100, 100.5): longer 1px
> 
> 
> So I reverted back to use `NearestNeighbor` for 100% scaling. Can you help to test this build if it's fixed: https://drive.google.com/file/d/1WEqziBZCasnowFYBMon-y3mRib50QUET/view?usp=sharing

Not completely valid. If the image a bit larger then the monitor, the pixels will deviate. It's obvious on low resolution monitors. 
Is there any way to force the drawing location to integer number?
![QQ截图20231223171333](https://github.com/d2phap/ImageGlass/assets/74607787/5f5f3be2-b8b0-445b-865e-d07cfce9fc93)

**Comment by d2phap** [comment]
> If the image a bit larger then the monitor, the pixels will deviate

It will be scaled according to your Image Interpolation setting.
The fix applies for 100% scaling.

**Comment by LoliMilkQ** [comment]
> > If the image a bit larger then the monitor, the pixels will deviate
> 
> It will be scaled according to your Image Interpolation setting. The fix applies for 100% scaling.

It is 100% scaling.

**Comment by d2phap** [comment]
@LoliMilkQ I think I didn't really get your comment. Can you send a full screenshot of IG window?

**Comment by LoliMilkQ** [comment]
> @LoliMilkQ I think I didn't really get your comment. Can you send a full screenshot of IG window?
OK

![01](https://github.com/d2phap/ImageGlass/assets/74607787/82403cc1-7e82-44f4-8d88-fd1c54a002f0)
![02](https://github.com/d2phap/ImageGlass/assets/74607787/e7c235a0-0b43-4ccd-8459-a9154b96adb0)

[sample image.zip](https://github.com/d2phap/ImageGlass/files/13758678/sample.image.zip)

**Comment by Opicka879** [comment]
> I probably found the root issue. It happened when the drawing location (X, Y) is float number, Direct2D somehow scaled it incorrectly with 1 extra pixel (as reported [#1762 (comment)](https://github.com/d2phap/ImageGlass/issues/1762#issuecomment-1868206717)). For example with image 400x400 px:
> 
> * (x, y) = (100, 100): ok no issue
> * (x, y) = (100.5, 100): wider 1px
> * (x, y) = (100, 100.5): longer 1px
> 
> So I reverted back to use `NearestNeighbor` for 100% scaling. Can you help to test this build if it's fixed: https://drive.google.com/file/d/1WEqziBZCasnowFYBMon-y3mRib50QUET/view?usp=sharing

Images where I had issues are ok now.

**Comment by d2phap** [comment]
Published [ImageGlass 9.0.9.1230](https://github.com/d2phap/ImageGlass/releases/tag/9.0.9.1230).

@LoliMilkQ if your issue still persists, I will reopen your ticket #1789

**Comment by dojima** [comment]
This is still an issue on 9.1.8.723 with Windows 10 19045.4651.

It seems to be highly dependent upon the window size and the position of the image within the window.  The window size in my sample videos is 479×553.  I subsampled the video chroma information to 4:2:0 for compatibility reasons, but hopefully you can still see that the image isn't represented correctly after zooming out and back in.  The easiest way to workaround the issue for now seems to be to drag the image to either the left or right edge; doing that seems to correctly align everything.

https://github.com/user-attachments/assets/5228716d-1241-48cc-aec9-937cb27b44c0

https://github.com/user-attachments/assets/3f4584f0-92a8-4a18-bbab-efa7208e8f72

The test image I'm using can be found here:  https://www.rtings.com/tv/learn/chroma-subsampling

**Comment by LoliMilkQ** [comment]
> Published [ImageGlass 9.0.9.1230](https://github.com/d2phap/ImageGlass/releases/tag/9.0.9.1230)。
> 
> [@LoliMilkQ](https://github.com/LoliMilkQ) if your issue still persists, I will reopen your ticket [#1789](https://github.com/d2phap/ImageGlass/issues/1789)

Still unresolved on 9.3.2.520 Windows 11 26100.4061.
