### ISSUE TITLE
Image list does not reload when delete the last in list

### ISSUE THREAD

**Issue by duckimann** [d2phap/ImageGlass#1763]
### System information:
 - Windows OS version: Windows 10 build 19044.3086
 - ImageGlass version: 9.0.8.1208

### To Reproduce
![081223_07-22-58-AM_xVpGvcKfSS](https://github.com/d2phap/ImageGlass/assets/46382253/77afe85e-c172-4c91-8c65-ec5cfeec27b1)

### Expected behavior:
Image list to be reloaded and display the previous image

**Comment by d2phap** [comment]
Should be fixed in [ImageGlass 9.0.9.1230](https://github.com/d2phap/ImageGlass/releases/tag/9.0.9.1230)
