### ISSUE TITLE
Could not load user settings

### ISSUE THREAD

**Issue by morty6688** [d2phap/ImageGlass#1764]
### System information:
 - Windows OS version: 22631.2715
 - ImageGlass version: 9.0.8.1208

### To Reproduce
1. Just open it then the error window pop

### Actual behavior:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at ImageGlass.Settings.Config.LoadThemePack(Boolean darkMode, Boolean useFallBackTheme, Boolean throwIfThemeInvalid, Boolean forceUpdateBackground) in D:\_GITHUB\@d2phap\ImageGlass\Source\Components\ImageGlass.Settings\Config.cs:line 1534
   at ImageGlass.Settings.Config.Load() in D:\_GITHUB\@d2phap\ImageGlass\Source\Components\ImageGlass.Settings\Config.cs:line 967
   at ImageGlass.Program.Main() in D:\_GITHUB\@d2phap\ImageGlass\Source\ImageGlass\Program.cs:line 63
```

### Screenshots:

![image](https://github.com/d2phap/ImageGlass/assets/26590220/ddaa86ae-28fc-4dc3-be6e-07b23d5abd9b)

**Comment by d2phap** [comment]
Check if the default theme pack (Kobe) is missing.

**Comment by morty6688** [comment]
> Check if the default theme pack (Kobe) is missing.

Looks not missing
![image](https://github.com/d2phap/ImageGlass/assets/26590220/b7d8becc-e7c9-43ee-8e12-533fd761f60e)

**Comment by d2phap** [comment]
Where did you download ImageGlass? There should be 2 default theme packs for v9.0:
![image](https://github.com/d2phap/ImageGlass/assets/3154213/e084faa9-65e4-4c25-9937-092b9ddbd18f)

I suspect your Kobe theme is for v8. Now check if you have this `igtheme.json` file:
![image](https://github.com/d2phap/ImageGlass/assets/3154213/f4110f26-164b-4fda-be7c-d0c6c961bf36)

the content is like this:
![image](https://github.com/d2phap/ImageGlass/assets/3154213/a02b52fc-b22f-4f9f-ab9b-cb3bc8d9f5f9)

**Comment by morty6688** [comment]
> Where did you download ImageGlass? There should be 2 default theme packs for v9.0: ![image](https://private-user-images.githubusercontent.com/3154213/289353343-e084faa9-65e4-4c25-9937-092b9ddbd18f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMDY1NTgsIm5iZiI6MTcwMjIwNjI1OCwicGF0aCI6Ii8zMTU0MjEzLzI4OTM1MzM0My1lMDg0ZmFhOS02NWU0LTRjMjUtOTkzNy0wOTJiOWRkYmQxOGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTBUMTEwNDE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yzk3ODkyNDk1MTY1MDZhNGYwMTIyZWVhY2JmNDcxMTE1OTVlMmEyMmY1ZTllZjIyMTlkNzgyM2YwZGJjZTUwYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xAycFVbEb9ztJKbS4A8Hw-xOLJiHJ2s68h0GTPB2OLc)
> 
> I suspect your Kobe theme is for v8. Now check if you have this `igtheme.json` file: ![image](https://private-user-images.githubusercontent.com/3154213/289353381-f4110f26-164b-4fda-be7c-d0c6c961bf36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMDY1NTgsIm5iZiI6MTcwMjIwNjI1OCwicGF0aCI6Ii8zMTU0MjEzLzI4OTM1MzM4MS1mNDExMGYyNi0xNjRiLTRmZGEtYmU3Yy1kMGM2Yzk2MWJmMzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTBUMTEwNDE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjRkZTEwOTljZTM5YTExODUyZmU3NmE5OTljNTJhYTNhOWMzYzVkNGVkMDI5MzYyOGIwZjgzYjkwZGJlMDI0ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.AXfAgSE8b8nDyAdXWT_DO_UraCAcukw2IkzGEUK_Ctg)
> 
> the content is like this: ![image](https://private-user-images.githubusercontent.com/3154213/289353460-a02b52fc-b22f-4f9f-ab9b-cb3bc8d9f5f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMDY1NTgsIm5iZiI6MTcwMjIwNjI1OCwicGF0aCI6Ii8zMTU0MjEzLzI4OTM1MzQ2MC1hMDJiNTJmYy1iMjJmLTRmOWYtYWI5Yi1jYjNiYzhkOWY1ZjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTBUMTEwNDE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjQ1ZWJiMmQ1N2I5NmNmZjdiZmEzMjI4ODBlY2E0YjZkNjJhOTJkM2NhODgyMDZhZWQyYjY1ZDQ3NDE5OWNlZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.gPpCJnhEvx0_MOqJnoUWPygHPEdyxSdcE3fdeVxfu6M)

Thx for ur reply! I uninstalled it and cleaned the persisted theme directory, then reinstall it through scoop. Now it can work.
