### ISSUE TITLE
Could not set ImageGlass as default photo viewer

### ISSUE THREAD

**Issue by tsargh** [d2phap/ImageGlass#1765]
### System information:
 - Windows OS version: Windows 10 22H2 (OS Build 19045.3693)
 - ImageGlass version: 9.0.8.1208

### To Reproduce
1. Install ImageGlass 9 from Microsoft Store.
2. Click button when prompted by installer to set ImageGlass as default photo viewer.

### Actual behavior:
ImageGlass reports an error "Could not set ImageGlass as default photo viewer".

### Expected behavior:
Installer should be able to set ImageGlass as default photo viewer.

### Screenshots:
![Could not set ImageGlass as default photo viewer](https://github.com/d2phap/ImageGlass/assets/1041995/69df94dc-4685-4010-974d-d5594e655e85)

### Additional context:
I had ImageGlass 8.10.9.27 installed as well at the time I tried this - I've since uninstalled that. I'll try installing ImageGlass 9 on a machine which has never had ImageGlass on it before.

**Comment by tsargh** [comment]
Same error occurs on a different machine which has never had ImageGlass installed on it before - clicking "Make default" results in a registry permissions error (like screenshot above).

**Comment by d2phap** [comment]
As the error message, your account doesn't have permission to do it, try running IG as admin if it helps.

You can send me a video if the problem still persists.
