### ISSUE TITLE
Skip forward/backward 10 images

### ISSUE THREAD

**Issue by ohei2** [d2phap/ImageGlass#1767]
### Is your feature request related to a problem? Please describe.

I am often working with large collections of chronological screenshots and need to browse those images. As it stands I find myself often forwarding through 50 or even 100 images one by one, knowing e.g. that the next 20 images cannot be what I am looking for.  If you do this 2 or 3 times on a day, you starting to feel that this is not what it could be.

### Describe the solution you'd like

I more than once wished for an option to skip ahead or backwards an amount of images.  This would make it two versus 20 keystrokes in the above example.

While left and right works as forward and backwards, e.g. CTRL-Left and CTRL-Right could be used to skip.

**Comment by d2phap** [comment]
You can add a custom toolbar button to do this in v9.1.
Open Settings > Toolbar > Toolbar buttons, click "Add a custom button" button and use this JSON. In the `Arguments` field, put `10` for skipping forward 10 images, put `-10` for skipping backward 10 images.

```json
{
  "Id": "Btn_SkipForward10Images",
  "Type": "Button",
  "Text": "Skip forward 10 images",
  "Image": "C:\\path\\to\\icon.svg",
  "Alignment": "Left",
  "CheckableConfigBinding": "",
  "DisplayStyle": "Image",
  "OnClick": {
    "Executable": "IG_ViewImage",
    "Arguments": [10]
  }
}
```

You may need to restart ImageGlass after adding a custom button to take effect.

**Comment by ohei2** [comment]
This solves the issue indeed. Thank you very much for looking into it.
