### ISSUE TITLE
Bookmark or open in new window for later use

### ISSUE THREAD

**Issue by ohei2** [d2phap/ImageGlass#1768]
### Is your feature request related to a problem? Please describe.

I often browse through large collections of screenshots, searching for something particular. During this process I quite often find other images relevant to me that I cannot deal with at the moment.

### Describe the solution you'd like

I would like to have an option to bookmark images for reopening at a later time.

### Describe alternatives you've considered

It would also work to just have an option to open the current image in a new window, that would be like cheap bookmarks, but still fine for the workflow.

**Comment by d2phap** [comment]
Duplicated of #141
