### ISSUE TITLE
Every image looks washed

### ISSUE THREAD

**Issue by floppyD** [d2phap/ImageGlass#1770]
### System information:
 - Windows OS version: 10
 - ImageGlass version: 9.0.8.1208

### To Reproduce
1. Open image

### Screenshots:
They look like this
![image](https://github.com/d2phap/ImageGlass/assets/29208110/3dab3292-0fa6-4338-8118-f4958dc43c9e)

Original image
![Windows 10 Stock 3840x2160](https://github.com/d2phap/ImageGlass/assets/29208110/30f7cea8-0510-47cb-8996-d1f4d40d32d8)

### Additional context:
Started happening after the latest update.

**Comment by d2phap** [comment]
See https://github.com/d2phap/ImageGlass/issues/1744#issuecomment-1836201850

**Comment by floppyD** [comment]
Weird, but works.
