### ISSUE TITLE
IG displays an update reminder after detecting the platform is unsuitable for an update

### ISSUE THREAD

**Issue by daved163g** [d2phap/ImageGlass#1772]
### System information:
 - Windows OS version: 10.0.19045
 - ImageGlass version: 8.10.9.27

### To Reproduce
1. No action required (automatic process).

### Actual behavior:
IG displays an update message stating that an update is not possible because the system does not support the update. In this case it is because of the Windows build. This can happen more than once a day, depending on how IG is invoked.

### Expected behavior:
Allow the user to suppress future update messages.

### Screenshots:
![IG update failure prompt](https://github.com/d2phap/ImageGlass/assets/25829031/acc4cc1d-ef76-4f29-b346-9aa03265eb47)

### Additional context:
It would be nice if IG could support older versions of Windows. People who maintain a stable build that works for them are usually not prepared to update for any reason. For a "simple" image viewer there seems little reason to keep shifting the goalpost.

**Comment by d2phap** [comment]
The "64-bit Windows" check is a bug that reported here #1712

You can uncheck this option to suppress the Check for Update dialog:
![image](https://github.com/d2phap/ImageGlass/assets/3154213/a4e49c9a-1bd2-4731-a6de-e0deb2fe8256)
