### ISSUE TITLE
Configuration files version 9 - Unable to use igconfig.default.json or igconfig.admin.json

### ISSUE THREAD

**Issue by stefanorova** [d2phap/ImageGlass#1773]
### System information:
 - Windows OS version: Win 11, Win Server 2022
 - ImageGlass version: 9.0.8.1208

### To Reproduce
  1. Open image glass and configure preferences (lenguage IT, remove auto updates, theme dark)
  2. Copy file igconfig.jon located at AppData\Local\ImageGlass and raname to igconfig.default.json (or igconfig.admin.json)
  2.5. Instead of copy the file we also tried to manually create the content of the file as follow:
  {
     "_Metadata":{
        "Description":"ImageGlass configuration file",
        "Version":"9.0"
     },	
          "QuickSetupVersion":9,
	  "Language":"Italian.iglang.json"
  }
  4. Put the generated file in C:\Program Files\ImageGlass
  5. Clear AppData\Local\ImageGlass to simulate first opening
  6. The app will ignore default and admin configuration file

### Actual behavior:

Done the steps above the app open whitout getting any startup config.
In version 8 we were able to make it work whitout any problem, is that a bug or did we make any error?

### Expected behavior:

Like in version 8 app should read file in startup directory and get initial or forced configuration

**Comment by d2phap** [comment]
Thanks @stefanorova for the bug report. It was a bug that IG 9 only looks for those files in the Config folder instead of the Installed folder.
A temporary solution while waiting for the next release is to put your files in Config folder: `%LocalAppData%\ImageGlass\`

**Comment by d2phap** [comment]
Should be fixed in [ImageGlass 9.0.9.1230](https://github.com/d2phap/ImageGlass/releases/tag/9.0.9.1230)
