### ISSUE TITLE
Custom zoom level not respected for decimal values

### ISSUE THREAD

**Issue by jwl-7** [d2phap/ImageGlass#1774]
### System information:
 - Windows OS version: 23H2
 - ImageGlass version: ImageGlass 9.0.8.1208

### To Reproduce
1. Use any zoom mode
2. Press `Z` to bring up zoom menu
3. Type in any float ex: `35.57`
4. Zoom value does not change

### Actual behavior:

When setting a custom zoom level, float values such as `24.5` are not respected and the zoom value does not change.

### Expected behavior:

When setting a custom zoom level, float values should change the zoom level to the exact decimal.

**Comment by d2phap** [comment]
Should be fixed in [ImageGlass 9.0.9.1230](https://github.com/d2phap/ImageGlass/releases/tag/9.0.9.1230)
