### ISSUE TITLE
Fast viewing images does not render all images

### ISSUE THREAD

**Issue by notosapien** [d2phap/ImageGlass#1775]
### System information:
 - Windows OS version: Windows 10 22H2
 - ImageGlass version: 9.0.8.1208

### To Reproduce
Steps to reproduce the behaviour:
1. Have around 50-100 images in a folder
2. Open the first image
3. Go through the images by holding down the right button
4. Image doesn't show all images as I hold right button

### Actual behavior:
In this latest version if I want to view hundreds of images fast I usually open the first one then hold down the right button to go through the images quickly but the image won't go quickly and it will stop after a few then if I let go the right button then only it will show the image where I stopped at. ( Example: viewing 100 photos, open 1 then hold right button it will show 1,2,3 then freeze at 3 and after release right button at photo 20, it will show photo 20)

### Expected behavior:
Older version like version 8.11.12.6, when there's hundreds of images in a folder, I can open the first image and hold down the right button and it will go through all images pic by pic. (Example: viewing 20 photos, open first one then hold down right button it will show 1,2,3,4,5,6,7,8,9....20 quickly)

Thanks

**Comment by d2phap** [comment]
Hi @notosapien,

What you described above is a performance issue of IG 8. This is one of the reasons IG v9 is rewritten from scratch.
- In v8: if photo 2 is being loaded into memory and users open photo 2, IG continues to load photo 1, renders it, unloads it, then loads photo 2. It's synchronous loading mechanism. This caused huge performance issue when users accidentally open a huge image, the whole app becomes hanging for a while.
- v9 fixed this issue with the asynchronous loading mechanism: if photo 1 is being loaded into memory and users open photo 2, IG cancels the loading progress of photo 1, frees the memory, and only loads photo 2.

**Comment by rotemdan** [comment]
Hi, I just noticed this issue after installing v9. I think the fast browsing of images was a fantastic and useful feature allowing to very quickly browse through many images, while keeping track on where I'm at.

Without this ability, holding down the left or right arrow key doesn't provide an effective user experience, since it is difficult to know the what the current image is. The gallery view is too small for that and I personally disabled it (it takes space and I want to have the images as large as possible).

For now I will uninstall version 9 and reinstall version 8 instead. I can't really use the application without this feature.

**Comment by notosapien** [comment]
> Hi, I just noticed this issue after installing v9. I think the fast browsing of images was a fantastic and useful feature allowing to very quickly browse through many images, while keeping track on where I'm at.
> 
> Without this ability, holding down the left or right arrow key doesn't provide an effective user experience, since it is difficult to know the what the current image is. The gallery view is too small for that and I personally disabled it (it takes space and I want to have the images as large as possible).
> 
> For now I will uninstall version 9 and reinstall version 8 instead. I can't really use the application without this feature.

Yea. I don't understand why is this an issue as stated by the author, press and holding the arrow button to go through 1000 images without hiccups, seems like a better performing software then the one latest which can't, I don't know.. :> I too have reverted back to version 8

**Comment by d2phap** [comment]
Okay, I added a setting to revert back to v8 behavior: `EnableImageAsyncLoading`.
In the next version, you can uncheck the option `Enable image asynchronous loading` or set `EnableImageAsyncLoading` to `false` in `igconfig.json` file.

![image](https://github.com/d2phap/ImageGlass/assets/3154213/e788b5db-a80f-4fc9-a4a2-e5e9fa67aced)

**Comment by notosapien** [comment]
Thanks so much @d2phap, really appreciated the effort, I will give it a try when it comes out and report back.

**Comment by d2phap** [comment]
[ImageGlass 9.0.10.201](https://github.com/d2phap/ImageGlass/releases/tag/9.0.10.201) is released. To switch to v8's behaviour
- Close all ImageGlass windows
- Open `igconfig.json` file in any text editor (Notepad, VS Code,...)
- Change value of `EnableImageAsyncLoading` from `true` to `false`:
  ![image](https://github.com/d2phap/ImageGlass/assets/3154213/772c965f-337e-407f-8463-22a6e6257f35)
- Save and launch ImageGlass again

There is no UI for this setting in v9.0.10 yet. I will add it in v9.1.

**Comment by gshawn3** [comment]
Thank you so much for adding this @d2phap! The previous behavior was driving me crazy :)

I can confirm that it works exactly as it should after setting `EnableImageAsyncLoading` to `false`. Thanks again.

**Comment by notosapien** [comment]
I also can confirm that it's working! Thanks @d2phap !
