### ISSUE TITLE
Toolbar Zoom In and Out Ignores Custom Zoom Levels

### ISSUE THREAD

**Issue by ghost** [d2phap/ImageGlass#1778]
### System information:
 - Windows OS version: Windows 10 Pro 22H2
 - ImageGlass version: 9.0.8.1208 x64

### To Reproduce
1. Open .jpg or .png image.
2. Uncheck "Use smooth zooming" in settings and load default zoom levels
3. Apply and "OK" out of settings.
5. Use the toolbar Zoom In and Zoom Out buttons (or toolbar hamburger button dropdown zoom in and zoom out)

### Actual behavior:
Zoom level changes by small amounts that don't match up with default zoom levels.
The zoom value also shifts as you zoom in and out repeatedly.

### Expected behavior:
Zoom level changes by one user-set increment.

**Comment by d2phap** [comment]
Should be fixed in [ImageGlass 9.0.9.1230](https://github.com/d2phap/ImageGlass/releases/tag/9.0.9.1230)

**Comment by ghost** [comment]
Thank you! ❤️
