### ISSUE TITLE
Windows version and prerequisites not detected

### ISSUE THREAD

**Issue by PeterVeg** [d2phap/ImageGlass#1779]
### System information:
 - Windows OS version:  22H2
 - ImageGlass version: 8.9.6.2
 -  .NET Desktop Runtime: 8
 - Webview2 120.0.2210.61

### To Reproduce
1. Help menu
2. Click "A new version is avaibable"
3. Your system does not meet the new version's requirements!
❌ 64-bit Windows
❌ .NET Desktop Runtime

### Actual behavior:
From a 8.9.6.2, my system does not have the correct prerequierments

### Expected behavior:
I want to update

### Screenshots:
![image](https://github.com/d2phap/ImageGlass/assets/25248556/10450a0b-3282-4048-a97a-8b860ffbf3f5)

### Additional context:
Installation can be done.

**Comment by d2phap** [comment]
- IG 8.10 or below does not detect OS architecture correctly, see #1712, fixed in v8.11
- IG 9 requires .NET 8, WebView2. It's recommended to uninstall v8 before installing v9. You can read the details here https://imageglass.org/news/introducing-the-new-imageglass-version-9-88
