### ISSUE TITLE
Rotate and clip then save, the clip result will be wrong.

### ISSUE THREAD

**Issue by suyangzuo** [d2phap/ImageGlass#1780]
### System information:
 - Windows OS version: 11 23H2
 - ImageGlass version: 9.08.1208

### To Reproduce
1. Rotate the image to left or right
2. Set the clip frame
3. Save
4. The result will be wrong

**Comment by suyangzuo** [comment]
Sometime, even just rotate the image and save `(no clip)`, the result preview will also be wrong `(but the actual result image is correct)`.

<img width="700" alt="PixPin_2023-12-16_11-43-46" src="https://github.com/d2phap/ImageGlass/assets/50766353/13a2ea24-ea6e-4a4b-9156-4959c47c6125">

**Comment by d2phap** [comment]
Should be fixed in [ImageGlass 9.0.9.1230](https://github.com/d2phap/ImageGlass/releases/tag/9.0.9.1230)
