### ISSUE TITLE
Windows Store apps icons are displayed with the ImageGlass icon in Start Menu.

### ISSUE THREAD

**Issue by DimMan88** [d2phap/ImageGlass#1781]
### System information:
 - Windows OS version: Windows 10 Pro 22H2
 - ImageGlass version: 9.0.8.1208 (64-bit)

### Actual behavior:
Windows Store apps icons are displayed with the ig icon in Start Menu.

### Screenshots:
![image](https://github.com/d2phap/ImageGlass/assets/71668463/1a819266-5dfe-4bff-a118-717907c35e3d)

**Comment by d2phap** [comment]
This is a known icon cache issue of Windows #664
