### ISSUE TITLE
Enabling or disabling fade transition between images

### ISSUE THREAD

**Issue by jmacasd** [d2phap/ImageGlass#1783]
In series 8, image transitions were not in use, however, I found kind of a annoying because looking for the best one from let's say 20-30 pictures thar are similar, it consumes more time to view.

A suggested solution it's a checkbox or something to enable or disable fade transition.

**Comment by d2phap** [comment]
You can uncheck this option:
![image](https://github.com/d2phap/ImageGlass/assets/3154213/f89079e4-8736-4fe5-98d8-65163525a0a4)
