### ISSUE TITLE
Auto zoom messes up aspect ratio/resolution

### ISSUE THREAD

**Issue by floppyD** [d2phap/ImageGlass#1786]
### System information:
 - Windows OS version: 10
 - ImageGlass version: 9.0.8.1208

### To Reproduce
1. Open 640x480 image
2. ImageGlass will scale it to 640x481

### Screenshots:

Sample
![480](https://github.com/d2phap/ImageGlass/assets/29208110/1506148a-708d-4399-b122-1468e1bc26db)

Result
![autozoom](https://github.com/d2phap/ImageGlass/assets/29208110/1b740458-b4d1-4639-943d-32151e4b251b)

### Additional context:

Pressing 0 for "Actual size" displays the same behavior.

**Comment by d2phap** [comment]
Probably duplicated #1763. Please help to test this build if it's fixed: https://github.com/d2phap/ImageGlass/issues/1762#issuecomment-1868183149
