### ISSUE TITLE
Image quality is low when zoom =100%

### ISSUE THREAD

**Issue by LoliMilkQ** [d2phap/ImageGlass#1789]
### System information:
 - Windows OS version: Win10 22H2
 - ImageGlass version:  9.0.8.1208
 - 2K monitor （2560*1440）

### To Reproduce
1. open an image (size close to window)
2. click 'Actual size' button

### Actual behavior:
I just open my game capture, it look like a low resolution images.
But it looks pretty good when zoom >100% or <100%.

### Screenshots:
Sample:
![00](https://github.com/d2phap/ImageGlass/assets/74607787/020ec80a-458e-41a7-a4f0-c8c8b48caef8)

Contrast:
![01](https://github.com/d2phap/ImageGlass/assets/74607787/28961e51-4f51-4e9d-ad5d-2d7ff1a2279a)
![02](https://github.com/d2phap/ImageGlass/assets/74607787/e73c113a-fb64-4e92-9a45-29ec38d40131)

**Comment by nbb1967** [comment]
Windows 10 Pro 22H2
ImageGlass 9.0.8.1208
Same problem

Resaved to PNG (lossless):

![bug](https://i.ibb.co/VxXqL5Q/100.png)

**Comment by d2phap** [comment]
Probably duplicated #1763. Please help to test this build if it's fixed: https://github.com/d2phap/ImageGlass/issues/1762#issuecomment-1868183149
