### ISSUE TITLE
Main window position not maintained between launches.

### ISSUE THREAD

**Issue by synner88** [d2phap/ImageGlass#1790]
### System information:
 - Windows OS version: MS Windows 10 version 22H2 (OS Build 10.0.19045.3803)
 - ImageGlass version:  9.0.8.1208 (64-bit)

### To Reproduce
1. Set Windows Taskbar to Top position: Windows Settings -> Personalization -> Taskbar -> Taskbar location on screen = Top
2. Launch ImageGlass and move main window position to top-left with just a pixels next to the screen edge & taskbar.
3. Close and re-launcha ImageGlass.

### Actual behavior:
Upon re-launch, main program window is moved **exactly 40px** down the screen.

### Expected behavior:
Main program windows should remember & restore its position & size upon re-launching the app.

### Screenshots:
![1_close_position](https://github.com/d2phap/ImageGlass/assets/29090601/b9b3ace7-7be6-4538-b9e8-ca3b2a9f1e34)
![2_reopen_position](https://github.com/d2phap/ImageGlass/assets/29090601/f342a644-bb85-40ec-888a-92cb0516861a)

### Additional context:
_n/a_

**Comment by d2phap** [comment]
Should be fixed in [ImageGlass 9.0.9.1230](https://github.com/d2phap/ImageGlass/releases/tag/9.0.9.1230)
