### ISSUE TITLE
Images always dark filter

### ISSUE THREAD

**Issue by Shadow322** [d2phap/ImageGlass#1791]
### System information:
 - Windows OS version: Microsoft Windows 11 Pro 10.0.22621
 - ImageGlass version: 9.0.8.1208 and 8.11.12.6

### To Reproduce
1. open an image
2. view image

### Actual behavior:
When I open an image it always has a dark filer ontop of the image if I use v8.11 the images show without this filter

### Expected behavior:
image without dark filder like in v8.11.12.6

### Screenshots:
![dark filter](https://github.com/d2phap/ImageGlass/assets/15938645/04bb1605-c272-4464-a476-019657613e75)
![no dark filter](https://github.com/d2phap/ImageGlass/assets/15938645/12c87ba2-2bf3-4132-8afb-c8062a8a5a28)

**Comment by d2phap** [comment]
Hi @Shadow322, please uncheck the setting "Enable image transition effect": https://github.com/d2phap/ImageGlass/issues/1744#issuecomment-1836201850

I will disable this by default in the next version.

**Comment by d2phap** [comment]
This setting is disabled by default in [ImageGlass 9.0.9.1230](https://github.com/d2phap/ImageGlass/releases/tag/9.0.9.1230)
