### ISSUE TITLE
Open zip/rar/7z archives

### ISSUE THREAD

**Issue by npgraham1** [d2phap/ImageGlass#1793]
It would be great if ImageGlass could open archives like zip, rar, 7z, and similar and display images found within.

FastStone MaxView has this feature which is fairly useful (for example, downloads from Google Photos and many other cloud services are automatically zipped if there's more than one file in the download), and I'd like to switch entirely to ImageGlass. I'm not sure how much I care about unzipping & decrypting strictly in-memory like MaxView does for security purposes, but I suppose it would be nice if ImageGlass didn't create and then delete lots of temp files whenever you open & close zip files.

**Comment by d2phap** [comment]
Duplicated of #254
