### ISSUE TITLE
Image doesn't look clear immediately when opened with ImageGlass

### ISSUE THREAD

**Issue by Marko-98** [d2phap/ImageGlass#1794]
### System information:
 - Windows OS version: Windows 11 Pro 23H2 Build 22631.2861
 - ImageGlass version: 9.0.8.1208 (64-bit)

### To Reproduce
1. Open the image file

### Actual behavior:
When you open the image file of non-standard dimensions, images with text will won't be clear.

### Expected behavior:
A clear image with text normally shown.

### Screenshots:
Arrows point to zoom level and where issue is present:
![Screenshot_3](https://github.com/d2phap/ImageGlass/assets/129692860/93a38ce4-58d3-4ed1-9d72-c937c5fcf05f)

If I zoom in and zoom out back to 100%, picture is clearly shown without issues:
![Screenshot_4](https://github.com/d2phap/ImageGlass/assets/129692860/3603dbc5-c629-4a65-b25b-b7175306007c)

### Additional context:
I tried changing settings but nothing helped.

**Comment by d2phap** [comment]
Probably duplicated of #1762. I created a new build for testing https://github.com/d2phap/ImageGlass/issues/1762#issuecomment-1868233184

**Comment by Marko-98** [comment]
@d2phap tested with the build you provided in #1762; I can confirm issue is not present. Thanks! 🙂
