### ISSUE TITLE
Problems and new Features to the cropping function

### ISSUE THREAD

**Issue by H1ghSyst3m** [d2phap/ImageGlass#1795]
### Is your feature request related to a problem? Please describe.
Hi Guys, I love ImageGlass since the newest updates, I am using it to crop my image datasets into a square, it works wonderful, and it's really simple and fast, so it doesn't take me much time to crop hundreds of images manually, because of the fast using [C then crop, then CTRG + S]. 
But there are some problems.
1. When I crop an image to 1:1 then it shows me a stretched view of the cropped image in the previous aspect ratio, and when I refresh it, then it shows me the image correctly in 1:1.
2. Normally when I crop an image to 1:1, then I always take the biggest possible length, but I always have to resize the crop view to the max.
3. I selected 1:1 as default, but when I press (C) to crop, then it shows me the cropping area with the aspect ratio from the image, I always have to resize the cropping area a little bit to let him use 1:1 again
4. Many people are used to press button "mouse3" to move in the image while cropping from other programs, but in ImageGlass it doesn't do anything.
5. When I zoom out and in while cropping, then changes the cropping selection that I had previously. As Example: I have a 16:9 image and want to crop 1:1. I select left 1:1, then I select the cropping area, now when I zoom out or in, then the selected area is completely changed

### Describe the solution you'd like
1. When I Crop an image then save it, then it should show the image instantly in the correct aspect ratio without stretching.
2. I would like it, if it can default select the biggest possible area.
3. When I select 1:1 as default, then it should show me the 1:1 when I start cropping again
4. Add Middle Mouse Button function (mouse3) to let us move in the image
5. Fix the cropping area to the image instead to the view of the user, so when I zoom out or in, then the cropping area should be still the same

**Comment by afgks** [comment]
I also don't like how the crop function works. When I selected a part of the image to crop then zoom in and out, the selected area should resize along with the image.

**Comment by KonoVitoDa** [comment]
> I also don't like how the crop function works. When I selected a part of the image to crop then zoom in and out, the selected area should resize along with the image.

Still no fix for this? What a shame. This new behavior is awful and makes 9.0 unusable to me.

**Comment by d2phap** [comment]
@KonoVitoDa 
> Still no fix for this? What a shame. This new behavior is awful and makes 9.0 unusable to me.

There is no such a shame here, this kind of comment is useless.
Stop nagging, open a PR, it's open source!

**Comment by KonoVitoDa** [comment]
> @KonoVitoDa
> 
> > Still no fix for this? What a shame. This new behavior is awful and makes 9.0 unusable to me.
> 
> There is no such a shame here, this kind of comment is useless. Stop nagging, open a PR, it's open source!

Oh, my bad, sorry for expressing myself like this. It just annoyed me that such a clear and basic issue is still not fixed after months.

**Comment by d2phap** [comment]
Improvements for Crop tool in [ImageGlass 9.2 Beta](https://github.com/d2phap/ImageGlass/releases/tag/9.1.8.1104)

- The selection coordinates now follow image source instead of the viewer source
- Zooming or panning does not change the selection
- Supports resizing selection area by dragging from any edge, not just from the 8 anchor points
- Supports keeping selection when clicking outside of it, thus avoiding accidentally losing the selection
- Supports dragging middle mouse to pan the image when Crop tool is enabled
- Supports snap-to-pixel selection with pixel-level precision
- Correctly sets default selection based on Crop settings and Aspect ratio


![image](https://github.com/user-attachments/assets/5a1ad563-1637-41e3-a55e-4faac6040a3d)
