### ISSUE TITLE
Error `0xc01e0006` after leaving open for a long time

### ISSUE THREAD

**Issue by Ruin0x11** [d2phap/ImageGlass#1797]
### System information:
 - Windows OS version: Windows Server 2022 (21H2 20348.2113)
 - ImageGlass version: 9.0.8.1208

### To Reproduce
1. Open an image.
2. Leave the window open for a long time.

### Actual behavior:
After a while, the program will show the error `0xc01e0006`. It's not a crash since I can still interact with the main window as usual, but clicking "Quit" will close the program.

### Expected behavior:
I would be able to leave the program open for as long as I wanted with no errors appearing.

### Screenshots:
<img width="448" alt="2023-12-28 10_59_06-New Issue · d2phap_ImageGlass - Chromium" src="https://github.com/d2phap/ImageGlass/assets/6700637/cfdd9f24-dee8-45be-b1a8-a2f1c525829f">

**Comment by d2phap** [comment]
@Ruin0x11 can you try [this build 1305](https://drive.google.com/file/d/1_qTiGxV7u0SuQ0B8PG2eug_z1nWnEgnc/view?usp=sharing) if the issue still persists?

**Comment by d2phap** [comment]
Okay so should be fixed in [ImageGlass 9.0.10.201](https://github.com/d2phap/ImageGlass/releases/tag/9.0.10.201)
