### ISSUE TITLE
.jfif files do not appear in ImageGlass list of images

### ISSUE THREAD

**Issue by SankFrinatra** [d2phap/ImageGlass#1798]
### System information:
 - Windows OS version: 10.0.19045 Build 19045
 - ImageGlass version: 9.0.8.1208

### To Reproduce
1. Open a folder in File Explorer that has a .jfif file and another type of image file (.jpg, .png, etc)
2. Open the .jfif or the other file type in ImageGlass
3. Notice that .jfif will not appear in the image list that ImageGlass shows

### Actual behavior:

.jfif files do not appear in the ImageGlass list of images (i.e. the numbered list of files in the top left, shown as 1/40 or, generally, 1/x). When opening .jfif files, the numbered list will show 0/x photos (the photo is incorrectly listed as number 0, but ImageGlass notices the rest of the non-.jfif files). When opening other image files, .jfif files are ignored. This happens even when .jfif files are set to open with ImageGlass in Default Programs.

.jfif files can be opened with ImageGlass, but ImageGlass cannot navigate to other images in the folder (even other .jfif files) without "forgetting" the .jfif (as in, you cannot navigate back to it in ImageGlass).

### Expected behavior:

.jfif files should show up in the list of images that ImageGlass counts and displays.

**Comment by d2phap** [comment]
You can manually add it in app Settings > File type associations > File formats, click "Add" button:

![image](https://github.com/d2phap/ImageGlass/assets/3154213/333c4a0d-756c-4b6a-a0da-10678ff362b5)

V9.0.9.1230 already includes it by default.
