### ISSUE TITLE
No icon appears in the taskbar when an image is opened in version 9.0.9.1230.

### ISSUE THREAD

**Issue by RVillaT** [d2phap/ImageGlass#1799]
### System information:
 - Windows OS version: Windows 11
 - ImageGlass version: 9.0.9.1230

### To Reproduce
1. Install version 9.0.9.1230.
2. Open any image.
3. -> The window icon does not appear in the taskbar.
4. Minimize the window.
5. -> Image cannot be maximized again since its icon does not appear in the taskbar.

### Actual behavior:

When an image is opened, no icon appears in the taskbar. If the window is minimized, it is therefore impossible to maximize the window again. We also cannot navigate between the different open windows. The image processes appear correctly in the task manager.

### Expected behavior:

Open windows should appear correctly in the taskbar (as in previous versions).

### Additional context:

This problem makes it impossible to use version 9.0.9.1230. I had to reinstall version 9.0.8.1208.

**Comment by d2phap** [comment]
Should be fixed in [ImageGlass 9.0.9.1230 (updated)](https://github.com/d2phap/ImageGlass/releases/tag/9.0.9.1230). Please redownload v9.0.9.1230 and install again.

**Comment by patrickbergner** [comment]
![image](https://github.com/d2phap/ImageGlass/assets/63791229/b11fa02a-006f-4ecc-9a48-96408bcdea05)

A new release would've been nice to avoid this
