### ISSUE TITLE
[enhancement] Mouse buttons 4 and 5 should move navigate to previous/next images in the folder

### ISSUE THREAD

**Issue by psbj** [d2phap/ImageGlass#18]
I would love to see ImageGlass add this, the same way web browsers and windows file explorer use 4 and 5 for back/forward or previous/next when navigating.

It is a minor inconvenience to move my hand to the arrow keys on the keyboard or move the cursor to the next/previous buttons on the top menu.

**Comment by d2phap** [comment]
Thank you. I got your issue!

**Comment by exaunique** [comment]
+1

**Comment by d2phap** [comment]
Mouse button 4, 5 and middle mouse button are now supported:
https://github.com/d2phap/ImageGlass/commit/aa10e1676ea9f0913b8f610564e4b651c27ad205
