### ISSUE TITLE
Can't save pasted image, ctrl s or save button doesnt promt for file explorer to save the image

### ISSUE THREAD

**Issue by EgeGurkan** [d2phap/ImageGlass#1801]
### System information:
 - Windows OS version: windows 11 22631.2861
 - ImageGlass version:  imageglass 9.0.9.1230

### To Reproduce
1. ctrl v from clipboard
2. try ctrls or save button
3. 
4. 

### Actual behavior:

cant save pasted image

### Expected behavior:

to be able to save it

### Screenshots:

dont need

**Comment by d2phap** [comment]
Just pushed a fix for the next release. An alternative solution is using "Save As" (Ctrl+Shift+S).

**Comment by d2phap** [comment]
I created a build for testing this, you can download it here: https://drive.google.com/file/d/1_qTiGxV7u0SuQ0B8PG2eug_z1nWnEgnc/view?usp=sharing

**Comment by EgeGurkan** [comment]
working thanks!
