### ISSUE TITLE
Missing from Taskbar

### ISSUE THREAD

**Issue by tboy-123** [d2phap/ImageGlass#1802]
### System information:
 - Windows OS version: W 10 LTSC 21H2
 - ImageGlass version: 9.0.9.1230 (64-bit)

### To Reproduce
1. Double click on image file, ImageGlass will show the image, but the program icon will not appear on Taskbar.
2. Open again same or another image and then the Icon will appear.
3. 
4. 

### Actual behavior:

Missing icon in Windows Taskbar after first start of ImageGlass.

### Expected behavior:

icon in Windows Taskbar after opening an image

**Comment by d2phap** [comment]
@tboy-123 refer to https://github.com/d2phap/ImageGlass/issues/1799#issuecomment-1872099476
