### ISSUE TITLE
In v9 Slideshow does not show slideshow end message

### ISSUE THREAD

**Issue by CodeMarc11** [d2phap/ImageGlass#1805]
Windows 11 Home x64 23H2, ImageGlass v9.0.9 x64

Ever since ImageGlass v9 came out, when a slideshow ends, it no longer shows a message about it. If the timer is displayed, it just hangs at 00:01. v8 would show "Slideshow paused" for a moment and hide the timer.

### Steps to reproduce:

1. Enable "Show slideshow countdown" in Slideshow settings.
2. Open image in a folder and start a slideshow (F12).
3. When the last image is reached, timer counts down to "00:01" then stops and the same image continues to display. I have interval set to 10, in case that matters.

### Expected behavior
When the timer ends on the last image, "Slideshow paused" (or "Slideshow ended") should be displayed momentarily and the timer hidden. This was the behavior in v8.

**Comment by d2phap** [comment]
I restored to the v8 behaviour for the next release!

**Comment by CodeMarc11** [comment]
Great! Thanks.

**Comment by d2phap** [comment]
I created a build for testing this, you can download it here: https://drive.google.com/file/d/1_qTiGxV7u0SuQ0B8PG2eug_z1nWnEgnc/view?usp=sharing

**Comment by CodeMarc11** [comment]
I tried it out, and the fix works! Thanks.

Small suggestion for default settings: Layout > Viewer > Zooming
When zoom > 100% default is "Nearest neighbor".

I suggest changing this default to "Multi-sample linear", to match the default for "When zoom < 100%". I think the zoom method is more important when zooming up (> 100%) since the resulting image is bigger, so a "higher quality" algorithm is preferable to the "lowest quality" (i.e. pixelated) algorithm.

**Comment by d2phap** [comment]
Thanks @CodeMarc11 for confirming.
I want to keep "Nearest neighbor" for zoom > 100% for being consistent with v8 and other photo viewing/editing apps.
