### ISSUE TITLE
Could not open a PSD file

### ISSUE THREAD

**Issue by kukuro-kt** [d2phap/ImageGlass#1806]
### System information:
 - Windows OS version: Win11: 10.0.22621.2861
 - ImageGlass version: 9.0.9.1230 (64-bit)

### To Reproduce
open this image:
https://drive.google.com/file/d/1kQFRPe7RpZ4Yic42zb8J9-Thcm3YCVeE/view?usp=sharing

### Actual behavior:
![image](https://github.com/d2phap/ImageGlass/assets/143474178/f4746c61-11fd-4021-857a-61b072c8bef4)

### Expected behavior:
I think ImageGlass supports PSD file.

### Additional context:
I tried Magick.NET by my self and opened this file successfully.
I didn't carefully check the source code of ImageGlass, so I'm not sure where is the difference.

**Comment by d2phap** [comment]
Hi @kukuro-kt 
I tried opening your PSD file with IMDisplay and got the same error

![image](https://github.com/d2phap/ImageGlass/assets/3154213/32c5388f-0f10-42ab-ab3a-f8fef9b73af7)

ImageMagick version 7.1.1-10 Q16 HDR
![image](https://github.com/d2phap/ImageGlass/assets/3154213/46eaaf06-f994-4ecf-9ce8-8d59a6ff1710)

Also same error with MagickViewer:
![image](https://github.com/d2phap/ImageGlass/assets/3154213/4ece21c7-bf0c-49c2-a25a-d2ba93dc440a)

It seems upstream issue, can you help to report this to [MagickNET](https://github.com/dlemstra/Magick.NET/issues) team?

**Comment by d2phap** [comment]
Should be fixed in v9.0.11
