### ISSUE TITLE
Cannot open .webp images

### ISSUE THREAD

**Issue by xiaweichuliang** [d2phap/ImageGlass#1807]
### System information:
 - Windows OS version: win11
 - ImageGlass version: v9.0.8.1208 64-bit

### To Reproduce
1. opening .webp files and shows that "Magick.NET-Q16-HDRI-OpenMP-x64: insufficient image data in file xxx" but it can be normally opened in Honeyview
2. here is the comparison of the two software:
![image](https://github.com/d2phap/ImageGlass/assets/71426054/1a983133-6ff8-4637-8544-0814d219eb16)

3. 
4. 

### Screenshots:

![image](https://github.com/d2phap/ImageGlass/assets/71426054/0fd35ac2-4d40-4d25-b855-37bb7ea6003f)

**Comment by xiaweichuliang** [comment]
and i update Imageglass to v9.0.9.... later, but it still cannot open the .webp files

**Comment by d2phap** [comment]
@xiaweichuliang I can't help to check without a sample file, can you attach it here?

According to the error message, your webp file might be corrupted: "insufficient image data", you can report this issue to [MagickNET](https://github.com/dlemstra/Magick.NET/issues) team and don't forget to attach a sample file.

**Comment by xiaweichuliang** [comment]
@d2phap Sorry, Github doesn't allow me to send .webp files.  I compress some example files into this zip. And i've update the comparison of Honeyview and Imageglass, i don't think it's the "insufficient image data" problem because Honeyview can open them normally.
[rwgn113.zip](https://github.com/d2phap/ImageGlass/files/13807439/rwgn113.zip)

**Comment by d2phap** [comment]
Hi @xiaweichuliang 
I have checked your files, it seems upstream issue with MagickNET. Can you help to report this to them? with your sample files, too!

https://github.com/dlemstra/Magick.NET/issues

**Comment by xiaweichuliang** [comment]
OK, I've already added a new issue to them. https://github.com/dlemstra/Magick.NET/issues/1505

**Comment by d2phap** [comment]
Should be fixed in v9.0.11
