### ISSUE TITLE
Unable to launch ImageGlass even with .Net 8.0 installed

### ISSUE THREAD

**Issue by Derion-ux** [d2phap/ImageGlass#1808]
![Error](https://github.com/d2phap/ImageGlass/assets/65355704/3dd5a911-f475-4882-b256-11c5b75f7c30)
### System information:
 - Windows OS version: Win10
 - ImageGlass version: 9

### To Reproduce
1. Installed .Net 8
2. Installed ImageGlass 9

### Actual behavior:
Keep getting the "Download .net" message upon launching

### Expected behavior:
Launching of the program.

**Comment by d2phap** [comment]
@Derion-ux what .NET 8 release did you download and install? It should be `.NET Desktop Runtime 8.0.0` or use this link (x64): https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-8.0.0-windows-x64-installer

![image](https://github.com/d2phap/ImageGlass/assets/3154213/1d2c40c5-3e94-4e0a-82c6-63f3896a94f5)

**Comment by Derion-ux** [comment]
Yes, the correct verion was installed. Is Microsoft Store required?

**Comment by mrwiora** [comment]
I knew that it will be an interesting thing with those additional required packages....

Microsoft released meanwhile Version 8.0.1 of this .NET Runtime - but the installer package does not replace the 8.0.0 version. It installs it side-by-side. So I uninstalled the 8.0.0. Version, tried to start imageglass - which didn't work.

- Uninstalled 8.0.1 again
- Reinstalled 8.0.1 again

And now I have the same issue :) - cannot start Imageglass on this installation.

https://dotnet.microsoft.com/en-us/download/dotnet/8.0

![image](https://github.com/d2phap/ImageGlass/assets/2744285/9d0083e6-5aa8-4839-bf03-b0787724e00a)

**Comment by d2phap** [comment]
@mrwiora 

I tested on my Virtual Machine Win10 22H2:
- Install .net 8.0.0, IG 9 works
- Uninstall .net 8.0.0, IG 9 does not work
- Install .net 8.0.1, IG works again


![image](https://github.com/d2phap/ImageGlass/assets/3154213/2e642429-7c9d-4dee-885f-6aef19f00b08)

**Comment by mrwiora** [comment]
mh. bad - because in my case it doesn't work

![image](https://github.com/d2phap/ImageGlass/assets/2744285/0508001f-b97a-4e03-9260-259babf03ead)

I will try it on a clean install and report back

**Comment by d2phap** [comment]
@mrwiora 
I think you installed “.NET Runtime”, but IG requires “.NET Desktop Runtime”

**Comment by mrwiora** [comment]
yap... you were right. :)  I guess case closed. thanks!

**Comment by d2phap** [comment]
@Derion-ux can you confirm as well?

**Comment by Derion-ux** [comment]
Yes, I can run the program after installing the desktop runtime.
