### ISSUE TITLE
View RGBA channels separately.

### ISSUE THREAD

**Issue by Leogh21** [d2phap/ImageGlass#181]
Add 4 buttons to view RGBA channels separately.
It would be extremely useful for designers and developers.

**Comment by MattOstgard** [comment]
As a game developer this would be amazing.

**Comment by d2phap** [comment]
Note: To separate a channel in Magick.NET

```csharp
using (var newImg = imgM.Separate(Channels.Red).First())
{
    //
}
```

**Comment by d2phap** [comment]
This feature is ready in IG Moon: https://imageglass.org/moon

**Comment by d2phap** [comment]
Added 2 more channels: Black and Alpha
