### ISSUE TITLE
Theme to make ImageGlass 9 look like ImageGlass 8

### ISSUE THREAD

**Issue by ghost** [d2phap/ImageGlass#1813]
### Is your feature request related to a problem? Please describe.
I dislike ImageGlass 9's themes. I dislike the new toolbar icons. I dislike the new navigation arrow buttons, they're too big.

### Describe the solution you'd like
I want a theme that makes ImageGlass 9 look like ImageGlass 8. It has nice colors, and the toolbar icons and navigation arrow buttons are discreet yet noticeable, unlike its new counterpart. Please help. I appeal to good taste.

### Describe alternatives you've considered
I looked at available themes, none are agreeable.

### Additional context
![ig8](https://github.com/d2phap/ImageGlass/assets/124498221/4f6c18df-060b-4ceb-838f-917083f422e6)

**Comment by d2phap** [comment]
Hi, you can follow the docs to create the theme pack for v9: https://imageglass.org/docs/theme-pack

**Comment by ghost** [comment]
@d2phap I don't know what you wanted me to do and I'm not good at tech but I tried anyway and it did not go well. The theme file for version 8 didn't have a similar structure/format compared to version 9, so I couldn't edit it in a way that made sense to me. And simply moving over version 8's icons to version 9 looked bad, I don't know how exactly but it was noticeably off. Please reconsider my request.
