### ISSUE TITLE
Can't open image with remote monitor in different directions.

### ISSUE THREAD

**Issue by kukuro-kt** [d2phap/ImageGlass#1814]
### System information:
Windows OS version: Win11: 10.0.22621.2861
ImageGlass version: 9.0.9.1230 (64-bit)

### To Reproduce
1. Prepare computer A with two monitors perpendicular to each other:
![image](https://github.com/d2phap/ImageGlass/assets/143474178/8b671726-c237-4a87-9a51-8f7983639dc1)

2. Use computer B with two horizontal monitors to remote control computer A with `mstsc.exe`
![image](https://github.com/d2phap/ImageGlass/assets/143474178/d03350b4-eedb-4c27-9afe-d4d7edb500b0)

3. Open some images on computer A from computer B by remote control

### Actual behavior:
Cannot open with error:
![image](https://github.com/d2phap/ImageGlass/assets/143474178/337df864-1fed-44e0-9932-9e23fd33099a)

### Expected behavior:
Open image

### Additional context:
I'm not sure whether it is necessary to have 4 monitors to reproduce this bug.
I guess it is also reproducable with a single vertical monitor (computer A) and a single horizontal monitor (computer B).
According to error message, I think this bug occurred because monitor directions mismatch.
`Windows Photos` works well.

**Comment by d2phap** [comment]
Hi @kukuro-kt 
Will it still work when you press Continue button?

**Comment by kukuro-kt** [comment]
> Hi @kukuro-kt Will it still work when you press Continue button?

No, Continue is the same as Quit.

**Comment by d2phap** [comment]
@kukuro-kt 
Can you check if this build fix the issue?
https://drive.google.com/file/d/1_qTiGxV7u0SuQ0B8PG2eug_z1nWnEgnc/view?usp=sharing

**Comment by kukuro-kt** [comment]
> @kukuro-kt Can you check if this build fix the issue? https://drive.google.com/file/d/1_qTiGxV7u0SuQ0B8PG2eug_z1nWnEgnc/view?usp=sharing

Preliminary test results indicate that this BUG seems to have been fixed.
I will adjust my monitors for in-depth testing to confirm it recently .
It will take some time because it takes me several hours to commute between my two computers.

I will update the result before next Tuesday.

**Comment by kukuro-kt** [comment]
Confirmed fixed under all monitor direction combinations.
