### ISSUE TITLE
Copy image as file

### ISSUE THREAD

**Issue by LeOndaz** [d2phap/ImageGlass#1815]
Reproduce what I mean:

- Open microsoft Photos or Photos legacy
- CTRL C
- Go Desktop
- CTRL V

The image appears as a file, super practical feature. Approve the feature and I'll start working on it :)

**Comment by d2phap** [comment]
![image](https://github.com/d2phap/ImageGlass/assets/3154213/0f538b47-9174-459c-bea0-829f2847bd51)
