### ISSUE TITLE
Screenshots look ver dim or dark compared to paint

### ISSUE THREAD

**Issue by dmkweima** [d2phap/ImageGlass#1818]
### System information:
 - Windows OS version: 11
 - ImageGlass version:  9.0.9.1230 (

### To Reproduce
1. Right click open screenshot file from windows 11 Snip
2. 
3. 
4. 

### Actual behavior:

See included image, shows screenshot open in paint and same screenshot open in ImageGlass opening the same image side by side. ImageGlass is VERY dim or dark. I have color profile set to None.

### Screenshots:

![Dim](https://github.com/d2phap/ImageGlass/assets/105314547/c88cfebf-94cf-4f5a-b55b-e8e9c0233105)

**Comment by d2phap** [comment]
Hi @dmkweima, pls refer to https://github.com/d2phap/ImageGlass/issues/1744#issuecomment-1836201850

**Comment by dmkweima** [comment]
All good!
