### ISSUE TITLE
Remove version number from shortcuts

### ISSUE THREAD

**Issue by EgeGurkan** [d2phap/ImageGlass#1821]
### Is your feature request related to a problem? Please describe.

Remove version number from shortcuts (app shortcut and uninstaller)

### Describe the solution you'd like

Remove version number from shortcuts (app shortcut and uninstaller) Don't really like when shortcuts have version at the end of it, and nearly zero softwares use the naming way your software uses. just image glass.lnk is enough. version number looks dirty and doesn't suit to a software this minimal and beautifull

**Comment by d2phap** [comment]
In [ImageGlass 9.0.10.201](https://github.com/d2phap/ImageGlass/releases/tag/9.0.10.201), the shortcut name is only "ImageGlass".
The uninstaller still remains the same "Uninstall ImageGlass \<version\>" and I want to keep this.
