### ISSUE TITLE
Unsupported image format

### ISSUE THREAD

**Issue by barryblueice** [d2phap/ImageGlass#1822]
### System information:
 - Windows OS version: Microsoft Windows 11 Pro for Workstation Ver. 10.0.22621
 - ImageGlass version: 9.0.9.1230

### Actual behavior:
I try to save a heic picture as a jpg file and it doesn't work. And whether it is saved as .png, .webp or any other format, the error message of "Unsupported image format" will also pop up.

### Expected behavior:
It can be used normally when heic pictures are saved as pictures in other formats.

### Screenshots:
![image](https://github.com/d2phap/ImageGlass/assets/44601454/d9a3063d-cb98-4264-b886-d7a7815ad0a4)

### Additional context:
This function used to works normally in the old version, such as version 8.11.12.6.

**Comment by d2phap** [comment]
Fixed in [ImageGlass 9.0.10.201](https://github.com/d2phap/ImageGlass/releases/tag/9.0.10.201)
