### ISSUE TITLE
Loading next or previous image is slower than in previous versions

### ISSUE THREAD

**Issue by kfal620** [d2phap/ImageGlass#1823]
### System information:
 - Windows OS version: 11 build 22621
 - ImageGlass version: 9.09.1230

### To Reproduce
1. Press left or right arrow to load the next or previous image
2. 
3. 
4. 

### Actual behavior:

There is a short "fade" animation in between images that makes them load slower, and if I hold down the arrow key, it doesn't let me quickly step the images. It waits until I release the key to load whichever image was landed on.

### Expected behavior:

I'd like the image to load quickly and without a fade animation, like before.

### Additional context:

With previous versions, I was able to hold an arrow key to step through image sequences to preview an animation I had made. It was a very welcome feature that other image editors didn't have. Really sped up my workflow. This new functionality breaks my workflow. I also appreciated being able to do a quick A/B of two different images. The new "white fade" animation makes it harder to see small detail differences between two images.

**Comment by d2phap** [comment]
@kfal620 You can disable the setting "Enable image transition":
https://github.com/d2phap/ImageGlass/issues/1744#issuecomment-1836201850

**Comment by kfal620** [comment]
Ah, I should have checked the settings! This works perfectly, thank you.
