### ISSUE TITLE
Crop tool Default selection "Use the last selection" does not work

### ISSUE THREAD

**Issue by freakingprime** [d2phap/ImageGlass#1825]
### System information:
 - Windows OS version: 10
 - ImageGlass version: 9.0.9

### To Reproduce
1. Open Crop tool. Set Default selection to "Use the last selection"
2. Draw a box
3. Save as
4. Observe selection is cleared after saving. It should be the last selection.

### Actual behavior:

The crop selection is dissapeared after saving

### Expected behavior:

The crop selection is keep as is after saving.

**Comment by d2phap** [comment]
Fixed in [ImageGlass 9.0.10.201](https://github.com/d2phap/ImageGlass/releases/tag/9.0.10.201)
