### ISSUE TITLE
Second Toolbar

### ISSUE THREAD

**Issue by xmha97** [d2phap/ImageGlass#1826]
Please add the second toolbar (like the Microsoft Photos app):

![image](https://github.com/d2phap/ImageGlass/assets/23485114/fba59f2e-2d24-4675-b60e-335730e661a4)

**Comment by xmha97** [comment]
I moved the toolbar to the bottom.
Now I need a toolbar for the top. 
![image](https://github.com/d2phap/ImageGlass/assets/23485114/b73ea910-12e2-4ac4-8600-2489626d8868)
Also, I can't add a button to the left side of the toolbar (it's center)

**Comment by d2phap** [comment]
Duplicated #1623
