### ISSUE TITLE
Navigation delay with side mouse buttons (back/forward) compared to arrow keys

### ISSUE THREAD

**Issue by ufuksarp** [d2phap/ImageGlass#1827]
### System information:
 - Windows OS version: 23H2 Build 22631.3007
 - ImageGlass version: Version: 9.0.9.1230 (64-bit)

### To Reproduce
1. Press side mouse buttons for back or forward navigation

There is a noticable delay if you use side mouse buttons for back/forward navigation compared to of arrow keys on keyboard.

**Comment by MistressAshai** [comment]
Issue #387 is likely resurfacing. Double clicking back/forward causes navigation to fail outright.

**Comment by d2phap** [comment]
Fixed in [ImageGlass 9.1.8.723](https://github.com/d2phap/ImageGlass/releases/tag/9.1.8.723)
