### ISSUE TITLE
set-default-viewer at machine level

### ISSUE THREAD

**Issue by zimbo86** [d2phap/ImageGlass#1828]
### Is your feature request related to a problem? Please describe.
We´re running Image Glass on our terminal servers. In IG8 we run 
`Start-Process "C:\Program Files\ImageGlass\igtasks.exe" -argumentlist "regassociations ""*.png;*.jpg;*.gif;*.jpeg;*.bmp""" -wait`
after deployment, so IG Classes were registered at HKLM\Software\Classes
The users default associations can easily be modified using the existing classes, for example ImageGlass.AssocFile.PNG

In IG 9 we run 
`Start-Process "C:\Program Files\ImageGlass\igcmd.exe" -argumentlist "set-default-viewer "".png;.jpg;.gif;.jpeg;.bmp;.webp""" -wait`
however the classes are created in HKCU:\Software\Classes (also when whe run this with administrative privilege).
So the cmd has to run for each user. 

### Describe the solution you'd like

A HKLM switch to igcmd to create the classes in HKLM insted of HKCU, so we can handle all of our FTAs with a generic tool.

**Comment by d2phap** [comment]
I will add new param for `set-default-viewer` command in the next release

**Comment by d2phap** [comment]
You can use `--per-machine` parameter in [ImageGlass 9.0.10.201](https://github.com/d2phap/ImageGlass/releases/tag/9.0.10.201) to tell `igcmd.exe` use `HKEY_LOCAL_MACHINE` key.
Updated docs: https://imageglass.org/docs/command-line-utilities

Example:
```
igcmd.exe set-default-viewer .png;.jpg;.webp --per-machine

igcmd.exe remove-default-viewer .png;.jpg;.webp --per-machine
```

**Comment by zimbo86** [comment]
Thank you, can you please remove this popup or add a silent parameter?
![image](https://github.com/d2phap/ImageGlass/assets/69269000/71fad205-052f-4605-b536-33acf66b4c4d)

**Comment by fanynek86** [comment]
Guys, I have such a problem with the "HEIC" file association, all the others go that way, but "HEIC" does not.

"C:\Program Files\ImageGlass\igcmd.exe" set-default-viewer .heic;.bmp;.cur;.cut;.dib;.emf;.exif;.gif;.ico;.jfif;.jpe;.jpeg;.jpg;.pbm;.pcx;.pgm;.png;.ppm;.psb;.svg;.tif;.tiff;.webp;.wmf;.wpg;.xbm;.xpm;.exr;.hdr;.psd;.tga
