### ISSUE TITLE
Scaled image overlaps the title bar on maximized window

### ISSUE THREAD

**Issue by Barafu** [d2phap/ImageGlass#1829]
### System information:
 - Windows OS version: Win11
 - ImageGlass version:  9.0.9.1230

### To Reproduce
1.  Open image
2.  Select scale to height
3.  Hide all toolbars
4.  Maximise window

### Actual behavior:
An image slightly overlaps the title bar on top, it just feels bad. 

Also, I have this problem with the application from the installer. I did not have that problem with the application from Store, but unsure what version it was. 

### Screenshots:
![image](https://github.com/d2phap/ImageGlass/assets/6612364/12f45504-16bc-4830-8c0d-b5112c3057b0)

**Comment by d2phap** [comment]
Hi @Barafu, pls refer to my comment here https://github.com/d2phap/ImageGlass/issues/1752#issuecomment-1855338287
