### ISSUE TITLE
GIF's playing in slowmotion

### ISSUE THREAD

**Issue by Oranzowy** [d2phap/ImageGlass#1831]
### System information:
 - Windows OS version:  10 Pro 22H2
 - ImageGlass version: 9.0.9.1230 (64-bit)

### To Reproduce
1. open any GIF file with ImageGlass

### Actual behavior:

Any gif file I open with ImageGlass plays very slowly. If I use the default windows program, the issue is gone.

**Comment by d2phap** [comment]
@Oranzowy can you send the sample file?
