### ISSUE TITLE
First launch is slow

### ISSUE THREAD

**Issue by EgeGurkan** [d2phap/ImageGlass#1832]
### System information:
 - Windows OS version: latest
 - ImageGlass version: latest

### To Reproduce
1. First launch is slow
2. 
3. 
4. 

### Actual behavior:

First launch is slow

### Expected behavior:

faster launch maybe run a background service like "lightning reopen" extension for chromium browsers etc runs software at system tray

**Comment by ufuksarp** [comment]
Yeah, the first launch takes too long. But I'm not sure if a background service is the solution that only transfers the lag to the Windows startup. That I dread even more.

**Comment by xanthisafk** [comment]
Same problem on Windows 11 Home build 22631.3007

**Comment by EgeGurkan** [comment]
> Yeah, the first launch takes too long. But I'm not sure if a background service is the solution that only transfers the lag to the Windows startup. That I dread even more.

I think new processors and ssds can handle a delayed system tray start or a service

**Comment by ufuksarp** [comment]
> I think new processors and ssds can handle a delayed system tray start or a service

Making a background service just for the initial startup lag is not the best idea or even a good idea. Having a service for a **photo viewer** is a bit too much. I’m positive that finding the main causes for the lag and fixing it in the first place is easier than creating a whole new module anyway.

**Comment by d2phap** [comment]
One of the .NET's cons is the first launch time is slow.

I thought upgrading to using .NET 8 makes it launch faster (or at least to my machine) so I removed the feature "Start with OS to improve startup speed" from v8. Even though I already enable ["Ready to Run"](https://learn.microsoft.com/en-us/dotnet/core/deploying/ready-to-run) when I publish the binary files.

In v8, you can check this option in Settings > General > Others to make ImageGlass pre-load and hide in the system tray.

I will bring this setting back to v9.

**Comment by EgeGurkan** [comment]
> > I think new processors and ssds can handle a delayed system tray start or a service
> 
> Making a background service just for the initial startup lag is not the best idea or even a good idea. Having a service for a **photo viewer** is a bit too much. I’m positive that finding the main causes for the lag and fixing it in the first place is easier than creating a whole new module anyway.

you can disable if you don't want. its better than having no solution. a new module? its few lines of code to make a system tray icon. no one can write software from scratch just to solve a stupid issue that can be solved in other ways. you can fork the work if u want another solution.

**Comment by Karob2** [comment]
On my machine, it's not just the first launch that is slow, but any launch after the app hasn't been opened in a while. (I'm not sure what time or condition causes it to be slow again within the same Windows session.) These slow launches also cause the app to open behind other app windows for me.

**Comment by d2phap** [comment]
Added Startup Boost option in [ImageGlass 9.1 Beta](https://github.com/d2phap/ImageGlass/releases/tag/9.0.11.529)

![image](https://github.com/d2phap/ImageGlass/assets/3154213/0c74974b-9925-4565-a0dd-0ca15f6fe61e)

**Comment by EgeGurkan** [comment]
works great thanks! my only problem is icon cache and printing problem now. I opened issues for them.

cant ctrl+p
![image](https://github.com/d2phap/ImageGlass/assets/93516630/6103bb41-9049-4d8e-95b6-2c7d8fd7b095)

I have changed default icons but they are still looking like this. cleaned cache not fixed/replaced.
![image](https://github.com/d2phap/ImageGlass/assets/93516630/e76c5be3-e048-42a3-8e2b-46f36e530b9f)
