### ISSUE TITLE
Built-in updater

### ISSUE THREAD

**Issue by H4ckerxx44** [d2phap/ImageGlass#1834]
### Is your feature request related to a problem? Please describe.

Imagine you have downloaded ImageGlass 9 _not_ via the Microsoft Store, when ImageGlass receives an update, the popup-window prompts you to update via the MS Store.

That is a bit annoying when you download the .exe from GitHub and not via the MS Store.

### Describe the solution you'd like

The nicest implemenation would be if you can just press "Update" in the popup-window.

### Describe alternatives you've considered

Alternatively, it would be a nice addition to the "Update" popup-window if the direct download link to the latest release of GitHub would be added.

Something like that
![grafik](https://github.com/d2phap/ImageGlass/assets/56711385/0ee3a4bc-9aac-4b7f-b61d-b6dde70c8087)

**Comment by EgeGurkan** [comment]
I am thinking about the same, I personally bought from store, but I edit my windows via ntlite and remove microsoft store and other bloatware. so I am downloading from github anyways. also it should be automatic

**Comment by d2phap** [comment]
I have no plan, this is a privilege feature of [ImageGlass Store](https://apps.microsoft.com/detail/9N33VZK3C7TH?launch=true&cid=ig_website_badge&mode=full) release.
You can either switch to it or install ImageGlass via a community-managed package manager such as winget, chocolatey,...
