### ISSUE TITLE
Add silent parameter to FTA command "--per-machine" (#1828)

### ISSUE THREAD

**Issue by zimbo86** [d2phap/ImageGlass#1835]
### Is your feature request related to a problem? Please describe.
First of all, thanks for adding "--per-machine"

When running 
`igcmd.exe set-default-viewer .png;.jpg;.webp --per-machine `
there is a "successful"-popup which prevents a scripted silent installation to continue

### Describe the solution you'd like
Remove the popup or add a silent parameter

### Additional context
![image](https://github.com/d2phap/ImageGlass/assets/69269000/a3bc0149-b891-404c-bfbe-f5467c70cd3a)

**Comment by xenadmin** [comment]
Just encountered this today, thanks for your report. We also need that command line switch to be silent or an additional silent switch. The popup breaks scripts.

**Comment by zimbo86** [comment]
> Just encountered this today, thanks for your report. We also need that command line switch to be silent or an additional silent switch. The popup breaks scripts.

As a dirty workaround you can use
`Start-Process "C:\Program Files\ImageGlass\igcmd.exe" -argumentlist "set-default-viewer "".png;"" --per-machine"`
`Start-Sleep -seconds 5`

(without -wait)

**Comment by d2phap** [comment]
Should be fixed in v9.0.11. All commands are run without UI by default unless passing `--ui` param
