### ISSUE TITLE
Please add support for Panasonic DC-G9M2 RAW file RW2 

### ISSUE THREAD

**Issue by habchab** [d2phap/ImageGlass#1837]
![Untitled](https://github.com/d2phap/ImageGlass/assets/7805704/8a7ccc55-9805-4eba-802d-86fccfa4c464)
Probably similar to #1684.

Example .RW2 (split due to github max size of 25MB. Rename .001.zip to .zip.001, etc.):
[P1020927.001.zip](https://github.com/d2phap/ImageGlass/files/14150542/P1020927.001.zip)
[P1020927.002.zip](https://github.com/d2phap/ImageGlass/files/14150543/P1020927.002.zip)

Embedded thumbnail works fine (if set in setting, and for a couple seconds before the raw data is loaded).

**Comment by d2phap** [comment]
Hi @habchab, I suggest you to report to [Magick.NET](https://github.com/dlemstra/Magick.NET/issues) since IG uses Magick.NET library to read the image file.

Also, I tried opening your file with MS Photos, it shows the same thing.

![image](https://github.com/d2phap/ImageGlass/assets/3154213/1305ad2e-5b4a-4f59-8d2c-73c3f5b33166)

**Comment by habchab** [comment]
I've done some digging. Magick.NET uses libraw, [which currently does not support DC-G9M2](https://www.libraw.org/supported-cameras). Rawdigger, made by LibRaw LLC, [does support DC-G9M2 in 1.4.8 Beta](https://www.rawdigger.com/news/rawdigger-1-4-8-beta). Presumably they have more supported cameras internally/with their extended support for libraw, For the public release of libraw, they refer back to their update policy (on their [website](https://www.libraw.org/comment/6576#comment-6576l) and on [github](https://github.com/LibRaw/LibRaw/issues/564#issuecomment-1435526177)), which states that new snapshots are published up to every 18 months. So I guess it's simply a waiting game for this.
Regards.
