### ISSUE TITLE
Delete image from slideshow mode

### ISSUE THREAD

**Issue by stnzbass** [d2phap/ImageGlass#1838]
It would be useful if we could delete an image (with Del key) directly from slideshow mode.

Another solution could be that exiting slideshow select the last shown image from the slideshow. This way we could stop the slideshow, delete the image, then restart the slideshow from where we left of.

Thank you

**Comment by d2phap** [comment]
Delete menu already added in [ImageGlass 9.1.8.723](https://github.com/d2phap/ImageGlass/releases/tag/9.1.8.723)
