### ISSUE TITLE
An error occurred while saving the ICO format

### ISSUE THREAD

**Issue by 1069641179** [d2phap/ImageGlass#1840]
When selecting the saved format after cropping the image, if the selected pixels  >256 * 256, an error will be reported (as shown in the figure), and if<256 * 256, it will be normal. Can text prompts be added when cropping images？
![1](https://github.com/d2phap/ImageGlass/assets/40432981/16c703d1-ddd7-426f-b1fd-4469081268c0)
![2](https://github.com/d2phap/ImageGlass/assets/40432981/2a5c11ba-a192-4473-8f28-6e6dbec4c1d4)

**Comment by d2phap** [comment]
Fixed in [ImageGlass 9.1.8.723](https://github.com/d2phap/ImageGlass/releases/tag/9.1.8.723)
