### ISSUE TITLE
select tool (not the whole file) 

### ISSUE THREAD

**Issue by csegyud** [d2phap/ImageGlass#1841]
### Is your feature request related to a problem? Please describe.
I would like to have a simple select tool (by mouse). Now it is not possible to select a portion of the image.

### Describe the solution you'd like
I would love a simple select tool with which I could select a part of the image with my mouse for copying to the clipboard or saving as a new file. The selection should be resizable - like the crop feature, e.g. 

thx.

**Comment by d2phap** [comment]
Can't you use Crop tool to select & copy?

**Comment by csegyud** [comment]
Oh... you are right, my fault. I'm new to the app.
And now I can see that I have a shortcut too. Nice. Thank you!
