### ISSUE TITLE
A key conflict is displayed

### ISSUE THREAD

**Issue by blakekilltime** [d2phap/ImageGlass#1842]
I can't use
The software won't open any pictures
A key conflict is displayed
I don't know why

![image](https://github.com/d2phap/ImageGlass/assets/38996492/822077f2-fa7d-4ccc-9e4b-4002682e5157)

**Comment by d2phap** [comment]
@blakekilltime Can you try the latest version v9.0.10.201?

**Comment by blakekilltime** [comment]
![IMG_20240205_104834](https://github.com/d2phap/ImageGlass/assets/38996492/d0f5229b-b076-42c7-a8d2-cadee12c64d1)
png is wrong
JPG is always loading

**Comment by d2phap** [comment]
Should be fixed in v9.0.11
