### ISSUE TITLE
view photo sort in windows search

### ISSUE THREAD

**Issue by syksumy** [d2phap/ImageGlass#1843]
<img width="1120" alt="屏幕截图 2024-02-05 140028" src="https://github.com/d2phap/ImageGlass/assets/24364975/6ba4cde2-c02c-45eb-a530-95e70f60141f">
When opening photos in the search window under Windows, the built-in Photos app in Win10 displays images in the correct order (pay attention to the thumbnails). However, when using this software, the images are displayed based on the original folder sorting of the pictures.

May I request this feature? I use Windows search very frequently.

Thanks a lot

**Comment by d2phap** [comment]
Duplicated of #404

**Comment by syksumy** [comment]
#404 but issue is not solve
