### ISSUE TITLE
Image selections in a folder will be unselected if I delete a an image while viewing.

### ISSUE THREAD

**Issue by notosapien** [d2phap/ImageGlass#1846]
### Is your feature request related to a problem? Please describe.
I open folder which contains dozens of pictures, I double click the first one and go through and if I saw the picture I want to move to another folder I will select it from the folder, and if I see the one I like I will just leave it there, and If I want to delete the ones I don't like, I will use the DEL key. The problem is deleting a picture will cause the selection I had in the folder to be unselected

### Describe the solution you'd like
Going though images found in a folder, allow me to select multiple images from that folder and If I delete an image from ImageGlass when I continue to go through the images, the multiple selections I made will remain selected.

### Additional context

![001](https://github.com/d2phap/ImageGlass/assets/46129606/732d4e1f-86c1-49c8-a680-a0d1edb0df14)
![002](https://github.com/d2phap/ImageGlass/assets/46129606/e36897f5-19e7-4e68-9d31-36697acd6efe)

**Comment by d2phap** [comment]
Hi @notosapien,
This is the behaviour of Windows File Explorer. ImageGlass, as a 3rd-party app, does not interfere this.
