### ISSUE TITLE
Add keyboard shortcuts (not only mouse)

### ISSUE THREAD

**Issue by norius-na** [d2phap/ImageGlass#1848]
### Is your feature request related to a problem? Please describe.

Not a problem.

### Describe the solution you'd like

Add keyboard shortcuts e.g. 
- M to move current image to latest destination folder
- C to copy current image to latest destination folder
- Shift+1 to 0 to MOVE to specific folder (out of 10 which have been set in Settings).
- Ctrl+1 to 0 to COPY to specific folder (out of 10 which have been set in Settings).
- Spacebar to next image, Backspace to previous
- Page Up/Down to previous/Next
- Arrow keys to scroll zoomed image

**Comment by d2phap** [comment]
For these:
> M to move current image to latest destination folder
> C to copy current image to latest destination folder
> Shift+1 to 0 to MOVE to specific folder (out of 10 which have been set in Settings).
> Ctrl+1 to 0 to COPY to specific folder (out of 10 which have been set in Settings).

You can create a new tool to execute batch script and assign hotkey for it, refer to https://github.com/d2phap/ImageGlass/issues/1422#issuecomment-1869918684

For these:
> Spacebar to next image, Backspace to previous
> Page Up/Down to previous/Next
> Arrow keys to scroll zoomed image

Refer to #1702 for hotkey customization.
