### ISSUE TITLE
Some GIF cannot save as Webp.

### ISSUE THREAD

**Issue by suyangzuo** [d2phap/ImageGlass#1849]
### System information:
 - Windows OS version: Windows 11 23H2
 - ImageGlass version: 9.0.10.201

### To Reproduce
1. open GIF
2. Save as Webp
3. popup a errow dialog

### Screenshots:
<img width="377" alt="PNG-To-Webp-Error" src="https://github.com/d2phap/ImageGlass/assets/50766353/ba041b92-9a49-4a9c-aeb9-5211f205499d">

Some GIF can Successfully saved as webp, some can't, unnable to find patterns. 
Here is the original GIF file.
![HTTP-Request-Methods](https://github.com/d2phap/ImageGlass/assets/50766353/9ab43167-1221-4589-983c-197ca1ed7190)

**Comment by d2phap** [comment]
It seems upstream issue. ImageGlass uses Magick.NET to read and [write image file](https://github.com/d2phap/ImageGlass/blob/f5fa3b2fffe3c54596cf35cd4dff97c465ae1c53/Source/Components/ImageGlass.Base/Photoing/Codecs/PhotoCodec.cs#L453C47-L453C57).

You can report this issue to [Magick.NET fork](https://github.com/dlemstra/Magick.NET/issues) with the sample image file.

**Comment by d2phap** [comment]
Should be fixed in v9.0.11
