### ISSUE TITLE
ImageGlass not opening files

### ISSUE THREAD

**Issue by AHolde** [d2phap/ImageGlass#1850]
### System information:
 - Windows OS version: 11
 - ImageGlass version: latest

### To Reproduce
1.  Open citrix
2. Open a picture
3. 
4. 

### Actual behavior:

I am working with ImageGlass in Citrix, when ever I try to open a .png etc. in ImageGlass nothing happens. The file just never opens, however it shows that imageGlass is open. However I am unable to access it.

### Expected behavior:

To open the picture

**Comment by d2phap** [comment]
I don't have Citrix environment so that I am not sure about the issue.
Can you enable Debug mode for ImageGlass and send a video?

To enable Debug mode in ImageGlass:
- Close all ImageGlass windows
- Open `igconfig.json` file
- Set `EnableDebug` to `true`
- Save the file and run ImageGlass again
