### ISSUE TITLE
custom zoom

### ISSUE THREAD

**Issue by davidp88** [d2phap/ImageGlass#1851]
Current zoom options are no good,add a custom zoom option to zoom pics at an increment of desired percentage.

**Comment by d2phap** [comment]
Menu > Zoom > Custom zoom:

![image](https://github.com/d2phap/ImageGlass/assets/3154213/8b86c217-d02e-47c4-9786-c9293f4d512b)

**Comment by davidp88** [comment]
when using it and after it crosses a certain zoom percentage it doesn't zoom at the set desired value in custom zoom
