### ISSUE TITLE
ImageGlass could not detect WebView2 Runtime 64-bit on your mac... (Windows 10)

### ISSUE THREAD

**Issue by floppyD** [d2phap/ImageGlass#1852]
### System information:
 - Windows OS version: Windows 10 Education 22H2 (Fresh install)
 - ImageGlass version: ImageGlass_9.0.10.20.exe

### To Reproduce
1. Install ImageGlass from github
2. Install .NET 8.0 Desktop Runtime (v8.0.2)
3. Launch ImageGlass from desktop shortcut
4. Get error

### Screenshots:
![mac](https://github.com/d2phap/ImageGlass/assets/29208110/ff6d6a15-21fc-4604-a0a3-40389ee6bfc3)

### Additional context:
Just noticed this "WebView2 Runtime 64-bit" is listed as a requirement on the readme, but it would be nice to have the program give you a link, just like it did for .NET 8.0. I actually thought it meant Mac as in Apple's Mac instead of "machine" and got confused lol

**Comment by d2phap** [comment]
The text is actually truncated!
The ".NET 8" is the built-in popup of.NET apps. I will update the message for better understanding

**Comment by Tha14** [comment]
I've also encountered this on the latest release.

**Comment by d2phap** [comment]
In V9.0.11 the message is updated with a link to download WebView2
