### ISSUE TITLE
Disable hover arrows on left/right

### ISSUE THREAD

**Issue by floppyD** [d2phap/ImageGlass#1853]
Just an option to disable these. I don't use them and I didn't find any option to disable them.

![image](https://github.com/d2phap/ImageGlass/assets/29208110/19523316-7d43-401f-8c13-4fbab1566b60)

**Comment by d2phap** [comment]
You can disable this option:
![image](https://github.com/d2phap/ImageGlass/assets/3154213/97780e85-40f4-4793-89f0-9951c77c39d0)

**Comment by floppyD** [comment]
No idea how I missed this. Thanks!
