### ISSUE TITLE
Trouble with quick set up

### ISSUE THREAD

**Issue by csarevalo** [d2phap/ImageGlass#1854]
### System information:
 - Windows OS version: OS Name	Microsoft Windows 11 Home
 - Version	10.0.22621 Build 22621
 - System Model	Dell G15 5525
 - ImageGlass version: ImageGlass_9.0.10.201_x64 

### To Reproduce
1. Begin set up process
2. Skipped make default
3. Click done
4. The exception pops up

### Unhandled Exception (Copy/Pasted)
Version: igcmd v9.0.10.201
Release code: kobe
Magick.NET: Magick.NET Q16-HDRI-OpenMP x64 netstandard21 13.5.0
WebView2 Runtime: 105.0.1343.27
OS: Microsoft Windows NT 10.0.22621.0 64-bit

----------------------------------------------------
Error:

Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Web.WebView2.Core.Raw.ICoreWebView2WebMessageReceivedEventArgs2'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{06FC7AB7-C90C-4297-9389-33CA01CF6D5E}' failed due to the following error: No such interface supported (0x80004002 (E_NOINTERFACE)).
----------------------------------------------------

System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Web.WebView2.Core.Raw.ICoreWebView2WebMessageReceivedEventArgs2'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{06FC7AB7-C90C-4297-9389-33CA01CF6D5E}' failed due to the following error: No such interface supported (0x80004002 (E_NOINTERFACE)).
   at Microsoft.Web.WebView2.Core.CoreWebView2WebMessageReceivedEventArgs.get__nativeICoreWebView2WebMessageReceivedEventArgs2()

**Comment by d2phap** [comment]
Your WebView2 version is outdated, please install [WebView2 Runtime 64-bit v119.0.2151 or later](https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section)

**Comment by mraklbrw** [comment]
Same problem - Image Glass Portable 9.0.10.201.
WebView2 installed, .Net 8.0 runtime installed.
Windows 10 22H2 19045.3570

**Comment by d2phap** [comment]
@mraklbrw check if your MS Edge version is >= 119?
