### ISSUE TITLE
If Window Fit is activated, the position of the window is not saved

### ISSUE THREAD

**Issue by hoyachoe** [d2phap/ImageGlass#1856]
### System information:
 - Windows OS version:  windows 11
 - ImageGlass version: Version: 9.0.10.201 (64-bit)
WebView2 Runtime: 121.0.2277.112
.NET Runtime: 8.0.0

### To Reproduce
1. If Window Fit is activated, the position of the window is not saved when the program is terminated (Auto-center the window in Window Fit mode-- Uncheck)

### Actual behavior:
In ImageGlass_Kobe_8, even if Window Fit is enabled, the position of the window when closed is saved.

### Screenshots:

Recoding Video

https://drive.google.com/file/d/1oUlQET3xIfWRdpn87gb6XGP4vI8Ion0X/view?usp=drive_link

**Comment by d2phap** [comment]
@hoyachoe Can't access the video, can you share again?

**Comment by hoyachoe** [comment]
> @hoyachoe Can't access the video, can you share again?

I just saw the message and reinstall. The Window popup location is saved normally. thank you~
