### ISSUE TITLE
Gallery saves thumbnail cache by name causing problem

### ISSUE THREAD

**Issue by TheCGDF** [d2phap/ImageGlass#1859]
### System information:
 - Windows OS version: Windows 11
 - ImageGlass version: 9.0.10.201 (64-bit)

### To Reproduce
1. Enable gallery function of ImageGlass, then close ImageGlass.
2. Create a empty folder, put a jpg file into it and rename it to "001.jpg".
3. Open 001.jpg with ImageGlass once and close it.
4. Delete 001.jpg and move another different jpg file into it, rename it to "001.jpg" again.
5. Open the new 001.jpg.

### Actual behavior:
![image](https://github.com/d2phap/ImageGlass/assets/17256673/499f99a4-f4c8-4b86-953f-58d9efd40021)
Gallery thumbnail did not update and still shows the old thumbnail.

### Expected behavior:
Gallery thumbnail should be to updated.

### Additional context:
I think there is no necessary to cache thumbnail globally?

**Comment by d2phap** [comment]
Should be fixed in [ImageGlass 9.1 Beta](https://github.com/d2phap/ImageGlass/releases/tag/9.0.11.529)
