### ISSUE TITLE
ImageGlass stop loading some picture

### ISSUE THREAD

**Issue by KaiHuaDou** [d2phap/ImageGlass#1861]
### System information:
 - Windows OS version: Windows 10 22H2
 - ImageGlass version: 9.0.10.201 (64-bit) in .NET 8.0.2

### To Reproduce
1. Open the file: [IMG_5621](https://github.com/d2phap/ImageGlass/assets/74781268/3f1ae30d-cbe4-4ab4-b1c5-a18cb3e0c5b2)
    - it's an image which import from my iPad

### Actual behavior:
it has the resolution of 3264x2448 and my ImageGlass reconized it.
But the ImageGlass only show a furry image just like a thumbnail.
I test this Image on my Chrome, and it displays well.

### Expected behavior:
Show the image in right resolution.

### Screenshots:
![image](https://github.com/d2phap/ImageGlass/assets/74781268/8df443d6-ddbd-49c3-930f-f7eaf537d809)

**Comment by d2phap** [comment]
Hi @KaiHuaDou,

Your image contains an embedded thumbnail. Make sure you are not enabling this option:

![image](https://github.com/d2phap/ImageGlass/assets/3154213/5b00f82a-601d-40f8-a443-2a85c97eeefb)
