### ISSUE TITLE
不能用激光笔翻页和旋转图片后未保存

### ISSUE THREAD

**Issue by LShovel** [d2phap/ImageGlass#1862]

**Comment by d2phap** [comment]
Please post your issue in English or Vietnamese

**Comment by LShovel** [comment]
Can’t turn pages with laser pointer：The laser pointer corresponds to the up and down keys of the keyboard. You can only press the left and right keys to turn pages with imageglass. You cannot use the laser pointer to turn pages when displaying the gallery. There are only a few picture viewing software that can use both the up and down keys and the left and right keys to view the next picture, such as wps.(Laser pointer: page turning controller used to demonstrate ppt)
Pictures cannot be saved automatically after being rotated：We often view a large number of images that are not displayed correctly. For example, PDF files are saved as single-page images. You can use the built-in software of win10 to view them one by one and rotate the images that are not displayed correctly. But using imageglass requires manually saving each chapter.
