### ISSUE TITLE
Image Clarity Issue with Long/Scrolling Screenshots When Zoomed

### ISSUE THREAD

**Issue by mriamnobody** [d2phap/ImageGlass#1863]
### System information:
 - Windows OS version: Windows 11 (22631.3155)
 - ImageGlass version: 9.0.10.201

### To Reproduce
1. Open a long or scrolling screenshot.
2. Zoom in on any part of the image to examine details more closely.
3. Notice that the image appears blurry and lacks the clarity..

### Actual behavior:
Zooming in on a long or scrolling screenshot results in a blurry image, making it difficult to view details clearly. This issue is not observed when the same image is viewed and zoomed in using the Windows Photo app.

### Expected behavior:
When zooming in on a long or scrolling screenshot, the image should retain its clarity and details should be easily discernible.

### Screenshots:
This is how it looks in  ImageGlass:

![Screenshot 2024-02-27 210850](https://github.com/d2phap/ImageGlass/assets/14347205/fa2d8a47-4032-4370-9292-fb36cc3b67f7)

This is how it looks in Windows Photo app:

![Screenshot 2024-02-27 211132](https://github.com/d2phap/ImageGlass/assets/14347205/c572a878-cc59-4083-8939-be6eb5b7bf76)

I have attached the Google Drive link of the original image as its size is more than 10 MB.
[Google Drive link of the original image](https://drive.google.com/file/d/1ux9XbMbMXFcbfwF4v1a6vWcQSUodfsl0/view?usp=sharing)

**Comment by d2phap** [comment]
Your image dimension exceeds the maximum supported size of ImageGlass (16380 x 16380, see https://imageglass.org/docs/features#limitations) so it will automatically scaled down to 16380.

![image](https://github.com/d2phap/ImageGlass/assets/3154213/20dfd7e9-d251-4348-98d4-8165e23f4b19)


For zooming, if zoom > 100%, IG uses `Nearest neighbor` algorithm which is pixelated (similar to MS Paint). You can change it in Settings > Viewer > Zooming:
![image](https://github.com/d2phap/ImageGlass/assets/3154213/13e51d3c-5e2a-414a-9485-751ffbacd6e3)

**Comment by mriamnobody** [comment]
Thank you @d2phap for quick resolution.
