### ISSUE TITLE
Cannot see JPEG XL image (VarDCT Lossy v0.10.1)

### ISSUE THREAD

**Issue by Ahmad-Amsyar** [d2phap/ImageGlass#1864]
### System information:
 - Windows OS version: Windows 10 22H2 (OS Build: 19045.4046)
 - ImageGlass version: 9.0.10.201(x64)

### To Reproduce
1. Download jxl-x64-windows-static version 0.10.1 (https://github.com/libjxl/libjxl/releases/tag/v0.10.1).
2. Extract JPEG XL zip file.
3. Go inside the extracted folder, you can see many files inside including cjxl.exe.
4. Download or use 1 image as testing. I will called it IMAGE(1).jpg.
5. Type "cmd" on the Windows Explorer address bar.
6. Type "cjxl -h" in the CMD to confirm the version number is 0.10.1.
7. Type "cjxl IMAGE(1).jpg IMAGE(2).jxl -m 0 -q 80  --lossless_jpeg 0" .
  - -m 0 = disable modular mode and use VarDCT instead.
  - -q 80 = Using quality level 80.
  - --lossless_jpeg 0 = disable lossless encoding and enable lossy image encoding.
8. Wait for the encoding process.
9. Open IMAGE(2).jxl using ImageGlass.
10. Error pops out.

Sample files:
[JXL-VarDCT.zip](https://github.com/d2phap/ImageGlass/files/14468197/JXL-VarDCT.zip)

### Actual behavior:

- Something problem with ImageMagickk I assume?
- Images sample folder: https://github.com/Ahmad-Amsyar/ImageGlass/tree/d6e4fd9835519b92224a9ad0a17a0033e77b611d/JPEG%20XL%20VarDCT%20v0.10%20issue%20(Sample%20Images)

### Expected behavior:

- The image can be seen.

### Screenshots:

![Image Glass error](https://github.com/d2phap/ImageGlass/assets/27284123/83119df6-163e-4353-aa4d-1f24d959f041)

### Additional context:

- Thumbnails seems to be working, but the error is shown when I open it in ImageGlass.
- For modular mode, there is no problem opening and seeing the image. the issue only happened in VarDCT mode.

**Comment by d2phap** [comment]
@Ahmad-Amsyar Can you attach the sample image file?
Anyway, IG 9.0.10.201 uses Magick.NET 13.5 which includes jpeg-xl 0.8.2. This is quite outdated version, so the image generated by newer version may not be decoded.

**Comment by Ahmad-Amsyar** [comment]
> @Ahmad-Amsyar Can you attach the sample image file? Anyway, IG 9.0.10.201 uses Magick.NET 13.5 which includes jpeg-xl 0.8.2. This is quite outdated version, so the image generated by newer version may not be decoded.

Here is the link to the images sample folder:
https://github.com/Ahmad-Amsyar/ImageGlass/tree/d6e4fd9835519b92224a9ad0a17a0033e77b611d/JPEG%20XL%20VarDCT%20v0.10%20issue%20(Sample%20Images)

**Comment by d2phap** [comment]
Thanks for the sample files.
The issue happens when encoding with jpeg-xl v0.10.1

Upgrading to Magick.NET v13.6 (jpeg-xl 0.9.2) fixes the issue:
![image](https://github.com/d2phap/ImageGlass/assets/3154213/433406c5-8c77-41ed-8c2f-50abda1599a6)

**Comment by Ahmad-Amsyar** [comment]
Thank you for the swift update. I will close this issue.

**Comment by d2phap** [comment]
I saw you forked IG repo, you can [build it by yourself](https://github.com/d2phap/ImageGlass/discussions/1740#discussioncomment-7706100) if can't wait for next release.

**Comment by Ahmad-Amsyar** [comment]
> I saw you forked IG repo, you can [build it by yourself](https://github.com/d2phap/ImageGlass/discussions/1740#discussioncomment-7706100) if can't wait for next release.

Thank you for the help.
