### ISSUE TITLE
ImageGlass going to the wrong monitor making it inaccessible or seem to not work

### ISSUE THREAD

**Issue by InaZeRaa** [d2phap/ImageGlass#1865]
### System information:
 - Windows OS version: 11
 - ImageGlass version: 9.0.10.201

### To Reproduce
Steps to reproduce the behaviour:
1. Have a duel monitor setup with the second monitor to the left of the main
2. Have that monitor plugged in, but turned off in windows display settings so its only on the main
3. Boot imageglass or load an image.  
4. This same thing can also be done by dragging the image off the visible screen to either side or by leaving it on the 2nd monitor while on and turning it off to only display on the first

### Actual behaviour:

The imageglass window is opening to the 2nd monitor instead of the first even thought its not technically available.
 If you can see the faintness of the window opening and closing but going off to the left, the bug is occurring.
This could be occurring because the application is trying to open the window to the last know location.

### Expected behaviour:

The application should be accessible on my first monitor at all times and shouldn't require me to turn on my second to retrieve the images.

### Screenshots:

The way i found out it was being put off there. (When unminimized it is completely invisible) 
![image](https://github.com/d2phap/ImageGlass/assets/108250991/165ea9d5-d9cd-41de-a40f-cf0fb1c13547)
Showing it can be pushed off screen and become inaccessible if put off screen to far
![image](https://github.com/d2phap/ImageGlass/assets/108250991/e5469853-2f38-4cf7-99e1-3fe4194e2254)

### Additional context:

My monitor I have, even when powered off will still be seen by window.
Even when i uninstalled and reinstalled the program, it was still doing it. This was before I tried turning my monitor on to check

**Comment by InaZeRaa** [comment]
I should note that the first image is of the in-between fade when applications are flying from the taskbar to the correct position

**Comment by d2phap** [comment]
Should be fixed in [ImageGlass 9.1 Beta](https://github.com/d2phap/ImageGlass/releases/tag/9.0.11.529)
