### ISSUE TITLE
Issue with Navigation arrow buttons not working after zooming into image

### ISSUE THREAD

**Issue by papajin68** [d2phap/ImageGlass#1866]
### System information:
 - Windows OS version:  Windows 11
 - ImageGlass version: 8.8.4.4 x64

### To Reproduce
1. Zoom in to the image using any method.
2. Try to navigate to the next or previous issue using the on-screen next/previous image arrows overlayed on the image.

### Actual behavior:
After zooming into an image, if you try to navigate to the next or previous image by clicking one of the on-screen arrows, the current doesn't change.  You can see the icon change to the cross with arrows pointing up/down/left/right which normally shows when you have an image that doesn't fit in the viewer which allows you to move the current view around the image, so it's likely this functionality is interfering with the on-screen navigation buttons in some way.

### Expected behavior:
Current image should either advance to the next or go back to the previous depending on which button is clicked.

### Screenshots:
Not applicable.

### Additional context:
Navigating by hitting the left / right arrow on the keyboard or page up / page down on the keyboard works as well as navigation by going through the main menu.  Only clicking on the on-screen arrows doesn't work as expected.

As a workaround, you can zoom back out until the image fits entirely on the screen, and then the buttons work as expected again.

**Comment by d2phap** [comment]
@papajin68 Please upgrade to the latest version
