### ISSUE TITLE
Ability to display / hide hidden image files

### ISSUE THREAD

**Issue by d2phap** [d2phap/ImageGlass#187]
From Сергей Павлов

Hi. I have a small issue. Program is cool but it's showing hidden indexed images in folders when I switching them. it would be cool if there will be an option to not showing them.

![image](https://cloud.githubusercontent.com/assets/3154213/25779083/bb7eee50-3342-11e7-8bc4-2e4b73c83a6b.png)

**Comment by s8321414** [comment]
And I don't why it still shows "ImageGlass 3.5" in Default Program panel...

**Comment by d2phap** [comment]
Hi @s8321414 
I guess you didn't uninstall v3.5 before installing v4.
You can uninstall and reinstall ImageGlass again.
I will check if this can be fixed in the next release

Thanks

**Comment by s8321414** [comment]
@d2phap I uninstalled v3.5 before install v4, but it still tell me v3.5.
I think there are some register value remaining old.

**Comment by d2phap** [comment]
This feature is implemented in `develop` branch.
Thanks @EJLV for your contribution!
