### ISSUE TITLE
Not sure if this is a bug per say, but it feels like one

### ISSUE THREAD

**Issue by Unlucky-the-13th** [d2phap/ImageGlass#1870]
I'm on Windows 10, and I tried Image Glass for a bit and didn't like it. I uninstalled it.
I will try and attach a picture. But, after uninstalling, it only gives me the option to save as "image glass jpg". It's not that big an issue but it's annoying and I would like to get rid of it. Can anyone help me?

![image](https://github.com/d2phap/ImageGlass/assets/92154027/236ebf5c-ea44-4e34-bdc1-34fb1426effa)

**Comment by d2phap** [comment]
You need to reinstall IG.
- Go to Settings > File type associations, click "Remove default" button.
- Or use the Main menu > Help > Remove default photo viewer

![image](https://github.com/d2phap/ImageGlass/assets/3154213/75b60c01-74fe-4b89-9e0c-a2ec1922594f)

**Comment by Unlucky-the-13th** [comment]
This did not work.
