### ISSUE TITLE
ImageGlass 9.0.10.201 Doesn't Show ExifTool GUI

### ISSUE THREAD

**Issue by RainfallWithin** [d2phap/ImageGlass#1873]
### System information:
 - Windows OS version: Windows 11 Pro 21H2
 - ImageGlass version: 9.0.10.201

### To Reproduce
1. Paste ExifTool executable into ImageGlass directory
2. Open ImageGlass and press "X" keyboard shortcut
3. 
4. 

### Actual behavior:
A blank command terminal opens for 1 second, then closes.

### Expected behavior:
A white ExifTool GUI should appear with the photo's exif data.

### Screenshots:
![Screenshot (355)](https://github.com/d2phap/ImageGlass/assets/69644154/b53669da-3b77-4037-9548-07c023cce1ef)

### Additional context:
The ExifTool executable works correctly when used outside of ImageGlass.

**Comment by d2phap** [comment]
ImageGlass 9 removed Exiftool from v8, you need to install ExifGlass and add it to ImageGlass.
- Download ExifGlass: https://imageglass.org/tools
- Add ExifGlass to ImageGlass: https://imageglass.org/docs/imageglass-tools#add-your-tool-to-imageglass

**Comment by RainfallWithin** [comment]
Thank you for the new instructions. They worked perfectly.

ExifGlass loads exif data much quicker than the old system, so I'm appreciating that.

Normally, I would have asked in Discord first, but it appears the ImageGlass Discord channel doesn't exist.

Now the only thing I need to figure out is how to hide unwanted exif tags in the viewer, but that's for another topic.

**Comment by d2phap** [comment]
You cane join IG Discord via this link:https://discord.com/channels/818852544859209748/818852544859209751


In ExifGlass settings, you can add command lines of Exiftool to do the filters

**Comment by RainfallWithin** [comment]
Thanks, I will research the ExifTool command lines.

The Discord link redirects to the Discord homepage; it doesn't show the server. I tried clicking it from the ImageGlass website too before writing my issue here.
