### ISSUE TITLE
ImageGlass toolbar icons missing when ImageGlass can access imagemagick's "delegates.xml" file

### ISSUE THREAD

**Issue by azzvx** [d2phap/ImageGlass#1875]
### System information:
 - Windows OS version: Win10 22H2
 - ImageGlass version: 8.11.12.6 and 9.0.10.201

### To Reproduce
1. `Scoop install imagemagick` 
2. Run ImageGlass

### Actual behavior:
Toolbar icons missing(v8) or show circle(v9)

### Expected behavior:
Toolbar icons show normally

### Screenshots:
![QQ截图20240326211149](https://github.com/d2phap/ImageGlass/assets/1546898/57384448-dd97-4bef-8ff5-b3d6a3cfff7c)

### Additional context:
Scoop will create environment variables "MAGICK_HOME" and "MAGICK_CONFIGURE_PATH", and ImageGlass will use configuration files under "MAGICK_HOME" and "MAGICK_CONFIGURE_PATH".

**Comment by KyleKolander** [comment]
I'm experiencing the same bug.  I uninstalled from Scoop and installed the latest msi from here.  When it first loaded, the toolbar icons were fine, but after closing the app and re-opening it, this bug presented again.  I even tried the previous version but was met with the same result.  Odd that this was all working fine yesterday...

**Comment by KyleKolander** [comment]
After completely uninstalling ImageGlass (all filesystem remnants) and then uninstalling Image Magick (all filesystem remnants) and then installing ImageGlass via Scoop again, everything is back to working as it used to...  Hopefully it keeps working, and it ends up that it was just a conflict between those two...  Maybe this will help someone else.

**Comment by azzvx** [comment]
> After completely uninstalling ImageGlass (all filesystem remnants) and then uninstalling Image Magick (all filesystem remnants) and then installing ImageGlass via Scoop again, everything is back to working as it used to... Hopefully it keeps working, and it ends up that it was just a conflict between those two... Maybe this will help someone else.

There are 3 ways to solve this issue.
1. Comment out the line `<delegate decode="svg:decode" .../> ` in "delegates.xml", witch Magick.NET does.
2. Remove environment variables "MAGICK_HOME" and "MAGICK_CONFIGURE_PATH".
3. Add code `Environment.SetEnvironmentVariable("MAGICK_HOME", "");` and `Environment.SetEnvironmentVariable("MAGICK_CONFIGURE_PATH", "");` in program to avoid ImageGlass load external configuration files.

**Comment by d2phap** [comment]
Thanks for the info. IG does not configure the path of ImageMagick so it's probably conflicted in this case.

I will use the ConfigDir as the path of ImageMagick in next versions
