### ISSUE TITLE
Print proken

### ISSUE THREAD

**Issue by EgeGurkan** [d2phap/ImageGlass#1876]
### System information:
 - Windows OS version:  win11 22631.3296 fresh install with all drivers installed
 - ImageGlass version:  9.0.10.201 .NetRuntime: 8.0.3 WebRuntime: 122.0.2365.92

### To Reproduce
1.  ctrl+p
2. 
3. 
4. 

### Actual behavior:

ctrl+p gives the error. screenshot added.

### Expected behavior:

to be able to print.

### Screenshots:

![image](https://github.com/d2phap/ImageGlass/assets/93516630/2bba189b-25fd-4134-8b00-43dd6b5fe81d)
![image](https://github.com/d2phap/ImageGlass/assets/93516630/c05375e6-ac8f-4271-8bb3-313c5330fc09)

### Additional context:

no driver error. can print from microsoft office and adobe acrobat and adobe photoshop and autocad etc etc you get the point

**Comment by EgeGurkan** [comment]
any improvement on this issue? this one effects life daily. not like other bugs. I can't print anything.

**Comment by d2phap** [comment]
ImageGlass print feature depends on "Print Pictures" dialog of Windows, the error shows that this feature does not exist in your system. You might remove some legacy Windows components.

![image](https://github.com/d2phap/ImageGlass/assets/3154213/cb6798b0-4f92-42fe-a0ca-976cd5e55cbe)

**Comment by d2phap** [comment]
@CrypticCus Can you try this https://github.com/d2phap/ImageGlass/issues/1156#issuecomment-956281382?

**Comment by EgeGurkan** [comment]
Hi that reg entry won't work because I don't have photoviewer.dll in my system so this is invalid "Clsid"="{60fd46de-f830-4894-a628-6fa81bc0190d}

I use custom ntlite edited windows 11 I made. never had any problems about printing with other photoviewers. can you change dependancy I don't like old things in my system just to use a software.

also: placing PhotoViewer.dll file and restoring via reg didn't work.

**Comment by d2phap** [comment]
The Print Pictures dialog provides a good print preview which it takes more effort to implement in WinForms. I have been searching for a way to use the WinUI Print dialog from Win10/11, but it requires XAML root element to display print preview.

I will close this issue, you can follow #604 instead.
