### ISSUE TITLE
[suggestion]Add mouse shortcut key and features

### ISSUE THREAD

**Issue by veizei-K** [d2phap/ImageGlass#1877]
1.When the mouse wheel zooms in on the image, i want the whole window to zoom in or out so that the window can display 100% of the image
2.When press and hold the right mouse button on the image and drag it, i can directly drag the entire window

**Comment by d2phap** [comment]
Hi @freedomspiritJohn 

> 1. When the mouse wheel zooms in on the image, i want the whole window to zoom in or out so that the window can display 100% of the image

You can enable Window Fit mode:
![image](https://github.com/d2phap/ImageGlass/assets/3154213/dfdc7e63-7a2d-40e5-bb80-e7ad07089613)


> 2. When press and hold the right mouse button on the image and drag it, i can directly drag the entire window

You can hold SHIFT key and left mouse to drag the window.
