### ISSUE TITLE
Allowing multiple Instances

### ISSUE THREAD

**Issue by ghost007** [d2phap/ImageGlass#188]
Its labed wrong, at least in the GERMAN Translation

### Expected behavior:
Don't allow multiple instances = only one window open, when i open a new picture

### Actual behavior:
every picture opens a new window.

### solution:
just change the translation to: "Mehrere Programminstanzen erlauben"
that means: Allow multiple Instances - which is the shown behavior.

THX

**Comment by d2phap** [comment]
Thanks @ghost007 

I just updated the translation.
You are also able to change it directly here:
https://crowdin.com/translate/imageglass/12/en-de
