### ISSUE TITLE
Possible to have .dll files in program files to be signed by publisher (Windows)?

### ISSUE THREAD

**Issue by GHM3434** [d2phap/ImageGlass#1881]
Hi, Is it possible to have .dll files in C:\program files\imageglass to be signed by a publisher? The installer .exe file is signed by the publisher which is great but WDAC (Windows Defender Application Control) is blocking the program from being opened. I'm not sure exactly which .dll files are needed to be signed but it's a lot of them. So far, the list of .dll that needs to be signed are:

ImageGlass.dll
ImageGlass.Setting.dll
ImageGlass.UI.dll
Microsoft.Extensions.Configuration.CommandLine.dll
Microsoft.Extensions.Configuration.Binder.dll
WicNet.dll
Magick.NET.Core.dll
FileWatcherEx.dll
Magick.NET.SystemDrawing.dll
stopped looking after here..

Would it be too much effort to sign all .dll files in C:\Program Files\ImageGlass ?

### System information:
 - Windows OS version: Windows 11 23H2
 - ImageGlass version: 9.0.10.201

### To Reproduce
1. Enable WDAC
2. Install ImageGlass
3. Open ImageGlass

### Actual behavior:

WDAC blocks ImageGlass from opening because various .dll files are not signed

### Expected behavior:

Open ImageGlass normally when WDAC is enabled

**Comment by d2phap** [comment]
DLL files are signed in v9.0.11
