### ISSUE TITLE
Please enable middle crop selection handle back.

### ISSUE THREAD

**Issue by chocobon** [d2phap/ImageGlass#1882]
ImageGlass Version: 9.0.10.201 (64-bit)
WebView2 Runtime: 122.0.2365.92
.NET Runtime: 8.0.1

In Crop image feature, selection is now using 4 handles at each corner. 
Previous version was having 5 handles. Fifth handle is middle one. I could move resized crop selection box using this middle handle. Please enable middle crop selection handle back.

**Comment by d2phap** [comment]
Implemented in [ImageGlass 9.2 Beta](https://github.com/d2phap/ImageGlass/releases/tag/9.1.8.1104), refer to https://github.com/d2phap/ImageGlass/issues/1795#issuecomment-2454934725 for more details
