### ISSUE TITLE
[Bug] Not right size of max button

### ISSUE THREAD

**Issue by emako** [d2phap/ImageGlass#1883]
### System information:
 - Windows OS version: W11 pro 23H2
 - ImageGlass version: 
Version: 9.0.10.201 (64-bit)
WebView2 Runtime: 123.0.2420.65
.NET Runtime: 8.0.0

### To Reproduce
1. Hoving mouse to max button

### Actual behavior:

The button background size is not right.

### Expected behavior:

Right size of max button.

### Screenshots:

![image](https://github.com/d2phap/ImageGlass/assets/24737061/fb9a09c9-e90c-4f7d-8c45-6982cc92e2f1)

**Comment by d2phap** [comment]
This is the issue of Windows 11 🫠. Not only ImageGlass, if you open other Win32 apps, you will see the same.
