### ISSUE TITLE
Errors while installing: Called RunScript, InstallFinalize when in progress

### ISSUE THREAD

**Issue by 57ar7up-3** [d2phap/ImageGlass#1884]
### System information:
 - Windows OS version: 22H2 (19045.2006)
 - ImageGlass version: 9.0.10.201_x64

### To Reproduce
1. Run installer

### Actual behavior:
Errors:
Called RunScript when not marked in progress
Called InstallFinalize when no install in progress

### Expected behavior:
Installing

### Screenshots:
![image](https://github.com/d2phap/ImageGlass/assets/129639487/2b187a80-ecad-4885-98b2-d5f15937f4d0)

### Additional context:
[MSI35daf.LOG](https://github.com/d2phap/ImageGlass/files/14899003/MSI35daf.LOG)

**Comment by d2phap** [comment]
From https://answers.microsoft.com/en-us/windows/forum/windows_vista-windows_programs/error-2503-called-runscript-when-not-marked-in/76e72d98-cbef-432f-8f6f-40417d139bc1:

> Solved my own problem but thought I would post the "how I did it" for others that might encounter the same problem.
>
> Problem is in permissions on "C:\Windows\Temp" folder.
>
> Somehow Administrators-Full Control is not enough.
>
> Added permissions as "<My User> - Changed permissions and that was all I needed to do, Installer worked again.


Video: https://www.youtube.com/watch?v=IgazD-BRMG0
