### ISSUE TITLE
How to keep the entire window size the same when the image is scaled, but the image size is scaled inside the window?

### ISSUE THREAD

**Issue by MK-320** [d2phap/ImageGlass#1885]

**Comment by d2phap** [comment]
It seems that you accidentally enabled Window Fit mode:

![image](https://github.com/d2phap/ImageGlass/assets/3154213/dfdc7e63-7a2d-40e5-bb80-e7ad07089613)

**Comment by MK-320** [comment]
Thank  you！！

> 似乎您不小心启用了 Window Fit 模式：
> 
> ![image](https://private-user-images.githubusercontent.com/3154213/320172962-dfdc7e63-7a2d-40e5-bb80-e7ad07089613.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NjQ4OTYsIm5iZiI6MTcxMjY2NDU5NiwicGF0aCI6Ii8zMTU0MjEzLzMyMDE3Mjk2Mi1kZmRjN2U2My03YTJkLTQwZTUtYmI4MC1lN2FkMDcwODk2MTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDlUMTIwOTU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjYzMjdjZmQ4N2YxODNjNGMwMjdkM2JmYjBjY2EzNzY1YjYwZmZjNmFmODNjNzdkYWQ1OWQ3OGUyNWU4MTlkZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.exmIWU3_XSgLhAu6M1B23TVx6lCgjMd8fHfoNCCNncE)

Thank you！！
