### ISSUE TITLE
Full Screen mode in actual full screen

### ISSUE THREAD

**Issue by floppyD** [d2phap/ImageGlass#1887]
### Describe the solution you'd like
I just want it to behave exactly like slideshow mode but with the countdown disabled, could be an option. The current full screen mode is not really useful in my opinion.

**Comment by d2phap** [comment]
What do you mean by this?
> The current full screen mode is not really useful in my opinion.

The slideshow mode only has 20% features of full screen mode, I don't understand what you're requesting for

**Comment by floppyD** [comment]
Well, by full screen I expected the image to be in full screen, not the UI. The current "full screen mode" should've been the frameless mode imo

I'm asking for this feature since the only way to do display the image in full screen seems to be using the slideshow, which has a timer and is quite annoying for my purposes.

**Comment by d2phap** [comment]
@floppyD 

How did you trigger the Full screen? I wonder the "full screen" you mentioned is not the Full screen mode in IG. It's better if you attach screenshot or video.

This is the screenshot of Full screen mode: a frameless window covers entire desktop including taskbar
![image](https://github.com/d2phap/ImageGlass/assets/3154213/ea8ef276-1bd9-46b8-a132-3cce7ad077f6)

**Comment by floppyD** [comment]
I know, I'm asking for something like this, just the image in full screen, like in slideshow mode (F12)
![image](https://github.com/d2phap/ImageGlass/assets/29208110/7759e151-9173-4c6c-bd81-6d988da683be)

The current "full screen" mode (F11) is kinda misleading, I think it should be called "borderless", since you are removing the borders, not actually making the content "full screen"
![image](https://github.com/d2phap/ImageGlass/assets/29208110/700be4e7-fdf5-486c-9fae-b4f0ddaff173)

---

Just for comparison, see how full screen behaves on browsers, it doesn't just remove the borders, it makes the content (webpages) full screen.

Before
![image](https://github.com/d2phap/ImageGlass/assets/29208110/cffd54a6-bd02-422f-a364-ba48bee8d03f)

After
![image](https://github.com/d2phap/ImageGlass/assets/29208110/afb555cd-1f24-4f5e-9c63-471192faf9c2)

**Comment by d2phap** [comment]
You can hide the toolbar and gallery for full screen mode in Settings:

![image](https://github.com/d2phap/ImageGlass/assets/3154213/5e73034a-4ed1-4b96-994b-65a2ff22ce32)

**Comment by floppyD** [comment]
Hahaha no way, I would never look for this option there. Thanks and sorry to bother you.

**Comment by floppyD** [comment]
Actually I found a bug in just one minute lol
If you enable full screen (F11) then close the program with alt+F4, the next time you open it it'll still be in full screen, and even if you press F11 to return to normal mode, the toolbar will be gone. You have to bring it back manually by pressing T or under the context menu.

[asdasd.webm](https://github.com/d2phap/ImageGlass/assets/29208110/59b900fd-f70c-40ce-aa6e-82feb01dc671)

**Comment by d2phap** [comment]
Full Screen is a window mode (same as Window Fit, Frameless), ImageGlass saves and restores its state
