### ISSUE TITLE
Default theme dark mode, BG color is not gray

### ISSUE THREAD

**Issue by optical-core** [d2phap/ImageGlass#1888]
![gl反馈](https://github.com/d2phap/ImageGlass/assets/39340555/09b8c6cc-9277-40cc-8cbd-d93d7a21625f)
Default theme dark mode, BG color is not gray.
In color work, BG color can affect the judgment of color.
In the top left corner, The bright blue icon also interferes, hoping to allow users to hide it.
I hope the default theme BG color to gray, For example: #202020

**Comment by d2phap** [comment]
The color scheme just follows my preference.
You can create your own theme pack, refer to https://imageglass.org/docs/theme-pack

To hide app logo, uncheck this option:
![image](https://github.com/d2phap/ImageGlass/assets/3154213/dbddfdd1-b3e5-4bc7-aca8-21bd89933415)
