### ISSUE TITLE
Opening in maximized view flashes white

### ISSUE THREAD

**Issue by Karob2** [d2phap/ImageGlass#1889]
### System information:
 - Windows OS version: Windows 10 Pro 22H2
 - ImageGlass version: 9.0.10.201 (64-bit)

### To Reproduce
1. Open ImageGlass.
2. Switch to a dark theme if not already on a dark theme.
3. Press the maximize button on the title bar if the app is not already maximized.
4. Close ImageGlass.
5. Open ImageGlass.

### Actual behavior:
The whole window flashes white when opening directly into a maximized view. This does not occur when the window is not maximized (not taking up the full screen). This also does not occur in fullscreen (F11) mode.

### Expected behavior:
The window should be a color appropriate to the theme when first opened, instead of white.

**Comment by d2phap** [comment]
Should be fixed in [ImageGlass 9.1 Beta](https://github.com/d2phap/ImageGlass/releases/tag/9.0.11.529)
