### ISSUE TITLE
Version 9 is still not working without admin rights (to install .net desktop runtime) as runtime is not integrated in IG

### ISSUE THREAD

**Issue by svenbolte** [d2phap/ImageGlass#1895]
### System information:
 - Windows OS version:  11 Pro (23H2 moment5)
 - ImageGlass version:   9.0.10.201_x64 (ZIP unpacked)

### To Reproduce
1.running the ig exe informs that you must install the .net desktop runtime 8.0.4
2. install that runtime does not work for all users without admin rights
3. even when admin installs the runtime it (runtime) runs services in background and wastes memory

### Actual behavior:
1) normal users without at least localadmin cannot install V9
2) Using v8 portable is ceased security updates vom April 23m 2024, so it will be unsafe to use once 
3) no security updates for V8 now

### Expected behavior:
running portable with the dot net desktop runtime integrated into imageglass (as paint.net and others do)

Will there be a real portable version with .net desktop framework integrated or must we all remove the very good and useful and slim Classic Version 8 and try to find another product? Dont want to use the microsoft foto gallery tho 📦

**Comment by d2phap** [comment]
No, I don't want to maintain another download option. It's easier just to install .NET 8, I don't see any issue with it.


> 3. even when admin installs the runtime it (runtime) runs services in background and wastes memory

This is wrong statement

> must we all remove the very good and useful and slim Classic Version 8 and try to find another product?

Refer to v8.12 release > FAQs number 4. Thank you.
