### ISSUE TITLE
[enhancement] An option to disallow multiple instances of the program if it is already running

### ISSUE THREAD

**Issue by psbj** [d2phap/ImageGlass#19]
Let's say you open ImageGlass by double-clicking on an image. If you double-click on another image, it should open in the ImageGlass window that is already open.

As it is now, if you click on 5 images, it opens 5 windows. This option would have the current image being viewed in the window to the image that was double-clicked.

Basically, the same thing as dragging and dropping an image into the window.

**Comment by d2phap** [comment]
This feature was supported in the commit: https://github.com/d2phap/ImageGlass/commit/7da90100c1a88ee035be90408e5658bc5590faf9
