### ISSUE TITLE
[bug] Going into fullscreen mode (F11, Alt+Enter) doesn't refresh the image size

### ISSUE THREAD

**Issue by nhantrn** [d2phap/ImageGlass#190]
### Expected behavior:
Going into fullscreen mode should redraw the image to fit fullscreen size.

### Actual behavior:
Image stays at openning size.

### Steps to reproduce:
Go into fullscreen/slideshow mode

### System info:
- ImageGlass version: 4.x
- OS version: Windows 10

**Comment by d2phap** [comment]
Hi @nhantrn 

This is correct behaviour.
Fullscreen mode is just to extend the window size, the viewing image still remains its state so that user will not loose the current zoom ratio of viewing image.
Thanks for your post.

**Comment by nhantrn** [comment]
Can you create an option disable disable this behavior? Because logically when doing slideshow, one would expect it to be fullscreen.

**Comment by d2phap** [comment]
Hi, can you just press F5 (Refresh button) / or click the middle mouse button? 
Since the next images will be auto-fit already.

**Comment by nhantrn** [comment]
I could do that, but it still bugs me since other image viewer programs don't do this.

The default behavior is fit to window, so when going into full screen mode it should also fit to the screen because the user did not change their zooming preference.
