### ISSUE TITLE
apng files get removed from the image list once you go to next or previos image

### ISSUE THREAD

**Issue by RalfReddings** [d2phap/ImageGlass#1901]
### System information:
 - Windows OS version: windows 11
 - ImageGlass version: 9.0.5.726 (64 bit)

### To Reproduce
1. Load a `.apng` image 
2. go to next/previous image
3. cant navigate back to the `.apng` file

If I open a folder with a `.apng` file like the following:
    
    C:\temp\Charles Martel.jpg
    C:\temp\lexter_arts.jpg
    C:\temp\quarters .jpg
    C:\temp\sample_apng.apng
    
The animation for `sample_apng.apng` does play but once I go to next or previous file, there is no way to go back to the `sample_apng.apng` file. In fact the `.apng` is not listed in the thumbnails.

The only way to get  `sample_apng.apng`  is dragging it from the file browser window to Image glass

![](https://i.imgur.com/ZgHdr7b.gif)

**Comment by d2phap** [comment]
Make sure `.apng` extension in the Format list

![image](https://github.com/d2phap/ImageGlass/assets/3154213/c984e32b-26e1-431a-bee4-01fc00cc24f1)
