### ISSUE TITLE
Command to set ImageGlass background to black, white or red etc etc

### ISSUE THREAD

**Issue by RalfReddings** [d2phap/ImageGlass#1902]
I work with transparent images a lot, often I need to set the background to either black or white.

For example the following animation (a `.apng` file) has a lot of anti aliasing artifacts around its border, a white background would be ideal for it:
![](https://i.imgur.com/r7xIF6e.gif)

Currently ImageGlass has only two background options, Checkered and some kind of gradient background.
Can we please get commands to set ImageGlass background to white or black, or even better the ability to predefine your own custom colour such as red or blue and to be able to enable it with a hotkey.

Thanks.

**Comment by d2phap** [comment]
You can change the background color in app Settings > Appearance
![image](https://github.com/d2phap/ImageGlass/assets/3154213/d45b7b79-637a-4a9c-8ca6-f8094f9eaae0)
