### ISSUE TITLE
Unable to minimize ImageGlass when using Frameless or Fullscreen mode

### ISSUE THREAD

**Issue by CharisRipple** [d2phap/ImageGlass#1904]
### System information:
 - Windows OS version: Win10 22H2
 - ImageGlass version: 9.0.11.502 (64-bit)

### To Reproduce
1. Select Frameless or Fullscreen mode
2. Click on taskbar or (win+M) or (win+down arrow)
3. 
4. 

### Actual behavior:

When using Frameless or Fullscreen mode without "Keep windows always on top", ImageGlass window cannot be minimized through taskbar or windows shortcut.
When using the Frameless mode, while (win+M) does nothing, (win+down arrow) can be used to normalize a maximized ImageGlass window, but won't be able to minimize it.

### Expected behavior:

Minimize ImageGlass window.

### Additional context:

It is possible to minimize the window by using task manager and right click the sub task then select Minimize.

**Comment by d2phap** [comment]
Should be fixed in [ImageGlass 9.1 Beta](https://github.com/d2phap/ImageGlass/releases/tag/9.0.11.529)
