### ISSUE TITLE
ImageGlass keep re-center itself of the screen.

### ISSUE THREAD

**Issue by HumanMus1c** [d2phap/ImageGlass#1905]
Issue:
The ImageGlass keep re-center itself by switching images after turn on "keep window always on top", This is really annoying me. Please make it not re-center itself while the "keep window always on top" been turn on. Thanks.

**Comment by HumanMus1c** [comment]
![recording](https://github.com/d2phap/ImageGlass/assets/46023154/854a54e5-f13d-4ca4-a9f9-c598298a45f0)

**Comment by d2phap** [comment]
It seems you're in Window Fit mode. You need to deselect this setting:

![image](https://github.com/d2phap/ImageGlass/assets/3154213/093e1dad-9456-46e7-b448-af8b19a37c50)

**Comment by HumanMus1c** [comment]
thanks, my bad.
