### ISSUE TITLE
Animated gifs aren't moving in ImageGlass 9.0.11

### ISSUE THREAD

**Issue by DreamyPixels** [d2phap/ImageGlass#1907]
### System information
- Windows OS version: Windows 11 Home 23H2
- ImageGlass version: 9.0.11.502
- ImageGlass release: Classic

### To Reproduce
1. Open any animated .gif file in ImageGlass

### Actual behavior
Animated .gif images appear as still images and don't move as expected

### Expected behavior
Images should move

### Screenshots / Video / Sample image file
[Video example](https://github.com/d2phap/ImageGlass/assets/9969882/d18206e2-6f56-4141-a6e2-6a143f58cf6d)
[Gif used, for reference](https://github.com/d2phap/ImageGlass/assets/9969882/02802e69-cff4-44c0-b98c-0edbce7eb629)

### Additional context
Worked completely normally up until the latest update.

**Comment by d2phap** [comment]
This is upstream issue (MagickNET v13.7), I will report to them

**Comment by davidbejarcaceres** [comment]
Same problem for animated AVIF. The option in Menu > Image > Start / "Stop animating image" is enabled, but the animated AVIF is still.

**Comment by d2phap** [comment]
@davidbejarcaceres IG does not support playing animated AVIF format

**Comment by d2phap** [comment]
Fixed in [ImageGlass 9.1 Beta](https://github.com/d2phap/ImageGlass/releases/tag/9.0.11.529)
