### ISSUE TITLE
Bring back scrollbars (or at least make an option to have them)

### ISSUE THREAD

**Issue by nywilds** [d2phap/ImageGlass#191]
Would you consider adding an option to enable scrollbars (which got taken out in version 3.0.9.2)? I sometimes find them useful for navigation (especially if I'm looking at a tall, narrow image), as well as for keeping track of where I am if I'm zoomed into a really large image.

**Comment by d2phap** [comment]
Hi @nywilds 
Thanks, I will tag this as suggestion

**Comment by d2phap** [comment]
Implemented
