### ISSUE TITLE
Cant zoom in or out with .SVG files.

### ISSUE THREAD

**Issue by DRGFL** [d2phap/ImageGlass#1911]
### System information
- Windows OS version: Windows 11 22631.3447
- ImageGlass version: 9.0.11.502 (64-bit)
- ImageGlass release: Classic

### To Reproduce
1. Open an SVG with ImageGlass.
2. Use scrollwheel to zoom in or out.
3. 
4. 

### Actual behavior
After using the scrollwheell to zoom the SVG in or out, it zoom out the image to maximum level and I cant zoom in it back.

### Expected behavior
The zoom with scrollwheel function should work normally.

### Screenshots / Video / Sample image file

https://github.com/d2phap/ImageGlass/assets/155883444/fb578f15-1181-469d-863f-9f3fca39bee0

SAMPLE FILE:
![YOLO](https://github.com/d2phap/ImageGlass/assets/155883444/10fe2083-f50f-475b-8dd2-cf44d943a0ba)

### Additional context
**_There is one more problem, but i think it's not a bug. The font i used in my svg artwork does not show correctly unless i installed it for my OS._**
Pls notify me when this bug get fixed

**Comment by d2phap** [comment]
This issue happens to some users (#1766), unfortunately I haven't been able to reproduce it yet.
Please refer to #1766 for future update
