### ISSUE TITLE
NVIDIA graphics card + CMYK color mode renders color abnormally

### ISSUE THREAD

**Issue by wzddl** [d2phap/ImageGlass#1914]
### System information
- Windows OS version: Windows10 22H2
- ImageGlass version: 9.0.10.201 (64-bit)
- ImageGlass release: Store / Classic? Store

### To Reproduce
1. CorelDRAW design shape by CMYK mode
2. output bitmap ( any format , jpg / png  etc. )
3. use ImageGlass load file to preview
4. oh~ the color it's so strange

### Actual behavior

The colors displayed in ImageGlass are very different from the display effects of other image browsers (such as the photo browser provided by Windows 10 system)

### Screenshots / Video / Sample image file
Color gap narrows

### Additional context
I found that this problem seems to be related to the graphics card and GPU manufacturer. My last graphics card was AMD RX6650 XT, and now I am using RTX 4080. This problem does not exist on AMD graphics cards, including when I use an older ImageGlass version, or newer. Old AMD graphics cards do not have this problem, and when I tried to use the Intel core GPU to drive the display, there was no problem of too much color difference.

![Snipaste_2024-05-15_21-45-42](https://github.com/d2phap/ImageGlass/assets/41256087/f54d5d0f-a21c-43ca-896e-3bdd7fc3cfaa)

**Comment by d2phap** [comment]
@wzddl for problems related to image format, please attach a sample file

**Comment by wzddl** [comment]
@d2phap try this
![Test](https://github.com/d2phap/ImageGlass/assets/41256087/d5069f9b-91a0-4ba7-8c0d-44d5f05fbf58)

**Comment by d2phap** [comment]
I think you did not enable Color management, it looks the same for me in IG and Chrome:

![image](https://github.com/d2phap/ImageGlass/assets/3154213/dabd8c40-516d-42c7-b887-a1bbef9783dc)

You might select "Standard user" profile in the Quick Setup window which does not have Color management enabled by default:
![image](https://github.com/d2phap/ImageGlass/assets/3154213/a29c721d-2f46-4a76-b4ab-c102b1efe41e)

**Comment by wzddl** [comment]
> I think you did not enable Color management, it looks the same for me in IG and Chrome:
> 
> ![image](https://private-user-images.githubusercontent.com/3154213/331753877-dabd8c40-516d-42c7-b887-a1bbef9783dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMzQ0MDEsIm5iZiI6MTcxNjAzNDEwMSwicGF0aCI6Ii8zMTU0MjEzLzMzMTc1Mzg3Ny1kYWJkOGM0MC01MTZkLTQyYzctYjg4Ny1hMWJiZWY5NzgzZGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MThUMTIwODIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2FhMThkODY1MDhkZGEzNzg3MDM1OGYzODZlMTBlMjE4NTViMzA5Y2YzN2FlMDBkMmQ0ODY2ODI0ODJjMzc5MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TtJMf5gVIlGkMShUpY-bIAUcbAizRQ_YW0LLpURRNHg)
> 
> You might select "Standard user" profile in the Quick Setup window which does not have Color management enabled by default: ![image](https://private-user-images.githubusercontent.com/3154213/331753995-a29c721d-2f46-4a76-b4ab-c102b1efe41e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMzQ0MDEsIm5iZiI6MTcxNjAzNDEwMSwicGF0aCI6Ii8zMTU0MjEzLzMzMTc1Mzk5NS1hMjljNzIxZC0yZjQ2LTRhNzYtYjRhYi1jMTAyYjFlZmU0MWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MThUMTIwODIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTViZDRhMTVlZmMzYjBjN2ZjOGYxNWYxNTY5MGE3YThhMGRlODUzMDc5NmE5MWM4NTk3Mzk1YjJkYTgwYmU2ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5R3StPN6JdwQVLO6tPkCa6n2wfIYzAzIfsM8KEiqSIw)

**Thanks, It's working ~~~~~**
