### ISSUE TITLE
Imageglass window will not appear in the correct screen

### ISSUE THREAD

**Issue by tjjh89017** [d2phap/ImageGlass#1918]
### System information
- Windows OS version: Windows 11
- ImageGlass version: 9.0.11.502
- ImageGlass release: Store / Classic? Classic

### To Reproduce
1. Have two screen with Window 11
2. Open imageglass and put it into the 2nd screen
3. close imageglass
4. switch 2nd switch to other video source (PC will only have main screen)
5. open imageglass again

Another about slideshow
1. Have two screen with Window 11
2. Open imageglass and put it into the 2nd screen
3. start slidesshow in 2nd screen
4. stop imageglass slideshow
6. close imageglass program
7. switch 2nd switch to other video source (PC will only have main screen)
8. open imageglass again

Another about slideshow (different for this above)
1. Have two screen with Window 11
2. Open imageglass and put it into the 2nd screen
3. start slidesshow in 2nd screen
4. stop imageglass slideshow
6. close imageglass program
7. open imageglass again (don't start slideshow)
8. move imageglass to main screen
9. close imageglass
10. switch 2nd switch to other video source (PC will only have main screen)
11. open imageglass again (this part will be normal)
12. start slidesshow
13. slidesshow window will not appear

### Actual behavior

Get nothing. Nothing shows up
I cannot move imageglass to my main screen.

### Expected behavior

It should show up in the main screen (the only one screen)

### Screenshots / Video / Sample image file

Didn't depend on any specific image file.

**Comment by d2phap** [comment]
Thanks @tjjh89017, it's duplicated of #1865

**Comment by d2phap** [comment]
Should be fixed in [ImageGlass 9.1 Beta](https://github.com/d2phap/ImageGlass/releases/tag/9.0.11.529)

**Comment by tjjh89017** [comment]
> Should be fixed in [ImageGlass 9.1 Beta](https://github.com/d2phap/ImageGlass/releases/tag/9.0.11.529)

Thank you for your rapid fix!!!
I will try and test it once I get back to my home!!!
