### ISSUE TITLE
Sort by "Last Write Time" sorts by creation time for pngs

### ISSUE THREAD

**Issue by user234683** [d2phap/ImageGlass#192]
### Expected behavior:
In a test folder of 5 png images (1.png, 2.png, etc.), when Imageglass is set to load images by "Last Write Time", I expected the order of the images to be 2, 4, 1, 3, 5

### Actual behavior:
The order of the images in ImageGlass is 2, 1, 3, 4, 5, which is the same as ordering by the creation date.

### Steps to reproduce:
1. Make a folder of png images
2. Make sure their date modified and date created are different so ordering by those would yield a different order
3. Compare to the order Imageglass gives when ordering by "Last Write Time"
4. Do the same but with a folder of jpg, notice ImageGlass orders them correctly.

### System info:
- ImageGlass version: 4.0.4.15
- OS version: Windows 7 64-bit

### Other info:
I can't tell what it's doing when a folder has a mix of jpgs and pngs. The pngs don't seem to be substituting date created in that case, but something else (they get put in the wrong place still).

Here's the file info for my test folder of pngs (none of them have an EXIF time taken) I used python to get the times. I checked them against what windows explorer reports, and it's the same:
```
Python data, raw epoch time (File name, date modified, date created)
1.png      1462076523.19      1495395838.0
2.png      1491028419.54      1495390620.17
3.png      1445149066.64      1495395838.01
4.png      1468713766.68      1495395869.4
5.png      1423235833.21      1495395876.53

Python data (File name, date modified, date created)
1.png      04/30/2016 21:22:03      05/21/2017 12:43:58
2.png      03/31/2017 23:33:39      05/21/2017 11:17:00
3.png      10/17/2015 23:17:46      05/21/2017 12:43:58
4.png      07/16/2016 17:02:46      05/21/2017 12:44:29
5.png      02/06/2015 07:17:13      05/21/2017 12:44:36

Explorer Sort by date modified (latest to earliest):
2, 4, 1, 3, 5
Explorer Sort by date created (latest to earliest, does not take into account milliseconds):
5, 4, 1, 3, 2
Image glass sort by last write time (incorrect):
2, 1, 3, 4, 5
Image glass sort by creation time (correct):
2, 1, 3, 4, 5
```

**Comment by d2phap** [comment]
Hi @user234683 
thanks for the details of this bug

**Comment by fire-eggs** [comment]
I was unable to reproduce this issue with IG 5.1.x.  I set up a folder on Windows 7 x64 with 5 PNGs, and distinct write/create times. ImageGlass showed the files in the correct order, for both LastWriteTime and CreationTime settings.

If this issue is still a problem, please re-open with particulars.
