### ISSUE TITLE
The thumbnail doesn't match real image content.

### ISSUE THREAD

**Issue by suyangzuo** [d2phap/ImageGlass#1922]
### System information
- Windows OS version:  Windoes 11 23H2
- ImageGlass version: 9.0.11.502
- ImageGlass release: Classic

### To Reproduce
1. Double click a image to open it by ImageGlass
2. The thumbnail doesn't match real image content.

<img width="732" alt="PixPin_2024-05-25_21-31-06" src="https://github.com/d2phap/ImageGlass/assets/50766353/cd73e183-be1b-4acf-b595-f4c2dbdc4791">

And this is my folder content in windows explorer:
<img width="733" alt="PixPin_2024-05-25_21-34-34" src="https://github.com/d2phap/ImageGlass/assets/50766353/7e6dde3e-7cac-4899-b385-bcc889794014">

**Comment by d2phap** [comment]
Should be fixed in [ImageGlass 9.1 Beta](https://github.com/d2phap/ImageGlass/releases/tag/9.0.11.529)
