### ISSUE TITLE
First time installation of ImageGlass using Chocolatey, successfully installs dependencies including WebView2, but ImageGlass doesn't see WebView2

### ISSUE THREAD

**Issue by matttrv** [d2phap/ImageGlass#1923]
### System information
- Windows OS version: 11 Pro N Insider Preivew (23H2, [Version 10.0.25977.1000], OS Build = 25977.1000 )
- ImageGlass version: v9.0.11.502
- ImageGlass release: Installed via Chocolatey (choco version v2.2.2)

### To Reproduce
1. Executed "``choco install imageglass``"
2. **Chocolatey** successfully installed imageglass and dependencies, including **WebView2**
3. Ran **ImageGlass** from start menu
4. ImageGlass shows in the main window, "*Please install the latest version of WebView2 Runtime*".

### Actual behavior
**ImageGlass** is telling me that I need to install **WebView2 Runtime**, but it has already been installed by **Chocolatey** as a dependency when I ran "``choco install imageglass``".

### Expected behavior
**ImageGlass** should have run successfully.

### Screenshots / Video / Sample image file
Screenshot of successful install via **Chocolatey**. (happy to provide verbose install progress screenshots as well)
![Screenshot 2024-05-25 112407](https://github.com/d2phap/ImageGlass/assets/77462293/9265d763-e7ea-493a-81ca-609551512765)

Screenshot of **ImageGlass** window which suggests that **WebView2** has not been installed and needs to be.
![Screenshot 2024-05-25 112418](https://github.com/d2phap/ImageGlass/assets/77462293/c73e43a2-99a8-471d-ab93-2c7ebb7bbc4d)

### Additional context
This differs from [Issue #1890](https://github.com/d2phap/ImageGlass/issues/1890) in that [#1890](https://github.com/d2phap/ImageGlass/issues/1890) is upgrading **WebView2**.  I am installing **ImageGlass** (and **WebView2**) for the first time. 

Is it possible that I need to point **ImageGlass** to **Chocolatey**'s location for **WebView2**?  If so, I wonder if it is possible to configure **ImageGlass** to do that at the time of install via **Chocolatey** using an install script.

Happy to share additional screenshots if it's helpful.

**Comment by chrishenn** [comment]
I also hit this error. 
I tried to install the webview2 runtime from microsoft's installer, and at first it failed - claming "webview2 runtime is already installed". 
Reboots and trying the standalone microsoft installer a second time, I was able to install the non-chocolatey webview2 runtime and imageglass was able to start normally

**Comment by d2phap** [comment]
This is probably the issue of the WebView2 package in Chocolatey.
ImageGlass shows the "Please install the latest version of WebView2" message if
- It cannot detect the WebView2 version through the [`GetAvailableBrowserVersionString()`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.getavailablebrowserversionstring?view=webview2-dotnet-1.0.2478.35#microsoft-web-webview2-core-corewebview2environment-getavailablebrowserversionstring(system-string)) API, or
- The version is older than `119.0.2151`


Alternatively, if you run ImageGlass 9.0.11.502 or later, you can use the Fixed Version of WebView2 for ImageGlass. Follow steps in the `Changelog > New Features > Added support for custom WebView2 Runtime` in this link https://github.com/d2phap/ImageGlass/releases/tag/9.0.11.502 to know how to do it.

![image](https://github.com/d2phap/ImageGlass/assets/3154213/9ad7d2dc-6bf1-42df-81f9-6b157e8a6d45)
