### ISSUE TITLE
In frameless mode, the application window will shrink due to restart

### ISSUE THREAD

**Issue by Lesliechueng23** [d2phap/ImageGlass#1924]
### System information
- Windows OS version: Win11_23H2_22631.3593
- ImageGlass version:9.0.10.201 (64-bit) / WebView2 Runtime: 125.0.2535.67 / .NET Runtime: 8.0.3
- ImageGlass release: Classic

### To Reproduce
1. F10 Enable frameless mode
2. Open image file
3. Close the program (e.g. using the Esc key)
4. Open the same image file again

### Actual behavior
 The size of the program window has decreased slightly compared to the previous time.

### Expected behavior
The size of the program window should remain unchanged. 

Case
![1](https://github.com/d2phap/ImageGlass/assets/107962897/08035ad6-9f12-4edb-bc4e-a6c34cf886f0)
![2](https://github.com/d2phap/ImageGlass/assets/107962897/c2dd6941-e782-4f26-abdd-13474a5a0ed8)
![3](https://github.com/d2phap/ImageGlass/assets/107962897/8ccb6c2a-a8e6-4cbf-9c1b-ae1caf529ab1)

Comparison of Three Test Results
![image](https://github.com/d2phap/ImageGlass/assets/107962897/267d11de-b049-4e84-bcd5-b661fde5deb5)

**Comment by Lesliechueng23** [comment]
![1](https://github.com/d2phap/ImageGlass/assets/107962897/d6f8c1cc-c4ba-40b8-b71c-83a666d1059c)

Version：9.1.6.14

**Comment by d2phap** [comment]
This issue is fixed in [ImageGlass 9.1.7.627](https://github.com/d2phap/ImageGlass/releases/tag/9.1.7.627)
