### ISSUE TITLE
ImageGlass 9.0 ignores HEIC orientation

### ISSUE THREAD

**Issue by arnileibovits** [d2phap/ImageGlass#1928]
### System information:
* Windows OS version: 11 23H2
* ImageGlass version: 9.0.11.502
 
### Actual behavior:
All images display in landscape orientation
 
### Expected behavior:
Image should be oriented to correct orientation
 
Screenshots
[ImageGlass_test_HEIC_rotation.zip](https://github.com/d2phap/ImageGlass/files/15499226/ImageGlass_test_HEIC_rotation.zip) contains 4 example photos with rotation 0°, -90°, -180° and -270°. These work as expected on iPhone, Windows (Explorer, Photos, Paint etc), Slack and other apps.

Screenshot of expected behavior:
![iPhone HEIC rotation](https://github.com/d2phap/ImageGlass/assets/5457121/f4cbd1c3-2b26-47e9-8be6-4c3c55e871ff)

Related issue: https://github.com/d2phap/ImageGlass/issues/1551

**Comment by Charltsing** [comment]
settings.SetDefines(new HeicReadDefines
{
    PreserveOrientation = false,  
});

**Comment by d2phap** [comment]
Fixed in [ImageGlass 9.1.8.723](https://github.com/d2phap/ImageGlass/releases/tag/9.1.8.723)
