### ISSUE TITLE
Unhandled exception when 3 or more new images are moved/copied into the folder in which the current image is being viewed

### ISSUE THREAD

**Issue by user234683** [d2phap/ImageGlass#193]
### Expected behavior:
Self-explanatory, see title.

### Actual behavior:
I've only managed to get this to happen with 3 images or more. Haven't managed with 2 or 1 new images. It doesn't always happen, but copying a large number of images is very likely to cause it to happen.

### Steps to reproduce:
1. Open an image in a folder of images
2. Move a ton (like 15 or more) new images into that folder
3. Should crash with the error. Might take a few tries messing with it, moving images back and forth.

### System info:
- ImageGlass version: 4.04.15
- OS version: Windows 7 64-bit

### Other info:
After putting some images in the folder, and ImageGlass doesn't crash, if you move them out by using CTRL-Z in Explorer, sometimes there are leftover phantom images in the thumbnail bar that can't be selected.

With the error, if you have a lot of images, and you click "Continue", it might give you a few more of those errors as it populates the thumbnail bar with the new images. Once populated, some images are missing. Also, in general, when moving images in and out of a folder, the selected image is usually changed as a result.

**Comment by d2phap** [comment]
Thanks @user234683 
Confirmed this bug

**Comment by d2phap** [comment]
This defect is fixed in ``develop`` branch
