### ISSUE TITLE
打开程序报错不支持此端口

### ISSUE THREAD

**Issue by ghost** [d2phap/ImageGlass#1930]
### System information
- Windows OS version: win11 pro 23H2
- ImageGlass version:版本：9.0.11.529 .NET：8.0.6
- ImageGlass release: Store / Classic?classic

### To Reproduce
1. 打开程序就显示报错

### Expected behavior

Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Web.WebView2.Core.Raw.ICoreWebView2WebMessageReceivedEventArgs2'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{06FC7AB7-C90C-4297-9389-33CA01CF6D5E}' failed due to the following error: 不支持此接口 (0x80004002 (E_NOINTERFACE)).

### Screenshots / Video / Sample image file

![微信截图_20240606171439](https://github.com/d2phap/ImageGlass/assets/152046622/2bf7f979-9d64-41a9-bde9-9aa233f8140f)

**Comment by d2phap** [comment]
Your WebView2 version is outdated, must be v119.0.2151 or later
