### ISSUE TITLE
Title bar reports sRGB for images that are not sRGB

### ISSUE THREAD

**Issue by PaulCoddington** [d2phap/ImageGlass#1932]
### System information
- Windows OS version: 11
- ImageGlass version: 9.0.11.502
- ImageGlass release: Store / Classic? Classic

### To Reproduce
1. Open wide gamut image in ImageView (eg: Display P3, etc)

### Actual behavior

Title bar reports the image is sRGB.

### Expected behavior

Title bar should report the image is Display P3, etc.

**Comment by d2phap** [comment]
See https://github.com/d2phap/ImageGlass/discussions/1593#discussioncomment-9593401

This issue is fixed in v9.1

**Comment by PaulCoddington** [comment]
> See [#1593 (reply in thread)](https://github.com/d2phap/ImageGlass/discussions/1593#discussioncomment-9593401)
> 
> This issue is fixed in v9.1

Issue still persists for me in v9.1.8.x.
