### ISSUE TITLE
9.0.11.502 and 9.1.6.14 won't launch/open due to InkScape PATH

### ISSUE THREAD

**Issue by Bishop0702** [d2phap/ImageGlass#1935]
### System information
- Windows OS version: Windows 10, 21H2, 19044
- ImageGlass version: 9.0.11.502, 9.1.6.14
- ImageGlass release: Classic (from GitHub releases)
- .Net Desktop Runtime version: 8.0.6.33720, x64 (no other .NET component installed)
- WebView2 Runtime version: 125.0.2535.92

### To Reproduce
1. Upgraded from 9.0.10.201 to 9.0.11.502, 9.0.11 wouldn't launch, no error message;
2. Uninstalled then re-installed ImageGlass 9.0.11 and .NET, still wouldn't launch, no error message
3. Uninstalled then re-installed ImageGlass 9.1.6 and .NET, still wouldn't launch, no error message
4. Uninstalled then re-installed ImageGlass 9.0.10 and .NET, launched normally

### Actual behavior
Double click on ImageGlass (9.0.11 and 9.1.6), the mouse cursor goes busy for a few moment then nothing happens, no error message

### Expected behavior
ImageGlass launches normally

### Additional context
Tried both 9.0.11 and 9.1.6 in a VM with the same system environment and both were working normally

**Comment by d2phap** [comment]
@Bishop0702 
Can you check the "Event Viewer" and apply some filters to find the error?

Also, can you look at this issue if it's similar https://github.com/d2phap/ImageGlass/issues/1915#issuecomment-2117345978

![](https://private-user-images.githubusercontent.com/3154213/331244871-1df4a76b-f638-41c1-a770-27c024308780.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMzA5NDQsIm5iZiI6MTcxODAzMDY0NCwicGF0aCI6Ii8zMTU0MjEzLzMzMTI0NDg3MS0xZGY0YTc2Yi1mNjM4LTQxYzEtYTc3MC0yN2MwMjQzMDg3ODAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTBUMTQ0NDA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmVjNzgxMTlhMzYyNzhlMGQ3Yjg5OTc0MTZmNmEzMjc3OGRmMGQ0ZTNhNDVjMWUzYTJiOGExZDE2ZmE4MmU4MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PeynDjWQCuYVXv5xwCn9DX4NdLlX-4kZA3iqwggZ3yw)

**Comment by Bishop0702** [comment]
> @Bishop0702 Can you check the "Event Viewer" and apply some filters to find the error?
> 
> Also, can you look at this issue if it's similar [#1915 (comment)](https://github.com/d2phap/ImageGlass/issues/1915#issuecomment-2117345978)
> 
> ![](https://private-user-images.githubusercontent.com/3154213/331244871-1df4a76b-f638-41c1-a770-27c024308780.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMzA5NDQsIm5iZiI6MTcxODAzMDY0NCwicGF0aCI6Ii8zMTU0MjEzLzMzMTI0NDg3MS0xZGY0YTc2Yi1mNjM4LTQxYzEtYTc3MC0yN2MwMjQzMDg3ODAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTBUMTQ0NDA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmVjNzgxMTlhMzYyNzhlMGQ3Yjg5OTc0MTZmNmEzMjc3OGRmMGQ0ZTNhNDVjMWUzYTJiOGExZDE2ZmE4MmU4MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PeynDjWQCuYVXv5xwCn9DX4NdLlX-4kZA3iqwggZ3yw)

![Snipaste_240611_005842](https://github.com/d2phap/ImageGlass/assets/43810531/4f8d65a5-959d-4165-9f4c-0ceb9af3af45)

I tried launching 9.0.11 and 9.1.6 again. Unfortunately nothing useful came up in the event viewer. Event ID 1023 is the only relevant one and that's because I intentionally launched ImageGlass without .NET installed. All other events are not related to ImageGlass.

The situation in #1915 doesn't really apply here as I don't have any other .NET component installed and I already uninstalled and re-installed .NET desktop runtime several times.

**Comment by jack-ii** [comment]
The same here, I came from 9.0.9

**Comment by d2phap** [comment]
The issue probably comes from MS Update, here are the similar issues that reported:
https://github.com/dotnet/runtime/issues/60144, https://github.com/dotnet/runtime/issues/100452, https://github.com/dotnet/runtime/issues/98576
Probably, reinstalling .NET 8 would fix but you also mentioned it does not fix for you.

Another thing to try is checking Task Manager if IG instance shows up when you open the app.

I will try to reproduce it in my Win10 VirtualBox

**Comment by Bishop0702** [comment]
> The issue probably comes from MS Update, here are the similar issues that reported: [dotnet/runtime#60144](https://github.com/dotnet/runtime/issues/60144), [dotnet/runtime#100452](https://github.com/dotnet/runtime/issues/100452), [dotnet/runtime#98576](https://github.com/dotnet/runtime/issues/98576) Probably, reinstalling .NET 8 would fix but you also mentioned it does not fix for you.
> 
> Another thing to try is checking Task Manager if IG instance shows up when you open the app.
> 
> I will try to reproduce it in my Win10 VirtualBox

Can confirm that IG instance shows up in Task Manager then closes itself soon after.

The Win10 VM I use always had its .NET component updated by Windows Update and both IG 9.0.11 and IG 9.1.6 work just fine in it.

**Comment by d2phap** [comment]
@Bishop0702 
Can you try deleting the folders: `%LocalAppData%\ImageGlass` (IG v9) and `%AppData%\ImageGlass` (IG v8)?

These folders are storing user settings.

**Comment by Bishop0702** [comment]
> @Bishop0702 Can you try deleting the folders: `%LocalAppData%\ImageGlass` (IG v9) and `%AppData%\ImageGlass` (IG v8)?
> 
> These folders are storing user settings.

Already did that every time I uninstalled/re-installed IG. Cleared all leftover files and reg traces. Didn't really help.

**Comment by luongson86** [comment]
This is the exact error I am getting!
- ImageGlass version: 9.0.11.502, 9.1.6.14
- Windows OS version: Edition: Windows 11 Pro, Version: 23H2, 1000.22700.1003.0
- WebView2 Runtime version: 125.0.2535.92

Back to 9.0.10.201 !

**Comment by LaunchLee** [comment]
I also meet the same thing. But when I uninstall Inkscape(maybe as the same as removing Inkscape from the PATH), ImageGlass can be opened. And I see when inkscape is in the PATH, running ImageGlass will also run Inkscape process that is presented in the task manager. The problem should be related to Inkscape.

**Comment by Bishop0702** [comment]
> I also meet the same thing. But when I uninstall Inkscape(maybe as the same as removing Inkscape from the PATH), ImageGlass can be opened. And I see when inkscape is in the PATH, running ImageGlass will also run Inkscape process that is presented in the task manager. The problem should be related to Inkscape.

Confirmed. Uninstalling Inkscape solved the problem! Nothing else was changed.

**Comment by Bishop0702** [comment]
Did some testing in VM.
Windows 10, 21H2, 19044
ImageGlass Classic, 9.0.10, 9.0.11, 9.1.6
Inkscape, 1.3.2, x64
.Net Desktop Runtime, 8.0.6, x64
WebView2 Runtime, 125.0.2535.92

ImageGlass was installed with all default settings.

Inkscape was installed with one of these options. Other settings were kept default.
![Snipaste_240613_211321](https://github.com/d2phap/ImageGlass/assets/43810531/9c0782fa-eb38-4815-9e93-19564a878600)

| Inkscape Installed with | IG 9.0.10 | IG 9.0.11 | IG 9.1.6 |
| --- | --- | --- | --- |
| Do not add to PATH | Y | N | Y |
| Add to PATH for all users | Y | N | N |
| Add to PATH for current user | Y | N | N |

Y: IG works normally
N: IG won't open

**Comment by d2phap** [comment]
Interesting!
The only thing that can be conflicted is the path of ImageMagick, I'm not sure if Inkscape uses ImageMagick library or not. I will check when I'm with my laptop.

Thanks a lot for the investigation

**Comment by d2phap** [comment]
@Bishop0702 
What version of Inkscape did you install?

I tried v1.3.2, v1.2.2, v0.92.3, the Inkscape Setup does not show the PATH options
![image](https://github.com/d2phap/ImageGlass/assets/3154213/27c71669-9ca2-4c8e-946e-efad81db8649)

**Comment by d2phap** [comment]
This issue is fixed in [ImageGlass 9.1.7.627](https://github.com/d2phap/ImageGlass/releases/tag/9.1.7.627)
