### ISSUE TITLE
Anti-Aliasing for Toolbar Icons Not Working Properly in ImageGlass 9.1.6.14

### ISSUE THREAD

**Issue by AWarthog** [d2phap/ImageGlass#1936]
### System information
- Windows OS version: Windows 11 23H2
- ImageGlass version: 9.1.6.14
- ImageGlass release: Store / Classic? Classic

### To Reproduce
1. Upgrade from stable release 9.0.11.502 to the latest stable release 9.1.6.14
2. Open ImageGlass
3. Icons look distorted
4. Uninstall ImageGlass
5. Install ImageGlass version 9.0.11.502
6. Icons render properly
7. Uninstall ImageGlass
8. Delete all folders containing themes or temporary files associated with ImageGlass
9. Install ImageGlass version 9.1.6.14
10. Icons look distorted even on a fresh install

### Actual behavior
Upgrading to the latest stable release of ImageGlass (9.1.6.14) causes icons to look distorted.

### Expected behavior
Upgrading to the latest stable release of ImageGlass (9.1.6.14) should result in icons rendering properly, as they did in the previous stable version (9.0.11.502).

### Screenshots / Video / Sample image file
Icons in version 9.0.11.502:
![image](https://github.com/d2phap/ImageGlass/assets/100887619/18c2c797-720f-47d2-801e-e2ee56cecb69)

Icons in version 9.1.6.14:
![image](https://github.com/d2phap/ImageGlass/assets/100887619/e6bafe74-9edb-46ba-af00-3b6201fa3612)

### Additional context
Rolling back to the previous stable version (9.0.11.502) resolves the issue. I have been able to replicate this behavior on three other computers. The resolution of the monitors for each computer tested was 1080p, with scaling set to 100% in the Settings app.

**Comment by d2phap** [comment]
This issue should be fixed, you can re-download the binary here [ImageGlass 9.1.6.14](https://github.com/d2phap/ImageGlass/releases/tag/9.1.6.14)

**Comment by AWarthog** [comment]
It works!
