### ISSUE TITLE
Images get stretched when rotating

### ISSUE THREAD

**Issue by FailSafeNow** [d2phap/ImageGlass#1937]
Win 11
9.16.14_x64
Classic

When I rotate an image, it doesn't automatically adjust the aspect ratio. It's annoying. I can get the aspect ratio to adjust by panning or zooming, but that's just not good enough. It should happen automatically.

Sometimes, actually, in addition to zooming, we get cropping. So there are two things that don't work right.

Look at these:
1. Normal image
2. Rotated clockwise
3. Rotated clockwise, panned, and then rotated normally again

![Screenshot 2024-06-11 185542](https://github.com/d2phap/ImageGlass/assets/65687160/2ec5cdef-b711-4005-ba5d-8843d02a161b)
![Screenshot 2024-06-11 185556](https://github.com/d2phap/ImageGlass/assets/65687160/500f31a9-848d-48a3-a3a9-443190ff2503)
![Screenshot 2024-06-11 185613](https://github.com/d2phap/ImageGlass/assets/65687160/bc80b748-8913-405d-b3b6-e84901d3e426)

**Comment by d2phap** [comment]
This issue is fixed in [ImageGlass 9.1.7.627](https://github.com/d2phap/ImageGlass/releases/tag/9.1.7.627)
