### ISSUE TITLE
Zooming in the svg file does not work properly.

### ISSUE THREAD

**Issue by triget** [d2phap/ImageGlass#1939]
### System information
- Windows OS version:  11
- ImageGlass version: 9.1.6.14 (64-bit)
- ImageGlass release:  Classic

### To Reproduce
1. Open test file test.svg
2. Try zoom in/out

### Actual behavior
Zoom changes from 0% to 10000%

### Expected behavior
Zoom behaves in exactly the same way as for other files such as jpg or png.

### Screenshots / Video / Sample image file

![bug](https://github.com/d2phap/ImageGlass/assets/9076850/d86267a9-3b10-4dc6-8220-bdf315ad9d19)
![test](https://github.com/d2phap/ImageGlass/assets/9076850/d80d1ce6-028d-42eb-91c1-2ab158c77dee)

**Comment by d2phap** [comment]
@triget this already reported at #1766. This issue happens to some users, currently I am not able to reproduce it yet
