### ISSUE TITLE
Translating array key name in menu

### ISSUE THREAD

**Issue by hNczy** [d2phap/ImageGlass#194]
### Expected behavior:
Translate the key commands names, not just the menu. 
Or use pictograms instead of the arrow keys names. I think its better.

### Actual behavior:
The menu name is translated, but the key command is stay english.
![shortcuts_lang](https://cloud.githubusercontent.com/assets/2458418/26487739/fb72cf82-4200-11e7-930f-79c13a9fcf1f.png)

### Steps to reproduce:
1. Open the program (I use Magyar/Hungarian language pack)
2. Click to sandwich menu (right up corner)
3. Select Navigáció (Navigation)
4. In submenu: "Következő kép megtekintése   Arrow right / PageUp" (Next image)

### System info:
- ImageGlass version: 4.0.4.15
- OS version: Windows 10 Pro 64bit

**Comment by d2phap** [comment]
Hi @hNczy 
Thanks, I will consider to add this in the next version.
Marked this as suggestion

Phap

**Comment by fire-eggs** [comment]
This has been in place and shipping for some time now.

**Comment by hNczy** [comment]
:bowing_man:
