### ISSUE TITLE
NEW FEATURE

### ISSUE THREAD

**Issue by veizei-K** [d2phap/ImageGlass#1940]
### System information
- Windows OS version: 11 23h2
- ImageGlass version: 9.1.6.14 (64-bit)
- ImageGlass release: Store / Classic? classic

### Describe the feature
在窗口化的时候，当我按住ctrl键的时候，鼠标左键按住可以拖动窗口。这样就不必点击窗口的标题栏才能移动窗口了。或者可以绑定其他的键
In windowed mode, holding down the Ctrl key allows  to move the window by clicking and dragging with the left mouse button. This way, i don't have to click the title bar to move the window.or can binding another key。

**Comment by d2phap** [comment]
You can hold SHIFT and drag

**Comment by veizei-K** [comment]
> You can hold SHIFT and drag

But I still want to be able to bind my favorite keys
