### ISSUE TITLE
Slow startup (100% CPU for 15 seconds to 1 minute) when InkScape is installed.

### ISSUE THREAD

**Issue by SeanCline** [d2phap/ImageGlass#1944]
### System information
- Windows OS version: Windows 10 Pro N 22H2 19045.4529
- ImageGlass version: 9.1.6.14
- ImageGlass release: Classic

### To Reproduce
1. Install InkScape.
2. Install ImageGlass.
3. Launch ImageGlass.
4. Observe slow startup with 100% CPU as several instances of inkscape are launched.

### Actual behavior
It seems that ImageGlass stores its toolbar icons in SVG format and converts them to a more suitable format for display each time the program is launched. Each icon gets a separate instance of inkscape.exe to perform the conversion, resulting in 53 instances of `inkscape.exe`, consuming every CPU core for several seconds. This results in a startup time of ~15 seconds on my desktop PC and 1 minute on my laptop (while the fans run full blast).

Ideas for improvement:
 - Perhaps the toolbar icons (and any other themed images) that are stored as an SVG can be rendered using the same method as when InkScape isn't installed. (i.e. Maybe ImageMagick can be to instructed not to use InkScape specifically for the toolbar icons, while still using InkScape for image the user is trying to view.
 - The rendered SVGs could be cached.
 - InkScape.exe could be profiled and optimized, though launching 53 instances of inkscape.exe still seems like a bad idea regardless of how optimized it is.

### Expected behavior
I expected ImageGlass to have similar startup performance with or without InkScape installed.

### Screenshots / Video / Sample image file
https://github.com/d2phap/ImageGlass/assets/3418587/332aaaad-c2e0-427d-8499-b6284972bea6

**Comment by d2phap** [comment]
Probably duplicated of https://github.com/d2phap/ImageGlass/issues/1935#issuecomment-2165762855. The problem happens when adding Inkscape to system PATH

**Comment by d2phap** [comment]
This issue is fixed in [ImageGlass 9.1.7.627](https://github.com/d2phap/ImageGlass/releases/tag/9.1.7.627)
