### ISSUE TITLE
Mouse side buttons take a while to scroll through photos

### ISSUE THREAD

**Issue by JustineLeonen** [d2phap/ImageGlass#1948]
### System information
- Windows OS version: Windows 10 Pro Version 22H2
- ImageGlass version: 9.1.6.14 (64-bit)
- ImageGlass release: Store & Classic (tried both)

### To Reproduce
1. Have a mouse that features side buttons
2. Open an image that has other images in it's folder
3. Scroll through next/previous photos with mouse side buttons

### Actual behavior
It would take a while (about half a second) for me to scroll through the next image. Clicking the side button multiple times causes it to stall, before it scrolls through the next image.

### Expected behavior
The next/previous image should show in an instant, or as I let go of the side button. This was not a problem in ImageGlass 8.

**Comment by d2phap** [comment]
Duplicated of #1827
