### ISSUE TITLE
Open super long screenshots to show blurring

### ISSUE THREAD

**Issue by uzcool** [d2phap/ImageGlass#1949]
### System information
- Windows OS version: window10
- ImageGlass version: 9.0.10.201
- ImageGlass release: Classic

### To Reproduce
1. Use Long Screenshot to capture a screenshot that is over 10,000+ pixels long
2. Open screenshot
3. For long screenshot software I use faststone capture
4.Pixel blurring when opening enlarged images with imageglass
![2024-06-22_12-00-44](https://github.com/d2phap/ImageGlass/assets/38136975/54ccdcce-02ab-4854-b98d-96d43df98460)
5.Using other software or Microsoft image viewing software is just clear with no pixel blurring

### Screenshots / Video / Sample image file
![2024-06-22_115227](https://github.com/d2phap/ImageGlass/assets/38136975/bb5300ca-87b8-45a0-981d-562df5c6626d)

**Comment by d2phap** [comment]
ImageGlass does not support viewing full size of image larger than 16384px. It will be scaled down to fit within these dimensions.

See the limitations: https://imageglass.org/docs/features#limitations

**Comment by 1208041822** [comment]
why not support ？This function is necessary
