### ISSUE TITLE
Extention case not ignored on image edition (.jpg != .JPG)

### ISSUE THREAD

**Issue by nodj** [d2phap/ImageGlass#195]
First, thank you for this soft. It's great, and I won't look back to the default viewer for win10.
I just find the setting for an external editor a little clunky. I'd love to edit a default settings, so that I don't have to edit all extentions one by one.
But the following is a real bug I think

### Expected behavior:
Ctrl+E on a **.JPG** image should bahave exactly as Ctrl+E on a **.jpg** file

### Actual behavior:
opens my .jpg with my custom software (defined in settings), but the JPG are opened with paint (default I guess)

### Steps to reproduce:
1. copy a file, change the extension case (one in jpg, the other one in JPG)
2. set a non-defaut editor for the extention 'jpg'
3. try Ctrl+E on both, only the jpg is open in the non-defqult editor

### System info:
- ImageGlass version: 4.0.4.15
- OS version: win 10

### Other info:
comparing the lowercase is often a good idea :)

**Comment by d2phap** [comment]
Thanks @nodj 

Just to confirm the bug of case-sensitive extensions. 
And also, I will improve the bulk assignment of edit function.

Currently, you can modify the config string in Registry:
HKEY_CURRENT_USER\Software\PhapSoftware\ImageGlass\ImageEditingAssociationList
The structure of this config is:

`[<extension>|<app name>|<app path>|<params>]`

Thanks

**Comment by d2phap** [comment]
Fixed this bug and added support for editing all extensions
