### ISSUE TITLE
100% zoom button

### ISSUE THREAD

**Issue by simon-spier0** [d2phap/ImageGlass#1950]
### Describe the feature
When I view images of various resolutions and zoom using scrolling, it often doesn't zoom exactly to 100%. The issue is that zoom levels of 99% or 101% make the image slightly blurry, and only at 100% zoom is the image perfectly sharp, as it should be.

Currently, to zoom to 100%, I have to:
Hamburger menu on the right → Zoom → Custom zoom... → 100 → OK

Many image viewers have a button to set the zoom exactly to 100%. Could you please add this feature too? Please see the attached image for my design suggestion.

### Additional context
![zoom_100%](https://github.com/d2phap/ImageGlass/assets/60992048/b9bd3235-b06f-4515-a229-115372fcae00)

**Comment by d2phap** [comment]
You can add more button in the Settings > Toolbar

![image](https://github.com/d2phap/ImageGlass/assets/3154213/96f02a14-3e78-4cc0-b637-601ebfc617ba)
