### ISSUE TITLE
Problems with Frameless dragging 

### ISSUE THREAD

**Issue by ldy779** [d2phap/ImageGlass#1951]
### System information
- Windows OS version: win10

When the image is enlarged beyond the window size, I hold down shift, and the mouse clicks anywhere on the image, I can drag the entire window, which is no problem, but when I release shift and mouse, thenI move the mouse, the image will move up and down with the mouse, and I need to click the mouse again to return to normal

**Comment by d2phap** [comment]
This issue is fixed in [ImageGlass 9.1.7.627](https://github.com/d2phap/ImageGlass/releases/tag/9.1.7.627):

> Updated the dragging window behaviour in Frameless mode: when holding Shift key, a Dragging Section appears to let user to move the frameless window

![image](https://github.com/d2phap/ImageGlass/assets/3154213/beccec5a-9663-461e-96ec-8224949022ec)
