### ISSUE TITLE
Typo in File Association Software\Classes

### ISSUE THREAD

**Issue by zimbo86** [d2phap/ImageGlass#1955]
### System information
- Windows OS version: Server 2019
- ImageGlass version: 9.1.6.14
- ImageGlass release: Classic

### To Reproduce
1. Install
2. Run 

`Start-Process "C:\Program Files\ImageGlass\igcmd.exe" -argumentlist "set-default-viewer ""*.png;*.jpg;*.gif;*.jpeg;*.bmp"" --per-machine" -wait`

### Actual behavior
HKLM\Software\Classes\ImageGlass.AssocFile..PNG is created (see the TWO dots)

### Expected behavior
HKLM\Software\Classes\ImageGlass.AssocFile.PNG is created (see the ONE dot)
Was fine in 9.0.10.201

### Screenshots / Video / Sample image file
![image](https://github.com/d2phap/ImageGlass/assets/69269000/1cceb995-f296-4779-b102-034318af6692)

**Comment by d2phap** [comment]
You should not include * in the extension string, just like this:

`igcmd.exe set-default-viewer .png;.jpg;.webp`


See https://imageglass.org/docs/command-line-utilities

**Comment by zimbo86** [comment]
can confirm, that this works. 
However there must be a change in the recent version, *.png worked without an issue in the past.
