### ISSUE TITLE
Hitting Esc will turn off ExifGlass extension and Alt + Enter for Properties / Shortcuts rebinding

### ISSUE THREAD

**Issue by Candelus** [d2phap/ImageGlass#1957]
### System information
- Windows OS version: 11
- ImageGlass version: 9.1.7.627
- ImageGlass release: Classic

### Describe the feature
I can open the ExifGlass extension with X key, but being able to hit Esc to turn it off would be great instead alt + F4 everytime. Makes the images metadata browsing much smoother.
Ctrl + I for image properties is a bit weird as it feels more like a macOS shortcut (Command + I), Windows commonly use Alt + Enter for Properties so either switch it to Alt + Enter or give us the ability to rebind shortcuts to our preferences would be great!

### How to use feature
As stated in Describe the feature.

### Additional context
Shouldn't need to as it's quite clear already.

**Comment by d2phap** [comment]
I will add ESC to close in the next version of [ExifGlass](https://github.com/d2phap/ExifGlass).
You can focus on ImageGlass window, and press X to close it as well.

**Comment by Candelus** [comment]
Thanks! I tried and it works but refocusing is such a hassle and add more steps for when I need to check the exif of multiple images at once. Being able to just hit esc and fly through the set of images is much faster than alt tab X for me!

Also what are your thoughts on the ctrl I / alt enter shortcut for properties?

**Comment by d2phap** [comment]
@Candelus 
[ExifGlass to v1.6](https://github.com/d2phap/ExifGlass/releases/tag/1.6.0.0) is released tp support pressing ESC to close the app window.

About the binding Alt+Enter for Properties, please refer to https://github.com/d2phap/ImageGlass/discussions/1702#discussioncomment-7660806, the name of the menu is `MnuImageProperties`.
