### ISSUE TITLE
Do not display BMP images

### ISSUE THREAD

**Issue by Charltsing** [d2phap/ImageGlass#1959]
[2091-1.zip](https://github.com/user-attachments/files/16094712/2091-1.zip)

![捕获](https://github.com/d2phap/ImageGlass/assets/19963715/7c547dc4-2127-4cca-8cb4-2234bee2e41b)

it will display with HasAlpha = false;
https://github.com/dlemstra/Magick.NET/issues/1667

This problem has appeared since Magick.Net version 13.9.0

**Comment by d2phap** [comment]
Fixed in [ImageGlass 9.1.8.723](https://github.com/d2phap/ImageGlass/releases/tag/9.1.8.723)
