### ISSUE TITLE
Add support for preview panel in Windows Explorer

### ISSUE THREAD

**Issue by d2phap** [d2phap/ImageGlass#196]
From Glenn H. Eriksen:

Hi,
I just wondered if there are any possibilities to support previews in Windows Explorer for the picture formats your application supports? Doesn’t seems like it. And, yes, I know you have your own preview in the app if the drag a folder into your application. But, I want it directly in Windows Explorer Preview pane… Would be a fantastic feature.
 
Best regards
Glenn H. Eriksen

**Comment by fire-eggs** [comment]
A useful library / sample :  [Preview Handler using **SharpShell**](https://www.codeproject.com/Articles/533948/NET-Shell-Extensions-Shell-Preview-Handlers)

**Comment by d2phap** [comment]
Suggest users to use https://sourceforge.net/projects/sagethumbs/ instead.

**Comment by Upgrade220** [comment]
Can anyone tell where and how is it solved? I still have that issue on 9.5 version...
Maybe there's some setting i didn't find?

**Comment by d2phap** [comment]
No, ImageGlass will not provide shell extension for thumbnail preview in File Explorer.
You can use sagethumbs:

> Suggest users to use https://sourceforge.net/projects/sagethumbs/ instead.
