### ISSUE TITLE
You can't say ImageGlass is lightweight given its slow start and installer size

### ISSUE THREAD

**Issue by gqqnbig** [d2phap/ImageGlass#1960]
From the viewpoint of size, its current installer size is 29MB. IrfanView is only 4.2MB.

From the viewpoint of speed, it starting is slow. Users have to deploy multiple hacks to speed it up (add exception to Windows Defender, keep ImageGlass in the background, etc.)

I tried version 8.12. Without these speeding hacks, **it is slower than MS Paint**.

I completely understand there are insufficient human resources to develop ImageGlass (https://github.com/d2phap/ImageGlass/issues/794#issuecomment-1752286529). I even could consider looking at the code of ImageGlass if I'm on a sabbatical.

In my opinion, to fix the conflict, the easiest solution is to change your advertisement, just remove the adjective "lightweight".

https://github.com/d2phap/ImageGlass/blob/773c6eb14640457b63b034bbff2a7a914586d6f4/README.md?plain=1#L1

**Comment by d2phap** [comment]
Nope, It’s my own software, I can say it whatever I want. It’s my rights about the freedom. 


> IrfanView is only 4.2MB.

Apparently you don’t understand programming & framework


> I tried version 8.12

ImageGlass 8 is discontinued long time ago


> Users have to deploy multiple hacks to speed it up (add exception to Windows Defender, keep ImageGlass in the background, etc.)

Never heard of this. ImageGlass 9 doesn’t support running in the background!


Instead, you could:
- Follow the issue template 
- Choose correct issue category
- Write constructive comment

ImageGlass is not built to satisfy everybody, and I don’t try to satisfy everybody either. Use whatever make you happy.
