### ISSUE TITLE
ImageGlass_9.1.7.627_x64.msi considered as infected

### ISSUE THREAD

**Issue by mrwiora** [d2phap/ImageGlass#1961]
Several Scanners classify the officially available MSI Package as infected.
https://www.virustotal.com/gui/file/c7f79c983c7e4fe79ad77386cca1aace8682703a7caddebfbf09fe0ff0034ec5

![image](https://github.com/d2phap/ImageGlass/assets/2744285/c3dcc842-fc9c-4901-b9a6-3538131ed73a)

The x64 portable variant has another one

![image](https://github.com/d2phap/ImageGlass/assets/2744285/fc062587-f4e6-4c98-8974-3e8c868a9517)

while the arm64 package seems to be fine - however I have no experiences with arm64 scannings.

**Comment by d2phap** [comment]
This may be just false positive detection.

In Version 9.1, I enabled the embedded WinUI rendering from Advanced Installer for better high DPI scaling for MSI installer, this may be the cause. For other builds, I have no idea.



https://github.com/d2phap/ImageGlass/blob/773c6eb14640457b63b034bbff2a7a914586d6f4/Setup/AdvancedInstaller/ImageGlass_9_x64.aip#L16-L17


![image](https://github.com/d2phap/ImageGlass/assets/3154213/339c4ae3-7d64-4f46-9d6c-c7a264d27831)


![image](https://github.com/d2phap/ImageGlass/assets/3154213/3b8fb6c8-c65e-4d04-a720-9ebc4463b139)
