### ISSUE TITLE
Failing to open .dds files @ error/dds.c/ReadDDSImage/2899

### ISSUE THREAD

**Issue by Speedy2662** [d2phap/ImageGlass#1962]
### System information
- Windows OS version: Windows 10 Pro 22H2
- ImageGlass version: 9.1.6.14
- ImageGlass release: Classic

### To Reproduce
1. Try to open .dds file
2. Fail

### Actual behavior
![image](https://github.com/d2phap/ImageGlass/assets/8947452/11df5a90-9902-4c9e-95ac-7b8854e6df84)

### Expected behavior
Expected the file to open

### Screenshots / Video / Sample image file

[yellow.zip](https://github.com/user-attachments/files/16117139/yellow.zip)

**Comment by d2phap** [comment]
@Speedy2662 thanks for provising the sample file. It seems upstream issue; can you help to report this to https://github.com/dlemstra/Magick.NET/issues (with the sample file)?
