### ISSUE TITLE
[Bug] Image Overlap Issues in Rapid Image Switching

### ISSUE THREAD

**Issue by AmTu-Suppachai** [d2phap/ImageGlass#1965]
### System information
- Windows OS version: windows 11
- ImageGlass version : Classic?

### To Reproduce
1. Open a webp file.
2. Quickly and repeatedly switch between images.
3. Images will begin to overlap.
4. Must switch back and forth between images multiple times to resolve the issue.

![image](https://github.com/user-attachments/assets/a6e95d06-9412-4d23-8cd8-c2f756af2051)

**Comment by d2phap** [comment]
Duplicated of #1942
