### ISSUE TITLE
Add description for image interpolation setting

### ISSUE THREAD

**Issue by stevencaiOR** [d2phap/ImageGlass#1973]
### System information
- Windows OS version: Windows 10 Home (64-bit)
- ImageGlass version: 9.1.8.723 (64-bit)
- ImageGlass release: Classic

### Describe the feature
In Settings > Layout > Viewer, have a description for each image interpolation setting under Zooming > Image interpolation.

### How to use feature

1. Go to Settings > Layout > Viewer to view description

### Additional context
Potential location shown in red outline: ![image](https://github.com/user-attachments/assets/f71c6476-c80a-40a0-8849-f6dd9d55f70f)

**Comment by d2phap** [comment]
Hi @stevencaiOR,

The interpolation in ImageGlass is as same as Direct2D, you can find more information here:
https://learn.microsoft.com/en-us/windows/win32/api/d2d1_1/ne-d2d1_1-d2d1_interpolation_mode#constants

Adding description to the Settings requires extra translation effort and more technical knowledge about graphic processing, which may lead to incorrect translation. Instead, users can just google the interpolation option and find more information if they want.
