### ISSUE TITLE
can you add a "free rotation" button on the toolbar to rotate the picture at any angle

### ISSUE THREAD

**Issue by jxxfwgq** [d2phap/ImageGlass#1975]
### System information
- Windows OS version: Windows11
- ImageGlass version:9.1.8.723
- ImageGlass release: Store / Classic?github.com

### Describe the feature

can you add a "free rotation" button on the toolbar to rotate the picture at any angle? Because when scanning with a scanner or taking photos with a mobile phone, it often deviates by one or two degrees and often needs to be rotated by several degrees.

### How to use feature

1.After clicking the "Free Rotation" button, the picture is selected, and a free rotation icon appears next to it,
2.so the mouse can rotate the picture freely.
3.After the rotation is complete, press Enter key, or click outside the selection box with the mouse to exit the rotation and confirm the rotation effect.

### Additional context

Thank you very much for developing ImageGlass! This is the best substitute for Windows photo viewer.
add a "free rotation" button,Because when scanning with a scanner or taking photos with a mobile phone, it often deviates by one or two degrees and often needs to be rotated by several degrees.
Often, I don't want to use photoshop, because there are many operation steps: open the picture, unlock it, edit it, transform it, rotate it, press Enter or click the "Submit" box to confirm.
It would be nice if you could rotate the picture freely quickly and conveniently in ImageGlass.

**Comment by d2phap** [comment]
Thanks @jxxfwgq but it's already posted here: #1356

**Comment by jxxfwgq** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
