### ISSUE TITLE
Add option to eliminate harassment to check Microsoft Store for updates

### ISSUE THREAD

**Issue by W4JEW** [d2phap/ImageGlass#1976]
Anytime I open ImageGlass after a new version becomes available, a pop-up message tells me to go to the Microsoft Store to get the update. I downloaded ImageGlass Classic, not the Microsoft Store version.

I can understand your desire to monetize your application. However, a one-time message encouraging someone to purchase the application should be sufficient. It should by no means pop up every time ImageGlass runs.

Otherwise, Classic users should see a message that there's a new version available. Then, it's up to us to decide whether or not we want to download/install it manually.

If you want more people to purchase the application, maybe you should eliminate the Classic option altogether.

**Comment by d2phap** [comment]
@W4JEW You should have spent your time to find the option in Settings instead of posting your harassment ticket here

**Comment by PC-SPEZIALIST** [comment]
Thanks for this awesome tool. 😍

We are deploying it using N-able N-SIGHT RMM for our clients and wondering if there is a parameter that we can use after _/qn_ to disable the information about the Microsoft Store. Is that already available or planned?

**Comment by d2phap** [comment]
@PC-SPEZIALIST There is no option to hide the MS Store badge. If you meant to disable the "Check for Update" for your clients, you can create `igconfig.default.json` or `igconfig.admin.json` file and set `AutoUpdate` value to `"0"`.

```json
{
  "_Metadata": {
    "Description": "ImageGlass configuration file",
    "Version": 9.1
  },
  "AutoUpdate": "0"
}
```

Refer to https://github.com/d2phap/ImageGlass/discussions/2067#discussioncomment-11723389 for the other use cases of using the configuration file

**Comment by PC-SPEZIALIST** [comment]
> @PC-SPEZIALIST There is no option to hide the MS Store badge. If you meant to disable the "Check for Update" for your clients, you can create `igconfig.default.json` or `igconfig.admin.json` file and set `AutoUpdate` value to `"0"`.
> 
> ```json
> {
>   "_Metadata": {
>     "Description": "ImageGlass configuration file",
>     "Version": 9.1
>   },
>   "AutoUpdate": "0"
> }
> ```
> 
> Refer to [#2067 (comment)](https://github.com/d2phap/ImageGlass/discussions/2067#discussioncomment-11723389) for the other use cases of using the configuration file

I was thinking about an option to disable the Microsoft Store badge.
Thanks for the helpful link. That makes it clear what is possible and what not. 👍
