### ISSUE TITLE
ImageGlass as default image viewer in Windows 10

### ISSUE THREAD

**Issue by AkitakeKun** [d2phap/ImageGlass#198]
Hi. I have a suggestion.

I have noticed that ImageGlass doesn't get recognized as an image viewer by Windows 10.
You cannot simply change the default image viewer to ImageGlass in the Windows 10 Settings "app by default" dropdown menu, it's simply not there, and I think it should be.

It would make it much easier to make the switch from the default Photos app, rather than having to look through the HUGE list of extensions and switch them one by one.

**Comment by d2phap** [comment]
Hi @AkitakeKun 

With ImageGlass 4, you can go to _Settings_ > _File Associations_, click on _Register extensions_ button
