### ISSUE TITLE
Hotkey editing in the settings or at least revert the proper "Ctrl+C" function.

### ISSUE THREAD

**Issue by Chimvokin** [d2phap/ImageGlass#1981]
- ImageGlass version: 9.1.8.723

### Describe the feature
Whoever came up with the idea to change simple file copy to "ctrl+shift+c" has made it a terrible experience for all the others considering people STILL can't easily edit any hotkeys in this software anywhere in the settings. 

**_Please, revert this change and don't make hotkeys for unconventioal actions overwrite the established standardised ones._** Or at least give the **_easy_** option to change it at any time in the settings (i.e. within the UI of the software and not by external configuration/code editing).

### How to use feature
- Ctrl+C should be "copy file" and not anything else;
- The option to edit all the hotkeys in the settings.

**Comment by d2phap** [comment]
@Chimvokin #1702

**Comment by Chimvokin** [comment]
> @Chimvokin #1702

Once again - NO. Missing the point.
