### ISSUE TITLE
ImageGlass can't open JPEG XL image

### ISSUE THREAD

**Issue by ghost** [d2phap/ImageGlass#1983]
### System information
- Windows OS version: Windows 10, version 21H2
- ImageGlass version: 9.1.8.723
- ImageGlass release: Classic

### To Reproduce
1. Download and open the [image](https://gofile.io/d/N01bX2)

### Screenshots / Video / Sample image file
![Screenshot 2024-08-11 003813](https://github.com/user-attachments/assets/e6032708-6a97-49c0-b969-84eb419b358a)

https://gofile.io/d/N01bX2

**Comment by d2phap** [comment]
Thanks @skibiditoilet356, it's upstream issue. Can you report this to https://github.com/dlemstra/Magick.NET?
