### ISSUE TITLE
Setting ImageGlass as default photo viewer error

### ISSUE THREAD

**Issue by tester5454** [d2phap/ImageGlass#1984]
- Windows OS version: Tiny11 23H2 Build 22631.3958
- ImageGlass release:Classic

### To Reproduce
1. On the quick setup pressing make ImageGlass as the default photo viewer
### Expected behavior
Open the default apps settings or put it default automatically
![Screenshot 2024-08-11 223139](https://github.com/user-attachments/assets/09eb627e-de97-4edd-bbee-152dd123a291)
And the whole log is:
Version: igcmd v9.1.8.723
Release code: kobe
Magick.NET: Magick.NET Q16-HDRI-OpenMP x64 netstandard21 13.10.0
WebView2 Runtime: 100.0.1185.36
OS: Microsoft Windows NT 10.0.22631.0 64-bit

----------------------------------------------------
Error:

Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Web.WebView2.Core.Raw.ICoreWebView2WebMessageReceivedEventArgs2'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{06FC7AB7-C90C-4297-9389-33CA01CF6D5E}' failed due to the following error: No such interface supported (0x80004002 (E_NOINTERFACE)).
----------------------------------------------------

System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Web.WebView2.Core.Raw.ICoreWebView2WebMessageReceivedEventArgs2'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{06FC7AB7-C90C-4297-9389-33CA01CF6D5E}' failed due to the following error: No such interface supported (0x80004002 (E_NOINTERFACE)).
   at Microsoft.Web.WebView2.Core.CoreWebView2WebMessageReceivedEventArgs.get__nativeICoreWebView2WebMessageReceivedEventArgs2()
Oh and nothing works
(Don't ask me why i was going fast github doesn't allow files larger than 10MB)

https://github.com/user-attachments/assets/bc30767c-c29d-4dbd-86b7-d9643e73b1e6

**Comment by tester5454** [comment]
so apparently tiny11 removes edge and also removes the webviewer so installing the webviewer fixed it

**Comment by tester5454** [comment]
Before you ask. Yes i have webviewer installed, i think so. but isn't there usually a task related to webviewer?
![Screenshot 2024-08-12 002903](https://github.com/user-attachments/assets/f9eaef64-a9fd-4938-a9ad-4893a98c3510)

![Screenshot 2024-08-12 002540](https://github.com/user-attachments/assets/2d00a875-b0c1-4a19-a752-6a01a6ac136d)

**Comment by d2phap** [comment]
Hi @tester5454 

Your WebView2 is outdated. Please update to version 119 or the latest version. See https://github.com/d2phap/ImageGlass/issues/1722#issuecomment-2282887526

![image](https://github.com/user-attachments/assets/e4931273-3a09-4a73-bc51-ffa57cacdd0e)
