### ISSUE TITLE
Open With Application

### ISSUE THREAD

**Issue by owenxm** [d2phap/ImageGlass#1987]
### System information
- Windows OS version: Windows 10
- ImageGlass version: 9.1.8.723 (64-bit)
- ImageGlass release: Classic

### Describe the feature

- An Open With Application button, a la Windows Photo Viewer.
- This allows you to open an image in, for example, an image editor.

### How to use feature

1. Add the button to your toolbar.
2. Click the button.
3. It will show a drop-down menu, like in the attached screenshot.

### Additional context

![firefox_ZCDvJZxz9Y](https://github.com/user-attachments/assets/9794c70b-e907-46d0-b6e1-5c2d27eaeed9)

  I am aware that there exists a button to edit images, however, it does not offer the versatility that a button like this does.

**Comment by d2phap** [comment]
You can add a custom toolbar button.
Open Settings > Toolbar > Toolbar buttons, click "Add a custom button" button and use this JSON:
```json
{
  "Id": "Btn_OpenWith",
  "Type": "Button",
  "Text": "Open with",
  "Image": "C:\\path\\to\\your\\icon.svg",
  "Alignment": "Left",
  "CheckableConfigBinding": "",
  "DisplayStyle": "Image",
  "OnClick": {
    "Executable": "MnuOpenWith",
    "Arguments": ""
  }
}
```
