### ISSUE TITLE
Unhandled exception when attempting to add extensions

### ISSUE THREAD

**Issue by assteepee** [d2phap/ImageGlass#199]
### Expected behavior:
Extensions should install properly?

### Actual behavior:
I get an unhandled exception error  when trying to install extensions

### Steps to reproduce:
1. Open extension manager
2. Install extension using extension button
3. navigate to extension, for example imagecomparator.dll and click Ok
4. Click refresh because nothing happens
5. Unhandled exception error appears

OR after step 3

4. Close extension manager
5. reopen extension manager
6. Unhandled exception error appears

OR

1. Directly put the .dll into the plugin folder
2. Open extension manager
3. Unhandled exception error appears

### System info:
- ImageGlass version: 4.0.4.15
- OS version: Windows 10

### Other info:
Removing the .dll from the folder manually allows the extension manager to be opened again without the error appearing. Also the themeconfig extension that is already preinstalled seems to work fine, and can remain the plugin folder regardless.

**Comment by d2phap** [comment]
Those extensions in ImageGlass website are not updated through new ImageGlass version.
However, ImageGlass will no longer support extensions due to securities of the current extension model (until I find a new better way)
