### ISSUE TITLE
"This action is only valid for products that are currently installed"

### ISSUE THREAD

**Issue by Aquind** [d2phap/ImageGlass#1992]
### System information
- Windows OS version: #Windows 10
- ImageGlass version: 9.1.8.723
- ImageGlass release: Classic

### To Reproduce
1. open jpg with file association set to "ImageGlass"
2. receive pop-up error stating "This action is only valid for products that are currently installed"
3. file does not open in viewer
4. 

### Expected behavior
When I double click or choose "open" on a jpg file it opens in ImageGlass with no error

### Screenshots / Video / Sample image file
![image](https://github.com/user-attachments/assets/da226d7e-0dd9-40e2-ae8a-6606d8ed5d79)

### Additional context
This issue has persisted through multiple versions through the past couple years at least.  In the past I have to uninstall, reboot, re-install and it fixes it temporarily.  This time it is stuck and unusable with the above error.

**Comment by d2phap** [comment]
I don't have a solution for this, probably Windows messed up the file type association for image formats. The way to fix is reinstall/repair ImageGlass via installer, or open ImageGlass Settings > File type associations, click "Make default" button.

Just close it for now

**Comment by Aquind** [comment]
Its perplexing to me.  I have uninstalled, rebooted multiple times across multiple versions.  I have changed the default file association 2-3 different ways, nothing seems to help.  

The major problem is that it makes image glass unusable since closing the window does not allow the application to open.

**Comment by dassels** [comment]
I'm having the same issue. Tried all the above, clean installs, re-linked associations, reboots, etc. And there is no way to get that error to go away. Unfortunately, I won't be able to use this either. Version 8 was working fine but it's EOL so that's not really an option either.
