### ISSUE TITLE
Every time I press the print button using ImageGlass I get an error

### ISSUE THREAD

**Issue by THEBOSSES7000** [d2phap/ImageGlass#1995]
### System information
- Windows OS version: Windows 11 Pro 23H2
- ImageGlass version: 9.1.8.723 (64 bits)
- ImageGlass Classic And Store

I have to clarify that I am technically using Tiny11, which is a version of Windows 11 without all the unnecessary applications that it comes with by default, I don't think that's it, but just in case I say it.

I tried to use the store version but it doesn't work for me either, below I leave the error that I have.

"Could not print display image"
![Captura de pantalla 2024-08-29 005330](https://github.com/user-attachments/assets/64a1e8ce-3467-4843-9757-d86edc0944b3)

**Comment by d2phap** [comment]
Please refer to https://github.com/d2phap/ImageGlass/issues/1876#issuecomment-2186928780
