### ISSUE TITLE
Remove alert sound on image deletion prompt

### ISSUE THREAD

**Issue by EternityEngine** [d2phap/ImageGlass#1997]
### System information
- Windows OS version: Windows 10
- ImageGlass version: 9.1.8.723
- ImageGlass release: Classic

### Describe the feature
- In ImageGlass, when the confirmation dialogue for deleting a file appears, an alert sound ("ding") is played.
- In Windows Explorer or Windows Photo Viewer, when the confirmation dialogue for deleting a file appears, there is no sound played.
- This sound is unnecessary, in my opinion, when simply moving a file to the recycle bin. Could it be removed?
- If having the sound follows some sort of UI guide I'm not aware of, could we please get an option to disable the sound?

### How to use feature (if setting)
1. Open Settings window.
2. Go to the Edit section.
3. As a sub-option under "Show confirmation dialog when deleting file", have a checkbox for "Play notification sound when dialog opens" (or similar wording).
4. Unchecking this option would prevent the alert sound from playing.

### Additional context
I don't know if the "overriding file" confirmation dialogue also plays this sound. If so, also have a matching option to turn that off.
It does make sense to have this sound play for permanently deleting an image (Shift+Delete).

**Comment by d2phap** [comment]
Implemented in [ImageGlass 9.2 Beta](https://github.com/d2phap/ImageGlass/releases/tag/9.1.8.1104), no sound is played when popup opens
