### ISSUE TITLE
List of suggestion

### ISSUE THREAD

**Issue by softyoda** [d2phap/ImageGlass#200]
-Add a eyedropper tool  when ALT key + mouse click is pressed in the picture. Show current color and automaticly add hexa code of the color to clipboard when click relaised.

-Use material acceleration to open faster than the windows 10 app "photo"

-Add little openable menu at right to show extif data and useful information like in properties of the image.

**Comment by softyoda** [comment]
Add smooth zoom like smooth wheel scroll or firefox scroll. To not have this sort of stairs effect when zooming.

**Comment by softyoda** [comment]
Use CTRL+Wheel to go to the next picture (like it is in option but inverted)

**Comment by TDNKosugi** [comment]
-Centered thumbnail panel (current image in middle) that can be scrolled with the scrollwheel
-Revomable/Movable toolbar buttons 
-Transparent/Translucent background color

This has come damn close to being my ideal image viewer. Thank you.

**Comment by Diddlik** [comment]
-Add little openable menu at right to show extif data and useful information like in properties of the image.

This would be very nice and useful!

**Comment by d2phap** [comment]
Thanks for those suggestions.
Please post it separately so that it can be easily to manage.

**Comment by d2phap** [comment]
Implemented:
- `Revomable/Movable toolbar buttons`
- `Use CTRL+Scroll to go to the next picture (like it is in option but inverted)`

Check ImageGlass Moon for early build download

**Comment by d2phap** [comment]
Implemented Color picker

**Comment by fire-eggs** [comment]
Implemented:
- `Use CTRL+Scrool to go to the next picture (like it is in option but inverted)` : customized scrollwheel behavior in settings
- `Add smooth zoom like smooth wheel scroll or firefox scroll. To not have this sort of stairs effect when zooming.` : finer control of zooming added

Tracked elsewhere:
- `Centered thumbnail panel (current image in middle) that can be scrolled with the scrollwheel` : issue #131
- `Add little openable menu at right to show extif data and useful information like in properties of the image` : issue #336 
- `Transparent/Translucent background color` : issue #591 

Suggest closing this issue.
