### ISSUE TITLE
Handle ms-photos link

### ISSUE THREAD

**Issue by hellojaccc** [d2phap/ImageGlass#2002]
### System information
- Windows OS version: 11
- ImageGlass version:
- ImageGlass release: Classic

### Describe the feature

When trying to open a photo app from windows camera app, it says 'get an app from ms store to open this link'
<img width="365" alt="Screenshot 2024-09-07 123309" src="https://github.com/user-attachments/assets/1ad9380a-bef2-419a-8fb9-4c9e80e57af6">

### How to use feature

1. 
2. 
3. 

### Additional context

There is an another app on ms store that handles ms-photos: link.

**Comment by d2phap** [comment]
Added support for app protocol in [ImageGlass 9.2 Beta](https://github.com/d2phap/ImageGlass/releases/tag/9.1.8.1104) for Custom Toolbar button, Tool, Edit app,...
- In the "Executable" box, enter the app protocol, must end with `:`
- In the "Argument" box, enter the parameters of the app. Use `<file>` macro to pass current image path to the app.
- Check the "Command preview" box if your settings are correct


![image](https://github.com/user-attachments/assets/9c819eb4-f352-4866-898e-0841f1311420)
