### ISSUE TITLE
Windows number format minus sign causes error on startup

### ISSUE THREAD

**Issue by lblblb** [d2phap/ImageGlass#201]
I changed the number format in my system to use the proper minus sign − (Unicode U+2212) instead of the wrong hyphen, but this change causes ImageGlass to show 
an error on startup. The error prevents me from viewing images.

![2017-06-22 11_49_05-program manager](https://user-images.githubusercontent.com/12690798/27428372-1d2dae3e-5742-11e7-96eb-f5bf5ac3010c.png)

### Expected behavior:
ImageGlass starts and displays image.

### Actual behavior:
Error, image not displayed, just blank window

### Steps to reproduce:
1. Control Panel\Clock, Language, and Region --> Change date, time, or number formats --> Additional settings --> Numbers --> Negative sign symbol
![number format](https://user-images.githubusercontent.com/12690798/27428371-1d218f5a-5742-11e7-96de-dac34ec58571.png)

2. Change the hyphen - to the correct minus sign − (Unicode U+2212)
3. Save
4. Start ImageGlass or open an image with it.

### System info:
– ImageGlass version: 4.0.4.15
– OS version: Windows 10 x64 (1703)

### Other info:
Error log:

    See the end of this message for details on invoking 
    just-in-time (JIT) debugging instead of this dialog box.
    
    ************** Exception Text **************
    System.FormatException: Input string was not in a correct format.
       at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
       at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
       at ImageGlass.frmMain.LoadConfig()
       at ImageGlass.frmMain.frmMain_Load(Object sender, EventArgs e)
       at System.Windows.Forms.Form.OnLoad(EventArgs e)
       at System.Windows.Forms.Form.OnCreateControl()
       at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
       at System.Windows.Forms.Control.CreateControl()
       at System.Windows.Forms.Control.WmShowWindow(Message& m)
       at System.Windows.Forms.Control.WndProc(Message& m)
       at System.Windows.Forms.Form.WmShowWindow(Message& m)
       at ImageGlass.frmMain.WndProc(Message& m)
       at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
    
    
    ************** Loaded Assemblies **************
    mscorlib
        Assembly Version: 4.0.0.0
        Win32 Version: 4.7.2098.0 built by: NET47REL1LAST
        CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
    ----------------------------------------
    ImageGlass
        Assembly Version: 4.0.4.15
        Win32 Version: 4.0.4.15
        CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.exe
    ----------------------------------------
    System.Windows.Forms
        Assembly Version: 4.0.0.0
        Win32 Version: 4.7.2094.0 built by: NET47REL1LAST
        CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
    ----------------------------------------
    System
        Assembly Version: 4.0.0.0
        Win32 Version: 4.7.2093.0 built by: NET47REL1LAST
        CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
    ----------------------------------------
    System.Drawing
        Assembly Version: 4.0.0.0
        Win32 Version: 4.7.2046.0 built by: NET47REL1
        CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
    ----------------------------------------
    ImageGlass.Services
        Assembly Version: 4.0.6319.22627
        Win32 Version: 4.0.6319.22627
        CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.Services.DLL
    ----------------------------------------
    System.Core
        Assembly Version: 4.0.0.0
        Win32 Version: 4.7.2098.0 built by: NET47REL1LAST
        CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
    ----------------------------------------
    ImageGlass.Core
        Assembly Version: 4.0.6319.22627
        Win32 Version: 4.0.6319.22627
        CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.Core.DLL
    ----------------------------------------
    ImageGlass.Library
        Assembly Version: 4.0.6319.22627
        Win32 Version: 4.0.6319.22627
        CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.Library.DLL
    ----------------------------------------
    System.Xml
        Assembly Version: 4.0.0.0
        Win32 Version: 4.7.2046.0 built by: NET47REL1
        CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
    ----------------------------------------
    ImageGlass.Theme
        Assembly Version: 4.0.6319.22628
        Win32 Version: 4.0.6319.22628
        CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.Theme.DLL
    ----------------------------------------
    System.Configuration
        Assembly Version: 4.0.0.0
        Win32 Version: 4.7.2046.0 built by: NET47REL1
        CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
    ----------------------------------------
    ImageGlass.ImageBox
        Assembly Version: 4.0.0.0
        Win32 Version: 4.0.0.0
        CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.ImageBox.DLL
    ----------------------------------------
    ImageGlass.ImageListView
        Assembly Version: 11.0.0.3
        Win32 Version: 11.0.0.3
        CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.ImageListView.DLL
    ----------------------------------------
    Magick.NET-Q16-AnyCPU
        Assembly Version: 7.0.0.0
        Win32 Version: 7.0.4.701
        CodeBase: file:///C:/Program%20Files/ImageGlass/Magick.NET-Q16-AnyCPU.DLL
    ----------------------------------------
    
    ************** JIT Debugging **************
    To enable just-in-time (JIT) debugging, the .config file for this
    application or computer (machine.config) must have the
    jitDebugging value set in the system.windows.forms section.
    The application must also be compiled with debugging
    enabled.
    
    For example:
    
    <configuration>
        <system.windows.forms jitDebugging="true" />
    </configuration>
    
    When JIT debugging is enabled, any unhandled exception
    will be sent to the JIT debugger registered on the computer
    rather than be handled by this dialog box.

**Comment by d2phap** [comment]
Fixed the issue in ``develop`` branch
