### ISSUE TITLE
Prevent auto update check

### ISSUE THREAD

**Issue by d2phap** [d2phap/ImageGlass#202]
From njwinter@...

Hello,
Can you please let me know how to deploy the program so that update check is disabled.  I can see an `AutoUpdate` registry key with a date in it - have tried 0 but the checkbox in settings is still checked.
This program is ideal for use with Win 10 LTSB - thank you.
Neil

**Comment by kocane** [comment]
@d2phap how can I disable the update check thru registry or config file? I've been unable to

**Comment by fire-eggs** [comment]
IG no longer uses the registry for settings.

The following line in the igconfig.xml file will turn off the update check:
`<Item key="AutoUpdate" value="0" />`

It might be a little tricky to find your igconfig.xml, depending on how you installed IG. You should look at [this](https://imageglass.org/docs/app-configs) to hunt down where your igconfig file(s) might be.

FYI, there is a[ Google+ group ](https://groups.google.com/g/imageglass)for discussion and questions about ImageGlass.

**Comment by kocane** [comment]
@fire-eggs right on, thanks!

**Comment by miharix** [comment]
Hi,

I would suggest a little change in config behavior et least for AutoUpdate parameter

 If Registry exist -> ignore setting in igconfig.xml & disable check field in settings
On click save in setting -> no code change, ignore registry, don't write to registry.

So when deploying over scripts/GPO admin could easy lock some parameter

**Comment by d2phap** [comment]
@miharix 
You can create `igconfig.admin.xml` in Start up folder: https://imageglass.org/docs/app-configs

**Comment by QoliAlliance** [comment]
Just rename igcmd.exe to igcmd_.exe in the ImageGlass folder

**Comment by d2phap** [comment]
@QoliAlliance igcmd.exe is also in charge of other functions like Set desktop wallpaper
https://imageglass.org/docs/command-line-utilities
