### ISSUE TITLE
We can't copy paste image into folders?

### ISSUE THREAD

**Issue by FurkanGozukara** [d2phap/ImageGlass#2020]
ok here what i want this app is amazing

copy only 1 image into clip board with ctrl + C and paste into folder with ctrl + V - no need to keep multiple images in clipboard

maximum speed with caching , I have very powerful GPU and CPU and NVME so I want to navigate between images very fast

**Comment by d2phap** [comment]
To change the default hotkey, please refer to: https://github.com/d2phap/ImageGlass/discussions/1702#discussioncomment-7660806

You can disable the multi-file copy/cut feature in settings:

![image](https://github.com/user-attachments/assets/ad921c76-fcf6-4f30-b64c-7dae88ccd83f)

**Comment by FurkanGozukara** [comment]
@d2phap ty if you can answer this too : https://github.com/d2phap/ImageGlass/discussions/1702#discussioncomment-10867518
