### ISSUE TITLE
ImageGlass does not open HEIC files anymore

### ISSUE THREAD

**Issue by alexandis** [d2phap/ImageGlass#2025]
- Windows OS version: 10 Enterprise 22H2
- ImageGlass version: 8.6.7.13
- ImageGlass release: Classic?

There was no problem before. The [HEIC file itself](https://drive.google.com/file/d/1-2XXos4b3_HFFDPNUk6gVJos8kF1wtJ2/view?usp=sharing) is allright - it's opened successfully with Windows 10 extensions by Photos app.

![image](https://github.com/user-attachments/assets/ebb651d4-a693-442f-b8c3-e19252400be9)

**Comment by d2phap** [comment]
Your ImageGlass version is outdated. You can try updating to the latest version. If it does not work, report the issue to https://github.com/dlemstra/Magick.NET fork with your sample file.
