### ISSUE TITLE
Bring back these features from ImageGlass 8 + Request for new features

### ISSUE THREAD

**Issue by KonoVitoDa** [d2phap/ImageGlass#2027]
### System information
- Windows OS version: Windows 11 Home 23H2 22631.4317 (64-bit)
- ImageGlass version: 9.1.8.723 (64-bit)
- ImageGlass release: Classic

**BRING BACK FROM V8:**
- Option to disable pressing ```ESC``` to Exit
- Press ```SPACE```/```BACKSPACE``` to navigate between files
- When zoomed in, ```UP```/```DOWN``` arrows pan/reposition image (it would be great being able to use ```RIGHT```/```LEFT``` as well)
- Crop tool:
  - Keep selected image area regardless of the zoom level, allowing users to zoom in as much as they want to make cropping with pixel-level precision
  - Make selection pixel-sensitive (snap to pixel)
- Set an Editing app for all file extensions at once

**NEW FEATURES:**
- Fully/partially customizable hotkeys
- Alternative Edit hotkey (e.g. ```Ctrl+e```), thus allowing users to open files in a secondary Editing app
- Crop tool:
  - Resize selection area by dragging from any edge, not just from the 8 anchor points
  - Keep selection when clicking outside of it, thus avoiding accidentally losing the selection
- Copy/Cut/Open File Location on files that exceed the path lenght limit

**Comment by d2phap** [comment]
- Crop tool, refer to https://github.com/d2phap/ImageGlass/issues/1795#issuecomment-2454934725
- Editing app: you can combine multiple extensions
  ![image](https://github.com/user-attachments/assets/f0777e9a-349f-4883-9864-aefc39d42c5d)
- Hotkey customization: refer to #1702 
- Long path in Windows: refer to https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry#enable-long-paths-in-windows-10-version-1607-and-later

**Comment by KonoVitoDa** [comment]
> * Editing app: you can combine multiple extensions

I still think the old approach was a little better, as you could set, for example, Photoshop as the Edit app for all extensions and just edit the ones you wanted to edit with a different app:
![image](https://github.com/user-attachments/assets/79460bbc-377b-4f01-9b6c-ef852f577f99)
Or we could at least change all extensions at once with ```<all extensions>```:
![image](https://github.com/user-attachments/assets/03e54d73-b613-484c-9bf6-866bd96ce499)
But it's okay if you can't implement this, it's not a big problem. It just feels weird to lose features that were present in an older release.

> * Alternative Edit hotkey (e.g. Ctrl+e), thus allowing users to open files in a secondary Editing app

And I also keep my suggestion for this feature, it'd would be good to open a file with a secondary app with just a hotkey, like ```Ctrl+e``` to open the image with mpv player (I constantly need to open GIFs with it).

> * Hotkey customization: refer to [Redefining default hotkeys #1702](https://github.com/d2phap/ImageGlass/discussions/1702)

Thank you, I didn't know about that! For anyone reading this in the future, I managed to do what I wanted with:
```
 "MnuViewNext": ["Right", "Space", "PageDown"],
	"MnuViewPrevious": ["Left", "Back", "PageUp"],
	"MnuPanUp": ["Up", "Alt+Up"],
	"MnuPanDown": ["Down", "Alt+Down"],
	"MnuExit": ["Esc", "F4", "Ctrl+w"],
	"MnuCopyFile": ["Ctrl+c"],
	"MnuCopyImageData": ["Ctrl+Shift+c"]
```

> * Long path in Windows: refer to https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry#enable-long-paths-in-windows-10-version-1607-and-later

This Registry option is already enabled here, but the issues still persists. But whatever, it's not a big deal, as it's pretty rare to come across with these files.

**EDIT:**
> * When zoomed in, `UP`/`DOWN` arrows pan/reposition image (it would be great being able to use `RIGHT`/`LEFT` as well)

I also reiterate that it would be great to be able to Pan with ```Left```/```Right``` when the image dimensions are bigger than screen's width due to Zoom.
