### ISSUE TITLE
Please Bring Back the User-Friendly Cropping Feature from Before Version 9.0

### ISSUE THREAD

**Issue by BobbyatGithub** [d2phap/ImageGlass#2028]
### System information
- Windows OS version: Win11
- ImageGlass version:8.12.4.30 
- ImageGlass release:  Classic?

### Describe the feature
Firstly, in versions 8.12.4.30 and earlier, when the crop function was activated and the image was zoomed in/out or scrolled, the crop preview box would synchronously zoom in/out or scroll. This was extremely beneficial for cropping large-sized images or long images, as it allowed me to zoom in to check the edges of the crop area.

However, in versions after 9.0, the crop preview box does not synchronize with the zooming in/out or scrolling; instead, it remains fixed, which is a very counterintuitive operation logic.

Secondly, the cropping animation in versions after 9.0 is smoother, and I hope it can be paired with the excellent croppingfeatures of the old version. Thank you.

**Comment by d2phap** [comment]
Fortunately, I decided to work on Crop feature today and just finished changing Crop feature as same as v8. This change will be included in v9.2.

**Comment by d2phap** [comment]
Implemented in [ImageGlass 9.2 Beta](https://github.com/d2phap/ImageGlass/releases/tag/9.1.8.1104), refer to https://github.com/d2phap/ImageGlass/issues/1795#issuecomment-2454934725 for more details
