### ISSUE TITLE
Wheel click

### ISSUE THREAD

**Issue by abcdefuku** [d2phap/ImageGlass#2036]
I know you already said that the option would be in the version 9 and it allegedly was in beta 9. But two years passed and i can't find how to bind wheel click for any action! Please add full screen view on wheel click.

**Comment by d2phap** [comment]
You can customize it in the `igconfig.json`

```json
...
"MouseClickActions": {
  "WheelClick": {
    "ToggleOn": {
      "Executable": "IG_ToggleFullScreen",
      "Arguments": []
    }
  },
  
  // other actions...
},
...
```

![image](https://github.com/user-attachments/assets/4363b61b-142f-4de1-9cd2-f2455347ceba)

**Comment by abcdefuku** [comment]
There's no this file in my app folder.
