### ISSUE TITLE
show mouse position and RGB or Gray Value

### ISSUE THREAD

**Issue by Sade686** [d2phap/ImageGlass#2038]
### System information
- Windows OS version: ALL
- ImageGlass version:ALL
- ImageGlass release: Store / Classic?Classic

### Describe the feature
Show Mouse Current Position image pixel coordinate and RGB or Gray Value with Mouse move

**Comment by d2phap** [comment]
You can use the Color Picker tool

**Comment by ylaperriere** [comment]
Agree with sade686
The color selector is perfect, but it's too complex for basic use, and takes up too much screen space.
an option to display the current mouse position and color in the status bar would be very useful (RBG)

I have just installed your software and it seems to be the perfect viewer for me (except the mouse  pos +color ;) )
