### ISSUE TITLE
Slideshow speed doesn't go below 1 second

### ISSUE THREAD

**Issue by Pamlau** [d2phap/ImageGlass#2047]
### System information
- Windows OS version: Windows 11 23H2
- ImageGlass version: 9.1.8.723 (64-bit)
- ImageGlass release: Classic

### To Reproduce
1. Open Settings
2. Open Slideshow Tab
3. Set Slideshow Interval to below 1 second

### Actual behavior

Slideshow speed is still 1 second even though it says the interval is set to below it

### Expected behavior

The Slideshow speed should be equal or at least close to set interval speed, its not a heavy/high quality slow loading case because its images of less than 500kb that load around 10ish images when spamming the next/previous image keys

### Screenshots / Video / Sample image file
![image](https://github.com/user-attachments/assets/e28c89ee-cda5-4493-8257-58ad4860a30d)

**Comment by Pamlau** [comment]
I need this to be fixed or added as feature because I've been loving this image viewer and being able to play my stock of images as a animation through slideshow like I used to with Nomacs would be a great addition

**Comment by d2phap** [comment]
Removed the second limit in [ImageGlass 9.2.0.1208 - Maroon 4](https://github.com/d2phap/ImageGlass/releases/tag/9.2.0.1208). The slideshow time may not be accurate for < 1 second
