### ISSUE TITLE
🙏 [Feature Request] Drawing over image

### ISSUE THREAD

**Issue by shafayetejaman** [d2phap/ImageGlass#2054]
### System information
- Windows OS version: 11 23h2
- ImageGlass version: 9.1.8.723  
- ImageGlass release: Classic

### Describe the feature

I would like a simple Image drawing feature like in the windows photo app. Sometimes I need to highlight or draw over an image, it would be very convenient to have this feature.

### How to use feature

1. There should be an edit btn in the toolbar.
2. clicking it would open an editing window with a pen, eraser, color, and pen thickness. 
3. draw over the image.
4. can save as a copy or update the original.

### Additional context

![{A0F3FA36-0DFC-4512-A3B3-B9C7DD6E67A7}](https://github.com/user-attachments/assets/e44c908b-02ef-4c50-ae69-9bc1e2dc71c9)

**Comment by d2phap** [comment]
Sorry I reject this request. ImageGlass mainly focuses on viewing features. You can open the image with Paint or other apps to edit
