### ISSUE TITLE
Delete button in toolbar

### ISSUE THREAD

**Issue by gaberad** [d2phap/ImageGlass#208]
Any possibility for a delete button in the toolbar (rather than having to right-click > move to recycle bin)? Windows photo viewer had a similar button in its toolbar which was quite useful at times.

**Comment by d2phap** [comment]
Hi @gaberad 
I think you can easily use `Del` key instead?

**Comment by gaberad** [comment]
Oh yeah, I'm aware of that. 

It's no biggie, just a QoL thing (especially when cycling through large series of images): in windows photo viewer I've always found it faster and easier to use the mouse forward/back buttons to cycle through images while hovering the mouse cursor over the delete button, and just clicking on the button when needed. It can all be done one handed, and you don't have to move the mouse around trying to get to the right context menu item.

**Comment by feidaman** [comment]
Having a button on the toolbar can be useful on touch devices like the Surface Pro.

**Comment by d2phap** [comment]
Thanks for the details.

**Comment by d2phap** [comment]
Implemented in `develop` branch.
