### ISSUE TITLE
Edit Image (Suggestion)

### ISSUE THREAD

**Issue by TheDevo** [d2phap/ImageGlass#209]
### Expected behavior:
I wish to find an option in the settings to choose the application I intend to edit the image with.
Using ImageGlass on Windows 10, I'd expect to see a "browse" button to either see a list of image editors or find the .exe I wish to execute through the action.

### Actual behavior:
The "Edit Image" function in the context menu opens the picture in MSPaint and there is no option to change that.

### Steps to reproduce:
1. Open any image in ImageGlass
2. Right click on the image and choose "Edit Image"
3. It opens it in MSPaint

### System info:
- ImageGlass version: 3.5.9.17
- OS version: Windows 10 Ent. 2016 LTSB

### Other info:
the.devolution@gmail.com

**Comment by d2phap** [comment]
Hi @TheDevo 

Since v4.0, you can change the editing application in `Settings` dialog, `Image` tab.

![image](https://user-images.githubusercontent.com/3154213/27995443-e909a8e8-6500-11e7-982e-e84566e0e45b.png)
