### ISSUE TITLE
Cannot use orientation exif tag

### ISSUE THREAD

**Issue by keedi** [d2phap/ImageGlass#21]
Some image format like JPEG has exif tag and there is a **[orientation](http://www.impulseadventure.com/photo/exif-orientation.html)** information which is used to reflect the positioning of the camera with respect to the ground. Current version of ImageGlass doesn't use this information to display the image.

**Comment by d2phap** [comment]
Hi Keedi,

Thank you for your report.

**Comment by d2phap** [comment]
Done :+1:
