### ISSUE TITLE
DPI-aware thumbnails

### ISSUE THREAD

**Issue by feidaman** [d2phap/ImageGlass#211]
On my Surface Pro 4, which has very high DPI, even after setting thumbnail size to 128 pixel, thumbnails still look quite small, and 32-pixel thumbnails are way too small to be useful. This makes me think the program currently is **not** DPI-aware (but I could be wrong!). Making it DPI-aware would have an additional benefit: the thumbnails would look roughly the same size on any system, which is especially useful when using the program in portable mode.

If the program is already DPI-aware, please forgive me. In that case it would be useful to add an extra 256-pixel option.

Thank you!

**Comment by d2phap** [comment]
Hi @feidaman 

v4.0 fully supports high DPI up to 500%, so you will see no alignment and blur issues when using the app.

There are a few options to change thumbnail size in Settings dialog, but according to your feedback, the largest 128px size seems still very tiny in your resolution. I will add some more size options (such as 256px, 512px, ...) for a better UI.

Thanks

![image](https://user-images.githubusercontent.com/3154213/28049847-9f8550fa-662c-11e7-98b4-5def557292b6.png)

**Comment by feidaman** [comment]
> Tv4.0 fully supports high DPI up to 500%

The GUI itself definitely supports high DPI, for example the toolbar buttons look look glorious. But it seems the thumbnail size is measured in actual pixels. I suspect the 32-pixel setting would be usable on a low DPI display, while on something like the Surface Pro 4 it would be too small. Here's what the 32-pixel setting looks like on my screen:

![highdpi](https://user-images.githubusercontent.com/11704566/28051363-68524d4a-6636-11e7-891d-b1c8d68dbcd3.png)

**Comment by d2phap** [comment]
Thanks for the screen shot.
It makes me clear how big the thumbnails are in your screen.
As I said, there will be more size options to make thumbnails bigger.

**Comment by d2phap** [comment]
Added new options for thumbnail: `256`, `512` and `1024`

You can set a customized value in Windows Registry: `HKEY_CURRENT_USER\Software\PhapSoftware\ImageGlass\ThumbnailDimension`

**Comment by feidaman** [comment]
Thank you
