### ISSUE TITLE
Zoom to fit in toolbar

### ISSUE THREAD

**Issue by feidaman** [d2phap/ImageGlass#212]
It would be great if the **Zoom to fit** option was also available from the toolbar, and had a keyboard shortcut too.

Of course, it would be even better if the toolbar was customizable, because I'm sure not everybody needs all those buttons, but that might be too much work.

Thank you!

**Comment by d2phap** [comment]
Thanks @feidaman 
The customizable toolbar is great idea but will take time to implement.
I also have some plans for ImageGlass.

The Zoom to fit button may appear in the next release.Thanks @feidaman 
The customizable toolbar is great idea but will take time to implement.
I also have some plans for ImageGlass.

The Zoom to fit button may appear in the next release.

**Comment by d2phap** [comment]
**Zoom to Fit** button is added into the toolbar in `develop` branch.
https://github.com/d2phap/ImageGlass/commit/eaebc6e1b33fe184cb667806722d1ba86c32f77c
Keyboard shortcut: `Ctrl + /`

**Comment by feidaman** [comment]
Thanks!
