### ISSUE TITLE
Settings window improvements

### ISSUE THREAD

**Issue by feidaman** [d2phap/ImageGlass#213]
Two simple improvements for the Settings UI:

**1) Remember Settings window last view:** Currently the program remembers the position of the Settings window, which is nice, but it doesn't remember the state of the window itself. For example, adjusting a setting under _Settings > Image > Slideshow_ takes some clicking and scrolling to get to. Because I need to close the Settings window to apply my settings, if I decide I'm not happy with my new settings and want to undo them, when I open the Settings window again I'm back at _Settings > General > Start up_, and I have to manually navigate to _Settings > Image > Slideshow_ again. It would be quicker if the program could remember the last view. The view would only be remembered for the duration of hte current session, that is, until the program closes. The view would be reset back to _Settings > General > Start up_ on the next program run.

**2) Save, Apply & Cancel buttons:** I love it when apps offer these buttons. Especially the Cancel button. At the moment closing the Settings window applies the settings, so users don't have a second chance to change their mind. Hitting the Escape key also applies settings, which I find unusual. The Apply button allows users to see their changes immediately without having to close the Settings window. This is especially useful for first-time users who are exploring through the settings.

**3) Option to keep Settings window always on top of the main window:** This is useful when used together with the Apply button. Ideally the Settings window should be always on top of the main ImageGlass window, but not on top of other windows. It should also be possible to access both windows simultaneously. If this is not possible, the way it works now is good enough.

Thanks

**Comment by d2phap** [comment]
Thanks again for great feedbacks.
1) and 2) are quite useful ideas.
3) I think it is not neccessary to set Settings window always on top because user mainly focuses on main window. User also can set main window always on top in context menu.

![image](https://user-images.githubusercontent.com/3154213/28050153-7ae200ca-662e-11e7-9556-c847dd91a700.png)

**Comment by feidaman** [comment]
Cool, and yeah 3) is not really a big deal, just ignore it

**Comment by d2phap** [comment]
Suggestion 1 and 2 are implemented

**Comment by feidaman** [comment]
Super!!
