### ISSUE TITLE
Keep menu button always visible

### ISSUE THREAD

**Issue by feidaman** [d2phap/ImageGlass#214]
This is not really a bug but it's something that I think could be improved. Currently, when the main window is not wide enough to accommodate all the toolbar buttons, the Menu button disappears. I think it's better if the menu button is visible at all times, because it is the most important button in the toolbar (it contains all toolbar commands and more!).

![toolbar](https://user-images.githubusercontent.com/11704566/28026629-4455acc4-65c9-11e7-9c0b-0826d29a4663.png)

Thanks!

**Comment by d2phap** [comment]
The PR of @EJLV has fixed the position of Main Menu icon.
