### ISSUE TITLE
Taskbar icon suggestion

### ISSUE THREAD

**Issue by feidaman** [d2phap/ImageGlass#215]
I'm being really picky here and this is a matter of taste, but I find the current taskbar icon difficult to relate to the concept of "pictures", because it's just a blue square with the letters "ig" written on it. If the icon looked a bit like a picture, it would be more logical.

See the following icons, even though the Microsoft Photos icon is very simple, it still looks more like "pictures" than the ImageGlass icon:

![taskbar icon](https://user-images.githubusercontent.com/11704566/28027871-410c366a-65cd-11e7-8155-c2d3d97d24c7.png)

Maybe something that looks like a photo with the letters "ig" written on it, and maybe some sort of glass reflection effect to hint at the original name of the software. I'm being too picky.

**Comment by d2phap** [comment]
Hi, I have a different perspective.

The non-logical icon makes it unique. For ex:
- Nodepad++ is a gecko 
- Firefox browser is a red fox
- Opera browser is just a simple O
- Photoshop / Illustrator / ... uses simply letter for icons
- Facebook icon is also the f letter wrapped by blue square
- Twitter is a bird
All above examples are to indicate that sometimes we don't need to have a logical icon :)

A non-logical icon makes people curious about itself and urges them to explore what it is.
Anyway, thanks for your feedback.

**Comment by feidaman** [comment]
That also makes sense, I suppose I will eventually get used to it and then it will feel natural :)
