### ISSUE TITLE
Preferred folder to open when I start app

### ISSUE THREAD

**Issue by miki995** [d2phap/ImageGlass#216]
### Expected behavior:
I expected that this app have some setting for choosing preferred folder to open when I start app.

### Actual behavior:
There is no such a thing.

### Steps to reproduce:
//////

### System info:
- ImageGlass version: actual from 11 july 2017
- OS version:  windows 7

### Other info:
Suggestion , make a setting which will have option to choose folder which it will open at start.
I keep all my photos in one folder, with many subfolders, dates, etc, so whenever I start app it opens only home page, I wish you could do it, when I select my folder it opens automatically when I start app.
Best, Miroslav Maksimovic

**Comment by d2phap** [comment]
Hi @miki995 

You can do it by passing folder path to ImageGlass shortcut.
Okay, right-click on the ImageGlass shortcut, select `Properties`
- Navigate to the `Shortcut` tab, the `Target` field shows the executable file of ImageGlass.
- Assuming your preferred folder path is `D:\My photos\`, you can add it into the field with `"` char:
`"C:\Program Files\ImageGlass\ImageGlass.exe" "D:\My photos\"`

Hope this helps!

![image](https://user-images.githubusercontent.com/3154213/28072539-f529084a-6685-11e7-92ef-e065ae635315.png)

**Comment by miki995** [comment]
Yes, that works, but I stil expect from you to make that in options
