### ISSUE TITLE
Suggestion - Filetype Icons (With image)

### ISSUE THREAD

**Issue by KyoGrou** [d2phap/ImageGlass#217]
Because of my job, I have to work with same image, same name but different extensions, so it's really difficult for me to find the file I wanted in short time. 
Maybe make the icon looks somewhat like faststone is good. 

Here is the sample I made. If you need the file (photoshop cs6), I will send it to your email address.

![sample](https://user-images.githubusercontent.com/30156458/28199688-786f9574-681c-11e7-8189-b9d61ddeb22c.png)

By the way, this is the best  free image viewer I have used so far, if this suggestion is solved, maybe I will consider it's a perfect image viewer 👍

**Comment by d2phap** [comment]
Hi, this is a pretty idea.
Thank you

**Comment by KyoGrou** [comment]
I want to get an update of this feature as soon as posible, what can I do to help this comes to reality ?

**Comment by d2phap** [comment]
Hi @KyoGrou 
Can you send me your design file?
It will be much better if you can make as SVG format.

ImageGlass's logo SVG file you can download here: http://www.imageglass.org/images/iglogo.svg
Thanks

**Comment by KyoGrou** [comment]
@d2phap 
Sorry but I can't make the icon vector type format.
I will make it by using photoshop's shapes, it's still scalable without losing quality.
This way I can make the icon sizes precisely (by pixel unit), easier to edit the styles, and change the content much faster.

So how about it? I will make **all of the icons** of the program. Just tell me these informations:
- How many extensions you want to make. If you want to make all the file extensions, should we use the same icon for similar extension. ( example: use a "JPEG" icon for JPE, JPG, JPEG).
- Which sizes does the .ICO contain, using 8, 24 or 32 bit images ? (32 bit can display half-transparent pixels, 24 bit display true color, 8 bit is the most light weight with acceptable quality) .
  + Recommend: 256; 128; 48; 32; 16 pixel sizes, 32 bit images.

I will send you all of the source images after everything is complete so don't worry about the changements in the future.

**Comment by d2phap** [comment]
Hi @KyoGrou 
Thanks a lot!

So please help me to create icons: 
`256; 128; 48; 32; 16 pixel sizes, 32 bit images.`

for the formats: http://www.imageglass.org/documentation/supported-formats (can use the same icon as you mentioned)

Besides, the file format list in the next version will be extended by supporting Windows Imaging Component (WIC) https://github.com/d2phap/ImageGlass/pull/231 (**but i haven't tested yet**).
You can help me to create icons the RAW formats, too. https://en.wikipedia.org/wiki/Raw_image_format

Thanks again!

**Comment by KyoGrou** [comment]
@d2phap 

I created all the extensions' icons so you can just use all of it, or just use the same icon for similar extensions, it's up to you.

I sent them to your email address: phap@imageglass.org

**Note:** 
- .ICO icon isn't included since windows display the icon itself.
- Added 24x24 size to the main program's icon since it seem like needed.
- Added icon for DDS extension.

If there is any problem, feel free to ask me.

**Comment by KyoGrou** [comment]
Can I ask you when there is an update available with all these icons ?

**Comment by d2phap** [comment]
Thanks @KyoGrou 
I plan to release the new version this month end.

**Comment by d2phap** [comment]
Implemented in the v4.5

**Comment by devcompl** [comment]
@KyoGrou I think the .ico icon is actually displayed in "list", "detail" and the lowest zoom on "small icons" views.
Would be nice if you could add it.

**Comment by KyoGrou** [comment]
I have created the icon for .ICO type and sent it to @d2phap .
Please be patient and wait for the next update :).
