### ISSUE TITLE
Make the current thumbnail look more distinct

### ISSUE THREAD

**Issue by Keith94** [d2phap/ImageGlass#218]
The background and border color of the active thumbnail is too hard to notice, in my opinion.

![image](https://user-images.githubusercontent.com/5490615/28201272-2a928a9c-6825-11e7-926d-f6b949268ec0.png)

**Comment by Keith94** [comment]
I would also say the blue colors on the toolbars doesn't stand out enough against the background (at least on my monitor it's hard to see).

![image](https://user-images.githubusercontent.com/5490615/28442884-9d1aafd0-6d67-11e7-96d8-09d2ad38b2e6.png)

**Comment by d2phap** [comment]
Implemented this in the latest build of IG Moon: https://imageglass.org/moon
