### ISSUE TITLE
GIF fullscreen to minimized glitch

### ISSUE THREAD

**Issue by mymain69** [d2phap/ImageGlass#22]
Ok this problem recently occurred when I downloaded this GIF went to fullsceen then minimized with f11, it would flash from minimize to maximize.

here is the gif
http://i.imgur.com/Rsp0lcy.gifv

I am using windows 7 home premium

**Comment by mymain69** [comment]
this is fullscreen with f11 then minimized with f11 again

**Comment by d2phap** [comment]
Fixed!
