### ISSUE TITLE
Image is blinking if open from %LocalAppData%\Temp after Firefox download

### ISSUE THREAD

**Issue by v-k-i** [d2phap/ImageGlass#220]
### Expected behavior:
Image is open as usual, can be zoomed in and out.

### Actual behavior:
After opening the image from %LocalAppData%\Temp folder (image downloaded by Firefox, after "open with.." chosen in download dialog. Or same image from that folder opened later directly.) It starts blinking each 1-2 seconds (looks like continuous reloading). If I try to zoom it, sometimes it disappears, sometimes continue blinking.  Same file cut and pasted to different folder opens OK. 

### Steps to reproduce:
1. Go to %LocalAppData%\Temp . 
2. Find some image file. Double click it to open with ImageGlass. 
3. If there are no pictures there, open Firefox, go to any site that allows to download pictures with download dialog (e.g. pixabay.com), start downloading any picture and select Open with in the dialog.  (Simple copying files to that folder does not cause this behavior)
4. Image starts blinking.
5. Try to zoom it.

### System info:
- ImageGlass version: 4.0.4.15
- OS version: Windows 10, version 1703

**Comment by d2phap** [comment]
I can reproduce this issue.
Can you help to check if it still persists in the latest build?
Can try it here: http://www.imageglass.org/moon

**Comment by d2phap** [comment]
Closed cuz no further information provided
