### ISSUE TITLE
Windows Store release

### ISSUE THREAD

**Issue by theel0ja** [d2phap/ImageGlass#224]
Win32 apps can be released on Windows Store.

Learn more: https://developer.microsoft.com/en-us/windows/bridges/desktop

**Comment by aelisya** [comment]
@d2phap hello, i just want to know if there is an update on this ? (i ask because it's been some times, and other software start to appear on the store (even without uwp) : see 7zip who is just a conversion with the Microsoft app converter : https://www.microsoft.com/en-us/p/desktop-app-converter/9nblggh4skzw?activetab=pivot:overviewtab

I really want to see your software on the store :)

**Comment by d2phap** [comment]
Hi @aelisya 
Thanks for asking. There is no progress yet, but thanks for the link, I will look into it!

**Comment by d2phap** [comment]
**ImageGlass v8.3 comes to Microsoft Store!**
This is the paid version, you will need to pay a small amount after 7-day trial.

**For the free version, it will also come from version 9.0**

If you buy ImageGlass in the Microsoft Store, you'll be supporting its development directly. You will get the convenience of fast, easy installation onto all of your Windows devices along with fully automatic, behind-the-scenes updates with all the newest features, improvements, and fixes. 😊

https://www.microsoft.com/store/productId/9N33VZK3C7TH

<a href="https://www.microsoft.com/store/productId/9N33VZK3C7TH">
  <img height="75" src="https://upload.wikimedia.org/wikipedia/commons/f/f7/Get_it_from_Microsoft_Badge.svg" />
</a>

**Comment by ghost** [comment]
> **ImageGlass v8.3 comes to Microsoft Store!** This is the paid version, you will need to pay a small amount after 7-day trial.
> 
> **For the free version, it will also come from version 9.0**
> 
> If you buy ImageGlass in the Microsoft Store, you'll be supporting its development directly. You will get the convenience of fast, easy installation onto all of your Windows devices along with fully automatic, behind-the-scenes updates with all the newest features, improvements, and fixes. 😊
> 
> https://www.microsoft.com/store/productId/9N33VZK3C7TH
> 
> [ <img alt="" height="75" src="https://camo.githubusercontent.com/3710844608ef5f15f9a7b5b33989ab74369d49b2f39a457632b092d12e48a8c2/68747470733a2f2f75706c6f61642e77696b696d656469612e6f72672f77696b6970656469612f636f6d6d6f6e732f662f66372f4765745f69745f66726f6d5f4d6963726f736f66745f42616467652e737667"> ](https://www.microsoft.com/store/productId/9N33VZK3C7TH)

Thanks i have see the free version for test.

One question through (before buy) does the update are done on the store (or must we manually check like the normal version) ?

Thanks again ;)

**Comment by d2phap** [comment]
> One question through (before buy) does the update are done on the store (or must we manually check like the normal version) ?

The update is handled by the Store, so no longer manually download and install.
