### ISSUE TITLE
Keep maximized window after exiting fullscreen

### ISSUE THREAD

**Issue by EgZvor** [d2phap/ImageGlass#226]
I just found ImageGlass and it looks pretty amazing, thank you.
Now to the issue)
### Expected behavior:
After exiting fullscreen with `F11`, the window is still maximized.

### Actual behavior:
When I have a maximized window of ImageGlass and then go into fullscreen with `F11` and then go back with `F11` again the window now in restored mode

### Steps to reproduce:
1. Maximize window
2. Go into fullscreen with `F11`
3. Go back with `F11`

### System info:
- ImageGlass version: 4.1.7.26
- OS version: Windows 10 (1703 Build 15063.483)

**Comment by d2phap** [comment]
This issue is fixed in `develop` branch.
Thanks @EJLV for your contribution!
