### ISSUE TITLE
Blank flashing if image gets updated in the background

### ISSUE THREAD

**Issue by Overdrivr** [d2phap/ImageGlass#228]
I have a long-running process that updates a PNG image every second. I'm using image glass to see results in real time.

### Expected behavior:
I would expect image to display the image without any blank flashing due to reloading

### Actual behavior:
It's not consistent, sometimes entire image disappears and reappears in quick blank flash (which is very exhausting for the eyes) sometimes it doesn't. 

### Steps to reproduce:
1. Start any process capable of updating an image in real time. If necessary, I can provide a python program that does just that
2. Open image with ImageGlass
3. Observe blank flashing when image gets updated

### System info:
- ImageGlass version: 4.0.4.15
- OS version: Win 10

**Comment by d2phap** [comment]
Hi @Overdrivr 

Yes, can you provide me the program?

**Comment by d2phap** [comment]
Closed cuz no further information provided

**Comment by Overdrivr** [comment]
Hi @d2phap, sorry about it missed your previous message. I cannot provide the program itself, but I can provide a dummy one. Do you have python installed on your machine ? This way I can share a simple script that reproduces the behavior

Cheers

**Comment by d2phap** [comment]
Hi @Overdrivr 
Thanks for coming back. 
Firstly, can you help to try out the latest build of ImageGlass Moon v5.5.12.8 if it resolved the issue? There are a lot of changes and improvements since v4.0.
Then you can provide me the script if it still persists.

**Comment by Overdrivr** [comment]
I've updated to 5.5.7.26, cannot reproduce the issue. Looks fixed, thanks !

**Comment by d2phap** [comment]
Thanks for your confirmation
