### ISSUE TITLE
Image Glass not opening png files as default

### ISSUE THREAD

**Issue by mymain69** [d2phap/ImageGlass#23]
Image would not open png pictures as my default picture viewer instead it would open windows photo viewer.

I am also using windows 7 home premium

**Comment by d2phap** [comment]
Thank you! I also received many same ones

**Comment by SnowGabe** [comment]
I have the same issue with Windows 8.1. I have to open ImageGlass first to view PNG files with this application.

All my folders that have JPG and PNG files look like this:

![2015-06-27 12_45_48-kameran kuvat](https://cloud.githubusercontent.com/assets/11059234/8391399/867006fc-1ccb-11e5-8738-93182c274385.png)

**Comment by d2phap** [comment]
@SnowGabe 
Please refer to this https://github.com/d2phap/ImageGlass/issues/16#issuecomment-112711256 to temporarily fix it.

Thanks!

**Comment by blindhead** [comment]
I solved correcting the program path in the regedit

![pantalla-001455](https://cloud.githubusercontent.com/assets/23023062/19634268/01f245fc-997f-11e6-8ad5-bc09b89eec9d.png)
