### ISSUE TITLE
Thumbnail line width resets after closing window

### ISSUE THREAD

**Issue by dansity** [d2phap/ImageGlass#232]
### Expected behavior:
I have 4k screen and I'm using bigger size thumbnails on right side. When thumbnail size set bigger a side scroll appears. I'm adjusting the width of the thumbnail area. I want it to save the width or have auto fix width based on the thumbnail size. Manual setting of width is not actually required.

### Actual behavior:
When I close imageglass and reopen the width of the thumbnail area goes back to original small size and has to be adjusted again to see thumbs.

### Steps to reproduce:
1. set thumbnail to some big size and set it to have it on the right side
2. adjust the width of the thumbnail area to show the thumbnails
3. close and reopen imageglass, the width is not saved and has to be readjusted to see thumbnails

### System info:
- ImageGlass version: 4.1.7.26
- OS version: _win 10 creators update
4k screen, 200% dpi scale

### Other info:
I like this image viewer :)

**Comment by d2phap** [comment]
This issue is fixed in `develop` branch.
Thanks @EJLV for your contribution!
