### ISSUE TITLE
Website skin DL link broken

### ISSUE THREAD

**Issue by esotericx** [d2phap/ImageGlass#233]
URL:
[http://www.imageglass.org/download/themes/simple-grey-dark-toolbar](url)

### Expected behaviour
When clicking download button new as per your websites setup up redirect page opens [http://www.imageglass.org/download/themes/simple-grey-dark-toolbar/download](url) and counts down. And then user should be prompted by a save as window.

### Actual behavior
Redirect page opens but after countdown page user is redirected to a page full of gibbirish/symbols at [http://www.imageglass.org/upload/theme/Simple_Grey_Dark_Toolbar.igtheme](url)
    **### Important:** most importantly i tested it on edge and it did work on edge. It maybe because of the beta` build i have. I wasn't aware or i suppose i forgot i was using a beta build.

### System info:
Browser: 61.0.3163.59 (Official Build) beta (64-bit)
OS: Windows 10 1703.

### Other info:
Tried multiple times to get it to work including disabling extentions. I was able to download other skins.

<bountysource-plugin>

**Comment by Keith94** [comment]
Works for me on Firefox. The `Simple_Grey_Dark_Toolbar.igtheme` file is saved correctly.

**Comment by d2phap** [comment]
Seems Chrome fixed this issue
