### ISSUE TITLE
Restore Autosave after Flip?

### ISSUE THREAD

**Issue by PrinceOfJudah** [d2phap/ImageGlass#239]
Hi guys. Would you please add an option for me to select autosaving after flipping an image? I need this because I archive books and need to flip them quickly. Thanks.

**Comment by PrinceOfJudah** [comment]
i would REALLY appreciate a setting which allowed me to leave autosave on while flipping.

**Comment by d2phap** [comment]
This option is added in `develop` branch which will be moved to `master` branch for release next few weeks.
Please be noted that the auto saving will cause image quality loss.

**Comment by PrinceOfJudah** [comment]
Thank you Mr. Phap. I appreciate it. This is a very useful feature for people like me who archive books. I archive books which are out of print and tend to be hard to get, especially on historical topics. Thanks again.

**Comment by d2phap** [comment]
If you dont want to wait for the official release, you can try the nightly build at:
http://imageglass.org/moon

:)
