### ISSUE TITLE
File bug

### ISSUE THREAD

**Issue by mymain69** [d2phap/ImageGlass#24]
Going through pictures and this message would pop up
![untitled](https://cloud.githubusercontent.com/assets/12878504/8151731/aa5f657a-12c7-11e5-85e8-cc5eb79f4ff7.png)

**Comment by d2phap** [comment]
Hello!
Is it possible to send the photo caused this bug to me for testing?
Thank you

**Comment by mymain69** [comment]
![zm1ugw](https://cloud.githubusercontent.com/assets/12878504/8175135/a04ce1b0-139a-11e5-8191-690d0a98c86f.jpg)
I know the file isn't corrupt because i can view the photo with Windows Photo Viewer

**Comment by d2phap** [comment]
fixed this issue in the 84th commit: https://github.com/d2phap/ImageGlass/commit/8d6c53aacfd720c4717b2e6e1462fd5e26dc12fa

**Comment by mymain69** [comment]
Ok sweet how do I use this?

**Comment by d2phap** [comment]
This will just notice about the bug that is fixed or not. Please wait for more few days, I will release new version soon.
