### ISSUE TITLE
Set as Background changed current Fit Option in Windows 10

### ISSUE THREAD

**Issue by tslin306** [d2phap/ImageGlass#247]
When selecting "Set as background image", windows default fit option (e.g. Fill, Tile) changed to "Fit"

### Expected behavior:
It should not change current user settings.

### Actual behavior:
Background fit was changed to "Fit" instead of previous setting.

### Steps to reproduce:
1. Set windows background fit option to "Fill" via "Personalize" option
2. Open an image using ImageGlass
3. Right click on the image and select "Set as desktop background"

### System info:
- ImageGlass version: 4.1.7.26
- OS version: Windows 10 Home Edition (64bit)

**Comment by d2phap** [comment]
This issue is fixed in `develop` branch.
Thanks @EJLV for your contribution!

**Comment by tslin306** [comment]
This issue is happening again in 5.5.7.26. Please help to check again.

**Comment by d2phap** [comment]
Hi @tslin306 
I acknowledged the issue and fixed in IG Moon. It will be shipped to the new version next few weeks.
