### ISSUE TITLE
Suggestion: Explorer window 

### ISSUE THREAD

**Issue by KyoGrou** [d2phap/ImageGlass#252]
There are time I need to sort the images by the contents, but my work required me to use the extension's icons in windows' file explorer, so an intergrated explorer window will save my day.

Just like the FastStone Image viewer is good. It can interact with file explorer, I can do things like copy, paste, delete, drag and drop. The current thumbnail view doesn't help much.
![example](https://user-images.githubusercontent.com/30156458/31946572-6697fe0a-b8fc-11e7-8b1b-b34475258e45.png)

**Comment by d2phap** [comment]
I think you can use File Explorer for all functionalities mentioned above. 
As of now, there is no plan to build the file explorer in ImageGlass.
