### ISSUE TITLE
Copy image data to clipboard

### ISSUE THREAD

**Issue by Sorashi** [d2phap/ImageGlass#253]
Currently, when you hit `CTRL+C` or click *Copy* in the context menu, the *file* gets copied into the clipboard. However, most of the time I need to copy the *image data* into the clipboard. I can't find any way to do that in ImageGlass (is there a way?). In other words, currently, you are using [`Clipboard.SetFileDropList`](https://msdn.microsoft.com/library/system.windows.forms.clipboard.setfiledroplist(v=vs.110).aspx) [[source](https://github.com/d2phap/ImageGlass/blob/7c69bbd414116c9b6bb7d02374dc56e0fe59232e/Source/ImageGlass/frmMain.cs#L964)] (or its alternative using `DataObject`).
 I'd like to add the option of using [`Clipboard.SetImage`](https://msdn.microsoft.com/library/system.windows.forms.clipboard.setimage(v=vs.110).aspx) or [`DataObject.SetImage`](https://msdn.microsoft.com/library/system.windows.forms.dataobject.setimage(v=vs.110).aspx). You could add it as `CTRL+SHIFT+C` for example.

This would be useful mostly for use in web applications, where you have to paste image data. Examples of these applications: Facebook (chat), [Discord](https://discordapp.com/), [Imgur](https://imgur.com/) and most communication software where you can send an image. You can't copy and paste a file into these, you have to copy and paste the image data straight into and from the clipboard.

**Comment by d2phap** [comment]
Hi @Sorashi,
Thanks for the suggestion.
There will be an implementation for this in v5.0

Phap

**Comment by d2phap** [comment]
This feature was implemented in `develop` branch.
I will uploaded to http://www.imageglass.org/moon soon
