### ISSUE TITLE
Add 'View with ImageGlass' context menu option

### ISSUE THREAD

**Issue by Keith94** [d2phap/ImageGlass#255]
Request:
In File Explorer, when right-clicking a file that's supported by ImageGlass, the main context menu should have an option 'View with ImageGlass' (with icon displayed) to open the image

**Comment by d2phap** [comment]
Hi @Keith94 

It is not the context menu as you requested but you can add ImageGlass into Open with menu or set as default image viewer by
- Go to Settings > File Associations
- Click on Register Extensions button

**Comment by Keith94** [comment]
Hi @d2phap and thanks, I know about that but I figured it would be nice to also have it in the main context menu (since I switched from Honeyview to ImageGlass). Is that something you will consider adding?

**Comment by d2phap** [comment]
I can help to provide the registry script for that but I think it is not necessary to integrate into ImageGlass because I would prefer the user set ImageGlass as default viewer :)

**Comment by Keith94** [comment]
If you can share the registry script I'd appreciate it!

I would mostly be using the context menu option for compressed archive files (#254) which are associated with a file archiver by default, but I still like to open them quickly in an image viewer via the menu without changing the associations.

**Comment by Keith94** [comment]
This is also useful for folder context menus to open folders quickly.

**Comment by d2phap** [comment]
This one is quite old already, I guess I will just close
