### ISSUE TITLE
Image is not resized in real-time while resizing window

### ISSUE THREAD

**Issue by Keith94** [d2phap/ImageGlass#257]
### Steps to reproduce:
1. Open ImageGlass with default zoom settings
1. Open an image that's much larger than the window size so it gets scaled down to fit
2. Slowly resize the window dimensions to be much smaller

### Expected behavior:
The image should be resized in real-time so that the image properly fits the window at all times

### Actual behavior:
The image only gets resized once you finish resizing the window and release the left mouse button

### System info:
- ImageGlass version: 4.1.10.25 Moon [Portable]
- OS version: Windows 10

**Comment by d2phap** [comment]
Hi @Keith94 
I understand your expectation but to optimize the performance when you resize the window, ImageGlass will only resize the image after window is resized.

The real time resizing may take much effort of CPU to redraw the image.
Thanks :)

**Comment by Keith94** [comment]
>The real time resizing may take much effort of CPU to redraw the image.

Are you sure there is really a performance impact for that kind of resizing? I didn't notice any performance issues with the Windows 10 Photos app or Honeyview which both support this "fast resizing".

I suggest run some tests and maybe reconsider adding it, if you want.

**Comment by d2phap** [comment]
Added support for real time resizing

**Comment by Keith94** [comment]
Proper resizing! Now I'm liking it ;)
Thanks a lot for implementing.
