### ISSUE TITLE
Dark theme not available in pre-release

### ISSUE THREAD

**Issue by Keith94** [d2phap/ImageGlass#258]
The latest [ImageGlass Moon](http://www.imageglass.org/moon) (4.1.10.25) seems to only include the Light Gray theme (labelled "Dark"), but I don't see an option to select or download the "real" Dark theme (from the stable releases).

![image](https://user-images.githubusercontent.com/5490615/32580846-317baed2-c49c-11e7-9797-bab933e51e9b.png)

**Comment by d2phap** [comment]
Hi @Keith94
This is the dev build only.
Dark theme will be back on official release
