### ISSUE TITLE
Show checked background on transparent images only

### ISSUE THREAD

**Issue by Keith94** [d2phap/ImageGlass#259]
I'd prefer if the checked background only applies to images with transparent backgrounds (to show the transparency), and the window background stays the same color. You could add a separate option for this also.

**Comment by d2phap** [comment]
Hi @Keith94 

> I'd prefer if the checked background only applies to images with transparent backgrounds (to show the transparency)

- If the image is not with transparent background, the checkered background will be also covered by the image; therefore, it is unnecessary to add an option for this.

> and the window background stays the same color

- I think you want the checkered background color should match with the viewer's background?

**Comment by Keith94** [comment]
>If the image is not with transparent background, the checkered background will be also covered by the image

This is intended, because the checkered background could be used to show where the transparency is.
For example in Firefox, the viewer background is dark but the transparency is shown as light gray:

![image](https://user-images.githubusercontent.com/5490615/32657073-32969d80-c5c9-11e7-85c0-761580d6ec47.png)

Alternatively you could add an option that sets the transparency background color separately from the window background.

**Comment by d2phap** [comment]
Hi @Keith94 
Your request was implemented in IG Moon 5.5.12.15 
https://imageglass.org/moon

**Comment by Keith94** [comment]
Looks great! Thanks so much.
