### ISSUE TITLE
Better full screen support

### ISSUE THREAD

**Issue by Keith94** [d2phap/ImageGlass#261]
### Steps to reproduce:
1. Open a large image (larger than the desktop)
2. Resize the ImageGlass window down (50% ish)
3. Enter full screen mode

### Expected behavior:
* Image's height fits the window automaticallly
* Hides the thumbnail bar automatically (same as the toolbar)

### Actual behavior:
* Image is displayed at same size until toggled manually
* Thumbnail bar must be hidden manually

### System info:
- ImageGlass version: ImageGlass_Moon_4.1.10.25
- OS version: Windows 10

**Comment by d2phap** [comment]
Hi @Keith94 

> Image's height fits the window automatically

- Agree with you about this.




> Hides the thumbnail bar automatically (same as the toolbar)

- The Full screen mode will be just allow user to use the app in "full screen" literally. So it will keep all the states of window layout.

**Comment by Keith94** [comment]
>The Full screen mode will be just allow user to use the app in "full screen" literally. So it will keep all the states of window layout.

Maybe add an option for it? It's not a huge deal, but I expect that full screen hides all other toolbars to remove distractions. ImageGlass already hides the top toolbar by default.

**Comment by d2phap** [comment]
Implemented both 2 issues:

- Image's height fits the window automatically
- Hides the thumbnail bar automatically (same as the toolbar)

You can try the latest build here: http://www.imageglass.org/moon

**Comment by Keith94** [comment]
Awesome! Thanks.
