### ISSUE TITLE
Unhandled exception when closing two windows

### ISSUE THREAD

**Issue by Keith94** [d2phap/ImageGlass#262]
### Steps to reproduce
1. Open two images in ImageGlass (in two separate windows)
1. Right-click ImageGlass on the taskbar and do "Close all windows"

### Actual results
Exception text: https://pastebin.com/Sc8g8h0F

### System info:
- ImageGlass version: 4.1.10.25
- OS version: Windows 10

**Comment by d2phap** [comment]
This issue is fixed in `develop` branch
