### ISSUE TITLE
feature request | rotate image -> safe edit

### ISSUE THREAD

**Issue by josefkreitmayer** [d2phap/ImageGlass#263]
### Expected behavior: 

When I rotate one or multiple images, I expect an option to save that rotation

### Actual behavior:
The UI is awsome. The buttons for going through the galery are right next to the rotate buttons (something most image viewers did not figure out yet), but the programm is useless for organizing my images, as I cannot save the image rotations.

### Other info:
Cudos, awsome UI. Drop me a note, when that feature is available, and it is my image viewer again right away. I tested and loved it, but can´t save, so useless for me.

Keep up the good work!

**Comment by d2phap** [comment]
Hi @josefkreitmayer 

You can try the latest build here: www.imageglass.org/moon
This is implemented by the request #239 
However, I have received an enhancement request as #267 

Please be noted that, saving image in ImageGlass **_loses its quality_** which I am still working on.
Thanks

**Comment by d2phap** [comment]
Implemented lossless JPEG rotation in `develop` branch.
Can try it here: http://www.imageglass.org/moon
