### ISSUE TITLE
Save after rotating enhancement 

### ISSUE THREAD

**Issue by d2phap** [d2phap/ImageGlass#267]
From https://groups.google.com/forum/#!topic/imageglass/jIq43KJZHXQ

In 3.5 you used to be able to rotate and image, and then when you moved on to next image it was automatically saved...without any confirmation prompts...it was just saved for you.

In 4.1 if you rotate 90 degrees, then move to next image, you don't get any "save" or "your image has been modified" prompts...it just goes onto the next image...if you move back to your image...you will see that no changes were done.

One has to do a CTRL+S (Save)...after the rotate, and before moving on, also it is annoyingly asking for the filename (you just want to save to the same file).

Could we have something that considered a rotate a modifying operation?....when you move onto the next image...you could show a prompt like this:

"Image was rotated, do you want to save? yes/no/cancel"

This would be better than 3.5 (which did a save even though you didn't know it would modify), and better than 4.1 as it makes it easier to rotate the image.

**Use case is this:**
I usually have a directory of images some need rotating, some don't, and I have to preview/view each one to decide what needs doing....a quick way to do this operation would be great!

**Comment by monkeynoises** [comment]
Actually another thought.....provide this message and buttons?

"Image was rotated/has been modified?"

Save, SaveAs, Lose Changes, Cancel

Also you could bring back the auto-save without any prompting at all....if there was a way to "undo" the save perhaps (e.g. keep the original in a backup file, or something?)

**Comment by d2phap** [comment]
Hi @monkeynoises 

> Also you could bring back the auto-save without any prompting at all

- You can try the latest build here: http://www.imageglass.org/moon

**Comment by d2phap** [comment]
Implemented lossless JPEG rotation in `develop` branch.
Can try it here: http://www.imageglass.org/moon

**Comment by DimoNline** [comment]
Images rotation is still not saving.

**Comment by fire-eggs** [comment]
@DimoNline : what operating system, what version of ImageGlass ?

**Comment by d2phap** [comment]
@DimoNline 

You should check the option: Save the viewing image after rotating.
However, ImageGlass does not keep the metadata.

![image](https://user-images.githubusercontent.com/3154213/90463375-61e6ed00-e13d-11ea-9f82-69804899359e.png)

**Comment by DimoNline** [comment]
@d2phap thank, it had solve the issue. This string translated to russian a little bit wrong. It sounds like "Rewrite the file auto rotation"

**Comment by d2phap** [comment]
@DimoNline 
Do you have any better translation? I can update the language pack
