### ISSUE TITLE
Zooming with keyboard doesn't follow mouse position

### ISSUE THREAD

**Issue by Keith94** [d2phap/ImageGlass#268]
### Steps to reproduce:
1. Open an image
2. Place your mouse cursor in a specific spot (eg, top of the image)
3. Press the <kbd>+</kbd> key a few times to zoom in

### Expected behavior:
IG should zoom in on the specific spot under the mouse cursor (just like mouse wheel zoom behavior)

### Actual behavior:
IG only zooms in on the center of the image

### System info:
- ImageGlass version: 4.5.11.14
- OS version: Windows 10

**Comment by d2phap** [comment]
As default behavior of ImageGlass, when you zoom with keyboard, the viewing image will be re-centered. 
This is actually not necessary but I will  still mark this as a suggestion.

**Comment by Keith94** [comment]
Thanks, it didn't seem necessary to me either. ;) Following the mouse position would be a nice enhancement!

**Comment by d2phap** [comment]
Closed because being not necessary
