### ISSUE TITLE
Add possiblity to Play and Pause  GIF images

### ISSUE THREAD

**Issue by 4goodapp** [d2phap/ImageGlass#27]
Can you add possiblity to Play and Pause  GIF images.

**Comment by d2phap** [comment]
Added!

**Comment by 4goodapp** [comment]
I just notice that my suggestion was added a year ago, Thank you very much.
Just one problem, I still don't know how to pause gif images. Is their a shortcut or something like that?

**Comment by Eboubaker** [comment]
how can we pause gif images?

**Comment by Eboubaker** [comment]
> I just notice that my suggestion was added a year ago, Thank you very much.
> Just one problem, I still don't know how to pause gif images. Is their a shortcut or something like that?

it is actually the ctrl+space key
