### ISSUE TITLE
Next image in folder not opened after deleting image

### ISSUE THREAD

**Issue by Keith94** [d2phap/ImageGlass#270]
### Steps to reproduce:
1. Make a folder with three images in it
2. Open the first image in IG
3. Press <kbd>Delete</kbd> to delete it

### Expected behavior:
The second image in the folder should be loaded in IG automatically

### Actual behavior:
IG only displays the text "The viewing image doesn't exist"

### System info:
- ImageGlass version: 4.5.11.14
- OS version: Windows 10

**Comment by Keith94** [comment]
Hmm, I see... well, despite the technical reasons for the new behavior, I just find it really inconvenient having to load the next image manually rather than ImageGlass doing it automatically.

I hope you (or someone) can come up with a good solution to this.

**Comment by Keith94** [comment]
Hi @d2phap ! this issue seems to be fixed in v4.5.11.27. Can you confirm that's the case?

**Comment by d2phap** [comment]
Yes, I tried in last minutes.
However, when deleting multiple files, the viewer becomes blank. It only fixed when user delete less than 3 files at the same time.

**Comment by tslin306** [comment]
This issue is not happening in 4.5.11.27 stable. But in 4.5.11.14_moon. Also, indexing seems to have  some issue. Let's say I have 3 images loaded (img1~3). While img1 is open, i delete it. IG display "The viewing image doesn't exist". When I scroll or use arrow key to move to next image, it show img3 instead of img2. Img2 has been skipped..

**Comment by d2phap** [comment]
I just realized the **case sensitive**: `PNG` vs `png`.
Only all lower case extensions are triggered.
I also push a commit to fix it. It may also fix a lot of related issues: #309 #296 #288 #270 #316 #193 

You can try the latest build here: http://www.imageglass.org/moon
