### ISSUE TITLE
Drag-and-drop image from same folder doesn't open the image

### ISSUE THREAD

**Issue by Keith94** [d2phap/ImageGlass#271]
### Steps to reproduce:
1. Make a folder with two images in it
2. Open the first image in IG
3. Go back to the folder and drag-and-drop the second image onto the IG window that has the first image in it

### Expected behavior:
The second image you dragged should be opened/switched to automatically

### Actual behavior:
Nothing happens

### System info:
- ImageGlass version: 4.5.11.14
- OS version: Windows 10

**Comment by d2phap** [comment]
Fixed in the `develop` branch

**Comment by Keith94** [comment]
Awesome thanks 👍
