### ISSUE TITLE
D3DCOMPILER_47.dll is missing

### ISSUE THREAD

**Issue by Nikdoge** [d2phap/ImageGlass#275]
### Expected behavior:
I expect the program to open image.

### Actual behavior:
I'm getting an error saying this: 
"ImageGlass.exe - Системная ошибка / Запуск программы невозможен, так как на компьютере отсутствует D3DCOMPILER_47.dll. Попробуйте переустановить программу." (orig., rus.), 
"ImageGlass.exe - System error / Unable to start the program, because D3DCOMPILER_47.dll is missing on this computer. Try to reinstall the program" (translation).
After I press OK it normally opens the image. _So a question appears, which program is unable to start?_

Anyway, I'm getting this error only by opening images by ImageGlass, and reinstall didn't change anything.
![2017-11-20 09_34_58-imageglass 4 1](https://user-images.githubusercontent.com/11614920/33005667-d742474c-cdd7-11e7-8fb6-2608ced0777d.png)

UPD: This problem occurs not since the install of the program, but only in a couple of weeks.

### System info:
- ImageGlass version: 4.1.7.26
- OS version: Windows 7 64 bit

### Other info:
The best image viewer I've ever seen.

**Comment by d2phap** [comment]
Hi @keedi 

As the error decsription, the `D3DCompiler_47.dll` file in `%windir%\system32` folder is missing.

Please install the file via this link from Microsoft:
https://support.microsoft.com/en-us/help/4020302/the-net-framework-4-7-installation-is-blocked-on-windows-7-windows-ser

> UPD: This problem occurs not since the install of the program, but only in a couple of weeks.

-> I think you installed .NET Framework 4.7?

**Comment by Nikdoge** [comment]
This Microsoft update fixed the error. Thanks.

No, .NET Framework 4.7 wasn't installed, but many other programs was.
