### ISSUE TITLE
Light Gray theme has missing toolbar icon

### ISSUE THREAD

**Issue by Keith94** [d2phap/ImageGlass#277]
![imageglass_2017-11-26_11-39-14](https://user-images.githubusercontent.com/5490615/33243645-0b5c4098-d29f-11e7-8d27-1c164888e664.png)

### System info:
- ImageGlass version: 4.5.11.27 portable
- OS version: Windows 10

**Comment by d2phap** [comment]
Updated the theme

**Comment by Keith94** [comment]
I reinstalled this theme but I can still reproduce the issue... Are you sure "zoom to fit" is updated?

**Comment by d2phap** [comment]
@Keith94 
Sorry I uploaded wrong file.
Can you download again?

Thanks

**Comment by Keith94** [comment]
Fixed, thanks!
