### ISSUE TITLE
Extension manager buttons are invisible

### ISSUE THREAD

**Issue by Keith94** [d2phap/ImageGlass#278]
If you resize the extension manager window to be too small, some buttons may not be visible such as the "Apply" button, which is important to switch themes.

![image](https://user-images.githubusercontent.com/5490615/33243678-a2152b3a-d29f-11e7-92b2-fcfe6770f8c4.png)

**Comment by d2phap** [comment]
The extension will be moved to Settings window in the next version and be fixed.
I won't fix this issue in plugin level.
