### ISSUE TITLE
Leave feedback button leads to Google Code

### ISSUE THREAD

**Issue by Konstamokh** [d2phap/ImageGlass#28]
The "Leave feedback" button at the top right corner leads to this page:
https://code.google.com/hosting/moved?project=imageglass

**Comment by d2phap** [comment]
Thanks, but google code currently allow me to activate "Move Project" function only, without any customized message

**Comment by Konstamokh** [comment]
Why don't you link to the github page with the button?

**Comment by d2phap** [comment]
Hi @Konstamokh 

That button is just for the app which doesnt exist in Github. I had already moved to Github for a long time before Google gave closing announcement.
