### ISSUE TITLE
UI doesn't rescale on multiple monitors with different DPI settings

### ISSUE THREAD

**Issue by enzy** [d2phap/ImageGlass#281]
### Expected behavior:

When you move the app window from one monitor (screen) to another, it should rescale to actual monitor DPI.

### Actual behavior:

The app is properly scaled to the highest DPI (150% in my case), but it stays that way also on a monitor with 100% scale. Icon toolbar looks fine, but the window top bar is huge.

![image](https://user-images.githubusercontent.com/809888/33433162-d55ff374-d5da-11e7-91d1-a2313ef1bbb1.png)

### Steps to reproduce:
1. Have at least 2 monitors with different system DPI
2. Launch app and move it between monitors

### System info:
- ImageGlass version: 4.5.11.27
- OS version: Windows 10 Pro 1709 (17046.1000)

**Comment by CrizGames** [comment]
It would be great if it gets fixed. It is a bit annoying to have that huge window on my smaller monitor.

**Comment by d2phap** [comment]
Should be fixed in v9.0 RC
