### ISSUE TITLE
Zoomed image looks cropped in full screen

### ISSUE THREAD

**Issue by Keith94** [d2phap/ImageGlass#284]
### Steps to reproduce:
1. Open a large image
2. Zoom in once
3. Go fullscreen

### Expected behavior:
Full image is displayed even while zoomed in fullscreen
or
Scaling resets to default aka zoom to fit (same as win 10 photos app)

### Actual behavior:
Image stays at the same zoom (and looks cropped)

### System info:
- ImageGlass version: 4.5.11.27
- OS version: Windows 10

### Other info:
![2017-12-11_10-23-40](https://user-images.githubusercontent.com/5490615/33846875-75402aaa-de5d-11e7-83ff-d92c78386a74.gif)

**Comment by d2phap** [comment]
Hi! There are some logics about zooming when you change the window size:

- If you enable `Zoom To Fit`, the image always fits to the viewer.
- If you zoom in/out, the image always remains your zoom ratio (and the panning position of zoomed image)

This is to make sure your viewing image not loose its state.
