### ISSUE TITLE
[BUG] RAM overload crash if there's a .PSD file in the directory

### ISSUE THREAD

**Issue by AlexAlabyev** [d2phap/ImageGlass#286]
If you open any normal size image (e.g. ~2MB .JPG) that is in a folder which contains a big .PSD file (75 MB in size: ~40 groups, ~300 layers), ImageGlass process quickly takes up a few GB of RAM and then crashes

Perhaps the solution to this problem would be to disable pre-caching of all (or just .psd) big files in the folder?

### System info:
- ImageGlass version: 4.5.11.27
- OS version: Win 10

**Comment by d2phap** [comment]
There is a memory leak bug reported #119 causing by ImageMagick.NET lib.
This just happens on few image files (?)
Please refer to #119, I will close this. 
Thanks

**Comment by AlexAlabyev** [comment]
@d2phap well, it happens with big PSD files. ImageGlass becomes completely unusable for all the graphics designers.
Maybe it'd be just better to not display PSD files at all (they are always getting displayed incorrectly anyway...)
