### ISSUE TITLE
deleting pictures in ImageGlass does not remove them

### ISSUE THREAD

**Issue by Phangan** [d2phap/ImageGlass#288]
### Expected behavior:
Hitting the delete button when an jpeg is openend in ImageGlass (and it is the active window of course) should of course delete it. ImageGlass should delete it from the hard disk, update the file list and remove the thumbnail of this image.

### Actual behavior:
Hitting the delete button does delete the jpeg from the hard disk, but ImageGlass does NOT update it's file list. The thumbnails in ImageGlass are still there and browsing through the folder in ImageGlass still shows the deleted pictures in full resolution.

### Steps to reproduce:
see above

### System info:
- ImageGlass version: 4.5.11.27
- OS version: Windows 10 Home

### Other info:
none

**Comment by d2phap** [comment]
Discuss at #296
