### ISSUE TITLE
Feature Request: Option to Show File Basename Only in Titlebar

### ISSUE THREAD

**Issue by AntumDeluge** [d2phap/ImageGlass#290]
If this functionality isn't present already, I would like to have the option to show only the basename of the currently displayed file, instead of the absolute path in the titlebar.

Mockup preview:
![imageglass-mockup](https://user-images.githubusercontent.com/3631473/34447412-6b4cd4c8-ec98-11e7-8793-4323d142d770.png)

**Comment by d2phap** [comment]
This is set as default (ImageGlass will show file base name instead of full path).
Implemented in `develop` branch. Update to http://www.imageglass.org/moon soon

**Comment by AntumDeluge** [comment]
Thank you so much! 😃

**Comment by d2phap** [comment]
You can download the latest build here: http://www.imageglass.org/moon
This is not a official release yet

**Comment by AntumDeluge** [comment]
Thank you. Downloading now.

**Comment by AntumDeluge** [comment]
Loving it!

Is there an option to switch back to display full path? I must be missing it in settings.

**Comment by AntumDeluge** [comment]
Thank you, it is working great.

I did notice that the applications needs to restart before the changes show up. Perhaps put a note about that in braces next to the setting?

**Comment by d2phap** [comment]
@AntumDeluge 
It should work when you view another image or start zooming.
There is ___no setting___ that requires restarting in the latest build 5.0.4.23 (even theme changing).

Some settings will be effective on the next action. For ex:
`Image loading order` will be effective when you open the image in a new folder.
