### ISSUE TITLE
Delete picture with delete key

### ISSUE THREAD

**Issue by xiti** [d2phap/ImageGlass#296]
### Expected behavior:
Delete a picture by pressing delete key on the keyboard and show next available picture.

### Actual behavior:
Does not delete the picuture. Non existing.

### Steps to reproduce:
N/A

### Feature request:
Add delete button in the GUI + activate delete key.

### System info:
- ImageGlass version: Latest available on 9/1/2018
- OS version: Win 10 Pro

### Other info:
N/A

**Comment by Phangan** [comment]
Please take a look at my issue #288.
I think the delete button deletes the image from the hard disk, but does not trigger a refresh of the file list of ImageGlass, so the image is still in the cache and displayed by ImageGlass.
Please open an image in ImageGlass, hit the delete button and check with a file browser if the image is still there or has been deleted. I believe the second.

**Comment by fire-eggs** [comment]
The Delete key is a keyboard shortcut for the menu entry "Delete from hard disk".

Phangan's hypothesis in issue #288 is correct. Refresh of the image list only happens with a GIF file. 

I cannot build the current code (I'm stuck at VS2013, no C# 7), but here are the two quick-and-dirty changes to frmMain.cs:

1. In `mnuMainDeleteFromHardDisk_Click` at line 2243(?), comment out the line:
`if (ext == ".gif") `
2. In `mnuMainMoveToRecycleBin_Click` at line 2194 (?), comment out the same line.

A "better" fix would be to have one copy of the code to delete a file, and invoke it from the two menu handlers, passing a bool flag for using the recycle bin.

**Comment by d2phap** [comment]
@fire-eggs, @Phangan

The whole block `if (ext == ".gif")` is actually not necessary. I forgot to remove.

 
You are correct. The delete function is quite complex with `System Watcher` - to keep the logic correct and real time updated. 
Whenever we make change a file (rename, delete, create, change attribute,....) the `System Watcher` will trigger an event or **two**. 

Actions | `System Watcher` Events
------------ | -------------
Update | delete + create
Create | create
Delete | delete

https://github.com/d2phap/ImageGlass/blob/develop/Source/ImageGlass/frmMain.cs#L1962

As we can see, both `update` and `delete` action have same events. The updating function must wait for few millisecond to detect the actions. This is to fix #270

I checked MS Photos, when users delete all files in the viewing folder but they still able to browse through photos (?). It means, they are just viewing temporary photos.

**Comment by d2phap** [comment]
I just realized the **case sensitive**: `PNG` vs `png`.
Only all lower case extensions are triggered.
I also push a commit to fix it. It may also fix a lot of related issues: #296 #288 #270 #316 #193 

You can try the latest build here: http://www.imageglass.org/moon
