### ISSUE TITLE
Feature request: Allow to use mouse wheel to scroll the image

### ISSUE THREAD

**Issue by RoToRa** [d2phap/ImageGlass#298]
It would be great to allow the mouse wheel to scroll the image up/down (and possibly left/right with a modifier key or "tilting" the mouse wheel) when zoomed in.

**Comment by d2phap** [comment]
Hi @RoToRa 

Your request was implemented in `develop` branch, and also posted as issues #95, #110
You can download the latest build here http://www.imageglass.org/moon
It is not the official version.

**Comment by RoToRa** [comment]
Ah, great, thank you. Sorry for the duplicate. I had only searched the open issues.
