### ISSUE TITLE
Bug: Using the German language package buttons in Settings dialog overlap

### ISSUE THREAD

**Issue by RoToRa** [d2phap/ImageGlass#299]
When using the German language package several buttons overlap each other in the Settings dialog:

- "Apply" ("Übernehmen") overlaps "Cancel" ("Abbrechen")
- Image / Image editing ("Bild / Bildbearbeitung"): "Reset to Default" ("Auf Standard zurücksetzen") overlaps "Edit" ("Bearbeiten")
- File Associations("Dateizuordnungen"): 
  - "Open File Associations" link ("Dateizuordnungen festlegen") cut off at window border 
  - "Add" ("Hinzufügen")  overlaps "Delete" ("Löschen")
  - "Register extensions" ("Registriere Erweiterungen") overlaps "Reset to Default" ("Auf Standard zurücksetzen")

**Comment by d2phap** [comment]
Thanks @RoToRa 
This is because the width of button is less than the length of text. I will make adjustment accordingly

**Comment by d2phap** [comment]
updated button size
