### ISSUE TITLE
Welcome image flickers into actual image displayed if welcome image is enabled

### ISSUE THREAD

**Issue by lucidfox** [d2phap/ImageGlass#30]
When ImageGlass is launched by double-clicking an image file (or choosing "Open With"), the welcome image is briefly seen, flickering into the image that is about to be displayed.

**Comment by d2phap** [comment]
Go to Settings > General. Uncheck the option 'Show welcome photo'

**Comment by lucidfox** [comment]
That's what I did, but it would be nice if the welcome image wasn't shown if ImageGlass was invoked with a filename argument. When I have time, I might prepare a patch for that if you don't get to it first.

**Comment by d2phap** [comment]
Thank you !
