### ISSUE TITLE
Rotation Pictures is reducing Qualtity and Size (MB)

### ISSUE THREAD

**Issue by President001** [d2phap/ImageGlass#300]
### Expected behavior:
I am rotating Pictures in ImageGlass 

### Actual behavior:
The rotation is saved (that is good) "but the IMG quality and the size of the picture is reduced" (from 5,2mb to 1,75mb or 1,2mb to 0,6mb)

### Steps to reproduce:
Just rotate a picture directly in ImageGlass, in any direction

### System info:
- ImageGlass version: 4.5.11.27 portable
- OS version: Win10 64bit

thx

**Comment by d2phap** [comment]
Hi @President001 
Image rotation is under warning due to losing quality. #219 #239  
There are some requests for work-around #263 #267
I will close because it is duplicated

**Comment by d2phap** [comment]
Implemented lossless JPEG rotation in `develop` branch.
Can try it here: http://www.imageglass.org/moon
