### ISSUE TITLE
File associations on Windows 10

### ISSUE THREAD

**Issue by lizzardhub** [d2phap/ImageGlass#302]
This is a general issue with Windows 10... File associations made from ImageGlass internal settings are being reset by Windows. Also, ImageGlass doesn't show up in the list in 'Settings->default apps->photo viewer'. Thus making ImageGlass a viewer by default is painful.

**Comment by d2phap** [comment]
Hi @lizzardhub 

To add it into default apps list:
- Go to Settings > File Associations
- Click on `Register Extensions` button

You can check out the tutorial here: http://www.imageglass.org/news/how-to-set-ImageGlass-as-default-photo-viewer
