### ISSUE TITLE
Option to preserve mod date on edit (especially rotating)

### ISSUE THREAD

**Issue by ekzoss** [d2phap/ImageGlass#307]
One of the main issues with recent windows photo viewers is that they change the mod timestamp on the photos.  Generally this is undesirable, as it's much more valuable to preserve the original mod timestamp on photos for later sorting purposes (quicker and more universal than EXIF).

Would be great if there was an option to do that in this tool.

Also would be nice if you could display mod timestamp in the toolbar rather than create.

### Expected behavior:
Feature to not change mod timestamp when photo is rotated (or maybe other edits too)

### Actual behavior:
Don't see that feature yet

### Steps to reproduce:
Rotate a photo in ImageGlass
Mod TS is changed to current time

### System info:
- ImageGlass version: Just downloaded
- OS version: win10

**Comment by d2phap** [comment]
this was implemented in v5.5
