### ISSUE TITLE
Real-time update the editing image

### ISSUE THREAD

**Issue by iwacky** [d2phap/ImageGlass#309]
### Expected behavior:
Refresh button refresh image view

### Actual behavior:
Refresh button does not refresh image view

### Steps to reproduce:
1. Open a PNG image with ImageGlass
2. Right click on image > Modify image
3. Paint is opened > Draw something > Save and close
4. Push Refresh button

### System info:
- ImageGlass version: 4.5.11.27
- OS version: Windows 10 1703

Rgards

**Comment by d2phap** [comment]
Hi @iwacky 

ImageGlass will auto-detect the changes on the viewing image and update it.
Refresh button will just reset the image to the one stored in memory.

Can you check again if your issue still persists?

**Comment by iwacky** [comment]
Hi @d2phap,

Please try the steps to reproduce.
No "change" is detected when Paint save the new image.

**Comment by greenfrogs** [comment]
Confirmed can reproduce using version 4.5.11.27.

1. Open image in ImageGlass
2. Open image in paint and change image then save
3. Go back to ImageGlass (no change)
4. Press refresh (no change except file size in the window name).

**Comment by greenfrogs** [comment]
Possible link to https://github.com/d2phap/ImageGlass/issues/296

**Comment by d2phap** [comment]
Hi @greenfrogs 
I just realized the **case sensitive**: `PNG` vs `png`.
Only all lower case extensions are triggered.
I also push a commit to fix it. It may also fix a lot of related issues: #296 #288 #270 #316 #193 

You can try the latest build here: http://www.imageglass.org/moon
