### ISSUE TITLE
"Image properties" menu item incorrectly handles Unicode characters

### ISSUE THREAD

**Issue by lucidfox** [d2phap/ImageGlass#31]
To reproduce this issue:

1. Rename an image file to a name containing non-ASCII characters (e.g. абвгд.png, with Cyrillic letters).
2. Open the image in ImageGlass.
3. Right click and select "Image properties".

Instead of the image properties, an error message box pops up, saying that the file "?????.png" cannot be opened. I assume that the file name string is incorrectly converted to/from Unicode.

**Comment by d2phap** [comment]
Thanks! 
I tried these steps. Perhaps, Windows API doesn't support Cyrillic??
Let me research more

**Comment by lucidfox** [comment]
It does. I think the answer may be that you're calling the ANSI version of ShellExecuteEx instead of the Unicode version. Try adding  CharSet = CharSet.Unicode to the DllImport attribute.

I'll test the fix locally.

**Comment by fire-eggs** [comment]
I have images with Japanese characters in the filename. To get properties to work for these images, I found that two changes were required to ImageInfo.cs:
 1. Declare the DllImport statement with CharSet.Auto:
```        
[DllImport("shell32.dll", CharSet=CharSet.Auto)]
private static extern int ShellExecuteEx(ref SHELLEXECUTEINFO s);
```
 2. The first four strings in the SHELLEXECUTEINFO structure need to be marshaled appropriately:
```
            [MarshalAs(UnmanagedType.LPWStr)]
            public string lpVerb;
            [MarshalAs(UnmanagedType.LPWStr)]
            public string lpFile;
            [MarshalAs(UnmanagedType.LPWStr)]
            public string lpParameters;
            [MarshalAs(UnmanagedType.LPWStr)]
            public string lpDirectory;
```

I tried just setting the lpFile member to LPWStr, but that seemed to be insufficient.

**Comment by d2phap** [comment]
I also tried declaring the DllImport statement with CharSet.Unicode, but it did not work
