### ISSUE TITLE
always zoom to the monitor size

### ISSUE THREAD

**Issue by ghost** [d2phap/ImageGlass#312]
Hi,

nice program but I miss the option to always zoom to the monitor size (either horizontal or vertical).

There is only the option to lock the zooming or to set every picture to one of two options but I have to do it every time again. No fun while watching a bunch of pictures with different resolutions.

**Comment by d2phap** [comment]
Do you mean `Zoom to fit`?

![image](https://user-images.githubusercontent.com/3154213/36936673-3cd64de4-1f43-11e8-8380-835fc6945488.png)

**Comment by fire-eggs** [comment]
I *think*, reading this multiple times, the request is for the ability to *lock* `scale-to-width` or `scale-to-height`. `zoom-to-fit` can be locked, but the other options are one-shots.

This is a guess, @tkoeck would have to confirm.

**Comment by tkoeck** [comment]
My primary motivation for using the tool is to look at scanned paintings. These pictures often have different resolutions. In that case it would be fine to have an option for automatic zooming to maximum size by preserving the aspect ratio.

Unfortunately my first impression of the tool was that the usability was a little bit hard and I haven't found the options needed to do that.

**Comment by d2phap** [comment]
@ghost

You now can lock any settings in the latest ImageGlass Moon (https://imageglass.org/moon) by create `igconfig.admin.xml` file in the startup folder of IG.

#### Example:
Always start IG in `ScaleToHeight` zoom mode
```xml
<ImageGlass>
  <Configuration>
    <Info description="ImageGlass Configuration file" version="7.5" />
    <Content>
      <Item key="ZoomMode" value="ScaleToHeight" />
    </Content>
  </Configuration>
</ImageGlass>
```
