### ISSUE TITLE
Windows 10 Default App

### ISSUE THREAD

**Issue by Ralms** [d2phap/ImageGlass#313]
ImageGlass is not recognized as a PhotoViewer app for Windows 10 and due to that won't show up in the "Choose default apps" settings.

Request: Have ImageGlass show up in Default Apps for "Photo Viewer" category.

**Comment by d2phap** [comment]
Hi @Ralms 

To add it into default apps list:
- Go to Settings > File Associations
- Click on `Register Extensions` button

You can check out the tutorial here: http://www.imageglass.org/news/how-to-set-ImageGlass-as-default-photo-viewer

Same issue as #129

**Comment by Ralms** [comment]
Ok. 

Why isnt the app registering its support for those file associations by default? 
I doesn't need to be the default app for those file types, but windows should be aware that the app supports it. 

I've opened this request more on the precpective of a non-tech users that just wants something to click and run. 

Just a suggestion to improve User Experience

**Comment by d2phap** [comment]
Thanks @Ralms
