### ISSUE TITLE
"Adjust Window to actual image dimensions" not respecting multiple monitors

### ISSUE THREAD

**Issue by Ralms** [d2phap/ImageGlass#314]
### Expected behavior:
When selecting "Adjust Window to actual image dimensions" it should adjust the window in-place and respect both the location of the window, taskbar and machines with multiple monitors. 

### Actual behavior:
When selecting "Adjust Window to actual image dimensions", the image adjusts the size as expected, but then the window jumps to the primary monitor at the top left corner behind the task bar. Not respecting neither the original location of the window, multiple monitors or the windows task bar. 

### Steps to reproduce:
1. Setup: Triple 1080p monitors with central monitor as primary. Windows Task bars vertical at the left on all monitors.
2. With ImageGlass in window mode (not maximized) on a secondary monitor, select "Adjust Window to actual image dimensions"

### System info:
- ImageGlass version: 4.5.11.27
- OS version: Windows 10 v1607

**Comment by d2phap** [comment]
Thanks @Ralms 
This issue happens when the viewing image dimensions are bigger than screen resolution.
Fixed in `develop` branch. I will upload to http://www.imageglass.org/moon soon
