### ISSUE TITLE
How can i hide my thumbnail filenames?

### ISSUE THREAD

**Issue by mallison424** [d2phap/ImageGlass#315]

**Comment by mallison424** [comment]
![image](https://user-images.githubusercontent.com/37420039/37488970-65ab186c-2853-11e8-8f65-de360533d034.png)

**Comment by d2phap** [comment]
@mallison424 

What version of ImageGlass are you using?
Since v4.0, thumbnail name was removed

**Comment by fire-eggs** [comment]
No response from original reporter within 6 months.
