### ISSUE TITLE
Very high resolution images do not open

### ISSUE THREAD

**Issue by devcompl** [d2phap/ImageGlass#317]
### Expected behavior:
Image is displayed.

### Actual behavior:
ImageGlass shows "ImageGlass cannot open this picture because the file appears to be damaged, corrupted or not supported." error.

### Steps to reproduce:
1. Download any image from [here](https://mega.nz/#F!vohxnZpZ!jWr1i42S-bSpMvRbFYJLfw!28oCHTLS).
2. Open image.
3. ImageGlass shows error.

### System info:
- ImageGlass version: 4.5.11.27
- OS version: Windows 10 1709 (build 16299.309)

### Other info:
This might be a problem with Magick.NET because from my tests it loads the image but fails to convert it to bitmap [here](https://github.com/d2phap/ImageGlass/blob/master/Source/Components/ImageGlass.Core/Interpreter.cs#L102).
The image opens fine in builtin windows image viewer but it does some fancy LOD stuff, full resolution is visible only when zoomed in a lot.

**Comment by d2phap** [comment]
Thanks @devcompl 

The dimension is too big to open with ImageGlass: 30208 x 30208 px.
However, Windows Photos still opens it well.

I'm sorry but I am not going to support for the very big image because of my limited knowledge.
You can use Windows Photos as an alternative.

Phap
