### ISSUE TITLE
Show thumbnails on top or left side

### ISSUE THREAD

**Issue by Keith94** [d2phap/ImageGlass#318]
Currently, thumbnails can be displayed on the bottom (default) or the right side. I'd like to see options for displaying them along the top and left side, too.

**Comment by d2phap** [comment]
Implemented in [v9.0 beta 4](https://github.com/d2phap/ImageGlass/releases/tag/9.0.4.416).
In `igconfig.json`, you can define the layout by `Layout` setting:
```js
// in igconfig.json
{
  "Layout": {
    "Toolbar": "Top;1", // Toolbar is at top, below thumbnail bar
    "Gallery": "Top;0", // thumbnail bar is at top, above the toolbar
    "ToolbarContext": "Bottom", // contextual toolbar is at bottom
  }
}
```
Becomes:
![image](https://user-images.githubusercontent.com/3154213/232105606-92f59212-f6ca-4017-8dab-ad3648f67238.png)

Or this:
```js
{
  "Layout": {
    "Toolbar": "Bottom",
    "Gallery": "Left",
    "ToolbarContext": "Bottom;1"
  },
}
```

becomes:
![image](https://user-images.githubusercontent.com/3154213/232106067-34262952-957e-4f21-b393-f4043cb7b24a.png)


## Note that, the vertical thumbnail bar is currently not resizable.
