### ISSUE TITLE
Color picker doesn't show selected color on first click

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#321]
### Expected behavior:
When clicking to select a color, the color picker should always show the color.

### Actual behavior:
The color picker does not show the color first clicked. 2d and all following color picks show.

### Steps to reproduce:
1. Run Imageglass with color pick on startup.
2. Open an image.
3. Click to select a (non-black) color. Note the topmost bar in color picker is still black.
4. Click again. Topmost bar in color picker now shows the selected color.

### System info:
- ImageGlass version: ImageGlass_Moon 5.0.4.14
- OS version: Windows 10 / Windows 7

**Comment by d2phap** [comment]
This is weird because there is no issue if you just open the tool and wait for few seconds (1 or 2s) then click on the viewing image.

**Comment by fire-eggs** [comment]
OK, I'll dig into it when ImageGlass bubbles up to the top of my stack again.

**Comment by fire-eggs** [comment]
Can't reproduce. Appears to be *bad user on device*.
