### ISSUE TITLE
ImageGlass Moon update checker is broken

### ISSUE THREAD

**Issue by Keith94** [d2phap/ImageGlass#324]
### Expected behavior:
Update checker should look for more recent versions of IG Moon

### Actual behavior:
IG reports that the software is outdated despite not being so

### Steps to reproduce:
1. Download ImageGlass Moon
2. Open update checker

### System info:
- ImageGlass version: 5.0.4.14
- OS version: Windows 10

### Other info:
![image](https://user-images.githubusercontent.com/5490615/38893027-e2e06824-423d-11e8-9c82-a3c1ad1e29c5.png)

**Comment by d2phap** [comment]
Hi @Keith94 
This update feature will check for the stable version only.
Because the Moon version is not stored in database, just directly uploaded to server.

I won't fix this.
