### ISSUE TITLE
Document ImageMagick limitation?

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#329]
After seeing some of my SVG files mis-rendered in ImageGlass, I did some digging.

ImageMagick is confirmed to not support SVG files which use style sheets.

I don't know if this is worth documenting as an ImageGlass limitation, thought I should mention it.

**Comment by d2phap** [comment]
Thanks @fire-eggs
I also realized while opening SVG.  I will add it on IG docs website
