### ISSUE TITLE
Bad layout: Toolbar Settings in Windows 7

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#330]
ImageGlass 5.0.4.x (Moon). Windows 7.

The Toolbar tab in Settings looks like:
![image](https://user-images.githubusercontent.com/9809727/39066172-2fa1cbce-44a2-11e8-8c9a-41c6f009b8b1.png)

Digging into what is going on, it appears on Windows 7, the ListViews are not obeying the size setting. They're expanding to cover the buttons.

I am working on finding a minimal set of changes which allow the tab to work in both Windows 10 and Windows 7.

**Comment by fire-eggs** [comment]
Works OK if Windows 7 is set to 150% font size.

**Comment by d2phap** [comment]
I removed the SplitContainer control to fix this issue.
However, these listviews cannot resize as well but it's still okay :)
