### ISSUE TITLE
Bad Font: Toolbar Settings

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#331]
When I designed the initial version of the Toolbar settings tab, I used the `Wingdings 3` font for the buttons. This font gave us the triangle left/right/up/down symbols.

I set up a vanilla Windows 7 machine to work on issue #330 and have discovered the `Wingdings 3` font is **not** part of Windows 7 ... and probably not Windows 10!  Said font is in fact installed as part of Microsoft Office.

The resulting appearance will be something like:
![image](https://user-images.githubusercontent.com/9809727/39067638-634256ce-44a7-11e8-9a92-40ac3a99e1f4.png)

I can only suggest using the `Wingdings` font, or some other approach, instead of `Wingdings 3`.

I will attempt a more specific solution once Issue #330 is under control.

**Comment by d2phap** [comment]
changed to `Windings` font
