### ISSUE TITLE
Option to always open window maximized. (feature request)

### ISSUE THREAD

**Issue by koscheim** [d2phap/ImageGlass#333]
Hello, 
I am on Win7 and have my images associated with ImageGlass, but always when I 2click any image the IG window opens as default, which is quite small if you have to go through many big images in many folders. I would really love an option to always open maximized, or for the program to remember the last size/position.

If there is such option in windows, I'd be thankful, but I found nothing that would work except the "Ctrl+Shift+Left click close" fix which works only one time, and the "Set your shortcut to do that" fix which is useless for me, as I open files through association, and I wasn't able to associate an extension with a shortcut.

Thanks for creating this great program, hope my is useful.

Edit: (I thought I fixed it but it was just momentary.)
Seems like Maximizing the window and clicking **Ctrl+Left clicking the close button** does not set it as default either... It works if I close it as such and open the same image, but as soon as I open any other image it's small again.

**Comment by koscheim** [comment]
Okay I feel stupid now. 

Seems like Maximizing the window and clicking **Ctrl+Left clicking the close button** does set it as default. No shift involved. Feel free to delete this, I'm dumb :roll_eyes:

**Comment by fire-eggs** [comment]
It is annoying that magic like Ctrl+Left+Close only seems to work reliably on Windows 10.

Can you confirm the issue with ImageGlass 5.0-Moon? (see [downloads](http://www.imageglass.org/moon)).

For me, on Windows 7, ImageGlass 5.0-Moon does remember the last size and position. This even when double-clicking on a file through association.

**Comment by koscheim** [comment]
So. Gathered the few brain cells still alive. I uninstalled all versions and got IG 5.0 extracted.

> Opened program
> Settings
> File Associations 
> selected said extensions
> Set as default
Got the "IG was set as default... successfully!"
But nothing was selected, so I selected again 
> Save
Nothing seems to have happened, if I navigate back to Settings > File assoc., there's nothing selected.
Trying to open anything I got "Error executing program (5)"
Next I tried setting the file associations directly in windows, that finally worked as expected.

In the end: 
Did the Ctrl+Right click trick again which helped. Whenever I open new screen it opens maximized. As with previous version, once I try to open another pic while the program is open, screen gets small again. Everything I open next is also in small screen. 
For now, I got to avoid trying to open something else while it's running.

Good news: While viewing gifs, I am able to use < and > keys with no problem, god fix!

**Comment by d2phap** [comment]
Hi @koscheim 
Are you able to resolve the issue? You can try https://imageglass.org/moon which supports Full screen mode.

**Comment by koscheim** [comment]
Will try, at the time I am using stable IG 5.5.7.26

So far, the issue only appears if I open new instance of the program while another windows i already open, and it opens as not maximized. I just either close it before opening ne one, or drop pictures in thereto load a new set. I guess it's a Win7 issue, hmm...

Will test the Moon when I get time, thanks!

**Comment by d2phap** [comment]
Hi @koscheim 

You now can lock any settings in the latest ImageGlass Moon (https://imageglass.org/moon) by creating a `igconfig.admin.xml` file in the startup folder of IG.

#### Example:
Always start IG in `Maximized` window mode
```xml
<ImageGlass>
  <Configuration>
    <Info description="ImageGlass Configuration file" version="7.5" />
    <Content>
      <Item key="FrmMainWindowState" value="Maximized" />
    </Content>
  </Configuration>
</ImageGlass>
```

**Comment by koscheim** [comment]
Thanks, this works great!
