### ISSUE TITLE
Option to view image EXIF (Feature Request)

### ISSUE THREAD

**Issue by ghost** [d2phap/ImageGlass#336]
Hello,
I am on Windows 7 and have my images associated with ImageGlass, but i can't view image EXIF in ImageGlass. I always work on multiple images and i have to check the EXIF in every image.

Can you add an option like "View Image EXIF" to ImageGlass?

Thanks <3

**Comment by fire-eggs** [comment]
Seems reasonable on first consideration.

In case I'm missing something, let me ask:
1. Is there particular Exif data you're interested in? Camera details, Geocoding, ?
1. Is the Windows Explorer EXIF data enough? You can see that in ImageGlass by right-clicking on your image, selecting Image Properties, then clicking on the Details tab.

**Comment by facoder2k2** [comment]
1. I think, just Camera details and Geocoding is enough. :+1: 
2. Yes, data from Windows Explorer EXIF enough, but i want to see it in ImageGlass (left or right hand-side) for comfortable :100:

**Comment by jeremyml** [comment]
+1

**Comment by lesca** [comment]
+1 
over 2 yrs. I saw many duplicates of this request. 
I believe that to view EXIF is quite important for image viewing. esp. to see the parameters of the camera and the camera model.
With my appreciation if you will add this feature!

**Comment by d2phap** [comment]
I will implement this by using external app: **ExifTool** as mentioned in #751 
This will provide ability to vie, copy, export image metadata.

> An easy way to implement it would be to use the application "command in line" ExifTool by Phil Harvey and show the console output.

**Comment by d2phap** [comment]
Implemented Exif tool in ImageGlass Moon: https://imageglass.org/moon
For more details, check at #871

### Screenshots
![image](https://user-images.githubusercontent.com/3154213/94359917-74f5c100-00dc-11eb-8044-b5d9fc32a518.png)

![image](https://user-images.githubusercontent.com/3154213/94359957-9656ad00-00dc-11eb-8e62-03442c27e158.png)

![image](https://user-images.githubusercontent.com/3154213/94359986-b6866c00-00dc-11eb-8e90-60cb89b968c3.png)
