### ISSUE TITLE
Window State

### ISSUE THREAD

**Issue by smaragdus** [d2phap/ImageGlass#339]
**ImageGlass** version **5.0.5.7**, in contrast with the previous version (**4.5.11.27**) cannot restore window state (non-maximized state) after restart. It seems that the values are saved in the configuration file (**igconfig.xml**) but they are not loaded after restart.

(Windows 8 x64, portable version)

### Expected behavior:
Restore window position after restart

### Actual behavior:
After restart the last used window state 

### Steps to reproduce:
1. Run ImageGlass;
2. Minimize Window;
3. Exit ImageGlass;
4. Restart ImageGlass;

### System info:
- ImageGlass version: 5.0.5.7 (portable)
- OS version: Windows 8 x64

**Comment by d2phap** [comment]
It's fixed in `develop` branch

**Comment by smaragdus** [comment]
@d2phap 
Thanks!

**Comment by smaragdus** [comment]
@d2phap 
Problem really fixed in version [5.1.5.20](https://github.com/d2phap/ImageGlass/releases/tag/5.1.5.20), thanks.
