### ISSUE TITLE
Feature request: Fit image (reduce or enlarge)

### ISSUE THREAD

**Issue by alpinemobile** [d2phap/ImageGlass#34]
As title says it would be nice to Auto Fit Image on window size or fullscreen (reduce large images or enlarge small images).
Also a hotkey 'f' to switch from fullscreen to window would be nice, as alt+enter is annoying.

**Comment by d2phap** [comment]
Hi @alpinemobile 
ImageGlass will open picture and fit it automatically, but small picture size is still kept as default for the best quality.
ImageGlass will provide a customization capabilities for hotkey for a few next releases.
Thanks for your issue :+1:

**Comment by alpinemobile** [comment]
You are correct about the image quality, but I'm not talking about a permanent resize, just a quick (medium quality) way to make the image cover the entire screen. Picture this scenario: image size is 60-80% of the window size (or fullscreen res) and it would be nice to see it larger. I happen to show pictures to an audience and it is awkward to zoom each picture until it covers the whole screen.
Anway, I'd like to thank you for all the efforts made.

**Comment by d2phap** [comment]
Hi @alpinemobile 
Yep, I see. While waiting for any good news from the releases, plz use 'Lock Zoom Ratio' feature to keep the size if you want to zoom at the same level for whole image folder.
Thanks!
