### ISSUE TITLE
When there are 3000+ image files in a folder, if we open any file "Unhandled Exception" error Comes

### ISSUE THREAD

**Issue by mystarsare** [d2phap/ImageGlass#341]
When there are 3000+ .png files in a folder, if we open any file "Unhandled Exception" error Comes.

### System info: inter core i5, 8 gb ram, .NET (updated to latest version)
- ImageGlass version: 5.0.5.7
- OS version: Windows 10Home Single language, 64 bit (Updated to latest version)

### Expected behavior:
I have some folders in which there are too many files. like png, gif, jpg, bmp, txt, word, some other folders. most of them are image files (around 2950+ image files), mostly png & jpg. i have kept ImageGlass as default image viewer for all image files. Normally whenever i open an image file (png/jpg/..) it opens in ImageGlass perfectly.
BUT if I try to open any file from such folder (Which have 3000+ image files in it), an error message comes saying "Unhandled Exception has occured....."
(I have attached full error message at last, see it.)
If I copy that SAME image file in some other folder (where there are not too many other files in the same folder), it opens fine..!
I tried keeping thumbnails On/Off, but problem still occurs.
Please resolve the issue as soon as possible & Provide an update.

### Actual behavior:
if I try to open any file from such folder (Which have 3000+ image files in it), an error message comes saying "Unhandled Exception has occured....."
(I have attached full error message at last, see it.)
If I copy that SAME image file in some other folder (where there are not too many other files in the same folder), it opens fine..!
I tried keeping thumbnails On/Off, but problem still occurs.
Please resolve the issue as soon as possible & Provide an update.

### Steps to reproduce:
1. Create a folder
2. copy 3000+ image files in it (png, jpg,..)
3. try to open any file by double clicking it. (first Make sure that imageglass is default image viewer for such files)
4. you will see an error window with following error message...

****************************************************************************************************************************************************************************************************************************

Copy of ERROR MESSAGE...
![error- imageglass](https://user-images.githubusercontent.com/39171013/39892119-2c66baca-54bd-11e8-8b35-7c4bfa973e4b.png)

****************************************************************************************************************************************************************************************************************************

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at ImageGlass.ImageListView.ImageListViewCacheMetadata.RunWorker(CacheRequest item)
   at ImageGlass.ImageListView.ImageListView.ImageListViewItemCollection.InsertInternal(Int32 index, ImageListViewItem item, ImageListViewItemAdaptor adaptor)
   at ImageGlass.ImageListView.ImageListView.ImageListViewItemCollection.Add(ImageListViewItem item, ImageListViewItemAdaptor adaptor)
   at ImageGlass.frmMain.LoadThumbnails()
   at ImageGlass.frmMain.Prepare(String path)
   at ImageGlass.frmMain.LoadFromParams(String[] args)
   at ImageGlass.frmMain.frmMain_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at ImageGlass.frmMain.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2650.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ImageGlass
    Assembly Version: 5.0.5.7
    Win32 Version: 5.0.5.7
    CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
ImageGlass.Services
    Assembly Version: 5.0.6698.396
    Win32 Version: 5.0.6698.396
    CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.Services.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
ImageGlass.Core
    Assembly Version: 5.0.6698.396
    Win32 Version: 5.0.6698.396
    CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.Core.DLL
----------------------------------------
ImageGlass.Library
    Assembly Version: 5.0.6698.396
    Win32 Version: 5.0.6698.396
    CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.Library.DLL
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
ImageGlass.Theme
    Assembly Version: 5.0.6698.397
    Win32 Version: 5.0.6698.397
    CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.Theme.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
ImageGlass.ImageBox
    Assembly Version: 4.5.0.0
    Win32 Version: 4.5.0.0
    CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.ImageBox.DLL
----------------------------------------
ImageGlass.ImageListView
    Assembly Version: 11.0.0.3
    Win32 Version: 11.0.0.3
    CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.ImageListView.DLL
----------------------------------------
Magick.NET-Q16-AnyCPU
    Assembly Version: 7.4.4.0
    Win32 Version: 7.4.4.0
    CodeBase: file:///C:/Program%20Files/ImageGlass/Magick.NET-Q16-AnyCPU.DLL
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.
![error- imageglass](https://user-images.githubusercontent.com/39171013/39892183-60c7cc46-54bd-11e8-825d-ed17b1e44ca8.png)

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

****************************************************************************************************************************************************************************************************************************

**Comment by d2phap** [comment]
Thanks for the details. This causes by Thumbnail bar.

**Comment by d2phap** [comment]
Hi @mystarsare 
Can you help to try the latest build at: http://www.imageglass.org/moon
I tested in a folder contains 9000+ files. It worked. 

**_Thing to be improved_**: The more files there are, the slower ImageGlass loads.

**Comment by fire-eggs** [comment]
This is related to issue #119 in that the thumbnailbar metadatacache is involved.

**Comment by d2phap** [comment]
@fire-eggs it's weird because with the latest build v5.0.5.11, it works, but the build v5.0.5.7, it doesn't work.
Only difference is we moved the code of loading window position https://github.com/d2phap/ImageGlass/commit/124718d0e5fb6d659275905e72f8fcae253c86cf (?)

**Comment by mystarsare** [comment]
a few more things...

1) When will v 5.0.5.11 be available as stable version (not moon/beta)

2) software generally takes a bit long time compared to other viewers. Can you jiske it a bit faster?

3) people love that Window less look of Picasa image viewer (floating, with transparency), & it was blazing fast. Can you have a settings option for such view (you can also have option to show thumbnail bar in that view).

4) it would be nice if you provide some more image editing options (like xn viewer)

5) we love your clean & neat ui, are you planning for any such video player in future..?

:-)

**Comment by fire-eggs** [comment]
@d2phap :
> @fire-eggs it's weird because with the latest build v5.0.5.11, it works, but the build v5.0.5.7, it doesn't work. Only difference is we moved the code of loading window position 124718d (?)

Yes, it does seem weird. Unfortunately, this may be a thread-safety problem, it will "work" if you don't happen to have any thread collisions. 

The exception thrown happens when code is attempting to update a dictionary from multiple threads, and dictionaries are not thread safe! See  [for instance](https://social.msdn.microsoft.com/Forums/vstudio/en-US/c8a83d23-a62e-4e37-a902-8e229bf3c31f/indexoutofrangeexception-on-genericsdictionaryadd-method?forum=netfxbcl)

I mentioned issue #119 because the call stack above referenced `ImageListViewCacheMetadata`. Since disabling Metadata caching seemed to "solve" issue #119, the same solution "should" fix this issue as well. I haven't had a chance to determine what capabilities are "lost" if Metadata caching doesn't happen.

It'll be moot if the issue doesn't resurface for mystarsare ...

**Comment by d2phap** [comment]
@mystarsare 

> 1. When will v 5.0.5.11 be available as stable version (not moon/beta)

If the build is stable enough for official release, it will push it. Normally it takes a week.

> 2. software generally takes a bit long time compared to other viewers. Can you jiske it a bit faster?

As I mentioned, _The more files there are, the slower ImageGlass loads_. It can be improved.


> 3. People love that Window less look of Picasa image viewer (floating, with transparency), & it was blazing fast. Can you have a settings option for such view (you can also have option to show thumbnail bar in that view).

You can hide toolbar, thumbnail bar of ImageGlass as well. The UI improvement will be considered if it doesn't impact to overall performance. Since the app is written by C# Winform, it's tough to customize the UI.


> 4. it would be nice if you provide some more image editing options (like xn viewer)

ImageGlass is a simple image viewer, people can integrate other editing app via ***Edit Image*** menu.

> 5. we love your clean & neat ui, are you planning for any such video player in future..?

Thanks but no plan yet 😆 


> 6. if we want to browse through images very fast, & we keep on pressing Left/right keyboard button continuously, it goes to only 1 image previous/next. actually it should scroll through images very fast if we continuously press a button.

We provide ***Go To*** function and some shortcuts: `End`, `Home` to help people browse images. Adding "keep on pressing" makes ImageGlass laggy (as of now).

---------

@fire-eggs let's move to #119 for the issue. I will close this issue :)
