### ISSUE TITLE
Switching away from 'large' .GIF files causes program to hang

### ISSUE THREAD

**Issue by spicewitch** [d2phap/ImageGlass#344]
### System info:
- ImageGlass version: 5.0.5.7
- OS version: win7 x64

When viewing and switching between .gif files above a few mb, ImageGlass will hang after pressing the 'next' button, CPU rising to ~25% and usually taking about 10-30 seconds to load the next image but sometimes I just have to close the program. Repeatedly clicking next during this time will advance the images by that many 'nexts' once the lag ends.

This seems strange because the .gif will open relatively quickly, only when clicking away from it does it lag. Even if the next image is only a .jpg or .png it still does this. After repeating the process a few times it generally seems to go a bit quicker though, but still 5-10 seconds.

Larger files seem to produce the issue more, generally above 5mb. <2mb seems fine, biggest I tried was about 15mb. I mostly got ImageGlass (which I otherwise love btw) to easily view .gif files and it is disappointing that opening in a webbrowser is still more effective. Laptop specs are nothing special but should be more than enough to view some gifs especially since these aren't particularly long.. Is there anything that could be done to mitigate this?

P.S. I didn't think it deserved its own issue, but does anyone know if the older themes are compatible with the current version? I tried to install one that said compatibility 1.5 (professional dark) but it gave me errors and I had to reinstall the program. I forgot to save the error message, sorry. If not compatible, why are these still available with no disclaimer?

**Comment by d2phap** [comment]
Hi @spicewitch 

- Did it always happen to all your gif files? Can you try other gif file from internet? (can find some from here: https://dribbble.com/)
- Could you attach your .gif file here?

The theme packs that are compatible with v1.5 don't work in the latest version. (v1.5 vs. v5.0 is too big).
I'm upgrading the new website and will remove (or update) it soon.

**Comment by Meowski** [comment]
I was able to replicate the laggy switching behavior.  To trigger this you need a GIF with a resolution high enough to throttle the UI thread.  

When switching to another image, [this](https://github.com/d2phap/ImageGlass/blob/96d6b13c2139c9bbb5f2d67b715a4a0ea4766007/Source/ImageGlass/frmMain.cs#L404) function is called.  At [this](https://github.com/d2phap/ImageGlass/blob/96d6b13c2139c9bbb5f2d67b715a4a0ea4766007/Source/ImageGlass/frmMain.cs#L421) line the application tries to process the entire message loop but never manages to finish as ImageBox is requesting paint events faster than it can handle, causing an infinite loop.  Removing that line or adding the following to the top of the `NextPic` function did the trick on my machine: `if (picMain.IsAnimating) picMain.StopAnimating();`

Here's the GIF I used.  You might need a bigger one if your machine is faster than mine: [silly.zip](https://github.com/d2phap/ImageGlass/files/2041986/silly.zip)

**Comment by d2phap** [comment]
Thanks @Meowski 
Your suggestion fixed the switching issue.

Btw, the gif file is too large, it causes all the apps i tested (ImageGlass, MS Photos, Firefox, Edge) also hang, only Chrome does not. The CPU usage runs up to 30%.
