### ISSUE TITLE
Add Support for the Windows 10 Timeline

### ISSUE THREAD

**Issue by severen** [d2phap/ImageGlass#350]
Support for showing recently opened images in the Windows 10 timeline feature, as the built-in photos app does, would be a nice feature and bring complete parity with the photos app.

**Comment by d2phap** [comment]
Isn't it supported by default?
In my laptop, I can see the recent photos opened by ImageGlass.

![image](https://user-images.githubusercontent.com/3154213/40490792-1c5d1de4-5f9f-11e8-9093-9fdb86790bda.png)

**Comment by severen** [comment]
I use the installer. I've just gotten in bed, but I can poke around
tomorrow and see if it's working then.

Den fre. 25. mai 2018, 2:24 a.m. skrev Phap Dieu Duong <
notifications@github.com>:

**Comment by severen** [comment]
Ok, it seemed to not work for me because I would open ImageGlass and then drag and drop files into it, rather than opening them directly with ImageGlass.
