### ISSUE TITLE
Do not save automatically!!

### ISSUE THREAD

**Issue by feidaman** [d2phap/ImageGlass#351]
Running v5.1.5.20 (portable).

I've just updated, after a long time sticking with an earlier version. The Delete button on the toolbar is great!!

One thing that used to be very annoying was that, after rotating a picture, rotation would not be saved and users had to click the Save button, and then Save As rather than just overwriting the existing file. The problem with the current version is that it **always** saves automatically. This is not good.  What's needed is two buttons, one for Save, and one for Save As. Furthermore, changes such as rotation should never be saved automatically, but clicking the Save button should save immediately without prompting for a path or filename, just one click, very convenient.

The Ctrl+S command is described as "Convert Image". Why not describe it as "Save" which everybody understands. That's exactly what it does: it saves the image.

**Comment by d2phap** [comment]
> The problem with the current version is that it always saves automatically. This is not good.

There is an option to disable this, but it seems not working (?).
.

> Furthermore, changes such as rotation should never be saved automatically.
> The Ctrl+S command is described as "Convert Image". Why not describe it as "Save" which everybody understands. That's exactly what it does: it saves the image.

Thanks I will improve it accordingly

**Comment by feidaman** [comment]
Thanks! I looked through the settings but didn't find the option.

**Comment by d2phap** [comment]
just fixed the auto-saving issue. You can download ImageGlass Moon: https://imageglass.org/moon.

> I looked through the settings but didn't find the option.

You can go to Settings > Image > Image Editing and uncheck option *Save the viewing image after rotating*
