### ISSUE TITLE
The viewing image is not auto-updated in certain folder

### ISSUE THREAD

**Issue by DatJulian** [d2phap/ImageGlass#353]
Version: 5.1.5.20 (and older)

Steps to reproduce:
1. Load an image
2. Open it in Paint, draw something in it, save
3. Assert that MS Explorer updated the thumbnail with your piece of art
4. Go back to IG
5. F5/Reload hammering
6. Filesize in the title updates (!), picture does not

The picture doesnt get updated after switching to another picture in the bottom navbar, nor does this thumbnail get updated.

**Comment by DatJulian** [comment]
The extension on all the files i tested was .png

**Comment by d2phap** [comment]
Need more information:
- what's the folder path of the image file?
- did you enable "Find images in child folders" option 
- if it is okay, could you send me that png file
Thanks!

**Comment by DatJulian** [comment]
- I experimented a bit with the folder, and it does not seem to have an influence (i tried it at the root of my drive (D:\)).
- No, that is not enabled. Should it be?
- It is just a png with some lines and happens with any file i tested so far, but here you go:
![test](https://user-images.githubusercontent.com/23399687/40885783-7214579e-672d-11e8-84b3-60553f131c5f.png)

**Comment by d2phap** [comment]
Thanks @DatJulian 
I am able to reproduce it.

**Comment by NathanSweet** [comment]
I can confirm the latest (5.1.7.2) auto refreshes, thanks! However, I'm seeing odd behavior for zooming:

1. I run ImageGlass, my image is shown at 70% (which is what I want: scaled to fit in the window but not larger than 100%).
2. The image file is changed externally to a larger size.

**Result:** The 70% zoom is kept and the larger image is bigger than the window.
**Expected:** Zoom to be behave identically to how it did before reloading the file (scaled to fit in the window, but not larger than 100%).

**Comment by NathanSweet** [comment]
Currently reloading stops watching if the file is deleted. It would be nice if ImageGlass would reload if the file later comes back.

**Comment by d2phap** [comment]
Hi @NathanSweet 
There is another issue with auto-updating feature #361 

The correct behaviour should be watching every file created / deleted / modified.
I'm working on this issue

**Comment by d2phap** [comment]
Updated the File Watcher engine, fixed a lot of issues with realtime updating
https://imageglass.org/moon
