### ISSUE TITLE
 Logo For ImageGlass #1

### ISSUE THREAD

**Issue by hawk28** [d2phap/ImageGlass#355]
Hi , I am a graphic designer, I want to help you in graphic design.

After I review your project, you have no logo on this project yet. Therefore I want to contribute to this project by creating a new logo / icons. What do you think?

**Comment by d2phap** [comment]
Thanks @hawk28

The current logo is created by my friend. I think it's quite okay already :)

You can contribute on creating ImageGlass theme. I need some more themes with SVG icons.
Thank you

**Comment by d2phap** [comment]
Close this because no further information
