### ISSUE TITLE
Opening files too fast crashes the program

### ISSUE THREAD

**Issue by B0und** [d2phap/ImageGlass#359]
### System information:
 - Windows 7: 
 - ImageGlass 5.1.5.20: 

### Describe the bug:
I have folder with ~700 pictures in it,
when i open and close different images too fast i get a crash.
Its in russian, but windows shows me this :
  Имя события проблемы:	CLR20r3
  Сигнатура проблемы 01:	ImageGlass.exe
  Сигнатура проблемы 02:	5.1.5.20
  Сигнатура проблемы 03:	5b017cc9
  Сигнатура проблемы 04:	ImageGlass.ImageListView
  Сигнатура проблемы 05:	11.0.0.3
  Сигнатура проблемы 06:	5b017669
  Сигнатура проблемы 07:	f9
  Сигнатура проблемы 08:	c
  Сигнатура проблемы 09:	System.NullReferenceException
  Версия ОС:	6.1.7601.2.1.0.256.1
  Код языка:	1049
  Дополнительные сведения 1:	91ab
  Дополнительные сведения 2:	91ab7ce1e807a9e2c1b1075a9f6d1a68
  Дополнительные сведения 3:	c0f0
  Дополнительные сведения 4:	c0f06a44c9e0c7ab3c4ec018f9bb733e
### Expected behavior:
Just opening the picture

### To Reproduce
1.  Goto folder with 700 pictures
2.  Open file and close it fast
3.  Repeat with different files until crashes

**Comment by d2phap** [comment]
Can you try the latest build here http://www.imageglass.org/moon?

**Comment by B0und** [comment]
Downloaded 5.1.5.24
Same thing,but now i`m getting three different kinds of errors heres the new one :
 Имя события проблемы:	CLR20r3
  Сигнатура проблемы 01:	igcmd.exe
  Сигнатура проблемы 02:	5.0.6718.41872
  Сигнатура проблемы 03:	5b06d720
  Сигнатура проблемы 04:	mscorlib
  Сигнатура проблемы 05:	4.7.3062.0
  Сигнатура проблемы 06:	5ab95381
  Сигнатура проблемы 07:	1679
  Сигнатура проблемы 08:	1d8
  Сигнатура проблемы 09:	System.IO.IOException
  Версия ОС:	6.1.7601.2.1.0.256.1
  Код языка:	1049
  Дополнительные сведения 1:	4def
  Дополнительные сведения 2:	4def3b33d7c7278176a1e1e2092c5cd4
  Дополнительные сведения 3:	5883
  Дополнительные сведения 4:	58837e953ef242778ef3da0d95e2e7c1

And the one before :

Имя события проблемы:	CLR20r3
  Сигнатура проблемы 01:	ImageGlass.exe
  Сигнатура проблемы 02:	5.1.5.24
  Сигнатура проблемы 03:	5b06d810
  Сигнатура проблемы 04:	ImageGlass.ImageListView
  Сигнатура проблемы 05:	11.0.0.3
  Сигнатура проблемы 06:	5b06d41a
  Сигнатура проблемы 07:	fa
  Сигнатура проблемы 08:	d
  Сигнатура проблемы 09:	System.NullReferenceException
  Версия ОС:	6.1.7601.2.1.0.256.1
  Код языка:	1049
  Дополнительные сведения 1:	6bc0
  Дополнительные сведения 2:	6bc0373900025af33ee3431a740b5b5e
  Дополнительные сведения 3:	2fdb
  Дополнительные сведения 4:	2fdb17120da5c4099960459db3d3d460

And the JIT version now pops up :
System.IndexOutOfRangeException: Индекс находился вне границ массива.
   в System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   в System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   в ImageGlass.ImageListView.ImageListViewCacheMetadata.RunWorker(CacheRequest item)
   в ImageGlass.ImageListView.ImageListViewCacheMetadata.Add(Guid guid, ImageListViewItemAdaptor adaptor, Object virtualItemKey, Boolean useWIC)
   в ImageGlass.ImageListView.ImageListView.ImageListViewItemCollection.InsertInternal(Int32 index, ImageListViewItem item, ImageListViewItemAdaptor adaptor)
   в ImageGlass.ImageListView.ImageListView.ImageListViewItemCollection.AddInternal(ImageListViewItem item, ImageListViewItemAdaptor adaptor)
   в ImageGlass.ImageListView.ImageListView.ImageListViewItemCollection.Add(ImageListViewItem item, ImageListViewItemAdaptor adaptor)
   в ImageGlass.ImageListView.ImageListView.ImageListViewItemCollection.Add(ImageListViewItem item)
   в ImageGlass.frmMain.LoadThumbnails()
   в ImageGlass.frmMain.Prepare(String path)
   в ImageGlass.frmMain.LoadFromParams(String[] args)
   в ImageGlass.frmMain.frmMain_Load(Object sender, EventArgs e)
   в System.Windows.Forms.Form.OnLoad(EventArgs e)
   в System.Windows.Forms.Form.OnCreateControl()
   в System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   в System.Windows.Forms.Control.CreateControl()
   в System.Windows.Forms.Control.WmShowWindow(Message& m)
   в System.Windows.Forms.Control.WndProc(Message& m)
   в System.Windows.Forms.Form.WmShowWindow(Message& m)
   в ImageGlass.frmMain.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Загруженные сборки **************
mscorlib
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ImageGlass
    Версия сборки: 5.1.5.24
    Версия Win32: 5.1.5.24
    CodeBase: file:///D:/Program%20Files/ImageGlass/ImageGlass.exe
----------------------------------------
System
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
ImageGlass.Services
    Версия сборки: 5.0.6718.41485
    Версия Win32: 5.0.6718.41485
    CodeBase: file:///D:/Program%20Files/ImageGlass/ImageGlass.Services.DLL
----------------------------------------
System.Windows.Forms
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
ImageGlass.Core
    Версия сборки: 5.0.6718.41484
    Версия Win32: 5.0.6718.41484
    CodeBase: file:///D:/Program%20Files/ImageGlass/ImageGlass.Core.DLL
----------------------------------------
ImageGlass.Library
    Версия сборки: 5.0.6718.41484
    Версия Win32: 5.0.6718.41484
    CodeBase: file:///D:/Program%20Files/ImageGlass/ImageGlass.Library.DLL
----------------------------------------
System.Xml
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
mscorlib.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
ImageGlass.Theme
    Версия сборки: 5.0.6718.41485
    Версия Win32: 5.0.6718.41485
    CodeBase: file:///D:/Program%20Files/ImageGlass/ImageGlass.Theme.DLL
----------------------------------------
System.Configuration
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
ImageGlass.ImageBox
    Версия сборки: 4.5.0.0
    Версия Win32: 4.5.0.0
    CodeBase: file:///D:/Program%20Files/ImageGlass/ImageGlass.ImageBox.DLL
----------------------------------------
ImageGlass.ImageListView
    Версия сборки: 11.0.0.3
    Версия Win32: 11.0.0.3
    CodeBase: file:///D:/Program%20Files/ImageGlass/ImageGlass.ImageListView.DLL
----------------------------------------
System.Windows.Forms.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
Magick.NET-Q16-AnyCPU
    Версия сборки: 7.4.6.0
    Версия Win32: 7.4.6.0
    CodeBase: file:///D:/Program%20Files/ImageGlass/Magick.NET-Q16-AnyCP

**Comment by B0und** [comment]
Forgot to mention that the "igcmd.exe" error doesnt actually crash the program, it still opens the picture and after closing the error window everything is fine.

**Comment by d2phap** [comment]
hmm, i have a folder with 7000 image files, but there is no issue...

**Comment by fire-eggs** [comment]
Sorry for being late.

A suggestion: if you haven't already, try turning ON 'allow multiple instances'. And turn OFF 'check for update'.

I will try to repro as soon as my system comes back up.

**Comment by fire-eggs** [comment]
This is a tricky one. I've repro-ed the `NullReferenceException` and the `IOException` each *once*. Not the `igcmd.exe` one tho. This is with the absolute latest-and-greatest, post 5.1 code.

My settings don't seem to make a difference - multi-instance, hidden images, child folders, etc. It is just plain difficult for me to repro.

I'll add some diagnostics and keep trying.

There is one possibly relevant issue I've been aware of. There is a background thread that runs to process thumbnails and collect image metadata. This background thread will keep running __even after__ the main program is exited. In this situation, what could happen is said background thread is still running after you open-and-close IG to show image 'x', and subsequently gets confused when IG is opened to show another image.

Also, a quick glance at the `ImageListViewCacheMetadata` code suggests it is not thread-safe, which I think could explain the `IndexOutOfRangeException`.

[So of course after typing all this, now IG is crashing repeatedly, with an image folder containing 15,000 files and no child folders.]

**Comment by B0und** [comment]
Thanks for answer, i turned OFF "allow multiple instances" and now i am not getting "igcmd.exe" error, and only the other two are still there.

**Comment by fire-eggs** [comment]
I checked in some changes which appear to solve the crashes for me (except the igcmd which I've not seen yet). Hopefully @d2phap can make a new IG-Moon release soon so you can give it a try.

My thanks for the reports and your help in pounding on this ...

**Comment by d2phap** [comment]
Thanks. I uploaded IGMoon v6 https://imageglass.org/moon
@B0und can you help to test?

**Comment by B0und** [comment]
Wow, well that was quick. No more crashes for me, nice job there ! 
Just wanna add that i really like ImageGlass, keep up the good work !

**Comment by d2phap** [comment]
Thanks for confirmation!
