### ISSUE TITLE
Remove social media plugins from the program

### ISSUE THREAD

**Issue by Dol-phin** [d2phap/ImageGlass#36]
When viewing an image, there's an option to "upload to Facebook" in the context menu and in the taskbar. I doubt that anyone really wants social media features, we have ShareX for that purpose.
I suggest you to either remove the item completely or at least as an optional addon to the installer.

![glasspng](https://cloud.githubusercontent.com/assets/11059234/9084104/adc88f46-3b78-11e5-838e-6713c0504c16.png)

**Comment by d2phap** [comment]
Hi @Dol-phin 

In a few next releases, I will move some features of ImageGlass to plugins / extensions, include Social features.

**Comment by raydric** [comment]
@d2phap any news on this? I'm still seeing Facebook on the 3.5, so I'm currently deleting the DLL from the folder just to make sure I don't misslick on the icon. Please don't add any network calls that aren't opt-in or that can be triggered by missclicking (on a UI button).
