### ISSUE TITLE
Attempting to access missing drive

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#360]
### System information:
 - Windows OS version: Windows 7
 - ImageGlass version: V5.1+

### Describe the bug:
"ImageGlass.exe - No Disk" dialog box appears repeatedly.

IG will bang on a dismounted drive. May require problem images which IG won't load.

### Expected behavior:
Once a disk has been dismounted, IG should fail to find it silently.

### To Reproduce
1.  Have a dismount-able drive mounted, e.g. a DVD in drive.
2.  Run IG. View images. May require 'error' images.
3.  Dismount drive (e.g. eject DVD).
4.  Try to view images. Said dialog box (trying to access drive D:) appears repeatedly.

Most noticeable when thumbnails are viewed: appears to attempt to access drive D: twice for each failed thumbnail image. App freezes while dialog box is shown.

Seems to happen even if IG is shut down after dismounting drive D:. Running again, attempts to access drive D:.

Is "disk watch" not being intelligent about missing devices?

### Screenshots:
Dialog references drive D: but note no drive D: active in Explorer.
![image](https://user-images.githubusercontent.com/9809727/41483358-d56762c8-70a6-11e8-9760-d1dceef154f9.png)

**Comment by kristixx** [comment]
Still happens it's annoying.

**Comment by fire-eggs** [comment]
Yup, it certainly is annoying!  Thank you for the comment - I'll integrate the change.

**Comment by d2phap** [comment]
Available in the latest IG Moon https://imageglass.org/moon

**Comment by fire-eggs** [comment]
As far as I've been able to determine, this is a system configuration issue and not caused by something IG is doing "wrong". But the fix is still necessary as the system configuration issue may be difficult to diagnose or fix.
