### ISSUE TITLE
Moving images out of the current folder does not update file list

### ISSUE THREAD

**Issue by UncleClapton** [d2phap/ImageGlass#361]
### System information:
 - Windows OS version: Windows 10 Pro (Insider Preview Build 17686)
 - ImageGlass version: 5.1.5.20 (also tested in Moon 6.0.0.0)

### Describe the bug:
When an image is moved out of the current folder, the file will remain in the file list.

I **have** been able to get some files removed from the list if I move multiple images in a single batch move, but it is very inconsistent.

### Expected behavior:
When a file is moved out of the folder, the image list is updated to reflect the new state of the folder.

### To Reproduce

1. Open image
2. Go to next image in folder
3. move first image
4. Go to previous image. Previous is the same image as before instead of the new previous image in the folder.

### Additional context:
I've been using ImageGlass to help me sort out a large collection of photos that has just ended up unsorted out of laziness. These issues with keeping ImageGlass in sync with the file system has made it inconvenient to use for sorting large collections like this.

**Comment by d2phap** [comment]
Thanks @UncleClapton 
The `FileSystemWatcher` of .NET is buggy.

**Comment by UncleClapton** [comment]
@d2phap I wondered if it was FSW. I've had my own issues with it in the past as well 😞. Thanks for the update, and all the work you do!

**Comment by d2phap** [comment]
Hi @UncleClapton 
Yes the FSW is.

There are multiple events triggered when you update a file.
- Moving a file will trigger `delete` and `change` event
- Updating a file will trigger `delete` and `create` event or `change` and `change` event
- Creating new file will trigger `create` event
- Deleting a file will trigger `delete` event

You can see there are many duplicated events, so ImageGlass needs to wait for few milliseconds to listen to the next event. The bigger file the longer duration. This will make the file list not updated correctly.

I'm working on an alternative FSW library. I will update on this issue soon.

**Comment by d2phap** [comment]
The issue was fixed.
Please try the latest build at https://imageglass.org/moon

**Comment by fire-eggs** [comment]
> Am I just going blind in my old age? :)

No, I don't think so! :)  Moon 6.0.0.0 has evolved, transmogrified, morphed, what-have-you.

@d2phap has mentioned in the Google group (https://groups.google.com/forum/#!forum/imageglass)  about a problem with the ISP hosting imageglass.org . I believe it means he has been unable to update the stable release there, so it is stuck at 5.1.5.20. 

The absolute latest stable release is **5.5.7.26**, which can be downloaded from Github:

https://github.com/d2phap/ImageGlass/releases

This issue has been addressed in 5.5.7.26. Please give it a try! Earlier ImageGlass Moon releases are obsolete.

So its no wonder you're confused! Hopefully the problems on imageglass.org can be rectified soon.
Kevin

**Comment by d2phap** [comment]
Hi,

I have prepared the v5.5 release but the server from Hongkong was down at the last minutes. Currently i'm on vacation.

I will be back on Sunday.
Thannks

**Comment by CollinChaffin** [comment]
You're missing my point.  Version 6 comes after 5, and how is v6 been on my desktop for a month and was pulled?  I downloaded it from your site, then you pulled it.  Clearly from Github I can see v6 is the next version so I'll ask another way - was v6.0.0 found to be so problematic that it was pulled and I should NOT be running it, or ?

Yes, I'm fully aware of what is NOW listed as "stable" and "moon" - neither of which is in the v6 level and it was a month ago (moon).  TIA!

**Comment by d2phap** [comment]
Hi @CollinChaffin 

> Version 6 comes after 5, and how is v6 been on my desktop for a month and was pulled? I downloaded it from your site, then you pulled it. Clearly from Github I can see v6 is the next version so I'll ask another way - was v6.0.0 found to be so problematic that it was pulled and I should NOT be running it, or ?

Yes you should run the v5.5. That's the latest stable version.
v6 is a very early build, it contains new changes that not in v5.5. However, that very early build of v6 doesn't include the bug fixes of v5.5. That's why i removed it. 

The next stable version may be v6 if there is no major bugs of v5.5

Close this issue because the bug was fixed
