### ISSUE TITLE
First-launch configurations

### ISSUE THREAD

**Issue by werkheim** [d2phap/ImageGlass#365]
Hello

Is it possible after the Installation from ImageGlass with the Registry Settings to stop the First-launch configurations Window to open?
When yes, which key is it.
I tried also to push the Language to change to German with Registry Settings, but dont work. It starts with the First launch and when I cancel that it stays in English.

Any Help would be very appreciated.
Thank you
Torrdan

**Comment by d2phap** [comment]
Hi @werkheim,

You can create key `FirstLaunchVersion` = `5` in registry 
`Computer\HKEY_CURRENT_USER\Software\PhapSoftware\ImageGlass`

If you are using portable version, look for `igconfig.xml` file, add this line
```xml
<Item key="FirstLaunchVersion" value="5" />
```

Merge duplicated to #346

**Comment by d2phap** [comment]
To install new language pack, you can copy the `*.iglang` to `\Languages\` folder.
Then open Settings > Languages, select your language pack.


To set it via registry / config file:
```xml
<Item key="Language" value="path_of_iglang_file" />
```

**Comment by werkheim** [comment]
Hi d2phab

Thanks for youre fast answer.
I tried with the FirstLaunchVersion = 5, but the First Launch Starts anyway.
Any Ideas?
The Installation of the Language Pack I did it like you have written before.
But it dont works for me.

I use Windows10 and took all the RegKeys from my Installation.
I have a Installation Tool that works fine with /versilent Switch.
Then I wait for 30sec. 
copy the .lang file to the \Languages folder
and put all the reg keys into the ImageGlass Registry folder

Greetings Torrdan

**Comment by d2phap** [comment]
Is your OS 32bit or 64bit? 
it's reported that this issue happens on 32bit OS #346

**Comment by werkheim** [comment]
My OS is 64bit

**Comment by d2phap** [comment]
I still cannot reproduce the issue, need more info:
- What is your installed folder?
- After you finish the first-launch steps, can you help to check in Registry and Config file if `FirstLaunchVersion` (or `ToolbarButtons`, `Theme`, `Language`) is written? (don't close the app yet)

Thanks!

**Comment by d2phap** [comment]
Hi @werkheim 
The issue was fixed.

Can you help to test the latest build and confirm?
https://imageglass.org/moon

Thanks
