### ISSUE TITLE
Next & previous image arrow relocation

### ISSUE THREAD

**Issue by WendlerTech** [d2phap/ImageGlass#367]
I'd love to see the next/previous image arrows be relocated to the right & left of each image. I like keeping the mouse scroll wheel as zoom, but it seems inconvenient to have to move to the top left corner to click the tiny icons to switch between images. The keyboard shortcuts are handy, but sometimes you just want to browse using the mouse.

**Comment by d2phap** [comment]
I think it will be annoying when users pan the image because they might accidentally click on the arrow button.

**Comment by WendlerTech** [comment]
Really? What about if the arrow doesn't permanently linger, but instead appears after hovering over the edge for a second? Also, make them wide, so they're visible & obvious. It also wouldn't be too hard to give users the option to use either the new feature or revert back to the buttons at the top.

**Comment by fire-eggs** [comment]
Merged into issue #448
