### ISSUE TITLE
Adapting window to image (Ctrl+M) makes the window go off screen in Windows 10

### ISSUE THREAD

**Issue by BowChow** [d2phap/ImageGlass#37]
And can't move the window. Restarting doesn't fix it.

![image](https://cloud.githubusercontent.com/assets/6789738/9156174/5a1385f2-3ed1-11e5-8946-a72837f9e6e3.png)

**Comment by d2phap** [comment]
Hi @BowChow 
This issue was fixed by the 91th commit.
Thanks!
