### ISSUE TITLE
crash deleting image

### ISSUE THREAD

**Issue by NathanSweet** [d2phap/ImageGlass#373]
1. Run Image Glass on Windows 10, open a GIF image.
2. Delete image using File Explorer.
3. Got dialog showing crash information: http://n4te.com/x/30-EQJS.txt
Image Glass showed: http://n4te.com/x/31-Ovpa.png

Most times when deleting the image that Image Glass has open, it does not crash like this, so it seems there is some race condition. At any rate, Image Glass should probably handle this exception silently, as it does when loading an image with errors, or an image that is still being written.

**Comment by fire-eggs** [comment]
Yup, you found a new one! Looks like the GIF animation code doesn't like having its image deleted out from underneath ...

**Comment by fire-eggs** [comment]
I'm not able to reproduce the issue - but your post suggests it doesn't happen all the time? 32 bit or 64 bit Windows?  Is the GIF file in question a large file? Delete permanently or to Recycle bin?

I'll look into grabbing this exception anyway ...

**Comment by NathanSweet** [comment]
It happens rarely, only once in fact and I've been working with GIFs a lot over the past few days. It was 64-bit Windows 10. I don't recall the size of the GIF, but most GIFs I write are ~1.5MB+, up to 15MB or so. Deletion was to the recycle bin. I know it sucks, but probably it's sufficient to handle the exception with a repro. Thank you for your effort!

**Comment by NathanSweet** [comment]
Yep, I've been running 5.1.7.15 since yesterday, thank you! I'll post here if it happens again, otherwise I think this issue can be closed.

**Comment by d2phap** [comment]
thanks :)
