### ISSUE TITLE
checkered background is too small on 4K

### ISSUE THREAD

**Issue by philiparvidsson** [d2phap/ImageGlass#374]
### System information:
 - Windows OS version: 10 (1803)
 - ImageGlass version: 5.1.5.20 [Portable]

### Describe the bug:
The checkered background is too small on 4K screens.

### Expected behavior:
The checker background should be scaled according to Windows display settings.

### To Reproduce
1. Buy a 4K monitor
2. Connect it to your computer.
3. Start ImageGlass.
4. Enable checkered background.

### Screenshots:
![image](https://user-images.githubusercontent.com/1163299/42566845-273f8b64-8508-11e8-9f3b-b24d7c2e4eb3.png)

### Additional context:
n/a

**Comment by d2phap** [comment]
Hi @philiparvidsson 
Thanks for the issue.

I need some more information:
- What is your screen DPI? You can check by open `Windows Settings` > `System` > `Display`, scroll to the `Scale and Layout` section.

Thanks

**Comment by philiparvidsson** [comment]
@d2phap 

I will check ASAP (not currently at that computer). It's a Dell U2718Q monitor, 27-inch 4K panel with scaling set to 200% in Windows.

**Comment by d2phap** [comment]
Thanks, I will add this feature in the next release

**Comment by d2phap** [comment]
Hi @philiparvidsson 
Your feature request was implemented. 
The size of grid will be auto-adjusted by DPI scaling number.

You can try the latest build `5.1.7.18` here: https://imageglass.org/moon

**Comment by philiparvidsson** [comment]
@d2phap, that's great. Did you also adjust the size of the image according to DPI scaling? 100% zoom should also be scaled according to DPI, otherwise 100% zoom will look tiny on high DPI monitors. I.e., not only the background should be scaled, but also the image.

**Comment by d2phap** [comment]
The image size cannot be adjusted. It will be blurred, and the viewer should respect the actual size of image.

One example, you can compare the png image by Google Chrome and ImageGlass to see the differences.

**Comment by philiparvidsson** [comment]
@d2phap you should have a look at how windows photos app does it. it doubles the pixel size if dpi scaling is set to 200% to keep the image the same size on the screen.

**Comment by d2phap** [comment]
Hi @philiparvidsson
Sorry but that is the big problem of Windows Photo app.

Reddit users complain its blurry issue.
PNG/JPG... are not like vector format, it's pixel-based rendering.

**Comment by philiparvidsson** [comment]
just tried the new version - great job!
