### ISSUE TITLE
ImageGlass crash on launch

### ISSUE THREAD

**Issue by avi-iz** [d2phap/ImageGlass#380]
### System info:
- ImageGlass version: 5.1.5.20
- OS version: WIN10

### Expected behavior:
double click image, image glass launches and displays the image

### Actual behavior:
if there are many images in the folder, then imageglass launches for less than a second, then closes by iteself (i.e. crashes). no error is displayed.
if i wait a while and try again sometimes imageglass launches properly.

### Steps to reproduce:
1. create a folder with ~2000 images
2. set ImageGlass as default image viewer
3. double click image

### Other info:
my images are roughly 500x300 pix. in PNG format (~100kb each)

**Comment by d2phap** [comment]
Hi @avi-iz

This may be a duplication of #341

Can you try the latest build https://imageglass.org/moon?

Thanks

**Comment by avi-iz** [comment]
yes, the latest build seems to fix the issue.
thanks
