### ISSUE TITLE
Viewing next/prev images in rapid succession with mouse causes undesired 1:1 zoom

### ISSUE THREAD

**Issue by NightJar** [d2phap/ImageGlass#387]
### System information:
 - Windows OS version: 10 - 1803
 - ImageGlass version: 5.1.5.20 stable & moon 5.1.7.18

### Describe the bug:
When browsing images with the back or forward mouse buttons, if the image is larger than the view area a double click can register; zooming the image to 1:1

### Expected behavior:
Clicking the browse forward or back button on my mouse should always simply cycle to the next or previous image with each single click, no matter how many times or how rapidly it is pressed.

### Minimal steps to Reproduce
1. Download ImageGlass Moon 5.1.7.18, extract the archive, and browse into the new folder
2. Copy and paste the `default.jpg` (so there is also `default - Copy.jpg`)
3. Open ImageGlass in this folder with `ImageGlass.exe` and ensure the view area is smaller than the `default.jpg` image size by double clicking (ensure the image 'zooms' to a 1:1 ratio, and resize window smaller if not)
4. Cycle the images by clicking the forward button on the mouse with a pause between each click
5. Observe normal behaviour (window title renames appropriately)
6. Increase to a rapid speed of clicking the forward button (as if scanning through a large library for a particular photograph)
7. Notice an image will first zoom to 1:1 ratio before moving to the next image (on 3rd click). This behaviour is as if I were first using a double click (left/main mouse button) before then clicking the forward mouse button.

Alternatively if one has a library of modern digital camera photographs this should also be sufficient to replicate the issue in a more obvious manner (as the images won't both be the same).

**Comment by fire-eggs** [comment]
This should no longer be possible with IG 6.0.12.29 and later.  IG was changed to ignore mouse / key presses during the time that an image is loading, which should prevent these "extra" double-clicks from happening.

**Comment by LunaAshai** [comment]
This issue shouldn't be closed since it isn't fixed. Changing IG to ignore mouse/key presses during image loading just makes it so the next image will get zoomed in when you press a mouse button again.

What happens now is this:
1. IG registers that mouse4 was pressed, so it displays the previous image, but also registers mouse4 as a left click to zoom in.
2. Pressing mouse4 again to display the next previous image will not display the previous image. Instead it is registered as double click to zoom.

I recommend running a check with the zoom function to make sure that if it is mouse4/5 then it won't register it as a left click.

**Comment by norms360** [comment]
Same problem here.  ImageGlass is by far the best lightweight Image Viewer!  Looking forward to this little annoying bug being fixed as I perform these actions quite a lot :-)

**Comment by ziixi** [comment]
I'm also still having this issue even after updating to version 7.0.7.26.

**Comment by NightJar** [comment]
> I'm also still having this issue even after updating to version 7.0.7.26.

I have also confirmed this.

**Comment by d2phap** [comment]
Thanks @LunaAshai for the fix.
It's shipped to https://imageglass.org/moon

**Comment by Zerowalker** [comment]
wow, lucky i saw this, i was just writing about it, and noticed it was only the mouse so i thought,
damn no way i am going to be able to explain this well enough lol.
Then when i wrote about the 1:1 (or i wrote 1x1 lol) i saw this, phew!

I am on Windows 10 x64, build is 7.0.7.26.

If it's supposed to be fixed (can't really tell?) it's sadly not if i haven't missed something.

**Comment by NightJar** [comment]
@Zerowalker the issue still exists in `7.0.7.26`.
The issue is fixed in the next release, as can be experienced with the [`moon` preview version](https://imageglass.org/moon), currently version [`7.0.8.5`](https://imageglass.org/upload/moon/ImageGlass_Moon_7.0.8.5.zip).

```ImageGlass_Moon_7.0.8.5.zip
Size: 14.36 MB
Release date: Aug 5 2019 11:42 PM```

**Comment by Zerowalker** [comment]
Ah, splendid:)
