### ISSUE TITLE
Remember zoom position for a small period of time

### ISSUE THREAD

**Issue by Seneral** [d2phap/ImageGlass#388]
### Is your feature request related to a problem? Please describe.
When comparing pictures on a per-pixel level you have to zoom in on both images and ideally are able to directly switch between them for perfect comparison. This is currently not possible as the zoom resets to standard values immediately.

### Describe the solution you'd like
I would like the viewer to remember a zoom value per image for a few seconds or for immediate neighbours. Say you zoom in on this image, switch to the next one, and when you come back shortly after it is still zoomed in on the same position. 
Criteria for remembering zoom could be: Did not go farther than two neighbouring images before returning / did not take a look at other images for more than 10 seconds.

### Describe alternatives you've considered
Creating two seperate windows where you can take your time to position both images and switch between those windows for comparison.

### Additional context
Very low priority obviously, as an alternative exists, although I'd very much like to see it.

**Comment by d2phap** [comment]
Hi @Seneral 
Is this Lock Zoom Ratio option, you mean?
With Lock Zoom Ratio, you can view all images with the same zoom value

**Comment by Seneral** [comment]
Thanks for the response, appreciated it.
That only saves the ratio, but not the individual zoom position, so it will always return to the top left corner when switching between images.
Ideally it would also save the zoom position for each image seperately, since for photographs you would need to compare slightly different viewpoints.
Hope I got the point across.

**Comment by xdkaplan** [comment]
Hi @d2phap I want to share my interest in this feature for the reasons mentioned above. For photography and other uses, in my personal use and work I often want to switch between multiple images without resetting the zoom position.

**Comment by Unknow0059** [comment]
@fire-eggs Issues #388, #486 and #795 are the same. I suggest that they be merged.

**Comment by d2phap** [comment]
Please prefer to #795 for future update.
Thanks @Unknow0059
