### ISSUE TITLE
[Suggestion] Tool to easily crop images

### ISSUE THREAD

**Issue by BowChow** [d2phap/ImageGlass#39]
Like this:

![image](https://cloud.githubusercontent.com/assets/6789738/9156263/5fb36484-3ed4-11e5-922d-9ed83f3c9312.png)

**Comment by d2phap** [comment]
Hi @BowChow 

I will release an Crop tool extension for ImageGlass. I won't intergrate it because ImageGlass is a simple photo viewer, not an photo editors.

**Comment by BowChow** [comment]
I agree :-) Looking forward to it.

**Comment by geometrikal** [comment]
Did you implement the crop feature?

**Comment by d2phap** [comment]
I won't implement this because the extension manager feature will be removed in the next version.
For cropping, user can use 3rd party tool

**Comment by elig0n** [comment]
If there's flip and rotate why not crop ? It's only reasonable to have a selection when there is copy/cut/paste

**Comment by anewuser** [comment]
@elig0n  try https://github.com/nomacs/nomacs#links
