### ISSUE TITLE
Please add multiple folder sources so you can load photos in the same session from multiple folders (and their subfolders)

### ISSUE THREAD

**Issue by mathkkad** [d2phap/ImageGlass#391]
Please add an option to load photos from multiple folders (and their subfolders) in one session.

Basically load photos from Folder 1, load from Folder 2, and so on and all the photos from these folders can be seen one after the other in the same session.

I really like and appreciate this software but unfortunately it lacks this basic option to load photos into it (from multiple folders). Since it is a photo viewer it would be appreciated to load photos in it from a couple of folders at once.

Hope this can be implemented soon as in my opinion is the only thing missing for a great experience

Thank You

**Comment by 14m3l1t3** [comment]
> Is this feature available? If it is, how can I do it, I cant find solution.

**Comment by d2phap** [comment]
@14m3l1t3 you can drag and drop multiple files/folders to the viewer

**Comment by 14m3l1t3** [comment]
> @14m3l1t3 you can drag and drop multiple files/folders to the viewer

Thanks! I was watching in options to load, but couldn't find a thing, didn't cross my mind to drag and drop... And by the way thanks for greatest viewer ever! Cheers!
