### ISSUE TITLE
Absolute paths in igconfig.xml make ImageGlass not portable

### ISSUE THREAD

**Issue by taroxd** [d2phap/ImageGlass#392]
### System information:
 - Windows OS version:  10.0.17134.191
 - ImageGlass version: 5.5.7.26

### Describe the bug:
Copy the portable version from one PC to another, and the language/theme settings are lost. 

### Expected behavior:
These settings should be portable.

### To Reproduce
See "Describe the bug" section.

### Screenshots:
Not required.

### Additional context:
Not required.

For the portable version of ImageGlass, it may be preferable to store the `Language` and `Theme` in `igconfig.xml` as relative path when the corresponding files are inside the root folder of the application.

**Comment by d2phap** [comment]
This issue is ready for testing, download here: 
https://imageglass.org/moon
