### ISSUE TITLE
Automatic resize window on file open [New feature/option]

### ISSUE THREAD

**Issue by SylwesterZarebski** [d2phap/ImageGlass#393]
### Is your feature request related to a problem? Please describe.
When i open image with different size than previous, window size stays the same and image is scaled (or not, depending on other options)

### Describe the solution you'd like
Window should be resized to image size - up to screen size, then scaled to fit to screen.

### Describe alternatives you've considered
I have to use <kbd>CTRL+M</kbd> after opening every image.

### Additional context
None.

**Comment by d2phap** [comment]
Hi @SylwesterZarebski 
What is this feature used for?

**Comment by d2phap** [comment]
Thanks for the information.

**Comment by d2phap** [comment]
- Implemented in the new window mode, called: `Window fit (F9)` (its former name is Adapt window to image - `Ctrl+M`).
- User can combine with `Frameless (F10)` mode to make it cooler!

Try the latest build: https://imageglass.org/moon

**Comment by SylwesterZarebski** [comment]
Thanks a lot, working perfectly.
