### ISSUE TITLE
when mouse move on manipulation must click other in menu

### ISSUE THREAD

**Issue by Mar24th** [d2phap/ImageGlass#394]
### System information:
 - Windows OS version: Windows 10 1607
 - ImageGlass version: 5.5.7.26

### To Reproduce
1. 
2. 
3. 
4.

**Comment by d2phap** [comment]
Note:
Maybe it's due to the disabled text customization(?)

https://github.com/d2phap/ImageGlass/blob/90956ece019cdf1c70e4c283b67f94189c23bcad/Source/Components/ImageGlass.Theme/ModernMenuRenderer.cs#L40-L66

**Comment by fire-eggs** [comment]
Confirmed and fixed.
