### ISSUE TITLE
Panning on large images is noticably sluggish compared to W10 Photos app

### ISSUE THREAD

**Issue by wisteso** [d2phap/ImageGlass#395]
### System information:
 - Windows OS version: Windows 10
 - ImageGlass version: 5.5.7.26

### Describe the bug:
When viewing a large image (16000x1300 in this case) the application becomes pretty sluggish when panning. This is not a problem with system capability, since the default Windows 10 photo viewer has no problems doing the same.

I would suspect it might be due to missing hardware acceleration, but there is no option in the settings to configure such a setting.

### Expected behavior:
Smooth panning at any zoom level across the image.

### To Reproduce
1. Load a large enough image on a mid-range system (i7 laptop in this case)
2. Zoom in and attempt to pan across the image
3. Notice the panning is noticeably sluggish compared to baseline of Windows 10 Photos application

### Screenshots:
N/A

**Comment by Keith94** [comment]
I can confirm it, too. See #272

**Comment by d2phap** [comment]
Thanks @wisteso 
However, this is duplicated of #272.
16000x1300 is too large for ImageGlass until I can find the way to deal with it.
