### ISSUE TITLE
APNG support

### ISSUE THREAD

**Issue by sorat0mo** [d2phap/ImageGlass#396]
It was like versions ago this feature was suggested. And it is **still** not yet implemented. I would very much like seeing apng supported in imageglass. This is what I would like to see!

**Comment by Keith94** [comment]
How common are APNG files anyway? I rarely see them since WEBM became a thing.

**Comment by thisiskarsten** [comment]
If you record animated pictures with Screen2Gif you would want to use apng sometimes. At least for me.

**Comment by AestheticPerfection** [comment]
Still nothing on APNG support?

**Comment by fire-eggs** [comment]
Internal note:  ImageMagick does not support APNG, because: libpng does not support APNG.

We'll have to introduce a new library to be able to support animated PNG.

**Comment by s8321414** [comment]
For APNG support, I will suggest https://sourceforge.net/projects/libpng-apng/

**Comment by fire-eggs** [comment]
Thanks for the tip!

**Comment by unquietwiki** [comment]
Looking through the 7.7. tickets, I saw this chain of issues. I might try https://github.com/jz5/APNG.NET with this @fire-eggs @s8321414

**Comment by tayflo** [comment]
Hi there. I had never encountered animated `.png` before, but recently came across this format as Discord implemented stickers, supporting only `.png` and `.apng` files.
Since ImageGlass is the ultimate pictures viewer for Windows in my eyes, it would be cool if APNG were also supported.

I also noticed that an APNG file can end with both `.png` or `.apng` extension. Cheers!

**Comment by Eneocho** [comment]
Any updates if this could be implemented? I have a ton of apngs that I have to open separately.

**Comment by Setsu-BHMT** [comment]
I just found out that imagemagic supports apng, could this be used instead of libpng?

**Comment by dlee13** [comment]
https://imagemagick.org/script/formats.php#supported does list APNG as supported now

**Comment by Infinitay** [comment]
Is there any plans to include animated support for apngs? Currently it only shows a static image instead of the animation

**Comment by d2phap** [comment]
Implemented in [v9.0 beta 4](https://github.com/d2phap/ImageGlass/releases/tag/9.0.4.416). The extension must be `.apng`.

**Comment by Eneocho** [comment]
nice

**Comment by d2phap** [comment]
With [ImageGlass 10.0.4.819](https://github.com/d2phap/ImageGlass/releases/tag/10.0.4.819), you can just install [APNG codec plugin](https://imageglass.org/plugins), it can handle both .PNG and .APNG

**Comment by Infinitay** [comment]
Thanks for implementing this. Out of curiosity, was there any reasoning on adding support for apngs as a plugin rather than natively support it?

**Comment by d2phap** [comment]
@Infinitay Magick.NET does not natively support APNG, I need another library (APNG.NET) to decode it. To add a new library, I need to consider about the security. Magick.NET is well-maintained but APNG.NET is not, the repo has been archived for long time. I am not aware of any issues for now, but it's safer to be separate as a plugin.

**Comment by Infinitay** [comment]
Got it. Thanks for the information!
