### ISSUE TITLE
Renaming files on network

### ISSUE THREAD

**Issue by ChewieChewbacca** [d2phap/ImageGlass#397]
### System info:
- ImageGlass version: 5.5.7.26
- OS version: Windows 10

### Expected behavior:
Press F2 to rename file. Enter new file name file. File renamed. 

### Actual behavior:
When viewing a file on a network. Pressed F2 to rename file. Entered new name in dialog. 
An Error shows, stating: "Could not find file \\nas\Data\nas\Data\path to file.jpg"
The correct address is "\\nas\Data\path to file.jpg".
Somehow it is repeating the first part of the path.

**Comment by fire-eggs** [comment]
Thank you for the report!

**Comment by d2phap** [comment]
uploaded to https://imageglass.org/moon

**Comment by ChewieChewbacca** [comment]
Thank you, this nows works perfectly
