### ISSUE TITLE
Ability to change icons

### ISSUE THREAD

**Issue by m1ga** [d2phap/ImageGlass#4]
Please add an option to change/remove some icons from the menu bar. E.g. I don't need Facebook, Newsletter, Bugreport. So I would like to right click the menu bar and add/remove icons I don't need all the time to get some more space.

**Comment by gaberad** [comment]
Yes, I'd like to add 'Move to the Recycle Bin' to the toolbar, so I don't have to right click the image.

If possible, could you also have an option to suppress the confirmation dialog?

**Comment by d2phap** [comment]
Hi @gaberad,

Confirmation dialog has been removed since v3.0.9.2
Besides, you can use DEL shortcut to perform 'Move to the Recycle Bin' quickly instead of opening context menu.

**Comment by Garywoo** [comment]
I too would like the ability to customise the toolbar. I would prefer a much smaller set of buttons, with the ability to see more under the hamburger menu, or something similar.

**Comment by d2phap** [comment]
This issue has been await for a long time. I still keep it open for implementation

**Comment by d2phap** [comment]
Implemented:
- `Removable/Movable toolbar buttons`

Check ImageGlass Moon for early build download

**Comment by fire-eggs** [comment]
Shipped in V5.0.
