### ISSUE TITLE
Thumbnail panel should be horizontal

### ISSUE THREAD

**Issue by Baegus** [d2phap/ImageGlass#40]
Vertical scrolling in the thumbnail panel seems a little bit disorienting.

**Comment by d2phap** [comment]
Hi @Baegus 
Since this commit https://github.com/d2phap/ImageGlass/commit/fa00c042c74731eedb21a173b01c4edf1aebce86, ImageGlass has changed to use new thumbnail panel for being faster. However, it just supports verticle scrollbar. I will do customization in the future.

**Comment by fire-eggs** [comment]
My initial attempt to implement this feature was as follows:
 1. In the frmMain designer, set the `thumbnailBar.View` property to `Gallery`. This forces horizontal scrolling.
 2. In the two places in `frmMain.cs` where `sp1.SplitterDistance` is set, change the value 40 and 41 to 57. This is necessary to account for the height of the horizontal scrollbar.

Initial testing suggests it seems to work. Caveat is I have not exercised it on Windows 10 or with changed scrollbar dimensions.

**Comment by d2phap** [comment]
@fire-eggs 

Should go to ```ImageListViewRenderer.cs``` and disable function's codes of 

```ruby
public virtual void DrawGalleryImage(Graphics g, ImageListViewItem item, Image image, Rectangle bounds)
```
