### ISSUE TITLE
Batch File For Default App

### ISSUE THREAD

**Issue by mrwolfe2018** [d2phap/ImageGlass#400]
Is there code or a batch file to make sure ImageGLass is the default image viewer on a user login?

**Comment by d2phap** [comment]
We don't have that code but if you want to associate file extensions to Windows, you can run the command

```
igtasks.exe regassociations "*.png;*.jpg;*.svg;"
```

**Comment by mrwolfe2018** [comment]
Does it matter if this is Windows 10 on a terminal server session? I run this and it says "ImageGlass was set as default photo viewer app successfully!" When I click on the PNG it opens in paint still.

**Comment by d2phap** [comment]
Hi @mrwolfe2018 
On Windows 10, we cannot change the default app programmatically, it's restricted.
What the command does is to register ImageGlass app to Default photo viewer list in Windows 10, the user must select it if they want to change.

**Comment by jonas-westphal-at-banovo** [comment]
Can you check if this could help you?
https://kolbi.cz/blog/2017/10/25/setuserfta-userchoice-hash-defeated-set-file-type-associations-per-user/

I really like to install this application but as long as i cannot install it and make it default at installation time its not really useful.

**Comment by d2phap** [comment]
Hi @jonas-westphal-at-banovo 
In Windows 10, what I can do is to register the extensions that can be opened by ImageGlass to registry, then user can select it from the default apps list.

**Comment by d2phap** [comment]
The MSI installer of v8.5 already supports register the extensions in the installation process
