### ISSUE TITLE
RAW Image issues

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#401]
As mentioned in Google group, people are having issues with Sony RAW (.arw) and Nikon RAW (.nef).
The images show as desired in Windows Photos but not in ImageGlass.

I downloaded a number of ARW and NEF files. I did not see any obvious issues with the ARW files. However, at least one NEF file displayed differently in ImageGlass 5.7 vs Windows Photos.

The following image is distinctly red in IG, but pale purple in Photos.
[infrared.zip](https://github.com/d2phap/ImageGlass/files/2308657/infrared.zip)

**Comment by fire-eggs** [comment]
Sample file links:
[NEF](http://www.mannyphoto.com/D700D3/)
[ARW](https://www.photographyblog.com/reviews/sony_a500_review/sample_images/)

**Comment by keerah** [comment]
I've just sterted using ImageGlass and haven't seen problems with ARW so far except they are **VERY** slow to open. About 5 seconds wait for 5K ARW image on Core i7 and GTX 1080

**Comment by d2phap** [comment]
Probably duplication of #464. There is an improvement version in IG Moon: https://imageglass.org/moon
