### ISSUE TITLE
Vertical Thumbnail View Causes Crash on Program Restart

### ISSUE THREAD

**Issue by TheYoke** [d2phap/ImageGlass#402]
### System information:
 - Windows OS version: Windows 10 x64
 - ImageGlass version: 5.5.7.26

### Describe the bug:
Change the settings to "Show thumbnails on right side" and adjust the thumbnail pane to about 3/4 of the screen will cause the program to crash on start.

### Expected behavior:
ImageGlass crashes on start

### To Reproduce
1. Go to Settings > Image
2. Check "Show thumbnails on right side" and Save
3. Click "Show Thumbnail"
4. Adjust the thumbnail pane to about 3/4 of the screen.
5. Restart ImageGlass.

### Screenshots:
![1](https://user-images.githubusercontent.com/19869060/44442650-9f234d80-a5fd-11e8-88bd-cd69977ae5e4.png)
![2](https://user-images.githubusercontent.com/19869060/44442676-c24dfd00-a5fd-11e8-8bcf-5e26f7d6efb3.png)

**Comment by d2phap** [comment]
uploaded to https://imageglass.org/moon
