### ISSUE TITLE
Display opened file name in taskbar

### ISSUE THREAD

**Issue by bitaruka** [d2phap/ImageGlass#403]
Hello! 
ImageGlass appearance in the taskbar is not so informative as it can be. Look at the screenshot in attachement. You actually can't quickly navigate between three instances without switching to each one cause there is no file names visible here.
I suggest to display name of opened file in the title of the app how it is done in Explorer, Photoshop, Chrome or 3ds Max for improving multitasking usability. You can do similar thing for Alt+Tab switcher too.
![issue2](https://user-images.githubusercontent.com/726535/44458306-75265700-a60e-11e8-95f6-0b9cac49a070.png)

**Comment by d2phap** [comment]
Thanks for suggestion
