### ISSUE TITLE
Register as Default App

### ISSUE THREAD

**Issue by werkheim** [d2phap/ImageGlass#406]
### System information:
 - Windows OS version: 10
 - ImageGlass version: 5.5.7.26

### Describe the bug:

We deploy ImageGlass with a deployement tool to our client computers. After installation, the user cannot set ImageGlass as default app like here in the image beacause it is simply not listed:

![2018-08-23_09h08_36](https://user-images.githubusercontent.com/40596187/44510199-406cdb00-a6b4-11e8-8333-eb7e1dd44730.png)

It is also not possible for the user without administrator rights to register as the default app from the first launch wizard (Step 4/4 Set ImageGlass as Default Photo Viewer?) because the user has no rights to write to HKEY_LOCAL_MACHINE\SOFTWARE\RegisteredApplications

### Expected behavior:
Would be nice to have a possibility to install ImageGlass with a deployment tool and a normal user can choose ImageGlass from the default apps window.

**Comment by werkheim** [comment]
Thank you for the fast reply.

We know that it needs admin rights. ImageGlass will be deployed with admin rights, but the first launch wizard runs with user rights and therefor it is not possible to write those keys. Would be great to have the  registry keys written during installation. It is possible to implement this? Can we to it by command line switch during installation (are there any command line switches?)

Thanks

**Comment by d2phap** [comment]
I'm using InnoSetup for packing installation. There is no option to do it during installation. 

However, the `igtasks.exe` file comes with the command line to register the extensions:
https://github.com/d2phap/ImageGlass/blob/master/Source/Ultilities/igtasks/Program.cs#L97

`regassociations "*.png;*.svg;"`

For the list of extensions, you can refer to https://github.com/d2phap/ImageGlass/blob/master/Source/Components/ImageGlass.Services/Configuration/GlobalSetting.cs#L86-L89

If you want to build and run *.reg file, you can check this:
https://github.com/d2phap/ImageGlass/issues/129#issuecomment-285069104

Hope it will help!

**Comment by werkheim** [comment]
Maybe with this (I'm definitely not the specialist :-) ):

http://www.jrsoftware.org/ishelp/index.php?topic=registrysection

**Comment by d2phap** [comment]
I will add writing registry to the setup file next version. 
Do you need it now, I can make a setup for you?

**Comment by d2phap** [comment]
There is a request to make *.msi installer as well.
Don't know if it is okay for you to test the MSI. 
I will create it over the weekend.
Thanks!

**Comment by werkheim** [comment]
Excuse my delay. Sure, that's fine.

**Comment by ITManVideos** [comment]
Hi, is there a download with this functionality? I deploy with the ImageGlass_5.5.7.26.exe and use the following switches: /VERYSILENT /SUPPRESSMSGBOXES /LANG=[EN]
But we do not have ImageGlass showing up in the list when setting associations.
If I run the following command afterwards it still does not show up:
igtasks.exe regassociations "*.bmp;*.cur;*.cut;*.dib;*.emf;*.exif;*.gif;*.ico;*.jfif;*.jpe;*.jpeg;*.jpg;*"

**Comment by d2phap** [comment]
Hi @ITManVideos 

The extension string you passed as argument is not a correct format.
It should be `igtasks.exe regassociations *.bmp;*.jpg;`

![image](https://user-images.githubusercontent.com/3154213/49202409-7a4e2b80-f3df-11e8-8cdc-67e6466a794a.png)

As your request to add option to remove the message box `--no-ui` already implemented here: #461
- For Portable version, you can just override _igtasks.exe_ file
- For Installer version, we are planning to roll out new release on mid of December 2018. You can experience the new version by downloading ImageGlass Moon. https://imageglass.org/moon

Thanks

**Comment by ITManVideos** [comment]
Thanks for your reply.
I copied over the igtasks.exe and ran the following command:
igtasks.exe regassociations *.bmp;*.jpg;* --no-ui

It does not show the message box anymore which is good and it now shows ImageGlass in the default list which is also good.

My mistake I was making was I was putting --no-ui straight after regassociations but it needs to be right at the end of the extensions.

Thanks for your help.
I am hoping a future release sets the associations automatically :-)

**Comment by d2phap** [comment]
Thanks @ITManVideos for your confirmation

**Comment by d2phap** [comment]
Implemented in the EXE installer (InnoSetup)
