### ISSUE TITLE
Start the program in full-screen mode when you open a file from Explorer

### ISSUE THREAD

**Issue by petrovnn** [d2phap/ImageGlass#407]
Hello and thank you for the wonderful program!

I use the program to view and organize my photos.
In order to see more details in the photo, you have to switch to full-screen mode.
This is necessary in order to use the maximum area of ​​the screen to view the photo.

It would be better to have the "checkbox" option "start the program in full screen mode" when the program is launched while opening the file from Windows Explorer. (this setting is implemented in FastStone and XN View)

**This setting in FastStone**
![image](https://user-images.githubusercontent.com/1567284/44569987-dbcd8100-a784-11e8-911a-406e1e03e964.png)

**This setting in XN View Classic**
![image](https://user-images.githubusercontent.com/1567284/44570193-a2494580-a785-11e8-89e5-ad206d9718fd.png)

**Comment by d2phap** [comment]
Thanks @petrovnn 
I have already had a plan to implement this. (also requested in #106)

**Comment by d2phap** [comment]
Implemented full-screen mode.
- Just need to toggle the Full Screen button or menu the app will remember this option on startup.
- Slide show mode also supports Full screen mode
