### ISSUE TITLE
ImageGlass "Lite"

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#408]
Raised in Google Groups:

> it seems a bit sluggish vs the windows default photo viewer.
> if possible please update so we can have it bare bones if we want so it can be faster.

Confirmed off-line with Mike Siggins:

> Okay child folder unchecked.
> Folder of sixty images, no child.
> First load 12 seconds. Second load (same image) <1sec.

This is consistent with the expensive start time of Magick.NET where the JIT compiler builds the massive DLL.

A "Lite" version of ImageGlass could be made where it does not use Magick.NET. It would start up faster, **but** be limited to image formats "native" to Windows: e.g. PNG, BMP, JPG, GIF. For other image formats, the "full" ImageGlass program would be required.

**Comment by d2phap** [comment]
Close because there is no plan for this
