### ISSUE TITLE
Request: tooltip should disappear on click

### ISSUE THREAD

**Issue by AnotherDimension-Ex** [d2phap/ImageGlass#409]
Hi, thank you for this amazing program.

My issue in the tooltip.
The tooltip is driving me crazy, it doesn't disappear when click on a button.
Tooltip, when hover on a button like "next image".

**Please note**:
All programs which have tooltip on hover, the tooltip disappears on click, you can see that in programs like FastStone Image Viewer, Nomacs, Photoshop, even Google Chrome, etc.

Also, could you please increase **rename image box** because I have allot of images with very long names.

Thanks!

**Comment by d2phap** [comment]
Hi @AnotherDimension-Ex 

> The tooltip is driving me crazy, it doesn't disappear when click on a button.
Tooltip, when hover on a button like "next image".

Do you mean the tooltip of the toolbar buttons?

> could you please increase rename image box because I have a lot of images with very long names.

surely we can do!
Thanks for your feedback

**Comment by AnotherDimension-Ex** [comment]
Yes, I mean the tooltip of the toolbar buttons.
Thank you very much for taking this suggestion

**Comment by AnotherDimension-Ex** [comment]
Yes, exactly the tooltip of the toolbar buttons.

It would be nice if we could resize the rename box of the size we like.
Like when resize the main imageGlass form (resizable form).

Maybe something like this:
FormBorderStyle = Sizable

Thank you very much for taking this suggestion.

**Comment by d2phap** [comment]
Implemented in ImageGlass Moon.
You can try the latest build here: https://imageglass.org/moon

**Comment by AnotherDimension-Ex** [comment]
Hi @d2phap 
Still, there is a little bit issue.

When the tooltip is shown and click on a button the tooltip it disappears, ok.
But If you click before the tooltip is shown, it doesn't disappear, and you will need a second click to make it disappear.

Please Note:
The click event is should cancel the tooltip even before it shows, this is the case for all programs with the tooltip.

Comparing with FastStone or other programs, click event cancels the tooltip even before it shows.

Thanks!

**Comment by d2phap** [comment]
Implemented in IG Moon 5.5.20.28
