### ISSUE TITLE
Unhandled exception error when opening a certain gif

### ISSUE THREAD

**Issue by JamesDean3** [d2phap/ImageGlass#41]
You guys should make a easier way to submit bugs on your website. It might be more encouraging for others to submit their bugs

--------------------------------------------------

.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
   at System.Drawing.Image.SelectActiveFrame(FrameDimension dimension, Int32 frameIndex)
   at System.Drawing.ImageAnimator.ImageInfo.UpdateFrame()
   at System.Drawing.ImageAnimator.UpdateFrames(Image image)
   at ImageGlass.ImageBox.DrawImage(Graphics g)
   at ImageGlass.ImageBox.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.96.0 built by: NETFXREL2STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ImageGlass
    Assembly Version: 2.0.1.5
    Win32 Version: 2.0.1.5
    CodeBase: file:///F:/Program%20Files%20(x86)/ImageGlass/ImageGlass.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
ImageGlass.Services
    Assembly Version: 1.0.6.0
    Win32 Version: 1.0.6.0
    CodeBase: file:///F:/Program%20Files%20(x86)/ImageGlass/ImageGlass.Services.DLL
----------------------------------------
ImageGlass.ImageBox
    Assembly Version: 2.0.4.2
    Win32 Version: 2.0.4.2
    CodeBase: file:///F:/Program%20Files%20(x86)/ImageGlass/ImageGlass.ImageBox.DLL
----------------------------------------
ImageGlass.ThumbBar
    Assembly Version: 2.0.5205.41597
    Win32 Version: 2.0.*
    CodeBase: file:///F:/Program%20Files%20(x86)/ImageGlass/ImageGlass.ThumbBar.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
ImageGlass.Theme
    Assembly Version: 1.5.5475.31523
    Win32 Version: 1.5.5475.31523
    CodeBase: file:///F:/Program%20Files%20(x86)/ImageGlass/ImageGlass.Theme.DLL
----------------------------------------
ImageGlass.Library
    Assembly Version: 1.4.0.0
    Win32 Version: 1.4.0.0
    CodeBase: file:///F:/Program%20Files%20(x86)/ImageGlass/ImageGlass.Library.DLL
----------------------------------------
ImageGlass.Core
    Assembly Version: 1.7.5465.38546
    Win32 Version: 1.7.5465.38546
    CodeBase: file:///F:/Program%20Files%20(x86)/ImageGlass/ImageGlass.Core.DLL
----------------------------------------
IconLib
    Assembly Version: 0.73.0.0
    Win32 Version: 0.73.0.0
    CodeBase: file:///F:/Program%20Files%20(x86)/ImageGlass/IconLib.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by d2phap** [comment]
Hi @JamesDean3 

Could you share the gif that causes exception? I published a pre-release build for testers / contributors, you can download it here https://github.com/d2phap/ImageGlass/releases/tag/2.1.0.0
it may be fixed.

**Comment by JamesDean3** [comment]
The newest build works properly. I attached the gif that caused the problem. 

![4vfxp2](https://cloud.githubusercontent.com/assets/13928304/9437399/f5f94a62-4a0a-11e5-9c4f-be5f0f38a907.jpg)

**Comment by d2phap** [comment]
Ok! The problem is your animated image ends with .jpg, instead of .gif.
The pre-release build fixed this issue.
Thank you :)
