### ISSUE TITLE
[Feature] Close after edit button

### ISSUE THREAD

**Issue by eliaspizarro** [d2phap/ImageGlass#413]
### Is your feature request related to a problem? Please describe.
Maybe, when you click on edit, the photo is still in use by imageglass, so yo need to close imageglass

### Describe the solution you'd like
Close after press edit

**Comment by fire-eggs** [comment]
Just to be clear, @eliaspizarro is saying he needs to close ImageGlass in order to release a file lock on the image.

I _may_ have seen this myself, just hadn't investigated. 

Files need to be opened in Read-only and Shared modes. Apparently, we are opening them in Read-Write and/or Exclusive modes.

**Comment by fire-eggs** [comment]
@eliaspizarro -
What file format(s) are you trying to edit?

So far, I can edit jpg and png files via IG, using Paint, with no issue.

**Comment by fire-eggs** [comment]
Digging a little further, I'm pretty sure in most cases that IG does not lock the image file. There is a lock on some or all of the _folders_ when viewing images in sub-folders (a side-effect of watching for changes).

So I'll need more details on how to reproduce this ...

**Comment by amirrammari** [comment]
> 
> 
> Is it really necessary to auto-close?
> Just press ESC to close?

Hi @d2phap
I need this feature.
Please add this feature in next release.
Thanks <3

**Comment by Crivens** [comment]
Yeah I would love this feature. I only use ImageGlass as a quick image previewer before maybe editing it in PSP (slow to load). I don't need ImageGlass to hang around after I've entered PSP, so making it auto close would be excellent.

**Comment by d2phap** [comment]
This feature is ready in IG Moon: https://imageglass.org/moon
You need to check on option in Settings > Edit tab:


![image](https://user-images.githubusercontent.com/3154213/98556935-8e467b80-22de-11eb-8dd4-afe2c0c84d59.png)

**Comment by xmha97** [comment]
Thanks 🙏
