### ISSUE TITLE
Bug: unable to open image in a folder contains special character

### ISSUE THREAD

**Issue by AnotherDimension-Ex** [d2phap/ImageGlass#415]
Hi,

It was very frustrated when I found ImageGlass was unable to open image in a folder contains special characters, the invisible character.

Please note:
All other images viewer was able to open image in folder contain the invisible character like
FastStone Image Viewer, default windows photo viewer, nomacs, IrfanView, XnView.

To get the invisible character create "New Folder" and rename it the invisible character.

To create the invisible character on windows (ALT 255).
1. Hold ALT key.
2. Press the numpad keys 2 and 5 and 5 .
3. Release the ALT key.
Also note use the numpad on the right keyboard (not the key numbers under the F1, F2, etc. this won't work)
And puts some images in the folder.

![1](https://image.ibb.co/dNYQXz/04056.png)
![2](https://image.ibb.co/dT6UaK/04055.png)
![3](https://image.ibb.co/hSEhvK/04053.png)
![4](https://image.ibb.co/faAcUe/04054.png)

**Comment by d2phap** [comment]
How does the char look like?
Can you attach screenshot or copy that char?
(Sorry I don't have NumPad keyboard)

I did a quick test with this list
https://www.redbubble.com/people/barnsis/journal/3570534-complete-ascii-list-of-symbols
ImageGlass works well.
Thanks

**Comment by fire-eggs** [comment]
Forgot to mention: this is an issue only when ALT+255 is at the end of the folder name. I.e. I could create a new folder, and use ALT+255 in the middle, and IG works fine.

**Comment by AnotherDimension-Ex** [comment]
The character is like a white space " ".

If you use windows you can create this character by using **On-Screen Keyboard**.
Open it and from options enable "Turn on numeric key pad" and prees ok, after that press NumLock to show the numeric keys, now you can create the invisible character. (may need to hold  ALT key from your regular keyboard).


I hope this can be fixed.

Thanks!

![Image](https://image.ibb.co/cVFpQK/04058.png)

**Comment by d2phap** [comment]
Implemented in ImageGlass Moon.
You can try the latest build here: https://imageglass.org/moon

**Comment by AnotherDimension-Ex** [comment]
Thank you the fix is working great.

Best regards,
Another Dimension
