### ISSUE TITLE
Save to extension keeps getting changed to BMP randomly

### ISSUE THREAD

**Issue by Welcius** [d2phap/ImageGlass#416]
### System information:
 - Windows OS version: Microsoft Windows 10 Pro N 10.0.17134 compilation 17134

 - ImageGlass version: 5.5.7.26

### Describe the bug:
When browsing through pictures and pressing Ctrl + S to save pictures the extension constantly gets changed to BMP with JPG pictures even when you change it manually, after some pictures it gets changed again to BMP, which is a bit of a bummer since you have to constantly change the extension when saving images.

### Expected behavior:
When choosing an extension after pressing Ctrl + S to save pictures and you change the extension manually it should be remembered at least during the session when saving again other pictures and not being constantly changed to BMP.

### To Reproduce
1. Open an image in a folder with many images
2. Save an image and choose the extension JPG
3. Save 10-20 images again until the extension that you chose gets changed to BMP without a reason

Note: The images that you save and the extension of the destination file gets changed to BMP are not BMP (they are JPG), I don't recognise a pattern between those extension changes.

**Comment by d2phap** [comment]
Currently the extension will be set as same as 
- the original file 
- or BMP if the original extension is not listed in the list.

Marked as improvement.
Thanks for your report

**Comment by Welcius** [comment]
In that case, could it be that some files have the extension JPEG which is the same as JPG? I think you should add JPEG as an alias for JPG since is commonly used, I am seeing right now that saving a JPEG file defaults to BMP

**Comment by d2phap** [comment]
This feature is ready in IG Moon https://imageglass.org/moon
