### ISSUE TITLE
Is it possible to add my custom image format (.YAIF)

### ISSUE THREAD

**Issue by DeaSTL** [d2phap/ImageGlass#417]
### Image Specification 
I've built an encoder for this image format, here is the specification 
https://docs.google.com/spreadsheets/d/1x92FSTWnqBIw4f9Z9bTM56SrJCUfrn42fn4d0mefxPA/edit?usp=sharing

### Encoder Software
https://github.com/DeaSTL/yaifEncoder

### Current Viewer Software
https://github.com/DeaSTL/yaifViewer-dotnet

### Additional context
I'd like to know if it's possible to add something like this with your current system

**Comment by d2phap** [comment]
Hi @DeaSTL 

Do you have the sample files?

**Comment by DeaSTL** [comment]
[Sample Image.zip](https://github.com/d2phap/ImageGlass/files/2353940/Sample.Image.zip)
Sorry but github said it doesn't support this image format, lol, I wonder why?
You'll just have to unzip this.

**Comment by DeaSTL** [comment]
@d2phap 
there are still some features I'd like implement, like image compression because right now the only image compression that it has is reducing the color palette and reducing the amount of bit used for each index.

**Comment by d2phap** [comment]
I will close this as I have no plan, IG just uses MagickNET for decoding image formats
