### ISSUE TITLE
Heavy lag when checkerboard background is enabled

### ISSUE THREAD

**Issue by juancarlosga** [d2phap/ImageGlass#419]
### System information:
 - Windows OS version: Windows 10 x64
 - ImageGlass version: 5.5.7.26
 - CPU: i5 6500
 - GPU: gtx 1060 6gb

### Describe the bug:
Few months back I was looking for a fast, lightweight and simple image viewer; ImageGlass is perfect! Except for one thing, I always seemed to get "lag" when I moved the picture around with the hand tool, and you could REALLY notice stuttering & some really annoying "unsmooth" tearing on the image. I found it particularly annoying because I have mid-high end hardware. I have never experienced this kind of problem ever before.

Well today I was messing around with ImageGlass and decided to get to the bottom of this, and long story short, I ended up disabling the checkerboard background and bingo! Performance is MUCH better! Image dragging feels much more responsive and there is no tearing or stutter.

### Expected behavior:
When I have checkerboard background I expect it not to have any kind of performance impact on the program.

### To Reproduce
1. Open ImageGlass
2. Go to dropdown menu
3. Go to Layout
4. Click Checkerboard Background to enable/disable

### Additional context:
In my attempts to solve this I tried to:
 - Set a process priority to IG thru task manager
 - Set a GPU priority thru NVIDIA control panel

None of that worked one bit.

**Comment by d2phap** [comment]
Hi @juancarlosga 

To understand your issue
- What is the image extension?
- What are the image dimension?
- How big is the file size?

Thanks a lot!

**Comment by juancarlosga** [comment]
- What is the image extension?
I mostly work with .png images.
- What are the image dimension?
2000x1125 on this random example, I work with at least 1920x1080 images, but sometimes much much bigger.
- How big is the file size?
On this random example size is 5.23MB



![ferrari](https://user-images.githubusercontent.com/42979427/45118596-8ac37280-b11e-11e8-8589-cacbe16216ff.png)

**Comment by fire-eggs** [comment]
A few thoughts:
1. IG could be a little smarter about drawing the checkered background. It is drawn to the full window, even if it will eventually be hidden by the image (assuming zoomed).
2. Others have mentioned performance issues when panning - see issue #272 
3. There are a number of threads on the interwebs discussing flickering/tearing problems with the GTX 1060. You might check into driver issues.

**Comment by d2phap** [comment]
I have tried opening the attached image with checkerboard background.
Tested on the Core i5, i7 machines, but performance was (almost) same. 

Image can be paned faster when zoomed in.

**Comment by d2phap** [comment]
This should be fixed in ImageGlass 9.0 beta
