### ISSUE TITLE
Request: please improve zoom level and add auto fit to canvas

### ISSUE THREAD

**Issue by AnotherDimension-Ex** [d2phap/ImageGlass#420]
Hi again,
I'm so sorry to keep troubling you by my requests, I hope you don't mind.

The zoom in ImageGlass I can't get used to it, my entire life I was using FastStone Image Viewer and Nomacs and I'm always looking for renewal.

**The are two issues in ImageGlass:**

<p>1) Is missing auto fit to canvas (scale to fit) when zooming in FastStone Image Viewer or Nomacs by the mouse wheel when get close to the canvas is auto fit.
Like when you press (Ctrl + H) or press "scale to fit" button.

<p>2) The zoom level is not smooth, comparing with FastStone and Nomacs and Microsoft Photos (windows default viewer) it has much better zoom level, Test on the same image (from zoom level 10%)
This test may slightly different because it depends on screen dimensions.

**Zoom in FastStone**   10%, 15%, 20%, 30%, 40%, 50%, 60%, 80%, 100%, 125%, 150%, 175%, 200%, etc.
**Zoom in ImageGlass** 10%, 15%, 20%, 30%, 50%, 70%, 100%, 150%, 200%,  etc.

Zoom level in ImageGlass not smooth because is missing 40%, 60%, 80%, 125%, 175%

So please add a way to get these two options even if it will mean we have to edit the config file.

Thanks!

**Comment by 0-0-0-0** [comment]
2.1) Zoom "steps" vary too much: 20->30->50->70->100. A uniform +10%  from 20% to 100% or from 20% to 50% makes more sense IMHO.

**Comment by d2phap** [comment]
Thanks for the suggestions.
The zoom steps are following Windows Photo Viewer, not really same but I tried to make it same.
I will add an option to customize the zoom steps in Settings dialogue.

**Comment by khari3** [comment]
Sir,

Also add custom zoom percent,to increase the image size in desired zoom%

**Comment by Hoowah** [comment]
If you want to give the user full customization over zoom levels, a Settings text box where the user can edit any zoom levels they want would be best. It would just be a numerical list separated by commas.

You could make a checkbox to "Snap on" to both 'Scale to Width' and 'Scale to Height'. This would catch both 'Scale to Fit' and 'Scale to Fill' cases.

**Comment by d2phap** [comment]
Added more zoom levels and option in Settings to customize it.
Shipped in IG Moon: https://imageglass.org/moon

![image](https://user-images.githubusercontent.com/3154213/59961564-153d5d00-950c-11e9-8acf-0e5e0cfc3ee6.png)
