### ISSUE TITLE
Option, to add the buttons at the centre of the window

### ISSUE THREAD

**Issue by khari3** [d2phap/ImageGlass#425]
Add an option to place all the button's(go to next image,previous image) in the center of the window.

**Comment by fire-eggs** [comment]
I'm having trouble visualizing this. Could you clarify - maybe with a mockup?

I.e. are you suggesting 3 regions:
1. Top region: image display or thumbnails
2. Middle region: the toolbar
3. Bottom region: image display or thumbnails

Or are you suggesting "fly-over" buttons like in issue #367 ?

**Comment by khari3** [comment]
I am suggesting toolbar buttons to place in the center.

![s2](https://user-images.githubusercontent.com/43307781/45635386-75f1c200-bac2-11e8-908a-859a0dbf3d56.jpg)

and also this ---

![s3](https://user-images.githubusercontent.com/43307781/45635423-8c981900-bac2-11e8-9e0e-c4d96a24e1bf.jpg)

**Comment by fire-eggs** [comment]
Gotcha! Thanks!

**Comment by khari3** [comment]
@phap -- Are you going to add the above feature?

**Comment by fire-eggs** [comment]
The code change has been checked in. @d2phap is on vacation this week, he'll have to speak to his plans for the release schedule.

**Comment by khari3** [comment]
@phap - What's your answer?

**Comment by d2phap** [comment]
The official version will be released in the mid (or end) of December. In the meanwhile, I will upload the ImageGlass Moon version.

**Comment by d2phap** [comment]
You can test this feature in IG Moon 5.5.11.28
https://imageglass.org/moon

Note: There is still a UX bug when toggling this option in Settings on Maximize/Normal state of Window, the toolbar button position is not updated

**Comment by d2phap** [comment]
Fixed the issue when resizing window.
https://imageglass.org/moon
