### ISSUE TITLE
Tooltip keeps flashing 

### ISSUE THREAD

**Issue by khari3** [d2phap/ImageGlass#426]
Press on the next button 5 to 6 times then the tool tip(go to next image) keeps flashing.

Using windows 10 and latest version of image glass(not the beta).

**Comment by khari3** [comment]
Even in the latest beta, when you place the cursor on the "view next image" and some other buttons the tool tip is flashing.

**Comment by fire-eggs** [comment]
Yeah, I finally "got it" last night. New attempted fix, pending a Moon release post 5.5.9.5 ...

**Comment by khari3** [comment]
Also the buttons like "view next image" keeps flashing.

**Comment by fire-eggs** [comment]
I'll take another look.

**Comment by d2phap** [comment]
Uploaded the new IG Moon version
