### ISSUE TITLE
Create a Chocolatey package for each release

### ISSUE THREAD

**Issue by masbicudo** [d2phap/ImageGlass#428]
[Chocolatey](https://chocolatey.org/) is a package manager for Windows.

It makes it easy to install software from a simple command line, and to make scripts to install software automatically, e.g. after formatting and installing Windows on multiple computers, to make sure a common set of software is available.

I found an [old verion there (5.1.5.20)](https://chocolatey.org/packages/imageglass) already, but it would be nice to automate the process to keep it updated.

[Creating Chocolatey Packages](https://github.com/chocolatey/choco/wiki/CreatePackages)

**Comment by d2phap** [comment]
updated the Chocolatey package

**Comment by masbicudo** [comment]
Thank you very much!!! =D
