### ISSUE TITLE
Gif Playback 'poor' on Windows 7

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#429]
### System information:
 - Windows OS version: Windows 7
 - ImageGlass version: 5.5.9.5 Moon

### Describe the bug:
The attached GIF plays poorly in IG.

### Expected behavior:
Plays nicely, as in Chrome.

![tumblr_owbyt3saav1rfx24fo1_500](https://user-images.githubusercontent.com/9809727/46040693-06418f80-c0df-11e8-9a2d-102385aa51a7.gif)

**Comment by d2phap** [comment]
How "poor" is it?
It looks same as chrome on Windows 10 in my test.

**Comment by fire-eggs** [comment]
Here is one frame, having paused GIF playback:

![image](https://user-images.githubusercontent.com/9809727/46087490-75b78d80-c178-11e8-90f6-956ef815554e.png)

You are correct - it plays fine in Windows 10.

**Comment by fire-eggs** [comment]
Fixed: IG needed to enforce the minimum frame delay of 10ms, an ancient holdover from Netscape Navigator.
