### ISSUE TITLE
Color management aware

### ISSUE THREAD

**Issue by eckso** [d2phap/ImageGlass#43]
If you pull this off you might get one image viewer of a kind, currently I don't know any lightweight image viewer that is color profiles aware. The embedded color profile must be converted to display profile, or at worst fallback to sRGB in the absence of it. You can see how an image should be viewed when opening it in programs like Photoshop or CM aware browsers like Firefox (ie. enabling this: pref("gfx.color_management.mode", 1)).

Normally images look darker on non CM aware programs.

**Comment by vancwa** [comment]
I am using the latest version (3.2.0.16) and am wondering if the CM aware feature within ImageGlass is enabled automatically by default, or if there is some software setting that must be user selected first before it is enabled. How do I know it's working? I have established a color profile between my laptop and a front projector unit using X-Rite calibration tools. I manage image competitions in a photo club and CM is very important.

**Comment by d2phap** [comment]
Hi @vancwa, @eckso 

Since ImageGlass v2.0.1.5, CM feature has been enabled automatically by default. ImageGlass will auto-detect embedded color management profile. You can compare ImageGlass color to Chrome / IE / Photoshop... it will be same. The new Win 10 Photos app is still not supported CM.

You can check issue #17 for further information and download sample image.

**Comment by markdv77** [comment]
Even latest version (now 4.5.11.27) does not appear to use/honor **monitor** profiles. (I calibrate my monitor using an X-Rite iDisplay.) I can clearly see Images (simple sRGB jpeg) opened in ImageGlass have different - esp. more saturated - colors then when opened in Photoshop or "chrome --enable-monitor-profile". Which makes it unsuitable to view/show edited photo's.

Would be nice if I could get accurate colors from it too.
For more casual image image viewing I still really like ImageGlass, so "thank you!"

**Comment by d2phap** [comment]
Hi @markdv77 

ImageGlass enables sRGB profile by default: https://github.com/d2phap/ImageGlass/blob/master/Source/Components/ImageGlass.Core/Interpreter.cs#L100

For the monitor color profile, I will investigate my time.

**Comment by Sandros94** [comment]
So for the monitor color profile is still under development right?

**Comment by d2phap** [comment]
To do:
- [ ] Add option to select `*.ICC` profile file.

**Comment by d2phap** [comment]
Implemented Color Management. 
- [x] Support some built-in color profiles
- [x] Allow to select a custom color profile *.icc
- [x] Option to apply the color profile to all or only the images with embedded profile, it's unchecked by default.
- [x] Use color profile `sRGB` by default

It's ready for testing in IG Moon 5.5.12.8
https://imageglass.org/moon

![image](https://user-images.githubusercontent.com/3154213/49683820-f3e3c900-fb05-11e8-9c72-78f7bd9ac828.png)

**Comment by sboukortt** [comment]
Nice progress, thanks!

Could you perhaps just clarify what happens exactly for images without an embedded profile? Looking at the code, it seems that it simply calls “AddProfile” once on the image, which doesn’t sound like it would perform any colorspace conversion (after all, one needs two colorspaces for that).

Maybe what is needed is an option to specify the default colorspace for images without an embedded profile? (I would assume that sRGB would be a typical choice.) You would then:

1. `AddProfile(the_default_image_profile_which_would_often_be_srgb)` if the image doesn’t have a profile, and then
2. `AddProfile(the_monitor_profile)` unconditionally.

(https://stackoverflow.com/a/18918798)

----

It is also not entirely clear to me why `magicImg.ColorSpace = imgColorProfile.ColorSpace;` is needed. Is it, really?

**Comment by d2phap** [comment]
Hi @sboukortt 
Thanks for the link. I forgot the "two colorspaces"!
Also updated the IG Moon.

---

> It is also not entirely clear to me why magicImg.ColorSpace = imgColorProfile.ColorSpace; is needed. Is it, really?

Sometimes, the color space of this: 
`magicImg.GetColorProfile().ColorSpace` 
and this: 
`magicImg.ColorSpace`  
are not same (Example: #430), that's why I need to correct it.

---

For images without an embedded profile:
- If `isApplyColorProfileForAll` = `false`, 
  + IG will skip the Color Management processing
- If `isApplyColorProfileForAll` = `true`, 
  + IG will assign a default Profile `sRGA` to the image, 
  + then apply the Color Profile from user settings.

**Comment by eckso** [comment]
Not working for me on ImageGlass_Moon_5.5.12.8, the "_Apply also for images without embedded profile_" is checked with sRGB as the fallback. Images look darker than in color managed viewers. I'm on Win7 SP1, if that helps. Thanks for the updates.

**Comment by d2phap** [comment]
Hi @eckso 
Can you attach your file? Thanks

**Comment by eckso** [comment]
Actually any image without an embedded color profile.
![cineon](https://user-images.githubusercontent.com/13509598/49707654-2683e380-fc24-11e8-8062-568f56b00805.png)
![imageglass](https://user-images.githubusercontent.com/13509598/49707656-2e438800-fc24-11e8-9b7c-b5df03a3ba0c.PNG)

**Comment by d2phap** [comment]
Hi @eckso 
I can't  see any difference of ImageGlass and other apps (MS Photos, Chrome,...), even in your screenshot.

**Comment by eckso** [comment]
Blacks are crushed, you can see it easier if you open the images in diferrent tabs and switch over back and forth. This is ImageGlass.
![cineon imageglass](https://user-images.githubusercontent.com/13509598/49733717-2adaeb80-fc7a-11e8-82b7-b0ac4c04e0ab.png)

**Comment by d2phap** [comment]
Hi @eckso 
Your image contains an embedded profile.
![image](https://user-images.githubusercontent.com/3154213/49776238-2542db80-fd36-11e8-9c50-84f6d4b62cf9.png)

I opened this image and compared ImageGlass to Chrome, Firefox, MS Photo, Adobe Photoshop Express. The difference is the brightness of the girl's neck area.
- the image looks same in ImageGlass, Firefox, MS Photo, Adobe Photoshop Express.
- the image is a bit lighter in Chrome.

So I think ImageGlass displays the image correctly.

**Comment by eckso** [comment]
PrintScreen or the Snipping tool is not color managed so in order to show what I see I have to interpret the image as Display referred and then convert to sRGB so you can see the same. I think the problem is because I use a calibration profile for my monitor and ImageGlass has issues converting to display space. Thanks for the help.
