### ISSUE TITLE
Image wrongly has inverted colors

### ISSUE THREAD

**Issue by Keith94** [d2phap/ImageGlass#430]
![imageglass_2018-09-28_15-15-11](https://user-images.githubusercontent.com/5490615/46235993-b3134b00-c331-11e8-98c4-750dd4da3ca2.jpg)

**Comment by Keith94** [comment]
![75b5c1062e881c95110488153614e18b](https://user-images.githubusercontent.com/5490615/46236052-fa99d700-c331-11e8-92b3-1e998e5332bc.jpg)

**Comment by d2phap** [comment]
Thanks @Keith94

**Comment by d2phap** [comment]
fixed this bug in IG Moon v5.5.12.4: https://imageglass.org/moon
