### ISSUE TITLE
how to uninstall?

### ISSUE THREAD

**Issue by khari3** [d2phap/ImageGlass#431]
There is no uninstaller,even clicking in control panel to uninstall only removes the entry and doesn't uninstall IG. So how to uninstall it?

**Comment by d2phap** [comment]
If you use Portable version, you need to manually delete all files.
For Installer version (*.exe / *.msi), you can uninstall it in the _Add or Remove Program_ Settings of Windows.

**Comment by khari3** [comment]
For installer version,In the Add or remove program settings of windows,clicking on the icon just removes the entry and doesn't uninstall.

**Comment by d2phap** [comment]
> clicking on the icon just removes the entry

Do you mean the shortcut icon?

There is an uninstall.exe file in the installed folder. You can try running it.
Btw, nobody reports this issue before

**Comment by khari3** [comment]
I should have mentioned in the beginning itself that this is for beta,which doesn't has uninstaller.
When a user update's to beta version and he rewrite's the contents of the beta zip file to the folder where IG has installed it removes the uninstaller.

**Comment by d2phap** [comment]
The portable version means that users don't need to install and of course, they cannot uninstall cuz there is no uninstaller, just simply delete the files.
