### ISSUE TITLE
Request: Mirror / Flip (horiz vert) button near Rotate buttons

### ISSUE THREAD

**Issue by ukoz** [d2phap/ImageGlass#433]
Hello.

### Is your feature request related to a problem? Please describe.
Some images you get mirrored having a button to revert it would be very useful.

### Describe the solution you'd like
Please, add Mirror / Flip button near Rotate buttons, at toolbar.

Thanks.

**Comment by fire-eggs** [comment]
Flip horz / vert, and buttons, is available in IG Moon 5.5.9.5.

Unfortunately, the images didn't make it into the theme, but the buttons do work (just blank).

Using the toolbar customization in settings, you can place the buttons where you'd like.

**Comment by d2phap** [comment]
Closed. It's a duplication of #99

**Comment by ukoz** [comment]
Where to get that updated 5.5.9.5?
It only 5.5.7.26 on github and imageglass.org .

**Comment by d2phap** [comment]
Hi @ukoz,

You can download it at https://imageglass.org/moon
