### ISSUE TITLE
Scale to Fill

### ISSUE THREAD

**Issue by Hoowah** [d2phap/ImageGlass#436]
### Describe the solution you'd like
'Scale to Fill'

A "Fill" scaling mode that automatically applies 'Scale to Height' or 'Scale to Width' to fill the Image Frame, based on the Image and Image Frame aspect ratios.

### Additional context
![scale_to_fill](https://user-images.githubusercontent.com/44103890/46900024-315b0b80-ce61-11e8-82e2-0bef9c37cd17.png)

Note: ImageGlass does not currently center images that exceed the boundaries of the Image Frame, misrepresented for demonstration. Request for this feature can be found here: https://github.com/d2phap/ImageGlass/issues/437

**Comment by d2phap** [comment]
This feature is ready in ImageGlass Moon: https://imageglass.org/moon
`Scale to fill` is 1 of 6 `Zoom modes` in ImageGlass now!

![image](https://user-images.githubusercontent.com/3154213/67633414-880b7a00-f8ea-11e9-9e75-2bd21f2bba3b.png)
