### ISSUE TITLE
Auto Center

### ISSUE THREAD

**Issue by Hoowah** [d2phap/ImageGlass#437]
### Is your feature request related to a problem? Please describe.
Image anchoring from the top edge, left edge, or top-left corner is currently implemented over centering the image in scaling/magnification modes when the image exceeds the boundaries of the viewing frame. This is desirable for viewing linear content such as text, comics/manga, contact sheets, etc.
But typical photographs and illustrations are poorly framed before user adjustment.

### Describe the solution you'd like
I think a toolbar button that toggles between the current behavior and a new 'Auto Center' mode would be best. 
It would be independent of and compatible with 'Lock Zoom Ratio', 'Auto Zoom', and the other scaling modes.

When activated, the current image is centered in the frame. The image does not re-center after panning or zooming unless re-activated.
While activated, newly opened or refreshed images are automatically centered in the frame. 
Effects are only appreciable when magnification levels exceed 'Scale to fit'.
   
Common use examples:
   
Viewing portrait photographs in 'Scale to Width' Mode
Viewing panoramic landscape photographs in 'Scale to Height' Mode
Viewing photographs under magnification in 'Lock Zoom Ratio' Mode

### Additional context
![auto_center](https://user-images.githubusercontent.com/44103890/46907381-28a51c80-ced7-11e8-8b86-c4e2c6137b9e.png)

**Comment by Hoowah** [comment]
I realized another detail

In addition to newly opened and refreshed images,
While activated, re-applying or switching between any of the scaling modes (EX: Auto Zoom, Scale to Width/Height, Scale to Fit) should also trigger the image to be auto centered.

**Comment by d2phap** [comment]
Your request was implemented, you can try the latest build here:
https://imageglass.org/moon

**Comment by Hoowah** [comment]
Thanks
