### ISSUE TITLE
Unhandled exception for FileSystemWatcher when opening image in folder with system created Junctions

### ISSUE THREAD

**Issue by JLJTGR** [d2phap/ImageGlass#440]
### System information:
 - Windows OS version: Windows 10 x64 1803
 - ImageGlass version: 5.5.7.26

### Describe the bug:
Unhandled exception for FileSystemWatcher when opening image in folder with system created Junctions.
Examples include: `C:\`  (SystemRoot) --  `C:\Users\%USERNAME%\` -- `C:\Users\%USERNAME%\Documents\`

### Expected behavior:
Handle the exception, I guess.

### To Reproduce
1. Open an image, from Explorer or inside ImageGlass, where the image is in a folder with hidden system junctions.  (like above examples)
2. 
3. 
4. 

### Screenshots:
![image](https://user-images.githubusercontent.com/5780236/47318816-16378b00-d61b-11e8-8d80-8001261b2cc2.png)

### Additional context:
![image](https://user-images.githubusercontent.com/5780236/47318965-7af2e580-d61b-11e8-87fa-1e56795e0bb2.png)

User created junctions don't have this issue.  Just system created ones made for compatibility reasons.

**Comment by fire-eggs** [comment]
Thank you for your report!

I was able to reproduce the crash with IG 5.5.7.26, opening an image from the C:\Users\%USERNAME% folder.

The latest Image Glass Moon 5.5.10.28 ([Moon](https://imageglass.org/moon)) does not crash when I repeat the same action.
