### ISSUE TITLE
ImageGlass not able to open hidden files (images)

### ISSUE THREAD

**Issue by homewehi** [d2phap/ImageGlass#441]
### System information:
 - Windows OS version: Windows 10 Home Version 1803
 - ImageGlass version: 5.5.7.26

### Describe the bug:
if you try to open hidden files (images) it will shows "ImageGlass cannot open this picture because the file appears to be damaged, corrupted or not supported." though it was not damaged nor corrupted and it was an png type image.
And if you open the hidden image with Windows Photos it works

### Screenshots:
[https://i.imgur.com/TOPFzif.png](img)
[https://i.imgur.com/HZN4ZYg.png](img)

### Additional context:
I expected that setting the file to unhidden would work and yes i was right

**Comment by fire-eggs** [comment]
Thank you for your report!

If you want to see hidden images, you need to check the "Show hidden images" setting.

The only way that I've been able to repeat the described situation is:
1. In the ImageGlass settings, I have "Show hidden images" _not_ clicked.
1. Drag a hidden image onto ImageGlass, where the image is the only image in the folder.
1. Running Image Glass 5.5.7.26.

The latest Image Glass Moon 5.5.10.28 (see [Image Glass Moon](https://imageglass.org/moon)) does not display the "cannot open this picture" message in this situation.

Closing this as "working as expected".

**Comment by PaulCoddington** [comment]
> Closing this as "working as expected".

I'm not sure this is working as expected.

Expectation would be that "show hidden images" applies to viewing images in a folder using navigation keys or slideshow feature. But ImageGlass would still be expected to display a hidden file when double-clicked in File Explorer regardless of this setting. This is the way most viewers work.
