### ISSUE TITLE
User config is destroyed upon portable upgrade

### ISSUE THREAD

**Issue by CollinChaffin** [d2phap/ImageGlass#444]
Please follow the industry standard and if moon is being packaged only as a "portable" zip that they when run shows "portable mode"...and remove the default igconfig.xml that is currently being included for some odd reason.

This makes zero sense anyway since IG then opens, sees the default xml missing options, and insists on running the initial config wizard, anyway.  What is ludicrous is EVERY single moon zip upgrade, if you forget to manually exclude that xml, you WIPE OUT all your settings.

Most other zip beta/daily/dev packages simply exclude the user-config exactly so you do not risk user data loss and can simply overwrite your IG folder with each new build and re-launch and not lose any settings.

**Comment by d2phap** [comment]
Hi @CollinChaffin 

Sorry for the inconvenience!
I will exclude the config file for portable/moon version.

Thanks for your feedback!
