### ISSUE TITLE
Improve startup time

### ISSUE THREAD

**Issue by ultravelocity** [d2phap/ImageGlass#446]
Great application. I've customized the UI to create a nice clean interface. However, despite using a very fast desktop, but there's still a slight delay when opening the application. It would be great to be able to keep the app running (e.g. in the system tray) and at startup.

Ideally, this configuration would also allow an option for opening multiple photos under the same process (rather than creating a new process, which introduces another delay).

**Comment by fire-eggs** [comment]
You didn't mention which version of IG you are using. In IG Moon 5.5.9.5 and later, a change was made to hopefully improve startup time. Download from [ImageGlass Moon](http://imageglass.org/moon).

You mention a couple of good options, we're still looking into ways to speed this up. Thanks!

**Comment by ultravelocity** [comment]
I was on 5.5.7.26. I updated to Moon 5.5.10.28 and it is definitely faster. Thanks for the tip. Still think it would be great to have an option to keep the process running and just bring it to the foreground.

**Comment by d2phap** [comment]
You can uncheck the option in Settings:
Allow multiple instances of the program

**Comment by ultravelocity** [comment]
Yes, but still need to be able to view photos side by side, so multiple forms in a single process would be great.

**Comment by d2phap** [comment]
I implemented asynchronous loading to improve startup time. 
Please help to test v5.5.12.16: https://imageglass.org/moon

Merge this to #462
