### ISSUE TITLE
Preloading next image while viewing current image

### ISSUE THREAD

**Issue by ultravelocity** [d2phap/ImageGlass#447]
### Is your feature request related to a problem? Please describe.
Slow to navigate to the next photo sometimes.

### Describe the solution you'd like
Similar to the image booster that keeps the previous image in memory, it would be nice to preload the next image while viewing the current one.

### Describe alternatives you've considered
None

### Additional context
None

**Comment by fire-eggs** [comment]
Hey! Great idea! Thanks!

**Comment by d2phap** [comment]
The current app auto-preloads the next 2 and previous 2 images to memory. 
The more images preloaded, the more memory used. 

To boost up the loading time, we can change this number to 10, but need to think about memory carefully.

https://github.com/d2phap/ImageGlass/blob/master/Source/Components/ImageGlass.Core/ImgMan.cs#L84-L108

**Comment by da3dsoul** [comment]
You make it sound like RAM is not plentiful. ImageGlass is pretty good about RAM. Honestly, this should be a setting. If people want a light version, they can set it to 0. I'm reading from a network drive over Wi-Fi, so I'd set it to to something more like 10 or 20.

**Comment by d2phap** [comment]
@da3dsoul thanks for sharing your thought.

**Comment by da3dsoul** [comment]
Another interesting idea if RAM is a concern is to have a setting for maximum preload size. For example, you might have a folder with hundreds of 46kB images vs a folder with hundreds of 4MB images. If you have the maximum set to 10MB, then it'll preload lots of the small images and only a few large ones.
If you are actually on a RAM constrained machine, then the ability to specify this is more reasonable than "preload 2 images".

**Comment by da3dsoul** [comment]
Something that I've noticed and would be useful is a cache around the current image. I often download files in batches from Pixiv, and I end up with many copies of the same image with various differences (no glasses or something). I flip back and forth between 5-6 images to find which one(s) I like best and delete the rest. With the current caching system, it seems to keep the previous image and the two next images. If I could keep something like the 5 previous and the 10 next, then this would be much smoother.

Obviously, this is something that only some people would want, but I think it's a rather common use case.

**Comment by d2phap** [comment]
Implemented in v7.0.
User can select the number of preloaded files in Settings dialog.

**Comment by mlewand** [comment]
@d2phap I know it is tricky to tune the default value, but it seems to be a little bit on conservative side to me. I initially thought this feature didn't exists and wanted to fill an issue for a feature request.

Changing the default value from 1 to 4 made it working well for me.

**Comment by LoganAC34** [comment]
Could this option be increased from the max of 10 currently to whatever number we want? I'm constantly getting slowed down by it trying to load the next picture. Being able to increase the cache to 20 would help.

**Comment by d2phap** [comment]
@HVCFOG3Y34 
It will stress the CPU when increasing this value. My recommendation is from 1 to 3

**Comment by LoganAC34** [comment]
@d2phap
It doesn't seem to stress my machine too much having it at 10. The images I'm trying to load are on a network drive which I think is slowing it down. When I reach the end of the cached images, it starts slowing down and my network usage goes up. It would be nice to have the option to up the image cache mount more. Maybe add a warning saying setting it higher than a certain amount will tax the CPU more.

Im not a programmer, so obviously you'd know better. I want to say thanks for this awesome program by the way!

**Comment by d2phap** [comment]
Thanks, ImageGlass currently limits max 10 items. If you set to 10, ImageGlass will load 21 (10 x 2 + 1) image files into RAM at the same time. It causes high CPU during startup, after that, if you navigate by Arrow keys, it only loads uncached images. 
I will think about supporting up to 20
