### ISSUE TITLE
Request: arrow button navigation on hover on right & left edge, even I wrote the code for you

### ISSUE THREAD

**Issue by AnotherDimension-Ex** [d2phap/ImageGlass#448]
Hi,

This time I wrote the code for you, to ensure you don't have any excuse ^_^
Despite I don't have any knowledge in programing especially with c#

I know this request already was for a while, and asked by some users including me.
So I'm asking you to add an option to allow us this option.

**Take a deep look to this image, to ensure it's a useful option.**

![](https://image.ibb.co/jFbBa0/IG-GIF.gif)
<p>
I know you don't need any Instructions, but I did it anyway.
<br>

<blockquote style="color: #000 !important;">
<p><strong>Instructions :</strong></p>
<ul>
<li>Create two button and dock one to the left and to the right.</li>
<li>Button width must be 70px.</li>
<li>Add MouseEnter &amp; MouseLeave event from events manager.</li>
<li>Use attached arrows resources (I created it in Photoshop).<br>
<a href="https://drive.google.com/file/d/1a4k2Eu4LLHovPL-UVvTybVsRAy74h3l8/view" rel="nofollow">https://drive.google.com/file/d/1a4k2Eu4LLHovPL-UVvTybVsRAy74h3l8/view</a></li>
</ul>
<p>Attaching the code for references.</p>
<pre><code>private void LeftArrow_Click(object sender, EventArgs e) {
	mnuMainViewPrevious_Click(null, e);
}
private void LeftArrow_MouseEnter(object sender, EventArgs e) {
	this.LeftArrow.BackgroundImage = Properties.Resources.left_arrow; // Arrow_Left;
}
private void LeftArrow_MouseLeave(object sender, EventArgs e) {
	this.LeftArrow.BackgroundImage = null;
}
private void rightArrow_Click(object sender, EventArgs e) {
	mnuMainViewNext_Click(null, e);
}
private void rightArrow_MouseEnter(object sender, EventArgs e) {
	this.rightArrow.BackgroundImage = Properties.Resources.right_arrow; // Arrow_Right;
}
private void rightArrow_MouseLeave(object sender, EventArgs e) {
	this.rightArrow.BackgroundImage = null;
}
</code></pre>
</blockquote>
<p></p>

<blockquote style="color: #000 !important;">
<p><strong>Some Notes :</strong></p>
<ul>
<li>If loop image option disabled.</li>
<span>  In the first image left arrow should be invisible on hover on left edge.</span><br>
<span>  In the last image right arrow should be invisible on hover on right edge.</span>
<li>If there's only one image in folder both arrows should be invisible.</li>
</ul>
</blockquote>

**Comment by fire-eggs** [comment]
Yup, no excuses!  I'll give it a try! Thank you _very_ much!

**Comment by fire-eggs** [comment]
My thanks for the inspiration and images! Also the opportunity to try ScreenToGif ...

Here is the results of my experiment today. Please take a close look and tell me if you think this 
will be a useful feature:

![test1](https://user-images.githubusercontent.com/9809727/47968706-9b6b6880-e03b-11e8-8b41-7d3480054d1a.gif)

Haven't done any of the enable/disable logic yet ...

**Comment by AnotherDimension-Ex** [comment]
That seems great.

Also, I wonder if it's possible if we could change the arrow image, I have some ideas about how it could look.
Maybe you could make it changeable via the theme folder (as external resource).

Thank you for taking this suggestion!
<br>

![-photo-523582-2](https://user-images.githubusercontent.com/34074375/47969604-19a32b80-e08b-11e8-82ed-80f8ffe85a31.jpg)

**Comment by AnotherDimension-Ex** [comment]
That seems great.

Also, I wonder if it's possible if we could change the arrow image, I have some ideas about how it could look, maybe you could make it changeable via the theme folder (as external resource).

Thank you for taking this suggestion!
<br>

![009](https://user-images.githubusercontent.com/34074375/47970092-d6988680-e091-11e8-9279-aeb914a250bf.jpg)

**Comment by AnotherDimension-Ex** [comment]
I just want it to be customizable with the theme, so everyone can make its own experience.

Also, you have a great idea, I think it will be better if.

**Light theme** - with black outline.
**Dark theme** - without black outline.

Regards,
Another Dimension

**Comment by AnotherDimension-Ex** [comment]
Do you agree if the final result will be something like this?
<br>

**Dark theme without black outline**

![dark](https://user-images.githubusercontent.com/34074375/48009026-e82e6c80-e12b-11e8-9ea1-a22f2cc53020.jpg)


**Light theme with black outline** 

![light](https://user-images.githubusercontent.com/34074375/48009029-e82e6c80-e12b-11e8-8362-3c30bbca3afc.jpg)

**Comment by fire-eggs** [comment]
Since you seem to be able to build IG, for your amusement, I'm attaching my experimental code. It expects the right_arrow and left_arrow resources to have been added to the project. I placed this code at the end of the frmMain constructor.

Not the final form, purely dirty hack

[ig_arrow_exp.zip](https://github.com/d2phap/ImageGlass/files/2549874/ig_arrow_exp.zip)
 level.

**Comment by AnotherDimension-Ex** [comment]
First, I want to mention the important thing is the functionality, and it doesn't matter if the arrow visible or not over the image background.

Try to visit ArtStation they have similar functionality.
https://www.artstation.com/artwork/4lX0k
https://www.artstation.com/artwork/61bXW
https://www.artstation.com/artwork/LEgyR

About the light and dark theme I just suggested to be similar to photos app (windows 10 default photo viewer), when choose dark theme the arrow will be white and when chose the light theme the arrow will be dark.

**Comment by AnotherDimension-Ex** [comment]
It's working great.


![04159](https://user-images.githubusercontent.com/34074375/48022342-f4c2bd00-e14b-11e8-9aca-3ddabc4f03fa.png)


Despite that, I note a minor issue, when the focus on the button and lose the focus of imageGlass main form you will see white border.

Maybe that seems weird, but, but the reason it because the button font color (ForeColor) the border will match the ForeColor, if the ForeColor set Red the border will be red.

It seems if "ForeColor" set to transport color the border will be white.

The workaround is making the button font color (ForeColor) match the background color.

```

_btnPrev.ForeColor = GlobalSetting.BackgroundColor;
_btnNext.ForeColor = GlobalSetting.BackgroundColor;
```

Or using something else instead of buttons.

![04156](https://user-images.githubusercontent.com/34074375/48022078-3c951480-e14b-11e8-8689-bb423628607c.jpg)

**Comment by AnotherDimension-Ex** [comment]
It's working great.


![04159](https://user-images.githubusercontent.com/34074375/48022342-f4c2bd00-e14b-11e8-9aca-3ddabc4f03fa.png)


Despite that, I note a minor issue, when the focus on the button and lose the focus of imageGlass main form you will see white border (button border).

Maybe that seems weird,  but the reason it because the button font color (ForeColor) the border will match the ForeColor, if the ForeColor set Red the border will be red.

It seems if "ForeColor" set to transport color the border will be white.

The workaround is making the button font color (ForeColor) match the background color.

```

_btnPrev.ForeColor = GlobalSetting.BackgroundColor;
_btnNext.ForeColor = GlobalSetting.BackgroundColor;
```

Or using something else instead of buttons.

![04156](https://user-images.githubusercontent.com/34074375/48022078-3c951480-e14b-11e8-8689-bb423628607c.jpg)

**Comment by AnotherDimension-Ex** [comment]
About the code, It's working great.


![04159](https://user-images.githubusercontent.com/34074375/48022342-f4c2bd00-e14b-11e8-9aca-3ddabc4f03fa.png)


Despite that, I note a minor issue, when the focus on the button and lose the focus of imageGlass main form you will see white border (button border).

Maybe that seems weird,  but the reason it because the button font color (ForeColor) the border will match the ForeColor, if the ForeColor set Red the border will be red.

It seems if "ForeColor" set to transparent color the border will be white.

The workaround is making the button font color (ForeColor) match the background color.

```

_btnPrev.ForeColor = GlobalSetting.BackgroundColor;
_btnNext.ForeColor = GlobalSetting.BackgroundColor;
```

Or using something else instead of buttons.

![04156](https://user-images.githubusercontent.com/34074375/48022078-3c951480-e14b-11e8-8689-bb423628607c.jpg)

**Comment by fire-eggs** [comment]
Excellent! I'd noticed the issue but hadn't found a fix ... Thank you for the help!

**Comment by AnotherDimension-Ex** [comment]
I'm afraid to tell you the fix will not work correctly.
The border will be over the image background.

Probably it better using something else instead of button!

**Comment by AnotherDimension-Ex** [comment]
Finally, I found the better workaround.
```
_btnPrev.GotFocus += (object sender, EventArgs e) => { _btnPrev.NotifyDefault(false); };
_btnNext.GotFocus += (object sender, EventArgs e) => { _btnNext.NotifyDefault(false); };
```

**Comment by AnotherDimension-Ex** [comment]
This Is the correct fix.
```
_btnPrev.GotFocus += (object sender, EventArgs e) => { _btnPrev.NotifyDefault(false); };
_btnNext.GotFocus += (object sender, EventArgs e) => { _btnNext.NotifyDefault(false); };
```

**Comment by fire-eggs** [comment]
Worked for me! Thank you!

Learning all sorts of new things today!

**Comment by AnotherDimension-Ex** [comment]
Hi @d2phap 

There is another solution if you want to change your mind.

You can hide the buttons when dragging the image.

<pre><code>
// Toggle the timer
private bool isTimer = false;

// picMain_Zoomed
private void picMain_Zoomed(object sender, ImageBoxZoomEventArgs e)
{
    if (!isTimer)
    {
        Timer t = new Timer();
        t.Interval = 500; // wait 500ms
        t.Tick += t_Tick;
        t.Start();
        isTimer = true; // stop calling the timer

        // Hide the button when zooming
        _btnNext.Hide();
        _btnPrev.Hide();
    }
}

// Show the buttons after 500ms
private void t_Tick(object sender, EventArgs e)
{
    Timer t = (Timer)sender;
    t.Stop();
    isTimer = false;
    _btnNext.Show();
    _btnPrev.Show();
}

// MouseDown
private void picMain_MouseDown(object sender, MouseEventArgs e)
{
    // Hide the button on MouseDown
    _btnNext.Hide();
    _btnPrev.Hide();

}

// Create MouseUp event for picMain
private void picMain_MouseUp(object sender, MouseEventArgs e)
{
    // Show the button on MouseUp
    _btnNext.Show();
    _btnPrev.Show();
}
</code></pre>

**Comment by AnotherDimension-Ex** [comment]
Hi @d2phap 

There is another solution if you want to change your mind.

You can hide the buttons when pans the image.

<pre><code>
// Toggle the timer
private bool isTimer = false;

// picMain_Zoomed, hide the buttons when zooming
private void picMain_Zoomed(object sender, ImageBoxZoomEventArgs e)
{
    // Issue: the timer will delay the navigation of next/prev image when the user keeps pressing the button fast
    // Workaround: enabling the timer after next/prev image loaded
    if (!isTimer)
    {
        Timer t = new Timer();
        t.Interval = 500; // wait 500ms
        t.Tick += t_Tick;
        t.Start();
        isTimer = true; // stop calling the timer

        // Hide the buttons when zooming
        _btnNext.Hide();
        _btnPrev.Hide();
    }
}

// Show the buttons after 500ms
private void t_Tick(object sender, EventArgs e)
{
    Timer t = (Timer)sender;
    t.Stop();
    isTimer = false;
    _btnNext.Show();
    _btnPrev.Show();
}

// picMain_MouseDown
private void picMain_MouseDown(object sender, MouseEventArgs e)
{
    // Hide the buttons on MouseDown
    _btnNext.Hide();
    _btnPrev.Hide();

}

// Create MouseUp event for picMain
private void picMain_MouseUp(object sender, MouseEventArgs e)
{
    // Show the buttons on MouseUp
    _btnNext.Show();
    _btnPrev.Show();
}
</code></pre>

**Comment by AnotherDimension-Ex** [comment]
Hi @d2phap 

There is another solution if you want to change your mind.

You can hide the buttons when pans the image.

<pre><code>
// Toggle the timer
private bool isTimer = false;

// picMain_Zoomed, hide the buttons when zooming
private void picMain_Zoomed(object sender, ImageBoxZoomEventArgs e)
{
    // Issue: the timer will delay the navigation of next/prev image 
    // When the user keeps pressing the button fast, get delay 10ms
    // Workaround: enabling the timer after next/prev image loaded
    if (!isTimer)
    {
        Timer t = new Timer();
        t.Interval = 10; // wait 10ms
        t.Tick += t_Tick;
        t.Start();
        isTimer = true; // stop calling the timer

        // Hide the buttons when zooming
        _btnNext.Hide();
        _btnPrev.Hide();
    }
}

// Show the buttons after 10ms
private void t_Tick(object sender, EventArgs e)
{
    Timer t = (Timer)sender;
    t.Stop();
    isTimer = false;
    _btnNext.Show();
    _btnPrev.Show();
}

// picMain_MouseDown
private void picMain_MouseDown(object sender, MouseEventArgs e)
{
    // Hide the buttons on MouseDown
    _btnNext.Hide();
    _btnPrev.Hide();

}

// Create MouseUp event for picMain
private void picMain_MouseUp(object sender, MouseEventArgs e)
{
    // Show the buttons on MouseUp
    _btnNext.Show();
    _btnPrev.Show();
}
</code></pre>

**Comment by AnotherDimension-Ex** [comment]
Hi @d2phap 

It's possible to make it similar to FastStone Image Viewer, as the new way is almost the same.
You can make this option not enabled by default.

As I requested before [#414](https://github.com/d2phap/ImageGlass/issues/414)

_Thanks!_

**Comment by d2phap** [comment]
Hi @AnotherDimension-Ex 
Yes it will be same. There will be an option to enable it.
Thanks

**Comment by d2phap** [comment]
Done. Ready for testing https://imageglass.org/moon

**Comment by AnotherDimension-Ex** [comment]
Great, thank you very much.

IMHO, double click event it should be disabled when hover on the left or the right and and Nav arrows visible.
Because when you navigate fast will get double click, instead of next/prev image.

You can make double click only when the mouse cursor in the center only, this will be much more sense.

Thanks!

**Comment by AnotherDimension-Ex** [comment]
Great, thank you very much.

IMHO, double click event it should be disabled when hover on the left or the right and Nav arrows visible.
Because when you navigate fast will get double click, instead of next/prev image.

You can make double click only when the mouse cursor in the center only, this will be much more sense.

Thanks!

**Comment by d2phap** [comment]
Thanks @AnotherDimension-Ex 
Updated your request in https://imageglass.org/moon v5.5.12.11

Btw, there is a big change in this build: 
- Removed Registry settings, all settings are written to `igconfig.xml` file

**Comment by AnotherDimension-Ex** [comment]
**Small note:**
<p>When navigate fast via the Nav arrow, will get some delay, cause (double click)
one click = next image
double click = next image + nothing 

When double click on Nav arrow - expected load 2 image bet the result 1 image.
When double click on next image in toolbar - the result 2 images.

This is not really an issue because picMain have two events oneClick & doubleClick.

I think maybe a solution will be (if it's possible)
<ul>
<li>When hover on next/prev Nav arrow, temporarily remove doubleClick event from picMain.</i>
<li>When hover on next/prev, Make doubleClick load next/prev image.</i>
</ul>

**Comment by AnotherDimension-Ex** [comment]
**Another note:**
<p>ImageGlass randomly crashes when I use Nav arrows.<br>
Unfortunately, there's no clear way to reproduce the issue.
</p>

![04210](https://user-images.githubusercontent.com/34074375/49834258-059aca00-fdad-11e8-83b3-5e005048ed28.jpg)

<pre><code style="height=50px">
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
   at System.Drawing.Bitmap.GetHicon()
   at ImageGlass.frmMain.<>c__DisplayClass70_0.<picMain_MouseMove>b__2()
   at ImageGlass.frmMain.CheckCursorPositionOnViewer(Point location, Action onCursorLeftAction, Action onCursorCenterAction, Action onCursorRightAction)
   at ImageGlass.frmMain.picMain_MouseMove(Object sender, MouseEventArgs e)
   at System.Windows.Forms.Control.OnMouseMove(MouseEventArgs e)
   at ImageGlass.ImageBox.OnMouseMove(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseMove(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3260.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ImageGlass
    Assembly Version: 5.5.12.11
    Win32 Version: 5.5.12.11
    CodeBase: file:///C:/Users/Another/Desktop/ImageGlass_Moon_5.5.12.11/ImageGlass.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
ImageGlass.Services
    Assembly Version: 5.5.6919.41225
    Win32 Version: 5.5.6919.41225
    CodeBase: file:///C:/Users/Another/Desktop/ImageGlass_Moon_5.5.12.11/ImageGlass.Services.DLL
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
ImageGlass.Core
    Assembly Version: 5.5.6918.37074
    Win32 Version: 5.5.6918.37074
    CodeBase: file:///C:/Users/Another/Desktop/ImageGlass_Moon_5.5.12.11/ImageGlass.Core.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
ImageGlass.Library
    Assembly Version: 5.5.6919.38107
    Win32 Version: 5.5.6919.38107
    CodeBase: file:///C:/Users/Another/Desktop/ImageGlass_Moon_5.5.12.11/ImageGlass.Library.DLL
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
FileWatcherEx
    Assembly Version: 1.3.0.0
    Win32 Version: 1.3.0.0
    CodeBase: file:///C:/Users/Another/Desktop/ImageGlass_Moon_5.5.12.11/FileWatcherEx.DLL
----------------------------------------
ImageGlass.Theme
    Assembly Version: 5.5.6919.41225
    Win32 Version: 5.5.6919.41225
    CodeBase: file:///C:/Users/Another/Desktop/ImageGlass_Moon_5.5.12.11/ImageGlass.Theme.DLL
----------------------------------------
ImageGlass.ImageBox
    Assembly Version: 5.5.0.0
    Win32 Version: 5.5.0.0
    CodeBase: file:///C:/Users/Another/Desktop/ImageGlass_Moon_5.5.12.11/ImageGlass.ImageBox.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
ImageGlass.ImageListView
    Assembly Version: 11.0.0.4
    Win32 Version: 11.0.0.4
    CodeBase: file:///C:/Users/Another/Desktop/ImageGlass_Moon_5.5.12.11/ImageGlass.ImageListView.DLL
----------------------------------------
Magick.NET-Q16-AnyCPU
    Assembly Version: 7.9.0.0
    Win32 Version: 7.9.0.2
    CodeBase: file:///C:/Users/Another/Desktop/ImageGlass_Moon_5.5.12.11/Magick.NET-Q16-AnyCPU.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
</code></pre>

**Comment by AnotherDimension-Ex** [comment]
Thank you @d2phap 
Everything's working fine.
