### ISSUE TITLE
SVG viewing

### ISSUE THREAD

**Issue by LuisMCerpa** [d2phap/ImageGlass#450]
SVG viewing with ImageGlass is not good enough because if i use zoom in i can see pixels, if i try that SVG files with Chrome explorer the file is perfectly seen even at maximum zoom in.
Can be using 5.5.10 or 5.5.7 versions of Imageglass.

Below SVG using Imageglass by zoom in 300%
![image](https://user-images.githubusercontent.com/44873035/48208231-1e990100-e351-11e8-9605-5b01e7284255.png)

Next
SVG using Chrome explorer 300% zoom in
![image](https://user-images.githubusercontent.com/44873035/48208341-59029e00-e351-11e8-817b-9468e49ed342.png)

Can you explain if i can do something to improve the quality?
Please attached the file for your testing.

[C_20cm_svg.zip](https://github.com/d2phap/ImageGlass/files/2562365/C_20cm_svg.zip)

I would hope that Imageglass shows the SVG with the same quality of Chrome explorer.

Thank you in advance
Best regards
Luis Morales

**Comment by d2phap** [comment]
Thanks for the issue, it is a duplication of #421
