### ISSUE TITLE
Shortcut for changing 'image loading order'

### ISSUE THREAD

**Issue by d2phap** [d2phap/ImageGlass#456]
From Pedro Squiieep <volbeatc64@...>

Hello!

I would love so much to be able just browse images in random order and then when momentarily needed change the loading order of images with keyboard shortcut or by pressing button on a toolbar. Specifically, I would like to have toggle shortcut from 'random' order to 'name (default)' order back and forth with key stroke / button press.

**Comment by AnotherDimension-Ex** [comment]
Great idea. thanks you very much.

It's will be great if you could make IG keyboard shortcuts customizable, maybe you could make a tab for shortcuts in the settings.

**For references.**

![04187](https://user-images.githubusercontent.com/34074375/48810301-9eec3880-ed39-11e8-893e-231df58f6e11.png)

**Comment by AnotherDimension-Ex** [comment]
Great idea. thank you very much.

It's will be great if you could make IG keyboard shortcuts customizable, maybe you could make a tab for shortcuts in the settings.

**For references.**

![04187](https://user-images.githubusercontent.com/34074375/48810301-9eec3880-ed39-11e8-893e-231df58f6e11.png)

**Comment by d2phap** [comment]
Hi @AnotherDimension-Ex 

> It's will be great if you could make IG keyboard shortcuts customizable

I acknowledge this and will have plan to implement

**Comment by d2phap** [comment]
Add shortcut `Alt+O`

Ready in IG Moon: https://imageglass.org/moon

![image](https://user-images.githubusercontent.com/3154213/99550331-95177180-29f5-11eb-970e-a0d1d460a600.png)
