### ISSUE TITLE
Issue: some animated GIF images play so slowly

### ISSUE THREAD

**Issue by AnotherDimension-Ex** [d2phap/ImageGlass#458]
Hi,

Currently this issue only in ImageGlass Moon, some animated gif images play so slowly than expected.
I suspect this issue has something to do with [#429](https://github.com/d2phap/ImageGlass/issues/429)

This issue not present in ImageGlass 5.5.7.26

<br>

**ImageGlass Moon 5.5.11.23**

![untitled project gif](https://user-images.githubusercontent.com/34074375/49089256-2ec74080-f26c-11e8-9ac9-a961fea5c7ea.gif)

**Original Image**

![project](https://user-images.githubusercontent.com/34074375/49089257-2f5fd700-f26c-11e8-91ec-99c89db7d7ef.gif)

**Comment by fire-eggs** [comment]
Thanks for the report & sample - I'll take a look!

**Comment by d2phap** [comment]
Updated new IG Moon 5.5.11.28
https://imageglass.org/moon
