### ISSUE TITLE
Remove default viewer message

### ISSUE THREAD

**Issue by ITManVideos** [d2phap/ImageGlass#461]
I use the command line igtasks to set the default extensions but it gives a message box saying "ImageGlass as set as a default viewer app successfully".
Is there a way to stop that message box coming up as I am testing this with PDQ Deploy and it does not continue unless you click OK on that message box.
Thanks

**Comment by d2phap** [comment]
Hi @ITManVideos ,

You cannot disable the message box in the current version. 
I just added `--no-ui` argument for this issue. 

https://github.com/d2phap/ImageGlass/blob/bb599650db7af8051773ff155d0466ef78612960/Source/Ultilities/igtasks/Program.cs#L97-L107


You can download the attached zip and replace to the old `igtasks.exe` in ImageGlass 5.5
[igtasks.zip](https://github.com/d2phap/ImageGlass/files/2625696/igtasks.zip)

Hope it works!

**Comment by d2phap** [comment]
Changed: 
- Removed `--no-ui` argument
- Command `regassociations` will no longer show message box. The process will return `0` on success, `1` on error.
- The message box was moved to main project for localization.
