### ISSUE TITLE
Improve "Scale Window to Actual Image Dimensions" (Ctrl+M)

### ISSUE THREAD

**Issue by Hoowah** [d2phap/ImageGlass#468]
Issue 1:

Currently when you activate Ctrl+M, the window is always resized in place and stays in the same location. This is typically the best behavior when the image is small enough to fit on screen.

But if the image is larger than the display resolution, the resulting window size will always scale off screen. The user has to drag the window back to correct it.

This can also happen with smaller images if Ctrl+M is activated when the image window is too close to the right/bottom screen boundary, but it's probably not a problem for typical use.

A simple solution would be to auto center the window if image size exceeds screen size.

Issue 2:

I haven't tested this extensively, but when using Ctrl+M on portrait images that exceed my screen size, the resulting window size is still too large. The vertical dimension goes behind and below my window's task bar. Using Ctrl+M on large landscape images works as expected, and the window fits neatly down to the taskbar.

**Comment by d2phap** [comment]
- Implemented in the new window mode, called: `Window fit (F9)` (its former name is Adapt window to image - `Ctrl+M`).
- User can combine with `Frameless (F10)` mode to make it cooler!

Try the latest build: https://imageglass.org/moon
