### ISSUE TITLE
More customization of mouse or keyboard button functionality

### ISSUE THREAD

**Issue by d2phap** [d2phap/ImageGlass#471]
From: https://groups.google.com/forum/#!topic/imageglass/EFg-InWZjRA

### Prerequisites
- [x] I have written a descriptive issue title
- [x] I have searched [open](https://github.com/d2phap/ImageGlass/issues?q=is%3Aissue+is%3Aopen+label%3A%22%E2%9C%A8+feature+request%22) and [closed](https://github.com/d2phap/ImageGlass/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+label%3A%22%E2%9C%A8+feature+request%22+) issues to ensure it has not already been reported

### Description

ImageGlass is an excellent program that I'm glad to have discovered. I think it is nearly perfect as a light-weight, functional and customizable photo viewer. There is room for some improvements, though, and one of those would be the ability to customize button functionality a bit more.

For example, in the same way that we can set the middle mouse button and scroll-wheel to do whatever action is most suitable for us (thankfully! So much better than Win 10's image viewer), I'd also like to be able to set Double Left-Click to toggle Fullscreen mode (instead of snapping the selected image to 100% zoom, which is currently what it seems to do).

Also, my mouse has 8 buttons on it, and I'd like to be able to set them to perform additional actions. Particularly, I'd like to be able to set Mouse Button 4 and Mouse Button 5 to be Previous Image and Next Image so that I can scroll through a folder of images without moving the mouse around.

**Comment by 4294967296** [comment]
## Request

As it stands now:
Single middle click = Auto zoom (Ctrl + A)
Double middle click = Actual size (Ctrl + 0)
Double left click toggles between the two above options.

The double left click functionality overlaps with the combination of the single and double middle click functionality.

A drop down list for the functionality of the middle button and/or the double left click, also containing a full screen option, would make more sense.

## Recommendation

"Mouse wheel actions" are a part of the "Image" tab, while "Keyboard" is an independent tab, although it contains only a few options.

Maybe an independent tab named "Mouse", placed below the "Keyboard" one, would make more sense, and the "Mouse wheel actions" could become a part of this new tab, along with any additional options hopefully added in the future.

**Comment by vertigo220** [comment]
This could be combined with issue #648 and #953. If this were done, those functions could be added as some of the available options, so users could zoom by scrolling while holding down right-click (#953) or, my preference, by either moving the mouse up and down while holding the RMB or, probably even better, double-clicking the LMB and holding it, then moving the mouse up and down (similar to how zoom is done in many touchscreen apps). And double-clicking could be set, if desired, to switch to full-screen, which would resolve issue #648.

**Comment by d2phap** [comment]
You can do this in [v9.0 beta 2](https://github.com/d2phap/ImageGlass/releases/tag/9.0.2.904).

See more details and example here: https://github.com/d2phap/ImageGlass/issues/991#issuecomment-1238130837
