### ISSUE TITLE
Nearly empty igconfig.xml file in AppData\Roaming\ImageGlass after running portable version

### ISSUE THREAD

**Issue by TheDutchJewel** [d2phap/ImageGlass#474]
When I run the portable version of ImageGlass v6.0.12.27, it stores a nearly empty igconfig.xml file in AppData\Roaming\ImageGlass.
When I remove this file, it's back after I run the portable version again.
If this file is not necessary, can you please remove it in the next version?

**Comment by d2phap** [comment]
Thanks @TheDutchJewel 
Why do you want to remove it?

This file is to write default settings of ImageGlass 6. 
I can remove it in the next version.

**Comment by ZIEXED** [comment]
+1

**Comment by d2phap** [comment]
Fixed this problem with the new ImageGlass Settings component, and it's ready to test in IG Moon version:
https://imageglass.org/moon.

There were some breaking changes in config file, please refer to #653 for further details.
Thanks all!
