### ISSUE TITLE
Use arrows at the corner

### ISSUE THREAD

**Issue by khari3** [d2phap/ImageGlass#478]
Use arrows at the top right corner and in middle right of the photo to change photo's(to go to next photo or previous one) because it reduces mouse movement a lot. Like this  ---

![ig1](https://user-images.githubusercontent.com/43307781/50533693-34f35a00-0b55-11e9-9968-1bf3ca700244.png)

**Comment by khari3** [comment]
How does it reduce mouse movement? -- Because we being right hand mouse users tend to move the cursor from the right side of the monitor, in that way it reduces mouse movement.

**Comment by khari3** [comment]
@phap -- will you add the above feature?

**Comment by d2phap** [comment]
Hi @khari3 

Thanks for your suggestion. 
However, I don't want to provide many options about UI customization which make users dizzy when they open Settings dialog. Some people may love to have the arrows on top right like you, some may want it to be on bottom left, and so on.

Currently, ImageGlass already provides quite a lots option navigate images:
- Shortcuts (Left/Right arrow, PageUp/PageDown)
- Toolbar buttons (can relocate to top / bottom)
- Arrow buttons on the viewer edges
