### ISSUE TITLE
Still there's some issues with nav arrow buttons

### ISSUE THREAD

**Issue by AnotherDimension-Ex** [d2phap/ImageGlass#479]
Hi,

I almost every day get this issue and it becomes like a routine for me.
So I figure share it, in the hope one day may be fixed.

As I reported before IG crash when using Nav arrow buttons [[#448:comment]](https://github.com/d2phap/ImageGlass/issues/448#issuecomment-446390529)
And used "try catch" to handle unexpected error, but it seems this crash something inevitable somehow.
<p>
<h4> After "catch" handle the errors:</h4>
<ul>
<li>No longer arrow cursor (default cursor)</span>
<li>Double click event no longer disabled on the left or the right edge <a href="https://github.com/d2phap/ImageGlass/issues/448#issuecomment-445902587">[#448:comment]</a></li>
<li>Right click context menu options no longer available</span>
<li>IG menu options no longer available</span>
<li>Opening IG menu will lead eventually to crash (sometimes)</span>
</ul>
<p>There's no clear way to reproduce this issue!

<details>
  <summary>Screenshots</summary>

![01](https://user-images.githubusercontent.com/34074375/50545062-90871b80-0c19-11e9-8e30-691811b09278.jpg)

![02](https://user-images.githubusercontent.com/34074375/50545063-90871b80-0c19-11e9-8fda-8b74edf79dc9.jpg)

</details>

**Comment by fire-eggs** [comment]
Using the crash stack from https://github.com/d2phap/ImageGlass/issues/448#issuecomment-446390529 I took a look at the code.

What we've got here is a Handle leak. If I'm correct, there is in fact *two* handle leaks every time the arrow cursors are set! The program behavior (menus blank, no cursor, etc) is also consistent with a Handle leak.  A Windows process has a hard limit to the number of Handles it can create; once the limit is reached, the app will become unstable and likely crash.

So the problem should be reproducible by bouncing back and forth to activate either arrow cursor. Eventually IG will run out of handles and crap out. You can watch the Handle count in Task Manager.

[I'm not in a position to try it myself at this moment ...]

**Comment by fire-eggs** [comment]
Seems I'm wrong about Task Manager - 'handles' it shows are not relevant.

But if I fire up [Process Explorer](www.sysinternals.com) and watch IG, I can see the GDI handles count jump up by ~200 each time the arrow cursor is activated, and it increases every second while the arrow cursor is shown!

That means you can get a fast leak by flipping back and forth, or a slow leak by just having the arrow cursor visible.

My first crash was seen in combination with tweaking a bunch of settings, including switching the theme. There seems to be several resource leaks involved there as well.

Thanks again for the pointer - looks like a couple of areas for improvement.

**Comment by AnotherDimension-Ex** [comment]
Hi @fire-eggs

Are you sure you didn't forget something? or this's on purpose ^_^

```
// this will return ViewNextImage only
using (var cursorIcon = new ThemeImage(LocalSetting.Theme.ToolbarIcons.ViewNextImage.Filename, new Size(iconHeight, iconHeight)).Image)
```

I'm not an expert, but pretty sure.
```
// this will return both
using (var cursorIcon = new ThemeImage(which, new Size(iconHeight, iconHeight)).Image)
```

**Comment by AnotherDimension-Ex** [comment]
Thank you for attempting to fix this issue one more time and for good.

I wonder if there's any easy way to make nav arrow buttons accept double click.
Because when I navigate fast and press two click (double click) I expect load 2 image, but it will load 1 image.

I know this is not an issue because picturebox have two events (one click & double click)
But in theory, I pressed  2 clicks and it's means it should load 2 images. 

**If you compare it with toolbar buttons**
Toolbar buttons double click = 2 images
Nav arrow buttons double click = 1 image

**Comment by fire-eggs** [comment]
> Are  you sure you didn't forget something? or this's on purpose ^_^

Aaarrgh! Yup that's a mistake - copy-pasta error. THANK YOU

**Comment by AnotherDimension-Ex** [comment]
Also, I want to mention if keep hovering on Nav button IG will consume abnormal CPU.
For me about 10%

![04258](https://user-images.githubusercontent.com/34074375/50592417-208cc580-0ea5-11e9-9b32-af9b5c469e32.jpg)

**Comment by fire-eggs** [comment]
Thanks, I'll double-check that!

**Comment by fire-eggs** [comment]
[ImageGlass Moon](https://imageglass.org/upload/moon/ImageGlass_Moon_6.1.0.0.zip) has been updated to 6.1 and should have a fix for these resource leaks.
