### ISSUE TITLE
Settings UI is reset when switching Settings tabs

### ISSUE THREAD

**Issue by 0-0-0-0** [d2phap/ImageGlass#482]
### System information:
 - Windows 7
 - ImageGlass 6.0.12.29

### To Reproduce
1. Open Settings
2. Change anything, do not apply
3. Go, say, from General to Image
4. Go back to General

### Actual behavior:
UI controls look the same as before

### Expected behavior:
State of all tabs is expected to be preserved until the Settings window is closed

**Comment by d2phap** [comment]
This issue is fixed in [ImageGlass 9.0 beta 5](https://github.com/d2phap/ImageGlass/releases/tag/9.0.5.726)
