### ISSUE TITLE
Fails to start when ThumbnailBarWidth is close or greater than WindowsBound

### ISSUE THREAD

**Issue by Otiel** [d2phap/ImageGlass#483]
### System information:
 - Windows OS version: Win10 1809
 - ImageGlass version: 6.0.12.29

### To Reproduce
To get a clean config file:
1. Delete _igconfig.xml_ for a clean startup.
2. Start ImageGlass.
3. Perform the 4 steps of the first launch configuration.
4. Close ImageGlass.

Now to reproduce:
1. Edit _igconfig.xml_ and change:

    ```
    <Item key="IsShowThumbnail" value="True" />
    <Item key="IsThumbnailHorizontal" value="False" />
    <Item key="ThumbnailBarWidth" value="990" />
    ```

    The idea is to set `ThumbnailBarWidth` to a value close or greater than the window width defined in `frmMain.WindowsBound`. In my case, it was set to 1000 by default:

    ```
    <Item key="frmMain.WindowsBound" value="280,125,1000,800" />
    ```
2. Start ImageGlass.

### Actual behavior:
ImageGlass fails to start. No error is displayed.

### Expected behavior:
`ThumbnailBarWidth` should be reset to an appropriate value and ImageGlass should start.

### Screenshots:
![Gif](https://i.imgur.com/oIphLMl.gif)

### Additional context:
It happened to me in the first place without tampering the config file. I'm not sure how though...

**Comment by fire-eggs** [comment]
Yup, I've struggled with this in the past. I thought I fixed 'em all but apparently missed something.

**Comment by fire-eggs** [comment]
Fix available in latest ImageGlass Moon. (https://imageglass.org/moon)
