### ISSUE TITLE
Proportionately long image display times with larger folder sizes

### ISSUE THREAD

**Issue by TacosAreYum** [d2phap/ImageGlass#487]
### System information:
 - Windows OS version: Windows 10 (Version 10.0.15063 Build 15063)

 - ImageGlass version: 6.0.12.29

### To Reproduce
1. Enter any folder with large file size (most noticeable > 1 GB) that was not recently opened.
2. Right Click, Open on any image.
3. ImageGlass will open and hold on a blank background for a proportionate amount of time to the size of the folder.

Tested and successfully reproduced multiple times with 1, 2, 6, and 15 GB folders composing of .jpg and .png. The 15 GB folder produced the most noticeable wait time ~1 min while the 1-2 GB folders were ~10 s at most. 

### Actual behavior:
On my machine, when opening any image from a folder with a large filesize (> 1 GB), there is a delay from **ImageGlass opening and displaying a blank background** to the **image appearing**. This seems to be relative to the filesize of the folder; the opening of images from larger-sized folders tends to cause proportionately longer startup times than the opening of images from smaller-sized folders. 

1. If I try to reproduce the issue a second time immediately after the first reproduction, second reproduction fails without exception (image will load within 2 s). 

2. If after the first reproduction, I navigate away and open some other folders and let a few minutes pass, return to the folder of the first reproduction, and attempt to reproduce, the second reproduction succeeds (image will take an extended amount of time to load). 

### Expected behavior:
Opening any image in any large folder is snappy and does not produce a noticeable wait time (I'd consider > 2 s)

**Comment by fire-eggs** [comment]
I'd done some work in the past to try to optimize the folder scan; perhaps something reverted. I'll see if I can reproduce.

**Comment by d2phap** [comment]
Should be fixed in v9.
IG v9 use asynchronous loading so that loading folder does not block the main thread.
