### ISSUE TITLE
Last ver of IG unable to display PSD files.

### ISSUE THREAD

**Issue by AnotherDimension-Ex** [d2phap/ImageGlass#491]
Hi,

I've noticed that, the latest IG ver unable to display PSD files as used.
But old ver was able to display PSD files.

6.0.12.29 - Not working.
5.5.12.16 - Working.

Thanks!

**Comment by d2phap** [comment]
Hi @AnotherDimension-Ex 
Can you attach or send me the PSD file?

**Comment by AnotherDimension-Ex** [comment]
Hi @d2phap sure.

Usually, I always attach a sample and screenshots and more info.
But this time the reason I didn't do that, because you should be able to reproduce this issue with any PSD file, I thought you had some or you will download one.

Also, before I post this issue I did a lot of tests to ensure it will be reproducible, like save a lot of PSD files from my Photoshop, also I downloaded some PSD files to make sure it doesn't relate to my Photoshop version, test it on my other PC.

[PSD Sample.zip](https://github.com/d2phap/ImageGlass/files/2787535/PSD.Sample.zip)

**Comment by d2phap** [comment]
Hi @AnotherDimension-Ex 
I test with v6.0.12.29, I can open it. Or you can attach screenshot (error message)?

![image](https://user-images.githubusercontent.com/3154213/51618164-b8437800-1f68-11e9-911d-f52690d48658.png)

Make sure `.psd` extension is in the list:

![image](https://user-images.githubusercontent.com/3154213/51618265-f345ab80-1f68-11e9-8e0d-0a60afba7303.png)

**Comment by AnotherDimension-Ex** [comment]
Oh, I don't have `.psd` extension because I deleted it and totally forget about it, because I wanted the Photoshop to be the default and since I just copy IG from my other PC it kept the setting with deleted extension, and the reason old version was able to display it because it has `.psd` extension.

Also, this's the first time I know I must have the extension to make IG display the file type,
and If don't have the extension will get message (file damaged ,corrupted, not supported).

I thought the "File Associations" just make the type not open by default by IG.
Not to make it completely not readable.

Perhaps considered to add some info about this, just in case someone will face the same issue in the future.

Thanks @d2phap
Really appreciate your help.
