### ISSUE TITLE
Suggestion: new icons set

### ISSUE THREAD

**Issue by AnotherDimension-Ex** [d2phap/ImageGlass#492]
Hi,

If you are interested and looking for something new, maybe you can consider my new icons design.

Please take a deep look to the new icons set, and see if you like the new icons or not.
It's totally up to you ^_^

>This pack includes 219 files.
>- All psd files.
>- All png files.
>- .ico files ready.
>
>I made it similar to the original as possible, hope you like it.
> [IG_New_Icons_Set.zip](https://github.com/d2phap/ImageGlass/files/2798917/IG_New_Icons_Set.zip)

![igv](https://user-images.githubusercontent.com/34074375/51785959-c531b880-216e-11e9-8f48-a15bcab66606.jpg)

![03881](https://user-images.githubusercontent.com/34074375/51785968-dda1d300-216e-11e9-90f0-110fbb6f3565.png)

![3](https://user-images.githubusercontent.com/34074375/51157270-26fd4300-1890-11e9-8012-dd7340537a38.png)

**Comment by AnotherDimension-Ex** [comment]
Wonderful, thank you so much ^_^

**Comment by d2phap** [comment]
Just uploaded your icons set to ImageGlass website:
https://imageglass.org/extension-icon/icons-set-anotherdimension-ex-1

**Comment by Slim08** [comment]
Missing AVIF, B64, CR3, HEIF, JXL and QOI icon.

[Missing Ext-Icons.zip](https://github.com/user-attachments/files/17784466/Missing.Ext-Icons.zip)

**Comment by d2phap** [comment]
Thanks @Slim08 for sending the icons, I have updated it at https://imageglass.org/extension-icon/icons-set-anotherdimension-ex-1.

Btw, the icon packs are hosted at: https://github.com/ImageGlass/Theme/tree/main/extension-icons/Icon-set.AnotherDimension-Ex
