### ISSUE TITLE
Opens wrong next image after filtering search results

### ISSUE THREAD

**Issue by ema93a** [d2phap/ImageGlass#493]
### System information:
 - Windows OS version: Windows 10 ver. 1809
 - ImageGlass version: 6.10.12.29

### To Reproduce
1. Open the Windows File explorer
2. Navigate to a folder with multiple .jpg and .svg files
3. Search for ".jpg" files
4. Open any of them and go to the next or previous photo inside ImageGlass

### Actual behavior:
The next and previous images opened both .jpg and .svg files instead of only the .jpg files we have searched for.

### Expected behavior:
The image viewer should have gone through the files found in the search result.

### Screenshots:
![screenshot_1](https://user-images.githubusercontent.com/22559586/52183712-024f1800-280b-11e9-83bc-4655eb9d090a.jpg)

**Comment by d2phap** [comment]
Thanks @ema93a for your issue, however, it is a duplication of #139
Currently, ImageGlass (and most of other apps) doesn't support this feature.
