### ISSUE TITLE
Faster loading of large files

### ISSUE THREAD

**Issue by lukesenna1998** [d2phap/ImageGlass#495]
Well, this feature request is related to a minor issue I have. I often have to open .HDR and .EXR files. And often these files are huge ~500 - 1000 MB but it takes a really long time to load these files. ~30 seconds
While it takes around 10 sec in windows photo viewer and it opens almost instantly because it previews the file and slowly increases resolution.

**Comment by da3dsoul** [comment]
On the inverse, I have a project that is 60000x20000px. While the image itself is currently only 8MB as a crushed PNG, ImageGlass Moon as of https://github.com/d2phap/ImageGlass/commit/2368d7d71f5f7fa104092e0e8519aeeb5c28df3f cannot even open it.

**Comment by wdhwg001** [comment]
I got another example:
![727153](https://user-images.githubusercontent.com/8943519/68131589-67d65d80-ff71-11e9-9aaf-1b75dd0e86dc.jpg)
This image takes ~10s to load in ImageGlass, and costs ~970MB of memory.

In comparison, IrfanView opens it instantly, and takes only ~95MB of memory.

**Comment by d2phap** [comment]
@wdhwg001 
That's weird, I opened your image with IG 7.0.7.26.
It took less than 2 seconds and 111 MB of memory.

![image](https://user-images.githubusercontent.com/3154213/68132399-95afa800-ff59-11e9-84af-f96d62c4fa46.png)

**Comment by wdhwg001** [comment]
@d2phap That's weird, I tried again in 7.0.7.26, it takes ~2s but eats a whopping ~3700MB of Memory. Perhaps it is because there are some huge PSD and TIF files in the same folder?
![image](https://user-images.githubusercontent.com/8943519/68135116-49736080-ff77-11e9-9437-efe791a89a58.png)

**Comment by d2phap** [comment]
@wdhwg001
Can you check the cached image files number?
The bigger number, the more memory consumed.

![image](https://user-images.githubusercontent.com/3154213/68135879-49676680-ff5f-11e9-9e9b-18d105cbe7ba.png)

**Comment by wdhwg001** [comment]
@d2phap Yes you are right. But may I have a feature request of having an option to ignore large images (both file and pixel size) when caching?

**Comment by d2phap** [comment]
[ImageGlass Moon 9.0 beta 3](https://github.com/d2phap/ImageGlass/releases/tag/9.0.3.1225) adds settings:
- `ImageBoosterCacheMaxDimension` to set the max image dimension to cache.
- `ImageBoosterCacheMaxFileSizeInMb` to set the max image file size to cache.
- `ShowImagePreview` to show the preview of the image while it's being loaded.
