### ISSUE TITLE
Touch gestures support (pinch zoom)

### ISSUE THREAD

**Issue by Zusurs** [d2phap/ImageGlass#497]
ImageGlass is one of the best looking, sleek and fastest image viewer for Windows today. But it has a huge drawback that made it virtually useless on my work laptop-tablet - it's missing touch gestures for swipe navigation (right now the only 'touch' gesture is to trying to manage to tap on the narrow edges outside the image to switch to next/previous image) and, most importantly, **pinch-to-zoom**.

I'm using laptop in tablet mode to show shetches to my clients in fullscreen mode, but inability to zoom/swipe between them is simply frustrating to say the least. 

I saw this feature being requested already beack in 2016 - three years ago. Guys, can you please implement this anytime soon? I'd gladly donate more to you, just to have a simple pinch zoom (I'm more than sure that there is at least a dozen almost ready-to-use touch API libraries available on GitHub to implement this feature in like a few hours).

Thanks in advance!

**Comment by d2phap** [comment]
Hi @Zusurs 

Thanks for your post! 
I did research and find some resources in the past.
However, I don't have the touch device 💻 (or touch simulator 😒). So it will take some times.

**Comment by fire-eggs** [comment]
Touch support has been shipped!  [Try the latest build](https://imageglass.org/moon)

The following actions are available:
- swipe left/right for previous/next picture
- rotate in either direction (90-degree)
- zoom in/out at a location via spread/pinch
- zoom in/out via swipe up/down

Caveat: implemented and tested only via emulation!

**Comment by rohitghali** [comment]
Pinch to zoom works... Nothing else does... No two finger scroll vertically or horizontally...

**Comment by not-holar** [comment]
> Pinch to zoom works... Nothing else does... No two finger scroll vertically or horizontally...

this

**Comment by pakoito** [comment]
Pinch and zoom is iffy for me too. The rest don't seem to do well either. May it be incompatibility with the High Precision driver?
