### ISSUE TITLE
Add option to hide Window Title Bar

### ISSUE THREAD

**Issue by rrous** [d2phap/ImageGlass#498]
### Prerequisites
- [x] I have written a descriptive issue title
- [x] I have searched [open](https://github.com/d2phap/ImageGlass/issues?q=is%3Aissue+is%3Aopen+label%3A%22%E2%9C%A8+feature+request%22) and [closed](https://github.com/d2phap/ImageGlass/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+label%3A%22%E2%9C%A8+feature+request%22+) issues to ensure it has not already been reported

### Describe the solution you'd like

In Layout submenu add option to hide TitleBar.
In Additional context is an example what it could be good for ... would be much nicer without TitleBar ;)

### Describe alternatives you've considered

Can be hidden together with toolbar(existing option) - so change of functionality, no change in UI.

### Additional context

<img width="325" alt="HiddenTittleBar" src="https://user-images.githubusercontent.com/2971042/54136408-0549b380-441c-11e9-9eef-890994b03fdd.png">

**Comment by jgodfrey** [comment]
It looks like IG already eliminates the window title bar when in full-screen mode. Are you suggesting that an option should eliminate the title bar when in non-full-screen (windowed) mode? If that's the case, you'd lose access to the standard move, resize, ... features provided in the title bar.

Maybe I don't understand the request?

**Comment by rrous** [comment]
Yes, I mean in Window mode.
The inspiration is from HoneyView. It is possible to unlock both Menu AND Tittle bar there. Both  re-appears, if you move mouse pointer near the upper edge of the window.
But I am afraid they use other technology in HoneyView, because the window looks different ...

**Comment by d2phap** [comment]
Those apps that have a custom windows title bar, will be not compatible with Windows 10’s Sets feature.

**Comment by d2phap** [comment]
It's ready.
You can try `Frameless (F10)` window mode in the latest build of ImageGlass Moon: https://imageglass.org/moon

**Comment by rrous** [comment]
Cool, thanks!
Contribution 10Euro sent via PayPal
