### ISSUE TITLE
Support for BC6H/BC7 in DDS

### ISSUE THREAD

**Issue by Krakean** [d2phap/ImageGlass#501]
Hello
Can you please add read only support for BC6H/BC7 compression that can be found in modern DDS for DX10/DX11?
You can use this library - https://bitbucket.org/Starnick/teximpnet/src - as donor, specifically it has "DDS" folder which doesn't depend on entire library, it has implementation for all algorithms that can be found in DDS format.

Purpose: to have ImageGlass as default viewer when working with game assets (specifically - textures)

**Comment by d2phap** [comment]
Hi @Krakean 
Can you send sample DDS files that use BC6H/BC7 compression?
ImageGlass uses Magick.NET - a wrapper of ImageMagick to read image files.

**Comment by Krakean** [comment]
@d2phap for example, this one - https://nofile.io/f/ZKfZtK5ENSk/Boat_1.DDS (BC7)
Its produced by AMD's Compressonator (https://github.com/GPUOpen-Tools/Compressonator)

>ImageGlass uses Magick.NET - a wrapper of ImageMagick to read image files.

Oh, its sad. Nevertheless, seems like ImageMagick's DDS decoder -https://github.com/ImageMagick/ImageMagick/blob/master/coders/dds.c - supports only pretty basic DXT set - 1/3/5. :(

**Comment by d2phap** [comment]
So please open a request in ImageMagick, I will instantly update the lib once it supported.
