### ISSUE TITLE
JP2 support request

### ISSUE THREAD

**Issue by kamilmirza** [d2phap/ImageGlass#502]
### Prerequisites
- [x] I have written a descriptive issue title
- [x] I have searched [open](https://github.com/d2phap/ImageGlass/issues?q=is%3Aissue+is%3Aopen+label%3A%22%E2%9C%A8+feature+request%22) and [closed](https://github.com/d2phap/ImageGlass/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+label%3A%22%E2%9C%A8+feature+request%22+) issues to ensure it has not already been reported

greetings can you guys add JP2 support?

**Comment by d2phap** [comment]
Hi @kamilmirza 

You can just add new extension `.jp2` in File Associations tab.
ImageGlass uses ImageMagick library to read image files, as long as ImageMagick supports the file type, ImageGlass will do, too.

![image](https://user-images.githubusercontent.com/3154213/54128567-54f1a480-4447-11e9-8798-7fb6f4a7c0a3.png)
