### ISSUE TITLE
Support for Webp animated format

### ISSUE THREAD

**Issue by paulomanrique** [d2phap/ImageGlass#508]
As the title says.

**Comment by d2phap** [comment]
Updated:
Webp animated format is already  supported in the latest version of Magick.NET, so in the ImageGlass Moon, user can see the first frame of the Webp file.

**Comment by andreisilv** [comment]
Will it ever support?

**Comment by d2phap** [comment]
Webp format will be supported in the new app of ImageGlass, the first preview version is coming in a month or two

**Comment by securitytime** [comment]
+1 for animated webp images

**Comment by dr-bing** [comment]
+1 - would be amazing to have this.

Thrilled that this is being worked on for version 9.0!

**Comment by ncx9** [comment]
Thanks for working on this! Would be fantastic to have.

**Comment by d2phap** [comment]
Add support for WEBP animated format in the latest build of ImageGlass Moon 8: https://imageglass.org/moon and [ImageGlass Moon 9.0 Beta 1](https://github.com/d2phap/ImageGlass/releases/tag/9.0.1.514).

Please note this implementation is not native (yet). ImageGlass converts WEBP to GIF and plays it

**Comment by Aphotic** [comment]
still cannot open .webp
created a new post aswell: #2178 

<img width="2553" height="1321" alt="Image" src="https://github.com/user-attachments/assets/383e2e09-a3c0-4750-a8fd-ea621a394a73" />

<img width="840" height="543" alt="Image" src="https://github.com/user-attachments/assets/88e08955-9722-4a6c-8c32-8338515ee05b" />

Version: 9.3.2.520 
win 10
