### ISSUE TITLE
Not refreshing when file changed; suspect using windows "date" field instead of "date modified"

### ISSUE THREAD

**Issue by jimonmars** [d2phap/ImageGlass#509]
### System info:
- ImageGlass version: ____6.0.12.29____
- OS version: ____Windows 10 Home____

### Expected behavior:
____Imageglass would refresh images when they change____

### Actual behavior:
____does not refresh, and refresh button does nothing____

### Steps to reproduce:
1. ____open a image in ImageGlass  from a directory with multiple images____
2. ____modify one image in inkscape (or other program that triggers windows' 'date' bug)____
3. ____ImageGlass does not refresh the image____

### Other info:
____windows has a field in explorer called 'date' which is often just a random number.  Usually inkscape will change this, but it will sometimes be the date of another file in the directory...not the actual modified date.  I suspect that ImageGlass is using this to determine if the file is changed. It should use the Windows' "Modified Date" instead.  I suspect this will allow the program to refresh correctly.____

**Comment by jimonmars** [comment]
Just found more info:

If ImageGlass is displaying the png file that is being output, the error does not occur.  It only occurs when editing a different file than the one currently displayed.  Navigate to the newly changed file and it will not be updated.  The only way to refresh it is to re-save it again, or by closing ImageGlass and re-opening.

**Comment by d2phap** [comment]
Hi @jimonmars 

When saving image, some softwares delete the image file and create it again which, i think, mostly causes the issue. In this case, ImageGlass will remove that file from the list, and add again when it created.

> The only way to refresh it is to re-save it again, or by closing ImageGlass and re-opening.
You can reload the image which skips caching (_Main menu > Reload image_, or _Ctrl + F5_).

**Comment by jimonmars** [comment]
Thanks for the quick reply!  Newbie to ImageGlass...so far it looks really awesome.

**Comment by d2phap** [comment]
Welcome @jimonmars !
You can always ask other questions if any.
