### ISSUE TITLE
Nikon RAW photos (.NEF)

### ISSUE THREAD

**Issue by d2phap** [d2phap/ImageGlass#51]
From Jaime McLellan:
https://plus.google.com/u/0/b/111172305613102428889/103834147987228154729/posts/g3UuxqxXWgq

I really love the ImageGlass browser and all its features, superior to windows standard viewers... but I'm currently having a problem viewing Nikon RAW photos (.NEF). Is there going to be support for viewing the ".NEF" file type?

**Comment by jnickg** [comment]
ImageGlass looks awesome and NEF support would make it even better. I'd like to try adding support for this... @d2phap—is there any reason we can't use the Nikon NEF SDK?

**Comment by d2phap** [comment]
Hi @jnickg 
ImageGlass has been using ImageMagick lib since version 4.0
Basically, it should support RAW formats but there are some extra requirements.

The latest build of ImageGlass Moon has supported WIC - which supports RAW formats as well.
http://www.imageglass.org/moon
But I haven't tested.

**Comment by d2phap** [comment]
`RAW` formats are supported in v4.5

**Comment by jnickg** [comment]
@d2phap -- Thanks for doing this. However, when I try on the latest version, it looks like if I open a NEF file, I get this error:

![image](https://user-images.githubusercontent.com/2337536/35551595-ada93ec8-0544-11e8-9de0-1eaaa6eae3dc.png)

My version info:

![image](https://user-images.githubusercontent.com/2337536/35551615-c38dac6a-0544-11e8-971c-2f960d8180aa.png)

**Comment by d2phap** [comment]
Hi @jnickg,

I tested with these sample files in the `5.0.1.28` version: http://www.mannyphoto.com/D700D3/
It works.

Please be noted that:
- `v5.0` is still under development. It's required `.NET Framework 4.7.1` (`Windows 7 SP1` or later) to run.
- `RAW formats` supported by `Windows Imaging Component` (WIC), ImageGlass just takes advantage of this codec.

If it's possible, it would be great if you can share your sample file for better diagnostic.
Thanks

![image](https://user-images.githubusercontent.com/3154213/35552080-44154798-05cd-11e8-8c46-c2de09c5c7e5.png)

**Comment by jnickg** [comment]
Hey @d2phap, thanks again for the reply. A fresh download seemed to resolve the issue, however I am seeing weird behavior. When I run the portable 5.0.1.28 download from my Downloads folder, I can load the NEF file:
![image](https://user-images.githubusercontent.com/2337536/36528959-b66c0ab6-176b-11e8-91d6-ff17ab70ba25.png)
However, when I manually created a C:\Program Files\ImageGlass and copy the same files, the Open dialog didn'tinclude NEF files and forcing it to try opening a NEF file fails.

I think what happened is when I uninstalled an older version of ImageGlass, the HKEY_CURRENT_USER keys were not removed. Once I deleted those, it now works.

Anyways, I appreciate the support, and can now open _all_ of my photos with ImageGlass! Thanks again for the great application :-)

**Comment by d2phap** [comment]
Hi @jnickg 

Since version `4.5`, ImageGlass has run under `portable mode` if possible. The `portable mode` writes all configs into `igconfig.xml` file which saved in local hard disk. 
If ImageGlass doesn't have `write` permission of its installed folder, it will run under `normal mode` - which writes configs to Windows Registry.

In your case, the folder `C:\Program Files\` is system folder, ImageGlass switches to `normal mode` - uses Windows Registry. You need to clear the configs of the previous version.

:)
