### ISSUE TITLE
Background of collapsed menu white instead of following theme color

### ISSUE THREAD

**Issue by SheepyDev** [d2phap/ImageGlass#511]
### System information:
 - Windows OS version: 1809
 - ImageGlass version: 6.0.12.29

### Actual behavior:
The background is white instead of following theming colors.
The screenshot below should explain it.

### Screenshots:
![Screenshot](https://i.imgur.com/oSDpY3H.png)

**Comment by d2phap** [comment]
I noticed it long time ago but i didn't know how to customize the overflow button and its dropdown.
Thanks Goodness, when you created this issue, I tried again and I could do it!

### Color schemes in theme pack (`*.igtheme\config.xml`):
- Ellipsis icon (`...`): use `statuscolor` value.
- Button background:
  - Normal state: use `topbarcolor` value.
  - Hover state: lighten normal state 15%.
  - on dropdown opening: darken normal state 15%.
- Dropdown background: use `topbarcolor` value.

### Screenshots:
#### Normal state:
![image](https://user-images.githubusercontent.com/3154213/55678729-22957300-5931-11e9-96b5-39ac8ad5acd7.png)

#### On hovering:
![image](https://user-images.githubusercontent.com/3154213/55678735-36d97000-5931-11e9-9b9a-673a550d4f0d.png)

#### On dropdown opening:
![image](https://user-images.githubusercontent.com/3154213/55678750-553f6b80-5931-11e9-82b9-91cc43029f82.png)

#### In light theme:
![image](https://user-images.githubusercontent.com/3154213/55678756-71430d00-5931-11e9-9174-c05cb591c01d.png)

**Comment by d2phap** [comment]
Available in IG Moon https://imageglass.org/moon
