### ISSUE TITLE
Ability to change toolbar button size

### ISSUE THREAD

**Issue by d2phap** [d2phap/ImageGlass#513]
### Is your feature request related to a problem? Please describe.
- Remaining the same button size in high resolution screen will make toolbar buttons tiny.
- Some people want different sizes of toolbar button
- Bigger button size, better UX in touch screen

### Describe the solution you'd like
- Allow user to manually change button size in settings
- Button size must remain in square ratio
- The size value is based on `Constants.TOOLBAR_ICON_HEIGHT = 20` (DPI 100%)
- Support custom button size in theme pack.

**Comment by fire-eggs** [comment]
See also Issue #222

**Comment by GitAlexToTheGreek** [comment]
This would be appreciated, please.

**Comment by gsomix** [comment]
Hello! I would like to work on it to familiarize with ImageGlass code base. Could you give me a tip where to start? Thank you!

**Comment by d2phap** [comment]
Hi @gsomix 

My rough implementation:

### 1. Introduce new setting
- You need to introduce new setting for toolbar size in https://github.com/d2phap/ImageGlass/blob/develop/Source/Components/ImageGlass.Settings/Configs.cs
- Suggest the name is `ToolbarIconHeight`
- Load / save value from config

### 2. Add UI for the new setting
- You need to add UI for the new setting in frmSetting.cs, tab Toolbar. I suggest to use numeric box!
- Load `ToolbarIconHeight` value to the numeric box
- Save setting value to `ToolbarIconHeight`

### 3. Extend function of rendering toolbar icon
- Pass andreplace `Constants.TOOLBAR_ICON_HEIGHT` by the `ToolbarIconHeight` in  `GetCorrectBaseIconHeight` function.
- ...


## Test cases
1. Change size in settings, click Apply, then switch to main window
2. Change size, and restart app
3. Change DPI

**Comment by gsomix** [comment]
@d2phap Thank you! I'll take a look. Could you please assignee this task to me?

**Comment by d2phap** [comment]
Thanks for helping!

**Comment by d2phap** [comment]
Ready for testing in the latest build of IG Moon https://imageglass.org/moon
