### ISSUE TITLE
Request: respect GIF loop count

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#516]
From Google Group:

i wanted to sugegst a little feature for this awesome software. you see i sometimes create for my slideshows a Animated Gif image, but sometime it's not necessarily looped, it only plays once, with the "photo" application by microsoft, this is recognised and the gif is played once. whereas in Imageglass no matter if the Gif animation is looped or not it will loop it endlessly when it's open. it would be very awesome if Imageglass could make the difference between a loop animated gif and a not looped one.

best Regards,

SpeendaSh

Example non-looping file provided by SpeendaSh:
![test-b](https://user-images.githubusercontent.com/9809727/56461967-1c6bb180-6389-11e9-93f4-27d060f8c33b.gif)

One I created using [ezgif](https://ezgif.com/loop-count):
![ezgif com-gif-maker](https://user-images.githubusercontent.com/9809727/56461969-4a50f600-6389-11e9-82a9-bc737d8a5ded.gif)

**Comment by d2phap** [comment]
Shipped in IG Moon https://imageglass.org/moon
