### ISSUE TITLE
[Feature Request] Bulk Convert Image

### ISSUE THREAD

**Issue by MicrosoftTakeover** [d2phap/ImageGlass#517]
The 'Convert Image' function is very useful, but it only works on one image at a time. What if you could select multiple images on the thumbnail bar using hotkeys like shift+click, ctrl+click, or ctrl+a and then perform the 'Convert Image' operation on all of them?

**Comment by MicrosoftTakeover** [comment]
Closing for now, since there seems to be no interest in this feature.

**Comment by GavanWilhite** [comment]
This is the one feature to get me to switch from IrfranView

**Comment by Clearmist** [comment]
Most people think converting an image has to be done individually so they avoid the hassle or knuckle down and get it done. Tech guys like us will know there are ways of bulk processing images. Having a bulk image processing feature is something ImageGlass can promote heavily and will differentiate itself in a positive way from other image viewers for the people that didn't know this was even possible.

**Comment by dcog989** [comment]
> Closing for now, since there seems to be no interest in this feature.

How did you come to that conclusion?! 

I was just about to ditch FastStone (lack of support for modern formats - AVIF, JXL, WEBP) for ImageGlass until I saw there was no batch function. I would have preferred this (open source) software but sadly XnView it is then....
