### ISSUE TITLE
File browser

### ISSUE THREAD

**Issue by kekkc** [d2phap/ImageGlass#519]
### Is your feature request related to a problem? 
If I search for an image in one folder (e.g. images in folder May) and I don't find it there, I have to either close IG and use the windows explorer to browse for the folder June and reopen IG, or I have to use "open file", browse again to uppger folder (where I don't see thumbnails) and click my way through until I found the correct month. Gets worse if I hide the toolbar.

### Describe the solution you'd like
Would an improvement, if the "open file" folder would show the current one. Would also be great if the "menu button" would be shown, even if the toolbar is hidden (or if it can be integrated in the window title bar, similar to e.g. firefox).

Best (and I guess also most complex one) would be an integrated file browser ;)

**Comment by d2phap** [comment]
Hi @kekkc 
There is an enhancement created #506 that will make it easier to search an image file in the viewing list.

> Best (and I guess also most complex one) would be an integrated file browser ;)

File browser will come with many unnecessary functions that makes IG bloated.

**Comment by d2phap** [comment]
I won't implement file browser to avoid being bloated
