### ISSUE TITLE
"View actual size" doesn't reset scrolling

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#52]
[I'm sorry, I haven't figured out git branches yet, so here is an issue report rather than a pull request.]

Symptoms:
 1. Open an image (preferably one which is smaller than the screen)
 2. Zoom-in a few times (preferably so the top of the zoomed image is off the screen)
 3. Click on the View-Actual-Size toolbar button.

Note the image is now scrolled off the top of the screen.

My (local) fix was to call image refresh in mnuMainActualSize_Click().

**Comment by fire-eggs** [comment]
My mistake. Invoking `mnuMainRefresh_Click` from `mnuMainActualSize_Click` breaks "View Actual size" when the image is _larger_ than the window size.

I need to ponder the solution some more...

**Comment by d2phap** [comment]
Just need to add this line to reset image position:

picMain.ScrollTo(0, 0, 0, 0);
