### ISSUE TITLE
Option to load image top left / center position

### ISSUE THREAD

**Issue by d2phap** [d2phap/ImageGlass#521]
Requested by Vasilis at: https://groups.google.com/forum/#!topic/imageglass/DMHyPW94Bmc

> is it possible to load images with default scroll to upper left of the image?
> It would be most useful when loading multiple large size images and don't want to lock "fit height".
> Currently images are loading centered.

**Comment by d2phap** [comment]
Ready in https://imageglass.org/moon

**Comment by leo1115** [comment]
hi sorry for replying to old thread but can you explain how to achive this in imageglass ? that is load images with default scroll to upper left of the image?

i cant find any such option in the settings.
