### ISSUE TITLE
Files with no extension will be loaded

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#53]
[As I don't yet understand git branching, here is an issue rather than a pull request.]

The `LoadImageFilesFromDirectory` method will include files with no extension. This is due to the `Contains()` call returning true when the file extension is empty.

My local fix was to replace this line:
`if (GlobalSetting.SupportedExtensions.Contains(Path.GetExtension(f)))`
with the following:

    string extension = (Path.GetExtension(f) ?? "").ToLower();
    if (extension.Length > 0 && GlobalSetting.SupportedExtensions.Contains(extension))

**Comment by d2phap** [comment]
Thanks!
About git branching, I will split master branch into develop and master. Master branch is completely source code for a release, while develop branch contains bug fixes, feature development...
