### ISSUE TITLE
Quit in Fullscreen mode -> Exception on next launch

### ISSUE THREAD

**Issue by moette** [d2phap/ImageGlass#531]
### System information:
 - Windows OS version: Win 10, Current
 - ImageGlass version: Moon_6.1.5.12

### To Reproduce
1. View a pic
2. Set fullscreen mode
3. Exit using Alt+F4
4. Restart IG 

### Actual behavior:
System.ArgumentOutOfRangeException: Der Index lag außerhalb des Bereichs. Er darf nicht negativ und kleiner als die Sammlung sein.
Parametername: index
   bei System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   bei System.Collections.Generic.List`1.get_Item(Int32 index)
   bei ImageGlass.Heart.Factory.GetFileName(Int32 index)
   bei ImageGlass.frmMain.SaveConfig()
   bei ImageGlass.frmMain.FullScreenMode(Boolean enabled, Boolean changeWindowState, Boolean onlyShowViewer)
   bei ImageGlass.frmMain.mnuMainFullScreen_Click(Object sender, EventArgs e)
   bei System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   bei System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.PerformClick()
   bei ImageGlass.frmMain.LoadConfig(Boolean isLoadUI, Boolean isLoadOthers)
   bei ImageGlass.frmMain.frmMain_Load(Object sender, EventArgs e)
   bei System.Windows.Forms.Form.OnLoad(EventArgs e)
   bei System.Windows.Forms.Form.OnCreateControl()
   bei System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   bei System.Windows.Forms.Control.CreateControl()
   bei System.Windows.Forms.Control.WmShowWindow(Message& m)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.Form.WmShowWindow(Message& m)
   bei ImageGlass.frmMain.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

IG does not work at all.

### Expected behavior:
:-)

### Work around (why missing??)
Setting "IsFullScreen=false" in igconfig.xml to false makes IG start again.

**Comment by fire-eggs** [comment]
Thank you for the report! I'm glad to say a checkin I made on 5/15 has fixed this. I'm certain that Phap will release an IG moon update soon!

**Comment by d2phap** [comment]
Hi @moette 
I have just uploaded IG Moon 6.1.5.25. Please help to check.
https://imageglass.org/moon

Thanks

**Comment by moette** [comment]
Works in  IG Moon 6.1.5.25! Thx,
