### ISSUE TITLE
Drag-and-drop of long file paths doesn't work

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#532]
Fallout from Issue #530. Support is available in Windows for long file paths (longer than 260 characters), but drag-and-drop of a path longer than 260 characters _does not work_.

If long file path support is enabled ([see](https://blogs.msdn.microsoft.com/jeremykuhne/2016/07/30/net-4-6-2-and-long-paths-on-windows-10/)) we get an exception from .NET framework. If long file path support is not enabled, we get nothing at all.

This issue is a placeholder as a reminder to follow up with Microsoft or investigate workarounds.

**Comment by d2phap** [comment]
This should work in v9.0 beta since .NET 6 supports long path by default
