### ISSUE TITLE
Issue: IG cannot open dragged and dropped image directly from local disk path

### ISSUE THREAD

**Issue by AnotherDimension-Ex** [d2phap/ImageGlass#533]
Hi,

I have noticed this issue in IG Moon 6.1.5.12, it seems when drag and drop image from local disk path
e.g. `C:\image.jpg` IG cannot open the image.

I think this issue have related to the path, if it was in a folder IG will be able to open the image from a path like this `C:\Folder\image.jpg`
<br>
<b>Steps to reproduce:</b>
1. Put an image in path like this `C:\image.jpg`
2. Open IG
3. Drag and drop the image to IG

![03954](https://user-images.githubusercontent.com/34074375/58412359-f966a880-807e-11e9-87ba-7883afde848b.png)

**Comment by d2phap** [comment]
Thanks @AnotherDimension-Ex 
Confirmed this bug

**Comment by fire-eggs** [comment]
Thought this was me as I was touching the code for issue #530.

**Comment by d2phap** [comment]
Shipped to IG Moon 6.1.5.28 https://imageglass.org/moon
