### ISSUE TITLE
Request: option to open image in new window

### ISSUE THREAD

**Issue by AnotherDimension-Ex** [d2phap/ImageGlass#534]
Hi,

It really will be very helpful if you could add an option in the context menu to open the image in new instance (new window).

Always when I want for example to compare images or keep some images open, I have to minimize IG and search for the last image was opened to reopen it in a new window to continue browsing and I always losing count especially when I have folder contain a thousand of images.

So I hope you could add this option.

Thanks!

**Comment by d2phap** [comment]
Thanks @AnotherDimension-Ex 
I also want a same thing actually.

> I have to minimize IG and search for the last image was opened to reopen it in a new window to continue browsing and I always losing count especially when I have folder contain a thousand of images.

For now, you can press `Ctrl+Shift+L` or click on `Open file location` menu

**Comment by d2phap** [comment]
This feature is ready in IG Moon: https://imageglass.org/moon

**Comment by AnotherDimension-Ex** [comment]
Hi @d2phap I'm sorry to keep bothering you.

Unfortunately, it seems there's an issue makes the new window open blank, luckily I was able to figure out what it causing this issue.

It seems if the file name contains space or the file path contains space this will make the new window open blank.

`C:\New image.jpg`  file name contains space
`C:\Files\New Images\Main\image.jpg`   file path contains space

**Comment by AnotherDimension-Ex** [comment]
Hi @d2phap I'm sorry to keep bothering you.

Unfortunately, it seems there's an issue makes the new window open blank, luckily I was able to figure out what it causing this issue.

It seems if the file name contain space or the file path contain space this will make the new window open blank.

`C:\New image.jpg` file name contain space
`C:\Files\New Images\Main\image.jpg` file path contain space

**Comment by d2phap** [comment]
thanks @AnotherDimension-Ex !!
I forgot to test the path contains space

**Comment by d2phap** [comment]
Fixed the path contains space issue. 
Ready in https://imageglass.org/moon
