### ISSUE TITLE
animated png support

### ISSUE THREAD

**Issue by whitequill** [d2phap/ImageGlass#535]
### Is your feature request related to a problem? Please describe.
I was just trying to open an animated png file. I found it doesn't open as an animation, though it seems there is some code for an animated png, '.apng'.
I'm not sure if this is a bug or just code that isn't currently active.

### Describe the solution you'd like
support for apng files.

**Comment by d2phap** [comment]
Thanks @whitequill 
ImageGLass doesn't support animated png yet. Please track this request in #396.
This is a duplication.

**Comment by Dhyfer1** [comment]
d
