### ISSUE TITLE
Toolbar Overflow always twice as large as necessary

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#541]
### System information:
 - Windows OS version: Win 10
 - ImageGlass version: Moon 6.1.6.15

### To Reproduce
1. Run IG
2. Shrink the width of the main window so the toolbar overflow is activated
3. Click to drop down the overflow

### Actual behavior:

![image](https://user-images.githubusercontent.com/9809727/59695282-fbbcae00-91b7-11e9-84f6-23448c399f7d.png)

### Expected behavior:
Overflow area should only be as large as necessary.

**Comment by d2phap** [comment]
This issue is fixed in ImageGlass Moon 9.0 beta 1

![image](https://user-images.githubusercontent.com/3154213/169641830-fa9168db-bdcd-4aee-87e0-e64e14678b5a.png)
