### ISSUE TITLE
Corrupted config xml prevents IG from running

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#542]
Reported from Google Group.  No information about Windows version or IG version. 

User somehow got an igconfig.xml file corrupted: as they put it:

> I could send you the ipconfig.xml, but it'd be easier to just tell you: 1600 bytes of 0x00.
>I have no explanation for how that happened, but not very xml-ish...

They mentioned "Uninstalled, reinstalled" which suggests they used the installer and therefore the igconfig.xml file would have been in their AppData\Roaming\ImageGlass folder.

Here is the exception dump reported:

```
Application: ImageGlass.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Xml.XmlException
   at System.Xml.XmlTextReaderImpl.Throw(System.Exception)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlLoader.Load(System.Xml.XmlDocument, System.Xml.XmlReader, Boolean)
   at System.Xml.XmlDocument.Load(System.Xml.XmlReader)
   at System.Xml.XmlDocument.Load(System.String)
   at ImageGlass.Services.Configuration.ConfigurationFile.ReadConfigFile()
   at ImageGlass.Services.Configuration.ConfigurationFile..ctor()
   at ImageGlass.Services.Configuration.GlobalSetting..cctor()

Exception Info: System.TypeInitializationException
   at ImageGlass.Services.Configuration.GlobalSetting.CheckStartUpDirWritable()
   at ImageGlass.Program.Main(System.String[])
```

IG needs to recover gracefully from this: if the config file cannot be loaded, reset to a "known good state". I was able to get the user running again by instructing them how to delete the igconfig.xml file, but IG should be able to do so automatically.

When doing so, need to consider informing the user, so that they are not completely confused when they find their settings have been lost.

**Comment by pdavis68** [comment]
To confirm for you: Yes, I did install with the installer and the file was in AppData\Roaming\ImageGlass as you indicated.

**Comment by d2phap** [comment]
Pushed a fix for this bug.
If the config file is corrupted, IG will silently clear its content and load with no config.

About:
> IG needs to recover gracefully from this: if the config file cannot be loaded, reset to a "known good state". I was able to get the user running again by instructing them how to delete the igconfig.xml file, but IG should be able to do so automatically.

> When doing so, need to consider informing the user, so that they are not completely confused when they find their settings have been lost.

I will implement it in the future (not in this upcoming version)

**Comment by d2phap** [comment]
Fixed this problem with the new ImageGlass Settings component, and it's ready to test in IG Moon version:
https://imageglass.org/moon.

There were some breaking changes in config file, please refer to #653 for further details.
Thanks all!
