### ISSUE TITLE
Square Brackets Break Image Edit Settings

### ISSUE THREAD

**Issue by TheYoke** [d2phap/ImageGlass#543]
### System information:
 - Windows OS version: Windows 10
 - ImageGlass version: 6.0.12.29

### To Reproduce
1. Go to Settings > Edit.
2. Input any of the text boxes with at least one square bracket "[".
3. Save and restart ImageGlass.

### Actual behavior:
After reproducing the problem and restarted ImageGlass. The settings that you just saved are either gone or modified in such a way that render it unusable.

### Expected behavior:
After saved the settings and and restarted ImageGlass. The settings should persist.

### Screenshots:
![ig_bug](https://user-images.githubusercontent.com/19869060/59916541-a5669e00-9449-11e9-82ab-bdec8e8ebd85.png)

### Additional context:
I presume that the problem resides in the way ImageGlass parses the value of "ImageEditingAssociationList" in igconfig.xml settings file and cannot distinguish difference between user inputs and setting templates.

**Comment by d2phap** [comment]
ImageGlass is using `[]` and `|` for splitting text in the configs.
It's not possible to use those chars now

**Comment by fire-eggs** [comment]
Shipped in V7.0
