### ISSUE TITLE
Uninstaller does not delete all registry information

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#546]
Reported in Google+ Group.

### System information:
 - Windows OS version: 10
 - ImageGlass version: 6.0.12.29

### To Reproduce
1. Install imageglass, setting it as default image viewer, associated to all extensions
2. Using Windows 'Default Apps' set IG as the default viewer
3. Use IG
4. Uninstall imageglass, reboot

### Actual behavior:
The ImageGlass uninstall has left a number of Registry entries still in place. This manifests to the user by selecting an image file in explorer, right-click, select "open with", then "choose another app". Image Glass is listed as a choice.

### Expected behavior:
ImageGlass needs to remove any and all registry entries

### Additional context:
Specifically, all the "ImageGlass.AssocFile.*" entries in the registry under HKEY_CLASSES_ROOT (e.g. "ImageGlass.AssocFile.3FR") need to be deleted. 

The registry should also be examined for any other incidences of ImageGlass keys.

**Comment by vinixwu** [comment]
This bug is not fixed yet. I have to remove these registry keys manually, after the uninstall.

**Comment by Hi-ImKyle** [comment]
![image](https://user-images.githubusercontent.com/25551312/149283731-b3be12ab-08fc-4a1d-9b93-9edf3fe081cb.png)

I figured I'd just press Unregister extensions before I uninstall but I just get this error prompt. 

EDIT: Just to make things worse, now my explorer crashes anytime I try to open a folder with images in it, I can't even open the default apps settings page to change it to use the default photos viewer. :/ No offence, but you really should have sorted this out a long time ago.

**Comment by d2phap** [comment]
Starting from v8.4 x64 MSI installer, you can choose the file type associations during installation process, and of course, it will be removed after uninstalled

**Comment by SynapseScribe** [comment]
app still appears as suggestion for gif after being uninstalled

**Comment by soumyasatpathy** [comment]
Now I have tried with "ImageGlass_Kobe_8.8.4.4_x64" but still it leaves junk registry entries all over even after uninstalltion. Moreover the app still comes as suggestion too after uninstalltion. A very badly designed uninstaller for a fantastic app.

**Comment by LorenzMichels** [comment]
Status Closed? The problem still exists with the same problems described earlier

**Comment by DraHD** [comment]
Junk registry after uninstallation is still a problem, and it broke the default app setting for images on Windows 11.

**Comment by zerowiredlein** [comment]
Any update on this one? Still have the same issues as other users after uninstall.

**Comment by sterno900** [comment]
so many junks

**Comment by speedfan-3000rpm** [comment]
2025 and still not fixed. We recently updated from and now we have 2 entries for file association. One works one doesn't. 

Also as an aside, choosing to associate imageglass with all file types on the GUI doesn't work. It just adds it to the choose and app menu.
