### ISSUE TITLE
Transparent UI and background.

### ISSUE THREAD

**Issue by 0450** [d2phap/ImageGlass#548]
I would like to see an option to make the UI transparent or that translucent frosted glass-like look like the option for windows taskbar and settings pages.

**Comment by SDPMrem71** [comment]
👍

**Comment by d2phap** [comment]
[ImageGlass Moon 9.0 beta 3](https://github.com/d2phap/ImageGlass/releases/tag/9.0.3.1225) supports transparency by the setting `BackdropStyle`. You can set it to one of these options:
- `None`: no transparency
- `Mica`: Mica effect
- `MicaAlt`: MicaAlt effect
- `Acrylic`: Acrylic effect

Only works with Windows 11 22H2.
