### ISSUE TITLE
extensions is not working

### ISSUE THREAD

**Issue by drv42** [d2phap/ImageGlass#55]
Extensions is not working

Log:
![default](https://cloud.githubusercontent.com/assets/7890964/11170445/f9a2220e-8bed-11e5-8ba9-94fa4f95241f.PNG)

Подробная информация об использовании оперативной 
(JIT) отладки вместо данного диалогового 
окна содержится в конце этого сообщения.

************** Текст исключения **************
System.NotSupportedException: Предпринята попытка загрузить сборку из сетевого ресурса, что в предыдущих версиях .NET Framework могло привести к помещению сборки в "песочницу". Этот выпуск .NET Framework не включает политику CAS по умолчанию, поэтому данная загрузка может быть опасной. Если эта нагрузка не предназначена для изоляции сборки, включите переключатель loadFromRemoteSources. Дополнительные сведения см. на странице http://go.microsoft.com/fwlink/?LinkId=155569.
   в System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   в System.Reflection.Assembly.LoadFile(String path)
   в ImageGlass.Plugins.PluginServices.AddPlugin(String FileName)
   в ImageGlass.Plugins.PluginServices.FindPlugins(String Path)
   в ImageGlass.frmExtension.LoadExtensions()
   в ImageGlass.frmExtension.frmExtension_Load(Object sender, EventArgs e)
   в System.Windows.Forms.Form.OnLoad(EventArgs e)
   в System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   в System.Windows.Forms.Control.CreateControl()
   в System.Windows.Forms.Control.WmShowWindow(Message& m)
   в System.Windows.Forms.Control.WndProc(Message& m)
   в System.Windows.Forms.Form.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Загруженные сборки **************
mscorlib
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.34003 built by: FX45W81RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ImageGlass
    Версия сборки: 3.0.9.19
    Версия Win32: 3.0.9.19
    CodeBase: file:///F:/soft/ImageGlass/ImageGlass.exe
----------------------------------------
ImageGlass.Services
    Версия сборки: 3.0.0.0
    Версия Win32: 3.0.0.0
    CodeBase: file:///F:/soft/ImageGlass/ImageGlass.Services.DLL
----------------------------------------
System.Windows.Forms
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.34003 built by: FX45W81RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
ImageGlass.Core
    Версия сборки: 1.9.5738.42613
    Версия Win32: 1.9.5738.42613
    CodeBase: file:///F:/soft/ImageGlass/ImageGlass.Core.DLL
----------------------------------------
ImageGlass.Library
    Версия сборки: 3.0.0.0
    Версия Win32: 3.0.0.0
    CodeBase: file:///F:/soft/ImageGlass/ImageGlass.Library.DLL
----------------------------------------
ImageGlass.Theme
    Версия сборки: 1.5.5738.42614
    Версия Win32: 1.5.5738.42614
    CodeBase: file:///F:/soft/ImageGlass/ImageGlass.Theme.DLL
----------------------------------------
System.Windows.Forms.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
ImageGlass.ImageBox
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.0.0
    CodeBase: file:///F:/soft/ImageGlass/ImageGlass.ImageBox.DLL
----------------------------------------
ImageGlass.ImageListView
    Версия сборки: 11.0.0.0
    Версия Win32: 11.0.0.0
    CodeBase: file:///F:/soft/ImageGlass/ImageGlass.ImageListView.DLL
----------------------------------------
Accessibility
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Core
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
PresentationCore
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.34004 built by: FX45W81RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
WindowsBase
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.34004 built by: FX45W81RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Xaml
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
TargaImage
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///F:/soft/ImageGlass/TargaImage.DLL
----------------------------------------
FreeImageNET
    Версия сборки: 3.15.1.0
    Версия Win32: 3.15.1.0
    CodeBase: file:///F:/soft/ImageGlass/FreeImageNET.DLL
----------------------------------------
Svg
    Версия сборки: 2.0.0.42482
    Версия Win32: 2.0.0.42482
    CodeBase: file:///F:/soft/ImageGlass/Svg.DLL
----------------------------------------
System.Drawing.PSD
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///F:/soft/ImageGlass/System.Drawing.PSD.DLL
----------------------------------------
IconLib
    Версия сборки: 0.73.0.0
    Версия Win32: 0.73.0.0
    CodeBase: file:///F:/soft/ImageGlass/IconLib.DLL
----------------------------------------
ImageGlass.Plugins
    Версия сборки: 1.1.5738.42613
    Версия Win32: 1.1.5738.42613
    CodeBase: file:///F:/soft/ImageGlass/ImageGlass.Plugins.DLL
----------------------------------------
mscorlib.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------

************** Оперативная отладка (JIT) **************
Для подключения оперативной (JIT) отладки файл .config данного
приложения или компьютера (machine.config) должен иметь
значение jitDebugging, установленное в секции system.windows.forms.
Приложение также должно быть скомпилировано с включенной
отладкой.

Например:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

При включенной отладке JIT любое необрабатываемое исключение
пересылается отладчику JIT, зарегистрированному на данном компьютере,
вместо того чтобы обрабатываться данным диалоговым окном.

**Comment by d2phap** [comment]
@drv42 

Whenever downloading a *.dll from the internet, Windows automatically block it for security. To temporarily fix this issue, you can open Properties, check Unblock option.

The next version of ImageGlass will fix this also.

![unblockdll](https://cloud.githubusercontent.com/assets/3154213/12073485/6cb734b0-b15e-11e5-857c-0338768a5235.png)
