### ISSUE TITLE
Remove Windows Sound option

### ISSUE THREAD

**Issue by 0450** [d2phap/ImageGlass#550]
### Is your feature request related to a problem? Please describe.

I dislike the windows sound. I get it when i try to exit full-screen with Alt+Enter and it's annoying.
### Describe the solution you'd like

Option in Settings to remove all sounds from the program.

**Comment by fire-eggs** [comment]
ImageGlass plays no sounds. If you are getting sounds, it's due to your Windows theme configuration.
