### ISSUE TITLE
Full-screen Optimization

### ISSUE THREAD

**Issue by 0450** [d2phap/ImageGlass#551]
### Is your feature request related to a problem? Please describe.

Improvements to full-screen mode i'll like to see. 
### Describe the solution you'd like

Change the full-screen hotkey to the universal F11 or add the option to. 

Make Esc in full-screen to exit fullscreen rather than close the program. 

Auto-Hide toolbar in full-screen. Or option to in settings.

**Comment by fire-eggs** [comment]
>Change the full-screen hotkey to the universal F11 or add the option to.
Alt+Enter is "more universal" than F11. E.g. F11 doesn't work in Microsoft Photos. But an option is always a good idea!

>Make Esc in full-screen to exit fullscreen rather than close the program.
This is why I turn off the setting "Allow to press ESC to quit application".

**Comment by 0450** [comment]
What i meant was Esc can still be used to close application in windowed mode but be set to close full-screen in full-screen mode. So if im in Full-screen, first Esc would close full-screen and second Esc would close the application.

**Comment by d2phap** [comment]
Shortcuts changed in upcoming release:
  + Full screen from <kbd>Alt+Enter</kbd> to <kbd>F11</kbd>.
  + Slideshow from <kbd>F11</kbd> to <kbd>F12</kbd>.

**Comment by d2phap** [comment]
You can find the options in Settings > Image > Full screen in the latest build of IG Moon now: https://imageglass.org/moon

![image](https://user-images.githubusercontent.com/3154213/140269074-80e708ee-9ddf-42cd-95c5-e48a58dac0bd.png)
