### ISSUE TITLE
Change size of navigation arrows.

### ISSUE THREAD

**Issue by 0450** [d2phap/ImageGlass#552]
### Is your feature request related to a problem? Please describe.

I like using the navigation arrows to go through pictures but it looks unnecessarily big and is distracting.  
### Describe the solution you'd like

Option to change size of navigation arrows.

Also there is a small weird flicker on the arrows when the normal arrows transitions into the navigation arrows.

**Comment by fire-eggs** [comment]
Personal note: the size may be effected by Windows Display "Scale and layout" setting? E.g. on one system where text is at 100%, the arrows are small. On another system where text is 150%, the arrows are big.

**Comment by d2phap** [comment]
Hi @0450 
You may want to try the new navigation arrow buttons in the latest build of ImageGlass Moon:
https://imageglass.org/moon

Changing the size of arrows, as Kevin said, it only supports in theme config file.

![image](https://user-images.githubusercontent.com/3154213/78454971-3bfd0680-76ce-11ea-8c2a-30d89ea58f75.png)
