### ISSUE TITLE
Organization of toolbar

### ISSUE THREAD

**Issue by 0450** [d2phap/ImageGlass#553]
### Is your feature request related to a problem? Please describe.

I am looking for a photo viewer program to switch to from the default windows 10 photos. I just started using ImageGlass and while i think that it has some cool features that i like, there are many things that could be improved on before i would use as my default photo viewer. I can see that the newer version's toolbar had some better organization that the previous, but it still feels very cluttered with icons that don't tell u what's what. Took me awhile to click on each icon to find the thing i wanted to do instead of icon telling me what it does.

### Describe the solution you'd like

Improved icons.
Improved groupings and placing of icons.
"Adjust windows to actual image dimensions" changes to "Restore windows" after clicking it.

### Describe alternatives you've considered

Allow customization of toolbar.

**Comment by fire-eggs** [comment]
Did you try customizing the toolbar via Settings?  You can arrange the buttons / groupings however you'd like.

![image](https://user-images.githubusercontent.com/9809727/60607467-4f6bf180-9d8b-11e9-820b-3e093cb15088.png)

**Comment by 0450** [comment]
Wow i didn't know that. I just downloaded the application in 5 minutes and couldn't find a way when i searched. Another thing, make a tour so we know where's where.
