### ISSUE TITLE
Remove playing windows notification sound when exit full-screen with Alt+Enter

### ISSUE THREAD

**Issue by 0450** [d2phap/ImageGlass#555]
### Is your feature request related to a problem? Please describe.

I dislike the windows sound. I get it when i try to exit full-screen with Alt+Enter and it's annoying.
### Describe the solution you'd like

Option in Settings to not play windows sound when exit full-screen with Alt+Enter.

**Comment by 0450** [comment]
@fire-eggs even if ImageGlass plays no sound, it gets windows to play it and no its not my config fault, it only happens in ImageGlass. test it out before closing and commenting.

**Comment by fire-eggs** [comment]
Fair enough. As one of the developers on ImageGlass, I could tell you that IG does not _deliberately_ play any sounds.  But as it does play, it is worth another look.

**Comment by fire-eggs** [comment]
Shipped in V7.0
