### ISSUE TITLE
Support opening image from URI Scheme (Web-to-App linking)

### ISSUE THREAD

**Issue by d2phap** [d2phap/ImageGlass#557]
From https://groups.google.com/forum/#!msg/imageglass/l6VPedgl0YE/nJilwYRMDQAJ

I am working on a web based document scanning application now i am trying to add a power full image viewer like Image Glass.

My question is how can i integrate ImageGlass in my Web page that can work on modern browsers like edge,chrome and Firefox without add on or applet or even ActiveX control.

Regards,
Kamran

**Comment by fire-eggs** [comment]
And my answer in google groups:

Pretty sure the answer is "you can't". You are limited to the image formats which are supported natively in the browser.
For example, see https://stackoverflow.com/questions/2176991/display-tiff-image-in-all-web-browser

If you want a pure-web solution (i.e no conversion by the user on the client side) the only possible solution is:
1. User uploads their image to your server
2. Your server converts it to a browser supported format. You'd use something like ImageMagick for that.
3. The client browser refreshes, loading the converted image from your server

When you are dealing with an image format with capabilities outside the native browser format, you need to inform the user the image they see at step 3 is merely an approximation.

It'd be educational if someone could tell me different ...
Kevin

**Comment by d2phap** [comment]
@fire-eggs I found a solution actually 😀

This issue makes me remember to `mailto:<email>`.
We can register a custom protocol `imageglass:<path>` so that when user clicks on the link, ImageGlass will launch with `<path>` as argument.

A nice article I found: https://www.meziantou.net/registering-an-application-to-a-uri-scheme-using-net.htm

**Comment by d2phap** [comment]
Ready for testing https://imageglass.org/moon

**Comment by fire-eggs** [comment]
Great. And how does that work on Mac, Linux, Mobile phone and other browsers?

**Comment by d2phap** [comment]
I guess this is just internal web app, and ImageGlass only runs on Windows OS, so I think we don't need to worry about other OS 😁

**Comment by fire-eggs** [comment]
Works for me!  :-)
