### ISSUE TITLE
Wrong orientation for HEIC image

### ISSUE THREAD

**Issue by skmskmskmskm** [d2phap/ImageGlass#559]
### System info:
- ImageGlass version: 6.0.12.29
- OS version: Windows 10 18362.239

### Expected behavior:
When opening a HEIC file with the "Orientation" metadata field set to "Rotate 90 CW", the image should show up in oriented to portrait orientation. 

### Actual behavior:
It displays in landscape orientation, i.e. not correctly oriented.

### Steps to reproduce:
1. Open a HEIC file that has the Orientation metadata field set to "Rotate 90 CW" in imageglass

Example photo:

[IMG_5878.zip](https://github.com/d2phap/ImageGlass/files/3383916/IMG_5878.zip)

**Comment by d2phap** [comment]
I just debugged ImageGlass using your sample file.

- The initial image size is `3024 x 4032`
  ![image](https://user-images.githubusercontent.com/3154213/61180206-b6b85a00-a645-11e9-956a-aa4c703442c1.png)

- And there is orientation tag in Exif profile, which is `Rotate 90 CW`
  ![image](https://user-images.githubusercontent.com/3154213/61180213-ca63c080-a645-11e9-9a53-4e37ff101c9c.png)

- And ImageGlass processes rotating the image, the size now is `4032 x 3024`
  ![image](https://user-images.githubusercontent.com/3154213/61180207-c20b8580-a645-11e9-9dee-fb057d987f34.png)

### The illustration shows it is correct rotation
![image](https://user-images.githubusercontent.com/3154213/61180255-8b823a80-a646-11e9-9ac6-ab1f41c304b8.png)

Do you have other sample HEIC files?

**Comment by skmskmskmskm** [comment]
Is portrait the right starting orientation before applying the rotation? I have attached new sample file shot from the latest iPhone in HEIC format. It should be displayed in portrait format, and does in other viewers, see screenshots below.

Image in GIMP
<img width="613" alt="GIMP" src="https://user-images.githubusercontent.com/52801888/61181670-64654200-a621-11e9-9585-946aa710d1b9.png">

Image in Imageglass
<img width="692" alt="imageglass" src="https://user-images.githubusercontent.com/52801888/61181678-6b8c5000-a621-11e9-85fd-8b35505fe119.png">

New example file:
[IMG_8214.zip](https://github.com/d2phap/ImageGlass/files/3389669/IMG_8214.zip)

**Comment by fire-eggs** [comment]
I used the ImageMagick `convert` tool with your images. With the `-auto-orient` option, they came out rotated, the same as ImageGlass  (and as expected from the rotation metadata).  Without that option, they came out in "portrait" mode.

I've tried other Windows image viewers which supposedly handle HEIC, and they bail on your images. One that works, [CopyTransHEICforWindowsv1.005](https://www.copytrans.net/download/), shows your images in portrait mode, but without color. [Unlike ImageMagick, which kept the color.]

I can only assume that you have configured GIMP to not auto-rotate, as mentioned in [this](https://photography-on-the.net/forum/showthread.php?t=1429366).

ImageGlass always rotates images as per the metadata. We don't currently have a setting to control that. 

We can change this issue to "Add option to turn off Auto Rotation" if you'd like.

**Comment by skmskmskmskm** [comment]
I have tested this in XNView (with HEIC plugin), Windows Photos (with HEIC support added through the Windows app store) and Quicklook. Also tested how these two images are displayed on iPhone as well as Android. All of the above display these two images in portrait orientation, while Imageglass will display in Landscape per my screenshot.

I don't know what's going on behind the scenes, but the end result is different from every other app with HEIC support I've found. I did go through the EXIF using Exiftool once more to see if I could spot something. Perhaps the following lines could be useful:

Orientation                     : Rotate 90 CW
Exif Image Width                : 4032
Exif Image Height               : 3024
Image Width                     : 4032
Image Height                    : 3024
Image Spatial Extent            : 4032x3024
Rotation                        : 270
Image Size                      : 4032x3024

Which suggest the initial image in landscape, rotated once to end up in portrait. While from the comment above I can see that ImageMagick (?) interprets the initial image as 3024 x 4032, i.e. portrait to begin with?

**Comment by fire-eggs** [comment]
Ow. My head is starting to hurt ...

I see from your Exif output that it is wider than high, i.e. in landscape orientation. Then there is a 270 degree rotation, which presumably turns it into the "portrait" form (3024Wx4032H). A little mystifying as to why those convolutions would be required ...

So I have to agree with you, the image's "actual" state is "portrait", ie, a 3024Wx4032H image. Which explains both ImageMagick and CopyTransHeic behavior. 

Then IG sees the Rotate 90 Clockwise orientation, and thus the "landscape" form as shown by IG. Also collaborated by ImageMagick and "-auto-orient".

Since you have ExifTool, you could experiment with `exiftool -Orientation= <image>` to delete the Orientation tag (or `exiftool -Orientation=1 <image>` to set no change). [I think those would be the options, pardon me if I'm preaching to the choir ...]  Which is a pain, I know.

What it comes down to at this point is IG is fixed in "auto orient" mode. A setting would need to be added to IG to change that behavior.

**Comment by skmskmskmskm** [comment]
[This issue](https://github.com/ImageMagick/ImageMagick/pull/1233) (now fixed it seems) in ImageMagick isn't related by any chance?

**Comment by fire-eggs** [comment]
Ah! Interesting. My copy of ImageMagick predates that change. Let me update and try `convert` again.

IG is using the latest Magick.NET, which is using a copy of ImageMagick which post-dates that change. 

We might have to take this up with the Magick.NET guy ...

**Comment by d2phap** [comment]
Fixed this bug by disabling rotation correction for `HEIC` format.
It's ready in IG Moon: https://imageglass.org/moon
