### ISSUE TITLE
Picture to fit to window frame

### ISSUE THREAD

**Issue by mymain69** [d2phap/ImageGlass#56]
Hi,

Thanks for the update fixing all the bugs and glitches! Can you make the picture always fit to the window frame when in window mode or in fullscreen in the next update please

thanks!

**Comment by Atulin** [comment]
I second it. It's a default feature of Windows default image viewer, and I miss it in ImageGlass.

**Comment by d2phap** [comment]
Hi @mymain69 

It's already there! As @Atulin said, it's default feature of ImageGlass. Besides that, ImageGlass also supports zooming, scaling functionalities.
