### ISSUE TITLE
"Delete image permanently" displays confirm dialog even when setting is OFF

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#562]
### System information:
 - Windows OS version: Windows 7
 - ImageGlass version: 6.1.7.10 Moon Portable

### To Reproduce
1. Open a folder containing images. Move to an image to be deleted
2. Delete the image permanently (via menu or keyboard)

### Actual behavior:
The "are you sure?" confirmation dialog appears, even if the setting to show it is OFF.

### Expected behavior:
If the setting is OFF, the confirmation dialog should never appear.

**Comment by d2phap** [comment]
Fixed!
