### ISSUE TITLE
Nice-to-have: Gif frame naming contains leading zeros

### ISSUE THREAD

**Issue by Davexx** [d2phap/ImageGlass#563]
### Is your feature request related to a problem? Please describe.

I love that your viewer can play GIFs, odd that more players can't do this...  :-(

I tried the"Extract Image Frames" feature (Ctrl+R) and I noticed it named the files with the original filename + a frame number, but the number had no leading zeros for frames 1-9, so the resulting output frame files were not in order, e.g.: image-1.png, image-10.png, image-2.png, image-3.png, etc...

### Describe the solution you'd like

I would love it if ImageGlass would add at least one leading zero to the one-digit numbers, I don't think many gifs go beyond 99 frames.  To be safe you could add two leading zeros, but one would cover the majority of situations and keep the names tidy.

### Describe alternatives you've considered

I would see this as a feature without any settable options, but you could add the ability to choose a destination name and number of digits.  
As a work around, I used other software: the robust file re-namer feature in Total Commander.

### Additional context

I hope this idea helps make that feature more convenient and saves the user some time.
Thanks for listening.

**Comment by fire-eggs** [comment]
Done. Two leading zeros. Thanks!

**Comment by Davexx** [comment]
Wow, thanks!!! That's gotta be the fastest implementation of a user feature request I have ever been a part of.  I eagerly await the next scheduled update.

**Comment by d2phap** [comment]
JFYI, the new version will be released in couple of weeks with many new features and improvements

**Comment by Davexx** [comment]
Looking forward to it!  I am most grateful for your hard work and energy.

**Comment by fire-eggs** [comment]
Shipped in V7.0

**Comment by Davexx** [comment]
Much appreciated!  Thank  you!
