### ISSUE TITLE
Not sure that "View Channels" menu state should persist

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#564]
1. Running IG, viewing images.
2. Changed view channels menu to red.
3. Restarted IG.
4. Confused because my images appeared as greyscale.

I think it is easy to inadvertently leave view channels to something besides 'All'. Especially as there is no obvious visual indicator (like the toolbar, or in Settings) to see it.

I suggest that `ColorChannels` should be a `LocalSetting`, not a `GlobalSetting`.

**Comment by d2phap** [comment]
OK!
