### ISSUE TITLE
Useful to initialize the color picker dialog when changing background color

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#569]
When changing IG's background color, it would be useful if the Windows Color dialog was initialized to the current color value.

E.g. I've changed the background color via settings, and closed out. I don't quite like the look, invoke settings again, then click to change the background color.

The color dialog is not set to the current color, so I have to fiddle to recreate my color and/or tweak it.

**Comment by d2phap** [comment]
Shipped to IG Moon https://imageglass.org/moon
