### ISSUE TITLE
WebM file type support

### ISSUE THREAD

**Issue by ClayF** [d2phap/ImageGlass#57]
Requesting WebM support.

I'm trying to make the switch over from Irfanview but sadly ImageGlass doesn't support the same variety of formats that Irfanview does.

**Comment by d2phap** [comment]
Hi @ClayF 

WebM is a video file format, so I cannot put it into a image viewer.
The new commit is just supported non-animated WebP format

**Comment by canerozdemircgi** [comment]
IrfanView and XnView MP supports this. 
Web is evolving from GIF images to WebM.

**Comment by JosefFStraka** [comment]
Looks like ImageGlass is only for images, kinda sad, I love its interface and ease of use. Sadly no video. Switching to IrfanView rn...
