### ISSUE TITLE
"View channels" very slow with large transparent PNG

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#572]
Switching between image channels for a large PNG is pretty slow. I know this is a Magick.NET / ImageMagick issue, wondering if we should bring it up.

I.e. each channel switch for the attached (8000x5177, 6.43M) PNG takes 6 seconds on my system.

[5a1cea7d3ec593.3966458915118444772571.zip](https://github.com/d2phap/ImageGlass/files/3398694/5a1cea7d3ec593.3966458915118444772571.zip)

**Comment by d2phap** [comment]
The "View channels" is accelerated by GPU in ImageGlass v9.1
