### ISSUE TITLE
File Association Editing dialog cannot be closed with 'X' button

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#573]
Run IG.
Goto settings, Edit panel.
Select any extension, click 'Edit' button.

The editing dialog cannot be closed via the 'X' button in the upper right corner. This is due to the fact that `_isAllowFormClosed` is false. However, the 'X' button should be equivalent to clicking the 'Cancel' button.

`_isAllowFormClosed` appears to not serve any useful purpose. It would make sense if it was set false if there was a validation error, but validation does not make use of it.

However, if it is intentional that the dialog cannot be closed via 'X', then I suggest removing the 'X' by switching the form property `ControlBox` to false.

**Comment by fire-eggs** [comment]
Ditto for 'Add New Format' dialog, via Settings, File Associations.

**Comment by d2phap** [comment]
Should not be an issue with v9.0
