### ISSUE TITLE
Drag & drop of file is behaving different than double-click of file

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#574]
1. Run IG. Settings are "include children".
2. Drag a folder (containing sub-folders) into IG.  E.g. C:\pix\z, where Z has subfolders A,B,C and each of those has multiple images: drag C:\pix\z into IG.
3. In explorer, navigate down to contents of a sub-folder, e.g. C:\Pix\z\B. Drag an image
from there into IG

Note at this point that the position in the image list has changed to show the dragged image, but the image list itself has not been updated.

4. Now double-click on the same image in step 3. [Where IG is the default photo editor].

At this point, the image list changes to show only those images in "C:\Pix\z\B".

I find this confusing: drag-and-drop of an image is, in my mind, the same as double-click. Am I missing some benefit from treating them differently?

**Comment by d2phap** [comment]
- When user drag and drop an image from the folder that is already loaded, ImageGlass does not reload the entire folder, it just finds the index of that image and open.
- Double-clicking an image from Explorer always does a full reload.
