### ISSUE TITLE
Ctrl + Z to undo latest action

### ISSUE THREAD

**Issue by jantheodor** [d2phap/ImageGlass#575]
### Is your feature request related to a problem? Please describe.
Browsing your library and deleting images can become quite quick. And sometimes I end up delting the wrong images because of it. And since you can undo most actions in most programs by pressing CTRL + Z

### Describe the solution you'd like
Enable CTRL + Z to undo latest actions (especially when it comes to deleting images)

### Describe alternatives you've considered
No idea.

### Additional context
Thanks for all the effort you've been putting into this project!

**Comment by d2phap** [comment]
I will not implement this feature, to undo the deletion, you can open that folder in File Explorer, and press Ctrl+Z. ImageGlass does not manage the file actions
