### ISSUE TITLE
Safe rotation on the fly into the file (like Windows Imageviewer or Photos does)

### ISSUE THREAD

**Issue by jantheodor** [d2phap/ImageGlass#576]
### Is your feature request related to a problem? Please describe.
Rotating images is quite handy, but not so much, if it doesn't automatically save the position.

### Describe the solution you'd like
Automatically rewrite image whenever the rotation changes.

### Describe alternatives you've considered
Using alternative programs. Using Windows Explorer context menu. Pressing CRTL + S to save the image (takes too long)

### Additional context
As always. THANK YOU!

**Comment by fire-eggs** [comment]
If you select this option (see Settings, Edit tab):
![image](https://user-images.githubusercontent.com/9809727/61558134-307c8900-aa34-11e9-9820-47e64afec00d.png)

All rotate/flip changes will be saved when you move to the next image.

**Comment by jantheodor** [comment]
Oh. I See. Thank you! Just wondering, why did you decide to make it not a default? Thanks for the answer : )

**Comment by fire-eggs** [comment]
I wasn't working on it when ImageGlass first appeared, back in 2013, two years before Windows Photos. My understanding though is that ImageGlass is primarily an image viewer, not an editor. Back at the beginning, I can only assume that saving _any_ changes was contrary to the intent of the program.  Obviously, some editing-like features have crept in, and there must have been some pressure to make saving those changes possible.

I happen to agree with how ImageGlass does it (i.e. I want to be able to switch perspectives on an image without _having_ to write it to disk - especially when using a lossy file format such as JPG where quality might suffer.

Which is one reason why I use (and help maintain!) ImageGlass.
