### ISSUE TITLE
Dialog boxes should obey theme

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#580]
Minor dialog boxes in IG do not follow the theme.

- rename
- about
- settings
- check for update
- error messages

**Comment by d2phap** [comment]
It will be complicated in theme config to define all of the color for dialog (dark / light text, background, link, ...)

To reduce the effort of theme maintenance, only simple dialogs opened directly from the main form will be applied theme color:
- Rename dialog
- Go to dialog

The other forms will be tweaked to grey color scheme:
- Settings
- About
- Add new extension
- Add new editing app
![image](https://user-images.githubusercontent.com/3154213/79066545-5137ed80-7ceb-11ea-86a6-80b559047352.png)

Out of scope, use default system dialog for:
- Error / Warning / Info message box

**Comment by d2phap** [comment]
Shipped in ImageGlass Moon https://imageglass.org/moon
