### ISSUE TITLE
"Copy" is backwards

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#582]
"Copy" function is "Copy file". 
"Copy Image Data" function is "Copy image to clipboard".

Every image viewer program that I'm aware of implements "Copy" as "Copy image to clipboard".

**Comment by d2phap** [comment]
We have `Cut - ctrl+x` function for `cut file`, the `Copy - ctrl+c` function should be for `copy file` (consistency).
Because ImageGlass is not photo editor, `Copy` function is for `copy file` is fine.

**Comment by MasterGroosha** [comment]
@d2phap Since Ctrl+C copies file and Ctrl+Shift+C copies image, could you please add an option to swap these shortcuts? I use ImageGlass to browse images and then upload somewhere using copy/paste and Ctrl+Shift+C seems counter-intuitive for me (and probably for other people too)
