### ISSUE TITLE
Open Image from Clipboard doesn't auto-zoom

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#583]
- run IG, view images
- use "copy image data" to put image in clipboard
- move to another image (ideally one where zoom factor is different)
- right click and "open image from clipboard"

Image displayed is not zoomed as per current settings. Tweaking or minimizing/restoring the window causes the zoom to take effect.

**Comment by d2phap** [comment]
Fixed in the latest build of IG Moon: https://imageglass.org/moon
