### ISSUE TITLE
Need help understanding "Open Image from Clipboard"

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#584]
- Run IG. Open some images, ideally more than a few
- Show thumbnails
- Get an image into the clipboard (via paint, IG, photos, whatever)
- In IG, while viewing an image, right-click and "open image from clipboard"

Confusions:
- Title bar reads "image data". This image doesn't appear to be in the "image list".
- Note that the last image viewed is still highlighted in the thumbs
- Has the clipboard image "superseded" the currently selected image in the image list?
- Save, delete, etc operate on the "selected" image, not the visible image. This seems risky.

**Comment by d2phap** [comment]
Some changes made in [v9.0 beta 2](https://github.com/d2phap/ImageGlass/releases/tag/9.0.2.904) to help to clarify this:
- `Image data` is changed to `Clipboard image`
- When being in the `Clipboard image` mode, all functions will work with the clipboard image, such as:
  + Refresh / changing Zoom modes
  + Save
  + Print
  + Flip / Rotate
  + Set as desktop background
  + Set as lock screen
  + Copy
  + Share
  + Open with
- To exit the Clipboard image mode, navigate to other image, or use Reload image.
- When deleting, the confirmation dialog will appear with a thumbnail and other details:
  ![image](https://user-images.githubusercontent.com/3154213/188649098-069a1db8-10cd-4c5a-b334-90b0842fb34f.png)
