### ISSUE TITLE
Open image viewer always in full-screen mode

### ISSUE THREAD

**Issue by amirrammari** [d2phap/ImageGlass#586]
Hello, Please add below feature:
Open image viewer always in full-screen mode.

**Comment by d2phap** [comment]
ImageGlass 6.0 already supports full-screen mode.
You can enable it but the Full screen button on toolbar, or Main menu > Full screen mode

![image](https://user-images.githubusercontent.com/3154213/61572872-1a73d480-aad7-11e9-81d9-c928ee68d96f.png)

**Comment by amirrammari** [comment]
I know it.
I would like to **always** open ImageGlass in full-screen mode.
(no need to press the full-screen button)

**Comment by d2phap** [comment]
If you don't exit full screen mode, ImageGlass will remain opening image in full screen mode when u restart.

**Comment by amirrammari** [comment]
> 
> 
> If you don't exit full screen mode, ImageGlass will remain opening image in full screen mode when u restart.

Ok, Thanks. 😘
