### ISSUE TITLE
Imageglass looses its zoom and navigation placement that it was in before the save

### ISSUE THREAD

**Issue by d2phap** [d2phap/ImageGlass#59]
From Rowan Griffiths:

Every time I save using 3DS Max, via hotkey and while saving using the on screen ui, Imageglass refreshes its image. Imageglass shows the text "loading" briefly before showing the image again. The annoying thing is that Imageglass looses its zoom and navigation placement that it was in before the save. Just thought I'd let you know.

**Comment by HanatakeYurii** [comment]
Hi,

I also get this kind of behavior when any program updates files. It loose zoom level (but don't change the selected picture), even it's at default level (image disappears then show again).

Tested with 3.2.0.16

**Comment by d2phap** [comment]
this bug was fixed

**Comment by HanatakeYurii** [comment]
Thanks :+1:
