### ISSUE TITLE
Crash. ImageGlass immediately closes when trying to generate HEIF/HEIC thumbnails.

### ISSUE THREAD

**Issue by MartBlur** [d2phap/ImageGlass#590]
_For the sake of this report any mention of .HEIF also implies .HEIC files. The issue affects both._

### System information:
 - Windows OS version: Windows 10 LTSC x64, build 1809
 - ImageGlass version: 7.0.7.26 (.msi x64)

### To Reproduce
1. Open an image (of any format) with ImageGlass from a folder that contains at least one .heif file.
2. Enable the thumbnail bar, if not already enabled.
3. If no .heif images are visible in the thumbnail bar, scroll it until some should load.

### Actual behavior:
ImageGlass will immediately crash, unexpectedly, with no message of any kind, when it tries to generate thumbnails from .heif files.
The program displays the heif images themselves with no issues: It will NOT crash until it actually needs to display a thumbnail for them.

### Expected behavior:
Load .heif thumbnails, and without crashing.

### Additional context:
Different issue but possibly related: Associations and thumbnails for explorer load normally for HEIC, but not HEIF files. HEIF is not listed in "File Associations" either, it must be manually added and configured. Simply renaming .heif to .heic appears to fully bypass the issue, and because of this I don't consider it important by itself. Should I open another issue?

**Comment by d2phap** [comment]
Hi @MartBlur 
Can you send me the HEIC/HEIF files that crashed the app?
Thank you

**Comment by MartBlur** [comment]
Sure. Had to compress, it doesn't let me upload directly.
[compressiontest.zip](https://github.com/d2phap/ImageGlass/files/3442937/compressiontest.zip)

So far the program was a good experience otherwise.

**Comment by fire-eggs** [comment]
> Should I open another issue?
Yes, that would be a separate issue. Thanks!

**Comment by MartBlur** [comment]
Just tested on ImageGlass moon 7.0.8.5 and the issue appears to be solved. Thank you.
