### ISSUE TITLE
Transparency Feature

### ISSUE THREAD

**Issue by xmha97** [d2phap/ImageGlass#591]
Please add transparency feature (like notepad++ find window)

This feature includes two modes:
1. Transparency window on losing focus
2. Transparency window, always.

![Notepad++ find window](https://user-images.githubusercontent.com/23485114/62072205-694a0880-b253-11e9-80f6-29c1c37aa653.png)

Thanks for developing. <3

**Comment by amirrammari** [comment]
![Untitled-1](https://user-images.githubusercontent.com/23485114/62073617-5258e580-b256-11e9-9c33-92e4cdefdc31.png)

**Comment by d2phap** [comment]
Any ideas why you need this?

**Comment by amirrammari** [comment]
You can see Google Picasa is transparent and I think the transparent feature is nice.
![Google Picasa on Windows 10](https://i.stack.imgur.com/jAq8Z.jpg)

**Comment by SDPMrem71** [comment]
+1, i'd like to see transparent background too. 👍

**Comment by fshafique** [comment]
+1, I just installed ImageGlass after hearing that it could be a decent replacement for Picasa Viewer. I was disappointed that it was similar to the Photo app in Win 10, which I was trying to replace. Please do add the transparency to the background. Thanks.

**Comment by d2phap** [comment]
This feature will be supported in ImageGlass Preview (UWP app)
https://github.com/d2phap/ImageGlass-Preview

**Comment by xmha97** [comment]
> This feature will be supported in ImageGlass Preview (UWP app)
> https://github.com/d2phap/ImageGlass-Preview

Please publish the beta package file (.appx)
I want to test ImageGlass UWP without recompiling.

**Comment by d2phap** [comment]
[ImageGlass Moon 9.0 beta 3](https://github.com/d2phap/ImageGlass/releases/tag/9.0.3.1225) supports transparency by the setting `BackdropStyle`. You can set it to one of these options:
- `None`: no transparency
- `Mica`: Mica effect
- `MicaAlt`: MicaAlt effect
- `Acrylic`: Acrylic effect

Only works with Windows 11 22H2.
