### ISSUE TITLE
Thumbnail for large SVG file is gibberish

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#596]
### System information:
 - Windows OS version: Any
 - ImageGlass version: 7.0

### Actual behavior:
The thumbnail for the attached (zipped) SVG file is complete gibberish.

### Expected behavior:
A reasonable thumbnail, at all thumbnail sizes.

### Screenshots:

![image](https://user-images.githubusercontent.com/9809727/62426189-b55fd780-b6af-11e9-8a38-54ad859d5beb.png)

### Additional context:
Thumbnail size of 256 appears acceptable; anything smaller is garbage.

[gramps.uml.API.zip](https://github.com/d2phap/ImageGlass/files/3465066/gramps.uml.API.zip)

**Comment by d2phap** [comment]
It's probably Magick.NET function, so I just close this bcuz support for SVG is very limited
