### ISSUE TITLE
Keeps reverting to defaults

### ISSUE THREAD

**Issue by BreadBreadington** [d2phap/ImageGlass#600]
### System information:
 - Windows OS version: Windows 10 Pro x64 v1903 Build 18362.239
 - ImageGlass version: 7.0.7.26

### Behavior:
After a seemingly random period of time (Seems to be a day or two, sometimes less) ImageGlass will revert to default settings
When opening an image for the first time in a while, ImageGlass will ask for the initial setup again and recreate igconfig.xml with default settings

### Additional context:
Uninstalled completely using Revo Uninstaller (Gets rid of lingering registry keys/folders) and reinstalled with the most recent version from the website, problem persists

**Comment by fire-eggs** [comment]
If IG has any sort of issue with the igconfig.xml file in the exe folder, then it will look elsewhere for the config file. It is difficult to guess off-hand why there might be a problem for you, I need to dig further to identify possible causes.

The alternative location that IG uses is in AppData.  The path to look for is going to be something like: `C:\users\<username>\AppData\Roaming\ImageGlass`. E.g. if your username is Bread, the path will be `C:\users\Bread\AppData\Roaming\ImageGlass`. [AppData is a hidden folder, if you have "show hidden items" off in explorer you won't see it].

So once you have IG configured the way you like it, I suggest copying igconfig.xml from the IG folder into that folder.

My apologies for the inconvenience. We need to get better control over the config file.

**Comment by BreadBreadington** [comment]
That's strange because igconfig.xml wasn't in my exe folder, only in appdata. I've copied it to the exe folder and will see how it goes.

**Comment by fire-eggs** [comment]
If IG is unable to write to the EXE folder, then igconfig.xml will never appear there. So that sounds like a likely problem here.

Could this be a privilege problem? E.g. you're running as a user but the IG folder is owned by Admin? (or visa versa) [Since you copied igconfig.xml to the EXE folder, it presumably is not read-only...]

**Comment by d2phap** [comment]
@BreadBreadington You can see the location of `igconfig.xml` in Settings > General tab.

**Comment by fire-eggs** [comment]
My observed behavior: debug IG in "portable" mode. Set a breakpoint on ConfigurationFile.Cs - `ReadConfigFile` and GlobalSetting.cs - `ConfigDir`.

When IG runs, `ReadConfigFile` is looking at the `AppData` location. It is not until the *third* call to `ConfigDir` that IG starts looking at the exe folder.

For me, IG is writing an empty igconfig.xml file to the `AppData` location, then using the config file from the exe folder (and reporting as such in the settings dialog).

**Comment by d2phap** [comment]
Fixed this problem with the new ImageGlass Settings component, and it's ready to test in IG Moon version:
https://imageglass.org/moon.

There were some breaking changes in config file, please refer to #653 for further details.
Thanks all!
