### ISSUE TITLE
Web site: UI Shortcuts Reference has some issues

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#601]
### System information:
 - Windows OS version: N/A
 - ImageGlass version: 7.0.7.26

### To Reproduce
In browser, go to [https://imageglass.org/docs/ui-shortcuts-reference](https://imageglass.org/docs/ui-shortcuts-reference)

### Actual behavior:
1. Zoom In/Out: Ctrl+Mousewheel has obsolete tooltip:
`Must enable the setting: "Use the mousewheel to browse images, hold CTRL for zooming"`
Needs to be updated to match "Horizontal / Vertical Scrolling" tooltip.

2. View next image / View previous image should be updated to mention keyboard customization.

3. Zoom in / Zoom out : should be updated to mention keyboard customization

4. Horizontal / vertical scroll: now possible via arrows (if configured)

5. Suggestion: Copy / Copy image data needs more exposition to distinguish file vs image (e.g. which one allows you to paste into Microsoft Paint). [see issue #584]

**Comment by d2phap** [comment]
updated the docs
