### ISSUE TITLE
Can't open large image

### ISSUE THREAD

**Issue by Matix-Media** [d2phap/ImageGlass#603]
### System information:
 - Windows OS version: Windows 10 (x64)
 - ImageGlass version: 7.0.7.26

### To Reproduce
1. open a image that exportet from darktable with large size (<7,15MB) and resolution like 5634 x 3753

### Actual behavior:
The Program do not display the Image, its dont crash or something like this, its even displaying the name of the image. Windows 10 Pictures is able to open it.

### Expected behavior:
I thought its just open the image...

### Screenshots:
![Anmerkung 2019-08-12 175945](https://user-images.githubusercontent.com/47772205/62879291-1a0fd780-bd2b-11e9-936e-16ad6dcde14c.png)

**Comment by fire-eggs** [comment]
What image format? jpg / png / ?

**Comment by d2phap** [comment]
@Matix-Media can you send me your sample file?
Thanks

**Comment by Matix-Media** [comment]
Yeah for shure, sorry i was afk, heare is an example
its a jpg
![_MG_9555_01](https://user-images.githubusercontent.com/47772205/63210124-7b98c300-c0ea-11e9-9bc2-1860e9b21339.jpg)

**Comment by fire-eggs** [comment]
Thank you for providing the image! I was able to load it with no issues - IG has easily loaded larger (pixel size) images in the past.

However, I do find that IG 7 seems to have some memory consumption issues. The library which we use to load images will make a "peak" memory demand, before memory usage drops again. If your system is running low on available memory, then I can imagine that IG could fail to load a larger image. 

With my own experiments, I see two significant ways to reduce IG's memory usage. First, is to turn off thumbnails. Based on your initial screenshot, that applies here.

The second is to reduce the "ImageBooster" setting as much as possible. Here it is in the 'Image' tab of the settings dialog:

![image](https://user-images.githubusercontent.com/9809727/63213349-9b73bb00-c0d9-11e9-9d6d-e488958ef84e.png)

If set to zero, as shown, then memory usage can be significantly reduced. In my testing, with it on, I've seen IG peak to 5G of memory!

Please let us know if either change makes any difference for you. I think IG needs to work on a memory diet!

Thank you in advance for your help!

**Comment by d2phap** [comment]
I am able to reproduce it.
It's because the image file has invalid profile tags.

![image](https://user-images.githubusercontent.com/3154213/63213684-e45f5a00-c141-11e9-837e-dcb6436c4576.png)

**Comment by fire-eggs** [comment]
Whelp, that's just me being stupid. We've hit a bug in our underlying library, it has nothing to do with memory.  Thank you again for submitting your image!!!
