### ISSUE TITLE
Window doesn't open in the place it was last closed

### ISSUE THREAD

**Issue by docfallingapart** [d2phap/ImageGlass#606]
### System info:
- ImageGlass version: 7.0.8.5
- OS version: Windows 10 Pro 18362.295

### Expected behavior:
The window will open in the place and size as when I used it last.

### Actual behavior:
Window opens centered vertically and off the right side of the screen. Please see attached screen recording video, if it lets me attach it.
[bandicam 2019-08-18 12-58-40-320.zip](https://github.com/d2phap/ImageGlass/files/3513337/bandicam.2019-08-18.12-58-40-320.zip)

### Steps to reproduce:
1. Set Monitor to portrait mode (I didn't try landscrape)
2. open a picture and move window to bottom left corner
3. Size window to full width and 75% height
4. Close window
5. Open a picture

### Other info:
I also have a second monitor set to the top of the screen.  So if I want to move the mouse to the second monitor I would move off the top of the screen.  However, I still see the same behavior with ImageGlass even when the second monitor is disabled, so I don't think it part of the issue.

**Comment by d2phap** [comment]
Thanks, I will check this issue!

**Comment by fire-eggs** [comment]
X position is likely to be negative, which is legit. Fixed.
