### ISSUE TITLE
Change keyboard shortcuts through the Settings window

### ISSUE THREAD

**Issue by claudiuskuo** [d2phap/ImageGlass#608]

**Comment by fire-eggs** [comment]
Could you provide a concrete example? Which shortcut key(s) do you want to change?

**Comment by claudiuskuo** [comment]
Thank you!
I was wondering if there is a way for me to set "Copy Image Path" to (Ctrl+Shift+C) and "Full Image" to (F).

**Comment by Unknow0059** [comment]
It would be nice to be able to.
I'd like to edit the shortcut for the "Scale to Width" setting. I keep hitting that accidentally when I mean to close the window.

**Comment by d2phap** [comment]
@Unknow0059 
The next release will have an update for shortcuts to make it more convenient and to prepare/standardize for the keyboard shortcuts customization
![image](https://user-images.githubusercontent.com/3154213/79638516-4e8c3b00-81b8-11ea-8c82-40dfe8558719.png)

**Comment by mlewand** [comment]
Personally I'm also missing hotkey for "Copy Image Path" option :slightly\_smiling\_face:

**Comment by d2phap** [comment]
@mlewand 
"Copy image path" menu has a hotkey in the latest build of IG Moon: https://imageglass.org/moon

![image](https://user-images.githubusercontent.com/3154213/139870148-8363bdd2-353a-4e9e-8354-732c9977f14f.png)

**Comment by mlewand** [comment]
Awesome, thank you! Can't wait till it makes into stable release 🤞

**Comment by mlewand** [comment]
@d2phap thank you I can confirm that it works like a charm in the stable release 👍

**Comment by xmha97** [comment]
I need this key shortcut:
`ESC` to minimize

**Comment by xmha97** [comment]
Please add "Hotkey settings" (like ShareX)

![image](https://user-images.githubusercontent.com/23485114/150628970-beb19a0b-1e29-467a-9218-522cff606306.png)

**Comment by KonoVitoDa** [comment]
Please, let me edit shortcuts like I want. I really don't like to have to press Ctrl+Shift+C to copy an image, I would like to hit just Ctrl+C; I would like a way to toggle full-screen with F; I would like a new shortcut to close ImageGlass, like Ctrl+W; and I would like to change the order of the Fit commands.

**Comment by d2phap** [comment]
You can change the hotkey of the menus in [v9.0 beta 2](https://github.com/d2phap/ImageGlass/releases/tag/9.0.2.904).

For example:
```js
// in igconfig.json file

"MenuHotkeys": {
  "MnuOpenFile": "O",
  "MnuPrint": "Ctrl+Shift+Alt+P"
},

```

You can find all the menu names (begin with `Mnu`) in https://github.com/d2phap/ImageGlass/blob/40c22af09e81ac6ffc8b8e0f3114615677ee4c45/v9/ImageGlass/FrmMain.Designer.cs

**Comment by xS10x** [comment]
Same as [vitormathews](https://github.com/vitormathews), if it would be possible to edit shortcuts/keybindings from settings.

Pressing CTRL+Shift+S for every image I want to save as , GRUELLING. Please let the user choose the keys/shortcuts best suited.

Thank you.

**Comment by d2phap** [comment]
You already can change the hotkey of the menus in since IG v9.0 beta 2 as mentioned in my above comment.
UI for settings will be added once the stable version is released

**Comment by KonoVitoDa** [comment]
> You already can change the hotkey of the menus in since IG v9.0 beta 2 as mentioned in my above comment. UI for settings will be added once the stable version is released

But how to do it? What should I add at the `MenuHotkeys` section in igconfig.json? And how to correctly format it?

**Comment by Fr1so** [comment]
Also tried to do the above, when I try to edit MenuHotKeys unfortunately the options do not swap around:
``"MenuHotkeys": {
    "MnuCopy": "Shift+C",
    "MnuCopyImageData": "Ctrl+Shift+C"
    }``
      
 What happens is that the right click menu glitches out:
![image](https://github.com/user-attachments/assets/46d57bb5-9ad1-431c-8909-ad713fc443d6)

**Comment by d2phap** [comment]
@Fr1so The above structure is for v9.0 beta 2. It's updated in the Official release, refer to #1702

**Comment by LenyMoynat** [comment]
Hi!
Thanks for the awesome application, I'm just wondering if its possible to edit the fullscreen hotkey.
I got used to ctrl + space for full screen on most of my apps, is there a way to add this ?

I tried adding this to igconfig but its not working, I guess I typed something wrong or idk :

"MenuHotkeys": {
    "MnuFullScreen": "Ctrl+Space"
},

or

"MenuHotkeys": {
    "MnuFullScreen": ["Ctrl+Space"]
},

Thanks in advance!

**Comment by d2phap** [comment]
It should be like this:

```json
...
"MenuHotkeys": {
  "MnuFullScreen": [
    "Ctrl+Space"
  ]
},
...
```

Refer to #1702 for the hotkey discussion

**Comment by LenyMoynat** [comment]
Thanks!
One last question, is there a way to clear hotkeys ? Like disable some of them

**Comment by LenyMoynat** [comment]
Thanks! Sry I didn't see that discussion

**Comment by kovaci1** [comment]
so correct me if i m wrong. this method to change hotkey work if we modify the file from source here in git and build up the app. not from the website or store.

**Comment by d2phap** [comment]
@kovaci1 nope, you need to modify the `igconfig.json` file located in "Configuration Folder" of ImageGlass app, not the source code.

To know where the "Configuration Folder", open ImageGlass Settings > General tab

**Comment by kovaci1** [comment]
welp that was useful and way way fast (3;30am). ty man. i go to dig by my self into this but just ask any way. i just go to change 3 thing preview = Q / next = W/ Delete = E. so what happened if this have conflict with other command. and yes pls a way to turn off the Edit option which by default is microsoft paint (i guess with just remove the hotkey E for edit go to do the job)

**Comment by d2phap** [comment]
You should refer to [Redefining default hotkeys #1702](https://github.com/d2phap/ImageGlass/discussions/1702) for overriding, changing, adding hotkeys

**Comment by kovaci1** [comment]
sorry to be like this but i m doing something wrong here?
  ],
  "MenuHotkeys": {
    "MnuViewPrevious": ["Q"],
  }
  "MouseClickActions": {
    "LeftDoubleClick": {
      "ToggleOn": {
        "Executable": "IG_AutoSetActualSize",
        "Arguments": []
      }
    },
