### ISSUE TITLE
In "Play Slideshow" mode (F11), ImageGlass automatically resumes to play when "view next/previous image" is activated.

### ISSUE THREAD

**Issue by claudiuskuo** [d2phap/ImageGlass#609]
### System information:
 - Windows OS version: Any
 - ImageGlass version: 7.0

### Actual behavior:
Program automatically resumes playing slideshow once View next/previous image is activated.

### Expected behavior:
Once the user pauses the slideshow, it should prevent ImageGlass from resuming the slideshow even when "view next/previous image" is activated.

**Comment by Natopsi** [comment]
Seems related to fb673ded899f58a8b221c4c5bec27ea4f5d3bc14

This fixes it for me but I have not made any extensive testing:

```
diff --git a/Source/ImageGlass/frmMain.cs b/Source/ImageGlass/frmMain.cs
index 61d8973..1c8a027 100644
--- a/Source/ImageGlass/frmMain.cs
+++ b/Source/ImageGlass/frmMain.cs
@@ -630,8 +630,8 @@ namespace ImageGlass
             // This below fixes that.
             if (GlobalSetting.IsPlaySlideShow)
             {
-                timSlideShow.Enabled = false;
-                timSlideShow.Enabled = true;
+                //timSlideShow.Enabled = false;
+                //timSlideShow.Enabled = true;
             }
             NextPic(step, false);
         }
```

**Comment by tomphillpotts** [comment]
This happens to me also. I like to view photos full-screen and delete rejects but this makes it almost impossible to flick back and forth comparing similar photos.

**Comment by d2phap** [comment]
Thanks for the info!

**Comment by tomphillpotts** [comment]
I tried modifying the source code as in Natopsi's comment but I couldn't install from source in Windows 10 (Linux was way easier to install from source but I'm forced to use Windows now). As a workaround I'm using version 6.0.12.29 because it behaves the way I want it to: the slideshow stays stopped when I stop it.
This is a great fast photo viewer that has exactly the features I want. Thanks!

**Comment by fire-eggs** [comment]
This feature is ready in ImageGlass Moon: https://imageglass.org/moon
