### ISSUE TITLE
Filetype association issues - Minor bugs and a practical recommendation

### ISSUE THREAD

**Issue by 4294967296** [d2phap/ImageGlass#610]
Thank you for implementing all of my requests. #105 #106 #107 #108 #109 #110 #111 #112 #113

ImageGlass has become a mature project, being indisputably an excellent image viewer, maybe the best one.

## Minor Bug

Under "Settings", "File Associations", **".tif"** is listed both under "Default formats" and "Optional formats".

You may ignore the following comment, but I think it has a valid point.

The "File Associations" expression seems awkward, although widely used.

You actually associate a **filetype** with a specific app and not a particular file.

"File Associations" should probably be renamed as "FileType Associations" (or "File Type Associations").

If so, for consistency reasons, the "Open File Associations" link on the top right of the window should also be renamed accordingly.

## Minor Bug

The following registry keys are probably created due to some bug.

**[HKEY_CLASSES_ROOT\ImageGlass.AssocFile|]**

**[HKEY_LOCAL_MACHINE\SOFTWARE\PhapSoftware\ImageGlass\Capabilities\FileAssociations]
"|"="ImageGlass.AssocFile|"**

## Recommendation

I want all my images to be sorted together under Windows File Explorer (by Type).

This can be achieved if the associated image files have consistent filetype descriptions, beginning with the same character regardless of the filetype.

The description of an associated filetype can be set as the default value (nameless) of the respective key.

Using the 3FR format as an example, the default filetype description is **"3FR File"**.

The simplest filetype description that allows proper sorting is **"ImageGlass 3FR File"**.

Another simple filetype description is **"ImageGlass 3FR Image"** (if the repeated word "Image...Image" would be considered OK).

Using a VLC like style, the filetype description should be **"ImageGlass file (.3fr)"** (lowercase) or even **"ImageGlass File (.3FR)"** (UPPERCASE).

You may include a respective option under "Settings", "File Associations", providing the power to the end user to select one of the above styles, or nothing at all.

### Temporary solution

Since ImageGlass does not support setting associated filetype descriptions, I have created simple ".reg" files to add or remove such functionality.

The required ".reg" file format is very simple, you just have to add the default value under the respective keys as follows:

**[HKEY_CLASSES_ROOT\ImageGlass.AssocFile.3FR]
@="ImageGlass 3FR File"**

You have to reload the shell environment to see the changes.

You can easily revert the above changes by removing the default value as follows:

**[HKEY_CLASSES_ROOT\ImageGlass.AssocFile.3FR]
@=-**

Below, I attach the ".reg" files for evaluation purposes from community members.

If you want to import them to the registry, change the extension from ".TXT" to ".REG".

[IG_REG_ADD_DESC_01.TXT](https://github.com/d2phap/ImageGlass/files/3521180/IG_REG_ADD_DESC_01.TXT) = Descriptions like "ImageGlass 3FR File"
[IG_REG_ADD_DESC_02.TXT](https://github.com/d2phap/ImageGlass/files/3521181/IG_REG_ADD_DESC_02.TXT) = Descriptions like "ImageGlass 3FR Image"
[IG_REG_ADD_DESC_03.TXT](https://github.com/d2phap/ImageGlass/files/3521182/IG_REG_ADD_DESC_03.TXT) = Descriptions like "ImageGlass file (.3fr)"
[IG_REG_ADD_DESC_04.TXT](https://github.com/d2phap/ImageGlass/files/3521183/IG_REG_ADD_DESC_04.TXT) = Descriptions like "ImageGlass File (.3FR)"
[IG_REG_DELETE_DESC.TXT](https://github.com/d2phap/ImageGlass/files/3521184/IG_REG_DELETE_DESC.TXT) = Remove the default values from the respective keys

**Comment by fire-eggs** [comment]
>Under "Settings", "File Associations", ".tif" is listed both under "Default formats" and "Optional formats".

So it is! Nice catch!

>The following registry keys are probably created due to some bug.

Thanks for the tip!

**Comment by d2phap** [comment]
@4294967296 
It's done in IG Moon: https://imageglass.org/moon
