### ISSUE TITLE
Improve Frameless Mode: Close/Minimize/Maximize buttons

### ISSUE THREAD

**Issue by xmha97** [d2phap/ImageGlass#611]
Dear Phap
I using ImageGlass in Full-screen mode.
Please add the close button for the toolbar. (Only in Full-screen mode)
![ImageGlass Toolbar](https://user-images.githubusercontent.com/23485114/63387618-234c1480-c3bb-11e9-9318-5ae3494eb90f.png)

**Comment by fire-eggs** [comment]
For now you can use the 'Exit Imageglass' option from the main menu:
![image](https://user-images.githubusercontent.com/9809727/63448100-456d8300-c40b-11e9-81c4-77bce6950f84.png)

**Comment by amirrammari** [comment]
> For now you can use the 'Exit Imageglass' option from the main menu:
> ![image](https://user-images.githubusercontent.com/9809727/63448100-456d8300-c40b-11e9-81c4-77bce6950f84.png)

This is not user-friendly.
I need a separate button.

**Comment by amirrammari** [comment]
![ImageGlass](https://user-images.githubusercontent.com/23485114/71869635-00cb5580-3128-11ea-88ae-dd209aa85fc6.png)

**Comment by d2phap** [comment]
Hi @amirrammari 
for now you can use shotcuts: `Window + arrow keys` instead.

**Comment by amirrammari** [comment]
Thank you.
Now I can Minimize the app using `Win+Down`

**Comment by mirh** [comment]
Hoping this isn't too much hijacking, frameless is also lacking any kind of window size control (i.e. those little arrows instead of the mouse pointer when the cursor is over some border). 
It's very strange since a lot of of other borderless programs still support that.

**Comment by xmha97** [comment]
@d2phap Please add some toolbar images (for Close, Minimize, Maximize)
Now I have to use delete image for exit :)

**Comment by xmha97** [comment]
@d2phap Please add some toolbar images (for Close, Minimize and Maximize)
![image](https://user-images.githubusercontent.com/23485114/232207750-60028413-dab9-468b-bbf1-42cc80eb6214.png)

**Comment by xmha97** [comment]
@d2phap Now It's possible to add window control buttons to the toolbar.
You can close this issue.
