### ISSUE TITLE
In application thumbnails of multi-layer PSD files don't load, high CPU usage

### ISSUE THREAD

**Issue by InfectedMushroom9** [d2phap/ImageGlass#617]
### System information:
 - Windows OS version: Windows 10 Enterprise LTSC 1809
 - ImageGlass version: 7.0.7.26

### To Reproduce
1. Put a few image files in a folder
2. At least one of them is a PSD file with a lot of layers (one of the problem files: [Boeing 787-9.zip](https://github.com/d2phap/ImageGlass/files/3586973/Boeing.787-9.zip))
3. Open one of the files with ImageGlass
4. Press Ctrl + T to show thumbnail previews

### Actual behavior:
The thumbnails for the PSD files never load, but CPU usage is very high
![Capture](https://user-images.githubusercontent.com/55032991/64479530-0b8cd280-d1a8-11e9-9fac-fed96dcdae3f.PNG)
If you close the thumbnail preview panel, CPU usage is gone 
![Capture1](https://user-images.githubusercontent.com/55032991/64479540-2101fc80-d1a8-11e9-8fa0-151dd84f5ccb.PNG)

**Comment by d2phap** [comment]
Thanks @InfectedMushroom9 
Confirm the issue

**Comment by d2phap** [comment]
- It also causes a bug that PSD images don't generate thumbnails
- Fixed this bug and shipped in the latest IG Moon: https://imageglass.org/moon
