### ISSUE TITLE
navigation arrow buttons collide with viewer scrollbars

### ISSUE THREAD

**Issue by IlO0OlI** [d2phap/ImageGlass#618]
### System information:
 - Windows OS version: Windows 10 1903
 - ImageGlass version: 7.0.7.26

### To Reproduce
1. ![f6aPpV83i15cjSu.png](https://i.loli.net/2019/09/08/f6aPpV83i15cjSu.png)
2. zoom in until scrollbars appear
3. ![DTCGLHyj4KAvlEq.jpg](https://i.loli.net/2019/09/08/DTCGLHyj4KAvlEq.jpg)
4.

**Comment by d2phap** [comment]
Fixed in ImageGlass Moon https://imageglass.org/moon
