### ISSUE TITLE
Titlebar: Ability to select date/time to show date modified instead of date created

### ISSUE THREAD

**Issue by Beet4** [d2phap/ImageGlass#619]
### Is your feature request related to a problem? Please describe.
I use OneDrive to automatically upload all my images to the cloud. If the setting is set to upload for example only when charging the "Date created" on the image is set to when it is uploaded to OneDrive (when the file is created on OneDrive). Therefore the date shown in the titlebar of ImageGlass shows the wrong date and/or time as it seems to be based on "Date created" instead of "Date modified". This is very misleading in my opinion. Date modified seems to be a more proper way to show when the image is taken.

I think this may be true in many more situtations, not just other cloud services but in other cases as well.

### Describe the solution you'd like
I would like to see a setting where you can choose what the timestamp in the titlebar should be collected from, either date created or date modified.

### Additional context
![ImageGlass 2019-09-09 14 55 47](https://user-images.githubusercontent.com/38279393/64532818-8bcf4700-d312-11e9-868c-075fe635920d.png)
![explorer 2019-09-09 14 56 06](https://user-images.githubusercontent.com/38279393/64532846-9689dc00-d312-11e9-86f3-d6523f118c49.png)
The image in the example above is taken 17:56 and not 23:08.

**Comment by fire-eggs** [comment]
Now superceded by #687

**Comment by d2phap** [comment]
This feature is ready in ImageGlass Moon, for more details: https://github.com/d2phap/ImageGlass/issues/687#issuecomment-603925112
