### ISSUE TITLE
F2 for rename does not focus filename field / text

### ISSUE THREAD

**Issue by frodebh** [d2phap/ImageGlass#622]
When renaming, you have to doubleclick in the modal box text field to activate it and select text. 
This feels like an unnecessary step, especially when you have lots of files to rename. 

Thanks for all of your great work it is appreciated!

**Comment by d2phap** [comment]
Hi @frodebh 

In my test, when I press F2 or click on Rename menu, the textbox is focused and all the text selected by default

![image](https://user-images.githubusercontent.com/3154213/65162471-dfa50300-da6b-11e9-9d6d-b75243ada2e9.png)

**Comment by frodebh** [comment]
This was caused by having the colour picker open, when  I closed the picker filename is selected as expected. 
Sorry for the late reply, thank you for responding and for the great app.
