### ISSUE TITLE
Apply button does nothing

### ISSUE THREAD

**Issue by thegamerx1** [d2phap/ImageGlass#623]
![21_09_2019_7Yrwn](https://user-images.githubusercontent.com/34986564/65375340-8ec42300-dc94-11e9-8168-f43a1b4b89f7.gif)

**Comment by d2phap** [comment]
Hi @thegamerx1 

You need to click on the main window to see the new changes. 
Apply button does not trigger the changes, it just saves the settings

**Comment by thegamerx1** [comment]
If i focus the main window the settings window goes under the main window.. Could atleast apply button trigger changes?

**Comment by MartBlur** [comment]
@d2phap You still need to provide some sort of feedback to the user that the button actually did something at all. The button doesn't even gray out like it would in any other piece of software. Up till today I _didn't know the button worked._

**Comment by d2phap** [comment]
marked this as `improvement` 😶

**Comment by thegamerx1** [comment]
cleaning my issues

**Comment by fire-eggs** [comment]
Two others have indicated approval of this issue, so it is still valid.

**Comment by d2phap** [comment]
This issue is fixed in [ImageGlass 9.0 beta 5](https://github.com/d2phap/ImageGlass/releases/tag/9.0.5.726)

**Comment by inson1** [comment]
@d2phap Why not unite save and apply buttons? 
Is there use case in which user doesnt want to apply settings but only to save the settings? OR wants to apply settng but not to save the settings?
