### ISSUE TITLE
关于ImageGlass的一些建议 : Hide Title Bar; Show Exif Data

### ISSUE THREAD

**Issue by shep2008** [d2phap/ImageGlass#626]
首先这是我目前见过的最好的图片浏览器,提一些意见,希望能更完善
1.建议保持统一的主题风格,标题栏的颜色和空白区域的颜色保持一致;(窗口模式)
2.建议标题栏了也可以隐藏,标题信息可以直接以透明字体加投影的方式显示在图片内容上,而且当鼠标移动到标题栏位置的时候工具栏自动显示出来(窗口模式、全屏模式)
3.可以以透明字体加投影的方式显示EXIF,并且EXIF可以自定义显示条目，(窗口模式、全屏模式)
以上功能都建议可以使用快捷键完成
谢谢
![图片浏览器建议](https://user-images.githubusercontent.com/42241740/65661971-a5d48d80-e065-11e9-8165-971e128ad7fc.jpg)

**Comment by shep2008** [comment]
![图片浏览器建议](https://user-images.githubusercontent.com/42241740/65661614-acaed080-e064-11e9-8eba-eec296b8ec10.jpg)

**Comment by d2phap** [comment]
Hi @shep2008 
It will be nice if you can write your post in English.

**Comment by fire-eggs** [comment]
via Google Translate:

First of all, this is the best photo browser I have seen so far. I would like to make some comments and hope to be more perfect.

1. It is recommended to maintain a uniform theme style, the color of the title bar and the color of the blank area are consistent; (window mode)

2. The suggested title bar can also be hidden. The title information can be directly displayed on the image content in a transparent font and projection, and the toolbar is automatically displayed when the mouse moves to the title bar position (window mode, full screen mode).

3. EXIF ​​can be displayed in a transparent font plus projection, and EXIF ​​can customize the display items (window mode, full screen mode)
The above functions are recommended to be completed using shortcut keys.
Thank you

**Comment by fire-eggs** [comment]
Need to break this up into separate feature request issues.

**Comment by fire-eggs** [comment]
#1: not understood. how are the theme styles not uniform?
#2: duplicated by #658 
#3: duplicated by #336
