### ISSUE TITLE
Old filename after change in title bar

### ISSUE THREAD

**Issue by DGardell** [d2phap/ImageGlass#627]
### System information:
 - Windows OS version: 10
 - ImageGlass version: 7.0.7.26

### Questions
Hello. I have the display basename of the viewing image in title bar option enabled. Because I don't want the full path as title. 
But it have happened many times that I've looked at a picture, then through windows explorer changed the filename. But when I open the new name in Image Glass, it still says the old one in the title bar. 
I've even made a copy of a file and renamed it, but it still shows the original filename. How is that possible? Is there some indexing function in Image Glass?

Thanks.

**Comment by d2phap** [comment]
Hi @DGardell 
I checked the renaming function problem as you mentioned, it worked well all of times.
If you can attach a video, i will be more clear for me because to fix the bug, I need to reproduce it :)

Thanks
