### ISSUE TITLE
"If, then, else" zoom options

### ISSUE THREAD

**Issue by CallMeWoody** [d2phap/ImageGlass#628]
Hi Phap Dieu Duong !
Here is my request 

### Is your feature request related to a problem? Please describe.
 When scrolling through small images, it keeps resetting the zoom-in which makes it difficult to read text and is inefficient because you keep clicking on the "Real size" button

### Describe the solution you'd like

An "if, then, else" zoom option setting, let's say like "If the image is smaller than the viewport, then make the zoom real size, else make it adapt to the viewport"

### Additional context

I have been loving your program and an option like that would make me switch completely from the legacy Windows Photo Viewer 

Thank you very much anyway if you take that request into consideration,
Have a good day!
CMW

**Comment by CallMeWoody** [comment]
There's an automatic zoom I didn't find in the options which does exactly what I was looking for

Sorry for the bother!

**Comment by d2phap** [comment]
:)
