### ISSUE TITLE
 Suggestions for ImageGlass to the animate pictures like GIF, APNG and so on.

### ISSUE THREAD

**Issue by 265785** [d2phap/ImageGlass#629]
I strongly recommend that you can create a little toolbar in the ImageGlass for the animate pictures like GIF, APNG and so on. And it will make your software more practical, convenient and controlable.
Here is a good example in another photoviewer:
![搜狗截图20191001234542](https://user-images.githubusercontent.com/56037874/65980485-dd01cf00-e4a9-11e9-9289-efb7f5556461.png)
![无标题](https://user-images.githubusercontent.com/56037874/65980494-e1c68300-e4a9-11e9-88d7-126d63228a4a.png)
![QQ截图20191001234606](https://user-images.githubusercontent.com/56037874/65980934-b09a8280-e4aa-11e9-87c6-9c59e70aced1.png)
I sincerely hope that you can receive my suggestions. 
Thank you!

**Comment by d2phap** [comment]
hi @265785 
Can you translate the chinese in your screenshots above?

**Comment by 265785** [comment]
![QQ截图20191001234606](https://user-images.githubusercontent.com/56037874/66036032-e6894680-e53e-11e9-9977-28ba7fc88a8b.png)
I want to tell you another problem. 
Also, Your software becomes very slow when you open a very large picture (Higher or wider than 7,000 pixels), and the picture is difficult to zoom in, difficult to drag, and takes up a lot of RAM memory. This is especially true when Zoom Optimization changed to Smooth pixels and Auto. Changing the number of caches doesn't improve, so hopefully you can optimize the speed and RAM use at which you open and browse, zoom in, drag and drag oversized pictures, just like fsviewer and MassiGra.
Thank you!

**Comment by d2phap** [comment]
Thanks @265785 

> Your software becomes very slow when you open a very large picture (Higher or wider than 7,000 pixels)

This is a limitation mentioned in #272

**Comment by skycommand** [comment]
Hello. This is a very thorough suggestion, but right now, APNG does not seem to be supported at all. Am I right?

**Comment by fire-eggs** [comment]
> Hello. This is a very thorough suggestion, but right now, APNG does not seem to be supported at all. Am I right?

Correct - see issue #396

**Comment by skycommand** [comment]
Thought so.

Recently, I find myself watching animated GIF and PNG files. More accurately, I drag them out of the web browser window into my desktop where I can play them with my video player. It seems to me that there has been a recent influx of animated image formats used for screencasting. (And I cannot emphasize how inappropriate their choice of format is.)

**Comment by fire-eggs** [comment]
>It seems to me that there has been a recent influx of animated image formats used for screencasting. (And I cannot emphasize how inappropriate their choice of format is.)

Interesting. Can you give me an example of these "new" formats?
 
> Maybe this is what everyone should do. Maybe animated images are best left for video players.

I have the opposite issue. On Imgur, it seems like almost every "gif" has been converted to an MP4 file! GIF always seemed to be perfectly adequate to me - and a GIF converted to MP4 will be larger and no better quality.

But it's quite likely that when someone says "GIF" they're using it as a generic term for "animation". The GIF format does have limitations where a video format might be a better choice.

**Comment by skycommand** [comment]
> Interesting. Can you give me an example of these "new" formats?

Actually, what I said was:

> a recent influx of animated image formats used for screencasting

In other words, I've recently seen a lot of cases in which animated image formats (i.e. Animated GIF, APNG; nothing new) are used for screencasting. Example: <https://code.visualstudio.com/updates/v1_41>

**Comment by fire-eggs** [comment]
Gotcha! Sorry for the confusion.

**Comment by DarkEnchanter1** [comment]
Personally I feel that things like GIF and apng belong in an image viewer rather than a dedicated video player. For one thing, video players are "heavy", and meant for playing long videos, not <5 second animation loops.

**Comment by d2phap** [comment]
You can use Frame Navigation tool in v9
