### ISSUE TITLE
ImageGlass Won't Open with Latest Version on Latest Windows 10 Update

### ISSUE THREAD

**Issue by davidlieberman** [d2phap/ImageGlass#632]
### System information:
 - Windows OS version: 1903 10.0.18362 Build 18362
 - ImageGlass version: 7.0.7.26

### Actual behavior:

When I click to launch ImageGlass nothing pops up. Checking Task Manager shows the process doesn't even start (as far as I can tell). ImageGlass had been working fine on this version for months, but the latest Windows Update seems to have borked it for me. I went back through old versions, and ImageGlass_5.5.7.26 starts for me, but anything later will not open.

**Comment by d2phap** [comment]
Thanks @davidlieberman 

Can you go to `%appdata%\imageglass\` and check the content of `igconfig.xml` file (or you can send me). It can be relevant to #542

**Comment by davidlieberman** [comment]
Sure no problem. I actually fired up ProcessHacker, and it seems like if I try and run ImageGlass through there, the process briefly starts before immediately crashing. GitHub isn't allowing me to attach an XML, so I put it in a ZIP. 
[igconfig_xml.zip](https://github.com/d2phap/ImageGlass/files/3692862/igconfig_xml.zip)

**Comment by d2phap** [comment]
@davidlieberman  Thanks for the file!
I pushed a new version for ImageGlass Moon, you can download at: https://imageglass.org/moon

If the `igconfig.xml` file is invalid, IG will create an empty file. But it's better to understand why the file become invalid. If you have any information to reproduce, it will be awesome!

**Comment by davidlieberman** [comment]
Yeah, unfortunately I have no idea what caused this -- I just know I had a Windows update about a week back and then couldn't open ImageGlass :/
