### ISSUE TITLE
HEIF image rotation incorrect

### ISSUE THREAD

**Issue by vinha** [d2phap/ImageGlass#633]
### System information:
 - Windows OS version: 10.0.18362 Build 18362
 - ImageGlass version: ImageGlass_7.0.7.26, ImageGlass_Moon_7.0.8.5 (both tested)

### To Reproduce
1. Open vertical HEIF photo captured with an iPhone

### Actual behavior:
The image is not shown as vertical, but instead horizontal

### Expected behavior:
The image should be automatically rotated as set in image metadata.

**Comment by d2phap** [comment]
Thanks @vinha for the bug report.
Please refer to #559 as this is a duplication
