### ISSUE TITLE
Some 32-bit integer TIF files no longer openable in 7.0.7.26

### ISSUE THREAD

**Issue by rohan-shah** [d2phap/ImageGlass#637]
### System information:
 - Windows OS version: Windows 10 Pro, Version 1709
 - ImageGlass version: 7.0.7.26

### To Reproduce
1. Open file [EGIPAGWQGLDNGPESR_2.1.tif.zip](https://github.com/d2phap/ImageGlass/files/3709899/EGIPAGWQGLDNGPESR_2.1.tif.zip) in Imageglass 7.0.7.26

### Actual behavior:
File does not open

### Expected behavior:
File should open, and look the same as in Imageglass 6.0.12.29

### Additional context:
Attached file is a TIF with three 32-bit integer channels, which is slightly unusual. It used to open just fine in Imageglass 6. 

Presumably related to the replacement of ImageGlass.Core by ImageGlass.Heart

**Comment by rohan-shah** [comment]
Damn, that was quick. Love your work!

**Comment by fire-eggs** [comment]
Only possible because of your useful bug report! Thank you!

**Comment by d2phap** [comment]
Shipped in IG Moon, you can download it at:
https://imageglass.org/moon
