### ISSUE TITLE
Add 'edit image' button for the toolbar

### ISSUE THREAD

**Issue by PngHD** [d2phap/ImageGlass#641]
Could you add an option that allows to manually select the desired default photo editing software? Thanks.

And also the option "open with" on the right click menu that allows to add a list of software to choose. Thanks.

**Comment by d2phap** [comment]
> Could you add an option that allows to manually select the desired default photo editing software? Thanks.

You can manually set the editing app in Settings
![image](https://user-images.githubusercontent.com/3154213/67148072-a7dce580-f2cd-11e9-9319-bfe00ba2bd32.png)

**Comment by PngHD** [comment]
Thank you so much. I didn't notice that the option was there. It's perfect.

**Comment by PngHD** [comment]
Thank you so much!
