### ISSUE TITLE
Actual Zoom button in toolbar

### ISSUE THREAD

**Issue by vadimhp** [d2phap/ImageGlass#643]
Sometimes when I open an image I want to see it in its full glory - in its actual size - right away.

It would be great to have a "Zoom to actual size" button in the toolbar.

Going to the main menu  > Zoom > Actual size is just too many steps.

The keyboard shortcut for Actual Size is hard to memorize - too many apps with too many keyboard shortcuts out there

Thank you!

**Comment by d2phap** [comment]
Hi @vadimhp 

You can go to Settings > Toolbar to add this button to toolbar.
For the hotkey, you can press `0` or `Ctrl+0` or `NumPad0`

![image](https://user-images.githubusercontent.com/3154213/67162324-657edb80-f395-11e9-9b44-fb5ae2cbd11d.png)

**Comment by vadimhp** [comment]
silly me :)
