### ISSUE TITLE
Program empties the config file when closing two or more instances at once

### ISSUE THREAD

**Issue by MisteryDuck** [d2phap/ImageGlass#644]
### System information:
 - Windows OS version: Windows 7 Ultimate, Service Pack 1
 - ImageGlass versions: 7.0.7.26 and 7.0.10.20 (Moon) 
### Actual behavior
When two or more instances of the program are running, if closed from the taskbar all at once, the program removes almost all entries from the config file and starts first-launch wizard if launched again. This is true for the newest moon version as well
### To reproduce
Run the ImageGlass.exe twice, right click the program on the taskbar and press the "Close all windows" button in the context menu

**Comment by d2phap** [comment]
There was a problem when the config file became invalid, ImageGlass could not launch anymore, reported in #542.
My temporary solution was to create a new config file.

Thanks for your report, I am able to reproduce it
> Run the ImageGlass.exe twice, right click the program on the taskbar and press the "Close all windows" button in the context menu

**Comment by d2phap** [comment]
Fixed this problem with the new ImageGlass Settings component, and it's ready to test in IG Moon version:
https://imageglass.org/moon.

There were some breaking changes in config file, please refer to #653 for further details.
Thanks all!

**Comment by AntumDeluge** [comment]
@MisteryDuck: Thank you for this report. I was having the same issue but didn't know what was causing it. @d2phap: I will download the latest Moon version. Thank you.
