### ISSUE TITLE
IG quit unexpectedly when open HEIC image

### ISSUE THREAD

**Issue by DELNEGEND** [d2phap/ImageGlass#647]
### System information:
 - Windows OS version: Window 10 1903 x64 (Build 18362.449)
 - ImageGlass version: 7.0.7.26 (x64 version)

### To Reproduce
Open .HEIC image

### Actual behavior:
IG closed after a few seconds (seems like it was loading something) when I was opening some HEIC images, no warning nor "...is not responding", just like I hit the X button.

### Additional context:
Images I'm having trouble with:
https://drive.google.com/open?id=1eqKJG5OZfpbqzDtARZEFRBv-wdMsUfjD

![bandicam-2019-11-06-19-47-51-355_1](https://user-images.githubusercontent.com/20481024/68300777-0a592280-00d1-11ea-9ff0-3558a808fa68.gif)

**Comment by d2phap** [comment]
Thanks @DELNEGEND 
This is a bug of Magick.NET library, I just reported to them at https://github.com/dlemstra/Magick.NET/issues/533

**Comment by fire-eggs** [comment]
FYI: other major viewers (IrfanView, XnView) can't view these images either.

**Comment by RanHum** [comment]
No, IrfanView can display it with heif image extensions form microsoft store: 
![image](https://user-images.githubusercontent.com/11231107/68341085-81aaa880-0109-11ea-83d1-2e5e812de98a.png)

**Comment by fire-eggs** [comment]
Thank you for the correction!

**Comment by d2phap** [comment]
upgraded Magick.NET to 7.15, and fixed in IG 7.5
