### ISSUE TITLE
Left double-click = Full Screen

### ISSUE THREAD

**Issue by Vig2OOO** [d2phap/ImageGlass#648]
Hi - can you consider making left double-click as the mouse shortcut for making an image full screen?  Left double-click currently zooms the image.  I'm using HydraMouse to associate left double-clicking with full screen, but it would be great if ImageGlass natively allowed this as an option.

**Comment by Slomo17** [comment]
I would love to see this feature as well, maybe make it configurable what double click does, as some people seem to prefere the current zoom function.

**Comment by alexantr** [comment]
I also like middle-button click to go fullscreen

**Comment by turmoggy** [comment]
Yes I've used middle button to go to full screen and see its not available in imageglass.

**Comment by d2phap** [comment]
You can do this in [v9.0 beta 2](https://github.com/d2phap/ImageGlass/releases/tag/9.0.2.904).

See more details and example here: https://github.com/d2phap/ImageGlass/issues/991#issuecomment-1238130837
