### ISSUE TITLE
No thumbnails in new version (7.0.7.26)

### ISSUE THREAD

**Issue by TobyOne** [d2phap/ImageGlass#649]
### System information:
 - Windows OS version: 10
 - ImageGlass version: 7.0.7.26

### To Reproduce
1. Can't get the thumbnail scrollbar anymore, changed settings multiple times
2. 
3. 
4.

**Comment by d2phap** [comment]
I don't have any problem with thumbnail scrollbar.

Can you attach screenshot?

![image](https://user-images.githubusercontent.com/3154213/68876441-6bbb6a00-073f-11ea-8c8b-8823dee0326c.png)

**Comment by TobyOne** [comment]
Hi,

Yes here you go. It worked in all the previous versions for me.

All the best
Torbjörn

[image: image.png]

Den tors 14 nov. 2019 kl 17:33 skrev Phap Dieu Duong <
notifications@github.com>:

**Comment by fire-eggs** [comment]
Sorry, the screenshot didn't get attached properly. A copy of your igconfig.xml file might be helpful as well.

**Comment by TobyOne** [comment]
Ok, I´ll try again :)



Den tors 14 nov. 2019 kl 18:34 skrev Kevin Routley <notifications@github.com

**Comment by TobyOne** [comment]
Sorry, I just saw that the current igconfig is in the roaming directory
see attached file

Den tors 14 nov. 2019 kl 18:42 skrev Torbjörn Jönsson <tobbe.hem@gmail.com>:

**Comment by fire-eggs** [comment]
Still not getting any attachments.

One thing you can look at (it has given me problems in the past) is this setting in your igconfig.xml file [copied from mine, yours is probably different]:

`      <Item key="ThumbnailBarWidth" value="116" />`

If that setting has somehow been corrupted and the value set to zero or negative, then the thumbnails might not be visible. You can change the value, using an editor such as Notepad, to something reasonable (e.g. 150) or even just delete the line, and IG will use a reasonable default on restart.

**Comment by TobyOne** [comment]
Ok, I'll try that tomorrow. Thanks for your help 👍👍👍

Den tors 14 nov. 2019 19:10Kevin Routley <notifications@github.com> skrev:

**Comment by TobyOne** [comment]
Hello,

I tried your suggestion but it didn't work. However I found this in the xml
file: <Item key="IsShowThumbnail" value="False" /> and when I changed it to
true it worked (of course :))

Thanks for your help!

Den tors 14 nov. 2019 kl 19:12 skrev Torbjörn Jönsson <tobbe.hem@gmail.com>:

**Comment by d2phap** [comment]
Thanks for the info
