### ISSUE TITLE
Main menu with toolbar off appears in random locations

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#650]
### System information:
 - Windows OS version: Win 7
 - ImageGlass version: 7.0.7.26

### To Reproduce
1. Run imageglass.
2. Make sure toolbar is off.
3. Use ` to invoke settings menu - note location. Close it.
4. Use alt+enter to make IG full screen
5. Use ` to invoke settings menu - note location. Close it.
6. Use alt+enter to make IG a window again.
7. Use ` to invoke settings menu - note location. Close it.
8. Resize IG window.
9. Use ` to invoke settings menu - note location. Close it.

### Actual behavior:
I've had the settings menu appear in different locations. In full-screen mode, sometimes way off to the right of the screen, and sometimes in the left one-third. In window mode, the menu has sometimes appeared within the window boundary, and sometimes way off to the right of the screen, no-where near the window boundary.

### Expected behavior:
The settings menu should appear in a consistent location, approximately near where it would appear if the toolbar was on. Namely, toward the right edge of the IG "window".

### Screenshots:
![image](https://user-images.githubusercontent.com/9809727/68882036-57925100-06dc-11ea-9d6e-8e918a96e58f.png)

**Comment by d2phap** [comment]
I think this issue does not impact much to the overall user experience. So I will close.
