### ISSUE TITLE
Debug mode?

### ISSUE THREAD

**Issue by miharix** [d2phap/ImageGlass#652]
### System information:
 - Windows OS version: Win10
 - ImageGlass version: 7.0.7.26

### Questions
How do I enable debug log output in ImageGlass ?

I have a strange problem in combination of ImageGlass and LotusNotes and would like to check what command is ImageGlass executed...

**Comment by d2phap** [comment]
Hi @miharix 
ImageGlass does not write log at all in the current version. So you can describe the "strange problem" here, I may help you.

**Comment by miharix** [comment]
Hi @d2phap 

when opening attachemnt in mail, when mail has multiple atachments in Lotus
The file is correctly saved in temp folder under AppData\Local\Temp\notes_ID_
But, displayed image is allways the first image in this folder, not that user is trying to open.

**Comment by fire-eggs** [comment]
What you can do is use Process Explorer. You can download it from [here](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer).

What Process Explorer will let you do is to see the command line that occurred when ImageGlass was invoked.

1. Run your LotusNotes, open an attachment in mail.
2. (Presumably) ImageGlass runs.
3. Run Process Explorer.
4. Find ImageGlass in the list of processes.
5. Right-click on ImageGlass and show Properties. Or even just hover over the line, the tooltip will show the command line.
The command line used to invoke ImageGlass is shown.

For example, here is Process Explorer showing the ImageGlass properties on my system. I invoked ImageGlass by double-clicking an image file in Windows Explorer.

![image](https://user-images.githubusercontent.com/9809727/68962341-562b5c00-07a2-11ea-96e9-debedce5e85c.png)

Microsoft also provides another tool called Process Monitor, which I understand can also view the command line. However, it must be running _before_ ImageGlass is invoked.

Hope this helps; let us know what Lotus Notes is doing!

**Comment by miharix** [comment]
Hi,

still on searching but for now just info where it looks to be the problem
My user name on win is miha.admin when opening from Lotus its calling path
C:\Users\MIHA~1.ADM\AppData\Local\Temp\notes7AC391\
and not 
C:\Users\miha.admin\AppData\Local\Temp\notes7AC391

this path shortening seems to be the problem.

**Comment by miharix** [comment]
My coworker has fund the bug and fixed the problem:
https://github.com/d2phap/ImageGlass/pull/654

**Comment by d2phap** [comment]
Thanks @miharix  so much
I will take a look!

**Comment by d2phap** [comment]
Merged the PR. Thanks!
