### ISSUE TITLE
ImageGlass does not remember settings when closing all windows

### ISSUE THREAD

**Issue by Yukari9** [d2phap/ImageGlass#659]
### System information:
 - Windows OS version: 10
 - ImageGlass version: 7.0.7.26

### To Reproduce
1. Open ImageGlass and change any of the settings, making sure to apply and save
2. Open multiple instances of ImageGlass
3. Right click the ImageGlass program on the taskbar and select 'Close all windows'
4. Start up ImageGlass again, it will go to first time setup, and all changes to settings will be lost

### Actual behavior:

After changing any of the settings in ImageGlass, they are lost even after applying and saving them, and reset back to default. The first time setup prompt will even appear as well. This occurs after changing, applying and saving any of the settings, then afterwards opening multiple instances of the program. If one uses the "Close all windows" function by right-clicking the program in the taskbar, the next time ImageGlass opens it will prompt the first time setup, and none of the previously applied and saved settings will be remembered.

### Expected behavior:

It should not be thinking it is the first time I am setting up if after I use the "Close all windows" function, and be remembering my settings.

### Screenshots:

![image](https://user-images.githubusercontent.com/58572941/70275493-f8ff5500-17f9-11ea-8505-4058c2186b6f.png)

### Additional context:

I have tried launching the program as admin, and moved the directory of the program to a place where admin permissions are not required to write. I have made sure that none of the folders it is in are set to 'read only'. Uninstalling and reinstalling did not help, neither did restarting the computer. I have tried everything I can think of, and it happens only when "Close all windows" is used, ImageGlass will remember my settings as long as I do not use that function.

**Comment by d2phap** [comment]
Hi @Yukari9 
Please try the latest build of ImageGlass Moon at https://imageglass.org/moon which fixed this bug reported in #644 

Let me know if it works.
Thanks
