### ISSUE TITLE
Hamburger Menu placement issues.

### ISSUE THREAD

**Issue by ConundrumAdInfinitum** [d2phap/ImageGlass#66]
Hi. Nice app.

The Hamburger Menu, however, should be in the Top Left corner, matching the design language of all other Windows 10 apps.

It's extremely visually awkward to have the Hamburger/Main menu pop up and be trailing off to the right, outside of the window frame.

Really looks and functions bad, as you're expecting it to be in the same place as all other apps with it on the platform.

Please Fix.

**Comment by daveloyall** [comment]
Also, with dual monitors, the hamburger menu opens on the wrong screen sometimes.

**Comment by ConundrumAdInfinitum** [comment]
Perhaps using the Centennial bridge to make a UWP App for Windows could be the best solution.
