### ISSUE TITLE
Inspect/edit image metadata and properties

### ISSUE THREAD

**Issue by bastianilso** [d2phap/ImageGlass#661]
### Is your feature request related to a problem? Please describe.
When I design posters, render 3D images, create open badges or go through photos from unknown sources, I need context information about image - its properties and metadata.

### Describe the solution you'd like
I would like an ability to see image properties and possibly edit this metadata within the viewer itself, either as overlaid text in the toolbar, in a sidebar or similar.

### Describe alternatives you've considered
I understand I can use Ctrl+I to get the Windows or platform-specific properties window shown, but its just not always making the cut and I cannot edit metadata or properties like fx what DPI the image is in, or the color profile the image is using.

**Comment by fire-eggs** [comment]
Viewing of metadata is duplicated in #336.

**Comment by d2phap** [comment]
merge this to #336

**Comment by d2phap** [comment]
Implemented Exif tool in ImageGlass Moon: https://imageglass.org/moon
For more details, check at #871
