### ISSUE TITLE
Multiple external image editors for the same image type

### ISSUE THREAD

**Issue by Crivens** [d2phap/ImageGlass#666]
### Is your feature request related to a problem? Please describe.
A GIF can be a simple image that I edit in PSP for developing websites, but it can also be an animated file that would be better edited in a different tool than PSP (only handles first frame). Currently you can only open a single external app to edit the file. Sometimes though it is just a better idea to use a simple tool (eg. Paint) than a full featured editor (eg. PSP), so it would be nice to have the option

### Describe the solution you'd like
I would like the ability to add a second external editing app per image type. Then you have the option to edit the image as you do now, but also to edit the image in a secondary external app. Specifically for GIFs then it would also be good if ImageGlass detects if the GIF is animated and then launches the alternative external editor

**Comment by d2phap** [comment]
In v9.0, you can add external apps and assign hotkey to open it in Settings > Tools.
