### ISSUE TITLE
Request: Command Line Configuration

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#669]
From the [Google forum](https://groups.google.com/g/imageglass/c/AqqxuI3H8qA/m/E-vp0HUWBgAJ) :

>Scusa il mio poco sapere
ma avrei necessità di realizzare un file bat al fine di lanciare ImageGlass sul secondo monitor in modalità Full Screen, Slideshow, parti da ultima immagine presentata. Mi sembra elementare ma io non sò realizzarlo.
Grazie

>Sorry for my little knowledge
but I would need to create a bat file in order to launch ImageGlass on the second monitor in Full Screen mode, Slideshow, starting from the last image presented. It seems elementary but I don't know how to do it.

This is something I recently realized I would like myself. Alas, this is not elementary. 

I can't get you all those conditions either, only some of them. For instance, IG currently will not restore to full screen mode on the 2d monitor, only the primary monitor. Also, IG is able to start in slideshow, but it is initially paused.

So here's how to do what you can:
1. Run image glass.
2. Make sure it is positioned on the second monitor. 
3. In the settings dialog, make certain that "start from last image" is enabled. Also check any other settings are as you desire: slideshow timer, "show countdown" and so on.
3. Open your desired first image.
4. Start slideshow mode.
5. Immediately exit IG using Alt+F4.

What you should have at this point is an igconfig.xml file which has the settings you desire. Make a copy of this igconfig.xml file to someplace else, e.g. "ig_slideshow.xml".

Your batch file would then read something like:
```
copy /Y ig_slideshow.xml igconfig.admin.xml
imageglass
del /F /Q igconfig_admin.xml
```

The batch file has to be executed in the folder where Imageglass.exe resides. The igconfig.admin.xml file will override any existing settings. By deleting it afterwards, you restore previous functionality.

Or, you could make a copy of your ImageGlass folder, with "ig_slideshow.xml" in place as "igconfig.xml", and use a desktop shortcut to execute that copy of ImageGlass.

I hope that was sufficiently clear ...  Neither easy nor elementary. Maybe Phap will point out some detail or capability that I've missed.

For me, when I used this setup the result was:
a. Imageglass in a window on the second monitor
b. showing the last image (i.e. the first image of the slideshow)
c. the slideshow paused

I recently had reason to desire similar functionality myself. I think we have an unmet need here which I'd like to address soon. It won't happen in for the 7.5 release.  I'll be tracking this in the ImageGlass repository here.

**Comment by fire-eggs** [comment]
Issues I take from this:

- Ability to pass a config file via the command line
- Ability to restore to full screen mode on the second monitor
- Ability to start in slideshow mode, full screen mode, _playing_ 

My own desired command line option:

- provide on the command line a text file containing a list of file paths to show as the image list [rather than using "last image" or contents of a folder]

**Comment by d2phap** [comment]
This feature is supported in v9.0 beta.

All settings from `igconfig.json` file can be passed to `ImageGlass.exe` as command lines:
```bash
# hide toolbar
# set background color to #aa001122
# set the default selection of Crop tool to 'Select70Percent'
ImageGlass.exe -ShowToolbar=false -BackgroundColor=#aa001122 -Tools:CropTool:InitSelectionType=Select70Percent
```
