### ISSUE TITLE
"scale to height" and "scale to width" buttons should have the effect of subsequent images auto-scaling to the window height / width 

### ISSUE THREAD

**Issue by Kosyne** [d2phap/ImageGlass#67]
Would like an option to set default zoom settings for slideshow/fullscreen. Scaled/unscaled, fit width/height/both, etc.

**Comment by d2phap** [comment]
Hi @Kosyne 

You can do it by Zoom functionalities with "Lock ratio" button option

Phap

**Comment by Kosyne** [comment]
Unfortunately, this does not work as it locks all images to the first images ratio, causing some to be zoomed way in, and some to be tiny.

**Comment by jsnathan** [comment]
+1

The lock ratio button pressed after the "scale to height" or "scale to width" buttons should have the effect of subsequent images auto-scaling to the window height / width while preserving their own ratio.

**Comment by d2phap** [comment]
Implemented this request, for the details: https://github.com/d2phap/ImageGlass/pull/378
For test version, pls go to: http://www.imageglass.org/moon
