### ISSUE TITLE
Add docs: how to Support EPS and Ai Pictures

### ISSUE THREAD

**Issue by xmha97** [d2phap/ImageGlass#670]
Hello, I can't open EPS pictures using ImageGlass.
Please support EPS pictures.

**Comment by fire-eggs** [comment]
1. Install ghostscript ([downloads](https://ghostscript.com/download/gsdnld.html))
2. For convenience, add ".eps" as a supported ImageGlass file type in the settings (settings, "File Type Associations"). Restart ImageGlass.

You should now be able to view EPS files using ImageGlass.

**Comment by fire-eggs** [comment]
ImageGlass Moon 7.0.12.14 viewing[ this ](http://www.vectordoctor.com/originals/test%20file.eps)eps file:

![image](https://user-images.githubusercontent.com/9809727/71564802-8722d000-2a74-11ea-9b78-8da9c596aaed.png)

**Comment by fire-eggs** [comment]
Reopened as a "improve the documentation" task.

**Comment by xmha97** [comment]
@fire-eggs Also Imageglass can open Ai image using ghostscript.

**Comment by d2phap** [comment]
updated docs
