### ISSUE TITLE
Autoatically write image rotation into the file

### ISSUE THREAD

**Issue by jantheodor** [d2phap/ImageGlass#673]
The more one needs to use alternative software, in this case windows explorer or other image viewers, to accomplish such basic tasks, the more likely they are to lose interest in this beautiful piece of software IMHO

**Comment by d2phap** [comment]
Hi @jantheodor 

I guess you are asking for the "auto-save image after rotating"
You can check the option in settings:

![image](https://user-images.githubusercontent.com/3154213/71782092-1ef26200-3011-11ea-9503-66926733c7fc.png)

**Comment by jantheodor** [comment]
Yes, I am. Thanks for the fast reply. Please make it default.

**Comment by d2phap** [comment]
Hi @jantheodor 

The reason it's not checked by default is when rotating the image, ImageGlass will modify it, and of course, any modification leads to changing image data.

To keep the image file safe, it's unchecked since then.

**Comment by FireEmerald** [comment]
@d2phap Was the `Save the viewing image after rotating` feature (checkbox) removed since I couldn't find it anymore in the current version?

**Comment by d2phap** [comment]
@FireEmerald it's removed because ImageGlass does not automatically save the image anymore.

**Comment by sunphoenixcmyk** [comment]
@d2phap I understand that the setting was that it wasn't checked by default (make sense) but you removed the setting completely, why ?
