### ISSUE TITLE
System.FormatException parsing ZoomLevels After Upgrade

### ISSUE THREAD

**Issue by charper3** [d2phap/ImageGlass#677]
### System information:
 - Windows OS version: Windows 10 Home, Version 1903, OS Build 18362.535
 - ImageGlass version: 7.5.1.1

### To Reproduce
1. Install an older version of ImageGlass (prior to 7.5.1.1)
2. Customize ZoomLevels (using commas as the separator).
3. Install Latest Version of ImageGlass.
4. Attempt to restart ImageGlass.

### Actual behavior:
ImageGlass fails to start. In the Event Viewer I see the following error:
Application: ImageGlass.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.FormatException
   at System.Number.StringToNumber(System.String, System.Globalization.NumberStyles, NumberBuffer ByRef, System.Globalization.NumberFormatInfo, Boolean)
   at System.Number.ParseInt32(System.String, System.Globalization.NumberStyles, System.Globalization.NumberFormatInfo)
   at ImageGlass.Base.Helpers.StringToIntArray(System.String, Boolean, Boolean)
   at ImageGlass.Settings.Configs.Load()
   at ImageGlass.Program.Main()

### Expected behavior:
ImageGlass starts with no errors.

### Additional context:
I believe commit 07a1493b8059a16c38d4977c0aebd9ca8ae2bf8b ("improved ToolbarButtons, changed some default configs values" by d2phap) caused this issue, specifically the change to line 107 of Helpers.cs to alter the delimiter from comma to semicolon. Assuming only people that have customized their ZoomLevel in the past would experience this issue. I hand edited the XML file (%AppData%\Roaming\ImageGlass\igconfig.xml) to change the delimiter to a semi-colon and the application started normally following that change.

**Comment by d2phap** [comment]
Hi @charper3 

Yea because of the new setting engine. The previous settings were not consistent in using separator. to separate the items in igconfig.xml. file.

Unfortunately, I could not make ImageGlass backward-compatible with, or auto-upgrade the previous settings. There should be a warning message box, to tell user that the some of the settings need to be manually updated.

I also mentioned in the change log of v7.5: https://github.com/d2phap/ImageGlass/releases/tag/7.5.1.1

The upgrade guide for settings:
https://imageglass.org/docs/app-configs#upgrade-guide

**Comment by fladouceur** [comment]
> Hi @charper3
> 
> Yea because of the new setting engine. The previous settings were not consistent in using separator. to separate the items in igconfig.xml. file.
> 
> Unfortunately, I could not make ImageGlass backward-compatible with, or auto-upgrade the previous settings. There should be a warning message box, to tell user that the some of the settings need to be manually updated.
> 
> I also mentioned in the change log of v7.5: https://github.com/d2phap/ImageGlass/releases/tag/7.5.1.1
> 
> The upgrade guide for settings:
> https://imageglass.org/docs/app-configs#upgrade-guide

Thanks for these instructions, it allowed me to go around the issue pretty quickly.
FYI: I never saw that dialog box mentioning that I have to update some files manually so had no idea whatsoever what to do (tried uninstall/reinstall x64 and x86, etc.).

**Comment by d2phap** [comment]
Fixed this bug in the latest build of ImageGlass Moon
https://imageglass.org/moon
