### ISSUE TITLE
Manual resize the thumbnail panel

### ISSUE THREAD

**Issue by ipthom** [d2phap/ImageGlass#678]
I'd love the possibility not only to resize the thumbnail-pane but to save the new size permanently.

**Comment by fire-eggs** [comment]
This is a reversion of previous functionality. We save the thumbnail pane size (see the `ThumbnailBarWidth` setting in igconfig.xml) but for some reason we are not applying in on startup.

**Comment by TheApX** [comment]
Should this issue be marked as fixed? https://github.com/d2phap/ImageGlass/commit/dc940dffc5a18262e914428102e525d13d509f45 has been merged to the "develop" branch.

**Comment by fire-eggs** [comment]
Thanks for asking! The "bug" part has not been addressed - when the thumb bar is at the bottom, it cannot be resized [and the size isn't remembered].

**Comment by TheApX** [comment]
Oh, right. Sorry I got a bit confused.

BTW, as a feature it would be great if size of the pane and size of thumbnails were tied to each other. The only real point of adjusting size of the pane now is to make it fit the thumbnails. It would be much more convenient if resizing the pane also resized thumbnails, so they always fill the pane. Thumbnail size in setting will not be needed anymore, but it requires arbitrary thumbnail sizes to be supported.

**Comment by fire-eggs** [comment]
>Oh, right. Sorry I got a bit confused.

Not a problem! The OP was unclear if they cared about horizontal thumbbar or not. As a maintainer, I _do_ care.

>BTW, as a feature it would be great if size of the pane and size of thumbnails were tied to each other.

Agreed! I think it also might be a solution for issue #525 .

**Comment by d2phap** [comment]
IG 9 supports resizing Gallery panel in vertical layout
