### ISSUE TITLE
'Page Navigation' for GIF feedback

### ISSUE THREAD

**Issue by Unknow0059** [d2phap/ImageGlass#680]
### Is your feature request related to a problem?
Only two points are related to a problem.
***************************
I'm frustrated that:
- **1** - I must use the context menu to Start and Stop an animated image (gif). There should be a dedicated button on the Page Navigation window for this.
- **2** - When I click 'View Previous/Next page', the animation starts playing on its own. This trivializes the Page Navigation feature. It shouldn't do this.
- **3** - I cannot navigate _only_ through different frames. If I have a four-unique-frames animation that has 60 frames for visibility/timing purposes, I'll have to navigate through 15 unchanging frames before I get to a different one. I wish I were able to navigate through unique frames only.
- **4** - The '**^**' button seemingly does nothing in the Page Navigation menu. If it does nothing, it should be removed.

### Additional context
I'm glad the Multipage/Page navigation feature was added. Before this, I had to open an image editor to view gifs frame-by-frame.

By the way, this is unrelated, but the Issues section of ImageGlass on GitHub is very organized. This is great. Most 'Issues' don't come close to being this organized.

**Comment by fire-eggs** [comment]
See also issue #629

**Comment by d2phap** [comment]
Hi @Unknow0059 

There was a problem in the last minute that made the page navigation was very unstable, so that I had to remove the support for GIF.
I will add it back in the future.
Thanks for your ticket.

**Comment by justanotheranonymoususer** [comment]
I hope that it will be implemented soon, that's the feature that is missing the most for me in ImageGlass

**Comment by d2phap** [comment]
Added support for GIF, shipped in IG Moon: https://imageglass.org/moon
