### ISSUE TITLE
Faster Preview

### ISSUE THREAD

**Issue by xmha97** [d2phap/ImageGlass#682]
Please add below feature:
- Display thumbnail instead original photo until the photo is loaded.
![Image Preview](https://user-images.githubusercontent.com/23485114/72209053-bba87a00-34bf-11ea-906b-b07b50183d5a.png)
cc: #495

**Comment by d2phap** [comment]
This feature is supported in [ImageGlass Moon 9.0 beta 3](https://github.com/d2phap/ImageGlass/releases/tag/9.0.3.1225).

You can enable it with setting: `ShowImagePreview`
