### ISSUE TITLE
Add OpenWith feature

### ISSUE THREAD

**Issue by xmha97** [d2phap/ImageGlass#684]
I have to change edit app for Open with feature.
![ImageGlass](https://user-images.githubusercontent.com/23485114/72522009-e1dc6a00-3871-11ea-9901-5f081d519a72.png)
![ImageGlass](https://user-images.githubusercontent.com/23485114/72522084-0cc6be00-3872-11ea-9c24-d997a42cb552.png)
![image](https://user-images.githubusercontent.com/23485114/72522160-3ed82000-3872-11ea-8b4f-d10a2fd58a73.png)

**Comment by d2phap** [comment]
Ready in https://imageglass.org/moon

**Comment by xmha97** [comment]
![image](https://user-images.githubusercontent.com/23485114/75182752-45ea2c00-5756-11ea-839e-96aaecb8faa4.png)
Ok, Thank you very much <3
