### ISSUE TITLE
Embedded Adobe RGB profile not recognised

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#685]
From Google Group.
>I have all my JPEGs in Adrobe RGB color profile and this program does not display colors correctly

See attached image. You can see the "desired" colors when using "Windows Photo Viewer" [but not Paint, Photos, or a browser].

From what I've been able to determine, an image may be marked with a color profile, but not via an ICC Color Profile. Instead, they use an exif metadata tag called the "Interoperability Index" (aka "InteropIndex"). In the case of this user, the "InteropIndex" is set to "Adobe RGB".

ImageMagick / Magick.NET do not recognize this exif tag, and provide the image to us with the sRGB color space.

The following line of code will get us the value of the "InteropIndex":
```
var test = imgM.GetAttribute("exif:thumbnail:InteroperabilityIndex");
```
where `imgM` is our `MagickImage` object.

The known values of the InteropIndex are:
- R03 : AdobeRGB
- R98 : sRGB

Suggested approach:
1. Add code to look for this exif tag, and verify the image is in the "desired" color space. If not, we should convert the image color space.
2. Submit an issue to Magick.NET requesting they use the "desired" color space in this situation.

![_A730823](https://user-images.githubusercontent.com/9809727/72555428-89559e80-386a-11ea-9b15-53fc5252a3ec.JPG)

**Comment by d2phap** [comment]
This was fixed some time ago
