### ISSUE TITLE
New version hint is shown even tough latest version is installed

### ISSUE THREAD

**Issue by andreasgottardi** [d2phap/ImageGlass#688]
### System information:
 - Windows OS version: 10, 1909, x64
 - ImageGlass version: 7.5.1.1

### To Reproduce
1. Open Menu
2. Select "Help"

### Actual behavior:
It says "A new version is available!".

### Expected behavior:
Hint should not be shown because latest version is already installed.

### Screenshots:
![image](https://user-images.githubusercontent.com/922195/72777561-646c7d00-3c16-11ea-935e-c0c6001008c2.png)

### Additional context:
A very minor bug, but maybe easy to solve. Thanks for the great application! You are doing great work.

**Comment by d2phap** [comment]
Fixed this bug in the latest build of ImageGlass Moon
https://imageglass.org/moon

**Comment by andreasgottardi** [comment]
Cool, thanks. Great application btw. 😃 Really appreciate your work.
