### ISSUE TITLE
%APPDATA%\ImageGlass missing, no settings stored

### ISSUE THREAD

**Issue by daooze** [d2phap/ImageGlass#689]
### System info:
- ImageGlass version: 7.5.1.1
- OS version: Windows 10 v1903 x64

Users settings folder (%APPDATA%\ImageGlass) is not automatically created when the "new user setup dialog" is suppressed.

For my users I make use of the possibility to create a default configuration of ImageGlass via the file igconfig.default.xml in the installation folder of IG. This file contains all settings (except a few) which IG stored in my personal igconfig.xml upon first run. This suppresses the initial startup dialog where users can configure language settings, themes etc. That´s absolutely fine and expected behaviour as I do not want my users to click through this dialog upon first run.
However, if a user changes a configuration setting, it is expected to be written to %APPDATA%\ImageGlass\igconfig.xml, but as the folder does not exist by default, no settings are stored. Manually creating the folder resolves this issue but this is difficult to handle, even in a managed environment.

I´d like ImageGlass to check if the folder %APPDATA%\ImageGlass exists every time the settings file is to be written and re-create the folder if it is not there.

**Comment by d2phap** [comment]
Hi @daooze 
This is a bug. I have checked and confirmed that if the `%APPDATA%\ImageGlass` does not exist, ImageGlass won't write any configs

**Comment by eamonn0** [comment]
@daooze 
@d2phap 
The settings are stored properly at %AppData%\Roaming\ImageGlass.

**Comment by d2phap** [comment]
Fixed and ready in ImageGlass Moon https://imageglass.org/moon

**Comment by Catfriend1** [comment]
Hi, i've still had this bug in 7.5.x and now upgraded to 8.x  recent release where it also exists. I'm enrolling to c:/program files/imageglass which is then write protected from the user perspective . If a  user first logs on and his profile is created, the appdata\imageglass folder is missing . so changing and persisting settings for the user is impossible.

**Comment by Catfriend1** [comment]
Thanks for caring @d2phap 
I'm currently working around the issue by pre-creating the folder on user profile creation.
Our AD logon script contains

> MD "%AppData%\ImageGlass" 2>NUL:

**Comment by d2phap** [comment]
Fixed this bug in IG Moon: https://imageglass.org/moon

**Comment by Catfriend1** [comment]
Thanks :-)
