### ISSUE TITLE
Background color of the toolbar and thumbnail bar displayed incorrect

### ISSUE THREAD

**Issue by WilliamZY** [d2phap/ImageGlass#690]
### System information:
 - Windows OS version: Windows 10 1909 18363.592
 - ImageGlass version: 7.5.1.1

### To Reproduce
1. Change "background Color" to any other color other than default in the setting
2. Apply the change
3. The background color of the toolbar and thumbnail bar have not been changed 

### Actual behavior:
The backgrpound color of the toolbar and thumbnail bar have not been changed according to the background color in the setting

### Expected behavior:
The backgrpound color of the toolbar and thumbnail bar should be in the same color as the setting

### Screenshots:
![image](https://user-images.githubusercontent.com/12370751/73247687-6a50f800-41ec-11ea-9db6-4439ed9c21b8.png)

**Comment by d2phap** [comment]
Hi @WilliamZY 

The background color is designed as separated color from toolbar and thumbnail bar.
Currently there is no option to change its color in Settings dialog. However, you can do it in the `config.xml` of theme package


Click on Open theme folder, go to the current theme, and open the `config.xml` file
![image](https://user-images.githubusercontent.com/3154213/74095569-da854500-4b2d-11ea-805f-1f4b27b9d41b.png)

These 2 values define the color of toolbar and thumbnail bar
```xml
topbarcolor="#EAEAF2" bottombarcolor="#EAEAF2"
```

**Comment by fire-eggs** [comment]
Re-open as a documentation improvement task.

**Comment by d2phap** [comment]
For theme pack details, you can find it here: https://github.com/ImageGlass/theme
