### ISSUE TITLE
Shortcut in Startmenu / Disable Desktop Icon on Installation

### ISSUE THREAD

**Issue by Flashbert** [d2phap/ImageGlass#691]
Hello,

i have to enhancement ideas.

1. Make the desktop icon optional on install, for now i deleted the icon from C:\Users\Public\Desktop after the installation.

this leads to the second idea:

2. Create the icon in C:\ProgramData\Microsoft\Windows\Start Menu\Programs (at least on Windows 10)

After i deleted the desktop icon i can't find Imageglass over the startmenu anymore, but i dont want the user to fill up his desktop with programs you normally start over the files, not the program itself.

**Comment by xmha97** [comment]
+1

**Comment by xmha97** [comment]
@d2phap I think this problem is a priority and should be fixed as soon as possible.

**Comment by theonemcdonald** [comment]
#835 

Give this a test. If this works I can modify the 32bit installer too.

**Comment by d2phap** [comment]
Thanks @theonemcdonald 😎
I will check!

**Comment by xmha97** [comment]
The ImageGlass app shortcut is currently in the app installation path!
![File Explorer](https://user-images.githubusercontent.com/23485114/89462095-2c77f200-d782-11ea-8a7d-c3c7a772933e.png)
