### ISSUE TITLE
Automatically Use Windows Color Profile

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#693]
From Google+:

> Actually, I thought the color management in ImageGlass was borken, but it works and here's how: In the settings, image, and color management section, go to the select and choose "custom" (not sRGBB unless you've calibrated your monitor to be exactly sRGB) then browse for your custom monitor profile. In Windows 10, it's in Window/system32/spool/drivers/color. Restart ImageGlass, then it should properly convert from the image profile to your display. It should really do that automatically like other apps.

**Comment by NothingWeAre** [comment]
As an additional request it would be good if ImageGlass can automatically switch to correct profile when moving from monitor to monitor(in a multimonitor setup).

**Comment by nwgat** [comment]
i just got a color calibratior and would love this, i also have multi-monitor setup and imageglass seem to have issues when you have a multi-display setup as it wont change the color profile, its just stuck to whatever is default, on my non-multi-monitor laptop it works fine

**Comment by nwgat** [comment]
left windows, right imageglass, nef file
![image](https://user-images.githubusercontent.com/5809156/76232116-8651ab80-6226-11ea-84ad-f87ab3873b07.png)

**Comment by nwgat** [comment]
kinda looks like a raw issue as this is how it looks on a jpeg
![image](https://user-images.githubusercontent.com/5809156/76232921-b0f03400-6227-11ea-9c56-3dc9642e7bb2.png)

**Comment by PaulCoddington** [comment]
This would make using ImageGlass a lot more practical.

With professional photographic and video monitors the Windows Color Profile gets changed automatically by the monitor on the fly when switching modes to different color spaces, each with their own variations of brightness, gamma and color primaries (BT.709, BT.2020 and DCI for watching/editing video or prepping photos for slide shows on UHD TV sets; Abode RGB for preparing photographs for prints; sRGB for office work, software development, and creating web content).

It is a bit inconvenient to have to remember to change the settings in ImageGlass back and forth manually, and mistakes often end up being made.

UPDATE: 

This is not just an issue with changing monitor modes, but calibration software embeds the date of the calibration in the ICC profile file name. So every time a calibration is run, the path to the current ICC profile changes and ImageGlass reverts back to "none". Even more tedious, the browse button does not open in the Spool-Devices-Color folder, so it takes a bit more unnecessary effort to navigate there.

**Comment by d2phap** [comment]
IG 8.6 added support for user current monitor profile (#781) in Settings > Image > Color management:

![image](https://user-images.githubusercontent.com/3154213/171987767-ad7511e1-4227-467a-98bd-34b15a450c16.png)
