### ISSUE TITLE
"scale to fit" sometimes works incorrectly with large picture

### ISSUE THREAD

**Issue by TheCGDF** [d2phap/ImageGlass#700]
### System information:
 - Windows OS version: 10.0.17763.973
 - ImageGlass version: 7.5.1.1
 - Resolution: 3840x2160
 - DPI: 225%

### To Reproduce
1. open imageglass, set "scale to fit" 
2. close imageglass
3. open this picture with imageglass:
![trappist1f_spitzer_4534](https://user-images.githubusercontent.com/17256673/74595757-cf2f9d80-5088-11ea-9f7a-b197cd83c326.jpg)
this picture's dimensions:4534x2550

### Actual behavior:
not fit.
![ImageGlass_FZImld5N2D](https://user-images.githubusercontent.com/17256673/74595796-4d8c3f80-5089-11ea-9885-7775eae03e7e.jpg)

### Expected behavior:
refresh(F5), it will display correctly.
![ImageGlass_Gmc4MTRgs3](https://user-images.githubusercontent.com/17256673/74595818-9217db00-5089-11ea-90cb-1269427bdb35.jpg)

### Additional context:
it seems to only happen to large pictures.

**Comment by d2phap** [comment]
Thanks @TheCGDF 

It works fine in my 1920x1280 screen.
I will keep this open when I have chance to test on bigger resolution.

**Comment by fire-eggs** [comment]
I have tried to repro this in a virtual machine environment, with no luck. It will have to be tested on a real screen.

**Comment by TheCGDF** [comment]
i found the reason.
please check in "Display viewer scrollbars".
![ImageGlass_HqMkC7ZGqK](https://user-images.githubusercontent.com/17256673/76153004-709a9400-6109-11ea-8971-03aa382803a2.jpg)

**Comment by fire-eggs** [comment]
Ah! Thank you! I do believe that will make a difference and even clues me in to what is likely to be the problem!

**Comment by TheCGDF** [comment]
@fire-eggs Any updates?

**Comment by d2phap** [comment]
@TheCGDF can you try [ImageGlass 9.0 beta 2](https://github.com/d2phap/ImageGlass/releases/tag/9.0.2.904)

**Comment by TheCGDF** [comment]
> Display viewer scrollbars

How to enable `Display viewer scrollbars` in 9.0 beta2?

**Comment by d2phap** [comment]
"Display viewer scrollbars" is one of [the removed features in v9](https://imageglass.org/news/introducing-the-new-imageglass-version-9-88#upgrading-to-version-9).
