### ISSUE TITLE
Opening image in Google Drive FS folder

### ISSUE THREAD

**Issue by PerezChilli** [d2phap/ImageGlass#701]
### System information:
 - Windows OS version: 10 x64 1909
 - ImageGlass version: 7.5.1.1

### To Reproduce
1. Install Google Drive File Stream and sign in into your account
2. Copy or find an image in Google Drive FS folder (G:\*\file.jpg)
3. Open image in ImageGlass

### Actual behavior:

1. Image blinks and not opening
2. Google Drive File Stream shows an error with file system

### Expected behavior:

1. Image opens well as in other local paths

### Screenshots:

![17-02-2020_16-10-04_IBWhsUPHZN](https://user-images.githubusercontent.com/39314909/74656865-13fa2800-51a0-11ea-9983-5b7b6e60fd3d.png)

**Comment by fire-eggs** [comment]
Note: requires a G Suite account and access to Google Drive File Stream.

Can any images in your Google Drive File Stream be opened with other programs? E.g paint, Microsoft Photos?

**Comment by PerezChilli** [comment]
> Note: requires a G Suite account and access to Google Drive File Stream.
> 
> Can any images in your Google Drive File Stream be opened with other programs? E.g paint, Microsoft Photos?

Yes. ImageGlass is the one application which can't open images in Google Drive FS folder correctly.

**Comment by d2phap** [comment]
Just realized the notification says that the antivirus software blocks the Google Drive `content_cache` folder, you need to allow this folder in your antivirus software.

```
Ошибка синхронизации

Добавьте диск G: и путь
C:\Users\usercmg\AppData\Local\Google\DriveFS\
dmxhZGlzbGF2LnBpc2FyZXZAY29udmVyZ2VudC11
c2EuY29t\content_cache в исключения для
антивирусного ПО.
```
