### ISSUE TITLE
NextPic is not thread-safe, but uses async/await

### ISSUE THREAD

**Issue by TheApX** [d2phap/ImageGlass#703]
While working on https://github.com/d2phap/ImageGlass/pull/702 I found a race condition in the `frmMain.NextPic` method.

`frmMain.NextPic` is not thread-safe, but it uses async/await. It modifies many variables in the Local struct without any any synchronization.

One common case of race condition is saving modified image. It modifies current image file, which triggers the file watcher, which calls `NextPic` in parallel. I've introduced a hack in https://github.com/d2phap/ImageGlass/pull/702 to overcome this scenario by stopping the file watcher right before saving the image, and restarting it right after. This is not a correct solution, as it:
* Ignores real changes to other files while saving.
* Doesn't prevent from other possible cases when `NextPic` is called in parallel.

A major refactoring is required to fix this problem correctly.

**Comment by d2phap** [comment]
Fixed this in v9.0 beta
