### ISSUE TITLE
Artists Request: Slideshow Timer improvements

### ISSUE THREAD

**Issue by nathan-rogers** [d2phap/ImageGlass#704]
### Is your feature request related to a problem? Please describe.
As an artist, I need an image viewing program that will cycle through a folder of images on a timer, that allows me to easily and readily change the timer, and also select a range for random timers. Image Glass is the only software I have discovered thus far that allows me to change the slideshow timer easily, but it could be improved, allowing the user to set specific times, and also select a random timer range. 

### Describe the solution you'd like
I would like to modify the existing slideshow timer to have 2 additional features. 

1. Add a numerical text field in the GUI (in addition to the slider) into which the user may enter the specific number of seconds for the slideshow timer. 
    - This text field should display the correct number of seconds selected by the slider if the slider is used instead. 
    - This text field will double as the lower bound for the following feature. 
2. Add a checkbox that enables a second numerical text field into which the user may enter the upper bound of the slideshow timer, and the slideshow will now rotate through images for a random number of seconds between the lower and upper bounds. 

### Describe alternatives you've considered
I cannot achieve either of these features in other image viewing programs, and gesture drawing software (typically phone apps, thus negatively affecting the physical image size) do not allow entering specific times or randomized times as I would like. 

### Additional context
Gesture drawing is typically done in a live studio session with models. Gesture drawing is done by setting a time limit for a pose, and having the model repose ever few seconds. Typically the time windows selected are 30-60-120, etc. to force the artists to capture motion and energy more quickly, and with greater fluidity, often as preparation for a long 30 minute to 1 hour pose or simply as its own standalone study. It is often great practice to have the model change pose randomly between 5-30 seconds so that the artists must practice capturing more information. To be able to quickly change between these timers, and also allow for a random timer, I have made this feature request.

**Comment by d2phap** [comment]
Thanks @nathan-rogers 

To sum up, you need to randomize the interval of slideshow in the range of X to Y seconds

**Comment by d2phap** [comment]
Implemented in the latest build of ImageGlass Moon: https://imageglass.org/moon
