### ISSUE TITLE
Fully integrated with Windows 10 Timeline

### ISSUE THREAD

**Issue by hohoaisan** [d2phap/ImageGlass#705]
While opening any image file, Windows 10 automatically places it into Timeline, with ImageGlass as the default image viewer,
![image](https://user-images.githubusercontent.com/26185060/75085317-9dbc4380-555a-11ea-8835-3643846f58cd.png)
It might be useful for most users found Timeline is such a productive feature. But when I clicked on these items. A popup with an error appears:
![image](https://user-images.githubusercontent.com/26185060/75085342-d3612c80-555a-11ea-98d7-8546a67202b0.png)
It shows that ImageGlass was not well integrated with this.

I hope you can take a look at this. This feature is not as important as others. I don't mind waiting for it to be released.

**Comment by d2phap** [comment]
Hi @hohoaisan 
Can I check with you if you can double-click on the PNG file to open it?

- You can try register ImageGlass for image extensions again in `Settings` > `File Type extensions`, click on `Set as default Photo viewer` button
  ![image](https://user-images.githubusercontent.com/3154213/75086435-1d540d80-556f-11ea-8307-d77636d0ae9d.png)

- Then go to Default apps setting in Windows 10, select ImageGlass as default Photo viewer
![image](https://user-images.githubusercontent.com/3154213/75086402-b2a2d200-556e-11ea-94a5-9676f6f85721.png)

Let me know if this helps.
Thanks!

**Comment by hohoaisan** [comment]
I had set IG as a default image viewer before and did all of your instructions above. Opening an image works fine for regular tasks. But as I mentioned above, opening it via Windows Timeline is not possible. I think the reason is IG was not fully supported for this feature.

**Comment by Arudinne** [comment]
Hello,

Using Process Monitor I found that Task view was looking under HKCR for ImageGlass.exe but could not locate it.

I found that adding this registry entry seems to fix the issue.

`Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\Applications\ImageGlass.exe\shell\open\command]
@="\"C:\\Program Files\\ImageGlass\\ImageGlass.exe\" \"%1\""
`

**Comment by hohoaisan** [comment]
@Arudinne thanks but your solution doesn't work for me. How could you do that?

**Comment by Arudinne** [comment]
> @Arudinne thanks but your solution doesn't work for me. How could you do that?

I'm not sure I understand your question? I just added the above entry to RegEdit by hand and then exported it as a .REG file

![image](https://user-images.githubusercontent.com/29390020/75715482-15911900-5c93-11ea-8a5f-60bb872b8881.png)

**Comment by fire-eggs** [comment]
Microsoft is dropping Timeline for Windows 11. Recommend closing this as "Won't fix".
