### ISSUE TITLE
IG Restores to "wrong" screen after save when Maximized

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#706]
Originally mentioned on Google group.

### System information:
 - Windows OS version: Windows 7; Windows 10
 - ImageGlass version: 7.1

### To Reproduce
1. Run IG. Maximize it on another screen, not the "primary" screen.
2. Exit IG.
3. Run IG. 

### Actual behavior:
IG will appear on the "primary" screen.

### Expected behavior:
IG should appear on the other, non-primary screen.

### Screenshots:
N/A

### Additional context:
Workaround: Edit igconfig.xml after step 2 above. Change the value of
"FrmMainWindowState" from "Maximized" to "Normal".

IG will then appear on the desired monitor at step 3 above.

**Comment by fire-eggs** [comment]
The upshot of this appears to be that we _cannot_ restore to a maximized state. Despite multiple posts providing various solutions, IG refuses to restore to the desired monitor when the WindowState is set to Maximized.

We can save the IG position and restore it so that IG _appears_ in the desired monitor and size, but _not_ in an actual maximized state.

**Comment by fire-eggs** [comment]
Fixed, plus solution for when IG attempts to restore to a monitor which has been removed.

**Comment by d2phap** [comment]
Reverted the commit https://github.com/d2phap/ImageGlass/commit/180a874cd9adb63a859d5835d66792cc9fae3b16

It causes another bug: ImageGlass does not restore the correct state and size of window in Maximized mode. I will think of another solution.

**Comment by neilalphazeta** [comment]
I'm also affected by this issue. Greatly looking to the update.

**Comment by d2phap** [comment]
This bug is fixed in the latest build of IG Moon:
https://imageglass.org/moon
