### ISSUE TITLE
Display/zoom enhancement (filters ?)

### ISSUE THREAD

**Issue by Isiolith** [d2phap/ImageGlass#71]
In a future release, would you consider adding filter options for example to smooth pixels while zooming ?
I'm not sure this is the right tool, but for example, a zoomed picture in Firefox is smooth, and a zoomed picture in ImageGlass is not smooth : pixels are visible.

There could be an option to choose what kind of filter is used in certain situations, and an option to disable it (I am sure current behaviour please to some people).

PS : sorry for my bad english :)

**Comment by eckso** [comment]
I second this (interpolation filters)
For cheap yet good quality catmull-rom, if something better, spline 3 taps or lanczos. I'm on the opinion that point upsampling is not for viewing purposes (only analysis tools), but make it optional.

**Comment by d2phap** [comment]
Hi @Isiolith @eckso 

This feature was already added, but its configuration has been removed since v3.0 because I didn't receiving any feedback for it and though that it's not necessary.
I will enable the configs for next version.

Thanks

**Comment by Isiolith** [comment]
Hi, thanks for answering, great news :) :+1:

**Comment by d2phap** [comment]
Done

**Comment by eckso** [comment]
Is this option in latest dev build?

**Comment by d2phap** [comment]
@eckso It's called Zoom Optimization in Settings > Image tab
