### ISSUE TITLE
Navigation arrows are invisible with black background

### ISSUE THREAD

**Issue by retrue** [d2phap/ImageGlass#711]
### System information:
 - Windows OS version: Windows 10
 - ImageGlass version: 7.5.1.1

### To Reproduce
1.  Open maximized an image that is not so wide as the monitor, for example, a 1440*1080 image on a 1920*1080 monitor. If the background is white, you will see as the cursor arrow turns into a black navigation arrow when you move the cursor to one side of the screen.
2.  In options, choose black background.

### Actual behavior:
With black backgrounds, when you move the cursor to the border, the cursor arrow will disappear and the black navigation arrow won't be visible.

### Expected behavior:
The navigation arrow should change its colour, from black to white when the background is set to black (or some very dark colour).

### Additional context:
A possible solution, instead of making the navigation arrow change its colour, could be to use a navigation arrow made of a double line white and black that would be visible with any background. Example in the image below.
![arrow](https://user-images.githubusercontent.com/18194241/75717813-290fa480-5cd2-11ea-96f1-6145016db8d1.png)

**Comment by d2phap** [comment]
Hi @retrue 

The navigation arrow buttons just got improved in the latest build of ImageGlass Moon:
Try it at: https://imageglass.org/moon

![image](https://user-images.githubusercontent.com/3154213/78454971-3bfd0680-76ce-11ea-8c2a-30d89ea58f75.png)

**Comment by retrue** [comment]
Thanks =)
It looks prettier than the double line thing I suggested.
