### ISSUE TITLE
On image load failure, right-click menu is too limited

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#713]
### System information:
 - Windows OS version:  Win7
 - ImageGlass version: V7.5

### To Reproduce
1. Open a valid image. Right-click to view menu contents. Note there are 18 items.
2. Open an invalid image (e.g. right now, the file from issue #708)
3. Right-click to view menu contents. Note there are 3 items

### Expected behavior:
Yes, the image load failed, but the file exists. So I expect at least to be able to:
- Edit image
- Rename image
- Move to recycle bin
- Copy image path
- Open image location
- Image properties

**Comment by d2phap** [comment]
Done
