### ISSUE TITLE
48 Bit-per-pixel TIFF images are too slow

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#714]
From Google Group:

> Unfortunately, the viewer for large TIFF images is far too slow.
> 
> Test Image: https://we.tl/t-HAe686DzRL
> 
> Just open the image with Windows Photo and zoom in and out, move the image to zoom in.
> Then try imageglass.
> 
> Sorry, but have ImageGlass uninstalled again.
> 

Note: the image from this report is 264M in size, too large to be attached.

**Comment by fire-eggs** [comment]
Possible duplicate of #272

**Comment by fire-eggs** [comment]
A second report in Google Groups. See the attached image.

On my system, the load time for this image in IG 7.5 is 28 seconds.

When loaded in IG 7.0, it takes 7 seconds!!!

ImageMagick / Magick.NET appears to have degraded TIF support recently.

[050-5001-B_Twiggy_Analog_New.zip](https://github.com/d2phap/ImageGlass/files/4351788/050-5001-B_Twiggy_Analog_New.zip)

**Comment by fire-eggs** [comment]
The reported image is 5486 by 8229 pixels, 48 bits per pixel.  When panning while zoomed, the image moves very "chunkily". This is true for both IG 7.0 and IG 7.5.

Converting the original image to 24-bit TIF does not show the same behavior. Panning while zoomed is "slow" (as per issue #272) but noticeably faster than the 48 bpp version.

We need to investigate how we are handling images greater than 24 bpp.

**Comment by d2phap** [comment]
Should be not an issue with IG v9
