### ISSUE TITLE
Show thumbnail panel only in full-screen mode

### ISSUE THREAD

**Issue by xmha97** [d2phap/ImageGlass#717]
Hello,
Please add below feature:
- Show thumbnail panel only in full-screen mode

![ImageGlass](https://user-images.githubusercontent.com/23485114/76138386-a59cdd00-605c-11ea-8921-47f8edb99660.gif)

**Comment by Rereyuop** [comment]
Looks great！

**Comment by d2phap** [comment]
I will not implement this, just simply press `G` (v9) or `H` (v8)
