### ISSUE TITLE
Need an option, prevent screen close.

### ISSUE THREAD

**Issue by d4rkk4** [d2phap/ImageGlass#718]
### System information:
 - Windows OS version: 10
 - ImageGlass version: 75.1.1

For some reason slideshow mode is not blocking my screen from getting closed.

**Comment by fire-eggs** [comment]
>not blocking my screen from getting closed

Sorry to be dense, but could you clarify what you mean here? Are you referring to the screen saver or lock screen activating? (or in the case of a laptop, going to sleep)?

**Comment by maneesh29s** [comment]
I am facing the same issue. Whenever I open an image in the ImageGlass, the app restricts me to change my active window. It doesn't let me open other windows. This happens whenever :
1) I use Alt+Tab shortcut to change my window
2) I click on the another window on the Windows Taskbar.
The app minimizes only when I use "minimize" button at the top of the app.

**Comment by fire-eggs** [comment]
> Whenever I open an image in the ImageGlass, the app restricts me to change my active window.

Can you confirm that you do not have "Keep window always on top" checked?
![image](https://user-images.githubusercontent.com/9809727/77237022-b3914880-6b9a-11ea-9b22-c1da05839e33.png)

If checked, IG will always stay in front, and only minimizes via the minimize button.

**Comment by d4rkk4** [comment]
When playing slideshow, after a certain time screen is going black. It is about power options. But it should prevent screen from going black.

**Comment by fire-eggs** [comment]
Thank you for the additional details!

**Comment by d2phap** [comment]
Some resources: 
- https://gist.github.com/brianhassel/e918c7b9f1a6265ff8f9
- https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-setthreadexecutionstate?redirectedfrom=MSDN

**Comment by maneesh29s** [comment]
> I am facing the same issue. Whenever I open an image in the ImageGlass, the app restricts me to change my active window. It doesn't let me open other windows. This happens whenever :
> 
> 1. I use Alt+Tab shortcut to change my window
> 2. I click on the another window on the Windows Taskbar.
>    The app minimizes only when I use "minimize" button at the top of the app.
> 
> Application Version: 7.5.1.1
> Windows 10


My issue was resolved. 
Thanks.

**Comment by d2phap** [comment]
This feature request is ready in ImageGlass Moon https://imageglass.org/moon
