### ISSUE TITLE
MacOS Version

### ISSUE THREAD

**Issue by cukabeka** [d2phap/ImageGlass#719]
Hi,

I look for an alternative to picasa and found ImageGlass which looks promising! Thanks folks!

Is there a chance you will compile something for MacOS one day? I saw that there seems to be a chance to have this happen if this is a .NET app, so maybe via https://www.mono-project.com/ ? 
And I found https://github.com/d2phap/ImageGlass/issues/439 which looks as if there was already some thought in this direction? 

Regards!

**Comment by d2phap** [comment]
hi @cukabeka 
It's too big to port the current project to other framework/platform. I am still looking for some possible solutions, but no plan for the near future yet.
