### ISSUE TITLE
Suggestion: a way of browsing only with mouse

### ISSUE THREAD

**Issue by HanatakeYurii** [d2phap/ImageGlass#72]
Hi,

I would suggest to make a way of browsing only with mouse.
I my mind that could be:

Using the mouse wheel to go "forward / backward" in files (as used by zoom).
Then using the mouse wheel click to switch between the browsing ans the zooming mode.
That way it could be easy and fast.

**Comment by eckso** [comment]
This is similar to #44 that I opened a while back, but the only change described was to enable a live area (far left, far right) where when clicked it would go to previous/next image. Also double click over image would close program.

**Comment by jsieler** [comment]
Looking for that feature too. This was good implemented in "irfanView". If you could add a settings check how to handle mouseScroll, that would be really nice!

**Comment by aimilin6688** [comment]
Looking for that feature too.

**Comment by d2phap** [comment]
I will implement it :+1:

**Comment by HanatakeYurii** [comment]
Thanks :)

**Comment by d2phap** [comment]
done!

**Comment by HanatakeYurii** [comment]
Thanks again +1

**Comment by d2phap** [comment]
Yeah. Will release the next version soon
