### ISSUE TITLE
Loading TIF File now 4x slower in IG7.5 vs IG7.0

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#720]
A new report from Google groups. See attached file.

Testing on my system, IG 7.0 took 7 seconds to load it.

IG 7.5 took 28 seconds!!!

Something has gone badly wrong in TIF support between Magick.NET 7.14.0.3 and 7.15.0.0 !!!

[050-5001-B_Twiggy_Analog_New.zip](https://github.com/d2phap/ImageGlass/files/4351804/050-5001-B_Twiggy_Analog_New.zip)

**Comment by d2phap** [comment]
Reported at https://github.com/dlemstra/Magick.NET/issues/594

There are 2 functions:
`MagickImageCollection()`, and `GetColorProfile()

**Comment by d2phap** [comment]
The TIF slow loading time is fixed in Magick.NET 7.15.5.0, but the `AddProfile()` function is not.

**Comment by d2phap** [comment]
Fixed the TIF performance, upgraded to Magick.NET 7.15.5.0 in the latest build of ImageGlass Moon: https://imageglass.org/moon

**Comment by d2phap** [comment]
Fixed the `AddProfile()` function and shipped in ImageGlass Moon: https://imageglass.org/moon
