### ISSUE TITLE
Navigation arrows require multiple clicks to quickly change images

### ISSUE THREAD

**Issue by squaven** [d2phap/ImageGlass#723]
### System info:
- ImageGlass version: 7.5.1.1
- OS version: Microsoft Windows 10 Version 1903

### Expected behavior:
A single click of the navigation buttons should advance to the next image for every click, matching the functionality of Toolbar buttons, Forward/Back mouse buttons, and Arrow Keys.

### Actual behavior:
When advancing through a large number of images using navigation buttons quickly, two clicks are required to navigate to the next image. When advancing through images slowly, only one click is required.

### Steps to reproduce:
1. Enable Navigation Buttons
2. Open a directory with a large number of images
3. Click the right side of the image quickly. Two clicks are required to advance to the next image.

### Other info:
The faster the navigation button is clicked, the faster the image advances, seemingly without limit. It appears that at high speed the first click is not registered by the navigation buttons.

**Comment by d2phap** [comment]
Hi @squaven 
This bug is fixed in the improved navigation arrow buttons in the latest build of ImageGlass Moon:
https://imageglass.org/moon

![image](https://user-images.githubusercontent.com/3154213/78454971-3bfd0680-76ce-11ea-8c2a-30d89ea58f75.png)
