### ISSUE TITLE
Support for woff2

### ISSUE THREAD

**Issue by michal-roman** [d2phap/ImageGlass#725]
Are you considerinig for woff2 support?

**Comment by d2phap** [comment]
@michal-roman 
We support those formats from ImageMagick library

**Comment by michal-roman** [comment]
![image](https://user-images.githubusercontent.com/48259464/79981010-424bfa80-84a4-11ea-8fa2-2ddffb5635b0.png)

not sure then, if correctly - it shuldn't be vector graphic :) 
same with SVG files

**Comment by d2phap** [comment]
Close this for now
