### ISSUE TITLE
Display navigation arrow buttons are blinking

### ISSUE THREAD

**Issue by uvrem** [d2phap/ImageGlass#726]
### System information:
 - Windows 10 
 - ImageGlass version 7.5.3.29
 - 4k display.

### To Reproduce
1. Display navigation arrow buttons should be active in ImageGlass.
2. Please check the video at https://streamable.com/mt9ui 

### Actual behavior:
The mouse cursor is blinking, when you move it.

### Expected behavior:
The mouse cursor should not blink, when you move it.

### Screenshots:
https://streamable.com/mt9ui

**Comment by d2phap** [comment]
Hi @uvrem 
This bug is fixed in the improved navigation arrow buttons in the latest build of ImageGlass Moon:
https://imageglass.org/moon

![image](https://user-images.githubusercontent.com/3154213/78454971-3bfd0680-76ce-11ea-8c2a-30d89ea58f75.png)
