### ISSUE TITLE
Renaming file does not rename if case is different

### ISSUE THREAD

**Issue by BitLooter** [d2phap/ImageGlass#73]
When a file is renamed with ImageGlass, if the new filename is identical to to the original except case, it does not rename. For example, if you have a file named Image.png, and you want to rename it to image.png, the case will not change.

**Comment by d2phap** [comment]
Hi @BitLooter 

I just did a test: rename Image.png to image.png with ImageGlass, it's working properly.

**Comment by fire-eggs** [comment]
BitLooter -
I do have difficulty reproducing the problem using Windows 7. However, with certain shared folders or mapped drives, Windows will refuse to allow a rename to change only the case.

The following linked page references the problem. Until or if ImageGlass is updated to work around the problem, you might try the Registry changes mentioned in the article.
http://www.techsupportalert.com/content/how-force-your-windows-file-and-folder-names-have-case-you-want.htm

fire-eggs

**Comment by BitLooter** [comment]
This actually was on a shared drive, that must be the problem. Thanks for the info.
