### ISSUE TITLE
Background Color toolbar button 

### ISSUE THREAD

**Issue by mriise** [d2phap/ImageGlass#730]
### Is your feature request related to a problem? Please describe.
Some images are better seen with different color backgrounds.

### Describe the solution you'd like
add a hot-swappable background color button to the toolbar for temporary background color change. Like the same with the setting in the settings menu, just a little more accessible when scrolling through a variety of images. 

An "invert background color" button would also work, but is more limiting in terms of flexibility

v7.5.1.1

**Comment by d2phap** [comment]
Hi @mriise 

Can you describe more details how you would want to use this button?
- Every time click on the button on toolbar
- Pick up a color
- Background color changed

Or,
- Define a temporary background color in Settings
- View an image file
- Click on the button on toolbar
- Background color changed
- Click on the button again
- Background reverted back to the default color.

**Comment by mriise** [comment]
I think having a "primary" color like the settings does now, and a "secondary" color in settings would cover most circumstances.

-left click tool to swap between primary and secondary colors
-right click tool to define a new secondary color 

So similar to the second option.

Would the "secondary" color be stored temporarily for that image or instance; or would it be stored as the "secondary" color for all new instances going forward?

**Comment by d2phap** [comment]
In v9.1, you can quickly change background color by pressing <kbd>M</kbd> hotkey (or Menu > Layout > Change background color...).

You can add a custom toolbar button to change the background to your favourite color as well: Open Settings > Toolbar > Toolbar buttons, click "Add a custom button" button and use this JSON:

The below JSON sets the background to red (hex code: `#ff0000`)
```json
{
  "Id": "Btn_ChangeBackgroundColor",
  "Type": "Button",
  "Text": "Change background color",
  "Image": "C:\\path\\to\\icon.svg",
  "Alignment": "Left",
  "CheckableConfigBinding": "",
  "DisplayStyle": "Image",
  "OnClick": {
    "Executable": "IG_SetBackgroundColor",
    "Arguments": ["#ff0000"]
  }
}
```

You may need to restart ImageGlass after adding a custom button to take effect.
