### ISSUE TITLE
Excessive gap/spacing when moving toolbar item to the left of the back/next buttons

### ISSUE THREAD

**Issue by minig0d** [d2phap/ImageGlass#732]
### System information:
 - Windows OS version: Windows 10 x64 Pro 1909
 - ImageGlass version: 7.5.1.1

### To Reproduce
1. From Settings > Toolbar
2. Select any item on the toolbar and click the up arrow to move it to the left of the previous/next toolbar buttons (in this screenshot I just moved the "refresh" button over
3. 
4. 

### Actual behavior:

Giant Gap

### Expected behavior:

No Gap

### Screenshots:

![Before Moving](https://user-images.githubusercontent.com/54046315/79031985-89fb8980-7b68-11ea-8919-df5d81187c6f.png)
![After Moving](https://user-images.githubusercontent.com/54046315/79031990-8d8f1080-7b68-11ea-89a5-6d19d05c1b8a.png)

### Additional context:
You'll notice it moved to of the icons off screen into the ... overflow menu

Also for some reason applying doesn't apply right away have to click apply then save (unsure if this is at all related or a different bug)

**Comment by d2phap** [comment]
Fixed and shipped in ImageGlass Moon: https://imageglass.org/moon
