### ISSUE TITLE
IG is very slow while working with large resolution images

### ISSUE THREAD

**Issue by TheSa3er** [d2phap/ImageGlass#734]
### System information:
 - Windows OS version: Microsoft Windows [Version 10.0.17134.228]
 - ImageGlass version: 7.5.1.1

### To Reproduce
1. Navigate through a folder with large resolution images. (e.g. 5000px and higher).
2. The same happens with large resolution TIFF and PNG files.
3. 
4. 

### Expected behavior:

The does not happen when using built-in Windows 10 Photo app or Adobe Bridge.

**Comment by d2phap** [comment]
Possibly duplication of #720 
Please try the new build of ImageGlass Moon at https://imageglass.org

**Comment by TheSa3er** [comment]
I tried the latest Moon version.
A little better, but still lags and long delays, even on window resize.
It's very frustrating.

So here I made GIF Video comparing IG speed with other viewers:
https://i.imgur.com/FXjQXCE.mp4

Hope it helps. Or maybe you could study their source code and figure out what they did.

**Comment by fire-eggs** [comment]
Thank you for the feedback and the video! I'll try to set up a similar situation on my machine and test it out.

A few thoughts:
1. Try turning off the checkerboard background. As per issue #419, some have seen performance degradation with checkerboard on. I don't expect a big win but it might help.
2. Try turning off the color picker. The other viewers didn't have the equivalent on.
3. All the viewers you show us are closed source so we can't readily look at their source code. But there are things we could learn!

**Comment by AaronAmadeus** [comment]
I tried all your suggestion and I just now downloaded the newest version. 
I'm on win7 64bit and it takes me half a minute to open a .jpg with 10k on the long edge. (2.8mb)

**Comment by AaronAmadeus** [comment]
OK update: I had the wrong version and it's way faster now :D Sorry !

**Comment by TheSa3er** [comment]
@AaronAmadeus Please do not hijack my thread. As I said earlier the problem still persists after updating to latest MOON version (7.5.4.21) and this is not definitely fixed. As I've shown in the latest video, here is another one. If you needed more information or more detailed videos let me know:
https://i.imgur.com/j01lKT2.mp4

**Comment by TheSa3er** [comment]
@d2phap @fire-eggs This is not a duplicate and this is not fixed. You were supposed to set up a similar situation and let me know about the results.

**Comment by d2phap** [comment]
@TheSa3er I guess you can increase the number of pre-loaded image in Settings > Image tab

**Comment by TheSa3er** [comment]
@d2phap Grateful but it doesn't work. Still get 1-second-lags on some high resolution images. As I've shown in some videos ago I'm only experiencing it with IG and this is not and issue with other viewers. It feels as if it has something to with the rendering-engine / resizing and anti-aliasing and sort of technologies.
Here it is again for review:
https://i.imgur.com/FXjQXCE.mp4

Please make the IG fast, I like it very much. And if possible have a thumbnail view as well. Thanks.

**Comment by d2phap** [comment]
Hi @TheSa3er 

Some of things can make it slow are:
- The framework. All photo viewer is written by C/C++ but ImageGlass is based on WinForms .NET C#, there is a limitation of native performance.
- GPU acceleration. WinForms with GPI+ does not support GPU acceleration.
- Color management. This color correction requires extra loading time.
- My knowledge. I don't know the optimal way to cache properly.

I have plan to move it to WPF which supports GPU acceleration but this is time-consuming task.

In the meanwhile, you can disable Color management (if you don't care about the color) to speed up it. Go to Settings > Image tab, Color management, change Color profile select box to `None`.

As we already have a thread to discuss performance at #272, I will keep this issue closed.
Thank you.

**Comment by TheSa3er** [comment]
Wow that's a great news. I think IG is really a great image viewer, amazing UX and futuristic UI. If only the speed problem goes away, it'll definitely become the best light wave image viewer ever.

Thanks for the tip, yes it improves the loading times:
https://i.imgur.com/wPD6Pk6.mp4

You can also notice that lag during image resize. But having my high hopes for GPU acceleration.

I'm very grateful for what you do and thank you for the time you put on this magnificent software.
