### ISSUE TITLE
Touchscreen image navigation backwards

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#736]
From Google+:
>The swiping seems to be reversed in image glass. When I swipe to change the image it goes the wrong way.

Provided video demonstrates this is true.

Assuming that something has not reverted, it may be necessary to add an option to reverse direction.

**Comment by fire-eggs** [comment]
fixed

**Comment by fire-eggs** [comment]
See also issue #683

**Comment by d2phap** [comment]
Shipped in ImageGlass Moon https://imageglass.org/moon
