### ISSUE TITLE
HSV color picker data

### ISSUE THREAD

**Issue by Coreat** [d2phap/ImageGlass#738]
The current version of ImageGlass already has a pretty nice color picker, but it lacks HSV data support (which is different from HSL), it would be nice to have an additional HSV data box added below the HSL data.
![image](https://user-images.githubusercontent.com/37432274/79184392-96bcfd80-7e46-11ea-9d8a-dc5cc7ce30be.png)

**Comment by d2phap** [comment]
RGB and HSV algorithms
https://stackoverflow.com/a/1626175

**Comment by d2phap** [comment]
Added HSV format to Color picker tool.
Try the latest build: https://imageglass.org/moon

![image](https://user-images.githubusercontent.com/3154213/94579990-f8194180-02ab-11eb-8ada-e15c07f3a233.png)

**Comment by Coreat** [comment]
> Added HSV format to Color picker tool.
> Try the latest build: https://imageglass.org/moon
> 
> ![image](https://user-images.githubusercontent.com/3154213/94579990-f8194180-02ab-11eb-8ada-e15c07f3a233.png)

Works like a charm! Thank you for the effort!
