### ISSUE TITLE
Zoom with touch should zoom at touch location

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#739]
Zoom via touch gestures [swipe up/down] currently zooms at the image center.

It should zoom in/out at the location where the touch gesture started.

Need to confirm if this is an issue with pinch-zoom.

**Comment by ThomasLeigh** [comment]
It could be great to have it working also for double click to zoom: I often need to zoom particular image area and it can be of a great help to zoom directly where I’ve clicked instead of being in the need to constantly looking for a desired area on a zoomed image.

**Comment by d2phap** [comment]
This feature is implemented in [ImageGlass 9.0 beta 5](https://github.com/d2phap/ImageGlass/releases/tag/9.0.5.726)
