### ISSUE TITLE
Slideshow mode on startup

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#740]
If exited via Alt+F4 during a slideshow, the ImageGlass config state is confused.

1. Run ImageGlass. Have one or more images loaded. Configure the toolbar or thumbbar to be off as desired.
2. Start a slideshow.
3. Use Alt+F4 to exit ImageGlass.
4. Run ImageGlass.

Note that ImageGlass is currently in "slideshow mode", but not fullscreen and not actually playing a slideshow. The user needs to exit slideshow mode at this point.

A side effect: when the user exits slideshow mode, the toolbar and thumbbar will always be turned ON, even if at step 1 above the toolbar or thumbbar were OFF.

Suggestion: on exit, ImageGlass should turn off the slideshow.

**Comment by s1nbad** [comment]
As a side note, when searching for how to use Slideshow in a window, other users have suggested using this 'bug' as a way of achieving this.  If you are to consider fixing this please take a look at supporting Slideshow in a window.

**Comment by d2phap** [comment]
Slideshow mode is supported in [ImageGlass Moon 9.0 beta 3](https://github.com/d2phap/ImageGlass/releases/tag/9.0.3.1225) with full screen / windowed mode
