### ISSUE TITLE
TXT (Base64String) file type support

### ISSUE THREAD

**Issue by xmha97** [d2phap/ImageGlass#741]
Hello, Please add support open Base64String file (.txt)
![image](https://user-images.githubusercontent.com/23485114/79320727-8298ff00-7f1f-11ea-82f7-864f18d3bf13.png)

**Comment by d2phap** [comment]
@xmha97 it's done and shipped to IG Moon: https://imageglass.org/moon

- By default, IG supports `.b64` as base-64 file format. It also supports for `.txt` but you need to manually add extension in Settings > File Type Associations tab.
- Conversion to base-64 format with `.b64` or `.txt` extension: The MIME types of base64 file are:
  - `image/gif`: animation supported
  - `image/tiff`: multi-page supported
  - `image/webp`: animation supported (*)
  - `image/svg+xml`: scaling supported (*)
  - `image/bmp`, `image/jpeg`, `image/x-icon`
  - `image/png`: all other image formats will be saved as PNG base-64
(*) - when copy the base64 content and open in browser - Chrome
- Conversion from base-64 format to image formats (png/bmp/gif/...):
  - TIFF / GIF: Only first frame/page
  - SVG base-64 converted to pixelated format
