### ISSUE TITLE
Background and text of Color picker

### ISSUE THREAD

**Issue by DanRotaru** [d2phap/ImageGlass#743]
### Description:
The color pallete has a dark background and black text in that, please fix it.

### Screenshots:
![pallete](https://i.ibb.co/s5KNLz7/image.png)

### System information:
 - Windows OS version: Windows 10 (1909) (using light theme)
 - ImageGlass version: 7.5.1.1

**Comment by d2phap** [comment]
@DanRotaru 
What are the steps to reproduce? I cannot reproduce this.

**Comment by DanRotaru** [comment]
> @DanRotaru
> What are the steps to reproduce? I cannot reproduce this.

I just open it: https://skr.sh/v/180420/eIflOYck.mp4

**Comment by DanRotaru** [comment]
Done! I just update config.xml file, change backcolor="#212121" to backcolor="#fffff", and now it's good: ![img](https://i.ibb.co/P5qHNwk/image.png)

**Comment by d2phap** [comment]
The text color in theme pack is not correct.

**Comment by d2phap** [comment]
Fixed in https://github.com/marnick-s/material-imageglass-themes
