### ISSUE TITLE
Add color picker button to toolbar

### ISSUE THREAD

**Issue by DanRotaru** [d2phap/ImageGlass#744]
### Screenshot (here) :
![instruments](https://i.ibb.co/L5pBwb8/image.png)

**Comment by arnofly** [comment]
+1

**Comment by d2phap** [comment]
Added Color picker button on toolbar.
- However, it's hidden by default. You need to go to Settings > Toolbar, select the Color button, add it to the right list.
- Only default themes of ImageGlass (2017 Dark and 2017 Light) support this icon as of now.

Shipped this in https://imageglass.org/moon
![image](https://user-images.githubusercontent.com/3154213/79860492-542a9080-8405-11ea-93c6-09a82e34ffbd.png)
