### ISSUE TITLE
Menu says there's an update available, despite being updated

### ISSUE THREAD

**Issue by Unknow0059** [d2phap/ImageGlass#745]
### System information:
 - ImageGlass version: Version: 7.5.1.1 stable
 - Windows OS version: Windows 10 Pro 1909 10.0.18363.778 64-bit

### Expected behavior:
No "Update available" warning, when in the latest version.

### Actual behavior:
"Update available" warning, despite me being in the latest version.

### Screenshots:
![image](https://user-images.githubusercontent.com/25656892/79634304-08939080-8140-11ea-852a-0f16153304d0.png)
![image](https://user-images.githubusercontent.com/25656892/79634314-1a753380-8140-11ea-976c-973af468a266.png)

**Comment by d2phap** [comment]
Thanks @Unknow0059 

This bug was fixed in ImageGlass Moon (https://imageglass.org/moon) as reported at #688
The official release will be shipped in couple of weeks.
