### ISSUE TITLE
Keyboard layout related shortcut keys suggestion

### ISSUE THREAD

**Issue by hNczy** [d2phap/ImageGlass#749]
### Is your feature request related to a problem? Please describe.
I tried the IG (7.5.1.1 - Win10x64 19041.207) with hungarian language pack with a my default keyboard layout ([hungarian](https://en.wikipedia.org/wiki/QWERTZ#/media/File:KB_Hungary.svg)). And when move the mouse over the flip horizontal / vertical menu icons it suggesting me the `Ctrl + ;` and `Ctrl + '`. But in hungarian layout there is not a simple `;` and `'` keys. The correct suggestion will be `Ctrl + É` and `Ctrl + Á`.

### Describe the solution you'd like
I suggest to ask the current keyboard layout settings from the system.

### Describe alternatives you've considered
Maybe it can depending from the language pack also, and there can be define the keyboard shortcuts.

### Additional context
I wrote only two example (the `Scale to fit` is similar) from Hungary, but I think this is also problem in many other language and keyboard layout. Actually it depends only the keyboard layout.

**Comment by Yochyo** [comment]
I have the same Problem with my german keyboard layout. It would be nice if the current keyboard layout would be asked from the system or if you could change keybinds.

**Comment by d2phap** [comment]
ImageGlass 9 added support for customizing hotkeys via `igconfig.json` file, refer #1702 for more details
