### ISSUE TITLE
Make bulit-in language pack go into source code repo.

### ISSUE THREAD

**Issue by s8321414** [d2phap/ImageGlass#75]
I think this is a good idea to make bulit-in language pack up-to-date. :smiley:

**Comment by d2phap** [comment]
Hi @s8321414 

Thanks, it's really good idea.

**Comment by s8321414** [comment]
\o/

**Comment by s8321414** [comment]
hmmm?

**Comment by d2phap** [comment]
Hi @s8321414,

I will use Crowdin.com to host the language packs which also supports many collaborators:
To join in, accecpt the following invitation link:
https://crowdin.com/project/imageglass/invite

Thanks :)

**Comment by s8321414** [comment]
Great!

**Comment by s8321414** [comment]
How about sync some langpacks to website? :smile:

**Comment by d2phap** [comment]
hi @s8321414 
I do very soon. Just enjoyed my trip

**Comment by s8321414** [comment]
Have fine :smiley:
