### ISSUE TITLE
Show image properties "Exif, Xmp, Iptc, ..." tool

### ISSUE THREAD

**Issue by vvv-easy** [d2phap/ImageGlass#751]
### Is your feature request related to a problem? Please describe.
Today Imageglass only shows the image file properties of the Windows.

### Describe the solution you'd like

It would be very interesting to also see the properties "Exif, Xmp, Iptc, ..."

### Describe alternatives you've considered

An easy way to implement it would be to use the application "command in line" ExifTool by Phil Harvey and show the console output.

**Comment by fire-eggs** [comment]
duplicate of issue #661

**Comment by d2phap** [comment]
merge this to #336

**Comment by d2phap** [comment]
Implemented Exif tool in ImageGlass Moon: https://imageglass.org/moon
For more details, check at #871
