### ISSUE TITLE
Cannnot open .gif

### ISSUE THREAD

**Issue by Glenta** [d2phap/ImageGlass#752]
### System information:
 - Windows OS version: Windows 10 Pro 1909
 - ImageGlass version: 7.5.1.1

### To Reproduce
1. Install ImageGlass with msi installer
2. Open a .gif
3. You get "ImageGIass cannot open this picture because the file appears to be damaged, corrupted or not supported. ImageGIass: Object reference not set to an instance of an object."

### Actual behavior:

Getting "ImageGIass cannot open this picture because the file appears to be damaged, corrupted or not supported. ImageGIass: Object reference not set to an instance of an object."

### Expected behavior:

Open the .gif

### Screenshots:

![image](https://user-images.githubusercontent.com/38775826/80106344-be4b4e80-8547-11ea-8363-96aea98a0082.png)

**Comment by d2phap** [comment]
Can you share your gif file, thank you

**Comment by Glenta** [comment]
While all gifs don't work, here are some examples
![wly3l6y50eh41](https://user-images.githubusercontent.com/38775826/80112015-9a3f3b80-854e-11ea-80d2-01b1c0926be9.gif)
![k82cy41qshx31](https://user-images.githubusercontent.com/38775826/80112077-b04cfc00-854e-11ea-9674-e6bc9e4b53bb.gif)

**Comment by d2phap** [comment]
@Glenta 
Your gifs don't have the correct header. It's not only ImageGlass, Chrome also cannot open it

**Comment by fire-eggs** [comment]
To confirm: those are GIF files, they're video files. You can play them back with a video player such as VLC, MPV,  or Windows Media Player. Rename them from .GIF to .MP4 and you'll be good to go.

While perusing Imgur I find a lot of posts are mis-labelled as "GIFs". I believe that if someone actually posts a GIF to Imgur, it is converted to a video file.
