### ISSUE TITLE
Touch Support for Thumbnails

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#753]
A suggestion via Google group.

There is no touch support in the thumbbar. The two capabilities that would be good to have:
1. Ability to view an image by touching its thumbnail.
2. Ability to scroll through the thumbnails (panning) via touch.

**Comment by d2phap** [comment]
Implemented in [ImageGlass 9.0 beta 5](https://github.com/d2phap/ImageGlass/releases/tag/9.0.5.726)
