### ISSUE TITLE
Crop Tool Enhancements

### ISSUE THREAD

**Issue by minig0d** [d2phap/ImageGlass#755]
### Describe the solution you'd like
Enhancements to the new crop tool, such as:
1) cropping to a specific aspect ratio, ex 1:1, 1:2, 4:3, 16:9, original aspect ratio, user defined aspect ratio
2) option to center the crop rather than originating from 0, 0
3) preference to auto close crop pane after crop is completed
4) rename "Clear" to "Reset" as clear implies potentially clearing part of the image.
5) visually make the clear button different from the other 3 buttons (since these are functionally things the user wants to do with the final product of the crop, so it's a little confusing/cluttered that the clear button is grouped with them.

**Comment by thefallinglink** [comment]
Yes, this exactly! Maybe even a button like in photoshop to change the coordinate's origin (top left, bottom left, etc.)

**Comment by d2phap** [comment]
Implemented (4), (5) in https://imageglass.org/moon
> 4. rename "Clear" to "Reset" as clear implies potentially clearing part of the image.
> 5. visually make the clear button different from the other 3 buttons (since these are functionally things the user wants to do with the final product of the crop, so it's a little confusing/cluttered that the clear button is grouped with them.

![image](https://user-images.githubusercontent.com/3154213/94578616-8b517780-02aa-11eb-9054-e6d57b9b313e.png)

![image](https://user-images.githubusercontent.com/3154213/94578709-9f957480-02aa-11eb-9836-63bd19b9ba36.png)

**Comment by Kuphi** [comment]
Just switched back from seven years main Linux system to Windows. ImageGlass seems to be the photo viewer of choice for daily tasks. Everything looks great so far. Adding cropping to fixed aspect ratios (1:1, 1:2, 4:3, 16:9, etc.) would be great. I used this feature in Shotwell and would for sure miss it. Thank you for developing ImageGlass!

**Comment by d2phap** [comment]
[ImageGlass Moon 9.0 beta 3](https://github.com/d2phap/ImageGlass/releases/tag/9.0.3.1225) added support for
- cropping with aspect ratios,
- setting the default selection,
- an option to close the Crop tool after it's done

![image](https://user-images.githubusercontent.com/3154213/209428453-fab81990-c437-4124-b619-21d857f71a4f.png)
