### ISSUE TITLE
WebP images don't show thumbnail in OneDrive folder

### ISSUE THREAD

**Issue by pnthach95** [d2phap/ImageGlass#756]
### System information:
 - Windows OS version: Windows 10 1909 build 18363.778
 - ImageGlass version: 7.5.1.1

### To Reproduce
1. Save WebP images in a OneDrive folder

### Actual behavior:

No thumbnail in OneDrive folder

### Expected behavior:

Show thumbnail in OneDrive folder like in normal folder

### Screenshots:

OneDrive folder

![image](https://user-images.githubusercontent.com/31266357/80189681-43fcf600-863d-11ea-8e82-31118b7fe775.png)

Normal folder can show thumbnail

![image](https://user-images.githubusercontent.com/31266357/80189784-74449480-863d-11ea-96c8-dc01a5497bca.png)

### Additional context:

OneDrive version 19.232.1124.0012

**Comment by fire-eggs** [comment]
ImageGlass is not the provider of your Explorer thumbnails. You need to contact Microsoft to see if they have a solution.

You might try dis-associating ImageGlass with the .webp extension to see if that helps.
