### ISSUE TITLE
Colors by CR2 format slightly off

### ISSUE THREAD

**Issue by Matix-Media** [d2phap/ImageGlass#758]
Hi, I recognized that the colors are slightly off when you use the CR2 (canon raw 2) format using ImageGlass version 7.5.1.1.

For comparison, here is the same photo in JPG and in cr2 format:
JPG:
![Anmerkung 2020-04-27 161013_2](https://user-images.githubusercontent.com/47772205/80381724-a6563080-88a1-11ea-9a93-271a74dad0f5.png)

CR2:
![Anmerkung 2020-04-27 161013](https://user-images.githubusercontent.com/47772205/80381798-c554c280-88a1-11ea-9dd3-05334cceb876.png)

Files to download (Provided using Google Drive):
https://drive.google.com/drive/folders/1EAeDdSGhcUUkXdMjk9Qr-Y1g-YDyXDk6?usp=sharing

**Comment by d2phap** [comment]
@Matix-Media 
- What IG version?
- And can you send me the file?

Thank you

**Comment by Matix-Media** [comment]
ImageGalss Version: 7.5.1.1
Image files (Provided via Google Drive):
https://drive.google.com/drive/folders/1EAeDdSGhcUUkXdMjk9Qr-Y1g-YDyXDk6?usp=sharing

**Comment by MihleG** [comment]
Its the same with Fuji RAW files(RAF)
I think its mainly that it ingonores camera metadata of colour temperature, or uses that metadata wrong.
As the example it always seem to be too yellow. On daylight shots at least.

**Comment by Matix-Media** [comment]
Yeah, it's always "yellower" as the original

**Comment by d2phap** [comment]
I have just made improvement to fix the yellowish color. It looks better but its brightness is slightly different from MS Photos / Photoshop.
You can try it in the latest build of IG Moon: https://imageglass.org/moon

Btw, this issue and #464 are same problem, so I will close this.

![image](https://user-images.githubusercontent.com/3154213/98556479-0e201600-22de-11eb-91fb-393f992a4a25.png)
