### ISSUE TITLE
Make toolbar autohide

### ISSUE THREAD

**Issue by eckso** [d2phap/ImageGlass#76]
So image has more screen display area. Image information can be (upon settings) displayed on top with transparency.
At any time the cursor can go to the top to automatically show the toolbar and change any setting.

**Comment by d2phap** [comment]
Hi @eckso 

In current version, you can show/hide toolbar via context menu or Ctrl+F1 hotkey

**Comment by d2phap** [comment]
Closed this because it is not necessary
