### ISSUE TITLE
Option to chose random in slideshow

### ISSUE THREAD

**Issue by anyfactor** [d2phap/ImageGlass#760]
I would like to request the option to view randomly sequential images in the current directory when I am in the slideshow mode.

**Comment by d2phap** [comment]
You can change it in Settings > Image > Image loading order

![image](https://user-images.githubusercontent.com/3154213/80501035-873ec800-89a1-11ea-8005-4cb6f28f2f4d.png)

**Comment by SimplSam** [comment]
But is there a way to switch during the Slideshow. i.e. With a short-cut key - so that I can switch between Default and Random - without going through the menus?

**Comment by d2phap** [comment]
Hi @SimplSam 
Sadly there is no shortcut. I will add this to the menu in the next release

**Comment by ftvkyo** [comment]
Hello @d2phap , just pinging you about this. Thanks for your work :)
