### ISSUE TITLE
Tools disappear from toolbar OR window shrinks - after deactivating full screen mode

### ISSUE THREAD

**Issue by SredniVashtar** [d2phap/ImageGlass#761]
### System information:
 - Windows OS version: Windows 10
 - ImageGlass version: 7.5.1.1

### To Reproduce
1. Open an image file
2. Set to full screen (Alt+Enter)
3. Deactivate full screen (Alt+Enter)

### Actual behavior:
Tools disappear from toolbar after deactivating full screen mode
OR
ImageGlass window shrinks after deactivating full screen mode

Both keep happening.

### Expected behavior:
I would expect tools to stay on toolbar, right where they were before going full screen.
I would expect window not to shrink and to be the same size it was before going full screen.

### Screenshots:
![After full-screen](https://user-images.githubusercontent.com/64483667/80503746-9a866f00-8972-11ea-93c9-7243dd351481.PNG)
![Before full-screen](https://user-images.githubusercontent.com/64483667/80503750-9bb79c00-8972-11ea-9136-bb31751b08ae.PNG)

**Comment by d2phap** [comment]
Hi @SredniVashtar 
Can you try ImageGlass Moon https://imageglass.org/moon?
It's may be duplication of #732

**Comment by SredniVashtar** [comment]
Just downloaded 7.6.4.30 and everything works perfectly! 

Thank you so much for this great software =)

P.S.
Just one little thing: the 'New version is available' "warning" is still visible and highlighted in the Help section.
