### ISSUE TITLE
Some string translations are not correctly displayed for French language

### ISSUE THREAD

**Issue by Gaoura** [d2phap/ImageGlass#762]
### System information:
 - Windows OS version:  Windows 10 Home N°18363
 - ImageGlass version:  7.5.1.1 x64

### To Reproduce
1.  Install ImageGlass and choose French language
2.  Right-click on the default picture and check the translation for "Set as Lock screen image", "Copy image data" and "View channels"
4.  Check the translation for several texts in the top toolbar as "Rotate left", "Rotate right" and some others

### Actual behavior:

The text still is in English for some strings

### Expected behavior:

I would expect the software to be fully translated in French, as I saw that the strings really are translated in French on Crowdin

### Screenshots:

![image](https://user-images.githubusercontent.com/5923601/80512277-8ac05800-897d-11ea-8f05-56ceb90d4df2.png)

### Additional context:

It was my first install of ImageGlass and I didn't download separately any language pack

**Comment by d2phap** [comment]
Hi @Gaoura 

The translation depends on community, you can join the Crowdin at:
https://crowdin.com/project/imageglass/invite

In the upcoming release, French language pack is fully translated 100%.

**Comment by Gaoura** [comment]
So you mean it's not a bug but that it wasn't 100% translated (as it is on Crowdin) yet in the version I just downloaded ? Ok ty for the info
