### ISSUE TITLE
HEIC format

### ISSUE THREAD

**Issue by lxryaxa** [d2phap/ImageGlass#768]
### Is your feature request related to a problem? Please describe.

In Windows 10 (1909) and ImageGlass (7.6.4.30) I do not see the image thumbnails for .HEIC files, only the ImageGlass thumbnail. I was wondering if this would be implemented soon (or if it is, how to enable it)
### Describe the solution you'd like

I would like there to be image thumbnails visible for .HEIC files in the same way as they're currently implemented for other image formats.
### Describe alternatives you've considered

I would like to mention that if it is the case that this feature is already present and I am not configured properly to see it, I would also like help on that. My settings seem to be configured properly to see thumbnails of images, just not of .HEIC files
### Additional context

For a screenshot of what I mean, I posted one below
![image](https://user-images.githubusercontent.com/50604280/80774230-66ee4500-8b2a-11ea-8cef-03b5f19da421.png)

**Comment by d2phap** [comment]
You can download this extension from Store: https://www.microsoft.com/en-us/p/heif-image-extensions/9pmmsr1cgpwg?activetab=pivot:overviewtab
