### ISSUE TITLE
HEIC broken

### ISSUE THREAD

**Issue by GrandArth** [d2phap/ImageGlass#769]
### System information:
 - Windows OS version: windows10
 - ImageGlass version: 7.6.30

### To Reproduce
1. download
[0001.zip](https://github.com/d2phap/ImageGlass/files/4563673/0001.zip)
2. open it with imageglass

### Actual behavior:

![图片](https://user-images.githubusercontent.com/30680793/80800525-4aaae080-8bdc-11ea-9eb1-343b5a9bd182.png)

### Expected behavior:

![图片](https://user-images.githubusercontent.com/30680793/80800560-55fe0c00-8bdc-11ea-9640-4899bad7e5ca.png)

### Additional context:
I tested my images on IOS they work just fine, wonder what is causing this.
These images were created by myself  using ffmpeg (to encode them as a frame) and mp4box (to box it as heic).

**Comment by GrandArth** [comment]
I see... this should more of a feature request then a bug, the main reason for this is that IG doesn't support 10-bit hevc encoded heic, i give it another shot with 8-bit encoding and everything worked fine.

**Comment by d2phap** [comment]
I use Magick.NET to read all image formats.
I will report to the fork.

Thanks
