### ISSUE TITLE
Suggestion: Ability to display thumbnails at right or left instead of bottom

### ISSUE THREAD

**Issue by HanatakeYurii** [d2phap/ImageGlass#77]
Hi,

Like the title state, it could be very useful to have a config for displaying the thumbnails at right or left instead of the bottom since it takes a large height (better display of images with high height).

**Comment by s8321414** [comment]
maybe an option about this will be great!

**Comment by d2phap** [comment]
It's done :)

**Comment by HanatakeYurii** [comment]
Thanks :+1:
