### ISSUE TITLE
Ctrl + v can't work on Rename dialog

### ISSUE THREAD

**Issue by sojey** [d2phap/ImageGlass#770]
### System information:
 - Windows OS version: win 10 x64 1909 18363.815
 - ImageGlass version: 7.6.4.30 portable

### To Reproduce
1. n win10 explorer, use imageglass to open a jpg file.
2. press F2, then press ctrl + v, the original copy of the text in the EDGE browser can not be pasted.
3. but the right mouse button-paste.
4. I think this is a bug.

**Comment by d2phap** [comment]
Hi @sojey 

What do you paste into ImageGlass?
It should be image data or base64 text

**Comment by sojey** [comment]
> Hi @sojey
> 
> What do you paste into ImageGlass?
> It should be image data or base64 text

I copied a text in the EDGE browser. 
I want used that text to Change the file name of the open jpg in ImageGlass, use F2 open rename dialog box, then ctrl + v, those texts cannot be pasted in the selected text.
The window focus is not lost.
I can only use the right mouse button - paste. To rename the opend jpg file.

This is a translator, I hope you can understand it.

**Comment by d2phap** [comment]
Thanks for more details. Confirm the bug.

**Comment by sojey** [comment]
hope you do well, I like this software.

**Comment by d2phap** [comment]
This bug is fixed in IG Moon: https://imageglass.org/moon
