### ISSUE TITLE
Startup error with igconfig.admin.xml and igconfig.default.xml present

### ISSUE THREAD

**Issue by etherforea** [d2phap/ImageGlass#771]
### System information:
 - Windows OS version: Windows 10 Pro 1909
 - ImageGlass version: 7.5.1.1, 7.6.4.30

### To Reproduce
1. Fresh install of ImageGlass
2. Deploy igconfig.admin.xml and igconfig.default.xml into the startup folder
3. %AppData%\ImageGlass doesn't exist yet
4. Start ImageGlass

### Actual behavior:
Error: Some settings are not compatible with your ImageGlass 7.6.4.30. It's recommended to update them before continuing...

### Expected behavior:
ImageGlass should start without errors.

### Additional context:
Deployed config files: [imageglass.zip](https://github.com/d2phap/ImageGlass/files/4565850/imageglass.zip)

**Comment by d2phap** [comment]
Thanks @etherforea 
Confirm the bug

**Comment by d2phap** [comment]
Fixed this and shipped in IG Moon: https://imageglass.org/moon
