### ISSUE TITLE
[Code Quality]: Tooling & .NET 4.8 migration

### ISSUE THREAD

**Issue by unquietwiki** [d2phap/ImageGlass#773]
https://github.com/unquietwiki/ImageGlass/tree/develop

Since I've used this program for 2-3 years now and was just looking at another program I use regularly, I figured I'd take a crack at making some codebase improvements. Here's what I'm going for...

- [.NET 4.8](https://dotnet.microsoft.com/download/dotnet-framework/net48) as a target runtime in the Solution components.
- Use [CodeMaid](http://www.codemaid.net/) to enforce formatting cleanup.
- Use [Sharpen](https://sharpen.rocks/) to suggest refactorings.

Sharpen can't yet do its refactorings automatically; it leans on user interaction + VS Code's own refactoring suggestions. The C# 5.0 & 8.0 refactorings are more involved because they involve async & null changes; the rest involve more basic changes, that have a less disruptive impact. I've done some of the work, but there remains much to do. I have other stuff I need to work on, so I don't want to put too much time into this if it's not going to be of use. Please advise. Thanks!

**Comment by unquietwiki** [comment]
@d2phap BTW thank you for answering my previous question a while back about added a codec. Since this is your work, I'd like your thoughts on this.

**Comment by d2phap** [comment]
Hi @unquietwiki 

It's good to know you want to refactor and clean up the code.

Actually, I have plan to move IG from WinForms to WPF with .NET 5; this will take long time!
The WPF version will reuse most of the code, except for `ImageGlass.ImageBox`, `ImageGlass.ImageListView`, and the UI code for WinForms...

Please feel free to create small pull requests of refactoring. I'm happy to merge it.
Thanks a lot!
