### ISSUE TITLE
Window position and size change when opening a picture

### ISSUE THREAD

**Issue by xmha97** [d2phap/ImageGlass#774]
Hello
Window position and size change when opening a picture.
This problem occurs when I split my screen. (drag and drop a window into the corner)
![Windows 10](https://user-images.githubusercontent.com/23485114/80921531-30b00000-8d8c-11ea-9737-1bb994fba6cb.gif)

**Comment by Rasmagoric** [comment]
Yeah, i use two monitors and it always opens on my left monitor after i just had imageGlass open on my right monitor.

**Comment by fire-eggs** [comment]
Fixed in ImageGlass Moon.

**Comment by xmha97** [comment]
Thanks <3

**Comment by d2phap** [comment]
Deployed to https://imageglass.org/moon
