### ISSUE TITLE
it's really support tiff or tif?why this awesome tool can not open my tiff file,but i can open it in qupath

### ISSUE THREAD

**Issue by nipeone** [d2phap/ImageGlass#777]
can this awesome tool handle deep zoom file?

**Comment by d2phap** [comment]
You should attach your TIFF file.
Also, don't clear template when creating issue.
Thank you

**Comment by fire-eggs** [comment]
If we're talking about the type of TIFF files supported by qupath, I'd strongly suggest they're really out-of-scope for ImageGlass. 

There are a set of sample OME-TIFF files available [here](https://downloads.openmicroscopy.org/images/OME-TIFF/). A random sampling suggests these files are in the 100+ megabyte size range. They are not intended to be loaded all-at-once into memory, which is in direct conflict with the ImageGlass operational model.

Their use is heavily dependent on OME-TIFF specific metadata support. So unless or until ImageMagick provides all this OME-TIFF specific support, ImageGlass will not.

**Comment by d2phap** [comment]
@fire-eggs answered this.

**Comment by nipeone** [comment]
> If we're talking about the type of TIFF files supported by qupath, I'd strongly suggest they're really out-of-scope for ImageGlass.
> 
> There are a set of sample OME-TIFF files available [here](https://downloads.openmicroscopy.org/images/OME-TIFF/). A random sampling suggests these files are in the 100+ megabyte size range. They are not intended to be loaded all-at-once into memory, which is in direct conflict with the ImageGlass operational model.
> 
> Their use is heavily dependent on OME-TIFF specific metadata support. So unless or until ImageMagick provides all this OME-TIFF specific support, ImageGlass will not.

thanks for your suggestions,i mean that this tool can support deep zoom file,not only tiff
