### ISSUE TITLE
CMYK Rendering problem with latest version (7.6.4.30)

### ISSUE THREAD

**Issue by psychosys** [d2phap/ImageGlass#779]
### System information:
 - Windows OS version:  10
 - ImageGlass version: 7.6.4.30

### To Reproduce
1. Open a CMYK File

### Actual behavior:
New version doesn't render the CMYK file correctly .. switched many color profiles and still the color is washed out

### Expected behavior:
Render the CMYK file correctly

### Screenshots:
CMYK RENDERED BY IMAGEGLASS
![1](https://user-images.githubusercontent.com/58204209/81339980-09537e80-907d-11ea-9fc2-f727e0152846.PNG)

CMYK TRUE COLOR
![2](https://user-images.githubusercontent.com/58204209/81339982-09ec1500-907d-11ea-97ae-3e2bf5a0ea2a.PNG)

### Additional context:
as I see there are some improvements to load the heavy images faster but new version is unable to show the CMYK file correctly I switched all the available color profiles in ImageGlass and I even disabled it but still doesn't show the correct picture .. older versions show the image correctly but those are a little slow 

even expensive applications like ACDSee are unable to load the CMYK files so this is not a big deal but the only weakness is the high resolution images load very slowly and I believe it is because the program is written with C#

**Comment by novodantis** [comment]
Assuming this is the same bug, but am seeing full-black rendering as white on a cmyk jpg. Both Chrome and Windows Photo Viewer show CMYK jpg as intended (as it appears in the paint program, on the left)
![imageglassBug](https://user-images.githubusercontent.com/6184548/85372179-602bef00-b529-11ea-8477-85864be989c1.jpg)

**Comment by d2phap** [comment]
Can you share the file, thanks

**Comment by novodantis** [comment]
![AlisonLetterbook-Z](https://user-images.githubusercontent.com/6184548/85637435-15ba8780-b67b-11ea-97f3-67cf45bc1cfe.jpg)
 Apologies for the delay

**Comment by fire-eggs** [comment]
I think IG needs to upgrade to the latest Magick.NET:
[7.20.0.1 release](https://github.com/dlemstra/Magick.NET/releases/tag/7.20.0.1)

**Comment by fire-eggs** [comment]
Issue #796 may be related?

**Comment by d2phap** [comment]
Yes, tried with the latest build, it's fixed: https://imageglass.org/moon

![image](https://user-images.githubusercontent.com/3154213/87216609-d9be3c80-c373-11ea-8b6f-597455d187bf.png)

**Comment by pinguluk** [comment]
I think have the same issue with this image:

https://cdn.shopify.com/s/files/1/0603/5167/6609/products/PagesfromIDFpositionpaperonsupportingthenutritionalneedsofchildren.jpg?v=1678353486

If you open the link in Chrome and save it (as .jpg) then open in ImageGlass, it will display like this:

**Chrome**
![image](https://user-images.githubusercontent.com/16257821/225075606-6d35cbf0-3ef5-4aac-90f3-33e0231d18aa.png)

**ImageGlass**
![image](https://user-images.githubusercontent.com/16257821/225075709-f4d912ee-9add-4b48-b6d1-c156cba2e6f3.png)

And if you open the image in Chrome (not from the link), it will be displayed like on ImageGlass.
![image](https://user-images.githubusercontent.com/16257821/225076252-0de84cf5-8e26-418b-aa38-f63d2ee1fd95.png)


But if you open the image in Paint, it will be displayed like original one
![image](https://user-images.githubusercontent.com/16257821/225076186-96b0c284-8486-4471-8899-582ca943ac04.png)
