### ISSUE TITLE
Implement free panning

### ISSUE THREAD

**Issue by lapiroman** [d2phap/ImageGlass#780]
It Would be great to add panning beyond image edges. It's very usefull when you need to closely look at the edges or corners of an image. 

https://i.imgur.com/TmTzjnL.jpg 
![image](https://user-images.githubusercontent.com/3154213/139782171-9847b637-1d27-49bd-a60d-63f85d1bcaef.png)

How it should work  https://i.imgur.com/P3PCfbz.jpg

![image](https://user-images.githubusercontent.com/3154213/139782178-fde3d9ad-1bec-4bcd-b68e-272f5615c427.png)

**Comment by d2phap** [comment]
Duplicated of #651
