### ISSUE TITLE
Unhandled exception when saving after pasting image

### ISSUE THREAD

**Issue by Bone008** [d2phap/ImageGlass#782]
### System information:
 - Windows OS version: Win10
 - ImageGlass version: 7.6.4.30 Portable

### To Reproduce
1. Copy a base64-encoded image string from browser or some other raw image data (e.g. from Snipping Tool, Photoshop, ...)
1. Open empty ImageGlass *without* "Show welcome picture" enabled.
1. Hit Ctrl + V to paste image.
1. Hit Ctrl + S to try to save image.

### Actual behavior:

Unhandled exception occurs:

```
System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.
Parameter name: startIndex
   at System.String.Substring(Int32 startIndex, Int32 length)
   at ImageGlass.frmMain.<mnuMainSaveAs_Click>d__133.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

### Expected behavior:

Save dialog should open and allow saving the image.

### Additional context:

Works fine when "Show welcome picture" is enabled in settings, most likely because the filename "default.jpg" is then present. Without it, the filename is empty, probably what causes the exception :)

**Comment by d2phap** [comment]
Thanks @Bone008 
Confirm the bug

**Comment by d2phap** [comment]
This bug is fixed in IG Moon: https://imageglass.org/moon

**Comment by Bone008** [comment]
Thanks a lot for the fix!
