### ISSUE TITLE
JP2 (JPEG 2000) file type support

### ISSUE THREAD

**Issue by xmha97** [d2phap/ImageGlass#785]
Hello @d2phap 
ImageGlass is now able to view JP2 files.
But by default, no.

You must add ".jp2" as a supported ImageGlass file type in the settings (settings, "File Type Associations"). Restart ImageGlass.
You should now be able to view JP2 files using ImageGlass.

**Comment by d2phap** [comment]
Thank you for the info.
I will add `jp2` by default in future release.

Btw, you don't need to restart IG when making any change in Settings.

**Comment by xmha97** [comment]
> 
> 
> Thank you for the info.
> I will add `jp2` by default in future release.
> 
> Btw, you don't need to restart IG when making any change in Settings.

OK, Thanks 😍

**Comment by d2phap** [comment]
Added this to built-in extensions group
