### ISSUE TITLE
URL (Internet Shortcut) file type support

### ISSUE THREAD

**Issue by xmha97** [d2phap/ImageGlass#787]
Hello Phap
Sometimes when I drag and drop a picture from Firefox to desktop, Firefox saves this picture as URL format!
[Sample.zip](https://github.com/d2phap/ImageGlass/files/4708620/Sample.zip)
Please add support for the *.url extension.
Thanks.

**Comment by fire-eggs** [comment]
To be precise: this is not a URL, but a [data URI](https://css-tricks.com/data-uris/).

**Comment by d2phap** [comment]
I will close this as not planned
