### ISSUE TITLE
CR3 file type support (canon eos raw) [feature request]

### ISSUE THREAD

**Issue by lessload** [d2phap/ImageGlass#788]
New RAW format of canon camera now is .CR3
It would be so good if  this app support it.
.
but it seem hard.
here is some detail about it.
https://github.com/lclevy/canon_cr3

**Comment by d2phap** [comment]
IG mainly supports the formats of MagickImage

**Comment by d2phap** [comment]
Hi @lessload 

Today I have time to look at this ticket again, and yes, ImageGlass 7.6 supports CR3 file.
What you need to is adding `.cr3` extension in Settings dialog:

![image](https://user-images.githubusercontent.com/3154213/87216733-f6a73f80-c374-11ea-86ab-5c83a92820de.png)


![image](https://user-images.githubusercontent.com/3154213/87216706-c5c70a80-c374-11ea-957d-76b6c61fde14.png)
