### ISSUE TITLE
How to disable slideshow?

### ISSUE THREAD

**Issue by 07416** [d2phap/ImageGlass#789]
### System information:
 - ImageGlass version: 7.6

### Questions
Can the slideshow feature be disabled entirely? Currently I only know how to increase the interval in settings > image.

**Comment by fire-eggs** [comment]
You can customize the toolbar to remove the slideshow button. Otherwise, no, you cannot disable the menus / shortcuts which invoke a slideshow.

**Comment by 07416** [comment]
I've been surprised that the slideshow is enabled by default and can't be truly disabled. I'm used to F11 enabling fullscreen and nothing more.

ImageGlass was otherwise a dream come true.

**Comment by fire-eggs** [comment]
Perhaps I misunderstood - are you saying that:
1. You run imageglass to view an image
2. IG immediately starts playing a slideshow

If so, then that is a bug!

Does the slideshow behavior depend on how you run ImageGlass? E.g. double-click an image file vs using the "open" menu in Imageglass?

**Comment by 07416** [comment]
> 
> 
> In ImageGlass:
> F11 is "slideshow".
> Alt+Enter is "full screen".
> 
> It is unfortunate that ImageGlass' key mapping is different from other apps.

Thank you. Since Alt + Enter doesn't enable full screen view (the dock remains shown), I'll leave this issue open.

**Comment by d2phap** [comment]
@07416 
Can you share your screenshot about:
> Since Alt + Enter doesn't enable full screen view (the dock remains shown)

I don't know the "dock" you mean.
Thanks

**Comment by fire-eggs** [comment]
"Dock" is referring to the toolbar, I assume.

**Comment by d2phap** [comment]
@07416 
It's the expected behaviour,
Full screen will expand the window to fit the screen, and hide Windows title bar.
