### ISSUE TITLE
Settings on a 4k monitor

### ISSUE THREAD

**Issue by saulob** [d2phap/ImageGlass#793]
### System info:
ImageGlass version: 7.6.4.30
OS version: Windows 10
Theme: 2017 (Light Gray)

### Actual behavior:
Settings is all messed up on a 4k screen

### Other info:
I'm using an 4k monitor
Display resolution 3840x2160
Scale and layout 300% (Recommend by Windows)

### Screenshots:
![2020-06-06 12_20_27-Settings](https://user-images.githubusercontent.com/3660977/83948038-16d16500-a7f1-11ea-86af-218b44714d8d.png)

![2020-06-06 12_27_53-_new 2 - Notepad++](https://user-images.githubusercontent.com/3660977/83948060-2cdf2580-a7f1-11ea-97d9-da6b9f230279.png)

**Comment by d2phap** [comment]
Hi @saulob 
Could you help to test the latest build of ImageGlass Moon if this issue fixed:
https://imageglass.org/moon/

Thanks!

**Comment by saulob** [comment]
Testing now... 

Strange thing, the Check for update did not work 

![2020-10-17 14_52_05-Check for update](https://user-images.githubusercontent.com/3660977/96349812-5e61da80-1088-11eb-808c-56beacfc3c98.jpg)

**Comment by saulob** [comment]
Did not work. Same problem :(

![2020-10-17 15_09_29-About](https://user-images.githubusercontent.com/3660977/96350182-e77a1100-108a-11eb-9e6c-d53bc45edb6d.jpg)
![2020-10-17 15_09_53-](https://user-images.githubusercontent.com/3660977/96350183-e8ab3e00-108a-11eb-9fef-aa56daf62521.jpg)

**Comment by d2phap** [comment]
This issue is fixed in [ImageGlass 9.0 beta 5](https://github.com/d2phap/ImageGlass/releases/tag/9.0.5.726)
