### ISSUE TITLE
I wish ImageGlass launch times were faster

### ISSUE THREAD

**Issue by timmay7** [d2phap/ImageGlass#794]
I switched to ImageGlass from Irfanview because I wanted a free image viewer that could be used for commercial purposes. But the one improvement I'd like to see is for ImageGlass to **launch just as fast**.

I'm on a Core i5 2500K with a Samsung 830 SSD, and there's a very noticeable difference between the two apps from the moment I double click on an image to open it, and the moment the image is displayed within the respective apps.

Apart from my one main criticism, I think you've created a great app.

**Comment by unquietwiki** [comment]
@timmay7 #773 might help with this?

**Comment by d2phap** [comment]
Slow launching for first time is a well known issue of .NET, I have tried compiling to the native image in the recent versions of IG, but still have lots of work to do.

**Comment by fire-eggs** [comment]
Unfortunately, IG does not display the first image until it "finds" all the images. So depending on your directory setup, and your IG settings, IG can take a long time to show the first image.

For "fastest" behavior, I turn off "Find images in child folder" and use "sort by name". These are the settings which match Irfanview - you have to manually change the sort order in Irfanview, and Irfanview doesn't scan child folders.

Accessing files across a network will take longer than a local folder.

[This might be a case of "perceived" performance. Ideally, IG should display the double-clicked image while it searches for, and sorts, images in the background.]

**Comment by timmay7** [comment]
@fire-eggs My settings in IG are already set as you described in your post. It's still noticeably slower than Irfanview.

Even when I test the initial startup times by opening an image in a folder that contains **only** that image, IG lags behind Irfanview in performance.

**Comment by d2phap** [comment]
> Unfortunately, IG does not display the first image until it "finds" all the images. So depending on your directory setup, and your IG settings, IG can take a long time to show the first image.

Improved the loading time of the first image in folder (#976)

**Comment by dreaddr** [comment]
Can this app just have an option of running in the background? It takes so much of time compared to other image viewers (Irfanview... and even MS Photos at times) and time is critical.

**Comment by unquietwiki** [comment]
@dreaddr @d2phap I can already see how that might work. Start the program as a taskbar item, and make async window startups. There's a way to async start for console apps as of C# 7.x; not sure how that is supposed to work for Forms or WPF apps in later versions.

- https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7
- https://docs.microsoft.com/en-us/archive/msdn-magazine/2015/november/asynchronous-programming-async-from-the-start
- https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/

**Comment by mhtvsSFrpHdE** [comment]
Is there any possible about the Windows Defender? I just double-clicked my image and realize Windows Defender use 68% CPU for seven  seconds, then ImageGlass shows my image immediately after Windows Defender CPU usage are gone.

As a comparison, if I use Windows UWP Photo to open the image, the entire process can be done within one seconds until the first image shows.

**Comment by mhtvsSFrpHdE** [comment]
@timmay7 If anyone here are using Windows Defender or any other antivirus program, try add

```
C:\Program Files\ImageGlass\ImageGlass.exe
```

Or your ImageGlass.exe **FULL PATH** to Windows Defender or something else's process exclusions.

1. Windows Settings(UWP)
2. Update & Security
3. Windows Security
4. Virus & threat protection
5. Virus & threat protection settings
6. Manage settings
7. Scroll down to "Exclusions"
8. Add or remove exclusions
9. Add an exclusion
10. Process
11. Type in full path of ImageGlass.exe
12. Add

I guess Windows Defender do more work to looking at ImageGlass, because it's not a "signed" program ----if you right-click ImageGlass.exe and select "Run as administrator", and you haven't changed your default UAC settings, you will see a yellow permission prompt window says "Publisher: Unknown".

Find another exe, for example Windows notepad, notepad.exe or Firefox, firefox.exe, do the same operation, this time it's a blue window and says "Verified Publisher: Microsoft Windows" or "Verified Publisher: Mozilla Corporation".

A signed EXE has less chance to be "hacked by someone" than the official one. So Windows Defender could think these EXE is more trustable. If ImageGlass don't have a sign plan, tell users to add this EXE to antivirus program exclusion could give performance a boost.

**Comment by BugFixesAndPerformanceImprovements** [comment]
I don't believe Windows Defender has anything to do with it. 

I'm using a version of Windows 10 without Windows Defender and devoid of all Windows 10 bloat on a M.2 NVMe SSD and ImageGlass still takes marginally longer to open an image than for instance, [JPEGView](https://sourceforge.net/projects/jpegview), which is quite literally instant. 

Give it a try and you'll see what I mean.

**Comment by mhtvsSFrpHdE** [comment]
@BugFixesAndPerformanceImprovements Windows Defender do "has anything to do with it".

The thing is there are multiple factors can have an impact. My suggest could remove antivirus side effect.  
And yes, add it to whitelist do improved open speed, but still slower than other solution.

**Comment by mirh** [comment]
Other solutions are also scanned by defender (which can also be disabled), this doesn't make sense.

**Comment by shockergit** [comment]
> Slow launching for first time is a well known issue of .NET, I have tried compiling to the native image in the recent versions of IG, but still have lots of work to do.

please make v9 fast like honeyview

**Comment by arthurjosse** [comment]
I think this issue should be a top priority. I mean, it's the core functionnality, the most used "feature" of an image viewer: open an image to see it. Speed should be prioritized over features. I'm on a fast desktop (Win 10) and ImageGlass takes 2s to open an image from the File Explorer. In comparison, Honeyview, JPEGView, Irfanview, nomacs are near-instant.

**Comment by unquietwiki** [comment]
https://devblogs.microsoft.com/dotnet/announcing-net-6/?WT.mc_id=dotnet-35129-website is probably going to be a good fix for this situation.

**Comment by shockergit** [comment]
> https://devblogs.microsoft.com/dotnet/announcing-net-6/?WT.mc_id=dotnet-35129-website is probably going to be a good fix for this situation.

Does honeyview and irfanview use net?

**Comment by fire-eggs** [comment]
> Does honeyview and irfanview use net?

No, Xnview, Irfanview and HoneyView are not .NET programs.

**Comment by shockergit** [comment]
> > Does honeyview and irfanview use net?
> 
> No, Xnview, Irfanview and HoneyView are not .NET programs.

hope imageglass use Xnview

**Comment by fire-eggs** [comment]
> hope imageglass use Xnview

The licensing restrictions from Xnview explicitly preclude it from being used to implement an image viewer.

**Comment by unquietwiki** [comment]
Since a bunch of you all were annoyed here, I took some free time to come up with #1198 ; which I'm stuck on one error, else I think it'll build into something faster at least. I guess keep an eye on that for any development as I can actually finish & submit that.

**Comment by d2phap** [comment]
@timmay7 
You can try [ImageGlass Moon 9.0 beta 4](https://github.com/d2phap/ImageGlass/releases/tag/9.0.4.416), I believe it is much faster than other versions

**Comment by arthurjosse** [comment]
Well, I have tested the latest release of imageglass 9 and I can report really poor performance. I don't really see how the perf is improved from v8, I mean it still takes several seconds to simply open an image... I mean, how ?

**Comment by d2phap** [comment]
> Well, I have tested the latest release of imageglass 9 and I can report really poor performance. I don't really see how the perf is improved from v8, I mean it still takes several seconds to simply open an image... I mean, how ?

Please `simply` just use v8 or other apps you like, it's all my time and effort. That's why there are a lot of apps doing the same things (in different ways) and they exist together.

I have no further plan for this.

**Comment by arthurjosse** [comment]
The other parts of your app are nice, and I thank you for this. My criticism is not at all personal, it's just purely about the functionality of the program. An image viewer should open images and interact with them instantly, it's just the core feature of an image viewer, I don't see how it couldn't be "the plan".

**Comment by eebssk1** [comment]
Cons of the web technology, just use V8.

**Comment by philipp-fischer** [comment]
Oh my god! This is the solution! I literally had to wait 30 to 60 seconds for and image to open, switching from v9 to v8 it's one second.

**Comment by eebssk1** [comment]
It should be a lot faster if compiled to native(good feature of .net 8), and has webview procees preloaded at background.
However this will indeed consume some resources constantly/infinitely that I doubt any people will happy with this since this is just a damn photo viewer....

**Comment by philipp-fischer** [comment]
But how does that explain over 30 seconds wait time?

**Comment by eebssk1** [comment]
> But how does that explain over 30 seconds wait time?

Maybe Hardware acceleration has something to do with this on your machine since it's the most notable change?

I don't have this issue and V9 actually start a bit faster at subsequent launch than V8.

(I still use V8 though)
