### ISSUE TITLE
Only portions of an image show

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#796]
[imageglass problem image file.zip](https://github.com/d2phap/ImageGlass/files/4758785/imageglass.problem.image.file.zip)

### System information:
 - Windows OS version: Windows 10
 - ImageGlass version: 7.6.4.30

### To Reproduce
Note: originally reported in Google groups.

The JPG image, exported from Adobe Illustrator, shows in IG with portions blank.

Manifests with 7.6.4.30/Win10, and recent dev.

Does NOT manifest with 7.5.1.1/Win10. Does NOT manifest with any IG/Win7.

### Actual behavior:
Portions of the image are blank.

### Expected behavior:
The entire image should display.

**Comment by unquietwiki** [comment]
@fire-eggs I think #811 fixed this. Seems fine for me.

**Comment by fire-eggs** [comment]
Righto I'll take a look!

**Comment by d2phap** [comment]
It seems even worse with the latest Magick.NET

![image](https://user-images.githubusercontent.com/3154213/87215540-16853600-c36a-11ea-9283-71426e60939f.png)

**Comment by unquietwiki** [comment]
@d2phap the JPG, I saw the difference. I didn't even realize the program could open AI files; it wasn't coming up in my thumbnail list.

**Comment by d2phap** [comment]
Ah i see, then the latest Magick.NET fixes the JPG file. It also seems a bit faster.
![image](https://user-images.githubusercontent.com/3154213/87216538-3c630880-c373-11ea-8a8f-1f96337fb002.png)
