### ISSUE TITLE
System.Drawing: Parameter is not valid

### ISSUE THREAD

**Issue by Qwerty-Space** [d2phap/ImageGlass#798]
### System information:
 - Windows OS version: 10
 - ImageGlass version: 7.2.4.30_x64 portable

### To Reproduce
1. Open large image, 30,000x30,000

### Actual behavior:

![image](https://user-images.githubusercontent.com/6967592/84582714-83e38c80-ade7-11ea-97b1-6d2a70a3b8a4.png)

### Additional context:

The image is a very large JPEG

**Comment by d2phap** [comment]
Currently ImageGlass cannot handle very large image https://github.com/d2phap/ImageGlass/issues/272#issuecomment-348381055

**Comment by Qwerty-Space** [comment]
Unfortunate, but thanks

**Comment by fire-eggs** [comment]
May I ask where you are finding/making such large images? The largest I've been able to find is only 20Kx20K ...

Thanks!

**Comment by Qwerty-Space** [comment]
> 
> 
> May I ask where you are finding/making such large images? The largest I've been able to find is only 20Kx20K ...
> 
> Thanks!

It's a render of our entire Minecraft server

**Comment by d2phap** [comment]
@fire-eggs 
I found this link contains quite a lot of super high resolution image (up to 100k px). https://commons.wikimedia.org/wiki/Commons:Very_high-resolution_file_downloads

Anyway, I am closing this ticket here and let's just refer to #272
