### ISSUE TITLE
[Feature request] Anti-aliasing when scaling

### ISSUE THREAD

**Issue by TheCGDF** [d2phap/ImageGlass#799]
Raw Image:
![ミカピカゾ 花少女](https://user-images.githubusercontent.com/17256673/84954303-1b224a00-b130-11ea-9fe4-6d80f0c2c786.png)

Scale to 150%
Left: Photoshop  Right:ImageGlass
(both of them are 150%)
![ImageGlass_x11uY1XdLc](https://user-images.githubusercontent.com/17256673/84954860-2629aa00-b131-11ea-8221-ebbc78028f0d.jpg)

There is obvious difference between them. Photoshop is much more smooth.
I tried some other image viewer programs, they don't have this problem.

### Additional context
Windows 10.0.17763.1039
Resolution: 3840x2160
DPI: 225%
ImageGlass: 7.6.4.30 [Portable]

**Comment by d2phap** [comment]
Hi @TheCGDF 

You can try changing the "Zoom optimization" in settings

![image](https://user-images.githubusercontent.com/3154213/85033260-57e35500-b1b3-11ea-92b2-89c141b42412.png)

**Comment by TheCGDF** [comment]
> Hi @TheCGDF
> 
> You can try changing the "Zoom optimization" in settings
> 
> ![image](https://user-images.githubusercontent.com/3154213/85033260-57e35500-b1b3-11ea-92b2-89c141b42412.png)

Thank you. It works.
