### ISSUE TITLE
Magic.Net-Q16-AnyCPU: The type initializer for 'NativeMagickSettings' on 400 pc

### ISSUE THREAD

**Issue by poweruser2** [d2phap/ImageGlass#800]
### System information:
 - Windows OS version: Windows 10 Pro X64 (18363.900)
 - ImageGlass version: 7.6.4.30 x64 version

### To Reproduce
1. Log in as guests user
2. Open ImageGlass 
3. Choose open file
4 Open file

### Actual behavior:

Imageglass is not opening pictures can't open any type, Imageglas lost navigation buttons, 
Image glass is showing error: ImageGlass cannot open this picture because file appears to be damaged, corrupted or not supported. Magic.Net-Q16-AnyCPU: The type initializer for 'NativeMagickSettings' threw an exception.
### Expected behavior:

Correct work of  Imageglass program for any user account type administrator, user or guest account for Windows.

### Screenshots:

https://ibb.co/b2hmsCg
<a href="https://ibb.co/b2hmsCg"><img src="https://i.ibb.co/s6SRKNv/error.png" alt="error" border="0" /></a>

### Additional context:

We have deployed in our school for education for students in computer classes. 
As picture viewer, problem has more than 400 computers.
Problem is the same on all computers. The same bug persists on 7.6.4.30, problem persists only on not administrators account.
All other programs running on limited or guests account, like Firefox, 7zip, VLC and others. Problem exists only in Imageglass.

Thanks for support.

**Comment by d2phap** [comment]
Hi @poweruser2 

- What version of .NET are you using? It should be v4.7.1.
- Also make sure you download and install the correct installer for Windows 32/64 bit

**Comment by poweruser2** [comment]
Hi, Phap Dieu Duong !
Thanks for Your response.

We use version 4.8.x How i googled. Net framework versions is compatible with older versions (backward compatible).
"What version of .NET are you using? It should be v4.7.1."

MSBuild.exe -version
Microsoft (R) Build Engine version 4.8.3752.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.4.8.3752.0

Also make sure you download and install the correct installer for Windows 32/64 bit
On 64 bit system we use 64 installer, on 32bit system.

**Comment by fire-eggs** [comment]
The build engine is not the framework. It states right in your output from `MSBuild.exe -version` that you have .NET Framework Version 4.0, not the required 4.7.1. So you'll want to double-check.

[Here is a link](https://smartdoc.zendesk.com/hc/en-us/articles/205232308-How-to-check-your-NET-Framework-version) describing one way to identify the installed .NET Framework version.

Phap is referring to the .NET Framework installer when he mentions using the correct installer. [Here is the link](https://dotnet.microsoft.com/download/dotnet-framework/net472) to download .NET 4.7.2 - you want to download the "4.7.2 Runtime". There is a link at the bottom of  the page for 4.7.1 if you prefer that one.

The last version of ImageGlass which targeted the .NET 4.0 Framework was V4.5.11.27.

**Comment by fire-eggs** [comment]
Frankly, the error you are seeing is probably due to a problem in your Guest account configuration. You state that ImageGlass works for Admin account, which really suggests you
have the correct .NET Framework installed.

It seems most likely that you need to fix the rights for your Guest account so that Guest users have full access to the ImageGlass install folder and sub-folders (for the navigation buttons, etc).

**Comment by unquietwiki** [comment]
@d2phap when I was working on #811 , I had to update the library for this, and that they had changed the behavior on loading bitmaps to require an extra command. It's possible this issue may or may not remain with that update?

**Comment by d2phap** [comment]
I saw it! I will push a new IG Moon version soon so @poweruser2 can test if it still persists.
But as Kevin said, it might be due to the rights

**Comment by poweruser2** [comment]
> 
> 
> I saw it! I will push a new IG Moon version soon so @poweruser2 can test if it still persists.
> But as Kevin said, it might be due to the rights

I tried new  ImageGlass_7.6.7.12_x64.zip
Size: 13.23 MB
Release date: Jul 12 2020 11:57 PM
 Problem still persists.

[url=https://ibb.co/QcTXcfD][img]https://i.ibb.co/mB2SBGN/error.png[/img][/url]

"It seems most likely that you need to fix the rights for your Guest account so that Guest users have full access to the ImageGlass install folder and sub-folders (for the navigation buttons, etc)."
I put Full access to everyone to Imageglass folder. The same.


Sorry for late response on ticket i was out on vacation.

**Comment by d2phap** [comment]
It's been some time, I will just close this. If you still encounter this issue on IG v9, feel free to let me know
