### ISSUE TITLE
Expand Keyboard Settings to Include Next Page / Previous page - also, Gif page control tweak

### ISSUE THREAD

**Issue by Davexx** [d2phap/ImageGlass#802]
### Is your feature request related to a problem? Please describe.
It would be nice to expand the keyboard controls for navigating "pages" in image files, like .ico, .cur, .gif files.

### Describe the solution you'd like
Under Settings > Keyboard > Add a drop-down option for "Previous / Next PAGE" so users can add faster access to the page controls

### Describe alternatives you've considered
Navigating pages by using the CTRL + left/right arrow, or CRTL + Home/End works perfectly fine.  This is just an extra ease-of-control option so, for example, you can navigate a series of icons using the left right arrows and then check their internal pages using the up/down arrows.  Super fast for the user.

### Additional context
For Gifs, it would be nice to use the "Previous / Next PAGE" control options for stepping through the internal pages/frames of the Gif file.  Currently when the animation is playing the "Previous / Next PAGE" controls do not stop the animation and allow you to step through the pages/frames one-by-one.  If you stop the animation and try to use the "Previous / Next PAGE" controls, it just starts the animation again.  In summary, being able to step through the Gif pages one-by-one would be super handy rather than having to extract the pages to see a specific frame.

Thank you!

**Comment by trickshooter** [comment]
Urgently needed here, too!

Wish list:
Configurable PageUpDown = PrevNext**Page**
Desired entry for "igconfig.xml" reading as follows:

(...)
\<Item key="KeyComboActions" value="LeftRight:PanLeftRight;**PageUpDown:PrevNextPage**;SpaceBack:PauseSlideshow;UpDown:PanUpDown;" />
(...)

**Comment by d2phap** [comment]
in v9, user can override the default hotkeys using `igconfig.json` file:

https://github.com/d2phap/ImageGlass/discussions/1702#discussioncomment-7660806
