### ISSUE TITLE
Feature to assign keys of our liking to the navigation functions.

### ISSUE THREAD

**Issue by KaveeHana** [d2phap/ImageGlass#803]
### Is your feature request related to a problem? Please describe.
Can't navigate easily using the left hand. (The right hand is doing it's business below the keyboard, if you know what I mean)

### Describe the solution you'd like
Ability to assign keys of our liking to the previous image, next image function

### Describe alternatives you've considered
Make it easier to navigate easier using the left hand.

**Comment by fire-eggs** [comment]
Duplicate of issue #729
