### ISSUE TITLE
Animated webp files do not play.

### ISSUE THREAD

**Issue by usuario4444** [d2phap/ImageGlass#804]
### System information:
 - Windows OS version: Windows 7 Microsoft Windows [Versión 6.1.7601]
 - ImageGlass version: Version: 7.6.4.30 [Portable]

### To Reproduce
1. Open any Animated Webp file, animation won't play.
2. 
3. 
4. 

### Actual behavior:

Animated Webp files don't play, only first frame is shown.

### Expected behavior:

Animated Webp files should play automatically or by pressing Ctrl-space (right?). GIFs files play without problem by the way.

### Additional context:

Only first frame is shown.

**Comment by d2phap** [comment]
Thanks @usuario4444 but IG doesn't support animating WEBP yet. 
Merge this to #508
