### ISSUE TITLE
Make "Use Windows File Explorer sort order if possible" work with other file explorers like Directory Opus

### ISSUE THREAD

**Issue by moritz1000** [d2phap/ImageGlass#807]
### Is your feature request related to a problem? Please describe.
If you use an alternative file explorer like [Directory Opus](https://www.gpsoft.com.au/) the feature "Use Windows File Explorer sort order if possible" does not work _(under Settings > Image)_. I would assume that people who install an alternative / more powerful image viewer are also more likely to be the same people who download alternative / more powerful file explorers.

### Describe the solution you'd like
Integrate the file sorting from other file explorers into ImageGlass.

### Describe alternatives you've considered
Sorting images in other file explores like Directory Opus should be transferred into the order in which images are shown in ImageGlass.

**Comment by d2phap** [comment]
Hi @moritz1000 

We can develop the feature "**Use Windows File Explorer sort order if possible**" thanks to Windows API. But the third-party app like Directory Opus does not provide API so it's impossible to know the sort order.

**Comment by moritz1000** [comment]
Thank you for your response.
I made a post on the Directory Opus forum and got this response:

> If they can tell of which API they're using, or which source file to look at, we might be able to implement the same one in Opus. (Although it can be complicated sometimes, as Opus windows can contain multiple folders/tabs, and can launch programs on files that aren't even in the current folder.)

Would it be possible for you to answer this question?

**Comment by d2phap** [comment]
The idea is Opus provides a command to retrieve the sort order (or even all the items in the list). For example:

#### Get sort order
```bash
# Command to get the sort order of the given directory
# It should return an integer corresponding to the sort order:
#     0: error
#     1: By name ascending
#     2: By name descending
#     3: By extension ascending
#     4: ...and so on...
opus.exe get-sort-order "C:\My photos\"
```

#### Get items in correct order
```bash
# Returns
#    0: error
#    1: successful
opus.exe extract-files "C:\My photos\" "C:\all-photos.txt"
```
This command lists all of the files in the given folder into a text file. By this way, it should also provides a flag option to include the hidden files in the result.

**Comment by LeoDavidson** [comment]
Hi, I'm one of the Opus developers. -- We were hoping you could tell us the API you're currently using to get this information from Explorer, or point us to the relevant source file to see what you're doing. We may then be able to emulate that API so that you don't need to make any changes at all.

**Comment by fire-eggs** [comment]
The functionality is implemented by using various Windows OLE interfaces: basically, the code iterates through all active Explorer windows, looking for the one which is currently showing the target path. It then determines the last sorted column in that Explorer view.

Raymond Chen shows an example here:
https://devblogs.microsoft.com/oldnewthing/20151228-00/?p=92721

The guts of our implementation can be found here:
https://github.com/fire-eggs/ExplorerSortOrder/blob/master/Dll1/Doit.cpp

Start with `GetExplorerSortOrder`.
