### ISSUE TITLE
SVG not generated in the windows pane preview 

### ISSUE THREAD

**Issue by neuropass** [d2phap/ImageGlass#809]
Windows 10, preview pane shows black background and fails to show the svg preview.

see:
https://gyazo.com/514ca69facc0886cf69183523714b4eb

**Comment by d2phap** [comment]
Hi @neuropass 

ImageGlass does not come with the preview panel support for File Explorer.
This SVG preview might come with Windows 10 Creators Update or from the Windows extensions with **limited** support.
https://docs.microsoft.com/en-us/windows/win32/direct2d/svg-support

This is not related to IG.
