### ISSUE TITLE
Window scales too small for tiny image + inconsistent scaling for larger image in loop

### ISSUE THREAD

**Issue by zEdS15B3GCwq** [d2phap/ImageGlass#814]
### System information:
 - Windows OS version: Win 10 x64 Pro 1909
 - ImageGlass version: 7.6.4.30

### To Reproduce
1. have 2 images in folder, one very small (10x10 red filled square here, first image), and another larger one (1920x1080 in my case; original not uploaded)
2. set IG scaling/zoom to "scale to fit" and "window fit"
3. cycle between images
4. profit

### Actual behavior:
Problem A: the window scales to a too small size for the tiny image - only the IG icon, minimize and close buttons are visible, the toolbar is unusable and the picture itself is hidden.
Problem B: inconsistent scaling - cycle between the images, and the larger image appears once smaller, once in full size. Cycling can be done in any way - loop in one direction, or up/down/up/down.
See uploaded images 2 3 and 4; in case of looping, IG would display them in this order: 2, 3, 2, 4, 2, 3, 2, 4 ...

### Expected behavior:
1. I'd expect IG to have a 'minimum' window size when scaling, which is still usable and shows the image.
2. Scaling should be consistent, the large image should appear properly scaled and the same size, always.

### Screenshots:
tiny image 10x10
![red filled rect 10x10](https://user-images.githubusercontent.com/58502181/86513152-de01cb80-be42-11ea-9130-4dff245c2cdb.png)
loop order (pressing next image repeatedly)
1 & 3 (red square not even visible)
![ig1](https://user-images.githubusercontent.com/58502181/86513188-27521b00-be43-11ea-9d66-10eff441f3a8.png)
2 (large image first appears incorrectly scaled, i.e. much smaller)
![ig2](https://user-images.githubusercontent.com/58502181/86513194-33d67380-be43-11ea-89e9-ce5c1c199086.png)
4 (large image correctly scaled)
![ig3](https://user-images.githubusercontent.com/58502181/86513197-36d16400-be43-11ea-9680-f78a32b72740.png)

### Additional context:
Today was rainy?

**Comment by fire-eggs** [comment]
I've confirmed this issue. Note that the "scale to fit" part doesn't seem to matter, even with "Auto Zoom", I see the described behavior. I.e. this is a problem solely with "Window Fit".

**Comment by SylwesterZarebski** [comment]
Confirmed with enabled or disabled Auto zoom.

**Comment by d2phap** [comment]
fixed in v8.2
