### ISSUE TITLE
Japanese language archive is broken?

### ISSUE THREAD

**Issue by tt4g** [d2phap/ImageGlass#817]
### System information:
 - Windows OS version: 1809
 - ImageGlass version: N/A

### To Reproduce

1. Download Japanese language file from https://imageglass.org/language/download/ja
2. Unzip `ja.zip`

### Actual behavior:

I can not unzip `ja.zip`.

### Expected behavior:

I will get language files.

### Screenshots:

None

### Additional context:

I try `unzip` command on bash provided by Git for Windows to expand `ja.zip`.
But `ja.zip` is can not unzip.

**Comment by d2phap** [comment]
ありがとう @tt4g 
I just rebuilt the translation. It should be working now.

**Comment by tt4g** [comment]
Thank you for quick response!
