### ISSUE TITLE
Feature Request / Idea: use SHIFT-NUM to move images to assigned folders; maybe open them too with ALT?

### ISSUE THREAD

**Issue by unquietwiki** [d2phap/ImageGlass#818]
The key assignment suggestion might conflict with #803 , else the idea here would be the following...

1. Define up to 10 locations to move files to with SHIFT + NUM.
2. Define up to 10 locations to open a directory with ALT + NUM.
3. GUI entry for registry/INI saving of the 10 locations in mind.

**Comment by unquietwiki** [comment]
@d2phap I can actually try working on this if you think it's worth doing. I know this would help me with sorting stuff.

**Comment by fire-eggs** [comment]
I'll be interested to see what you come up with. The main reason I still use XnView periodically is for precisely this purpose.

**Comment by unquietwiki** [comment]
@fire-eggs @d2phap one thing that I did think of: doing it this way would have to keep in mind the use of other keyboards that have different symbols for their 1-0 row. So the functionality could be done as menu items, and then keys bound by solving #803

**Comment by d2phap** [comment]
Similar to #1422, this feature can be done in v9 by creating an IG Tool which lets you to run script and assign hotkey.

Refer to https://github.com/d2phap/ImageGlass/issues/1419#issuecomment-1840508259, replace `xcopy` command with `move` command.
