### ISSUE TITLE
Slow when you use the next/previous buttons in folder with mixed JPEG/RAW. Prirotize the image that is actually selected rather than the one that was skipped.

### ISSUE THREAD

**Issue by ghost** [d2phap/ImageGlass#819]
When I just click on a jpeg image to view it directly its open very fast, but when I press next to view next one in the folder its very very slow. I think its because I shoot JPEG+RAW and when viewing images usually just dubble click next one to skip the raw and look at next JPEG. I think Imageglass keeps prossesing to show the RAW (Fuji losless compressed) finished because that got selected for a little split second, before it.

A sollution would be that when you press next before an image prossesing to view is finished, it just stops doing that and just do the one that is actually open at that moment, or at least put the one actually on screen in front and prioritized.

An work around would be an option that just turns off lossless compressed RAF image viewing as Windows photo viewers do it, and then just show a messalge of RAF image viewing is turned off in the settings instead or  something.

Right now Imageglass is unusable for me because of this, when this makes it so slow, I rather just open windows photo viewer or even photo editor program, if it wasnt I wouldnt becuase its great in other ways.

I dont know if bug or feature requrest is the correct option.

An related but different issue is that the time it takes to show a losless compressed RAF file is slow af, dont know if anything can be done with that tho, tho programs like Rawtherapee seem to be faster at it.
Also another issue I mentioed in another post.

**Comment by d2phap** [comment]
Should be fixed in v9
