### ISSUE TITLE
Bind 'Space' key as 'Show next image'

### ISSUE THREAD

**Issue by PSVortex** [d2phap/ImageGlass#821]
### Is your feature request related to a problem? Please describe.
No

### Describe the solution you'd like
Bind 'Space' key as 'Show next image'

**Comment by d2phap** [comment]
Hi @PSVortex 

You can find it in the Settings

![image](https://user-images.githubusercontent.com/3154213/87215517-cc9c5000-c369-11ea-9b19-a82780dfb413.png)
