### ISSUE TITLE
Remove Gradient Background Color When Next Picture/Previews Picture Button Pop Out

### ISSUE THREAD

**Issue by jonathanbayu** [d2phap/ImageGlass#825]
### Is your feature request related to a problem? Please describe.

No, but it is so distrubing

### Describe the solution you'd like

Remove Gradient Background Color When Next Picture/Previews Picture Button Pop Out

### Describe alternatives you've considered

Remove Gradient Background Color When Next Picture/Previews Picture Button Pop Out

### Additional context

look at the red circle, my picture become blurry because of gradient bakcground
![test](https://user-images.githubusercontent.com/45531864/87849185-bade1e00-c910-11ea-8227-1ef056dba72b.png)

**Comment by fire-eggs** [comment]
Now available in [ImageGlass Moon](https://imageglass.org/moon) : ImageGlass_7.6.8.30_x64.zip
