### ISSUE TITLE
Is there any way to truly rotate the image and keep the file size?

### ISSUE THREAD

**Issue by LaserLV52** [d2phap/ImageGlass#829]
### System information:
 - Windows OS version:  win10 1909
 - ImageGlass version:  7.6.4.30

### Questions
After I choose the "save the viewing image after rotating", the image only has an orientation tag in Exif profile and the file size will change from 8M to 38M.
This feature is friendly to professional applications, but can be a hassle to use on a daily basis. How can I do if I would like to save the truly rotated image and maintain the file size in a reasonable range. Can this feature be added in future updates? Thanks.

**Comment by d2phap** [comment]
Hi @LaserLV52 
IG is set to save the image as 100% quality by setting "quality" in Magick.NET library. In other apps (MS Paint,...) it's about 75-80%
I will add an option to change this value in the next release.

**Comment by LaserLV52** [comment]
> Hi @LaserLV52
> IG is set to save the image as 100% quality by setting "quality" in Magick.NET library. In other apps (MS Paint,...) it's about 75-80%
> I will add an option to change this value in the next release.

Very appreciate。Looking forward to the new version。
