### ISSUE TITLE
麻烦问一下，目前的软件，有滚轮控制缩放的功能吗？有的话他在哪里？

### ISSUE THREAD

**Issue by zslsycn** [d2phap/ImageGlass#830]
### System information:
 - Windows OS version: 
 - ImageGlass version:

**Comment by d2phap** [comment]
Hi @zslsycn 
Please post your question in English!

**Comment by fire-eggs** [comment]
The scroll wheel functionality is defined in the Settings Dialog, "Image" tab. The default functionality for the mouse scroll wheel is "Zoom".
