### ISSUE TITLE
theme problem

### ISSUE THREAD

**Issue by AndromedM31** [d2phap/ImageGlass#831]
### System information:
 - Windows OS version: 10 Pro latest update 
 - ImageGlass version: 7.6

### To Reproduce
1. i tried to download new themes and apply them..
2. i downloaded 2 themes. settings --> theme --> download themes --> Windows 10 Navy Blue (HiDPI)
3. i unzipped and moved the files  "C:\Program Files\ImageGlass\DefaultTheme"
4. i installed the themes..no problem but the themes didn't apply even i restart the app
5. i tried the same process to install the theme but this time from "theme folder" located "C:\Users\*******\AppData\Roaming\ImageGlass\Themes" but still didn't work

### Actual behavior:

it didn't work even after i restart the program

**Comment by fire-eggs** [comment]
I just confirmed I could download, install, and use the "Windows 10 Navy Blue" theme. So you'll have to provide more details.

Here are the steps I performed:
1. Downloaded theme from imageglass.org. This is a zip file.
2. Unpack the theme someplace. This is an igtheme file.
3. Using ImageGlass 7.6, go to settings, theme.
4. Click on "Install..." button, find the igtheme from step 2, select it. It should be "installed successfully", and appear in the list of installed themes.
5. Select the just installed theme.
6. Click "Apply theme" button. "Theme is applied successfully"
7. Save or Cancel out of Settings.

New theme takes effect.

**Comment by AndromedM31** [comment]
i think i made a mistake i was expecting the bar where the the pic address would change color same as the theme ..but no

**Comment by fire-eggs** [comment]
Having the theme change the title bar color is a feature which Phap has decided he will not implement [see issue #595].

**Comment by d2phap** [comment]
Dark mode for title bar is supported in v8.7.11.6. You may need to update your theme packs: https://imageglass.org/themes.

If you check the option `Show colour in Start, taskbar, action centre and title bar` in Windows Settings, the title bar will use the accent color.
