### ISSUE TITLE
ImageGlass unable to set file extensions

### ISSUE THREAD

**Issue by MT950** [d2phap/ImageGlass#832]
### System information:
 - Windows OS version: 1909 (OS Build 18363.720)
 - ImageGlass version: 7.6.4.30_x64

### To Reproduce
1. Install Image Glass
2. Go to Settings
3. Go to File Type Associations
4. Click Set as Default photo viewer...
5.) Optional: Open Windows Default Apps, click "Photo Viewer", ImageGlass will not be in the list, so no way to set it as default photo viewer.

### Actual behavior:
Error messages:
The specified registry key does not exist.
Unable to register file extensions for ImageGlass app
Attempted to perform an unauthorized operation.

### Expected behavior:
For file extensions to be set.

### Screenshots:
![image](https://user-images.githubusercontent.com/3154213/94412200-1730aa00-01ac-11eb-801f-fbbaa5322106.png)

![image](https://user-images.githubusercontent.com/3154213/94412209-1a2b9a80-01ac-11eb-8c08-66c0ddd7fac2.png)

![image](https://user-images.githubusercontent.com/3154213/94412217-1d268b00-01ac-11eb-8497-5f685158d68a.png)

**Comment by SaumitraVerma** [comment]
You can click on look for another app in pc as shown in image and select the main image glass executable i.e 
C:\Program Files\ImageGlass\ImageGlass.exe

<img width="235" alt="1" src="https://user-images.githubusercontent.com/46890315/89977761-96fcc680-dc89-11ea-9fa8-a433a39400df.png">

**Comment by d2phap** [comment]
Similar to #1360, it's fixed in [v9.0 beta 2](https://github.com/d2phap/ImageGlass/releases/tag/9.0.2.904)!
