### ISSUE TITLE
Request: Remove "ImageGlass" on the file type

### ISSUE THREAD

**Issue by miki-sakura** [d2phap/ImageGlass#833]
### System information:
 - Windows OS version: Windows 10 Home Single Language version 2004
 - ImageGlass version: 7.6.4.30 - 10th

### To Reproduce
1. Install Imageglass
2. Set Imageglass as Default Photo Viewer

### Actual behavior:

Instead of simply showing the photo file extension / type like before (jpg, png, etc.), it has "ImageGlass" appended to all photo file types.

### Screenshots:

Viewing by Group on Windows Explorer:
![filetype1](https://user-images.githubusercontent.com/7825053/89097425-67d89080-d411-11ea-8b12-d3449d43082f.JPG)
Upon checking the file properties:
![filetype2](https://user-images.githubusercontent.com/7825053/89097426-6909bd80-d411-11ea-9b84-32078c4a8cdd.JPG)

On regedit ("ImageGlass" is on all photo extensions associated with Imageglass on regedit):
![filetype3](https://user-images.githubusercontent.com/7825053/89097427-69a25400-d411-11ea-9101-b89144e0d792.JPG)

Editing the Value Data by removing "ImageGlass", and then restarting the computer resolves the issue. 
Would love it if the "ImageGlass" part can be removed to make photo file extensions be easier in reading and simpler.
![ft3](https://user-images.githubusercontent.com/7825053/89097629-3234a700-d413-11ea-905b-5b521c5b6def.JPG)

![ft1](https://user-images.githubusercontent.com/7825053/89097572-b2a6d800-d412-11ea-85f3-e8552ffbcc44.JPG)
![ft2](https://user-images.githubusercontent.com/7825053/89097573-b3d80500-d412-11ea-9b53-ac44508a1c6b.JPG)

**Comment by d2phap** [comment]
To delete all file type associations, you can open terminal and run:

```bash
C:\path\to\igtasks.exe delassociations
```

There is no direct way in UI yet. For more command lines, see https://imageglass.org/docs/command-line-utilities

**Comment by miki-sakura** [comment]
It just deleted the file associations..I still wanted the program to be used when opening all Image files. So I ended up associating the program to open pictures again.

Also, what happened is that all file types got "ImageGlass" appended to them again (I've manually removed all of them through regedit earlier, sample from above screenshots)

Can such be considered on a future release? Instead of having the registry value data for those folders be "ImageGlass <file type> File" (like I"mageGlass PNG File") can it be simply "<file type> File" instead (like "PNG File")?

**Comment by d2phap** [comment]
Hi @miki-sakura 
Sorry, I misunderstood.
This is requested at #610 for better sorting and grouping all image type

**Comment by miki-sakura** [comment]
Hi @d2phap, it seems that was indeed made with better sorting in mind.
Specifically, having all photo-files be sorted and grouped together. 

For example, a folder that has 3FR, DOCX, PNG:
1: Normal / Default group sort:
3FR
DOCX
PNG

vs 2: Group Sort through ImageGlass (# 610 )
DOCX
ImageGlass 3FR
ImageGlass PNG

I guess I have my own preference regarding sorting / grouping. And, I guess it depends on this community as to which way should be on future releases.

Sharing my workaround that suits my needs.
(need to change extension from ".txt" to ".reg" in order to import them to the registry..

[IG_REG_FileTypeDesc_VANILLA.txt](https://github.com/d2phap/ImageGlass/files/5010889/IG_REG_FileTypeDesc_VANILLA.txt) = Descriptions like "PNG File" (or windows default, if I'm not mistaken)
[IG_REG_FileTypeDesc_VLCstyle.txt](https://github.com/d2phap/ImageGlass/files/5010890/IG_REG_FileTypeDesc_VLCstyle.txt) = Descriptions like "PNG Image File (ImageGlass)" (patterned through VLC)

Would an option on the installation as to what file description type is preferred, be possible in a future release?

**Comment by mirh** [comment]
I can't really vouch on what's really the best and most frequent use case..
Though since it modifies the default OS behaviour, it sounds a bit like this should be disabled by default and only come through a checkbox.

**Comment by BlepBlep** [comment]
Still waiting for this to be implemented.


> I can't really vouch on what's really the best and most frequent use case.. Though since it modifies the default OS behaviour, it sounds a bit like this should be disabled by default and only come through a checkbox.

This is the best idea. It should NOT be default, and should be toggle-able.

**Comment by d2phap** [comment]
Implemented in [ImageGlass 9.0 RC](https://github.com/d2phap/ImageGlass/releases/tag/9.0.6.1008)

**Comment by BlepBlep** [comment]
> Implemented in [ImageGlass 9.0 RC](https://github.com/d2phap/ImageGlass/releases/tag/9.0.6.1008)

I cannot find this setting in 9.0 RC. All my files are still named "ImageGlass"

**Comment by d2phap** [comment]
You just press "Make default" button to set ImageGlass as default photo viewer, or using Main menu > Help > Set as default photo viewer, the file type description will be reset

**Comment by BlepBlep** [comment]
Yes, that makes ImageGlass the default viewer. But it does not remove the "ImageGlass" name on extentions

**Comment by ghost** [comment]
It's annoying, and takes up too much space. It's a PNG file, not an ImageGlass PNG file. Thanks miki-sakura for showing how to fix this in 2023...
