### ISSUE TITLE
cut, copy or paste is not working in Rename dialog "f2".

### ISSUE THREAD

**Issue by Disaeon** [d2phap/ImageGlass#834]
### System information:
 - Windows OS version: Windows 10 2004
 - ImageGlass version: 7.6.4.30

### To Reproduce
1. open image
2. press f2
3. cut, copy or paste text using ctrl+z, ctrl+x or and ctrl+c
4. not working

### Additional context:

work on 7.0.7.26
not work on 7.5.1.1 and 7.6.4.30

**Comment by d2phap** [comment]
Hi @Disaeon 

Thanks for reporting the issue. However, it's reported at #770 and fixed in IG Moon version.
You can download IG Moon at https://imageglass.org/
