### ISSUE TITLE
Mouse cursor doesnt work if Tooltip blinks - Define the Mouse Click Area ..

### ISSUE THREAD

**Issue by NR2014** [d2phap/ImageGlass#836]
### System information:
 - Windows OS version: Windows 10
 - ImageGlass version: 7.6.4.30

### To Reproduce
1. Enlarge the program
2. Get the mouse near the "Next" / "previous" buttons
3. You cant click if you have blinking "tooltip"

### Actual behavior:
The tool tip is disabled , still its showing when you dont place your mouse properly over the "NEXT" "PREVIOUS" buttons , or any button of that sort

### Expected behavior:
The tool tip shouldnt blink. Also the Cursor area needs to be enlarged so that program doesnt misread its position/box area.

### Screenshots:
adding a gif ...
![jHt5rDlKUa](https://user-images.githubusercontent.com/7801807/89812302-88b18c00-db5d-11ea-86e5-b22e1bdb24b7.gif)

**Comment by NR2014** [comment]
This doesnt happen when the program is run in a smaller window mode.. nor in full screen. It only happens when its in maxed window mode.

If the cursor is not in the middle of the button or when the tooltip is blinking , even if you clock the mouse , nothing happen. the program doesnt register the click. Also is there a way to disable that tooltip message ?

**Comment by d2phap** [comment]
Thanks for the info. There is no solution for disabling tooltip yet.

**Comment by NR2014** [comment]
Thanks , but i think something has to be done for "HIT BOX" area for these button. Even slight click away from the centre either activated the blinking tooltip or doesnt register the click at all.

Also i noted that on second click , it registers.

**Comment by fire-eggs** [comment]
See issue #634

**Comment by d2phap** [comment]
Fixed in IG Moon https://imageglass.org/moon

**Comment by NR2014** [comment]
Works wonderful. I simply replaced all the files from the zip to current location. Lost my settings.. but no problem.. will get it back.

The issue is resolved. Please while we are at it, give option to whether show "tooltip" or not. 
Thanks again for fixing it.

**Comment by d2phap** [comment]
@NR2014 

> Please while we are at it, give option to whether show "tooltip" or not.

You can set `IsHideTooltips` to `True` in `igconfig.xml` file. This is hidden option, not showing on UI yet.

**Comment by NR2014** [comment]
![notepad++_wEewlXmao6](https://user-images.githubusercontent.com/7801807/93042319-58816f80-f66c-11ea-8ba8-13add13e4f89.png)

I think i did it correctly.. still its showing tooltip ..

CMIIW.

**Comment by fire-eggs** [comment]
> I think i did it correctly.. still its showing tooltip ..

Yes, you have it correct. I have just verified that IsHideTooltips does stop showing tooltips for me.

What you need to do is make sure there is no second "IsHideTooltips" line in the XML file. Annoyingly, it overrides any earlier line, and is probably set False.

**Comment by NR2014** [comment]
Just checked , there is only one "IsHideTooltips" in the xml file.

**Comment by d2phap** [comment]
Added option in Settings to hide toolbar tooltips.
https://imageglass.org/moon

![image](https://user-images.githubusercontent.com/3154213/94580254-48909f00-02ac-11eb-80e3-8c4679b3de84.png)

**Comment by d2phap** [comment]
Fixed the known error mentioned above https://imageglass.org/moon
