### ISSUE TITLE
Clipboard not cleared after copy/paste

### ISSUE THREAD

**Issue by alexphiev** [d2phap/ImageGlass#838]
### System information:
 - Windows OS version: 10.0.18362
 - ImageGlass version: 7.6.4.30

### To Reproduce
1. Ctrl+C to copy X amount of images
2.  Go in a Windows folder
3.  Ctrl+V to paste in the folder
4. Go back to ImageGlass and switch to a new image
5. Ctrl+C to copy
6. Popup says X+1 images copied to clipboard

### Actual behavior:
Clipboard keeps incrementing until reset manually from ImageGlass (right click + reset clipboard button)

### Expected behavior:
Clipboard is reset when images are copied (using Ctrl+V) in a windows folder

**Comment by d2phap** [comment]
Hi @alexphiev 

It's the correct behaviour. It allows user to copy/cut multiple files to clipboard.
To clear the clipboard, need to press Ctrl+` (or using main menu > Clipboard > Clear)
