### ISSUE TITLE
Some black elements are not displayed when opening CMYK file

### ISSUE THREAD

**Issue by NelsonTien** [d2phap/ImageGlass#840]
### System information:
 - Windows OS version:  Windows 10 Professional 1909
 - ImageGlass version: 7.6.4.30

### Questions
When I open CMYK file with an embedded colour profile (Japan Color 2001 Coated)，all the black elements ( coloured as #0000000 ) are not displayed in ImageGlass. But it can be displayed in CMYK mode by other image browsers, such as Honeyviewer. I tried to uncheck "Apply also for images without embedded colour profiles" setting in the 「setting >  Image」viewport, but it still not work. I'm not sure if this is a problem with my options or a bug in the software. I hope you can help me 😀.

Comparison on RGB and CMYK：
![Contrast](https://user-images.githubusercontent.com/61303573/90711458-5f1e0080-e2d3-11ea-8383-90407f9af6ac.jpg)
CMYK source file with embedded colour profile：
![imageglass-CMYK](https://user-images.githubusercontent.com/61303573/90710998-36e1d200-e2d2-11ea-8400-64cf2da5a0bb.jpg)
SRGB source file with embedded colour profile：
![imageglass-SRGB](https://user-images.githubusercontent.com/61303573/90711004-39dcc280-e2d2-11ea-966d-e3b767e44138.jpg)

**Comment by d2phap** [comment]
Hi @NelsonTien 

This is probably due to Magick.NET lib, reported at #779

You can try the latest build of IG at:
https://imageglass.org/moon

**Comment by NelsonTien** [comment]
It has been fixed! Thank you!😄
