### ISSUE TITLE
ImageGlass cant open JPG or PNG with Exif-Metadata exported from darktable

### ISSUE THREAD

**Issue by Julianiolo** [d2phap/ImageGlass#842]
### System information:
 - Windows OS version: Windows 10 Pro x64, Version: 1903, Build: 18362.1016
 - ImageGlass version: 7.6.4.30 x64 (latest) (I'm like 99% sure its x64 but couldn't find a way to check)
 - [Darktable](https://www.darktable.org/) verison: 3.2.1

### To Reproduce
Either:
1. Open this file in ImageGlass:
![IMG_0224_Draktable3 2 1](https://user-images.githubusercontent.com/50519317/90799935-3702c180-e314-11ea-8c1e-cf143c4b7848.jpg)

Or:

1. Export this [CR2](https://drive.google.com/file/d/1C91dB-94bLZF99NGgSxmDmVXh2C32-_0/view?usp=sharing) in [darktable](https://www.darktable.org/) and export it (make sure Exif-Metadate is enabled):
2. Open the exported Image

### Actual behavior:
When i export an CR2 in darktable with Exif-Metadata and try to open that exported image it displays this message:
![image](https://user-images.githubusercontent.com/50519317/90800374-dde75d80-e314-11ea-8667-94282003810b.png)
Translated:
ImageGlass cannot open this picture because the file appears to be damaged, corrupted or not supported.
Magick.NET-Q16-AnyCPU: The arraydimensions exceeded the supported range.

The thumbnails work.

This happend with the CR2 exported as JPEG and PNG but not with TIFF or OpenEXR and only if exporting with Exif-Metadata was enabled.
[JPG without Exif-Metadata](https://user-images.githubusercontent.com/50519317/90804217-2ead8500-e31a-11ea-95bd-eb43b0e02704.jpg)
I had this issue with multiple versions of ImageGlass and darktable.

### Expected behavior:
Open the Image and be able to look at it

**I dont know if this is an issue with ImageGlass or darktable but every other program I tried could open the exported images fine so I assume it's an issue with ImageGlass.**

**Comment by d2phap** [comment]
Thanks @Julianiolo 
This is the error from Magick.NET - the library I use to read image file. I will check and report to the maintainer

**Comment by Julianiolo** [comment]
It seems like it got fixed with ImageGlass 8

**Comment by d2phap** [comment]
Thanks for the update!
