### ISSUE TITLE
Crashed while opening

### ISSUE THREAD

**Issue by FrankLiOnLine** [d2phap/ImageGlass#844]
I downloaded 7.6.4.30 version for my laptop (windows 10 with internet access) and desktop (win 7, company R&D asset without Internet access)

The issue is: This software runs perfectly on my laptop but crashes every time I try to start it on my desktop. It returns a microsoft help dialog box, and direct me to incompatible .NET framework help page.

I checked .NET version for these two devices. My laptop has a 3.5 (include 2.0 and 3.0) and a 4.0 .NET framework, my desktop has only 3.5.1 activated (with a lot of different .NET frameworks installed with Visual Studio, but only 3.5.1 shows in control panel -> Programs -> windows feature).

My desktop is in an isolated environment, I am sorry I cannot transfer any doc, log or picture out. The only thing I can do is take some pictures of my screen. Hope you can help a little bit about this issue (totally understand if you cannot, it's totally a nightmare to trouble shooting in ). If you want to check any info about this desktop, I can take some pictures. That's the only way I can help.

**Comment by d2phap** [comment]
Hi @FrankLiOnLine 
ImageGlass 7.6 requires .NET Framework 4.7.1 or later. It's recommended to install .NET Framework 4.8.

You can send me a screenshot, it also helps

**Comment by FrankLiOnLine** [comment]
I followed your instruction, installed .NET framework 4.8 and it works! Thanks a lot!
