### ISSUE TITLE
Option to change the shortcut Ctrl+C between copy and copy picture data

### ISSUE THREAD

**Issue by shioku** [d2phap/ImageGlass#845]
**Problem**
If you want to copy a picture to a website which supports upload of pictures like the editor on github with the "normal" copy (Ctrl+C) nothing will happen. You have to copy the picture data for it to work. Which is at the moment a fixed shortcut which can't be changed. (Ctrl+Shift+C)

**Solution**
A setting with a simple checkbox to be able to change the behavior between the two copy shortcuts.
So everyone can decide if Ctrl+C should "copy" or "copy picture data"

**Comment by d2phap** [comment]
Ctrl+C will be for "Copy image data" in the next version, also requested in #901 

![image](https://user-images.githubusercontent.com/3154213/99865016-d9676500-2be1-11eb-8bd7-86295ddf9542.png)

**Comment by Chimvokin** [comment]
Whoever came up with the idea to change simple file copy to "ctrl+shift+c" has made it a terrible experience for all the others considering people STILL can't easily edit the hotkeys in this software anywhere in the settings. **Please, revert this change and don't make hotkeys for unconventioal actions overwrite the established standardised ones.**

**Comment by d2phap** [comment]
@Chimvokin #1702

**Comment by Chimvokin** [comment]
> @Chimvokin #1702

That approach is not user-friendly and the feature to edit hotkeys should be within the UI of the software.
