### ISSUE TITLE
Images won't open with ImageGlass

### ISSUE THREAD

**Issue by luczztem** [d2phap/ImageGlass#847]
### System information:
 - Windows OS version: 10
 - ImageGlass version: any

### To Reproduce
1. Install;
2. Set as default photo viewer (optional);
3. Try open any image;
4. Simply won't open.

### Actual behavior:
If I set ImageGlass as default photo app and try opening a photo, it just won't open. If I try to open an image right-clicking > Open With > ImageGlass, it will "blink" and throw me back at the screen to select an app.
If I try just opening ImageGlass, it will open normally. If I drag and drop a photo inside ImageGlass, the photo loads normally too.

### Expected behavior:
Expected it to open normally.

### Screenshots:

(ImageGlass don't have icons, neither in the "Default apps" Windows settings nor when I right click a image and try to open it with ImageGlass)
![image](https://user-images.githubusercontent.com/70558658/91792774-b9309700-ebec-11ea-8713-ee9b398b78d6.png)
![image](https://user-images.githubusercontent.com/70558658/91793042-715e3f80-ebed-11ea-8a9f-29131f5ea576.png)

### Additional context:
This problem happens in any version. I do have latest .NET version.
Already tried reinstalling and restating PC.

**Comment by d2phap** [comment]
Hi @luczztem 

Can you try re-register the extensions as described at: https://github.com/d2phap/ImageGlass/discussions/791#discussioncomment-23108
