### ISSUE TITLE
Book View button

### ISSUE THREAD

**Issue by Dogway** [d2phap/ImageGlass#848]
### Is your feature request related to a problem? Please describe.
Yes, some image sequences are scans of books or extracted from PDFs.

### Describe the solution you'd like
A Book View button on the tool bar to change from single image to a dual image presentation side by side

### Describe alternatives you've considered
The only workaround is to reencode the merged images, or convert to PDF and use a PDF viewer for it. But this is not ideal.

### Additional context
The Book View starts from the clicked image onwards (alphabetically) so if you want to skip cover page you start by clicking on Page 2.

**Comment by d2phap** [comment]
Thanks @Dogway , but this feature is too advanced for the current design of ImageGlass, I will close then.
