### ISSUE TITLE
gif playing too fast

### ISSUE THREAD

**Issue by floppyD** [d2phap/ImageGlass#852]
### System information:
 - Windows OS version:  Windows 7 x64
 - ImageGlass version: 7.6.4.30

### To Reproduce
1. Open the gif

### Actual behavior:

This specific gif plays really fast. Never had any issue with other gifs.

### Expected behavior:

Play just like browsers and other image viewers do.

### Screenshots:

![GIF 05-09-2020 20-19-50](https://user-images.githubusercontent.com/29208110/92314946-337a6600-efb5-11ea-9874-ecdd2630f415.gif)

### Additional context:

Original gif:
![ezgif-5-efea89b512](https://user-images.githubusercontent.com/29208110/92314949-42f9af00-efb5-11ea-8017-64ce30088f7e.gif)

**Comment by fire-eggs** [comment]
I'm seeing a couple of playback issues with this GIF, which will require some digging.

The cause of the speed difference is the frame delay in the GIF is set to only 10ms. ImageGlass attempts to respect that setting, and you get a fast gif.

Browsers enforce a minimum frame time. Unfortunately, different browsers have different minimums, and those minimums have changed over time.

I recommend that you use [EzGif](https://ezgif.com/optimize) and change the animation speed. I had good results with 10 "hundredths of second between frames" (100ms), and 8 1/100s (80ms). Doing so will not affect browser playback, and will play nicely in ImageGlass.

**Comment by fire-eggs** [comment]
80ms delay:
![ezgif-4-5b9de69795e3_80ms](https://user-images.githubusercontent.com/9809727/92331551-8ac81700-f045-11ea-8bd8-26115da559a5.gif)

100ms delay:
![ezgif-4-0610bbf1c26d 100ms](https://user-images.githubusercontent.com/9809727/92331552-8b60ad80-f045-11ea-806f-ccc7a5f06c7a.gif)

**Comment by floppyD** [comment]
It's just a badly encoded gif then. All right, thanks!

**Comment by rubenguip** [comment]
Hi team, I had a similar issue with some gifs and found this thread.
One specifically seems to have weird frame delay in the beginning then becomes normal.
![ant water](https://github.com/d2phap/ImageGlass/assets/82772484/8a1b64d1-d318-4059-b17a-37e3b3c12a79)

Would it be possible to add an option to force a global specific frame delay for gifs? Or an active option like "if frame delay is less than 0.2 seconds (seems to be chromes and firefox default) set frame delay to specific value"?
