### ISSUE TITLE
Improper handling of laptops with extended displays

### ISSUE THREAD

**Issue by mportuesisf** [d2phap/ImageGlass#853]
### System information:
 - Windows OS version: Windows 10 version 2004, OS build 19041.508
 - ImageGlass version: 7.6.4.30

### To Reproduce
1. On a laptop, plug in an external monitor (I'm using a Displayport monitor connected via USB-C).  Set up Windows to Extend Display.
2. Double-click on an image to launch ImageGlass.
3. Drag the ImageGlass window fully onto to the external monitor.
4. Exit ImageGlass completely.
5. Unplug the external monitor.
6. Double-click on an image to launch ImageGlass.

### Actual behavior:
1. ImageGlass opens a window on the disconnected (non-existent) second monitor.   The user can tell there is a window open by looking at the task bar, but cannot see the image nor move the window onto the laptop display. 

### Expected Behavior:
1. ImageGlass opens a window displaying the image on the laptop display.

**Comment by d2phap** [comment]
Hi @mportuesisf 
Please follow #706 for future fix!

**Comment by d2phap** [comment]
This bug is fixed in the latest build of IG Moon:
https://imageglass.org/moon
