### ISSUE TITLE
Window gets resized in single instace setting

### ISSUE THREAD

**Issue by SS-035** [d2phap/ImageGlass#855]
### System information:
 - Windows OS version: Windows 10 x64
 - ImageGlass version: 7.6.4.30

### To Reproduce
1. Uncheck "Allow multiple instances of the program" in General settings.
2. Open multiple images.

### Actual behavior:
First image is opening in maximized window but when subsequent images are opened, window in resized to the Normal window size.

### Expected behavior:
Window should not get resized at when opening each image.

**Comment by d2phap** [comment]
Hi @SS-035 
The settings of ImageGlass instance only saved (written in disk) on exiting.

**Comment by SS-035** [comment]
I am not saying that images are opening in multiple instances of Imageglass even after unchecking that setting. After reopening it is working as intended i.e. if open a 2nd image from file explorer, that image is displayed on the existing ImageGlass instance as it should be. But the problem is when 2nd image is displayed then existing window of the existing instance (which was in maximized mode) is getting resized to the "Normal" size (not maximized). For a better UX, it should retain the existing window mode.

**Comment by d2phap** [comment]
@SS-035 
Currently, changing "Allow multiple instances of the program" option requires app restart.
I will think about the way to improve it.

**Comment by fire-eggs** [comment]
This sounds like issue #774, a fix for which is available in [ImageGlass Moon](https://imageglass.org/moon). Could you please try it and see if it solves your request?

**Comment by SS-035** [comment]
Thank God!! @fire-eggs, you understand the issue correctly. I was about to express it in details :relieved:. d2phap was misinterpreting my issue. 

Sorry I did not check if it was already mentioned in previous issues. I shall try the Moon version and let you know.

**Comment by SS-035** [comment]
@fire-eggs, the issue persists also in the Moon version.

**Comment by fire-eggs** [comment]
>Sorry I did not check if it was already mentioned in previous issues. 

No worries, we have too much history to search :-(

> the issue persists also in the Moon version.

Sorry to hear that. I'll take another look, and ask questions if I might be misunderstanding your issue.

**Comment by SS-035** [comment]
FYI, my issue is exactly same as the issue #774. There the user was also using single instance setting but it was not mentioned. And the issue is same for any automatically snapped window (not only split screen as shown in the user's attached gif) as well as Maximized window.

**Comment by fire-eggs** [comment]
Thanks for mentioning the snapped window case, I forgot to test that!

**Comment by SS-035** [comment]
Is there any binary distribution of the current "develop" brunch? I want to avoid compiling it myself.  


Or when can I expect this version to be rolled out as update?

**Comment by d2phap** [comment]
Yes, it's called ImageGlass Moon. 
You can download at https://imageglass.org/moon
