### ISSUE TITLE
Image Glass slow working with large images (25000x6000) and above

### ISSUE THREAD

**Issue by laacis2** [d2phap/ImageGlass#858]
### System info:
- ImageGlass version: 7.6.4.30
- OS version: Windows 10 x64 1906

### Expected behavior:
Smooth dragging zoomed images

### Actual behavior:
Large images will drag slow with poor framerate, the bigger the slower. Somewhere around 50000x15000 pictures no longer open with a error. Other software (pictus) doesn't struggle this way.

### Steps to reproduce:
Open a image over 25000x6000 size.

### Other info:
ryzen 7 3700x, rtx 2080 ti, 64gb of ram, samsung 970evo NVME.

**Comment by d2phap** [comment]
Hi @laacis2 

It's limitation of the current ImageGlass, mentioned at #272 
In the future, [ImageGlass Preview](https://github.com/d2phap/ImageGlass-Preview) will be the right app to handle bigger file. It's currently under development, there is no public release yet.
