### ISSUE TITLE
Add "Don't remind me again" checkbox to Upgrade message.

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#859]
From Google Group.

### Is your feature request related to a problem? Please describe.
Irritated by constant upgrade reminders.

### Describe the solution you'd like
Add a checkbox to the Upgrade message: "Don't remind me again." Turns off the check for update.

### Describe alternatives you've considered
User too lazy to look at settings.

### Additional context

If user goes to settings and re-enables "Check for upgrade", the reminder should come back and the checkbox should be clear.

**Comment by d2phap** [comment]
@rstarkov 
> My work-around is to block network access in the firewall.

You can disable the option "Check for update automatically" in Settings > General.
