### ISSUE TITLE
Easier upgrade process

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#860]
### Is your feature request related to a problem? Please describe.
User cranky because they have to go to the website and download to upgrade. Wants an easier process.

### Describe the solution you'd like
Since IG can check the website to see if there is a newer version, it should be possible to download and invoke the newer version.

This may require changing the website so there is a "latest version" area, instead of having to check version numbers.

This mechanism would have to keep in mind if IG is portable or installed. Also needs to take into account Admin installs [where IG should not be prompting for upgrade anyway!].

### Describe alternatives you've considered
Ignore whiny users.

**Comment by d2phap** [comment]
Close as not planned. User can switch to the MS Store version.
