### ISSUE TITLE
Title bar auto-hide function

### ISSUE THREAD

**Issue by baibai92** [d2phap/ImageGlass#861]
###1.我一直在寻找一个ui美观，无边框看图软件，最终发现imageglass，然而在使用过程中不尽人意。我希望能够添加 标题栏自动隐藏 功能，当我把鼠标移动到标题栏位置时自动显示出来，当我缩放图片时，缩放比例以透明方式悬浮在图片上。
2.自定义右键菜单选项，将选择权交给我们。

###这样做的原因：我在使用无边框模式时，缩放图片看不到缩放比例，移动图片需要按下shift按键，关闭图片需要按下esc按键，当我浏览图片时更喜欢鼠标简化操作。这种逻辑的软件有honeyview.然而ui丑最终放弃。特别希望作者能够加入这个功能。

google translate:###1.I have been looking for a beautiful ui, borderless image viewing software, and finally found imageglass, but it was not satisfactory during use. I want to be able to add the title bar auto-hide function, which will be displayed automatically when I move the mouse to the title bar position. When I zoom the image, the zoom ratio is transparently floating on the image.
2.Customize the right-click menu options, leave the choice to us

###The reason for this: When I use the borderless mode, I can’t see the zoom ratio when zooming the image. I need to press the shift button to move the image, and I need to press the esc button to close the image. I prefer the mouse to simplify the operation when I browse the image. This kind of logic software has honeyview. However, ui ugly finally gave up. I especially hope that the author can add this feature.

**Comment by baibai92** [comment]
@d2phap

**Comment by fire-eggs** [comment]
The right-click menu customization is an existing issue: see #102.

Displaying the title bar details (including zoom) is an existing issue: see #658.

So we'll keep this issue for "Title bar auto-hide" feature.

Thanks!

**Comment by baibai92** [comment]
@fire-eggs  Okay, I can accept it. Then, in the borderless mode, when zooming, 1. The zoom ratio is suspended on the picture in a transparent manner 2. The zoom ratio is 100% or less, you can click the left button to drag directly. I think the borderless mode will be easier to use。
In fact, there is a bug in the borderless mode (I don’t know if it’s): the preview list needs to be double-clicked to switch the picture, the normal mode only needs to be click。
Except for the above requirements, I am fine, thank you。
