### ISSUE TITLE
how do I set as Default photo viewer during installation? i know its possible because...

### ISSUE THREAD

**Issue by xekon** [d2phap/ImageGlass#862]
### System information:
 - Windows OS version: 10 pro 1909
 - ImageGlass version: ImageGlass_7.6.4.30_x64.msi

### To Reproduce
1. perform silent install (START "" /WAIT MSIEXEC /i "%SystemRoot%\Setup\Files\ImageGlass_7.6.4.30_x64.msi" /qn)
2. copy igconfig.xml to install directory, make sure it is writable.
3. try to open a file and it opens in MS paint.

### Actual behavior:
now windows should automatically know that it is the photo viewer, but it does not.

there does not seem to be an easy way to set it as the default photo app
I have read through the few issue reports relevant such as: https://github.com/d2phap/ImageGlass/issues/400

there may not be a way to programmatically do it, but i am fairly certain it can be done automatically during install.
for instance if I install VLC or firefox then they set them selves as the default application without intervention.

```
ECHO.
ECHO Installing Firefox . . .
START "" /WAIT "%SystemRoot%\Setup\Files\Firefox_x64.exe" /s
ECHO.
ECHO Installing VLC . . .
START "" /WAIT "%SystemRoot%\Setup\Files\vlc-3.0.11-win32.exe" /L=1033 /S
ECHO.
```

**Comment by xekon** [comment]
i may be mistaken, and those other programs do not work either when silent installed, still trying various things.

**Comment by xekon** [comment]
another program called "PotPlayer" if installed like this, correctly sets itself as the default media player, not sure if that is relevant to photo viewers being able to do the same thing or not:

START "" /WAIT "%SystemRoot%\Setup\Files\PotPlayerSetup64.exe" /S

**Comment by d2phap** [comment]
Hi @xekon 

You can write batch script and use ImageGlass command line utilities to register default extensions:
```
C:\path\to\ImageGlass\igtasks.exe regassociations "*.png;*.jpg;*.gif;"
```

- To get all default extension of ImageGlass: 
https://github.com/d2phap/ImageGlass/blob/master/Source/Components/ImageGlass.Base/Types/Constants.cs#L50

- To see all command lines: https://imageglass.org/docs/command-line-utilities

**Comment by fire-eggs** [comment]
Microsoft made it more difficult in Windows 10 to associate default apps. ImageGlass is currently only able to set file extension associations, which does _not_ make ImageGlass the default 'Photos' app.

Here are some links to Microsoft articles about setting default apps. Please let us know what you end up getting to work!

[Default App Assoc - command line](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/dism-default-application-association-servicing-command-line-options)
[File assoc for IT pros](https://docs.microsoft.com/en-us/archive/blogs/windowsinternals/windows-10-how-to-configure-file-associations-for-it-pros)
[Enterprise ready file assoc](https://docs.microsoft.com/en-us/archive/blogs/hewagen/making-file-type-associations-enterprise-ready)

**Comment by xekon** [comment]
@d2phap I tried your method to register extensions, it does not register it as the default Photo viewer for windows, only for some extensions.

I understand Microsoft made it more difficult in Windows 10, but it should be possible, both firefox and potplayer successfully set themselves as the default application on a silent install, without any intervention:

```
ECHO.
ECHO Installing Firefox . . .
START "" /WAIT "%SystemRoot%\Setup\Files\Firefox_x64.exe" /s
ECHO.
ECHO Installing PotPlayer . . .
START "" /WAIT "%SystemRoot%\Setup\Files\PotPlayer_x64.exe" /S
ECHO.
```

![defaults](https://user-images.githubusercontent.com/106644/93634701-e4193a00-f9a5-11ea-80f9-8def43bd8b6f.png)

**Comment by xekon** [comment]
VLC also sets as default on silent install:

```
ECHO.
ECHO Installing Firefox . . .
START "" /WAIT "%SystemRoot%\Setup\Files\Firefox_x64.exe" /s
ECHO.
ECHO Installing VLC . . .
START "" /WAIT "%SystemRoot%\Setup\Files\vlc-3.0.11-win32.exe" /L=1033 /S
ECHO.
```

![vlc](https://user-images.githubusercontent.com/106644/93655083-57d33b00-f9d6-11ea-9cfc-72f6da61362e.png)

**Comment by xekon** [comment]
Does anyone know the ProgID for ImageGlass? going to try OEMDefaultAssociations.xml:

for example:
```
<?xml version="1.0" encoding="UTF-8"?>
<DefaultAssociations>
  <Association Identifier=".jpe" ProgId="AppX43hnxtbyyps62jhe9sqpdzxn1790zetc" ApplicationName="Photos" ApplyOnUpgrade="true" OverwriteIfProgIdIs="AppX9vdwcvrwnbettpahnt26jswq0n8hgyah;Paint.Paint;Microsoft.PhotoManager.imagetype;jpegfile" />
  <Association Identifier=".jpeg" ProgId="AppX43hnxtbyyps62jhe9sqpdzxn1790zetc" ApplicationName="Photos" ApplyOnUpgrade="true" OverwriteIfProgIdIs="AppX9vdwcvrwnbettpahnt26jswq0n8hgyah;Paint.Paint;Microsoft.PhotoManager.imagetype;jpegfile" />
  <Association Identifier=".jpg" ProgId="AppX43hnxtbyyps62jhe9sqpdzxn1790zetc" ApplicationName="Photos" ApplyOnUpgrade="true" OverwriteIfProgIdIs="AppX9vdwcvrwnbettpahnt26jswq0n8hgyah;Paint.Paint;Microsoft.PhotoManager.imagetype;jpegfile" />
  <Association Identifier=".png" ProgId="AppX43hnxtbyyps62jhe9sqpdzxn1790zetc" ApplicationName="Photos" ApplyOnUpgrade="true" OverwriteIfProgIdIs="AppX9vdwcvrwnbettpahnt26jswq0n8hgyah;Paint.Paint;Microsoft.PhotoManager.imagetype;pngfile" />
</DefaultAssociations>
```

**Comment by d2phap** [comment]
@xekon 
Honestly, I don't know how to set it as default app automatically, also open for contribution :)

**Comment by xekon** [comment]
Woa, actually If you use the above OEMDefaultAssociations.xml then it DOES become the default photo viewer application. Initially I only set some extensions, but since adding the remaining ones a clean install of windows is now showing ImageGlass as the default photo viewer!

**Comment by d2phap** [comment]
Thanks @xekon for the information!
