### ISSUE TITLE
Crash attempting to save clipboard image

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#863]
### System information:
 - Windows OS version: Win 7 / Win 10
 - ImageGlass version: 7.6.4.30

### To Reproduce
1. Open an image from the clipboard
2. Attempt to save it (either from main menu or crop)

### Actual behavior:
Crash.

### Expected behavior:
Able to successfully save image.

### Additional context:

System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.
Parameter name: startIndex
   at System.String.Substring(Int32 startIndex, Int32 length)
   at ImageGlass.frmMain.<mnuMainSaveAs_Click>d__133.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

"Save as" code assumes the image has an extension.

Reported in Google Group.

**Comment by gsomix** [comment]
I cannot to reproduce that. Is it issue already resolved?

**Comment by d2phap** [comment]
Also cannot reproduce

**Comment by fire-eggs** [comment]
Duplicate of #782, already fixed.
