### ISSUE TITLE
"Save As" to Base64 (text) does nothing

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#864]
### System information:
 - Windows OS version: Win 7
 - ImageGlass version: 7.6.4.30

### To Reproduce
1. Open an image.
2. Use "Save as"
3. Select the option "Base64 (txt)"

### Actual behavior:
No .txt file is created.

### Expected behavior:
Creates a .txt file with an appropriate name, containing Base64 encoding.
**OR**
The "Base64 (txt)" option is removed.

**Comment by d2phap** [comment]
I tried but could not reproduce.

![image](https://user-images.githubusercontent.com/3154213/95078667-17025280-0748-11eb-88dc-388dd73441e0.png)

**Comment by fire-eggs** [comment]
Apparently fixed since 7.6.4.30
