### ISSUE TITLE
Couple of questions comparing to MS Photos

### ISSUE THREAD

**Issue by MadTomT** [d2phap/ImageGlass#866]
### System information:
Windows 10 Pro  2004
ImageGlass 7.6.4.30_x64

### Questions
If I open multiple images in Photos, this is all launched within one process of Photos. ImageGlass appears to launch multiple processes, one for each image..  Why ?

If I minimise Photos all cpu / memory usage is suspended, ImageGlass appears to keep hold of it.. why ?

These are not meant are criticisms just curios why it works that way.

Thanks

**Comment by d2phap** [comment]
Hi @MadTomT 
These are the differences of Win32 app (ImageGlass) and UWP app (MS Photos).

- UWP app supports single page application, so it can open multiple images in 1 instance. Win32 probably can do this too, but need more efforts, I guess.
- UWP app has suspending/resuming state which is similar to mobile app. It means, when you miminize it, it will enters suspending state which release the memory.
However, UWP app has lots of restrictions about file accessing, security.  You can read more about it at https://docs.microsoft.com/en-us/windows/uwp/get-started/universal-application-platform-guide

**Comment by MadTomT** [comment]
Thanks for the information.  This is probably a daft question. Is a Win32 app for 32Bit PC, what about 64Bit ?

**Comment by d2phap** [comment]
> Win32 generally refers to the 32-bit Windows API. However, the _WIN32 macro is defined for both 32-bit and 64-bit programming. As a Visual Studio project type it includes both GUI and console subsystem API-level programs.

https://stackoverflow.com/questions/20592783/what-is-the-difference-between-win32-application-windows-form-application-and-c

😊
