### ISSUE TITLE
AVIF support

### ISSUE THREAD

**Issue by h0n24** [d2phap/ImageGlass#867]
# Add AVIF support

AVIF image format is slowly becoming the next big thing on the web. It makes pictures around 50 % smaller in comparison to jpeg and 30 % smaller in comparison to webp.

## More info
https://reachlightspeed.com/blog/using-the-new-high-performance-avif-image-format-on-the-web-today/
https://en.wikipedia.org/wiki/AV1#AV1_Image_File_Format_(AVIF)

## Current web support
https://caniuse.com/avif

## Sample files
https://github.com/link-u/avif-sample-images

**Comment by fire-eggs** [comment]
Waiting on [ImageMagick](https://imagemagick.org/script/formats.php):

Post by magick » Wed Feb 12, 2020 1:49 pm

ImageMagick should instantly be able to encode/decode the AVIF image format once libheif includes AVIF support. They have a AVIF branch that has recent patches. We don't have an ETA on when it will be available. We are hesitant to write an decoder/encoder against libavif as long as there is some promise support will land in the libheif delegate library. If it becomes apparent that AVIF support won't land in libheif or if libavif becomes more prevalent in the Linux distributions, we will revisit utilizing libavif instead.

**Comment by d2phap** [comment]
Add support for AVIF format in IG Moon https://imageglass.org/moon
You need to manually add new extension in Settings:

![image](https://user-images.githubusercontent.com/3154213/94365510-3d9b0a80-0104-11eb-89ff-0b61a24ec621.png)


![image](https://user-images.githubusercontent.com/3154213/94365465-dda46400-0103-11eb-8b7d-539ddeac9b8a.png)

**Comment by h0n24** [comment]
Amazing job! Thank you!
