### ISSUE TITLE
ImageGlass image opening size

### ISSUE THREAD

**Issue by AdrianMolen** [d2phap/ImageGlass#868]

**Comment by AdrianMolen** [comment]
Hi 
I find Image Glass to be an excellent software.
I am using it to measure features in ultrasound images (using a ruler).

Just before an upgrade to W10 1909 Image Glass would open up an image to the last size used.  This was very handy because it saved a lot of time resizing images for measuring features.  Unfortunately after the upgrade, this feature seems to not be working.

Can it be restored or can I be informed how to set the opening size of the image so that it opens automatically to a specified size?

Kind regards
Adrian

**Comment by d2phap** [comment]
Hi @AdrianMolen 

I'm not sure what your problem is. 
- If you are asking about image size, you can check the Zoom mode: `Lock zoom ratio` which helps to lock and apply the current viewing image's zoom ratio to next images.

**Comment by AdrianMolen** [comment]
Hi Phap

Thank you. That, after scale to fit, does exactly what is wanted.

Kind regards
Adrian
