### ISSUE TITLE
"Open with" Context menu error 

### ISSUE THREAD

**Issue by Ruslanx9** [d2phap/ImageGlass#869]
### System information:
 - Windows OS version: Window 7 Ultimate 64x
 - ImageGlass version: 7.6.4.30

### Actual behavior:
When i click "open with" context menu i got error massage : "windows cannot find open with make sure typed name correctly"

### Screenshots:
![image](https://user-images.githubusercontent.com/3154213/94328602-6e851d80-ffe6-11ea-9201-6173e0a5113e.png)

![image](https://user-images.githubusercontent.com/3154213/94328608-71800e00-ffe6-11ea-868c-d52371945a81.png)

**Comment by d2phap** [comment]
Thanks @Ruslanx9 

Can you run this command in Run dialog (press Windows + R):

```
openwith "path_of_image_file"
```

![image](https://user-images.githubusercontent.com/3154213/94328715-4ba73900-ffe7-11ea-9d94-58dd9cfc8b5d.png)

**Comment by Ruslanx9** [comment]
didn't work :(

**Comment by Ruslanx9** [comment]
is there any way to edit the context menu in imageglass ?

**Comment by fire-eggs** [comment]
Sorry for the delay. I get the same error with IG 7.6.4.30 / Windows 7. I'll take a look.

>openwith "path_of_image_file"

I'm pretty sure that "openwith" is not available on Windows 7.

>is there any way to edit the context menu in imageglass ?

Not at this time - see issue #102

**Comment by fire-eggs** [comment]
Got it. "Open With" is a new feature added in 7.6 and doesn't support Windows 7.  We'll investigate if there is a Windows 7 alternative but most likely we'll have to disable the menu.

**Comment by fire-eggs** [comment]
Tech info: [How to host an IContextMenu](https://devblogs.microsoft.com/oldnewthing/20040920-00/?p=37823) [part 1 of 11 !!!].

**Comment by d2phap** [comment]
Hide the OpenWith menu in Win7, ImageGlass Moon https://imageglass.org/moon
