### ISSUE TITLE
Borderless window 

### ISSUE THREAD

**Issue by d2phap** [d2phap/ImageGlass#87]
Requested by David Rivera [fb]:

Hi, I love this app, I want to know if is possible to hide the tittle bar. What I want is something like this, a minimalist viewing option

https://scontent-sin1-1.xx.fbcdn.net/v/t1.0-9/13055286_783563868445375_8498216299134732575_n.jpg

**Comment by fire-eggs** [comment]
Isn't this "full screen mode"?

**Comment by d2phap** [comment]
Exactly but need to add to configs #291
