### ISSUE TITLE
Image file size changed after saving

### ISSUE THREAD

**Issue by baibai92** [d2phap/ImageGlass#870]
### System information:
 - Windows OS version: windows 10 2004
 - ImageGlass version: 7.6.4.30

When I use the function: save image as, the saved image size has been changed. I don’t know if the others have changed.
I want the saved image to retain the same attributes as the original image, just like copying.

![屏幕截图 2020-09-27 023525](https://user-images.githubusercontent.com/71174772/94347835-4212e500-006a-11eb-9b2d-b4b6332c71f8.png)
On the left is saved, and the right is the original
@d2phap

**Comment by d2phap** [comment]
IG is set to save the image as 100% quality by setting "quality" in Magick.NET library. In other apps (MS Paint,...) it's about 75-80%
I will add an option to change this value in the next release.
Also reported at #829

**Comment by fire-eggs** [comment]
The image in question is a PNG image. Image quality "normally" doesn't apply to PNG.

We'd need to have a copy of an image which shows the problem. Did IG strip Exif or other Metadata? Change the bits-per-pixel?

**Comment by fire-eggs** [comment]
Before I forget (again!) - the image you show is very nice! Would you share the source? Thanks!

**Comment by baibai92** [comment]
I tried different formats and different sizes of pictures, some became bigger and some became smaller. Now I provide these files, you can try。
Link：https://cowtransfer.com/s/2f99346b322449

**Comment by baibai92** [comment]
@fire-eggs

**Comment by fire-eggs** [comment]
Thanks for the samples!

What IG needs to do is save the image using the same configuration the image was loaded with.

As Phap points out, in the case of JPEG, IG is potentially using a different quality setting. But there is more to it:
- BMP files: Magick.NET is writing out additional metadata (Red Mask, Green Mask, etc) which increases the file size.
- JPEG: in addition to the quality setting change, Magick.NET is writing different metadata.
- PNG: Magick.NET is writing additional metadata, but is using a more effective encoding, making the written PNG overall smaller!

**Comment by d2phap** [comment]
Add option to change image quality in Settings > Edit tab in IG Moon: https://imageglass.org/moon

![image](https://user-images.githubusercontent.com/3154213/99551197-841b3000-29f6-11eb-8d2f-a6553e81225e.png)

**Comment by mirh** [comment]
I cannot find that option in 8.0.12.8.

**Comment by d2phap** [comment]
@mirh 
You go to Settings > Edit tab.
Or you can send me a screenshot

**Comment by mirh** [comment]
~~Yes, I have seen your scre~~
Nvm I had a brainfart.

**Comment by manyfew** [comment]
I just rotated a JPEG 90° right once. The file was originally 12.2 MB, and after saving it became 18.7 MB. If I rotate it using the Windows Photos app the file size doesn't change. I wonder if this could be optimized.
