### ISSUE TITLE
Unhandled exception when I attempt to save a theme

### ISSUE THREAD

**Issue by emCarCode** [d2phap/ImageGlass#872]
### System info:
- ImageGlass version: 7.6.4.30
- OS version: Windows 10 version 2004 x64

### Expected behavior:
Able to save themes

### Actual behavior:
Unhandled exception when I attempt to save a theme

### Steps to reproduce:
1. Go to Settings > Theme
2. Click "Save As" button
3. Navigate "Save As" window to user Downloads folder and click Save
![ImageGlass_cant-save-theme](https://user-images.githubusercontent.com/59533707/94363534-ad16e880-0077-11eb-9765-9cd8a0e0e6e5.PNG)

### Other notes:
If I open ImageGlass as Administrator then the unhandled exception doesn't occur and I am able to save a copy of the theme as expected.

**Comment by emCarCode** [comment]
Here is the debug text:

************** Exception Text **************
System.UnauthorizedAccessException: Access to the path 'C:\Program Files\ImageGlass\DefaultTheme\config.xml' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.Xml.XmlDocument.Save(String filename)
   at ImageGlass.UI.Theme.SaveAsThemeConfigs(String dir)
   at ImageGlass.UI.Theme.PackTheme(String themeFolderPath, String outputThemeFile)
   at ImageGlass.frmSetting.btnThemeSaveAs_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4220.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ImageGlass
    Assembly Version: 7.6.4.30
    Win32 Version: 7.6.4.30
    CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
ImageGlass.Services
    Assembly Version: 7.6.7421.42062
    Win32 Version: 7.6.7421.42062
    CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.Services.DLL
----------------------------------------
ImageGlass.Settings
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.Settings.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
ImageGlass.Base
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.Base.DLL
----------------------------------------
ImageGlass.Library
    Assembly Version: 7.6.7421.42062
    Win32 Version: 7.6.7421.42062
    CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.Library.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4220.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
ImageGlass.UI
    Assembly Version: 7.6.7421.42063
    Win32 Version: 7.6.7421.42063
    CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.UI.DLL
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
ImageGlass.Heart
    Assembly Version: 7.6.0.0
    Win32 Version: 7.6.0.0
    CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.Heart.DLL
----------------------------------------
Magick.NET-Q16-AnyCPU
    Assembly Version: 7.16.0.0
    Win32 Version: 7.16.0.0
    CodeBase: file:///C:/Program%20Files/ImageGlass/Magick.NET-Q16-AnyCPU.DLL
----------------------------------------
FileWatcherEx
    Assembly Version: 1.3.0.0
    Win32 Version: 1.3.0.0
    CodeBase: file:///C:/Program%20Files/ImageGlass/FileWatcherEx.DLL
----------------------------------------
ImageGlass.ImageBox
    Assembly Version: 7.6.7421.42062
    Win32 Version: 7.6.7421.42062
    CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.ImageBox.DLL
----------------------------------------
ImageGlass.ImageListView
    Assembly Version: 11.0.0.7
    Win32 Version: 11.0.0.7
    CodeBase: file:///C:/Program%20Files/ImageGlass/ImageGlass.ImageListView.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
DotNetZip
    Assembly Version: 1.13.7.0
    Win32 Version: 1.13.7
    CodeBase: file:///C:/Program%20Files/ImageGlass/DotNetZip.DLL
----------------------------------------

**Comment by d2phap** [comment]
Thanks @emCarCode 
This is because of folder permission. I will investigate how to solve this

**Comment by d2phap** [comment]
Fixed in IG Moon: https://imageglass.org/moon
