### ISSUE TITLE
In borderless mode, Thumbnail bar double-click to single-click

### ISSUE THREAD

**Issue by baibai92** [d2phap/ImageGlass#873]
When I use the preview list in borderless mode, I need to double-click to switch the picture. Can it be changed to single-click to make the behavior consistent with normal mode?
@fire-eggs

**Comment by d2phap** [comment]
Thanks @baibai92 
Confirm the bug

**Comment by d2phap** [comment]
Fixed this. It will be shipped in the upcoming release
