### ISSUE TITLE
Tif files display a pink tint after rotating

### ISSUE THREAD

**Issue by AlexanderRitter02** [d2phap/ImageGlass#874]
### System info:
- **ImageGlass version:** 7.6.4.30 and 7.6.9.27 (Moon)
- **OS version:** Windows 10 1909, Build 18363.1082

### Expected behavior:
Display the tif file in normal colours.

### Actual behavior:
Display the tif file with a pink coloured overlay.

![grafik](https://user-images.githubusercontent.com/42546705/94375954-91fbb580-0117-11eb-84c6-861415467dab.png)

Other photo viewers display it correctly.
Closing and reopening ImageGlass does help.

### Steps to reproduce:
1. Create a .tif file (Mine resulted from a scan)
2. Open with ImageGlass (should show normal). 
3. Rotate the file
4. Close and reopen

:x: Pink overlay is visible

### Other info:
- Saving after rotating is enabled

**Comment by d2phap** [comment]
@AlexanderRitter02 
Can you attach the file,  thanks!

**Comment by AlexanderRitter02** [comment]
Here, I attached a new file since the original contains sensitive information. However it seems to happen to every file.
Contains `Original` and `Rotated_and_Pink`. I also noticed the file sizes are different.
[Lorem Ipsum.zip](https://github.com/d2phap/ImageGlass/files/5291855/Lorem.Ipsum.zip)

**Comment by AlexanderRitter02** [comment]
@d2phap Sorry to bug you. I attached the files, you can remove the "ℹ️` need more information`" label.
Hoping this didn't corrupt my files, I am currently using another viewer for TIFs.

**Comment by d2phap** [comment]
Thanks @AlexanderRitter02 
Confirm the problem!

**Comment by klou** [comment]
v8.1.4.18

I have a TIF scan that was sent to me (sorry, can't share) that opened OK, looked like a standard scanv.  I then ran the TIF through FileOptimizer (https://nikkhokkho.sourceforge.io/static.php?page=FileOptimizer), and the resulting file had all of the white space replaced by magenta.

**Comment by d2phap** [comment]
Upgraded Magick.NET to v8.2.0 to fix this issue.
https://github.com/dlemstra/Magick.NET/issues/946

Download the latest build of IG Moon: https://imageglass.org/moon
