### ISSUE TITLE
rename can not support ctrl +V

### ISSUE THREAD

**Issue by 986244073** [d2phap/ImageGlass#876]
### System information:
 - Windows OS version:  1903
 - ImageGlass version: 7.64.30

rename can not support ctrl +V

**Comment by d2phap** [comment]
It's fixed in ImageGlass Moon: https:// imageglass.org/moon/

Also reported in #834

**Comment by 986244073** [comment]
show the error when the file name exists

**Comment by d2phap** [comment]
Can you attach screenshot or error message?
Please follow our issue template, I cannot support if you only say "there is an error"...

**Comment by 986244073** [comment]
I want a new feature :If this file exists, the input box will warn you
