### ISSUE TITLE
Using 'Delete' key in "Rename Image" dialog deletes the image

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#88]
1. Run ImageGlass, open and view image.
2. Right-click the current image, select "Rename image"
3. The Rename dialog appears. Click in the edit box _before_ one of the characters in the filename.
4. Press the Delete key.

The expectation is the character in the filename would be deleted, the user clicks OK and the image is renamed.

The actual behavior is the image vanishes, being placed in the Recycle bin.

**Comment by d2phap** [comment]
Hi @fire-eggs 

This bug was reported at issue #69  and fixed by this commit https://github.com/d2phap/ImageGlass/commit/5f6313c3fa36723e61b2dc5408b326675136d3b4

**Comment by fire-eggs** [comment]
Thank you! I'll take a look.
