### ISSUE TITLE
Allow Page Navigation to step through GIFs frame-by-frame

### ISSUE THREAD

**Issue by fire-eggs** [d2phap/ImageGlass#880]
### Is your feature request related to a problem? Please describe.
Can't use Page Navigation feature to step through a GIF frame-by-frame. Even when the GIF is paused, clicking "Next Page" starts the GIF playing again.

### Describe the solution you'd like
If a GIF is paused, using the Page Navigation controls should not start playback, but move through the file frame-by-frame.

**Comment by d2phap** [comment]
Duplicated of #680 ^^
