### ISSUE TITLE
Open an image in a large folder is very slow

### ISSUE THREAD

**Issue by remss** [d2phap/ImageGlass#881]
### Is your feature request related to a problem? Please describe.
When the folder contains lots of files then imageglass is slow to open even with toolbar/thumbnails hidden because it counts all files in the folder to display it in the window title.

### Describe the solution you'd like
I'd like an option in the settings to not display number of files in the window title, so imageglass will not try to count files.

### Describe alternatives you've considered
I don't see any alternatives to tackle this.

**Comment by d2phap** [comment]
This requested is implemented,
Download the latest build at https://imageglass.org/moon
