### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by shenqiang968** [d2phap/ImageGlass#888]
************** 操作系统 **************
win10 2004
----------------------------------------

有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> System.InvalidOperationException: 此实现不是 Windows 平台 FIPS 验证的加密算法的一部分。
   在 System.Security.Cryptography.MD5CryptoServiceProvider..ctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 System.Security.Cryptography.CryptoConfig.CreateFromName(String name, Object[] args)
   在 System.Security.Cryptography.MD5.Create()
   在 ImageGlass.ImageListView.ImageListViewCacheThumbnail.GetKey(Guid guid, Size size, UseEmbeddedThumbnails useEmbeddedThumbnails, Boolean autoRotate, Boolean useWIC)
   在 ImageGlass.ImageListView.ImageListViewCacheThumbnail.GetImage(Guid guid, Size thumbSize, UseEmbeddedThumbnails useEmbeddedThumbnails, Boolean autoRotate, Boolean useWIC, Boolean clone)
   在 ImageGlass.ImageListView.ImageListViewItem.GetCachedImage(CachedImageType imageType)
   在 ImageGlass.ImageListView.ImageListViewRenderers.ThemeRenderer.DrawItem(Graphics g, ImageListViewItem item, ItemState state, Rectangle bounds)
   在 ImageGlass.ImageListView.ImageListView.ImageListViewRenderer.RenderItems(Graphics g)
   在 ImageGlass.ImageListView.ImageListView.ImageListViewRenderer.Render(Graphics graphics)
   在 ImageGlass.ImageListView.ImageListView.OnPaint(PaintEventArgs e)
   在 System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   在 System.Windows.Forms.Control.WmPaint(Message& m)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.8.4220.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ImageGlass
    程序集版本:7.6.4.30
    Win32 版本:7.6.4.30
    基本代码:file:///C:/Program%20Files/ImageGlass/ImageGlass.exe
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.8.4200.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
ImageGlass.Services
    程序集版本:7.6.7421.42062
    Win32 版本:7.6.7421.42062
    基本代码:file:///C:/Program%20Files/ImageGlass/ImageGlass.Services.DLL
----------------------------------------
ImageGlass.Settings
    程序集版本:1.1.0.0
    Win32 版本:1.1.0.0
    基本代码:file:///C:/Program%20Files/ImageGlass/ImageGlass.Settings.DLL
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.8.4200.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
ImageGlass.Base
    程序集版本:1.1.0.0
    Win32 版本:1.1.0.0
    基本代码:file:///C:/Program%20Files/ImageGlass/ImageGlass.Base.DLL
----------------------------------------
ImageGlass.Library
    程序集版本:7.6.7421.42062
    Win32 版本:7.6.7421.42062
    基本代码:file:///C:/Program%20Files/ImageGlass/ImageGlass.Library.DLL
----------------------------------------
System.Core
    程序集版本:4.0.0.0
    Win32 版本:4.8.4220.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
ImageGlass.UI
    程序集版本:7.6.7421.42063
    Win32 版本:7.6.7421.42063
    基本代码:file:///C:/Program%20Files/ImageGlass/ImageGlass.UI.DLL
----------------------------------------
System.Xml
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
ImageGlass.Heart
    程序集版本:7.6.0.0
    Win32 版本:7.6.0.0
    基本代码:file:///C:/Program%20Files/ImageGlass/ImageGlass.Heart.DLL
----------------------------------------
Magick.NET-Q16-AnyCPU
    程序集版本:7.16.0.0
    Win32 版本:7.16.0.0
    基本代码:file:///C:/Program%20Files/ImageGlass/Magick.NET-Q16-AnyCPU.DLL
----------------------------------------
mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
FileWatcherEx
    程序集版本:1.3.0.0
    Win32 版本:1.3.0.0
    基本代码:file:///C:/Program%20Files/ImageGlass/FileWatcherEx.DLL
----------------------------------------
ImageGlass.ImageBox
    程序集版本:7.6.7421.42062
    Win32 版本:7.6.7421.42062
    基本代码:file:///C:/Program%20Files/ImageGlass/ImageGlass.ImageBox.DLL
----------------------------------------
ImageGlass.ImageListView
    程序集版本:11.0.0.7
    Win32 版本:11.0.0.7
    基本代码:file:///C:/Program%20Files/ImageGlass/ImageGlass.ImageListView.DLL
----------------------------------------
System.Configuration
    程序集版本:4.0.0.0
    Win32 版本:4.8.4190.0 built by: NET48REL1LAST_B
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试程序，
而不是由此对话框处理。

![image](https://user-images.githubusercontent.com/67826085/95669392-e2aced00-0bb2-11eb-90e3-d795ed874645.png)
![image](https://user-images.githubusercontent.com/67826085/95669406-16881280-0bb3-11eb-985f-565a4de0f082.png)

**Comment by d2phap** [comment]
Hi @shenqiang968 

Please follow the bug template and write in English.
Thanks!
