### ISSUE TITLE
Group images slideshow by their directory

### ISSUE THREAD

**Issue by sunbinyuan** [d2phap/ImageGlass#890]
### Is your feature request related to a problem? Please describe.
No.

### Describe the solution you'd like
When I open a root folder with multiple subfolders or multiple folders at once, I want to be able to look at every files in one folder, sorted by whatever filter, before moving to another folder.

### Describe alternatives you've considered
Default options doesn't work.

### Additional context
PR will open soon.

**Comment by d2phap** [comment]
Ready for testing in IG Moon: https://imageglass.org/moon
