### ISSUE TITLE
Thumbnail data is not updated after rotating the picture

### ISSUE THREAD

**Issue by zirbuk** [d2phap/ImageGlass#892]
### System info:
- ImageGlass version: 7.6.4.30
- OS version: Windows 7 Professional

### Expected behavior:
In the settings, I enabled "Saving picture after rotation".
When I display a picture and I click on "Rotate", and then I quit the software, I expect the thumbnail to be updated in Windows explorer.

### Actual behavior:
Image is rotated but not the thumbnail in Windows Explorer. I have to open the file with Paint for example, and just save it, to update the thumbnail in the Explorer.

### Steps to reproduce:
1. In the settings, the parameter "Saving picture after rotation" is selected (enabled)
2. I select a picture in a folder and I double click to open it with ImageGlass
3. I click on "Rotate".
4. The picture is indeed rotated.
5. I quit the software and go back to Explorer. 
5. The thumbnail is not updated unless I open the file with another software and just save the picture without any additional modification.

### Other info:
No other info :)

**Comment by fire-eggs** [comment]
Windows Explorer will not update the thumbnail unless it detects that the image has been "changed". You are making that happen by opening in paint and saving it again.

To get the same behavior from ImageGlass, you need to turn the following setting OFF:

![image](https://user-images.githubusercontent.com/9809727/96460506-448fd700-11f1-11eb-88be-bd7877aa6e16.png)

The setting can be found immediately below the "Save the viewing image after rotating".

If that doesn't solve the issue for you, see [this thread](https://social.technet.microsoft.com/Forums/windows/en-US/3d37b5ab-5592-4eff-9082-cf25ec9e31da/how-do-i-refresh-thumbnails-in-windows-7?forum=w7itprogeneral) on refreshing thumbnails.

**Comment by zirbuk** [comment]
Thank you, this way it does work !
