### ISSUE TITLE
HEIF Support

### ISSUE THREAD

**Issue by Wolfrisger** [d2phap/ImageGlass#893]
### Is your feature request related to a problem? Please describe.
I would like to open HEIF format I took from android 10+ phone

### Describe the solution you'd like
I think its supported already, if I change the extension of the file from heif to heic it can be opened. Maybe just need link heif with heic? I'm not sure.

### Additional context
There is a problem though, if I open it that way, the image is rotated by 90 degree if I capture it in landscape mode.

thanks.

- Sample file:
[IMG_20201019_171539.zip](https://github.com/d2phap/ImageGlass/files/5479419/IMG_20201019_171539.zip)

**Comment by d2phap** [comment]
Hi @Wolfrisger 
You can open Settings > File Type Associations, and add `.heif` to the list

> There is a problem though, if I open it that way, the image is rotated by 90 degree if I capture it in landscape mode.

What version of ImageGlass are you using?

**Comment by Wolfrisger** [comment]
> 
> 
> Hi @Wolfrisger
> You can open Settings > File Type Associations, and add `.heif` to the list
> 
> > There is a problem though, if I open it that way, the image is rotated by 90 degree if I capture it in landscape mode.
> 
> What version of ImageGlass are you using?

Added `.heif` to the list and it works!

I'm using 7.6.10.18,
[a landscape heif here](https://we.tl/t-W6LGtxHNJX)  (WeTransfer Link)

**Comment by d2phap** [comment]
@Wolfrisger 
Sorry I am too late, the transfer link was expired

**Comment by Wolfrisger** [comment]
> Sorry I am too late, the transfer link was expired

https://drive.google.com/file/d/1UBkkwSQRZcF0nSeTouUTvXuiK_0LTpDA/view?usp=sharing

**Comment by d2phap** [comment]
Add `.heif` as built-in formats
