### ISSUE TITLE
Very high resolution images do not load (System.Drawing: Parameter is not valid)

### ISSUE THREAD

**Issue by HydroHydro** [d2phap/ImageGlass#894]
### System information:
 - Windows OS version: 10
 - ImageGlass version: 7.6.4.30 *and* moon version

### To Reproduce
1. Download the "original file" here: https://en.wikipedia.org/wiki/The_Garden_of_Earthly_Delights#/media/File:The_Garden_of_earthly_delights.jpg
(39137x22279)
2. Open in ImageGlass.
3. Error: https://i.imgur.com/cJ97Yj2.png

Tried it on the official version and the moon version. Same error each time.

**Comment by fire-eggs** [comment]
I thought this was a duplicate entry, but I can't find an existing bug for this.

This is a known limitation of ImageGlass.

**Comment by HydroHydro** [comment]
> I thought this was a duplicate entry, but I can't find an existing bug for this.
> 
> This is a known limitation of ImageGlass.

Are there any plans to fix it? Windows Photos app seems to handle it just fine...

**Comment by d2phap** [comment]
> Are there any plans to fix it? 

Unfortunately, no plan to support big image in ImageGlass. You can follow ImageGlass Preview which is new app (under development) that can handle big file: https://github.com/d2phap/ImageGlass-Preview

Merged this to #272
