### ISSUE TITLE
20H2 breaks ImageGlass

### ISSUE THREAD

**Issue by aaa4xu** [d2phap/ImageGlass#897]
### System information:
 - Windows OS version: 20H2 19042.572
 - ImageGlass version: 7.6.10.25

### To Reproduce
1. Update Windows to 20h2
2. Try to open any image

### Actual behavior:
IG opens, but it's in "empty" state. `File > Open file` gives same result. No errors, just empty window.

### Screenshots:
![image](https://user-images.githubusercontent.com/1071970/97223914-7997bd00-17e1-11eb-9c12-7d4f94e65c7e.png)

**Comment by aaa4xu** [comment]
Looks like unchecking `Image > Use Windows File Explorer sort order if possible` option fixes this problem.

**Comment by fire-eggs** [comment]
Fantastic. Sounds like Microsoft might have broken that option. I'll try to revisit it once the October 2020 general release is out.

**Comment by d2phap** [comment]
I just tried on my laptop (Win 10 20H2), and there is no issue.
@aaa4xu  Can you send me your `igconfig.xml` file?
You can try deleting this file and see if it works?

![image](https://user-images.githubusercontent.com/3154213/97321622-0a39d000-18aa-11eb-8c73-b8d1551204db.png)

**Comment by aaa4xu** [comment]
And it's gone... I don't changed anything but can't reproduce this today even after install back `7.6.4.30`. Sorry for false report.
