### ISSUE TITLE
Issue with .jp2 files

### ISSUE THREAD

**Issue by tedfuyk** [d2phap/ImageGlass#899]
### System information:
 - Windows OS version: Windows 10 Pro 20H2
 - ImageGlass version: 7.6.4.30

### To Reproduce
1. Click a .jp2 file (attached below, at the end of this bug report)
2. Select open with ImageGlass
3. 
4. 

### Actual behavior:

I tried to open .jp2 files with ImageGlass, but failed with the message "ImageGlass cannot open this picture because the file appears to be damaged, corrupted or not support.

### Expected behavior:

Open the file

### Screenshots:

![image](https://user-images.githubusercontent.com/57200343/97736700-79821080-1ab2-11eb-94da-3bc9e2d2c90c.png)

### Additional context:

I checked that .jp2 file is supported according to the "Supported formats" page. I also used an online viewer to make sure the file is not damaged or corrupted. (Online viewer: [https://products.groupdocs.app/viewer/jp2](url))
![image](https://user-images.githubusercontent.com/57200343/97737159-06c56500-1ab3-11eb-8732-13cc79d7deb5.png)
Here's the file I was trying to open: (it's in the zip file since GitHub does not support .jp2 file)
[01.zip](https://github.com/d2phap/ImageGlass/files/5466657/01.zip)

**Comment by d2phap** [comment]
Hi @tedfuyk 

In v7.6.4.30, you need to manually add `.jp2` as extension in Settings:
![image](https://user-images.githubusercontent.com/3154213/97769374-42b90280-1b65-11eb-9f41-7e7542ab3b0c.png)

**Comment by tedfuyk** [comment]
Thanks a lot. It works. Just one more question, there's no preview in the File Explorer, how can I enable it? Thank you in advance.

**Comment by d2phap** [comment]
IG does not provide shell extension for File Explorer to show thumbnail preview. 
You can try installing SageThumbs https://sourceforge.net/projects/sagethumbs/

**Comment by tedfuyk** [comment]
Interesting. I thought IG provide thumbnail preview since at first there's no thubmnail preview for. webp files, and after I set IG as default there's thumbnail preview. Anyway, thanks a lot. I'll submit another feature request on that.
