### ISSUE TITLE
Key shortcut for Copy functions

### ISSUE THREAD

**Issue by xmha97** [d2phap/ImageGlass#901]
Hello, please change the below key shortcuts.
I would like to copy image data using Ctrl+C and paste to Word, Firefox (GitHub site), Photoshop and etc.
![ImageGlass context menu](https://user-images.githubusercontent.com/23485114/98315810-542f5e00-1fee-11eb-8ac7-10572315d7bf.png)

**Comment by Wuhao1627003** [comment]
Would be wonderful if we can customize keyboard shortcuts! (Many other frs also mentioned similar requests)

**Comment by d2phap** [comment]
Ready in IG Moon: https://imageglass.org/moon

![image](https://user-images.githubusercontent.com/3154213/99550496-be380200-29f5-11eb-8387-cd1cdeb492c0.png)

**Comment by xmha97** [comment]
Thanks <3
