### ISSUE TITLE
Square Select for Crop

### ISSUE THREAD

**Issue by xmha97** [d2phap/ImageGlass#903]
In Photoshop you can hold down the shift key to force the selection to be square-shaped.
I need this feature for ImageGlass.
![Photoshop](https://user-images.githubusercontent.com/23485114/98327328-88b01380-2008-11eb-8efd-0f16aa2fb0a4.gif)

**Comment by d2phap** [comment]
Duplicated #755

**Comment by d2phap** [comment]
It's supported in [ImageGlass Moon 9.0 beta 3](https://github.com/d2phap/ImageGlass/releases/tag/9.0.3.1225)
