### ISSUE TITLE
Going to full screen screen flashes

### ISSUE THREAD

**Issue by Wuhao1627003** [d2phap/ImageGlass#905]
### System info:
- ImageGlass version: 7.6.4.30
- OS version: Win 10

### Expected behavior:
Going to full screen smoothly

### Actual behavior:
Screen flashes a broken part of image, then loads picture full-screen

### Steps to reproduce:
1.Open an image
2.Alt+Enter to go full screen

### Other info:
Happens to both vertical and horizontal, large and small images, happens every time

**Comment by fire-eggs** [comment]
I believe this might be related to Issue #885 - the `FullScreenMode` function _always_ forces the work of turning off frameless mode and windows fit mode, even if they aren't already on.

On some systems, doing this forced work could make a visible "hiccup" on the screen.

**Comment by d2phap** [comment]
This issue should be fixed in [ImageGlass 9.0 beta 2](https://github.com/d2phap/ImageGlass/releases/tag/9.0.2.904) already!
