### ISSUE TITLE
Colour management in TIFF files with .tif extension is broken

### ISSUE THREAD

**Issue by noccu** [d2phap/ImageGlass#906]
### System information:
 - Windows OS version: Win 10 x64
 - ImageGlass version: 7.6.4.30 & 7.6.11.9

### To Reproduce
1. Create TIFF file with embedded icc profile
2. Use the .tif extension
3. Open the file in ImageGlass

### Actual behavior:
Colours are displayed incorrectly.
The title bar lacks the colour model info.
Changing colour management settings in any way causes no changes to these files.

### Expected behavior:
TIFF files with the (recommended by the spec) .tif extension show correct colours, info, and are subject to colour management.

### Additional context:
Files with the .tiff extension work as expected.

**Comment by d2phap** [comment]
@noccu 
Do you have sample file? Thanks!

**Comment by noccu** [comment]
@d2phap
[ig_color-bug_906.zip](https://github.com/d2phap/ImageGlass/files/5610785/ig_color-bug_906.zip)

**Comment by d2phap** [comment]
Fixed this in the latest build of ImageGlass Moon: https://imageglass.org/moon
