### ISSUE TITLE
[Feature] Minimize after edit button

### ISSUE THREAD

**Issue by xmha97** [d2phap/ImageGlass#907]
Hello, Please don't close this issue :)
I want to minimize the program by clicking the edit button.
Similar: #413

![ImageGlass](https://user-images.githubusercontent.com/23485114/98948495-bff05a00-250b-11eb-9e9c-5d2360faff84.gif)

**Comment by d2phap** [comment]
Ready in IG Moon: https://imageglass.org/moon

![image](https://user-images.githubusercontent.com/3154213/99551273-9a28f080-29f6-11eb-883c-ca43e236f908.png)

**Comment by xmha97** [comment]
Thanks very much 😘
