### ISSUE TITLE
Crash with svg on windows 10

### ISSUE THREAD

**Issue by HanatakeYurii** [d2phap/ImageGlass#91]
Hi, I got some crashing errors with svg files:
First I tried to open svg file with ImageGlass, it loads perfectly but after some seconds it goes crashing ("has stopped working" error).

Second I tried to open a png file in the same folder of some svg files, and it goes exactly the same way.

Then, after some more tries, I searched in the event log just to got that:

> Nom de l’application défaillante ImageGlass.exe, version : 3.2.0.16, horodatage : 0x56b4cc55
> Nom du module défaillant : unknown, version : 0.0.0.0, horodatage : 0x00000000
> Code d’exception : 0xc00000fd
> Décalage d’erreur : 0x00007ffd14e90612
> ID du processus défaillant : 0x2568
> Heure de début de l’application défaillante : 0x01d1a7f7e2a31352
> Chemin d’accès de l’application défaillante : C:\Program Files\ImageGlass\ImageGlass.exe
> Chemin d’accès du module défaillant: unknown
> ID de rapport : 5f3a68bc-6a8c-4dc6-84c5-f00f9e33ba8c
> Nom complet du package défaillant : 
> ID de l’application relative au package défaillant : 

And that:

> Récipient d’erreurs 129094232453, type 5
> Nom d’événement : CLR20r3
> Réponse : Non disponible
> ID de CAB : 0
> 
> Signature du problème : 
> P1 : ImageGlass.exe
> P2 : 3.2.0.16
> P3 : 56b4cc55
> P4 : Svg
> P5 : 2.0.0.42482
> P6 : 55f83ae5
> P7 : 979
> P8 : a
> P9 : System.StackOverflowException
> P10 : 
> 
> Fichiers joints :
> C:\Users\empir\AppData\Local\Temp\WER3A59.tmp.WERInternalMetadata.xml
> C:\Users\empir\AppData\Local\Temp\WER4622.tmp.appcompat.txt
> C:\Users\empir\AppData\Local\Temp\WER4B15.tmp.WERDataCollectionFailure.txt
> 
> Ces fichiers sont peut-être disponibles ici :
> C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_ImageGlass.exe_82de7f5857c93cb214616bc1e80da603754f7a_1a48d762_3f944b9f
> 
> Symbole d’analyse : 
> Nouvelle recherche de la solution : 0
> ID de rapport : 5f3a68bc-6a8c-4dc6-84c5-f00f9e33ba8c
> Statut du rapport : 9
> Récipient avec hachage : d952acab08acba268a40c968ee842156

It seems that's svg files-related as seeable in the second log. I couldn't find more infos in the other files. I only tested this on Windows 10, doesn't know if it's the same behavior elsewhere.

After some more investigation, it seems related to a specific svg file. It always crash if it is the same folder. Strange that this file is not very heavy and is loading well in web browsers.

Don't know if this report will be useful for you, but as a developper I would be worried if my software crashes instead of saying that this file is not readable.

Feel free to ask me more infos if you know how to get them. I can provide you the file if you want (it's a metro map of Shanghai)

Have a good day
HanatakeYurii

**Comment by d2phap** [comment]
Hi @HanatakeYurii ,

If it's ok for you, please upload that svg file so that I can test and debug easily.
Thanks for your post!

**Comment by HanatakeYurii** [comment]
[shanghai.zip](https://github.com/d2phap/ImageGlass/files/253311/shanghai.zip)

There it goes ^^

**Comment by d2phap** [comment]
Hi @HanatakeYurii 

Because ImageGlass is using open source SVG library from this repo: https://github.com/vvvv/SVG
So I just summited your file as an issue. Hope they will have an update of the lib soon.

Thanks
Phap

**Comment by HanatakeYurii** [comment]
Thanks
I hope it was a rare issue and they can do something. I never got it again since.

**Comment by d2phap** [comment]
The bug is fixed by using new lib.

**Comment by HanatakeYurii** [comment]
Thanks, will wait for a future release.
