### ISSUE TITLE
Sometimes First Launch config. prompt shows up incorrectly

### ISSUE THREAD

**Issue by philiparvidsson** [d2phap/ImageGlass#910]
### System information:
 - Windows OS version: Windows 10 x64 b19041.630
 - ImageGlass version: 7.6.4.30 [Portable]

### To Reproduce
1. Open ImageGlass with some image
2. Close ImageGlass
3. Open ImageGlass again very quickly with some other image

### Actual behavior:
ImageGlass starts with the First Launch configuration prompt
**NOTE** This does not ALWAYS happen, but SOMETIMES.

### Expected behavior:
ImageGlass starts as normal, showing the new image

**Comment by d2phap** [comment]
I tried to reproduce this but no luck!
I will keep this open if some one can find better way to reproduce.
Thanks @philiparvidsson

**Comment by tx46** [comment]
I've upgraded to the latest ImageGlass and this is still occurring sometimes. Is the app rewriting the config file on every exist even if it hasn't changed? I would suspect that's the issue.

**Comment by d2phap** [comment]
Close because I could not reproduce it
