### ISSUE TITLE
ImageGlass cannot open a picture

### ISSUE THREAD

**Issue by CroControl** [d2phap/ImageGlass#911]
### System information:
 - Windows OS version: Windows 10 Pro build 18362.1082
 - ImageGlass version: 7.6.4.30
 - Hardware: i7-4790K CPU with 32GB RAM

### Actual behavior:
When trying to open a PNG file, ImageGlass spits out a message: "ImageGlass cannot open this picture because the file appears to be damaged, corrupted or not supported. System.Drawing: Parameter is not valid."

### Expected behavior:
MS Photos, GIMP and several other programs open the file just fine. Only ImageGlass is unable to open it.

### Additional context:
PNG is over 760MB in size with a resolution of 23660×36670.

**Comment by d2phap** [comment]
Hi @CroControl 

The image file is too big (23660×36670) for the current ImageGlass to open as this is a limitation #272, #894
