### ISSUE TITLE
[Bug] The panels are full-screen with the Win+Up key

### ISSUE THREAD

**Issue by xmha97** [d2phap/ImageGlass#914]
The panels are full-screen with the Win+Up key
![ImageGlass](https://user-images.githubusercontent.com/23485114/100395194-4309c800-3055-11eb-9578-dcba83c7a23e.gif)

**Comment by xmha97** [comment]
@d2phap This problem does not exist in version 9.0.4.

**Comment by d2phap** [comment]
thanks!
