### ISSUE TITLE
Hope for absolutely frameless mode

### ISSUE THREAD

**Issue by QingKongBaiYu** [d2phap/ImageGlass#916]
After enable frameless mode, you can still see a border of 2px, hope this border can be hiden too.

**Comment by d2phap** [comment]
In the next version, it will be reduced to 1px.
I cannot remove the border totally, it will not be able to move the form.

**Comment by QingKongBaiYu** [comment]
> In the next version, it will be reduced to 1px.
> I cannot remove the border totally, it will not be able to resize the form.
> 
> Or, unless just toggle back to normal mode to change the size?

ok, thanks for the reply

**Comment by d2phap** [comment]
Okay so i decided to totally remove border, user will need to toggle back to normal mode to resize window
