### ISSUE TITLE
How to auto-clear clipboard to prevent continuous copy\cut

### ISSUE THREAD

**Issue by tslin89** [d2phap/ImageGlass#917]
Feature request (system setting\flag to disable continuous copy\cut\paste)

### System info:
- ImageGlass version: 7.6.4.30
- OS version: Windows 10 Home x64

### Expected behavior:
When continuous copy\paste feature is off, clipboard should clear after it is already copied to another location or another image is copy\cut.

### Actual behavior:
Pressing Ctrl+C on multiple images are loaded to clipboard and paste altogether. 

### Steps to reproduce:
1. Press Ctrl + C on multiple images
2. Press Ctrl + V on target folder

### Other info:
This behavior is not always useful unless you are trying to make selection from multiple images one time and copy to one location. Currently, if I want to copy image 1 and image 2 to folder A and image 3 to folder B, after I copied image 1 and 2 to folder A, I had to press Ctrl + ` to clear clipboard before I copy image 3 and paste at folder B else all 3 images will be copied to folder B.

**Comment by d2phap** [comment]
You can change the copy/cut behavior in [ImageGlass Moon 9.0 beta 3](https://github.com/d2phap/ImageGlass/releases/tag/9.0.3.1225) with these settings `EnableCopyMultipleFiles` and `EnableCutMultipleFiles`.
