### ISSUE TITLE
Cannot even install!!!!

### ISSUE THREAD

**Issue by BigBearLio** [d2phap/ImageGlass#92]
Hi there!
I installed 3 times the program but when I launch it there are no menus.
I cannot even use drag & drop and there is nothing clickable.
I downloaded the program version 3.2.0.16 (3.28 MB) from ww.imageglass.org/ and every time I install it, I get what you see in the screenshot attached.
My OS is 64bit Win10.
What should I do?
thank you﻿
![2016-05-27_17 18 51](https://cloud.githubusercontent.com/assets/19615824/15621749/3483777a-2431-11e6-9e32-c4b0612ed093.jpg)

**Comment by dimaaan** [comment]
Hmm, i use same version and same OS. Runs OK

**Comment by BigBearLio** [comment]
Here you go!

![2016-05-29_17 17 35](https://cloud.githubusercontent.com/assets/19615824/15636076/818d3f9c-25c1-11e6-8f98-6b3efd70f5ac.jpg)

**Comment by d2phap** [comment]
Hi!

Any error messages during installation?
Can you try deleting the configs in registry: Hkey_user/Software/PhapSoftware/ImageGlass

**Comment by d2phap** [comment]
Closed because there is no further information provided.
