### ISSUE TITLE
Add avif image support

### ISSUE THREAD

**Issue by DanRotaru** [d2phap/ImageGlass#921]
Add _avif_ image viewer support
**Avif** is new image format that use new super-compressed image type.

### AVIF Compared to JPEG and WebP
![image](https://user-images.githubusercontent.com/7759507/100859512-f92b4280-3497-11eb-8c7f-2bb343d75adb.png)

### About:
Great article about this new standart: [https://reachlightspeed.com/blog/using-the-new-high-performance-avif-image-format-on-the-web-today/](https://reachlightspeed.com/blog/using-the-new-high-performance-avif-image-format-on-the-web-today/)

**Comment by d2phap** [comment]
You can manually add AVIF extension in Settings > File type associations:

https://github.com/d2phap/ImageGlass/issues/867#issuecomment-699632416

**Comment by DanRotaru** [comment]
> You can manually add AVIF extension in Settings > File type associations:
> 
> [#867 (comment)](https://github.com/d2phap/ImageGlass/issues/867#issuecomment-699632416)

![Uploading image.png…]()

**Comment by DanRotaru** [comment]
> You can manually add AVIF extension in Settings > File type associations:
> 
> [#867 (comment)](https://github.com/d2phap/ImageGlass/issues/867#issuecomment-699632416)

![image](https://user-images.githubusercontent.com/7759507/100860437-2e846000-3499-11eb-9254-307b73925f1e.png)

**Comment by d2phap** [comment]
Ah, you need to use ImageGlass Moon,  https://imageglass.org/moon. Or wait for a week for the official release!

**Comment by DanRotaru** [comment]
> Ah, you need to use ImageGlass Moon, https://imageglass.org/moon. Or wait for a week for the official release!

Ok, why not start it by default
