### ISSUE TITLE
Ability to drag current image to copy the file into a folder

### ISSUE THREAD

**Issue by gaelanlloyd** [d2phap/ImageGlass#923]
### Is your feature request related to a problem? Please describe.
Not a problem, just a feature request.

### Describe the solution you'd like
The ability to drag the currently-viewed image out of ImageGlass and copy the file into a Windows Explorer folder.  I organize photos this way.  I believe the old Windows XP photo viewer did this.

Here's my workflow: Open ImageGlass, open a target folder for "Best of" photos.  Go through the photos using ImageGlass, when you come to one you want to save, drag it into the target folder.  ImageGlass makes a copy of the file into that folder.

### Describe alternatives you've considered
N/A

### Additional context
N/A

**Comment by d2phap** [comment]
Hi @gaelanlloyd 

You can hold <kbd>Ctrl</kbd> key and drag it to other applications or anywhere!
