### ISSUE TITLE
Installer triggers Windows Defender SmartScreen

### ISSUE THREAD

**Issue by VocifSky** [d2phap/ImageGlass#924]
### System information:
 - Windows OS version: Win 10
 - ImageGlass version: 8.0.12.8_x64.msi

### To Reproduce
1. Run installer msi
2. 
3. 
4. 

### Actual behavior:

Running the installer, Windows Defender SmartScreen prevents install, citing "Windows Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk." "App: ImageGlass_8.0.12.8_x64.msi Publisher: Unknown publisher". If you click on "More Info" you can then click on "Run anyway".

### Expected behavior:

Windows shouldn't object to running this app installer.

### Screenshots:

![Screenshot 2020-12-08 111509](https://user-images.githubusercontent.com/6521096/101530649-0be5c180-3947-11eb-9f00-47b4448615dd.png)
![Screenshot 2020-12-08 111528](https://user-images.githubusercontent.com/6521096/101530653-0c7e5800-3947-11eb-8012-9d9fff6680b5.png)

**Comment by d2phap** [comment]
Hi @VocifSky 
This is because the executable files are not signed (#97).
