### ISSUE TITLE
HEIF Rotation problem

### ISSUE THREAD

**Issue by Wolfrisger** [d2phap/ImageGlass#925]
### System information:
 - Windows OS version: win10 19042.662
 - ImageGlass version: 8.0.12.8

### To Reproduce
1. open the heif file
2. press H to open the small bottom images.

### Actual behavior:
landscape.heif : it displayed the image in portrait mode(90 degree clockwise). the bottom small image is same as big one.
portrait.heif : it displayed the image in landscape mode(90 degree clockwise), but the bottom small image is correct.

### Expected behavior:
landscape.heif should display the image in landscape mode. the bottom small image should be same.
portrait.heif should display the image in portrait mode, the bottom small image should be same.

### Screenshots:
both screenshot and heif samples here:
[heifsss.zip](https://github.com/d2phap/ImageGlass/files/5663216/heifsss.zip)

![screenshot](https://github.com/d2phap/ImageGlass/assets/3154213/049c7925-8585-4726-95b2-108fbcf5b69c)

### Additional context:
this is related to #893

**Comment by d2phap** [comment]
This issue should be fixed in the newer versions
