### ISSUE TITLE
What happened to the logo icon in version 8?

### ISSUE THREAD

**Issue by timmay7** [d2phap/ImageGlass#926]
The screenshot basically tells the story. The empty space used to be occupied by the ImageGlass logo. But since upgrading to version 8, it's gone?

![empty-space](https://user-images.githubusercontent.com/4268981/101596856-b17e4c80-39aa-11eb-82ba-d376e7d97534.png)

Very minor, but a visual annoyance.

**Comment by d2phap** [comment]
Hi @d2phap 
It's purposely hidden in the default theme Kobe.

The new theme pack API allows  user to customize and hide the logo: https://github.com/ImageGlass/theme
If you select another theme pack, the logo will be back.

If you want to have the logo on the title bar with Kobe theme, you can edit its `igtheme.xml` file, set `isshowtitlebarlogo` to `True`:
https://github.com/ImageGlass/theme/blob/master/themes/dark/Kobe/igtheme.xml#L19

**Comment by timmay7** [comment]
> Hi @d2phap
> It's purposely hidden in the default theme Kobe.
> 
> The new theme pack API allows user to customize and hide the logo: https://github.com/ImageGlass/theme
> If you select another theme pack, the logo will be back.
> 
> If you want to have the logo on the title bar with Kobe theme, you can edit its `igtheme.xml` file, set `isshowtitlebarlogo` to `True`:
> https://github.com/ImageGlass/theme/blob/master/themes/dark/Kobe/igtheme.xml#L19

Thanks, that worked in restoring the logo. My only suggestion is that in the case where the logo is hidden, I would left-align the text so that the area where the logo used to be is filled in. That's what made it look weird.

**Comment by d2phap** [comment]
Thanks @timmay7, i couldn't find a way to remove that space though. I will investigate on it.

**Comment by retrue** [comment]
Unfortunatelly, that is not the only icon missing.
In the tasks bar there is an empty space, not icon of Imageglass or mini thumbnail of the image or anything else.
See the pic.
![Captura de pantalla 2020-12-13 132429](https://user-images.githubusercontent.com/18194241/102011834-23f28200-3d47-11eb-81c5-dce9ec83d52d.png)

**Comment by d2phap** [comment]
@retrue 
- Does it happen every time?
- Can you try changing to other themes, see if the icon restored?
- Then change back to Kobe theme again?

**Comment by retrue** [comment]
I use ImageGlass portable. Yes, it happens every time. Installed theme is Kobe.
I followed your instructions, changed to Light Gray theme and the icon in the taskbar appeared. However, if I change back to Kobe theme the icon disappears again.

**Comment by d2phap** [comment]
@retrue 
Thanks for the info, there is a temporary solution, you can open `igtheme.xml` file of Kobe theme, set `isshowtitlebarlogo` to `True`:


https://github.com/ImageGlass/theme/blob/master/themes/dark/Kobe/igtheme.xml#L19

**Comment by retrue** [comment]
That worked, thanks.
