### ISSUE TITLE
Theming Issues - TitleBar Accent color and separator line

### ISSUE THREAD

**Issue by PowershellScripter** [d2phap/ImageGlass#929]
### System info:
- ImageGlass version: 8.0.12.8
- OS version: Windows 10 2009

### Expected behavior:
Change Accent Color, Titlebar changes to color desired for theme

### Actual behavior:
Title bar stays completely white

### Steps to reproduce:
1. Changed the values of the accent, dark and light
2. Even copied from original Kobe theme
3. Still nothing

### Other info:
Also, can we please get the ability to make the separator transparent. The line is rather annoying and makes everything feel cluttered

**Comment by d2phap** [comment]
Hi @NinjaRMMTheming 

The accent colors current only apply to the color of text links.
In the future, it will also apply to the selected color of the toolbar, and the thumbnail bar.

The title bar uses Windows native component, it follows system style, and unable to customize in ImageGlass theme.
You can change the title bar color in Windows Settings.


> Also, can we please get the ability to make the separator transparent. The line is rather annoying and makes everything feel cluttered

Thanks for suggestion

**Comment by PowershellScripter** [comment]
Oh, okay. Thank you! and youre welcome. Id rather see a big empty space between sections, rather than a line as it just looks much cleaner that way.
