### ISSUE TITLE
ImageGlass attempts network access even if "check for updates" is disabled

### ISSUE THREAD

**Issue by xnoreq** [d2phap/ImageGlass#930]
### System information:
 - Windows OS version: Windows 10
 - ImageGlass version: 8.0.12.8

### To Reproduce
1. Disable "check for updates"
2. Restart ImageGlass

### Actual behavior:
ImageGlass attempts network access.

### Expected behavior:
ImageGlass should not attempt network access.

**Comment by d2phap** [comment]
@xnoreq 
How do you test for network access?
I checked in Resource monitor, under Network activities, ImageGlass is not listed at all

**Comment by d2phap** [comment]
Close due to no further information provided
