### ISSUE TITLE
Allow Settings UI to follow personalized colors.

### ISSUE THREAD

**Issue by RaXorX** [d2phap/ImageGlass#933]
### Is your feature request related to a problem? Please describe.

Right now it seems to me as if the Settings UI only follows a light colored UI. That isn't helpful for people option for people opting for Dark colors.
This also poses a problem for people using customized themes (which require ultraux or secureux patching)

### Describe the solution you'd like

- Allow Settings UI to follow personalized colors set in the Imageglass config.

### Describe alternatives you've considered

- Bring a dark Settings UI along with the Light one
- Make the UI follow System all system colors, except for just the text. (I think only the text in the UI follows the system colors, whereas the background is set as grey. Since My theme uses grey colored font it's almost invisible to me, which wouldn't be if the UI also followed the colors for the background, set as black) [Scratch this one. I was mistaken about this]

### Additional context

![2020-12-11_14h52_03](https://user-images.githubusercontent.com/44987810/101886848-1495fc00-3bc2-11eb-9d25-381edf0d76d3.png)
![2020-12-11_14h58_38](https://user-images.githubusercontent.com/44987810/101886853-1790ec80-3bc2-11eb-9e94-0d925a3a41c8.png)
As you can see from the above screenshots, the Default UI has Black text in normal windows theme (Aero), while in my theme, it's almost invisible making the Settings hard to see.

EDIT: Correction in my analysis of the UI following system colors.

**Comment by d2phap** [comment]
Thanks @RaXorX 
Theming for other dialogs: Settings, About,... in the plan of next versions.

**Comment by ThomasLeigh** [comment]
Please include settings etc. within themes, it’s very hard for me (vision-wise) to configure the app, many settings are hardly visible :(

**Comment by ThomasLeigh** [comment]
Or maybe You could make it following Windows 7 theme?

**Comment by boromyr** [comment]
+1 for this correction.

**Comment by d2phap** [comment]
Close this, ImageGlass 9 already supports accent color for all controls
