### ISSUE TITLE
WEB 404 error at changelog page v8.0.8.12

### ISSUE THREAD

**Issue by fS0cW5uK4pW2dI4v** [d2phap/ImageGlass#934]
### System information:
 - Windows OS version: latest
 - ImageGlass version: latest

### To Reproduce
1. go to https://github.com/d2phap/ImageGlass/releases/tag/8.0.8.12
2. 
3. 
4. 

### Actual behavior:

404 no page found

### Expected behavior:

changelog page

### Additional context:

link at bottom of page https://imageglass.org/release/imageglass-8-0-8-12-kobe-30

alternative working link is https://github.com/d2phap/ImageGlass/releases/ (with no version number)

**Comment by d2phap** [comment]
Thanks @fS0cW5uK4pW2dI4v 
I fixed it
