### ISSUE TITLE
Problems with full screen with 8k images.

### ISSUE THREAD

**Issue by retrue** [d2phap/ImageGlass#935]
### System information:
 - Windows OS version: Windows 10.
 - ImageGlass version: Last version (8.0.12.8)

### To Reproduce
1. Open a 7680x4320 image in a monitor FullHD (1920x1080)
2. Go to Fullscreen (F11 and T) You will see the image correctly.
3. Go to next image in the gallery (in my case, an image at resolution 3840x2160). You will see it correctly too.
4. Go back to the previous image. 

### Actual behavior:

You will see small borders all around the image.

### Expected behavior:

You should see the image in fullscreen mode without borders if it has the image is bigger than the monitor resolution but has the same proportions. In this case,  to see the image again at fullscreen mode, without borders you need to press F11 twice.

### Screenshots:

See below that white border. (Well, you will have to download the image to see the white border because the background is white too, looooool)
![Sin título](https://user-images.githubusercontent.com/18194241/102012302-e8a58280-3d49-11eb-8781-fb5b49949ca4.png)

### Additional context:

It happens too if ImageGlass is in Fullscreen mode and you open one of these images with resolution bigger than 3840x2160. You will see the white borders at first try. To see the image without borders, you need to press F11 twice.
I tried another image, with resolution 4000x2250 in my monitor 1920x1080 and the behaviour is worst. In this case, you not only see the white border, but when you press F11 once the window change size but you get fullscree view with second F11.

EDIT: I have just noticed that this problem with the small white borders happens too with images of resolution 3840x2160 in my 1920x1080 monitor if the previous image doesn't is not 16:9. For example, if you have 4 images, being the first one 1920x960, 3840x2160 the second one, 1920x1080 the third one and 3840x2160 the fourth one, and you watch them in full screen mode, you will see without white margins only the two images with smaller resolution.

**Comment by d2phap** [comment]
I believe it's fixed in v9
