### ISSUE TITLE
Full screen without toolbar with just pressing F11

### ISSUE THREAD

**Issue by retrue** [d2phap/ImageGlass#936]
### Is your feature request related to a problem? Please describe.

If I am watching an image in a window, be it a maximized window or no, and the toolbar of ImageGlass is active, when pressing F11 I will see the toolbar. To see the image truly as fullscreen I will need to press T to hide the toolbar.
### Describe the solution you'd like

If I press F11 or choose Fullscreen in the menu I want to see the image without the toolbar. I alway will be able to see back the tool bar by pressing F11 again or T.

**Comment by sparrowt** [comment]
As a guess I expect the reason the toolbar isn't hidden by default is that new users might then struggle to get out of full-screen.

Hiding the toolbar by default in full screen would be a good default behaviour _if_ the toolbar re-appeared on mouse movement near the top of the screen, as is a common pattern in many applications.

**Comment by d2phap** [comment]
You can find the options in Settings > Image > Full screen in the latest build of IG Moon now: https://imageglass.org/moon

![image](https://user-images.githubusercontent.com/3154213/140269074-80e708ee-9ddf-42cd-95c5-e48a58dac0bd.png)
