### ISSUE TITLE
Make viewer's background transparent

### ISSUE THREAD

**Issue by libid0nes** [d2phap/ImageGlass#937]
### Is your feature request related to a problem? Please describe.
I'm used to using Picasa Viewer, in terms of user experience no one has come close to it yet, and I want to bring that experience to your design.

first of all it is a transparent and free user interface, in the usual image viewer every time you open an image, the software literally cuts you off from the whole system, forcing you to view images inside the software instead of doing it inside the explorer. Picasa is good in that it creates an effect where the photo just appears in the middle of the screen without cutting you off from the system and explorer.
It not only opens images easily, but it also easily lets you exit the view by just clicking outside the image, which is very convenient, no need to reach for the Esc key.

Picasa is also handy in that it makes it easy to view huge amounts of photos internally using the thumbnail bar, when you scroll through the thumbnail bar the images automatically change and you no longer have to stare at little thumbnails to find the right image, you just quickly scroll through at great speeds until your eye catches the right image.

### Describe the solution you'd like
Transparent UI.

Quick exit from the app similar to how it's implemented in Picasa (When as now in ImageGlass I can't close the software without accessing the keyboard if I'm in full screen mode).

Scrolling images at the same time as scrolling the thumbnail bar.
### Additional context
Example: 

![image](https://user-images.githubusercontent.com/3154213/103875164-0e396800-510d-11eb-94a8-8904871b5d42.png)

**Comment by Polychronopolis** [comment]
I have been following ImageGlass for years hoping for a similar adoption of Picasa features.  In addition to the thumbnail bar, I'd like to see image caption data displayed on screen.  I manage a ton of archive photos and have captions added to easily identify (and preserve) information about the image.
![Caption_Info](https://user-images.githubusercontent.com/17388157/103178672-d6037100-4852-11eb-9d4b-4ff5bf8ce358.png)
![Properties](https://user-images.githubusercontent.com/17388157/103178674-d7cd3480-4852-11eb-87da-2477a6db69f9.JPG)

**Comment by silverwings15** [comment]
great suggestions. i'd like to build on/flesh out the previous post with the following feature:

right now, the image metadata is only displayed on the titlebar, which means that it is not/will not be possible for it to show during fullscreen or in the proposed transparent view. thus, i'm suggesting a shortkey like `Tab` that will display the image metadata/exif info directly in the viewer.

here is what the implementation looks like in `Honeyview` (the X button is for closing and the other button is for copying the info to clipboard)

![image](https://user-images.githubusercontent.com/10742312/103187002-4a8eec00-48f5-11eb-8cb3-f69fbb4fd36f.png)

**Comment by d2phap** [comment]
@mimecry You can view full EXIF data in v8.0, just need to link `exiftool.exe` to ImageGlass

**Comment by fire-eggs** [comment]
RE: transparent background, see issue #548

**Comment by d2phap** [comment]
[ImageGlass Moon 9.0 beta 3](https://github.com/d2phap/ImageGlass/releases/tag/9.0.3.1225) supports transparency by the setting `BackdropStyle`. You can set it to one of these options:
- `None`: no transparency
- `Mica`: Mica effect
- `MicaAlt`: MicaAlt effect
- `Acrylic`: Acrylic effect

Only works with Windows 11 22H2.
