### ISSUE TITLE
Easier way to overwrite currently open file with changes (rotate, ...)

### ISSUE THREAD

**Issue by CombeeMike** [d2phap/ImageGlass#939]
### Is your feature request related to a problem? Please describe.
I'm oftentimes looking for a very quick way to change rotation of images whilst I'm viewing them AND saving the change in the same file. Changing the rotation is easy, however, pressing `Ctrl+S` or `Save image as...` from the file menu doesn't open the location of the file I'm currently viewing/editing but the last location I saved something to (I guess...). Whilst navigating to the correct location is not too much trouble, it feels like an unnecessary "distraction" to me.

### Describe the solution you'd like
Either change the behaviour of `Save image as...` by setting the default location of the "Save as" dialog to the location of the current file or add an explicit option (incl. some shortcut) like `Save changes to file` or something the like. Ideally this second option wouldn't even require any other input from my end (no confirmation dialog etc.), so a simple shortcut like `Ctrl+Alt+S` could just save my changes to the file...

**Comment by d2phap** [comment]
Thanks for the feedback!

I will add:
- `Save image` (Ctrl+S), will immediately save the changes without any prompts.
- `Save image as...` (Ctrl+Shift+S), will open a Save dialog with the current image location.

**Comment by fire-eggs** [comment]
I forgot to mention ... Have you tried the ImageGlass setting "Save the viewing image after rotating"? [See Settings -> Edit].

**Comment by CombeeMike** [comment]
@fire-eggs Perfect, this is even better than my proposed change which is then obsolete for me 😮
Thanks you very much for pointing this out!

**Comment by d2phap** [comment]
Ready in ImageGlass Moon https://imageglass.org/moon

**Comment by sunphoenixcmyk** [comment]
> [@fire-eggs](https://github.com/fire-eggs) Perfect, this is even better than my proposed change which is then obsolete for me 😮 Thanks you very much for pointing this out!

For those wondering, that useful setting disappeared.
