### ISSUE TITLE
Admin config causes imageglass to not load when clicking images

### ISSUE THREAD

**Issue by PowershellScripter** [d2phap/ImageGlass#943]
### System information:
 - Windows OS version: Windows 10 2009
 - ImageGlass version: 8

### To Reproduce
1. Create admin config
2. Place in program files directory
3. Try to open image
4.

**Comment by d2phap** [comment]
You can try the latest IG Moon at https://imageglass.org/moon

**Comment by PowershellScripter** [comment]
IG Moon Still does the same thing. Will not open application if igconfig.admin.xml found in program install directory. Essentially, the program doesnt have the 'Run As Admin' flag set, so when 'igconfig.admin.xml' file exists, it requires the program to run in admin mode, but in turn, it wont because the executable itself doesnt have the run as admin flag bit set on it.

I understand the premise of running in user level, but the old ImageGlass (prior to release 8) could utilize the admin config without effecting user run levels, but now it cant. ImageGlass Moon does the same thing.

**Comment by d2phap** [comment]
Can you provide more information like recorded video, or config files?
I am unable to reproduce this

![image](https://user-images.githubusercontent.com/3154213/114170760-f2d93580-9965-11eb-9852-bd8905f9a899.png)

**Comment by fire-eggs** [comment]
If ImageGlass is not appearing, then it sounds to me like an exception is causing the shutdown. We probably need to see your admin config file. Details on file ownership might also be necessary [e.g. is the user not the owner of the program files folder? who is the owner of the admin config file?]

Can you run ImageGlass itself (i.e. not double-clicking on an image)?
