### ISSUE TITLE
Tooltip of `Actual Size` Is Incorrect

### ISSUE THREAD

**Issue by chenrylee** [d2phap/ImageGlass#944]
### System information:
 - Windows OS version: Windows 10
 - ImageGlass version: 8.12.0.8 (latest)

The tooltips of button `Actual size (6)` is wrong, it shows `Scale to fit (6)`, same as `Scale to fit (5)`.

**Comment by d2phap** [comment]
I tried but could not reproduce this.
Do you have screenshot?

**Comment by chenrylee** [comment]
@d2phap  Can't reproduce it either, maybe a coincidence, or I misread `Scale to fill` to `Scale to fit` .
