### ISSUE TITLE
Windows Store app as "edit" program with shortcut (.lnk-file) shows error but works

### ISSUE THREAD

**Issue by Countryen** [d2phap/ImageGlass#945]
### System information:
 - Windows OS version: Windows 10 Home, 20H2, 9042.685,120.2212.551.0
 - ImageGlass version: 8.0.12.8 [Portable]

German System, please ask if I should translate anything.

### To Reproduce
1. Open ImageGlass
2. Open "Einstellungen" > "Bearbeiten"
3. Click "Alle Erweiterungen bearbeiten..."
4. Enter <any> in "Programmname" and click "..." next to "Programmpfad"
5. Select a .lnk file (shortcut)

### Actual behavior:
Shows error "Schwerwiegender Fehler".

### Expected behavior:
Maybe it should not work with .lnk-files? 
It does work if I enter the path to the file manually.

Example: `"P:\paint.net.lnk" "D:\Clouds\OneDrive\Bilder\Eigene Aufnahmen\20190630_234658.jpg"`

Works -> Pressing "E" on an open image opens paint.net.

### Screenshots:
![image](https://user-images.githubusercontent.com/11256873/102632334-3c9bd700-414f-11eb-9586-8f8e5957233a.png)

### Additional context:
Not to be confused with #832.

Why I use .lnk-files? I have paint.net installed as an windows store application and no access to any actual EXE file.
Any other way to specify a Windows Store (UWP) app as the edit-program?

Since the workaround is easy (enter path manually) it's in no way important but might also be really easy to fix.

**Comment by d2phap** [comment]
Thanks @Countryen 
This is interesting

**Comment by d2phap** [comment]
This request is ready in IG Moon: https://imageglass.org/moon

#### Settings > Edit
- Add support for `*.lnk` extension, environment variables (relative paths). You can use command for App path, e.g. `cmd`, `cmd.exe`, `imageglass`, ...
- Add support for selecting multiple extensions to edit

![image](https://user-images.githubusercontent.com/3154213/116801951-57407c80-ab41-11eb-8fec-c767df12f254.png)

**Comment by Countryen** [comment]
Awesome news :) Good job
