### ISSUE TITLE
Please change the slideshow shortcut back to F11

### ISSUE THREAD

**Issue by cpz3501** [d2phap/ImageGlass#947]
### Is your feature request related to a problem? Please describe.

In ImageGlass 7.6.4.30, the slide show used to be on F11, which is much more logical for a photo viewer, since it is practically the "real" full screen mode.

### Describe the solution you'd like

Revert #551

### Describe alternatives you've considered

Add custom keybind.

### Additional context

I'm pretty sure the majority of people would prefer the previous shortcuts as it is the standard in most software (browsers, video players, games). 
Imageglass is great, but please fix that.

**Comment by d2phap** [comment]
F11 is more used for Fullscreen (browser, file explorer,...) so I will stick to this.
About your request for the custom keybind, let's follow this ticket #608
