### ISSUE TITLE
Significantly degraded image quality of zoomed photos

### ISSUE THREAD

**Issue by MarcelBigger** [d2phap/ImageGlass#949]
### System info:
- ImageGlass version: 8.0.12.8
- OS version: 10.0.18363

### Expected behavior:
Zoom does not produce jagged lines and other quality degrades

### Actual behavior:
Zoom does produce jagged lines and other image quality degrades as compared to the Microsoft Photos app

### Steps to reproduce:
1. Load the same photo in the ImageGlass and Microsoft Photos apps
2. Apply the same zoom level to both
3. Show the same photo section for comparison
4. Take special note of jagged "N" in the world "CANDLEMAKER"

### Other info:
Side-to-side comparison of zoomed photos in lossless TIF attached in a ZIP archive

![image](https://user-images.githubusercontent.com/3154213/102899483-eb207e80-44a5-11eb-9419-7997ee106e01.png)

**Comment by d2phap** [comment]
Hi @mwbigger 

You can change the zoom optimization from `Auto` to `Smooth pixels` in Settings > Image > Zoom optimization:

![image](https://user-images.githubusercontent.com/3154213/102899316-b3193b80-44a5-11eb-8524-81976737cfca.png)

**Comment by MarcelBigger** [comment]
OK, the setting "Smooth pixels" resolves the jaggedness but makes the photo now blurry (as compared to Microsoft Photos). I've now discovered the article in your Google Groups forum on the topic: ImageGlass definitely needs more sophisticated resampling options to complement its zoom function.

[2020-12-22_17-01-51.zip](https://github.com/d2phap/ImageGlass/files/5730852/2020-12-22_17-01-51.zip)

**Comment by brunogm0** [comment]
Hi to contribute more in this issue [here ](https://photosauce.net/blog/post/examining-iwicbitmapscaler-and-the-wicbitmapinterpolationmode-values) an analysis of the  "zoom interpolation methods~ from  Windows Imaging Component.  
Some are broken most are slow...  
So how about integrating THE  fastest library [MagicScaler](https://github.com/saucecontrol/PhotoSauce ). It also uses the least memory from the benchmark.

 *MagicScaler Load, Resize, Save(1)           |  69.82 ms | 
| System.Drawing Load, Resize, Save(2)     | 378.48 ms |
| ImageSharp Load, Resize, Save(3)            | 246.56 ms |
| ImageMagick Load, Resize, Save(4)         | 398.36 ms | 
| ImageFree Load, Resize, Save(5)              | 253.21 ms | 
| SkiaSharp Canvas Load, Resize, Save(6)   | 143.41 ms |
| SkiaSharp Bitmap Load, Resize, Save(6)   | 143.21 ms |
| NetVips Load, Resize, Save(7)                  | 139.27 ms |

**Comment by d2phap** [comment]
ImageGlass is using .NET interpolation algorithms, I will not write custom ones.
In the latest build of IG Moon, I added all options for Zoom optimization:
![image](https://user-images.githubusercontent.com/3154213/108621991-07727480-7471-11eb-8b36-21273e02efa7.png)

High quality options can cause performance issue.
Download at: https://imageglass.org/moon

**Comment by imrigp** [comment]
@d2phap 
Seems like this setting is gone, and the smooth quality is degraded. Any chance of bringing it back?

**Comment by d2phap** [comment]
@imrigp, it's in Settings > Viewer > Zooming: You can use "Linear" or "Multi-sample Linear"
![Image](https://github.com/user-attachments/assets/14cf3221-75be-4579-be0f-eb280427c9af)
