### ISSUE TITLE
"Save As" default path

### ISSUE THREAD

**Issue by attikov** [d2phap/ImageGlass#952]
"Save As" should have and option if the save dialog should use "last dir" or "image dir"

**Comment by d2phap** [comment]
I added a shortcut to open the current folder of viewing file.
Download the latest build at https://imageglass.org/moon

![image](https://user-images.githubusercontent.com/3154213/106278835-5bc17480-6276-11eb-95fa-b55c457fcff6.png)

**Comment by attikov** [comment]
I appreciate your efforts but you have to understand that this is very far from what I have asked.
I was already able to select the directory where I want to save the image, but using the last save dir by default
is against common sense, unexpected, contra productive, without any logic and annoying.
Example: try to mass edit (rotate, whatever) some images in separate directories. (Like icons)
Every time you want to save the new image, the default dir is the dir of the previous image.
That is just wrong.

**Comment by pmcstjean** [comment]
the only thing that makes sense on a "save as" for any software, is to be in the same folder as the current file being saved as
