### ISSUE TITLE
New method for zooming an image

### ISSUE THREAD

**Issue by rahmanshaber** [d2phap/ImageGlass#953]
It's always extra step to hold down the ctrl and scroll to zoom.

Holding the right mouse button and scroll to zoom is a good solution to it, as it does not involve 2 hands for simple task as zoom.

This way is fast and don't have to use keyboard at all. All can be done using the mouse.

I learned about this navigation from this app [pdflite](http://www.pdflite.com/), and using it for many years. I think adding this option in the mouse navigation section in settings will be very productive.

**Comment by d2phap** [comment]
ImageGlass already provides many ways for zooming: Scroll, Ctrl/Shift/Alt + Scroll, hotkey,... I don't have plan to support this
