### ISSUE TITLE
Some .pgm type P2 files cannot be opened

### ISSUE THREAD

**Issue by slobodaapl** [d2phap/ImageGlass#954]
### System information:
 - Windows OS version:  Windows 10 build 19041.685
 - ImageGlass version: 8.0.12.8

It seems that opening certain .pgm (P2) files is currently bugged. A file with a correct format cannot be opened.

### To Reproduce
Open a  .pgm file of type P2.

### Actual behavior:
A correctly formatted .pgm type P2 file is reported as unsupported or corrupted by the software.

### Expected behavior:
The file opens and displays correctly without errors.

### Additional context:
Example that doesn't work:
```
P2
# Shows the word "FEEP" (example from Netpbm man page on PGM)
24 7
15
0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
0  3  3  3  3  0  0  7  7  7  7  0  0 11 11 11 11  0  0 15 15 15 15  0
0  3  0  0  0  0  0  7  0  0  0  0  0 11  0  0  0  0  0 15  0  0 15  0
0  3  3  3  0  0  0  7  7  7  0  0  0 11 11 11  0  0  0 15 15 15 15  0
0  3  0  0  0  0  0  7  0  0  0  0  0 11  0  0  0  0  0 15  0  0  0  0
0  3  0  0  0  0  0  7  7  7  7  0  0 11 11 11 11  0  0 15  0  0  0  0
0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
```

[img.zip](https://github.com/d2phap/ImageGlass/files/6251165/img.zip)

**Comment by d2phap** [comment]
Hi @slobodaapl 
Can you attach the file?
Thanks!

**Comment by slobodaapl** [comment]
[img.zip](https://github.com/d2phap/ImageGlass/files/6251161/img.zip)

Sure! Here you go. The image's contents are identical to that provided in Additional context.

**Comment by d2phap** [comment]
It seems that Magick.NET does not support this file
![image](https://user-images.githubusercontent.com/3154213/114060559-15b50c80-98c8-11eb-9b25-1531c14eeeb5.png)

**Comment by slobodaapl** [comment]
Yeah it seems so. Though it's very similar in structure to .PGM P1 files. Any possibility of implementing support for it?.. Or is ImageGlass strictly dependent on Magick.NET?

**Comment by d2phap** [comment]
@slobodaapl Sorry it takes me long time to reply this. Since this is upstream issue, you can report it to https://github.com/dlemstra/Magick.NET
