### ISSUE TITLE
HDR images are too dark / colors are way off

### ISSUE THREAD

**Issue by ASOwnerYT** [d2phap/ImageGlass#956]
### System information:
 - Windows OS version:  20H2
 - ImageGlass version: 8.0.12.8

### To Reproduce
1. Open any HDR image in both ImageGlass, and mostly any other image viewers (such as the Windows 10 default image viewer)
2. Compare the two, and in ImageGlass the image is way darker than it should

### Actual behavior:

When I view an OpenEXR image in ImageGlass, the colors are way off, and it appears darker. This also happens when I convert the OpenEXR image to PNG using [AConvert](https://www.aconvert.com/image/), so I think it is because it is an HDR image.

### Expected behavior:

The image colors should look the same to when it is viewed in the Windows 'Photos' app. 

### Screenshots:

![image](https://user-images.githubusercontent.com/23545044/103740293-d8887680-505b-11eb-80f4-d76d405edf53.png)

### Additional context:

OpenEXR image file: https://mega.nz/file/7f5QBAjb#BIzLjO4ZbWsQRHbtTaLmvK4WS9O1JXffzjQWng_Xb-0

**Comment by robinfriedli** [comment]
I have the same problem with JXL files containing HDR content created by Mirillis Action:
![image](https://user-images.githubusercontent.com/29976416/188317494-d20d2156-b55d-4967-b6e2-54086f50f408.png)
(of course the right side looks a bit off / washed out in an SDR screenshot, but it's closer to what it should look like).

Here's the jxl image: https://mega.nz/file/tXlkRJBb#PmEpeJwc3z9vHeBisy6f0OaMDDrh4T_HXAYBQWUsyyA
Here's an SDR PNG of how it should look like: https://mega.nz/file/lHtHXAwD#z5G4PIw4cjKX1B15ITYzuTW2W95VoAJQ-gPVYkpXwuE

**Comment by pedrodeleo** [comment]
I'm having the exact same problem with EXR images, colors are way too dark! It's weird because it didn't use to be like that, ImageGlass was my favorite image viewer by far because of the EXR/HDR capabilities but now I can't use it anymore. Any chance to update this?

**Comment by d2phap** [comment]
@ASOwnerYT tested you EXR image with [ImageGlass 9.0 beta 2](https://github.com/d2phap/ImageGlass/releases/tag/9.0.2.904), the color seems correct.

![image](https://user-images.githubusercontent.com/3154213/195751285-99890f65-4941-4626-9daf-2fad5e248861.png)

**Comment by d2phap** [comment]
@robinfriedli 
I open your JXL with GIMP 2.10.32 (revision 1) and ImageGlass 9.0 beta 2, both render the same.
Can you try opening it in other viewers?

![image](https://user-images.githubusercontent.com/3154213/195753136-79a1b05f-cf3b-4968-b1cf-b64dba5de448.png)

**Comment by pedrodeleo** [comment]
I just tested the 9.0 beta 2 and it looks like this problem is fixed!!
The image sequence on the bottom still looks too dark but the main image looks accurate! Great job!
![Screenshot 2022-10-14 153757](https://user-images.githubusercontent.com/115746302/195874040-cb2d43aa-1628-42e0-95f1-5c8099eef3fa.png)
(LEFT SIDE: ImageGlass 9.0 beta 2, RIGHT SIDE: DJV 2)

Happy to go back to my favorite image viewer :)

**Comment by d2phap** [comment]
Thanks @pedrodeleo!
