### ISSUE TITLE
Make "Open image location" feature more accessible

### ISSUE THREAD

**Issue by Ailothaen** [d2phap/ImageGlass#958]
Hello,

I have been searching for this feature for some time, and I eventually found it:

![20210106-235323-001755](https://user-images.githubusercontent.com/11133116/103828047-8e62bd80-507a-11eb-85a7-161554771063.png)

Something I am often doing with ImageGlass is going through folders that have a lot of images in them (hundreds, or even thousands sometimes). Depending on the context, when I come across a relevant image, I may do something with the file (copy it somewhere else, remove it...). The feature "open image location" is great for that because it opens the folder and automatically selects the file, avoiding me to search for the right file in the window.

However, I feel like this feature is still not very accessible. The proposed shortcut (Ctrl+Shift+L) still feels quite complicated, and it is the only way to access this feature.
Something that would really nice to improve that would be:
- An available button in the sidebar that would perform this action
- A more simple shortcut (`Ctrl+SomeLetter` or even `SomeLetter`)

Thank you for your time and the amazing work on ImageGlass!

**Comment by d2phap** [comment]
Thanks @Ailothaen 
FYI, This function is also accessible in context menu.

**Comment by d2phap** [comment]
The shortcut changed from <kbd>Ctrl+Shift+L</kbd> to <kbd>L</kbd> in v8.1
