### ISSUE TITLE
ImageGlass app needs icon in taskbar preview

### ISSUE THREAD

**Issue by KaranKad** [d2phap/ImageGlass#959]
### System information:
 - Windows OS version: 20H2
 - ImageGlass version: 8.0.12.8
### Problem:
Imageglass app does not have a icon in taskbar preview.
### Screenshots:
![Screenshot 2021-01-07 121228](https://user-images.githubusercontent.com/71691514/103860492-b6393c00-50e1-11eb-9fce-896aa37c0859.jpg)

**Comment by d2phap** [comment]
I don't think other apps have an icon:

![image](https://user-images.githubusercontent.com/3154213/103894115-67af9000-5129-11eb-8ff9-61edc3dfbb31.png)

**Comment by KaranKad** [comment]
### Windows has settings for taskbar where it does not show icon and app name on the top like your current one.
![image](https://user-images.githubusercontent.com/71691514/103895290-3083b380-5116-11eb-97bf-9aef02967750.png)
### Mine is set to always hide label so it shows app name and icon on the top.
![image](https://user-images.githubusercontent.com/71691514/103895397-5d37cb00-5116-11eb-9b1d-82a55d94d2cb.png)

**Comment by d2phap** [comment]
fixed this in v8.1
