### ISSUE TITLE
Previous / Next Image with arrow keys also pan the view.

### ISSUE THREAD

**Issue by VoxSerico** [d2phap/ImageGlass#963]
### System information:
 - Windows OS version: Windows 10 Pro v2004 build19041.685
 - ImageGlass version: 8.0.12.8

### To Reproduce
1. Set Keyboard setting "Left / Right arrows" to "Previous / Next Image"
2. Open an image in a folder with other images
3. Zoom in far enough for panning to work and lock the zoom ratio.
4. Hold (Single press is more subtle to see) Left or Right arrow key.

### Actual behavior:
Next image is presented, but continually pans left or right when held. (The next image is panned a single "step" when the arrow key is pressed instead of held.)
When the arrow key is held, the currently displayed image may pan more than one step if the next image takes longer to load.

### Expected behavior:
Next image is presented without panning a step in the chosen arrow direction. The program repeatedly switches to the next image when the chosen arrow key is held.

### Additional context:
Discovered this bug while switching between two images that are larger than the program window to compare small differences between them. I noticed that the image would be shifted one pan "step" in the left/right direction on identical images.

Changing the "Left / Right arrows" setting to "Pan Left / Right" stops the next/previous image from being shown, but then I can no longer switch images with the arrow keys like desired and instead have to move my hand to the page up / down keys.

**Comment by fire-eggs** [comment]
Damn, you're right! I was sure I had it covered but I was wrong! Thanks!

**Comment by fire-eggs** [comment]
Fix is available in ImageGlass Moon 8.1.1.21 and later.
