### ISSUE TITLE
Key Shortcut for Always on Top

### ISSUE THREAD

**Issue by RanArkon** [d2phap/ImageGlass#970]
Hi,

Please make Key Shortcut for Always on Top feature.

**Comment by d2phap** [comment]
Your request is implemented in the latest build of IG Moon: https://imageglass.org/moon
- Main menu hotkey to **Alt+F**
- Keep window always on top: **`**

**Comment by CarloApri** [comment]
> Your request is implemented in the latest build of IG Moon: https://imageglass.org/moon
> 
> * Main menu hotkey to **Alt+F**
> * Keep window always on top: **`**

how about a shortcut like ALT + something or whatever. Can we also specify a json button to get a "always on top toggle"? Thanks!

**Comment by d2phap** [comment]
@carlox97 refer to this for hotkey customization in v9: https://github.com/d2phap/ImageGlass/discussions/1702#discussioncomment-7660806
