### ISSUE TITLE
Little scrolling improvements

### ISSUE THREAD

**Issue by mirh** [d2phap/ImageGlass#974]
- [x] A new action (at least for PgUp/PgDn keys) to straight-away jump at the top/bottom of the current image. 
- [x] A new setting to adjust scrolling speed. I know ctrl/shift modifiers for "bigger skips than simple arrow keys" already exist, but they are just too unsmooth to still keep track of long text lines you are reading, if I can explain.

**Comment by d2phap** [comment]
Add panning speed options in Settings > Image (#1286).
Deployed to the latest build of IG Moon: https://imageglass.org/moon

![image](https://user-images.githubusercontent.com/3154213/154062970-f04f6635-c067-40be-821f-f1d47ccaaff5.png)

**Comment by d2phap** [comment]
Smooth panning is improved in [ImageGlass Moon 9.0 beta 3](https://github.com/d2phap/ImageGlass/releases/tag/9.0.3.1225)

![image](https://user-images.githubusercontent.com/3154213/209428266-fa96f203-8b56-4053-88bc-849a6526573a.png)

**Comment by mirh** [comment]
Not the nicest looking walk in the park when you still don't have a settings panel and everything must be somewhat confined to the drop-down menu, but this is still really nice. Thanks.
