### ISSUE TITLE
HEIC images with YUV444P8/10 colorspace doesn't present correct chroma resolution when open with ImageGlass.

### ISSUE THREAD

**Issue by Mr-Z-2697** [d2phap/ImageGlass#977]
### System information:
 - Windows OS version: Windows10 1909 Pro
 - ImageGlass version: Moon_8.1.1.21_x64

### To Reproduce
1. Open a YUV444 HEIC image.
2. Zoom to 100% (if not).
3. See blocks in color.

### Actual behavior:
1. YUV444 is somehow converted to YUV420 then to actual RGB.
2. And, blocks are caused by point resize is used when upscaling chroma planes, this also appears in YUV420 HEIC images (which might be a bigger issue since they are more common).

### Expected behavior:
Present YUV444 with real full chroma resolution.

### Screenshots:
![ImageGlass](https://user-images.githubusercontent.com/74594146/105609730-2fc17180-5de6-11eb-8d69-da9909eb9ebc.png)

### Additional context:
GIMP 2.10.22 is doing it right.
![GIMP](https://user-images.githubusercontent.com/74594146/105609734-33ed8f00-5de6-11eb-97bb-4f75a95f370b.png)

Sample YUV444P10 HEIC file:
[78265291_p0.zip](https://github.com/d2phap/ImageGlass/files/5860687/78265291_p0.zip)

**Comment by Mr-Z-2697** [comment]
Sorry, seems that it all depends on ImageMagick, I might be in the wrong place.

**Comment by d2phap** [comment]
Honestly, I don't see any difference.
Can you help to point out? 😅

![image](https://user-images.githubusercontent.com/3154213/105620182-f6642280-5e34-11eb-8d25-a23f518b6780.png)

**Comment by Mr-Z-2697** [comment]
> 
> 
> Honestly, I don't see any difference.
> Can you help to point out? 😅
> 
> ![image](https://user-images.githubusercontent.com/3154213/105620182-f6642280-5e34-11eb-8d25-a23f518b6780.png)

Thanks for your reply!
Please zoom in to 100% and look at those red areas.
ImageGlass:
![ig](https://user-images.githubusercontent.com/74594146/105620911-e2242380-5e3c-11eb-9432-8781044d26dc.png)
GIMP:
![gimp](https://user-images.githubusercontent.com/74594146/105620913-e2bcba00-5e3c-11eb-963b-b214ba9ee7ea.png)

**Comment by fire-eggs** [comment]
It is subtle but I can see it on _one_ of my monitors. IG looks "more red" than GIMP. There is also a difference in skin tone: the IG version looks "more tanned".

But not my other monitor. I'm not sure what that means - color calibration?

**Comment by Mr-Z-2697** [comment]
> It is subtle but I can see it on _one_ of my monitors. IG looks "more red" than GIMP. There is also a difference in skin tone: the IG version looks "more tanned".
> 
> But not my other monitor. I'm not sure what that means - color calibration?

Were you saw this two kind of "color tone"? (please be sure to open original png image)

This is another story: bt709 and bt601 (bt470bg) matrixs used in RGB <==> YUV conversion.
The "more red" color may be caused by "RGB ==(bt601)==> YUV ==(bt709)==> RGB" uncorrect process.

I chose **bt601** to convert my image, and I've tagged this info in the image, if image viewers are ignoring this info and use bt709 anyway, the result will be inaccurate.
This might just a rare case though, since it only happeds in one ~computer~ monitor. (wait? monitor? does they connected to the same computer?)

And the reason why I chose bt601 is... it seems GIMP and XnView are using **bt601** to do YUV ==> RGB by default when opening HEIC, and are ignoring tagged info. 
But a lot of HEIC encoder and viewer are using bt709 by default, as well as ignoring tagged info, what a mess...
So, I think we can skip that problem for now, just wait for them to reach a consensus?

Original file:
![78265291_p0](https://user-images.githubusercontent.com/74594146/105637441-87c0ac80-5ea8-11eb-95ef-d06759ab55d8.png)
Convert to YUV using bt601 then convert to RGB using bt709:
![470bg-yuv-use-709-to-convert](https://user-images.githubusercontent.com/74594146/105636395-33ff9480-5ea3-11eb-9dea-a556b7fa84d2.png)

**Comment by Mr-Z-2697** [comment]
Is that I noticed the blocky color because I'm still using "1080p garbage"?😢

**Comment by fire-eggs** [comment]
>Were you saw this two kind of "color tone"? (please be sure to open original png image)

I'm sorry, I seem to be doing this wrong. I was looking at the screen cap posted by Phap, showing the two side-by-side. I can see the problem (and the skin tone difference) in that cap.

I have two monitors connected to my computer. I can get slightly different color behavior depending on which monitor I look at, due to differences in the monitors and/or monitor configuration.

When GIMP 2.10.22 finishes downloading, I'll take a look with the original file. (GIMP 2.10.14 won't load it.)

**Comment by dlemstra** [comment]
This should be fixed with an upgrade to the most recent version of Magick.NET.

**Comment by d2phap** [comment]
Thanks @dlemstra !
@Mr-Z-2697, you can try the latest build of IG Moon at https://imageglass.org/moon

**Comment by Mr-Z-2697** [comment]
> Thanks @dlemstra !
> @Mr-Z-2697, you can try the latest build of IG Moon at https://imageglass.org/moon

The problem is solved, thank you!
