### ISSUE TITLE
Make exiftool tag selection configurable

### ISSUE THREAD

**Issue by pwhnz** [d2phap/ImageGlass#978]
I am enjoying ImageGlass and exiftool.

It would be nice if there was an option to display selected exif tags in the exiftool window. For example, using exiftool from the command line I can get my favorite data by going: "exiftool -Model -LensID -FocalLength35efl -MeteringMode -WhiteBalance -ISO -Aperture -ExposureTime DSC_3362.JPG".

A config file where you list the tags you want seems like the simplest way, from a user perspective.

I have searched but couldn't find any existing solution.

Philip.

**Comment by d2phap** [comment]
This feature is ready in IG Moon:
https://imageglass.org/moon


![image](https://user-images.githubusercontent.com/3154213/110205609-e0299780-7eb3-11eb-9734-477248d7aa22.png)

**Comment by pwhnz** [comment]
Tried it out, works great. Nice easy config. So good, thanks.
