### ISSUE TITLE
Viewing an image prevents another program from writing to the image

### ISSUE THREAD

**Issue by daveloyall** [d2phap/ImageGlass#98]
I think ImageGlass opens the current image file for reading/writing.  That prevents another application from writing to the file.

I'm using virtualbox on a Windows host with a GNU guest.  Virtualbox uses a weird kernel module for guest/host file sharing, so it's possible that the same problem wouldn't occur on a windows-only setup, but I can't confirm that easily.

**Comment by daveloyall** [comment]
One solution would be to open the file only for reading by default and then re-open as read-write if the user tries to change the image.  Closing the file and re-opening it as read-only after writing to the file would be very nice!

**Comment by d2phap** [comment]
Current version of ImageGlass opens image file for reading only, then it tries to cache it into memory
