### ISSUE TITLE
When installing the program, it looks like this. It does not work

### ISSUE THREAD

**Issue by antoniomtnez** [d2phap/ImageGlass#980]
### System information:
 - Windows OS version: 8.1
 - ImageGlass version: 8.0.12.8

### To Reproduce
1. Install
2. Open

![2021-02-06_175639](https://user-images.githubusercontent.com/38137118/107131613-fa1c8e00-68a5-11eb-8166-2a510b672db9.jpg)

**Comment by d2phap** [comment]
You need to install .NET Framework 4.8 or later 

https://dotnet.microsoft.com/download/dotnet-framework/net48
