### ISSUE TITLE
Adobe Reader / PDF icon is being replaced with ImageGlass's ICO icon

### ISSUE THREAD

**Issue by Arudinne** [d2phap/ImageGlass#982]
### System information:
 - Windows OS version: Windows 10 LTSC (1809)
 - ImageGlass version: 8.0.12.8

### To Reproduce
1. Install ImageGlass
2. Set ImageGlass's File Type Assocations
3. Reboot
4. Open a PDF

### Actual behavior:
The Installation of ImageGlass seems to be replacing the icon settings for Adobe Reader DC somewhere.

### Expected behavior:
Adobe Reader icon would remain unchanged.

### Screenshots:

![Adobe DC Shortcut](https://user-images.githubusercontent.com/29390020/107540826-1cefc080-6b8c-11eb-8d71-e809d3e35ef9.jpg)
![Adobe DC](https://user-images.githubusercontent.com/29390020/107540847-1feab100-6b8c-11eb-8f62-f2c2ea69a8af.jpg)

### Additional context:

I didn't see anything else reported that looked similar when I searched for the issue.

I saw this once before on a different computer when considering the use of ImageGlass 7.5 as a replacement for Windows Photo Viewer on Windows 10 LTSB but didn't have time to troubleshoot the issue at the time.

**Comment by tferrerm** [comment]
The same happened to my Transmission Qt client desktop icon right after installing the program. It seems to affect shortcuts with a non-editable target (Don't really know the difference between these shortcuts and regular ones other than the fact they are created by a program installer).

![image](https://user-images.githubusercontent.com/26530657/109028051-2f93ea80-76a0-11eb-96bc-6c3d03eb0f72.png)

**Comment by d2phap** [comment]
You can try going to Settings > File type associations, click on Unregister extensions button to remove the extensions in registry, then click on Set as Default photo viewer button again to re-register them

**Comment by Arudinne** [comment]
> You can try going to Settings > File type associations, click on Unregister extensions button to remove the extensions in registry, then click on Set as Default photo viewer button again to re-register them

I've actually since removed ImageGlass because I found it had replaced the icon for our AnyDesk client as well. Both programs now show the generic icon for an application that doesn't have it's own icon now. So whatever occurred seems to be somewhat permanent.

![image](https://user-images.githubusercontent.com/29390020/109665373-b3802380-7b33-11eb-890c-01676b7feee6.png)

EDIT: Reinstalled Adobe just now and it seems to have fixed the icon, so at least that was easy.

**Comment by Arudinne** [comment]
I've stripped the external icons from my local copy of the MSI and reinstalled. So far the issue has not reoccured.

**Comment by tferrerm** [comment]
Changing the file association of the .ico format to Paint (for example) restores the right icon. Changing it to ImageGlass again however makes the same ImageGlass icon reappear.

**Comment by xmha97** [comment]
@d2phap 
This problem is related to Adobe Acrobat and is outside the scope of ImageGlass.
Also, this issue has also been resolved in the latest version of Adobe Acrobat Pro.

**Comment by d2phap** [comment]
Thanks @xmha97!
Similar issues also resolved here https://github.com/d2phap/ImageGlass/issues/664#issuecomment-1022305280
