### ISSUE TITLE
Settings | Toolbar | Apply button doesn't work

### ISSUE THREAD

**Issue by SteveThackery** [d2phap/ImageGlass#986]
### System information:
 - Windows OS version: 10.0.19042 Build 19042
 - ImageGlass version: 8.0.12.8

### To Reproduce
1. Click Menu button, then Settings, then Toolbar
2. Add any item from the 'Available Buttons' column to the 'Current Buttons' column by selecting and clicking the right arrow icon
3. Visually confirm that it is now in the 'Current Buttons' column
4. Click the 'Apply' button, bottom right

### Actual behavior:

The toolbar is not updated.

### Expected behavior:

The toolbar should be updated.

### Screenshots:

N/A

### Additional context:

N/A

**Comment by d2phap** [comment]
@SteveThackery 
When you click on Apply button, the settings are saved in memory. And when you focus on the viewer window, you will see the changes.

**Comment by SteveThackery** [comment]
Thank you, d2phap.  However, this is not really "standard" behaviour for a Windows program with this feature: normally you would expect to see the window update without having to focus it first.

However, if this is "as designed", please feel free to close this report.

**Comment by d2phap** [comment]
Thanks @SteveThackery 
Let's close this for now
