### ISSUE TITLE
Uncheck "Auto-center the window in Window Fit mode" in setting doesn't work.

### ISSUE THREAD

**Issue by flyxyz123** [d2phap/ImageGlass#987]
I uncheck "Auto-center the window in Window Fit mode" in the setting but it doesn't work. The window still auto center when using Window Fit mode. The `IsCenterWindowFit` value in `igconfig.xml` file is updated when I reopen the software. So I think it's not the problem. I looked at the code and find this.

https://github.com/d2phap/ImageGlass/blob/0e0711a5e00d00c38532b79457df62251e76e7f9/Source/ImageGlass/frmMain.cs#L2141-L2146

I'm not sure what's the purpose of this code here `|| fullW > screen.WorkingArea.Width || fullH > screen.WorkingArea.Height` . I think delete this code might solve the problem but I don't know how to compile and check it. The following code is after the edit.

```
 // center window to screen 
 if (Configs.IsCenterWindowFit) { 
     App.CenterFormToScreen(this); 
 } 
```

**Comment by flyxyz123** [comment]
I build the program and tested it with #988 and it fixed the problem.

**Comment by d2phap** [comment]
Thanks @flyxyz123 
I will check it tomorrow!
