### ISSUE TITLE
SVG looks blurry instead in a vector form

### ISSUE THREAD

**Issue by Ronald-G-Andrade** [d2phap/ImageGlass#989]
### System information:
 - Windows OS version: Windows 10 Enterprise - 21H1 - 64 bits
 - ImageGlass version: 8.0.12.8 - Kobe

### To Reproduce
1. Open a SVG File
2. Zoom In the file

### Actual behavior:
It won't show the vector form in a SVG file

### Expected behavior:
To be seen like in every browser, in other words, make infinite zoom and see fine the vector image.

#### Firefox
![image](https://user-images.githubusercontent.com/3154213/108790474-bb7e1780-75b7-11eb-97cb-7a89ac839109.png)

#### ImageGlass
![image](https://user-images.githubusercontent.com/3154213/108790465-b6b96380-75b7-11eb-9c57-9316c3482b11.png)

**Comment by d2phap** [comment]
Hi @Ronald-G-Andrade 
ImageGlass does not support scaling SVG yet, please refer to #421 for future update

**Comment by Ronald-G-Andrade** [comment]
> 
> 
> Hi @Ronald-G-Andrade
> ImageGlass does not support scaling SVG yet, please refer to #421 for future update

Hello dear d2phap, thank you very much for your quick response :) 

Oh, that's strange, because I really can open a SVG file (but as I wrote above, it looks blurry, not vector).
