### ISSUE TITLE
Flip Image Horizontal / Vertical

### ISSUE THREAD

**Issue by karma12gaming** [d2phap/ImageGlass#99]
Suggestion: Add button to flip image horizontally. Add button to flip image vertically. Ideally these would be added after the rotate left / right function.

**Comment by fire-eggs** [comment]
[ImageGlass Moon](https://imageglass.org/moon) has Flip Horizontal / Vertical ability. The toolbar icons are not set up correctly in 5.5.9.5, but the menus work fine.

**Comment by d2phap** [comment]
Added icons. Ready for test in IG Moon v5.5.11.23
