### ISSUE TITLE
Drag & drop from the thumbnail panel

### ISSUE THREAD

**Issue by Zeus64** [d2phap/ImageGlass#990]
It's could be very good if we can do drag & drop from the thumbnail panel (for example drag from the thumbnail panel and drop it in the word document). I guess it's must not be very complicated to implement as we know the file location

**Comment by gerroon** [comment]
I hope to see this feature as well.

**Comment by d2phap** [comment]
This feature is implemented in the ImageGlass Moon v9.0 beta 1: https://github.com/d2phap/ImageGlass/releases/tag/9.0.1.514.
You can just drag a thumbnail and drop it to any windows.

**Comment by Zeus64** [comment]
thanks @d2phap
