### ISSUE TITLE
Need an option to define custom action when double clicking on a Image

### ISSUE THREAD

**Issue by Zeus64** [d2phap/ImageGlass#991]
In setting we can define what to do when we scroll the wheel but nothing to define what to do when we double click on the image. Personally I would like to define an option like : "open image location & close ImageGlass" when I double click on the image (instead of the actual behavior to set the image at full size).

**Comment by fire-eggs** [comment]
Mickey N<mickeysworkemail@gmail.com> Apr 19, 2021, 10:17:32 PM (2 days ago) 
to ImageGlass Community
Is there a way to change double click behavior when viewing an image? I would like it to go to full screen and hide the toolbar. Double clicking again would return to windowed with toolbar.

**Comment by d2phap** [comment]
[v9.0 beta 2](https://github.com/d2phap/ImageGlass/releases/tag/9.0.2.904) adds support for mouse action customization with this setting:

### Example 1:
Left double-click to open image location and exit the app:
```js
// in igconfig.json file

"MouseClickActions": {
  "LeftDoubleClick": {
    "ToggleOn": {
      "Executable": "IG_OpenLocation",
      // action can be chained
      "NextAction": {
        "Executable": "IG_Exit",
      }
    }
  }
},
```

### Example 2:
- First left double-click to view actual size of the image.
- Second left double-click to set the zoom back to Auto zoom.
```js
// in igconfig.json file

"MouseClickActions": {
  "RightDoubleClick": {
    // first click to set zoom to 100%
    "ToggleOn": {
      "Executable": "IG_SetZoom",
      "Arguments": "1"
    },

    // second click to set zoom value to Auto zoom's value
    "ToggleOff": {
      "Executable": "IG_SetZoomMode",
      "Arguments": "AutoZoom"
    }
  }
},
```

### Example 3: 
- First left double-click to enter full screen and hide toolbar.
- Second left double-click to exit full screen and show toolbar.
```js
// in igconfig.json file

"MouseClickActions": {
  "LeftDoubleClick": {
    "ToggleOn": {
      "Executable": "MnuFullScreen",
      "Arguments": "",
      "NextAction": {
        "Executable": "IG_ToggleToolbar",
        "Arguments": false
      }
    },
    "ToggleOff": {
      "Executable": "MnuFullScreen",
      "NextAction": {
        "Executable": "IG_ToggleToolbar",
        "Arguments": true
      }
    }
  }
},
```


### The `Executable` can be:
- name of menu, begins with `Mnu`. You can find all the names in https://github.com/d2phap/ImageGlass/blob/40c22af09e81ac6ffc8b8e0f3114615677ee4c45/v9/ImageGlass/FrmMain.Designer.cs
- name of the function, begins with `IG_`. You can find all functions in https://github.com/d2phap/ImageGlass/blob/40c22af09e81ac6ffc8b8e0f3114615677ee4c45/v9/ImageGlass/FrmMain/FrmMain.IGMethods.cs
- path of an executable file, such as *.bat, *.ps1, *.exe,...


### The list of events for `MouseClickActions`:
https://github.com/d2phap/ImageGlass/blob/40c22af09e81ac6ffc8b8e0f3114615677ee4c45/v9/Components/ImageGlass.Base/Types/MouseEvent.cs#L26-L42
