### ISSUE TITLE
Use "Page Up" and "Page Down" to navigation pages (like Windows 7 Photo Viewer)

### ISSUE THREAD

**Issue by xmha97** [d2phap/ImageGlass#992]
Use `Page Up` and `Page Down` to navigation pages (like Windows 7 Photo Viewer)

![image](https://user-images.githubusercontent.com/23485114/109726046-474eff80-7bc7-11eb-8958-79bc18ade169.png)

Please add this feature:

![image](https://user-images.githubusercontent.com/23485114/109724561-07871880-7bc5-11eb-930b-d56f824974ee.png)

![image](https://user-images.githubusercontent.com/23485114/109724673-2b4a5e80-7bc5-11eb-9629-c0b00f25d624.png)

**Comment by trickshooter** [comment]
Urgently needed here, too!

Wish list:
Configurable PageUpDown = PrevNext**Page(!)**
Desired entry for "igconfig.xml" should read as follows:

(...)
\<Item key="KeyComboActions" value="LeftRight:PanLeftRight;**PageUpDown:PrevNextPage**;SpaceBack:PauseSlideshow;UpDown:PanUpDown;" />
(...)

**Comment by xmha97** [comment]
@d2phap Please add this feature as soon as possible as I need it to view my TIFF documents:
`PageUpDown` : `PrevNextPage`
Thanks.

**Comment by xmha97** [comment]
@d2phap 
Is it possible to add this feature in the new version?

**Comment by xmha97** [comment]
@d2phap Is this feature exist on the ImageGlass v9.0.4?

**Comment by d2phap** [comment]
You can change the default hotkeys since v9.0 beta 2:

```js
// in igconfig.json file
"MenuHotkeys": {
  "MnuViewNextFrame": [
    "PageUp"
  ],
  "MnuViewPreviousFrame": [
    "PageDown"
  ],
}
```

**Comment by xmha97** [comment]
Thanks, you can use these hotkeys by default.
