### ISSUE TITLE
Window moves/resets when switching between photos

### ISSUE THREAD

**Issue by kyyyy4** [d2phap/ImageGlass#993]
### System information:
 - Windows OS version: 10
 - ImageGlass version: 8.0.12.8

### To Reproduce
1. snap window
2. switch image (arrow keys)

### Actual behavior:

window returns to the middle of the screen and resizes on arrow key press

### Expected behavior:

window remains snapped and switches between images

### Screenshots:

no easy way to add the screen capture

**Comment by d2phap** [comment]
Hi @kyyyy4 
Can check with you if  you are in `Window Fit` mode with the option in Settings > Others `Auto-center the window in  Window 
 Fit mode` checked?

**Comment by kyyyy4** [comment]
yeah, I have window fit on, and I've tried Auto-center in Window Fit mode on and off, doesn't seem to make a difference.

**Comment by d2phap** [comment]
I think it's related to #987 which was fixed in the latest build of ImageGlass Moon: https://imageglass.org/moon

**Comment by kyyyy4** [comment]
yup, fixed. thank you very much. great app btw ima drop a donation
