### ISSUE TITLE
Discord server

### ISSUE THREAD

**Issue by pTinosq** [d2phap/ImageGlass#996]
I'm just wondering if there's ever been any thought of starting a Discord server related to ImageGlass?

I think it'd be really beneficial as it'd reinforce a stronger community, allow for instant development feedback, allow for people to get mentioned when a new update is released and it could potentially act as marketing for the software.

**Comment by d2phap** [comment]
Hi @pTinosq 

Thanks for the suggestion. The problem is that we are lack of people, there are only me and Kevin, and we have our own work.
It's good to have a Discord server, but I worry that I cannot response fast enough. 😣
