### ISSUE TITLE
Error on copying a gif image from web browser and pasting in image glass

### ISSUE THREAD

**Issue by Amnesiac9** [d2phap/ImageGlass#998]
### System info:
- ImageGlass version: 8.0.12.8
- OS version: Windows 10 20H2

### Expected behavior:
Open gif image copied from firefox

### Actual behavior:
Gives error: "ImageGlass cannot open this picture because the file appears to be damaged, corrupted or not supported. Magick.net-Q16-OpenMP-x64: improper image header 'C:\Users\NAME\AppData\Local\Temp\ShipperLabel.gif' @ error/gif.c/ReadGIFImage/1028

### Steps to reproduce:
1. Right click>view image on shipping label generated by Amazon in firefox web browser
2. Right Click>Copy the shipping label image
3. try and paste into ImageGlass, error results.

### Other info:
This use to work, just noticed this error for the first time a few weeks ago.

Downloading the same image by saving it to device instead of copying/pasting from firefox fixes the error and imageglass can load the gif file.

**Comment by d2phap** [comment]
Can you attach the GIF file here?

**Comment by fire-eggs** [comment]
I can't repro using other GIF images on the web. For example, here's a link to an Amazon shipping label; it's in GIF format.

[Here's a link to one](https://www.google.com/imgres?imgurl=https%3A%2F%2Fi.pinimg.com%2Foriginals%2F02%2F56%2F38%2F025638874d7579c6dd7a8b5f6acca202.gif&imgrefurl=https%3A%2F%2Fwww.pinterest.com%2Fpin%2F411375747187308049%2F&tbnid=h8roW7B0hQRb4M&vet=12ahUKEwiFmvqswbfvAhWeIN8KHclvBjAQMygDegUIARDGAQ..i&docid=SxS1MJWe3Kq2EM&w=1800&h=1200&q=amazon%20shipping%20label%20gif&ved=2ahUKEwiFmvqswbfvAhWeIN8KHclvBjAQMygDegUIARDGAQ).

Right-click on it, select "copy image". Attempt to "load image from clipboard" in IG.

Succeeds for IG 8.0, latest IG Moon, and latest IG codebase. Windows 7 or Windows 10, Chrome/Brave or Firefox.

**Comment by fire-eggs** [comment]
... but I do have an "oddity" about this ...

1. Copy image in browser
2. Paste into IG
3. Note the image is created in the user's temp folder and is viewable in IG
4. Copy an image in the browser

As soon as I do step 4, the image from step 2 disappears from the temp folder and from IG.
