### ISSUE TITLE
Exiftool feature does not work with chocolatey distributions of exiftool

### ISSUE THREAD

**Issue by laundmo** [d2phap/ImageGlass#999]
### System information:
 - Windows OS version: Windows 10 20H2 19042.804
 - ImageGlass version: 8.0.12.8

### To Reproduce
1. Install exiftool using chocolatey: `choco install exiftool`
2. Start ImageGlass and navigate to the exiftool section
3. observe it claiming the exe is invalid

### Actual behavior:
exiftool.exe as installed by chocolatey is invalid.

### Expected behavior:
The exiftool file to be valid.

### Screenshots:
![image](https://user-images.githubusercontent.com/24855949/110496562-e0b17080-80f5-11eb-94c2-a920e61e95ef.png)

### Additional context:
Possibly caused by chocolatey shims, but also doesn't work with non-shimmed exe.

**Comment by fire-eggs** [comment]
This looks like a known issue (see #927). IG 8.0 is unhappy about the space in the path.

You can either:
- Grab a copy of [IG Moon](https://imageglass.org/moon)
- Change the location of exiftool.exe so there is no space in the path.
